### PR TITLE
Fixed #23816 -- Add support for default deferred fields

### PR DESCRIPTION
**Pull request by manubb**
Ticket: https://code.djangoproject.com/ticket/23816
Already existing PR: #9309

### CODE REVIEW

**Review by charettes — COMMENTED** [review]
FWIW I think this feature would be better implemented by allowing the definition per-manager instead

```python
class User(models.Model):
    username = models.CharField(max_length=50)
    nickname = models.CharField(max_length=50)

    objects = Manager.defer('nickname')
```

What makes `defer` and `only` special over `filter`, `exclude`, `select_related` and other `QuerySet` methods that warrants the inclusion as `Meta` options?

I think it would be preferable to invest time in allowing managers to be defined with lazy queryset method calls resolved at `contribute_to_class` time instead to remove the necessity to define `Manager` subclasses for the sole purpose of overriding `.get_queryset()` to `filter()` or `defer()` from `super().get_queryset()`.

e.g.

```python
class Article(models.Model):
    excerpt = models.CharField(max_length=200)
    text = models.TextField()
    published_at = models.DateTimeField()

    summaries = Manager.defer('text').filter(published_at__lte=timezone.now)
```

feels way more concise and powerful than

```python
class ArticleSummaryManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(published_at__lte=timezone.now)


class Article(models.Model):
    excerpt = models.CharField(max_length=200)
    text = models.TextField()
    published_at = models.DateTimeField()

    summaries = ArticleSummaryManager()

    class Meta:
        defer_fields = ('title', 'user')
```

**Comment by manubb** [comment]
Thanks for your review. AFAIK, a custom manager would not help preventing field loading in `select_related`.
Currenly, adding a call to `defer` is required:
```python
Publication.objects.select_related("user").defer("user__nickname")
```
With this PR content, you can simply write:
```python
Publication.objects.select_related("user")
```

Basically, i would like to have a simple way to tell django: never load these fields unless explicitly requested.
This can be useful for fields used for filtering on the db side (e.g. `tsvectors`) which can have a huge size and are useless on the django side.

**Comment by charettes** [comment]
@manubb thanks for the extra details.

I understand your need but it feels like the point above about _why_ field deferral should be supported  through `Meta` and not other queryset achievable options still stand. For example, you might want to make sure that a field is always `select_related` or that an annotation is always included when `select_related` is used.

I fear we might be heading a slippery slope like we did with `ModelForm.Meta`'s myriad of options and I'd like us to make sure we know we're aware of that. Seeing how `Meta.ordering` has been a constant source of confusion which forced the adoption of hard to document special rules (e.g. wrt to distinct and aggregation) opening this door should not be taken lightly. Anything that has global effects on the base and default managers behavior will have ripple effects through many parts of the ORM.

**Comment by manubb** [comment]
@charettes I took some time to think about this and you are probably right: if we are to add this in `Meta`, there is no clear reasons not to add a bunch of other things. 

In we want to avoid adding data in `Meta`, the other options i can think of are:
- adding a boolean param in the fields indicating that the field should always be default deferred (this is the initial proposal of the ticket) 
- adding an optional method on the model returning the set of default deferred fields (which i think is very close to adding the data in `Meta`)

What is your feeling on this?

**Comment by manubb** [comment]
@charettes ?

**Comment by charettes** [comment]
Hello Manuel, currently in the middle of moving to a new place and I introduced a few regressions in 3.2 which takes most of my "Django" time.

> adding a boolean param in the fields indicating that the field should always be default deferred (this is the initial proposal of the ticket)

I'm personally not against the idea TBH but [another previously core developer thought it might not be appropriate](https://code.djangoproject.com/ticket/23816#comment:4). To me the _characteristic of querying_ point is not as strong as it uses to be if we think of options such as [`related_query_name`](https://docs.djangoproject.com/en/3.2/ref/models/fields/#django.db.models.ForeignKey.related_query_name).

> adding an optional method on the model returning the set of default deferred fields (which i think is very close to adding the data in Meta)

I don't think we've used this pattern before for anything else so that might be alien to the other Model APIs.

---

If you want to reach a larger audience to gather feedback and traction about your proposal I suggest you post to [the developer mailing list](https://docs.djangoproject.com/en/3.2/internals/contributing/bugs-and-features/#requesting-features) as way more folks monitor this channel than Github.

**Comment by manubb** [comment]
@charettes Sorry for being a little pushy. (I had some time last week to move forward on this.)
I'm going to follow your suggestion then!

**Comment by adamchainz** [comment]
> I think it would be preferable to invest time in allowing managers to be defined with lazy queryset method calls resolved at contribute_to_class time instead to remove the necessity to define Manager subclasses for the sole purpose of overriding .get_queryset() to filter() or defer() from super().get_queryset().

I am slightly against this. Django has tons of "shortcuts" to things that are just a couple extra lines of code. This is another such case. One can always introduce

```python
def Manager_with_deferred(deferred):
    class Manager:
        ...
    return Manager

**Comment by manubb** [comment]
@adamchainz Thanks for your review. I provide some more context: this PR add a feature that can not be implemented with custom managers (see this [comment](https://github.com/django/django/pull/14110#issuecomment-797815109)).
Do you think that:
- the deferred fields should be specified in the `Meta` class of a model?
- the deferred fields should be specified with a boolean attribute on the fields?
- django does not need to support default deferred fields?

**Comment by mik3y** [comment]
Been lurking with interest, thought I'd toss out an additional use case, in case it is helpful: I've made a custom field type library which provides [a Timeseries field type](https://github.com/mik3y/django-simple-timeseries). It does so by.. serializing and deserializing a whole bunch of JSON.

Setting aside the larger question of whether using an rdbms for time series data is a particularly wise idea, I'd love to issue guidance to users like, "do the following to ensure your timeseries column is always by default `deferred`".

(On a related note, @manubb if you need any help testing, just let me know, I'd be happy to assist.)

**Pull request closed without merging**
