### PR TITLE
Fixed #35716

### PR DESCRIPTION
**Pull request by domingues**
#### Trac ticket number
ticket-35716

#### Branch description
Replace with tag with firstof tags

#### Checklist
- [x] This PR targets the `main` branch.
- [ ] The commit message is written in past tense, mentions the ticket number, and ends with a period.
- [x] I have checked the "Has patch" ticket flag in the Trac system.
- [ ] I have added or updated relevant tests.
- [ ] I have added or updated relevant docs, including release notes if applicable.
- [ ] I have attached screenshots in both light and dark modes for any UI changes.

### CODE REVIEW

**Comment by nessita** [comment]
Hello @domingues, thank you for this work!

As mentioned in the ticket-35716, I don't think this is the right solution. Not only existing tests are currently failing, but also new tests covering the fix are missing. Also, I think that we should, instead, fix the templates that includes this one to define/pass all required variables (which should be doable).

**Comment by sarahboyce** [comment]
I am really sorry @domingues I hadn't spotted this pr and worked on a solution in https://github.com/django/django/pull/18526
I could have sworn I didn't see a link in Trac but I must have just missed it 🤦‍♀️

**Comment by sarahboyce** [comment]
Merged in #18526 - thank you for raising this to our attention @domingues :star:

**Comment by domingues** [comment]
> I am really sorry @domingues I hadn't spotted this pr and worked on a solution in #18526 I could have sworn I didn't see a link in Trac but I must have just missed it 🤦‍♀️

No problem at all! Happy to see the issue addressed so quickly. Thanks!

**Pull request closed without merging**
