### PR TITLE
Add HttpRequest.get_client_ip() method.

### PR DESCRIPTION
**Pull request by mixkorshun**
Method detects client ip address by ``HTTP_X_FORWARDED_FOR`` and ``REMOTE_ADDR`` headers.

### CODE REVIEW

**Comment by Windsooon** [comment]
Is better to use `REMOTE_ADDR` before `HTTP_X_FORWARDED_FOR` ? 
Since we may not use proxy when use django.
[HTTP_X_FORWARDED_FOR, HTTP_VIA and REMOTE_ADDR Explained](http://www.xpertdeveloper.com/2011/08/http_x_forwarded_for-http_via-and-remote_addr-explained/)

**Comment by mixkorshun** [comment]
I think no, if we trying to detect user ip address.

> So if any user visits your site with the proxy server then REMOTE_ADDRESS is the IP address of the machine which is actually making the request to your website, HTTP_VIA is the IP address of the proxy server and HTTP_X_FORWARDED_FOR is the IP address of the actual user who uses the proxy server.

When user use a proxy server, then he's actual ip address will be stored in ```HTTP_X_FORWARDED_FOR``` header, ```REMOTE_ADDR``` will point at used proxy server.

**Comment by Windsooon** [comment]
You are right, maybe add comment like

use `HTTP_X_FORWARDED_FOR` in case server use proxy.

**Comment by timgraham** [comment]
I have some doubts that we should add this considering the value can't be trusted. Consider past changes like d78cf61c992079a04892abe27c439431e4ef633b.

 By the way, the first step to contributing any patch is to create a [Trac ticket](https://code.djangoproject.com/newticket), not to send a pull request.

**Comment by adamchainz** [comment]
I also have doubts, I've always found it better to roll it into the app after considering the deployment setup.

**Comment by timgraham** [comment]
@mixkorshun, feel free to start a discussion on the [django-developers mailing list](https://groups.google.com/forum/#!forum/django-developers) if you want to try to get a consensus to proceed with this.

**Pull request closed without merging**
