### PR TITLE
Fixed #27755 -- Added ModelAdmin.get_inlines() hook.

### PR DESCRIPTION
**Pull request by twz915**
https://code.djangoproject.com/ticket/27755

### CODE REVIEW

**Comment by timgraham** [comment]
A test, release note, and `versionadded` annotation are needed. See our [patch review checklist](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/submitting-patches/#patch-review-checklist).

**Comment by twz915** [comment]
The ticket has been accepted.
I don't know what should I do to merge the patch to `master` branch, add tests?

**Comment by timgraham** [comment]
Yes, see my previous comment.

**Comment by timgraham** [comment]
Closing due to inactivity.

**Pull request closed without merging**
