### PR TITLE
Bug fix for postgres array indices

### PR DESCRIPTION
**Pull request by yotamofek**
Hey guys, this is my first attempt at contribution, hopefully I'll get it right.

I've encountered a bug when trying to filter on an annotated function call (the function is my own, written in plpgpsql).
The test case I've provided, which fails without my fix, is somewhat odd, but I could not find a general example of an annotation function that returns an array.

I think my fix might be too over-reaching, it can be maybe fixed by surrounding the SQL before the array index in parenthesis.

Thanks!

### CODE REVIEW

**Comment by luzfcb** [comment]
@yotamofek you probably also will need an open a ticket in https://code.djangoproject.com/newticket  and describe what the is problem, how to reproduce it and put a link to this possible solution.

**Comment by timgraham** [comment]
@jarshwah @mjtamlyn -- any ideas about this?

**Comment by mjtamlyn** [comment]
This could certainly generate a rather impressive number of parentheses in queries with many nested expressions. I don't think this is likely to break anything, and would make things quite explicit. However generated SQL like `SELECT (concat((least("a", "b")), " ok?")) FROM ...` is a bit excessive and harder to read.

I wonder whether adding parens more sparsely, such as around [this line's SQL](https://github.com/django/django/blob/bdba0fc195f2e497483abefb8ea1b2d2b071c001/django/contrib/postgres/fields/array.py#L254) (and the corresponding line in the slice transform) would work just as well.

**Comment by jarshwah** [comment]
I agree. Better to target the specific problem rather than wrapping all Func expressions in parens.

**Comment by timgraham** [comment]
Closing due to inactivity. Please send a new PR if you can update it as described in the comments and also please open a ticket.

**Pull request closed without merging**
