### PR TITLE
Fixed #27517 -- Fixed charset param in SimpleTemplateResponse.__init__().

### PR DESCRIPTION
**Pull request by Surgo**
Refs [ticket 27517](https://code.djangoproject.com/ticket/27517)

Call `HttpResponse.__init__` with keyword args.

### CODE REVIEW

**Comment by timgraham** [comment]
Could you please add a regression test?

**Comment by Surgo** [comment]
Sorry, I'll write tests.

**Comment by Surgo** [comment]
@timgraham Added simple test :)

Test failed at dc3f9875cc4d8d0793521f255d3f00bd661e6423,

```
./runtests.py template_tests.test_response.SimpleTemplateResponseTest.test_kwargs
Testing against Django installed in '/Users/kitahara/Repos/django/django' with up to 4 processes
Creating test database for alias 'default'...
Creating test database for alias 'other'...
F
======================================================================
FAIL: test_kwargs (template_tests.test_response.SimpleTemplateResponseTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kitahara/Repos/django/tests/template_tests/test_response.py", line 128, in test_kwargs
    self.assertEqual(response.charset, 'ascii')
AssertionError: 'utf-8' != 'ascii'
- utf-8
+ ascii


----------------------------------------------------------------------
Ran 1 test in 0.030s

FAILED (failures=1)
Destroying test database for alias 'default'...
Destroying test database for alias 'other'...
```

But passed a5500bdd2e4b9574eace24d93b0211df69599deb.

```
./runtests.py template_tests.test_response.SimpleTemplateResponseTest.test_kwargs
Testing against Django installed in '/Users/kitahara/Repos/django/django' with up to 4 processes
Creating test database for alias 'default'...
Creating test database for alias 'other'...
.
----------------------------------------------------------------------
Ran 1 test in 0.033s

OK
Destroying test database for alias 'default'...
Destroying test database for alias 'other'...
```

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
Good, but `content_type` and `status` can be changed back to args without any failures. Are those changes also required? If so, can they be tested?

**Comment by Surgo** [comment]
Sorry, its not required. I'll change back.

**Comment by Surgo** [comment]
@timgraham fixed it :)

**Pull request merged**
