### PR TITLE
Used Node.js 20 for GitHub actions.

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Comment by carltongibson** [comment]
Is it worth using 20? https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by felixxm** [comment]
> Is it worth using 20? https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

18 is the latest LTS, that's why I chose it. But I don't mind using 20 instead.

**Comment by ngnpope** [comment]
Given [this image](https://github.com/nodejs/Release/blob/32b439edd32c6442ddbbd015e897c42a8b52b9d7/schedule.svg), I vote 20 which will be supported for longer than 18.

**Comment by pauloxnet** [comment]
I vote for 20 too.

**Comment by felixxm** [comment]
Updated :+1:

**Review by carltongibson — APPROVED** [review]
Looks good. Thanks

**Comment by felixxm** [comment]
Thanks y'all for reviews :rocket:

**Pull request merged**
