### PR TITLE
Fixed #22822 --Use default locale from settings for get_javascript_catalog (exclude …

### PR DESCRIPTION
**Pull request by gen1us2k**
…hardcoded 'en')

### CODE REVIEW

**Comment by timgraham** [comment]
Hi, could you please create a Trac ticket with a description of your proposed changes? First, check the existing Internationalization tickets. For example, https://code.djangoproject.com/ticket/22822 looks like it could be related.

Tests and documentation updates are likely also required. Thanks!

**Comment by gen1us2k** [comment]
Yes https://code.djangoproject.com/ticket/22822 is related. What to do next? Re-open pull request?
No changes for documentation, because this is a small bugfix.

**Comment by timgraham** [comment]
Is there a reason the change can't or shouldn't be tested? Also the variable names like `en_selected` now seem misleading.

**Comment by gen1us2k** [comment]
Refactored misleading variables.
I don't know how to write tests for this commit changes. I don't see any tests for language_code setting.

**Comment by timgraham** [comment]
There are some tests for the view in `tests/view_tests/tests/test_i18n.py`. I guess you'll need to use `@override_settings(LANGUAGE_CODE='...')` in the new test.

**Comment by gen1us2k** [comment]
I see that test_i18n_language_non_english_default is checks this commit

**Comment by timgraham** [comment]
The idea is to add a test that checks the new functionality that this commit enables so that feature isn't inadvertently broken in the future.

**Comment by gen1us2k** [comment]
Sorry my mistake

**Comment by gen1us2k** [comment]
Added test for last commit. I testing LANGUAGE_CODE='ru', because of I faced to same problem, as described in # 22822

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
Please check the test failures and uncheck "patch needs improvement" on the ticket when they're fixed.

**Comment by gen1us2k** [comment]
Test failures were before my changes.
OK I'll try to fix them

**Comment by timgraham** [comment]
Are you still trying to fix the test failures?

**Comment by gen1us2k** [comment]
Yes

2016-01-23 3:16 GMT+06:00 Tim Graham <notifications@github.com>:

**Comment by timgraham** [comment]
Please send a new PR when tests are passing, thanks!

**Pull request closed without merging**
