### PR TITLE
Fixed #32832 -- Fixed adding BLOB/TEXT nullable field with default on MySQL 8.0.13+.

### PR DESCRIPTION
**Pull request by felixxm**
ticket-32832, ticket-32503, ticket-32425

| operation  | nullable | support for a default value| 
| ------------- | :---: | :---: |
| add field  |  :white_check_mark:  |   :red_circle:  |
| add field  |  -  |   :green_circle: | 
| alter field  | :white_check_mark:  |   :red_circle: | 
| alter field  | -  |   :red_circle: | 

Alternatively we can revert 6b16c91157512587017e9178d066ed1a683e7795 and 5e04e84d67da8163f365e9f5fcd169e2630e2873.

### CODE REVIEW

**Review by omkar-dsd — CHANGES_REQUESTED** [review]
I see that this has been just

**Comment by felixxm** [comment]
> I see that Test Case is just covered for TextField. I think it should be covered for JSONField as well.

IMO we don't need separate tests for all field types all of them are in the same list of limited data types:
https://github.com/django/django/blob/cb6c19749d342c3dc0f97d89ff6887b220cf45b8/django/db/backends/mysql/base.py#L134-L142

@omkar-dsd Can you confirm that this patch works for you?

**Comment by omkar-dsd** [comment]
That sounds fine. Sure I'll check and confirm. This patch can be expected in 3.2.5, right ?

**Comment by felixxm** [comment]
> That sounds fine. Sure I'll check and confirm. This patch can be expected in 3.2.5, right ?

Yes.

**Comment by omkar-dsd** [comment]
Can you raise this patch on top of 3.2.4 so I can test? Or just create a separate branch out of it and let me know.

**Comment by felixxm** [comment]
> Can you raise this patch on top of 3.2.4 so I can test? Or just create a separate branch out of it and let me know.

np, see https://github.com/felixxm/django/tree/3.2.x/issue-32832

**Comment by omkar-dsd** [comment]
Getting this error in 3.2.5 branch:

```python
AttributeError: 'DatabaseSchemaEditor' object has no attribute 'skip_default_on_alter'
```

You need to include the function definition along with it:
https://github.com/django/django/blob/main/django/db/backends/base/schema.py#L269

**Comment by omkar-dsd** [comment]
Also you might have to include those changes which were introduced along with `skip_default_on_alter ` in the same patch.

**Comment by felixxm** [comment]
> Also you might have to include those changes which were introduced along with `skip_default_on_alter ` in the same patch.

I missed one commit, you can check again.

**Comment by omkar-dsd** [comment]
Perfect. Working fine now !

**Review by charettes — APPROVED** [review]
It's hard to believe that this feature was advertised as working without any mention of its caveats given how restrictive they are.

https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-13.html#mysqld-8-0-13-data-types
https://dev.mysql.com/doc/refman/8.0/en/data-type-defaults.html
https://dev.mysql.com/doc/refman/8.0/en/data-type-defaults.html#data-type-defaults-explicit

Thanks for the adjustments @felixxm. Hopefully this is the last surprise in this area.

**Comment by felixxm** [comment]
Thanks both for checking :+1:

**Comment by felixxm** [comment]
Merged in 57bc16b38ec75fc96829f912d57a58d8c6358e8f and fa0433d05f213afe4c67055006320f7aba4c8108.

**Pull request closed without merging**
