### PR TITLE
Fixed typo in docs/intro/tutorial08.txt.

### PR DESCRIPTION
**Pull request by iamcerebrocerberus**

### CODE REVIEW

**Review by smithdc1 — APPROVED** [review]
Lgtm! Thanks for the patch.

**Comment by smithdc1** [comment]
Actually, could you rename the commit to something like `Fixed typo in tutorial08.txt`.

**Comment by felixxm** [comment]
@iamcerebrocerberus Thanks :+1: Welcome aboard :boat:

**Comment by iamcerebrocerberus** [comment]
Thank you @felixxm

**Pull request merged**
