### PR TITLE
Fixed #26124 -- Added missing code formatting to docs headers.

### PR DESCRIPTION
**Pull request by rowanv**

### CODE REVIEW

**Comment by rowanv** [comment]
Jenkins build failed due to added indentation at ref/files/uploads.txt
Fixed and squashed into original commit, pushed to ticket_26124 branch.

**Comment by timgraham** [comment]
Thanks for working on this. Here are some fixes: http://dpaste.com/11DRDF8  Download the raw version and apply it with `patch -p1 -i 11DRDF8.txt`. Do it in a separate commit for easier review.

Please check these files again (and make changes in another commit for easier review):
ref/contrib/gis/functions.txt
ref/contrib/humanize.txt
ref/models/querysets.html
ref/templates/api.html
ref/templates/builtins.html (recheck)

Did you check the `docs/topics/` tree at all? Seems a bit suspicious that there aren't any changes there and after a quick look I found at least a few places that should be changed.

My technique for checking this is to build the docs and then scan the table of contents on the right side of each page looking for anything that should be in block letters but isn't. Hope that helps!

Please uncheck "Patch needs improvement" on the ticket when you update the pull request.

**Comment by rowanv** [comment]
Thanks for the review. Went ahead and added your patch, as well as changes for the requested files. You're right, I'd missed `docs/topics/`, went ahead and added those as well.

**Comment by timgraham** [comment]
merged in a6ef025dfb2a1d1bd23893408eef6d066fb506d9, thanks!

**Pull request closed without merging**
