### PR TITLE
Fixed #31259 -- Added a dark theme in the admin module

### PR DESCRIPTION
**Pull request by mimi89999**
Since this is the new approach using CSS variables, I opened a new PR. It replaces https://github.com/django/django/pull/12444.

### CODE REVIEW

**Review by pope1ni — COMMENTED** [review]
I really like that this is self-contained in one place. That's what CSS variables allow for - much nicer and easy to maintain.

Would you be able to do another round of screenshots for everything, including the open `<select>` elements, etc? I'd like us to make sure that we didn't miss anything from the previous reviews in the previous pull request.

**Comment by matthiask** [comment]
Thanks, this looks great!

The filter_horizontal title doesn't look right yet:
image

Also, I'm not sure whether an `admin.site.enable_dark_mode` flag would make sense (defaulting to `True`) – theming is more work when a dark mode is involved. Anyway, the "Theming support" section of the docs would probably need an addition anyway now https://docs.djangoproject.com/en/dev/ref/contrib/admin/#theming-support

**Comment by mimi89999** [comment]
Screenshot_2021-01-13 2018-12-Staszic_Kurier pdf Change Wydanie Django site admin
Screenshot_2021-01-13 Log in Django site admin
Screenshot_2021-01-13 Select Aktualność to change Django site admin
Screenshot_2021-01-13 Select Aktualność to change Django site admin pagination
Screenshot_2021-01-13 Site administration Django site admin
Screenshot_2021-01-13 Staszic pierwszy w Polsce Change Aktualność Django site admin
Screenshot_2021-01-13 Staszic pierwszy w Polsce Change Aktualność Django site admin bot

The white editor is Summernote. Will need to theme it.

**Comment by mimi89999** [comment]
@matthiask Where do you have `filter_horizontal` in your app? The permissions view looks good:
Screenshot_2021-01-13 michel Change user Django site admin

**Comment by matthiask** [comment]
@mimi89999 Sorry for the noise, that was probably a problem on my side! I may not have had the most up-to-date CSS files then.

**Comment by mimi89999** [comment]
> Also, I'm not sure whether an admin.site.enable_dark_mode flag would make sense

That would complicate things. I would need to move it to a separate CSS file and load it conditionally.

**Review by carltongibson — COMMENTED** [review]
OK, this looks good. Works fine on Firefox, Edge, & Safari. I can't help but think there's tweaks to come, but we can deal with those as they come up; let's get it in people's hands. 

We need to adjust the release note and themeing doc (as @matthiask notes). @mimi89999 Are you up to do that? 

(I think we should just mention that variables are defined for both variations. Folks can define both if they want, or override base.css if they really need to. I don't want to add additional API for that.)

**Comment by knyghty** [comment]
I don't think we need to put it behind a flag, I don't see a compelling reason for this - maybe if you were to provide your own admin theme and not a dark version, but I don't think it's a big problem.

What might be useful is a toggle, so the end user can decide if they want it or not - some people prefer dark themes on some sites but not others. But I would consider that an improvement that can be made later.

**Comment by carltongibson** [comment]
> ... toggle...

[SO has an approach here](https://stackoverflow.com/questions/56300132/how-to-override-css-prefers-color-scheme-setting). _Maybe_ someone can do something along those lines for 4.0+

I wonder if the browser isn't a better place for such a control, rather than every site adding it's own. 🤔 (We might think it's out-of-scope for us...) Anyhow let's see if we can get this in as it is for 3.2

**Comment by mimi89999** [comment]
I think it's more a browser or addon thing to set the theme per site.

**Comment by pope1ni** [comment]
> _Maybe_ someone can do something along those lines for 4.0+

Delaying adding a toggle in 4.0 was going to be my suggestion too.

> I wonder if the browser isn't a better place for such a control, rather than every site adding it's own.

I think it is worth adding as there are times when users (me included) want to override this on a per-site basis. Also browsers don't currently provide a control for doing this. In addition, I have a dark theme enabled for GNOME on Linux, but this doesn't seem to translate to Chromium preferring a dark theme so having a way to override this allows a dark theme to be used by users that have systems that don't seem to support this seamlessly or at all.

**Comment by pope1ni** [comment]
Thanks for the screenshots @mimi89999. Looking good.

I wonder whether we want to [desaturate some of the images/icons](https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/#design) in the dark theme using CSS `filter` properties? The linked article uses `contrast()` and `brightness()`, but `saturate()` could be used instead. This isn't essential to getting this landed, however - @carltongibson has already implied that there may be tweaking to do post-freeze.

**Comment by mimi89999** [comment]
> I have a dark theme enabled for GNOME on Linux, but this doesn't seem to translate to Chromium preferring a dark theme

This is a known issue with Chromium on GNOME. Firefox and Epiphany are not affected:
Capture d’écran du 2021-01-13 12-45-52

**Comment by carltongibson** [comment]
I added docs and release notes but "Allow edits from maintainers" wasn't enabled so merged in b5cef91a91c9dbb697b65ef978a7de0b2c5cf564. Thanks @mimi89999! Nice work 🥇

**Comment by carltongibson** [comment]
@knyghty This is in now, but can I ask you to cast your a11y eye over it for contrast and such?

**Comment by knyghty** [comment]
I had a quick look at it, but only with the eyeball. A few disabled elements are lacking some contrast maybe, but I think the active versions are good, which is probably fine.

I'll try to make time for a deeper delve in the coming days.

**Comment by apollo13** [comment]
Hi @mimi89999 -- compared to your screenshots mine look way off:
Screenshot_2021-01-14 Select group to change Django site admin

If I compare that with your first screenshot you had the headers in the sidebar as white, mine are dark on dark?

Also: Is there any easy way I can simply disable dark mode on my site? Usually we give users the choice if they want to use new features in Django. It is certainly easier to simply not use a new class etc, but I think it should be possible to disable this.

**Comment by carltongibson** [comment]
> Also: Is there any easy way I can simply disable dark mode on my site? Usually we give users the choice if they want to use new features in Django. It is certainly easier to simply not use a new class etc, but I think it should be possible to disable this.

Currently, you'd need to set the extra_head CSS block variables back to the _light_ values. 

We could move to a separate stylesheet, which you could then override with an empty file. 🤔 

Adding a JS toggle was discussed above. But, surely, the powers that be don't intend every site to add JS for this?  — Ideally it should be controlled by `prefers-color-scheme` but I don't know if browsers let you set that per site.

**Comment by knyghty** [comment]
@carltongibson I've had chance to look over it, a few things...

Not a11y related at all, but the nav sidebar seems really wrong. The border doesn't look right, there is a bright white border on the top/bottom/left in Firefox. There is this:

```css
border-right: 1px solid var(--hairline-color);
```

I really think it should be:
```css
border: 1px solid var(--hairline-color);
```

Also, some colours are too vibrant (icons, delete button), but this has been mentioned before.

The contrast between the almost white text and lighter shade of blue (login page heading, main header) is apparently too low. I'm not sure it matters that much, I think dark theme users are expecting a lower-contrast experience. However, it's pretty close to being at AA, so maybe the blue can be changed a bit.

Probably not enough contrast on the "History", "Add Foo" / etc. buttons. I also think it looks a bit ugly.

The help text is good, but the timezone warning is unreadable:

Screenshot 2021-01-19 at 18 02 34

Action select looks very bad on Firefox at least:

Screenshot 2021-01-19 at 18 08 33

It looks like this can be fixed by removing `background: none` in the CSS.

The contrast of the text for disabled actions on filter horizontal widgets is too low ("choose all" / "remove all" / the arrows). Since they're disabled it's maybe okay.

There are a few other things I can think of, but they are probably a bit too opinionated.

**Comment by mimi89999** [comment]
I agree it should be `border: 1px solid var(--hairline-color);`

> Probably not enough contrast on the "History", "Add Foo" / etc. buttons. I also think it looks a bit ugly.

The color is in the icons. I don't quite know what can be done to make them themable.

> The help text is good, but the timezone warning is unreadable:

Sorry. I did not test that. Didn't even know that this warning exists.

@knyghty Will you open a PR with fixes for those issues? Could you please tag me inside it?

**Comment by knyghty** [comment]
For sure, hopefully tomorrow 👍 

I see the + in the add button is an SVG, so it will always be white unless we inline it, but you can change the text and background colours - maybe it's enough. It would be nice to able to change the icon colour as well, but I don't see an easy solution there.

**Comment by pope1ni** [comment]
> The color is in the icons. I don't quite know what can be done to make them themable.

See my [comment](https://github.com/django/django/pull/13880#issuecomment-759394701) above.



> Action select looks very bad on Firefox at least:
> 
> Screenshot 2021-01-19 at 18 08 33
> 
> It looks like this can be fixed by removing `background: none` in the CSS.

I mentioned a potential solution to this for Chrome in another [comment](https://github.com/django/django/pull/12444#issuecomment-678336529).

**Comment by knyghty** [comment]
I guess I should link the PR with some tweaks from here too: https://github.com/django/django/pull/13919

**Pull request closed without merging**
