### PR TITLE
Fix name and prototype for cached_property.__get__ to match Python docs

### PR DESCRIPTION
**Pull request by funkybob**

### CODE REVIEW

**Comment by timgraham** [comment]
@oinopion, okay with you? (refs b88abd684041ffa66bfe445e1ac26164e803d488)

**Comment by oinopion** [comment]
@funkybob @timgraham LGTM.

**Comment by timgraham** [comment]
Curtis, should we make this change for all `__get__` methods? e.g.
```
django/db/models/fields/related.py:    def __get__(self, instance, instance_type=None):
django/db/models/fields/related.py:    def __get__(self, instance, instance_type=None):
django/db/models/fields/related.py:    def __get__(self, instance, instance_type=None):
django/contrib/contenttypes/fields.py:    def __get__(self, instance, instance_type=None):

django/db/models/fields/subclassing.py:    def __get__(self, obj, type=None):
django/db/models/manager.py:    def __get__(self, instance, type=None):
django/db/models/manager.py:    def __get__(self, instance, type=None):
django/db/models/manager.py:    def __get__(self, instance, type=None):
django/contrib/gis/db/models/proxy.py:    def __get__(self, obj, type=None):
```

**Comment by timgraham** [comment]
It seems the Python docs aren't entirely consistent. Here's an example that shows a different signature: https://docs.python.org/3/howto/descriptor.html#descriptor-protocol

There's [at least one place in Django](https://github.com/django/django/blob/1bbca7961cee20c4ddd453a7d74d316e84f4bbb5/django/db/models/fields/related.py#L918) where we call a descriptor without the second argument.

**Comment by timgraham** [comment]
Curtis, any thoughts on how to proceed here?

**Comment by funkybob** [comment]
I'm not pushing this ticket hard... it just seemed like an easy cleanup, but clearly isn't.

Is it worth the effort to at least be consistent internally with our signature?

**Comment by timgraham** [comment]
I wouldn't mind. Which one do you think we should use?

**Comment by funkybob** [comment]
Well:
- "instance_type" is explicit
- "cls" is a common convention for passing a class
- "owner" is in the docs {but so are others}
- and "type" I think is a bit confusing...

So... my preference, upon reflection, would be:

```
def __get__(self, instance, cls=None):
```

**Comment by timgraham** [comment]
Maybe you could quickly run your proposal by the mailing list.

**Comment by timgraham** [comment]
Updated in https://github.com/django/django/pull/5482.

**Pull request closed without merging**
