### PR TITLE
Fixed #34985 -- Fixed GeneratedFields.contribute_to_class() crash when apps are not populated.

### PR DESCRIPTION
**Pull request by felixxm**
ticket-34985

Thanks Paolo Melchiorre for the report.

Regression in f333e3513e8bdf5ffeb6eeb63021c230082e6f95.

### CODE REVIEW

**Comment by felixxm** [comment]
@pauloxnet Does it work for you?

**Comment by pauloxnet** [comment]
I'm going to try it locally ASAP

**Comment by pauloxnet** [comment]
If I use this branch in my 'samples' local project with multi-table inheritance models described in the ticket and don't see the confusing error reported before.

```python
from django.db import models
from django.db.models import Value
from django.db.models.functions import Concat

class Person(models.Model):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)

class Profile(Person):
    email = models.EmailField()
    display_name = models.GeneratedField(
        expression=Concat("first_name", Value(" "), "last_name", Value(" "), "email",),
        db_persist=True,
        output_field=models.TextField(),
    )
```

However, strangely the `makemigrations` command succeeds, also if I'm forcing the Generated Field to use a column from another table:

```console
$ python3 -m manage makemigrations
Migrations for 'samples':
  samples/migrations/0010_person_profile.py
    - Create model Person
    - Create model Profile
```

And then inevitably I see an error if I try to ask for the SQL code:

```console
$ python3 -m manage sqlmigrate samples 0010
```

```pycon
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/paulox/Projects/generatedfields/manage.py", line 22, in <module>
    main()
  File "/home/paulox/Projects/generatedfields/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/paulox/Projects/django/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/paulox/Projects/django/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/paulox/Projects/django/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/paulox/Projects/django/django/core/management/commands/sqlmigrate.py", line 38, in execute
    return super().execute(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paulox/Projects/django/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paulox/Projects/django/django/core/management/commands/sqlmigrate.py", line 80, in handle
    sql_statements = loader.collect_sql(plan)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paulox/Projects/django/django/db/migrations/loader.py", line 381, in collect_sql
    state = migration.apply(state, schema_editor, collect_sql=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paulox/Projects/django/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/home/paulox/Projects/django/django/db/migrations/operations/models.py", line 96, in database_forwards
    schema_editor.create_model(model)
  File "/home/paulox/Projects/django/django/db/backends/base/schema.py", line 482, in create_model
    sql, params = self.table_sql(model)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/paulox/Projects/django/django/db/backends/base/schema.py", line 218, in table_sql
    definition, extra_params = self.column_sql(model, field)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paulox/Projects/django/django/db/backends/base/schema.py", line 367, in column_sql
    " ".join(
  File "/home/paulox/Projects/django/django/db/backends/base/schema.py", line 336, in _iter_column_sql
    yield self._column_generated_sql(field)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paulox/Projects/django/django/db/backends/base/schema.py", line 429, in _column_generated_sql
    expression_sql, params = field.generated_sql(self.connection)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paulox/Projects/django/django/db/models/fields/generated.py", line 58, in generated_sql
    resolved_expression = self.expression.resolve_expression(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paulox/Projects/django/django/db/models/expressions.py", line 978, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paulox/Projects/django/django/db/models/expressions.py", line 978, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paulox/Projects/django/django/db/models/expressions.py", line 857, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paulox/Projects/django/django/db/models/sql/query.py", line 2009, in resolve_ref
    raise FieldError(
django.core.exceptions.FieldError: Joined field references are not permitted in this query
```

Things are better than before, so I confirm the fix worked. But can be better to avoid migrations creations in cases like this?
Or that's something to do in Django 5.1

**Comment by felixxm** [comment]
> Or that's something to do in Django 5.1

We could add a [system check](https://code.djangoproject.com/ticket/34985#comment:1) for `GeneratedField` references (similar to what we have for indexes and constraints), but IMO, this is a cleanup that we can add in Django 5.1. The current `FieldError` seems to be clear enough that it should not be considered a 5.0 release blocker.

**Review by nessita — APPROVED** [review]
LGTM

**Review by pauloxnet — APPROVED** [review]
LGTM

**Comment by felixxm** [comment]
Thanks for reviews :100:

**Pull request merged**
