### PR TITLE
Fixed #25718 -- Fixed JSONField isnull lookups

### PR DESCRIPTION
**Pull request by Stranger6667**
Initially it was only about JSONField from `django.contrib.postgres`, but in fact, an ability to query `None` values might be helpful.
In current trunk there is only one case for `None` - convert it to SQL's `NULL` , but with some complex types it is also possible to have another options of `None` conversion. In this case - JSON's `null`.
At that moment I'm not completely sure about `isnull` lookup usage, because it corresponds to `IS NULL` in SQL, which is an other concept rather then `null` in JSON. Please give an advise.
Thanks.

### CODE REVIEW

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
@jarshwah @mjtamlyn -- could you advise here?

**Comment by mjtamlyn** [comment]
I think combining use of isnull like this could be confusing - SQL `NULL` and json `null` are definitely different - the latter is better considered the equivalent of `0` for an integer field - it's still "falsy", but it's a specified value.

It's important to note the following SQL differences as well:

```
marc=# select ('{"a": null}'::jsonb -> 'c') is NULL;
 ?column?
----------
 t
(1 row)

marc=# select ('{"a": null}'::jsonb -> 'a') is NULL;
 ?column?
----------
 f
(1 row)
marc=# select ('{"a": null}'::jsonb -> 'c') = 'null'::jsonb;
 ?column?
----------

(1 row)
marc=# select ('{"a": null}'::jsonb -> 'a') = 'null'::jsonb;
 ?column?
----------
 t
(1 row)
```

So you can use `-> key is NULL` as an alternative to `__haskey`. This would make the change backwards incompatible. This means that for a JSON field at the moment `field__k__isnull=True` and `field__k=None` are actually different.

Adding a special JSON null transform seems a bit pointless assuming that `=None` does work as you'd expect.

**Comment by timgraham** [comment]
Closing due to inactivity.

**Pull request closed without merging**
