### PR TITLE
Refs #24227 -- Removed ManyToManyField special casing in model_to_dict().

### PR DESCRIPTION
**Pull request by timgraham**
See https://code.djangoproject.com/ticket/24227#comment:17

### CODE REVIEW

**Comment by charettes** [comment]
This change makes sense to me. I suppose the `instance.pk` check is not necessary anymore because the ORM is smart enough not to execute a query in this case?

**Comment by timgraham** [comment]
No, but the coverage report indicates the removed `if instance.pk is None` line never evaluates to True.

**Comment by charettes** [comment]
LGTM

**Comment by collinanderson** [comment]
Nice, yeah, I'm hoping this doesn't cause _other_ backwards compatibility issues, but I think this is good long-term. :)

**Pull request merged**
