### PR TITLE
Refs #29478 -- Doc'd how to use cached_property under the mangled name.

### PR DESCRIPTION
**Pull request by sir-sigurd**
https://code.djangoproject.com/ticket/29478

### CODE REVIEW

**Comment by timgraham** [comment]
Is the idea to merge this for older Django versions and then modify the note as part of https://github.com/django/django/pull/10033?

**Comment by sir-sigurd** [comment]
Yes, and in #10033 we could make warning (error?) provide the link to this text.

**Comment by timgraham** [comment]
Could you check that my edits are correct?

**Comment by sir-sigurd** [comment]
@timgraham LTGM

**Pull request merged**
