### PR TITLE
Refs #34381 -- Fixed isolation of MigrateTests.test_migrate_fake_initial().

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Comment by smithdc1** [comment]
If I just run the `migrations` tests before this patch I saw `FAILED (failures=2, errors=3, skipped=1)` with this patch that's redcued to `FAILED (failures=1, skipped=1)`.

The failing test is the one that's been adjusted in this patch. I started to have a bit of an investigation but was unsure how to make much progress, sorry. 

```
======================================================================
FAIL: test_migrate_fake_initial (migrations.test_commands.MigrateTests.test_migrate_fake_initial)
--fake-initial only works if all tables created in the initial
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.752.0_x64__qbz5n2kfra8p0\Lib\unittest\case.py", line 57, in testPartExecutor
    yield
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.752.0_x64__qbz5n2kfra8p0\Lib\unittest\case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.752.0_x64__qbz5n2kfra8p0\Lib\unittest\case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\smith\projects\django\django\test\utils.py", line 443, in inner
    return func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\smith\projects\django\tests\migrations\test_commands.py", line 185, in test_migrate_fake_initial
    self.assertTableNotExists("migrations_author", using="other")
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\smith\projects\django\tests\migrations\test_base.py", line 41, in assertTableNotExists
    self.assertNotIn(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.752.0_x64__qbz5n2kfra8p0\Lib\unittest\case.py", line 1147, in assertNotIn
    self.fail(self._formatMessage(msg, standardMsg))
    ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.752.0_x64__qbz5n2kfra8p0\Lib\unittest\case.py", line 703, in fail
    raise self.failureException(msg)
    ^^^^^^^^^^^^^^^^^
AssertionError: 'migrations_author' unexpectedly found in ['auth_group', 'auth_group_permissions', 'auth_permission', 'auth_user', 'auth_user_groups', 'auth_user_user_permissions', 'django_admin_log', 'django_content_type', 'django_migrations', 'django_session', 'django_site', 'migrations_author', 'migrations_modelwithcustombase', 'migrations_unmigratedmodel']
```

**Comment by felixxm** [comment]
> If I just run the `migrations` tests before this patch I saw `FAILED (failures=2, errors=3, skipped=1)` with this patch that's redcued to `FAILED (failures=1, skipped=1)`.
> 
> The failing test is the one that's been adjusted in this patch. I started to have a bit of an investigation but was unsure how to make much progress, sorry.

This is suspicious :thinking: Do you share the same database for `default` and `other`?

**Comment by felixxm** [comment]
If you share the same database then we can close ticket-34381 as "invalid", see [docs](https://docs.djangoproject.com/en/4.1/internals/contributing/writing-code/unit-tests/#using-another-settings-module):
> _"A database with the alias **other**. The **other** database is used to test that queries can be directed to different databases. This database should use the same backend as the **default**, and it must have a different name."_

I'd still merge this PR as it fixes as isolation issue.

**Comment by smithdc1** [comment]
Things I learnt! As well as the database alias the "NAME" is also important. 

This seems to have fixed the `migration` tests and leaves the following:

```
======================================================================
ERROR: test_empty_result_set (postgres_tests.test_aggregates.TestGeneralAggregate.test_empty_result_set) [<object object at 0x0000019F0B660DC0>] (aggregation=(BitXor(F(integer_field)), None))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.752.0_x64__qbz5n2kfra8p0\Lib\unittest\case.py", line 57, in testPartExecutor
    yield
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.752.0_x64__qbz5n2kfra8p0\Lib\unittest\case.py", line 538, in subTest
    yield
  File "C:\Users\smith\projects\django\tests\postgres_tests\test_aggregates.py", line 106, in test_empty_result_set
    values = AggregateTestModel.objects.none().aggregate(
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\smith\projects\django\django\db\models\query.py", line 571, in aggregate
    self._validate_values_are_expressions(
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\smith\projects\django\django\db\models\query.py", line 1945, in _validate_values_are_expressions
    raise TypeError(
TypeError: QuerySet.aggregate() received non-expression(s): (BitXor(F(integer_field)), None).

======================================================================
ERROR: test_ops_class (indexes.tests.SchemaIndexesPostgreSQLTests.test_ops_class)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\smith\projects\django\django\db\backends\utils.py", line 87, in _execute
    return self.cursor.execute(sql)
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\smith\projects\django\.venv\Lib\site-packages\psycopg\cursor.py", line 723, in execute
    raise ex.with_traceback(None)
    ^^^^^^^^^^^^^^^^^
psycopg.errors.DuplicateTable: relation "test_ops_class" already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.752.0_x64__qbz5n2kfra8p0\Lib\unittest\case.py", line 57, in testPartExecutor
    yield
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.752.0_x64__qbz5n2kfra8p0\Lib\unittest\case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.752.0_x64__qbz5n2kfra8p0\Lib\unittest\case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\smith\projects\django\tests\indexes\tests.py", line 191, in test_ops_class
    editor.add_index(IndexedArticle2, index)
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\smith\projects\django\django\db\backends\postgresql\schema.py", line 324, in add_index
    self.execute(
  File "C:\Users\smith\projects\django\django\db\backends\postgresql\schema.py", line 45, in execute
    return super().execute(sql, params)
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\smith\projects\django\django\db\backends\base\schema.py", line 201, in execute
    cursor.execute(sql, params)
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\smith\projects\django\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\smith\projects\django\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\smith\projects\django\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\smith\projects\django\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\smith\projects\django\django\db\backends\utils.py", line 87, in _execute
    return self.cursor.execute(sql)
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\smith\projects\django\.venv\Lib\site-packages\psycopg\cursor.py", line 723, in execute
    raise ex.with_traceback(None)
    ^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "test_ops_class" already exists

======================================================================
FAIL: test_foreign_data_wrapper (inspectdb.tests.InspectDBTransactionalTests.test_foreign_data_wrapper)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.752.0_x64__qbz5n2kfra8p0\Lib\unittest\case.py", line 57, in testPartExecutor
    yield
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.752.0_x64__qbz5n2kfra8p0\Lib\unittest\case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.752.0_x64__qbz5n2kfra8p0\Lib\unittest\case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\smith\projects\django\tests\inspectdb\tests.py", line 615, in test_foreign_data_wrapper
    self.assertIn(foreign_table_model, output)
    ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.752.0_x64__qbz5n2kfra8p0\Lib\unittest\case.py", line 1140, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
    ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.752.0_x64__qbz5n2kfra8p0\Lib\unittest\case.py", line 703, in fail
    raise self.failureException(msg)
    ^^^^^^^^^^^^^^^^^
AssertionError: 'class InspectdbIrisForeignTable(models.Model):' not found in '# This is an auto-generated Django model module.\n# You\'ll have to do the following manually to clean this up:\n#   * Rearrange models\' order\n#   * Make sure each model has one field with primary_key=True\n#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior\n#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table\n# Feel free to rename the models, but don\'t rename db_table values or field names.\nfrom django.db import models\n\n\nclass InspectdbCharfielddbcollation(models.Model):\n    char_field = models.CharField(max_length=10, db_collation=\'sv-x-icu\')\n\n    class Meta:\n        managed = False\n        db_table = \'inspectdb_charfielddbcollation\'\n\n\nclass InspectdbCharfieldunlimited(models.Model):\n    char_field = models.CharField()\n\n    class Meta:\n        managed = False\n        db_table = \'inspectdb_charfieldunlimited\'\n\n\nclass InspectdbColumntypes(models.Model):\n    big_int_field = models.BigIntegerField()\n    bool_field = models.BooleanField()\n    null_bool_field = models.BooleanField(blank=True, null=True)\n    char_field = models.CharField(max_length=10)\n    null_char_field = models.CharField(max_length=10, blank=True, null=True)\n    date_field = models.DateField()\n    date_time_field = models.DateTimeField()\n    decimal_field = models.DecimalField(max_digits=6, decimal_places=1)\n    email_field = models.CharField(max_length=254)\n    file_field = models.CharField(max_length=100)\n    file_path_field = models.CharField(max_length=100)\n    float_field = models.FloatField()\n    int_field = models.IntegerField()\n    gen_ip_address_field = models.GenericIPAddressField()\n    pos_big_int_field = models.BigIntegerField()\n    pos_int_field = models.IntegerField()\n    pos_small_int_field = models.SmallIntegerField()\n    slug_field = models.CharField(max_length=50)\n    small_int_field = models.SmallIntegerField()\n    text_field = models.TextField()\n    time_field = models.TimeField()\n    url_field = models.CharField(max_length=200)\n    uuid_field = models.UUIDField()\n\n    class Meta:\n        managed = False\n        db_table = \'inspectdb_columntypes\'\n\n\nclass InspectdbDbcomment(models.Model):\n    rank = models.IntegerField(db_comment="\'Rank\' column comment")\n\n    class Meta:\n        managed = False\n        db_table = \'inspectdb_dbcomment\'\n        db_table_comment = \'Custom table comment\'\n\n\nclass InspectdbDigitsincolumnname(models.Model):\n    number_123 = models.CharField(db_column=\'123\', max_length=11)  # Field renamed because it wasn\'t a valid Python identifier.\n    number_4extra = models.CharField(db_column=\'4extra\', max_length=11)  # Field renamed because it wasn\'t a valid Python identifier.\n    number_45extra = models.CharField(db_column=\'45extra\', max_length=11)  # Field renamed because it wasn\'t a valid Python identifier.\n\n    class Meta:\n        managed = False\n        db_table = \'inspectdb_digitsincolumnname\'\n\n\nclass InspectdbForeignkeytofield(models.Model):\n    to_field_fk = models.ForeignKey(\'InspectdbPeoplemoredata\', models.DO_NOTHING, to_field=\'people_unique_id\')\n\n    class Meta:\n        managed = False\n        db_table = \'inspectdb_foreignkeytofield\'\n\n\nclass InspectdbFuncuniqueconstraint(models.Model):\n    name = models.CharField(max_length=255)\n    rank = models.IntegerField()\n\n    # A unique constraint could not be introspected.\n    class Meta:\n        managed = False\n        db_table = \'inspectdb_funcuniqueconstraint\'\n# Unable to inspect table \'inspectdb_iris_foreign_table\'\n# The error was: could not stat file "nul": Invalid argument\n\n\nclass InspectdbJsonfieldcolumntype(models.Model):\n    json_field = models.JSONField()\n    null_json_field = models.JSONField(blank=True, null=True)\n\n    class Meta:\n        managed = False\n        db_table = \'inspectdb_jsonfieldcolumntype\'\n\n\nclass InspectdbMessage(models.Model):\n    from_field = models.ForeignKey(\'InspectdbPeople\', models.DO_NOTHING, db_column=\'from_id\')  # Field renamed because it was a Python reserved word.\n    author = models.ForeignKey(\'InspectdbPeople\', models.DO_NOTHING, related_name=\'inspectdbmessage_author_set\')\n\n    class Meta:\n        managed = False\n        db_table = \'inspectdb_message\'\n\n\nclass InspectdbPeople(models.Model):\n    name = models.CharField(max_length=255)\n    parent = models.ForeignKey(\'self\', models.DO_NOTHING)\n\n    class Meta:\n        managed = False\n        db_table = \'inspectdb_people\'\n\n\nclass InspectdbPeopledata(models.Model):\n    people_pk = models.OneToOneField(InspectdbPeople, models.DO_NOTHING, primary_key=True)\n    ssn = models.CharField(max_length=11)\n\n    class Meta:\n        managed = False\n        db_table = \'inspectdb_peopledata\'\n\n\nclass InspectdbPeoplemoredata(models.Model):\n    people_unique = models.OneToOneField(InspectdbPeople, models.DO_NOTHING)\n    message = models.ForeignKey(InspectdbMessage, models.DO_NOTHING, blank=True, null=True)\n    license = models.CharField(max_length=255)\n\n    class Meta:\n        managed = False\n        db_table = \'inspectdb_peoplemoredata\'\n\n\nclass InspectdbSpecialTableName(models.Model):\n    field = models.IntegerField()\n    field_field = models.IntegerField(db_column=\'Field_\')  # Field name made lowercase. Field renamed because it ended with \'_\'.\n    field_field_0 = models.IntegerField(db_column=\'Field__\')  # Field name made lowercase. Field renamed because it contained more than one \'_\' in a row. Field renamed because it ended with \'_\'. Field renamed because of name conflict.\n    field_field_1 = models.IntegerField(db_column=\'__field\')  # Field renamed because it contained more than one \'_\' in a row. Field renamed because it started with \'_\'. Field renamed because of name conflict.\n    prc_x = models.IntegerField(db_column=\'prc(%) x\')  # Field renamed to remove unsuitable characters.\n    tamaño = models.IntegerField()\n\n    class Meta:\n        managed = False\n        db_table = \'inspectdb_special.table name\'\n\n\nclass InspectdbTextfielddbcollation(models.Model):\n    text_field = models.TextField(db_collation=\'sv-x-icu\')\n\n    class Meta:\n        managed = False\n        db_table = \'inspectdb_textfielddbcollation\'\n\n\nclass InspectdbUniquetogether(models.Model):\n    field1 = models.IntegerField()\n    field2 = models.CharField(max_length=10)\n    from_field = models.IntegerField(db_column=\'from\')  # Field renamed because it was a Python reserved word.\n    non_unique_column = models.IntegerField(db_column=\'non__unique_column\')  # Field renamed because it contained more than one \'_\' in a row.\n    non_unique_column_0 = models.IntegerField(db_column=\'non_unique__column\')  # Field renamed because it contained more than one \'_\' in a row. Field renamed because of name conflict.\n\n    class Meta:\n        managed = False\n        db_table = \'inspectdb_uniquetogether\'\n        unique_together = ((\'from_field\', \'field1\'), (\'non_unique_column\', \'non_unique_column_0\'), (\'field1\', \'field2\'),)\n'
```

**Comment by felixxm** [comment]
> Things I learnt! As well as the database alias the "NAME" is also important.
> 
> This seems to have fixed the `migration` tests and leaves the following:

Great! Please leave a comment on the ticket :notebook: 

Can you approve this PR on behalf of Django Triage & Review Team? :wink:

**Review by smithdc1 — APPROVED** [review]
Thank you @felixxm !

**Pull request merged**
