### PR TITLE
Refs #30420 -- Added request process check routine when runserver request is processing

### PR DESCRIPTION
**Pull request by bunseokbot**
Added request process check routine when the request is processing

https://code.djangoproject.com/ticket/30420

### CODE REVIEW

**Comment by apollo13** [comment]
autoreload is a weird place for the lock, I think it should be in core.handlers if at all. Btw is there any chance we can do this so it only affects the development server?

**Comment by apollo13** [comment]
You can most likely verify that this PR is broken by creating a view which sleeps for 1000 seconds and then try hitting __any__ other view.

**Comment by felixxm** [comment]
This change locks `servers` tests.

**Comment by felixxm** [comment]
Closing due to hanging tests.

**Pull request closed without merging**
