### PR TITLE
Refs #31040 -- Doc'd Python 3.9 compatibility.

### PR DESCRIPTION
**Pull request by felixxm**
~Checking Django 2.2 and 3.0 is in progress.~

### CODE REVIEW

**Comment by felixxm** [comment]
Django 3.0 checked :heavy_check_mark: .

**Comment by felixxm** [comment]
Django 2.2 checked :heavy_check_mark:.

**Review by carltongibson — APPROVED** [review]
Super. That's quite exciting. Thanks!

**Comment by felixxm** [comment]
Thanks for checking.

**Pull request merged**
