### PR TITLE
Fixed #30506 -- Fixed crash of autoreloader when path contains null characters.

### PR DESCRIPTION
**Pull request by orf**
Ticket: https://code.djangoproject.com/ticket/30506

### CODE REVIEW

**Comment by felixxm** [comment]
@orf Thanks for this patch :+1: I pushed minor edits.

@kezabelle Can you confirm that this patch fixes "null bytes" issue for you?

**Comment by kezabelle** [comment]
Hi @felixxm. Thanks for pinging me. I never figured out how to actually reproduce the problem consistently, but catching the `ValueError` should certainly suppress the problem (at the expense of incorrectly not tracking the given filename)

**Comment by felixxm** [comment]
@kezabelle Thanks :+1:  I don't think that tracking these files is even possible, so this fix looks good to me.

**Comment by felixxm** [comment]
buildbot

**Comment by liampauling** [comment]
Thanks for fixing this so quickly!

Just tested locally off the 2.2 stable branch and no issues.

**Pull request merged**
