### PR TITLE
Fixed #28706 -- Moved AuthenticationForm error to a method for reuse.

### PR DESCRIPTION
**Pull request by jdufresne**
https://code.djangoproject.com/ticket/28706

### CODE REVIEW

**Comment by timgraham** [comment]
I'd be inclined to use this name (or perhaps a `invalid_login_error` property) -- did you check if there's any similar convention elsewhere?
```
def get_invalid_login_error(self):
    # For subclasses that want to raise this error.
```
Adding a test would reduce a risk that it's refactored away.

**Comment by jdufresne** [comment]
Thanks for the review. I have made the suggested edits.

* Renamed method to `get_invalid_login_error()`
* Added a test for my use case

**Comment by timgraham** [comment]
I was thinking that a unit test for `get_invalid_login_error()` (checking the return value in some fashion) is sufficient.

**Comment by jdufresne** [comment]
Updated the test based on the suggestion. Now tests the return value exactly. Thanks.

**Pull request merged**
