### PR TITLE
Preferred dict literal over built-in.

### PR DESCRIPTION
**Pull request by jdufresne**
I noticed some uses of `dict()` that could easily use a literal instead. Not sure if this was intentional or not. Let me know if this kind of clean up is welcome. If you think this should go through a Trac ticket, let me know and I'll create one.

### CODE REVIEW

**Comment by srinivasreddy** [comment]
I think this should be welcomed. literal creation is faster than dict builtin function.

**Comment by raminfp** [comment]
Literal is much faster,

```
>python -m timeit "d = dict(a=1, b=2, c=3)"
1000000 loops, best of 3: 0.906 usec per loop
>python -m timeit "d = {'a':1, 'b':2, 'c':3}"
1000000 loops, best of 3: 0.423 usec per loop
```

**Comment by timgraham** [comment]
Fine by me, I'll keep it in mind for future reviews. Did you finish looking? A ticket isn't needed.

**Comment by jdufresne** [comment]
> Did you finish looking?

Yup. Those are all the simple key/value arguments to `dict()` I found. Thanks.

**Pull request merged**
