### PR TITLE
Fixed #31524 -- Removed minified static assets from the admin.

### PR DESCRIPTION
**Pull request by jdufresne**
https://code.djangoproject.com/ticket/31524

### CODE REVIEW

**Comment by jdufresne** [comment]
Thanks Carlton. I added a blurb to the release notes please let me know if it aligns with what you have in mind or if you have any wording suggestions.

**Comment by jdufresne** [comment]
buildbot, test on selenium.

**Comment by jdufresne** [comment]
I can reproduce the test failures locally. I will investigate them.

**Comment by jdufresne** [comment]
buildbot, test on selenium.

**Comment by jdufresne** [comment]
Test failures fixed.

**Comment by carltongibson** [comment]
buildbot, test on selenium.

**Pull request merged**
