### PR TITLE
Fixed #25598 -- Support for SCRIPT_NAME in STATIC_URL and MEDIA_URL

### PR DESCRIPTION
**Pull request by kottenator**
https://code.djangoproject.com/ticket/25598

Build static and media URLs using SCRIPT_NAME prefix.
The prefix should be added when displaying the URL
and omitted when serving the URL.

### CODE REVIEW

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by kottenator** [comment]
Finally, all the checks passed! :)

I can squash my PR-related commits and create another PR, but I'd do it later, after change requests and remarks.

**Comment by timgraham** [comment]
You can squash commits and force push to the same branch so as not to need to create a new pull request. "Fixed #..." is the correct format unless this doesn't fully resolve the ticket in which case "Refs" is used.

Any documentation changes required? At least a mention in the release notes under "Backwards-incompatible changes" as discussed on the ticket is required.

I'm skeptical that the minor test changes you made so far are sufficient to cover all the code changes.

**Comment by kottenator** [comment]
Thanks for the hint about force push, I'll do that at the end. 
Yes, additional tests are required, I'll add them.

**Comment by naphthalene** [comment]
Has this been abandoned?

**Comment by kottenator** [comment]
> Has this been abandoned?

No, I haven't forgot about it. I was just extremely busy _and maybe a bit lazy_ :)
I'll update & finish this PR hopefully until the end of the next week.

**Comment by naphthalene** [comment]
Sounds good, let me know if you need a hand :)

**Comment by kottenator** [comment]
Thanks, Pavel!

**Comment by jonashaag** [comment]
I'd like to help getting this done. What's the current state?

**Comment by kottenator** [comment]
@jonashaag - first of all, I really want this PR to be done. There are three things to do:

1. Update the code. It's been awhile, many changes have been made to Django code. Maybe I'll have to completely redo my changes.
2. Write tests. I need to figure out how the tests are organized, where are existing tests located for the related functionally/module. And reuse the same test patterns.
3. But first of all - is it the right way I'm doing it? I'm replacing all the usages of `settings.STATIC_URL` with special helper functions. But what if all the _people_ are using `settings.STATIC_URL` in their projects and reusable apps? How to fix that? It may be hard to describe - I'm open for chat _somewhere_, if you have some better idea ;)

**Comment by kottenator** [comment]
But anyway, I'll return to this PR soon.

**Comment by glxiong** [comment]
Need this feature. Can we push it to master?

**Comment by and3rson** [comment]
Any updates? This has been around for a while.

**Comment by timgraham** [comment]
Closing due to inactivity. Anyone else is welcome to take the patch and continue it.

**Pull request closed without merging**
