### PR TITLE
Add __not_in filter field lookup (TRAC #25113)

### PR DESCRIPTION
**Pull request by tschuy**

### CODE REVIEW

**Comment by tschuy** [comment]
Closed: https://code.djangoproject.com/ticket/25113#comment:5

**Comment by LiorA1** [comment]
Any Chance you reconsider it ?

As comment 7 in the [link](https://code.djangoproject.com/ticket/25113#comment:7): `NOT ( <attribute> IN [...(list)])` is not equal to `NOT_IN`

**Comment by StevenLudwig** [comment]
Why, closed? this is helpful

**Comment by nessita** [comment]
> Why, closed? this is helpful

You can read the rationale and details in the linked bug above.

**Pull request closed without merging**
