### PR TITLE
Refs #19884 -- Introspect CharFields lengths correctly on Oracle.

### PR DESCRIPTION
**Pull request by felixxm**
Ticket [#19884](https://code.djangoproject.com/ticket/19884).

### CODE REVIEW

**Comment by felixxm** [comment]
Buildbot, test on Oracle.

**Comment by timgraham** [comment]
merged in 3e43d24ad36d45cace57e6a7efd34638577ae744, thanks! Pending a check of third-party backends, maybe the `can_introspect_max_length` feature can be removed also?

**Comment by felixxm** [comment]
From the official [3rd-party-database-backends](https://docs.djangoproject.com/en/1.10/ref/databases/#using-a-3rd-party-database-backend) only [IBM DB2](https://github.com/ibmdb/python-ibmdb) and [Firebird](https://github.com/maxirobaina/django-firebird) are using `can_introspect_max_length`. I created appropriate PRs (IBM DB2 - [PR](https://github.com/ibmdb/python-ibmdb/issues/252), Firebird - [PR](https://github.com/maxirobaina/django-firebird/issues/67)).

**Comment by timgraham** [comment]
Thanks, that's interesting that firebird duplicates Django's test suite. I wonder if your PR is helpful or if they  would merge the update from upstream.

**Pull request closed without merging**
