### PR TITLE
Refs #25438 Oracle GIS test failures for Django 1.9

### PR DESCRIPTION
**Pull request by felixxm**
Changed EPSG:3857 (which is not available in Oracle ver. < 11.2.0.3) to EPSG:3785 (which should be available in all backends), tests in progress...

### CODE REVIEW

**Comment by charettes** [comment]
Buildbot, test this please.

**Comment by charettes** [comment]
Buildbot, test on oracle

**Comment by timgraham** [comment]
buildbot, test on oracle.

**Comment by timgraham** [comment]
the new traceback reported by Jenkins:
```
Traceback (most recent call last):
  File "/mnt/jenkinsdata/workspace/pull-requests-oracle/database/oragis11/python/python3.5/django/test/testcases.py", line 1093, in skip_wrapper
    return test_func(*args, **kwargs)
  File "/mnt/jenkinsdata/workspace/pull-requests-oracle/database/oragis11/python/python3.5/tests/gis_tests/geoapp/test_functions.py", line 191, in test_difference_mixed_srid
    self.assertEqual(c.mpoly.difference(geom), c.difference)
AssertionError: <MultiPolygon object at 0x7f82e23efd58> != <MultiPolygon object at 0x7f82e23efc48>
```

**Comment by felixxm** [comment]
EPSG:3857 is available in Oracle 11.2.0.3 or later, so we have to options:
* increase require Oracle db version for gis backend to 11.2.0.3, or
* change EPSG:3857 to EPSG:3785 (which is the same, because 3785 code has been changed to 3857), just like in this PR.

**Comment by timgraham** [comment]
Another option could be to add a "supports_epsg_3857" database feature flag, make it a function of the Oracle version, and skip the test if applicable.

As non-Oracle user, I can't comment if increasing minimum supported version of Oracle GIS backend would be fine from a user perspective (in my view, it's up to whatever the people maintaining the Oracle backend decide), however, the main issues from my perspective would be:
1. We'd need someone to upgrade the Oracle version provided by our CI.
2. We'd need someone to upgrade the [OracleTestSetup](https://code.djangoproject.com/wiki/OracleTestSetup) instructions for the new version of the Oracle Developer Days VM (current instructions work for version 11, which is no longer offered by Oracle, but I have a copy that I use for running the tests). (This needs to be done at some point regardless of the decision here, so if you are able to help with it, that'd be great.)

**Comment by felixxm** [comment]
Ok, I'll update OracleTestSetup instruction for current vm version.

**Comment by jtiai** [comment]
Oracle policy is to only support latest patch set. IOW when you open ticket in metalink first thing you must be sure that you're running latest patchset. Latest server version you can download directly from Oracle site is 11.2.0.1.0 so that would be good starting point to settle out common nominators.

Feature flag wouldn't be right since it's not really a feature but a thing that you have to know (just like any other SRID, you have to know what to use)

**Comment by timgraham** [comment]
@shaib, when you have a chance, could you upgrade Oracle on CI and document the process? I guess testing against v12 could be nice. We could try asking for help on the mailing list too.

**Comment by felixxm** [comment]
[OracleTestSetup](https://code.djangoproject.com/wiki/OracleTestSetup) instruction is ready, enjoy.

**Comment by shaib** [comment]
@felixxm thanks for the updated instructions. I'll see when I can get to upgrade the CI. FWIW, as @jtiai said, there's no way to upgrade an Oracle 11 beyond 11.2.0.1, but we can and should get an Oracle12 running.

**Comment by timgraham** [comment]
Should we close this PR in favor of requiring a newer version of Oracle then?

**Comment by timgraham** [comment]
I am still getting `AssertionError: <MultiPolygon object at 0x7fb5128be450> != <MultiPolygon object at 0x7fb512971ab0>` for this test on the Oracle 12 Developers Days VM before and after this PR, so I think this isn't sufficient to fully resolve the issue unless the Oracle versions I've tested against are no good.

**Pull request closed without merging**
