### PR TITLE
Fixed #34455 -- language_from_path returning None in LocaleMiddleware

### PR DESCRIPTION
**Pull request by sinsniwal**
Fixed: https://code.djangoproject.com/ticket/34455

When using LocaleMiddleware, the value of language_from_path was coming out to be None initially, and because of that, the redirect was not working.

### CODE REVIEW

**Comment by felixxm** [comment]
Please create patch against the `main` branch.

**Comment by sinsniwal** [comment]
Thanks Mariusz, on it, I am new to open source so it's taking a little bit
of time.

**Comment by sinsniwal** [comment]
Can you please check this, should i send the pull request?

https://github.com/sinsniwal/django/tree/ticket_34455

**Comment by felixxm** [comment]
Looks good as a draft patch (release notes `4.2.1.txt` and a regression test is missing). However, I don't believe it is the correct solution, see [comment](https://code.djangoproject.com/ticket/34455#comment:10).

**Comment by felixxm** [comment]
Also, `get_language_from_request()` is intended to return a language from requests, not from settings.

**Comment by sinsniwal** [comment]
But the thing is for the first time if someone enters a URL like admin,
there is no language to get from there, than in those cases we can redirect
too, that's what i got , like once i open the admin using en/admin, after
that i was able to access admin directly without using en, by implementing
this code instead of None, everything seems to work.
Even i will try to look more deeper.

**Comment by sinsniwal** [comment]
Yes, Sir, You are correct, This issue is not even persistent, and now I am
unable to simulate the issue, the issue can be on edge cases, I was able to
simulate like an hour ago and now its working fine without any changes

**Pull request closed without merging**
