### PR TITLE
Corrected the direction of arrows in admin selector boxes for RTL languages.

### PR DESCRIPTION
**Pull request by swarakaka**

### CODE REVIEW

**Comment by felixxm** [comment]
@shaib Can you take a look?

**Comment by shaib** [comment]
I'm not all that fluent in the admin's CSS... @swarakaka can you post here before/after images which show the effect of the change?

**Comment by swarakaka** [comment]
@shaib please ...
**before**
grafik

**after**
grafik

**Comment by swarakaka** [comment]
This change should also be made in some other places, including select all etc.

**Comment by shaib** [comment]
@felixxm yep, looks right
@swarakaka I think any improvement is welcome, but since you already noted the "select all" arrow and you are already "in" this, would you mind fixing that too?

**Comment by felixxm** [comment]
@shaib Thanks for checking :+1:

**Comment by felixxm** [comment]
@swarakaka Thanks for the patch :+1:

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Pull request merged**
