### PR TITLE
Fixed #25034 -- Converted caches ImproperlyConfigured error to a system check

### PR DESCRIPTION
**Pull request by tomchristie**
https://code.djangoproject.com/ticket/25034

To do:

- [x] Test cases.
- [x] Add 'caches' tag to system checks docs.

### CODE REVIEW

**Comment by timgraham** [comment]
Tom, we can offer completing this as an "easy pickings" task for the sprints on Thursday/Friday if you like.

**Comment by tomchristie** [comment]
@timgraham Sure, good idea. Failing that I'll polish it off next week.

**Comment by tomchristie** [comment]
Does this need to be complete before the alpha freeze?

**Comment by timgraham** [comment]
Yes, bug fixes are allowed after alpha and this doesn't seem to qualify as a bug.

**Comment by tomchristie** [comment]
Okay, tests & docs addressed.

Evidently further incremental improvements we can make now that the 'caches' system checks exist.
(Eg. ensure the 'BACKENDS' and other bits are correct at system check time, rather than later on) although no reason why we can't treat those improvements as secondary (ie 1.10).

The main thing being addressed here is preventing errors being raised by imports, due to settings being accessed at a module level.

**Comment by tomchristie** [comment]
Assuming that the test failures there are not meaningful.

image

**Comment by timgraham** [comment]
Yep, you can read about those checkout errors [on the wiki](https://code.djangoproject.com/wiki/Jenkins).

Merged in b02f08e02c34bcf19444c15b54c5f64ddd4c9ef2, thanks!

**Comment by tomchristie** [comment]
Wonderful, thanks for your time @timgraham.

**Pull request closed without merging**
