### PR TITLE
Completed test coverage for django.urls.utils.get_callable().

### PR DESCRIPTION
**Pull request by hramezani**

### CODE REVIEW

**Comment by timgraham** [comment]
Could you try for complete coverage of `get_callabe()`, test the full message for each case, and put each case in a separate test method?

**Comment by hramezani** [comment]
@timgraham sure, as soon as possible.

**Comment by hramezani** [comment]
@timgraham I added extra tests and separate the tests.
It seems `mariadb/database=mysql` and `mariadb/database=mysql_gis` tests failed because of connection to Mysql problem.
anyway, if I missed something please let me know.

**Comment by hramezani** [comment]
@timgraham I added extra tests and separate the tests.
if I missed something please let me know.

**Pull request merged**
