### PR TITLE
Fixed #28569 -- Corrected get_layer_by_name prototype to skip error checking

### PR DESCRIPTION
**Pull request by pope1ni**
Ticket [#28569](https://code.djangoproject.com/ticket/28569).

This is a follow up of https://github.com/django/django/pull/9006#pullrequestreview-60309807.

### CODE REVIEW

**Comment by timgraham** [comment]
Can you put the test for the bug fix in that commit?

**Comment by pope1ni** [comment]
Hah. I thought about doing that, but erred on the side of lazy. Incoming...

**Comment by timgraham** [comment]
I'm seeing a test failure with PostGIS after this commit:
```
======================================================================
ERROR: test_time_field (gis_tests.inspectapp.tests.OGRInspectTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/tests/gis_tests/inspectapp/tests.py", line 121, in test_time_field
    decimal=['f_decimal'])
  File "/home/tim/code/django/django/contrib/gis/utils/ogrinspect.py", line 119, in ogrinspect
    return '\n'.join(s for s in _ogrinspect(*args, **kwargs))
  File "/home/tim/code/django/django/contrib/gis/utils/ogrinspect.py", line 119, in <genexpr>
    return '\n'.join(s for s in _ogrinspect(*args, **kwargs))
  File "/home/tim/code/django/django/contrib/gis/utils/ogrinspect.py", line 139, in _ogrinspect
    layer = data_source[layer_key]
  File "/home/tim/code/django/django/contrib/gis/gdal/datasource.py", line 100, in __getitem__
    return Layer(layer, self)
  File "/home/tim/code/django/django/contrib/gis/gdal/layer.py", line 34, in __init__
    self.ptr = layer_ptr
  File "/home/tim/code/django/django/contrib/gis/ptr.py", line 27, in ptr
    raise TypeError('Incompatible pointer type: %s.' % type(ptr))
TypeError: Incompatible pointer type: <class 'int'>.
```
I haven't identified the difference between my machine and Jenkins yet.

**Comment by timgraham** [comment]
@pope1ni, you should be able to reproduce that failure locally -- can you look into it? The test is being skipped on Jenkins due to another issue. I'll wait to fix the issue there until we have a resolution here so we don't have failing builds in the meantime.

**Comment by timgraham** [comment]
In the failing test, the return value of [capi.get_layer_by_name()](https://github.com/django/django/blob/2a4b33134883b80870b4b23e59ccd3b6cb7266a3/django/contrib/gis/gdal/datasource.py#L90) is `c_void_p(53596128)` before this patch and 36153408 after this patch. Does it give any ideas? \cc @sir-sigurd

**Comment by ngnpope** [comment]
@timgraham: I'm mobile phone only until Friday, I'm afraid.

Seems odd as the pointer type should still be the same as before, but should be returning `None` if the layer name is invalid instead of raising `GDALException`. Was this test already skipped on Jenkins before as I don't remember bumping into this?

**Comment by sir-sigurd** [comment]
I think I can fix it.

**Comment by ngnpope** [comment]
PR https://github.com/django/django/pull/9065 by @sir-sigurd.

Yeah. That was the other way to fix the bug I found, but I went for the one that seemed consistent with similar functions for fetching objects by name. Thanks.

**Pull request merged**
