### PR TITLE
Removed old and out of date comment about PUT

### PR DESCRIPTION
**Pull request by anxodio**

### CODE REVIEW

**Comment by hughgrigg** [comment]
What is old and out of date about it?

**Comment by anxodio** [comment]
Browsers actually support other methods than POST... or the comment is talking about the method in the action form tag? In this case, is not out of date but causes confusion (at least to me)

**Comment by hughgrigg** [comment]
I think it is just talking about the `method` attribute in a `form` element.

**Comment by charettes** [comment]
I confirm what @hughgrigg said; it's talking about `<form method>` since the comment is part of `ProcessFormView`'s definition. It seems to [still be true](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#attr-method).

**Comment by anxodio** [comment]
Yeah, I see... as I said, I just misunderstood it, so in any case this PR has no sense because is not out of date, it just causes confusion (at least to me :wink: )

**Pull request closed without merging**
