### PR TITLE
Fixed SeleniumTests.test_related_object_update_with_camel_casing() assert.

### PR DESCRIPTION
**Pull request by sarahboyce**
Failed test run:
- https://github.com/django/django/actions/runs/8532477057/job/23373682477
- https://github.com/django/django/actions/runs/8532477057/job/23373682378

### CODE REVIEW

**Review by carltongibson — APPROVED** [review]
OK, looks sensible. (Curious change to just come up... — I guess a Selenium update? 🤔)

**Comment by sarahboyce** [comment]
> OK, looks sensible. (Curious change to just come up... — I guess a Selenium update? 🤔)

It's a newly added test from https://github.com/django/django/pull/18025 and I think `innerHTML` was intended to be referenced (as `_get_HTML_inside_element_by_id` was written) but the selenium tests weren't run. Can think about whether it's worth having selenium tests run on all 'admin' PRs automatically 🤔 but not sure, assume we don't run them on every PR because of flakiness rather than a cost saving.

**Review by claudep — APPROVED** [review]
Sarah, let me take this opportunity to congrat and welcome you in your new role! :balloon: :fireworks:

**Comment by sarahboyce** [comment]
Thank you @claudep 😁

**Pull request merged**
