### PR TITLE
Added Armenian language

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
Just asked Ruben to approve this PR before the push.

**Comment by K-DOT** [comment]
I'm approving. Please push.

**Comment by timgraham** [comment]
`admin_widgets.tests.DateTimePickerSeleniumTests.test_calendar_show_date_from_input` fails since this change.

**Comment by claudep** [comment]
Should be fixed by 87bf35abd3. There were unexpected \u200e chars (left-to-right marker) in two month names.

**Pull request merged**
