### PR TITLE
first stab at properly handling natural keys combined with inheritance

### PR DESCRIPTION
**Pull request by denys-duchier**
this PR concerns my bug report https://code.djangoproject.com/ticket/24607

it seems to work on my test example.

### CODE REVIEW

**Comment by timgraham** [comment]
Thanks for sending a patch. You should send your PR against master though, so I'll close this one. A test will also needed. See also our [patch review checklist](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/submitting-patches/#patch-review-checklist).

**Comment by denys-duchier** [comment]
The reason I did it against stable/1.8.x is because it is LTS.  Do you only want a PR against master, or 2 PRs against both?

**Comment by denys-duchier** [comment]
for this PR, I am trying to write tests that check that loaddata of dumpdata works properly.  for each test, I need to populate the database, serialize it, clear it, then reload it.  what is the right way to clear it?

**Comment by timgraham** [comment]
See our [supported versions policy](https://docs.djangoproject.com/en/dev/internals/release-process/#supported-versions) for the guidelines on what bug fixes we backport. I don't think this particular bug qualifies.

**Pull request closed without merging**
