### PR TITLE
Fixed # 32226 QuerySet.explain(format='json') outputs repr'd JSON on PostgreSQL

### PR DESCRIPTION
**Pull request by Uday-kiran007**
now the ouput of explain() is actual json.

### CODE REVIEW

**Comment by felixxm** [comment]
@Uday-kiran007 You can push changes to your branch, there is no need to open multiple PRs for the same change. Please don't do this.

**Comment by Uday-kiran007** [comment]
now the output is actual json

**Comment by Uday-kiran007** [comment]
> u can push changes to your branch, th

sorry fleixmm I am contributing for the first time

**Comment by Uday-kiran007** [comment]
> @Uday-kiran007 You can push changes to your branch, there is no need to open multiple PRs for the same change. Please don't do this.

sorry felixxm, I am conrtibuting for the first time

**Pull request closed without merging**
