### PR TITLE
Refs #18392 -- Changed default MySQL connection charset to utf8mb4

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by collinanderson** [comment]
+1, though it's more of a "changing a default" than "adding support", right? It will certainly make it much easier.

**Comment by claudep** [comment]
Totally right, title updated.

**Comment by timgraham** [comment]
Should some documentation in `docs/ref/databases.txt` and or release notes detailing the change be added? Could a test show the change's usefulness?

I understand bumping the minimum version in the documentation but as 5.5.8 is the first release designated "General Availability", I wonder if that's useful in practice. Is there much chance users would be using a prerelease of MySQL 5.5 at this point? Just curious; I don't know much about MySQL's release process.

**Comment by claudep** [comment]
I intended to provide more documentation/release notes/tests when the Django test suite itself is able to run with utf8mb4 (in works locally). Maybe we should just wait for that patch being ready?
It's true that the probability people use Mysql 5.5 before 5.5.3 is near to 0. However it's technically correct.

**Comment by timgraham** [comment]
Waiting for a more comprehensive patch sounds good.

**Comment by claudep** [comment]
OK

**Comment by wakaryry** [comment]
My setting for MySQL in django is already for utf8mb4.
```python
DATABASES = {
    'default': {
        'ENGINE': 'mysql.connector.django',
        'NAME': 'xxxx',
        'USER': 'xx',
        'PASSWORD': 'xxxxxxxx',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'autocommit': True,
            'use_pure': True,
            'charset': 'utf8mb4',
            'collation': 'utf8mb4_0900_ai_ci'
        }
    }
}
```
And my MySQL database is also setted into `utf8mb4` for `characterset` and `collation`.

I migrated my table before with times. It's OK.

But today I added some tables, and then migrate them. It throws error:

```
django.db.utils.DatabaseError: 
(3719, "3719: 'utf8' is currently an alias for the character set UTF8MB3, 
which will be replaced by UTF8MB4 in a future release. 
Please consider using UTF8MB4 in order to be unambiguous.", None)
```

I really do not know why it throws the error.

I was using `Python 3.6.5` `Django 2.0.6` `mysql-connector 8.0.11` `MySQL 8.0.11`.

Thanks for any help.

**Pull request closed without merging**
