### PR TITLE
Used Decimal.scaleb() in backends.utils.format_number() and DecimalField.widget_attrs() to improve performance.

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Comment by orf** [comment]
I don't know if you've considered this, but creating the `Decimal(1)` object outside of these function and re-using it could provide quite a nice speedup, in my benchmarks 10% of the time is spent creating this Decimal object (which is immediately thrown away).

Copying the context takes a long time as well, it would be nice to only copy it if needed, but I can't think of a nice way to do this with the current code.

**Comment by pope1ni** [comment]
> creating the Decimal(1) object outside of these function and re-using it could provide quite a nice speedup,

Why stop at just the creation of `Decimal(1)`? Realistically, how many decimal places do people use? Why not pre-create for a range of decimal places up front in global scope (or some utility module)?

```
In [1]: %timeit decimal.Decimal(1).scaleb(-10)
7.62 µs ± 114 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [2]: d = decimal.Decimal(1)
In [3]: %timeit d.scaleb(-10)
6.67 µs ± 52.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [4]: x = {dp: d.scaleb(-dp) for dp in range(100)}
In [5]: %timeit x[15]
30.6 ns ± 0.329 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```

Ok, this is a naive example not in context, but the principle is that we get a simple dictionary lookup instead.

Also, I've plucked up to 99 decimal places as a value out of thin air which is probably too many. We would also still need to fall back to the slow path just in case someone chooses a value not accounted for.

If this approach is considered, then the other two places recently updated to use `Decimal.scaleb()` should be reviewed to see if this would be useful in those places too:

- https://github.com/django/django/blob/78247b80a8cbf1ebfb7a54624de7dc92e1a1f888/django/template/defaultfilters.py#L137
- https://github.com/django/django/blob/c8a85e3e91bf829671b4a8cbd105fbabce945174/django/db/backends/oracle/base.py#L409

**Comment by sir-sigurd** [comment]
@pope1ni 
> Why not pre-create for a range of decimal places up front in global scope (or some utility module)?

Instead of that we could use `lru_cache`d function.
Anyway it would be nice to have some benchmarks.

**Comment by orf** [comment]
This implementation:
```
In [13]: %timeit format_number(d, 3, 3)
2.62 µs ± 89.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

With making `Decimal(1)` a global:
```
In [9]: %timeit format_number(d, 3, 3)
2.33 µs ± 71.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

And if we remove the call to `context.copy()` if it's not needed:
```
In [6]: %timeit format_number(d, 3, 3)
1.81 µs ± 61.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

I ran each of these a few times, they are representative on least my machine. Here is the code:

```python
one_d = decimal.Decimal(1)

def format_number(value, max_digits, decimal_places):
    """
    Format a number into a string with the requisite number of digits and
    decimal places.
    """
    if value is None:
        return None
    if isinstance(value, decimal.Decimal):
        context = decimal.getcontext()
        if decimal_places is None or max_digits is None:
            context = context.copy()

        if max_digits is not None:
            context.prec = max_digits
        if decimal_places is not None:
            value = value.quantize(one_d.scaleb(-decimal_places), context=context)
        else:
            context.traps[decimal.Rounded] = 1
            value = context.create_decimal(value)
        return "{:f}".format(value)
    if decimal_places is not None:
        return "%.*f" % (decimal_places, value)
    return "{:f}".format(value)
```

**Pull request merged**
