### PR TITLE
Fixed #9388 -- Added year select element to admin datepicker.

### PR DESCRIPTION
**Pull request by rynomster**
Added a select element to the calendar which makes it easier to
navigate between years.

### CODE REVIEW

**Comment by timgraham** [comment]
I guess the solution needs some refining -- unless I missed something, making it unusable for dates before 1900 doesn't seem acceptable (as in, if a pre-1900 date is already selected, the year will display as 1900 in the dropdown).

I'd consider using a jQuery plugin if there's something suitable out there. Things have changed a bit since Django's beginnings in 2005, and I think there's probably not much need for Django to maintain its own version.

Of course tests are also needed, but using a plugin might eliminate that need since there's not much need to test third-party code.

**Comment by rynomster** [comment]
I'll play around again tonight, the native html5 calendar also does the job?

**Comment by rynomster** [comment]
The HTML5 date field is changing the display format to a localized format, but internally the value is set to RFC3339 specification (yyyy-mm-dd). http://stackoverflow.com/questions/7372038/is-there-any-way-to-change-input-type-date-format
If you could give my some guidelines, I'll implement it, but there's quite allot of javascript and css already in the system to deal with dates, maybe for years outside the select range, we just show the year as text and allow them to continue with the arrow navigation (quickfix), but I'm keen to help implement the correct solution.

**Comment by timgraham** [comment]
Firefox doesn't support [an HTML5 datepicker](http://caniuse.com/#feat=input-datetime) so unfortunately I think that solution is out for now. I'm not sure investing much effort to solve the ticket is worthwhile. If you need a year far off in the past or future, you can always just select the date in the current year and edit the year in the text box after the datepicker closes.

**Comment by timgraham** [comment]
Closing for now.

**Pull request closed without merging**
