### PR TITLE
Add command "loadstatic" inside cmd for load automatically assets/static inside template

### PR DESCRIPTION
**Pull request by vBlackOut**
check here original project : https://github.com/vBlackOut/loadstatic

### CODE REVIEW

**Comment by vBlackOut** [comment]
Hello, yes it's my first contribution i try to fix my linter code thank !

**Comment by felixxm** [comment]
Thanks for this patch, however all new features require [an accepted ticket](https://code.djangoproject.com/newticket).

**Comment by felixxm** [comment]
Thanks for this patch, however it sounds like a third-party package is the best way to proceed so that people can try it out and then approaching the [django-developers mailing list](https://groups.google.com/g/django-developers) to reach a wider audience and see what other think.

**Comment by vBlackOut** [comment]
why it's better package for this ? i didn't found ? 
and for download the cdn on path static it's possible ? on automaticaly ?
i didn't found the solution on django ...

**Comment by felixxm** [comment]
I didn't say that there is a better package for your use case.

IMO, it's not something that needs to be built into Django itself.

**Comment by vBlackOut** [comment]
but it's better it's inside core for all people ? no
i creater documentation after and test unitest for thaht and add inside django for better use :) no ?
you are okai

**Comment by felixxm** [comment]
> but it's better it's inside core for all people ? no

No, the current thread is to keep Django a core framework, not providing every utility which might be useful.

**Comment by vBlackOut** [comment]
ok thank for you explain it's just my proposal solution :) i create the package no other solution :( and i add pip install other package for that but it's weird for me

**Pull request closed without merging**
