### PR TITLE
Fixed #24558 -- Made dumpdata mapping ordering deterministic. 

### PR DESCRIPTION
**Pull request by charettes**
It's missing some tests.

### CODE REVIEW

**Comment by charettes** [comment]
From looking at the tests I assumed we wanted the following ordering:

```json
{
    "pk": 1,
    "model": "foo.bar",
    "fields": {
        ...
    }
}

**Comment by claudep** [comment]
Simon, you should not put hardcoded ids in tests, as they may vary depending on the tests run.

**Comment by charettes** [comment]
Hmm missed that, do you think creating an object with an explicit pk could do?

**Comment by charettes** [comment]
I have a better idea.

**Comment by gfairchild** [comment]
This is fantastic. Thanks for being so quick to address this!

**Comment by charettes** [comment]
@gfairchild this is something that also bugged me in the past.

**Comment by charettes** [comment]
Switched back the ordering to


```json
{
    "model": "foo.bar",
    "pk": 1,
    "fields": {
        ...
    }
}```

Since it makes more sense to me, comments welcome.

**Comment by gfairchild** [comment]
That ordering makes the most sense to me as well.

**Comment by claudep** [comment]
That loogs, good. However I think this deserves a mention in the release notes as it could change some current behavior.

**Comment by gfairchild** [comment]
Which version of Django is likely to receive this patch, a minor (e.g., 1.8.1) or major (e.g., 1.9) release?

**Comment by claudep** [comment]
1.9 (as it's not a regression)

**Comment by gfairchild** [comment]
Great, thanks! I look forward to it.

**Comment by charettes** [comment]
Added a release note mentioning `dumpdata` output changes.

@claudep, do you think this is sufficient or should I also note that the changes were done at the serializer level?

**Pull request merged**
