### PR TITLE
Fixed #27061 -- Added a TEST TEMPLATE setting for postgresql.

### PR DESCRIPTION
**Pull request by cjerdonek**

### CODE REVIEW

**Comment by timgraham** [comment]
A few cosmetic edits: http://dpaste.com/3J5NNW8 (Did you read in the style guide how we allow longer lines up to 119 characters?)

The tests should go in tests/backends/test_creation.py. postgres_tests is for contrib.postgres.

**Comment by timgraham** [comment]
Might be worth mentioning in the PostgreSQL section of docs/ref/databases.txt

**Comment by cjerdonek** [comment]
Thanks for the review!

Ah, yes re: line length. I believe you wrote your last comment to me about that after I had already prepared / submitted the current patch: https://github.com/django/django/pull/7096#discussion_r75004267

And okay re: tests/backends/test_creation.py. I see though that tests/backends currently seems to have only two postgres-specific tests, and I'm not able to import `from ..postgres_tests import PostgreSQLTestCase` from tests/backends:

    ValueError: attempted relative import beyond top-level package
    
(The vendor check in the two current postgres-specific tests should probably be DRYed up using the same or a similar decorator or test-case class.)

**Comment by timgraham** [comment]
merged in a3db480393d0065fc69834057f0e02a4afc65df9, thanks!

**Comment by cjerdonek** [comment]
Thanks!

**Pull request closed without merging**
