### PR TITLE
Fixed #24053 -- Removed contrib.admin css for IE6&7

### PR DESCRIPTION
**Pull request by seanwestfall**
Removed the main IE6&7 css file from the admins page.
Also removed the image related to the css file "inline-delete-8bit.png",
as well as the line from the template that included the css file:
django/contrib/admin/templates/admin/base.html
The reasons for doing this is specified on the ticket:
https://code.djangoproject.com/ticket/24053

All tests passed during the test suite run from tests/runtests.py on
sqlite.

### CODE REVIEW

**Comment by timgraham** [comment]
Thanks, but we cannot merge this until we cut the stable/1.8 branch so that master is accepted features for 1.9. At that point this should be mentioned in the 1.9 release notes under "backwards incompatible changes". Also see our [patch review checklist](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/submitting-patches/#patch-review-checklist) for the proper commit message format. I can ping you when it's a good time to update this.

**Comment by seanwestfall** [comment]
yeah, please do ping me timgraham. And I'll look through the patch review checklist aswell. Thanks!

**Comment by timgraham** [comment]
This change can move forward now.

**Comment by seanwestfall** [comment]
cool thanks!

**Comment by timgraham** [comment]
Do you understand the remaining work that's needed?

**Pull request closed without merging**
