### PR TITLE
Fixed #24944 -- Added extra_email_context parameter to password_reset() view.

### PR DESCRIPTION
**Pull request by SujaySKumar**

### CODE REVIEW

**Comment by auvipy** [comment]
squash all the commits in a single commit according to guideline

**Comment by charettes** [comment]
Can also add tests for this?

**Comment by SujaySKumar** [comment]
Hi,
I am not sure how to add tests for this feature. Can you guide me in how to
go about doing it?

**Comment by timgraham** [comment]
Take a look at `tests/auth_tests/test_views.py` for how tests for the other parameters are done.

**Comment by SujaySKumar** [comment]
Hi Tim,
In the tests for auth views, there are no tests for parameters like
extra_context.
Why is that?
Also, if extra_context cannot be tested, how can extra_email_context be
tested? As they are very similar.

**Comment by timgraham** [comment]
There is no good reason why `extra_context` is not tested. Pretend you are using the feature. There is a test in `admin_views` for a similar `extra_context` parameter there.

**Comment by timgraham** [comment]
The test isn't testing this feature. If I revert your changes in `django/contrib/auth/views.py` I'm pretty sure the test will still pass.

**Comment by SujaySKumar** [comment]
@timgraham Should I send the extra_email_context to send_mail function too?

**Comment by timgraham** [comment]
It should be merged with the `context` dictionary: https://github.com/django/django/blob/7efdd40407838dc3c922e0e62e9b4eefabe7de01/django/contrib/auth/forms.py#L246-L254

**Comment by SujaySKumar** [comment]
Hi Tim,
I've done it...Any other changes?

**Pull request closed without merging**
