### PR TITLE
Refs #6767 -- Added test for fetching decimal values without rounding error on Oracle.

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by timgraham** [comment]
Is it testing a different code path than the above test for [#5079](https://code.djangoproject.com/ticket/5079). I noticed that fails with `numbersAsStrings = True` removed.

**Comment by felixxm** [comment]
Both test fail when we remove `numbersAsStrings = True`:

```
======================================================================
FAIL: test_save_without_float_conversion (model_fields.test_decimalfield.DecimalFieldTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/django/tests/model_fields/test_decimalfield.py", line 52,
  in test_save_without_float_conversion
    self.assertEqual(bd.d, Decimal('12.9'))
AssertionError: Decimal('12.9000000000000003552713678800500929355621337890625')
!= Decimal('12.9')

======================================================================
FAIL: test_fetch_from_db_without_float_rounding (model_fields.test_decimalfield.DecimalFieldTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/django/tests/model_fields/test_decimalfield.py", line 58, in
  test_fetch_from_db_without_float_rounding
    self.assertEqual(big_decimal.d, Decimal('.100000000000000000000000000005'))
AssertionError: Decimal('0.1000000000000000055511151231257827021181583404541015625')
!= Decimal('0.100000000000000000000000000005')
----------------------------------------------------------------------
```

but when we remove also `_rowfactory` (that is a part of ad93542c8f) then they behave differently:
```
======================================================================
FAIL: test_save_without_float_conversion (model_fields.test_decimalfield.DecimalFieldTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/django/tests/model_fields/test_decimalfield.py", line 52,
  in test_save_without_float_conversion
    self.assertEqual(bd.d, Decimal('12.9'))
AssertionError: 12.9 != Decimal('12.9')

======================================================================
FAIL: test_fetch_from_db_without_float_rounding (model_fields.test_decimalfield.DecimalFieldTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/django/tests/model_fields/test_decimalfield.py", line 58, in
  test_fetch_from_db_without_float_rounding
    self.assertEqual(big_decimal.d, Decimal('.100000000000000000000000000005'))
AssertionError: 0.1 != Decimal('0.100000000000000000000000000005')
----------------------------------------------------------------------
```

**Pull request merged**
