### PR TITLE
Removed various unused/untested code in django.db.models.fields.

### PR DESCRIPTION
**Pull request by timgraham**

### CODE REVIEW

**Comment by timgraham** [comment]
buildbot, test on oracle.

**Comment by timgraham** [comment]
@akaariai, @jarshwah, please let me know if anything looks suspicious here.

**Comment by jarshwah** [comment]
The only one I'm concerned about here is the removal of `refs_aggregate`, although it looks like it isn't actually used anymore.

The docs mention this kind of queryset:

```
queryset.filter(num_chairs__gt=F('sum__employees'))
```

A test to see if refs_aggregate should be used would be something like:

```
class Abs(Func):
    lookup_name = 'abs'
    function = 'ABS'
IntegerField.register_lookup(Abs)

Model.objects.annotate(sum=Sum('employees')).filter(num_chairs_gt=F('sum__abs'))
```

**Comment by timgraham** [comment]
I tried to test your concern with this addition to `tests/expressions/tests.py`:
```python
def test_refs_aggregate(self):
    class Abs(Func):
        lookup_name = 'abs'
        function = 'ABS'
    IntegerField.register_lookup(Abs)

    list(Company.objects.annotate(sum=Sum('num_employees'))).filter(num_chairs__gt=F('sum__abs')))
```
This gives:
on 1.8: `Cannot resolve keyword 'sum' into field. Choices are: ceo, ceo_id, id, name, num_chairs, num_employees, point_of_contact, point_of_contact_id, sum`
on 1.9/master: `FieldError: Cannot resolve keyword 'abs' into field. Join on 'sum' not permitted.`
(no change of behavior with these changes)

**Comment by jarshwah** [comment]
I shouldn't write responses late after beers, sorry. Lookups don't work within F, they'd need to be on the LHS.

```
list(Company.objects.annotate(sum=Sum('num_employees'))).filter(sum__abs=F('num_chairs')))
```

But I'd be extremely surprised if that wasn't tested.

**Comment by akaariai** [comment]
I think the changes are OK. The lookups stuff was for old style lookups, and if Q.clone() isn't needed by the test suite, I'm positive it isn't needed currently.

**Pull request merged**
