### PR TITLE
Fixed #32313 -- Corrected QuerySet.in_bulk() signature.

### PR DESCRIPTION
**Pull request by iurisilvio**

### CODE REVIEW

**Review by carltongibson — APPROVED** [review]
Seems reasonable to me. (@felixxm it's nothing you'd object to no?)

**Comment by felixxm** [comment]
I'm not sure, normally we don't include it in docs, e.g. [`set()`](https://docs.djangoproject.com/en/3.1/ref/models/relations/#django.db.models.fields.related.RelatedManager.set), [`clear()`](https://docs.djangoproject.com/en/3.1/ref/models/relations/#django.db.models.fields.related.RelatedManager.clear),  [`update_or_create()`](https://docs.djangoproject.com/en/3.1/ref/models/querysets/#django.db.models.query.QuerySet.update_or_create), [`explain()`](https://docs.djangoproject.com/en/3.1/ref/models/querysets/#django.db.models.query.QuerySet.explain), etc.

**Comment by iurisilvio** [comment]
The behaviour was really unexpected to me, explicit docs would be great.

I had the doubt if it should be included in the docs, but `FilteredRelation` has it explicit in the same page. https://docs.djangoproject.com/en/3.1/ref/models/querysets/#django.db.models.FilteredRelation

**Comment by carltongibson** [comment]
hehe. Yes, that's why I paused. But it's concise and adds info, perhaps we should — although we deliberately don't match the signature exactly in the docs...? 🤷 (let's chat about it tomorrow)

**Comment by felixxm** [comment]
@iurisilvio Thanks :+1: , let's merge it.

**Pull request merged**
