### PR TITLE
Fixed #24223 - SessionMiddlewareTests now use django.test.TestCase

### PR DESCRIPTION
**Pull request by matt-leach**
See https://code.djangoproject.com/ticket/24223 for more info

### CODE REVIEW

**Comment by charettes** [comment]
Buildbot, test this please.

**Comment by charettes** [comment]
Wondering if `CookieSessionTests` should subclass `unittest.TestCase` since it doesn't mess with the DB.

**Comment by matt-leach** [comment]
yes I believe so; I'll push a change

**Comment by charettes** [comment]
Buildbot, test this please.

**Comment by charettes** [comment]
Merged in 55c76f4e3bab74c8544b72d11a99e94a1c2cfbce and backported to `stable/1.8.x` in 7b92acea7055c6b39207a813b52e683a3672e467, thanks!

For future contribution use the past tense for commit message and two `-` to separate the message from the ticket number.

**Comment by matt-leach** [comment]
Will do!

**Pull request closed without merging**
