### PR TITLE
Removed unnecessary type creation in modelforset_factory.

### PR DESCRIPTION
**Pull request by charettes**

### CODE REVIEW

**Comment by charettes** [comment]
It was introduced by f026a519aea8f3ea7ca339bfbbb007e1ee0068b0 but was never required as `getattr(None, 'foo', 'bar') == 'bar'`.

**Comment by timgraham** [comment]
The comment in the related commit seems to imply all of stuff leading up to `ImproperlyConfigured` could be removed since a similar message would be raised in `modelform_factory()`. I guess it's fine to keep it for the better error message referencing `modelformset_factory` instead of `modelform_factory`.

**Comment by charettes** [comment]
Agreed, let's keep the explicit `modelformset_factory` error. The `type()` removal LGTY?

**Comment by timgraham** [comment]
I guess -- I don't see what the purpose is.

**Pull request merged**
