### PR TITLE
Fixed #27141 -- Fixed makemigrations crash on readonly database with django_migrations table.

### PR DESCRIPTION
**Pull request by sjoerdjob**
Follow-up on 76ab8851181675a59425f9637bdbf3f2de95f6f1.

### CODE REVIEW

**Comment by timgraham** [comment]
Does https://github.com/django/django/pull/7142 solve the issue?

If a separate patch is needed, I don't think renaming an exception class as you've done is a good idea for a stable release.

**Comment by sjoerdjob** [comment]
Regarding the renaming. Yes, I was assuming that it was introduced between 1.10 and 1.10.1, but it is actually a bit older (at least 2015). So renaming it is indeed a very bad idea.

From what I can see of the #7142, it is not going to fix the issue, because the table does exist (so `self.Migration._meta.db_table not in self.connection.introspection.table_names(self.connection.cursor())` holds), but the table is not readable.

What would help me is if there is a try/except around the following line `return set(tuple(x) for x in self.migration_qs.values_list("app", "name"))` (line 72 in the current diff).

Given the complexity of #7142, I think it might be best to extend it to also handle this case instead of having a separate PR.

**Comment by timgraham** [comment]
Which database is this? I wonder if modifying table introspection to exclude tables which can't be read would be feasible and a logical solution.

**Comment by sjoerdjob** [comment]
The database in question is Postgres, but I think most databases will have this issue.
Also, I'm not sure if excluding non-readable tables from introspection makes sense (might violate the single responsibility principle), though it would probably help for this case.
Thank you for looking into this.
Should we close this PR and move the discussion to code.djangoproject.com?

**Comment by timgraham** [comment]
Sure, you could let us know how `inspectdb ` currently works with this situation. I guess it might hit [that exception block](https://github.com/django/django/blob/488b3d2b38f69e668e86b1d40d976a936f48ed0f/django/core/management/commands/inspectdb.py#L82-L85). I guess if that's better than silently skipping such tables then that solution may not be ideal, or at least we'd need a new parameter to `introspection.table_names()` to skip unowned tables.

**Comment by sjoerdjob** [comment]
(replied at https://code.djangoproject.com/ticket/27141#comment:3, now going to ignore this PR).

**Pull request closed without merging**
