### PR TITLE
Added range filter

### PR DESCRIPTION
**Pull request by Dhruvacube**
## Added functionality for the pythonic ``range`` function in templates

A simple PR for the added functionality for the ``range`` function (I would say numeric forloop)
In `python` we have
```python
for i in range(5):
    print(i)
```

Here in template they can do:
```django
{% for j in an_integer_no|range %}
    {{j}}
    some html code or a random fnc .........
{% endfor %}
```

### CODE REVIEW

**Comment by felixxm** [comment]
Closing per ticket-13088.

**Comment by Dhruvacube** [comment]
hey @felixxm pleasee explain me, whats wontfix?? or there is a already alternative this ???

**Comment by Dhruvacube** [comment]
or is there a reason that django team wont implement this?

**Comment by felixxm** [comment]
See [Russell's comment](https://code.djangoproject.com/ticket/13088#comment:1). You can start a discussion on [django-developers mailing list](https://groups.google.com/g/django-developers) if you don't agree, [following triaging guidelines with regards to wontfix tickets](https://docs.djangoproject.com/en/stable/internals/contributing/triaging-tickets/#closing-tickets ).

**Pull request closed without merging**
