### PR TITLE
Fixed #26149 --Invalid migration generated when using order_with_respect_to an…

### PR DESCRIPTION
**Pull request by anabelensc**
Invalid migration generated when using order_with_respect_to and a unique_together constraint

### CODE REVIEW

**Comment by timgraham** [comment]
Any response to https://code.djangoproject.com/ticket/26149#comment:6?

**Comment by timgraham** [comment]
Could you please reply to [the comment on the ticket](https://code.djangoproject.com/ticket/26149#comment:6) about "I think there might be a better way to fix this bug."? I have a similar doubt that this is the best fix. 

Also, your branch needs to be rebased so it merges cleanly.

**Comment by anabelensc** [comment]
yes of course, let me check the comment

**Comment by timgraham** [comment]
Closing due to inactivity and because this doesn't seem to be the ideal solution as discussed on the ticket.

**Pull request closed without merging**
