### PR TITLE
Fixed #28991 -- Added EmptyFieldListFilter class in admin.filters.

### PR DESCRIPTION
**Pull request by jmfederico**
This PR continues the work from #10599 which in turn took from #9546.

### CODE REVIEW

**Comment by jmfederico** [comment]
Initially I just updated the docs assuming this gets merged to Django 3.1

**Comment by felixxm** [comment]
@jmfederico Thanks for updates :+1: I rebased from master, squashed commits, pushed edits, and reorganized tests.

**Comment by felixxm** [comment]
@jmfederico @jonashaag @baldychristophe Thanks :rocket: 

@baldychristophe Welcome aboard :boat:

**Comment by jmfederico** [comment]
@felixxm glad it helped.

I have one question for future MR, your input is appreciated.

I see you moved `EmployeeAdminWithEmptyFieldListFilter` inside the only test that uses it, but did not do the same with `DepartmentAdminWithEmptyFieldListFilter`.

- Is there a reason for this?

If `DepartmentAdminWithEmptyFieldListFilter` should also be inside the only test where it is used, can one just create a MR directly with no ticket in https://code.djangoproject.com to make this sort of code improvements or fixes?

**Comment by felixxm** [comment]
> Is there a reason for this?

I didn't want to mix inline and module-level `ModelAdmin`'s in a single test.

> can one just create a MR directly with no ticket in https://code.djangoproject.com to make this sort of code improvements or fixes

Yes, small cleanups can be sent without a ticket, but I don't see any value in changing these tests.

**Pull request merged**
