### PR TITLE
Fixed #33920 -- Doc'd dependency of LOGGING_CONFIG callback on non-empty LOGGING. 

### PR DESCRIPTION
**Pull request by Kinza-Raza**

### CODE REVIEW

**Review by carltongibson — COMMENTED** [review]
Hi @Kinza-Raza — thanks for this, welcome aboard! ⛵ 

Can I suggest a slightly different change? In line 2035 in the `LOGGING` section above...

```
A data structure containing configuration information. When not-empty, the
contents of this data structure will be passed as the argument to the
configuration method described in :setting:`LOGGING_CONFIG`.
```

I think that would be sufficient. 🤔

**Review by carltongibson — APPROVED** [review]
Hey @Kinza-Raza — I pushed those changes. Thanks for picking this up! 🏅

**Comment by Kinza-Raza** [comment]
Thank you for the help @carltongibson :)

**Comment by carltongibson** [comment]
Welcome aboard, first of many! 👍

**Pull request merged**
