### PR TITLE
Fixed #34978, Refs #31331 -- Added backward incompatibility note about raw aggregations on MySQL.

### PR DESCRIPTION
**Pull request by felixxm**
ticket-34978
ticket-31331

Thanks Matthew Somerville for the report.

### CODE REVIEW

**Comment by dracos** [comment]
Thanks, looks good :)

**Review by nessita — COMMENTED** [review]
Thanks @felixxm, the text looks good, though I do wonder if it wouldn't be better placed next to the `Database backend API` section that talks about `functional dependency detection`.

**Comment by felixxm** [comment]
> Thanks @felixxm, the text looks good, though I do wonder if it wouldn't be better placed next to the `Database backend API` section that talks about `functional dependency detection`.

"Database backend API" _describes changes that may be needed in third-party database backends_. This is not the case here.

**Comment by nessita** [comment]
> > Thanks @felixxm, the text looks good, though I do wonder if it wouldn't be better placed next to the `Database backend API` section that talks about `functional dependency detection`.
> 
> "Database backend API" _describes changes that may be needed in third-party database backends_. This is not the case here.

Fair enough, thanks for the clarification! +1

**Comment by charettes** [comment]
Thanks for the release notes adjustments @felixxm, appreciate!

**Comment by nessita** [comment]
> @nessita Thanks for merging 👍 I was waiting for Simon to take a look 😉

Oh, sorry, I merged this as part of my focus on release blockers! Thank you both!

**Pull request merged**
