### PR TITLE
Refs #26167 -- Made DatabaseSchemaEditor._create_index_sql()'s fields argument optional and kwarg-only.

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Review by carltongibson — APPROVED** [review]
Errr... OK, looks fine. (Is this ever intended that you wouldn't pass `fields`? 🤔 )

**Comment by felixxm** [comment]
> Is this ever intended that you wouldn't pass fields?

Yes, because #11929 introduces a new `expressions` kwarg.

**Comment by carltongibson** [comment]
Perfect. Thanks. 😉

**Pull request merged**
