### PR TITLE
Fixed #23967 -- Added formats for Greek

### PR DESCRIPTION
**Pull request by spapas**
For ticket #23967 (https://code.djangoproject.com/ticket/23967#ticket)

### CODE REVIEW

**Comment by pmav99** [comment]
I can confirm too that the correct format for greek locale is `"%d/%m/%Y`. That being said, I haven't actually tested the patch, but it seems be correct. 

The only thing I might disagree with is the thousand separator. AFAIK there is no standard convention for this and it might be better idea not to specify it (i.e. to leave it as it is).

**Comment by spapas** [comment]
@pmav99 Hello! I don't think that we can leave the thousand seperator as it is because the default (from https://github.com/spapas/django/blob/ffb3a065a4d60612f85f9474cb28b478b7e2760f/django/conf/global_settings.py#L422) is ``THOUSAND_SEPARATOR = ','`` which for Greek (and other EU countries) is used as a decimal seprator.

**Comment by timgraham** [comment]
Could you squash the commits and add release notes for 1.7.3 similar to 1ac32e76ac14323eef70142f57b8d7a3a192a829? I've updated the title of this PR to a commit message format that follows our guidelines. Thanks.

**Comment by spapas** [comment]
Done on #3875.

**Pull request closed without merging**
