### PR TITLE
Fixed #29109 -- Fixed display of auto-generated datetime/time input in admin form for Thai locale.

### PR DESCRIPTION
**Pull request by whs**
As DateTimeShortcut.js does not support %f, formats with %f are deprioritized.

### CODE REVIEW

**Comment by timgraham** [comment]
Could that be tested? I think https://github.com/django/django/blob/d0a42a14c06e033922f6d51e6384cba53be887b6/tests/admin_widgets/tests.py#L817 might be a similar test.

**Comment by whs** [comment]
Not sure how I should write a test that could apply to all locales. The replication is like this

1. Click the clock icon on date/time picker widget
2. Choose any time (eg. now)
3. The date appears with %f section as `undefined`

Writing a test that expect the correct value is not viable as different locales has different date format. I also feel writing test that check for "undefined" isn't the right thing to do.

I'm thinking that maybe adding a check to the JavaScript file so it will refuse to work with unsupported format specifier to make some of the existing tests fail. Is this ok?

**Comment by whs** [comment]
I've modified DateTimePickerShortcutsSeleniumTests.test_date_time_picker_shortcuts to run on all locales.

**Comment by claudep** [comment]
Selenium tests that run on all locales are somewhat lengthy.
Couldn't we test instead that first occurrences of DATETIME_INPUT_FORMATS  and TIME_INPUT_FORMATS for each language do not contain any letter outside {BcdHImMpSwxXyY}?

**Comment by whs** [comment]
Updated the test.

**Comment by claudep** [comment]
Thanks, I like that much better. Ready for a final detailed review (some spare new lines)?

**Comment by claudep** [comment]
Oh, and I would backport that to Django 2.0, so a note in docs/releases/2.0.3.txt would be great.

**Comment by whs** [comment]
Updated the changelog.

**Pull request merged**
