### PR TITLE
Fixed #26731 -- Allowed bytestring output with management commands on Python 2

### PR DESCRIPTION
**Pull request by claudep**
Thanks Darren Hobbs for the report.

### CODE REVIEW

**Comment by timgraham** [comment]
Ugh, worthing debugging Windows for this?

**Comment by timgraham** [comment]
Claude, I didn't have much luck easily debugging the Windows failures. Would you like me to continue trying or should we close this?

**Comment by claudep** [comment]
As I'm not touching Windows stuff, I let you decide.

**Comment by timgraham** [comment]
With the end of Python 2 support near, I'm not motivated to spend a lot of time on it. I'll leave a comment on the ticket asking if someone wants to debug those failures. Otherwise, we'll close the ticket after the release of Django 1.11.

**Pull request closed without merging**
