### PR TITLE
Refs #12118 -- Allowed "mode=memory" in test database names for sqlite

### PR DESCRIPTION
**Pull request by xrmx**
Let user specify in memory database names.

Removed restriction added in 8c99b7920e8187f98cf4d7dbd9918bd6c6da1238.

### CODE REVIEW

**Comment by timgraham** [comment]
@coldmind, please let us know if we missed the reason for this restriction.

**Comment by coldmind** [comment]
IIRC I added this restriction because in case test db name contains `mode=memory` it will be detected as in-memory https://github.com/django/django/commit/8c99b7920e8187f98cf4d7dbd9918bd6c6da1238#diff-d6fb66d008c65a72ab1415045d0c6907R520

If some user will set `mode=memory` and sqlite version is not allowing sharing in-memory database between threads, test execution will have incorrect behaviour

**Comment by timgraham** [comment]
I don't see the reason why have "mode=memory" in the database name will make it disk base. It will still be in-memory if it uses the file::... syntax, correct?

**Comment by coldmind** [comment]
It will be in-memory if user is under python3.4+ (on python2's sqlite3 database name `file:memorydb_test?mode=memory` will be not recognised as a link, so file will be created instead).

For example, if user on python2 will set database name which contains `mode=memory` it will not remove test database
https://github.com/django/django/blob/b215a3ab63d1c34746855594656e988561484fe3/django/db/backends/sqlite3/creation.py#L89-L91 and so on

**Comment by xrmx** [comment]
So what about adding a warning instead of an error if not six.PY3 and using that kind of string? BTW i was aware that the fact that the shared memory db is available only on py3.4+.

**Comment by timgraham** [comment]
Makes sense to me. Could you add a mention in the 1.8.6 release notes too?

**Comment by winsky2008** [comment]
try

**Comment by winsky2008** [comment]
try

**Comment by xrmx** [comment]
Uhm i think the test added is not being executed, btw should i move it under SQLiteTests?

**Comment by xrmx** [comment]
Regarding writing 1.8.6 notes @apollo13 hinted that this may not be considered a bugfix and thus backported to 1.8.

**Comment by timgraham** [comment]
My impression was that it's something that worked in 1.7? At least it's a problem with a feature introduced in 1.8.

**Comment by xrmx** [comment]
I'm writing a new app so it's not a regression for me :) OTOH since this changes something only for python 3.4+ i think the affected people are not many so i would appreciate if this can go in. So if we are fine with that i'll updated docs too. Should i update 1.9 / 2.0 releases notes too?

**Comment by timgraham** [comment]
We don't list bug fixes in major version release notes.

**Comment by timgraham** [comment]
merged in 3543fec3b739864c52de0a116dde3b0e5e885799, thanks.

**Comment by xrmx** [comment]
Thanks!

**Pull request closed without merging**
