### PR TITLE
Fixed #28755 -- Made check_for_language() include apps' locale directories.

### PR DESCRIPTION
**Pull request by ChillarAnand**
Ticket: https://code.djangoproject.com/ticket/28755

### CODE REVIEW

**Comment by ChillarAnand** [comment]
@timgraham Can you please check CI pipeline? Windows build is not getting triggered for all recent PRs.

**Comment by timgraham** [comment]
Should the behavior be documented?

**Comment by ChillarAnand** [comment]
This seems to be [documented here](https://docs.djangoproject.com/en/2.0/topics/i18n/translation/#how-django-discovers-translations).

**Comment by timgraham** [comment]
Okay, I see, so this is just a bug fix. I think the test should instead involve `check_for_language()` since `all_locale_paths()` is just a helper function that might be subject to refactoring.

**Comment by ChillarAnand** [comment]
Added test case for `check_for_language`.

**Pull request merged**
