### PR TITLE
Fixed #33191 -- Avoided clearing cached reference when saving child after parent.

### PR DESCRIPTION
**Pull request by AllenJonathan**

### CODE REVIEW

**Comment by AllenJonathan** [comment]
Tests coming up.

**Comment by AllenJonathan** [comment]
I'm unable to find the reason why one of the checks is failing. Any insight is appreciated.

**Comment by charettes** [comment]
It's a known flaky test failure; it's safe to ignore.

**Comment by felixxm** [comment]
@AllenJonathan Thanks :+1: I updated the related comment.

**Pull request merged**
