### PR TITLE
Fixed #33361 -- Fixed Redis cache backend crash on booleans.

### PR DESCRIPTION
**Pull request by jlaine**

### CODE REVIEW

**Comment by adamchainz** [comment]
Can you add a cache backend test that uses `cache.set()` as well? This could help catch the bug on other backends.

**Comment by jlaine** [comment]
Hi @adamchainz, which class in `cache/tests.py` should I be tacking on to in order to cover all backends? Thanks in advance for your insights!

**Comment by adamchainz** [comment]
`BaseCacheTests` , around `test_data_types`. IMO `test_data_types` could be converted into multiple set + get pairs, since currently it *really* only tests one type - a complex dict.

**Comment by jlaine** [comment]
Great, and you're absolutely right, we really want to test each primitive type separately. I've done this using ` with self.subTest()` as done in other places.

**Review by adamchainz — APPROVED** [review]

**Comment by felixxm** [comment]
@jlaine Thanks :+1: I added a release note and pushed small edits.

**Pull request merged**
