### PR TITLE
Fixed #34838 -- Corrected output_field of resolved columns for GeneratedFields.

### PR DESCRIPTION
**Pull request by pauloxnet**
Ref https://code.djangoproject.com/ticket/34838

### CODE REVIEW

**Comment by charettes** [comment]
Thanks for the patch @pauloxnet!

I wonder if we also need to account for the caching layer for the default `Col` of the `Field` instance.

```python
@cached_property
def cached_col(self):
    from django.db.models.expressions import Col
    
    return Col(self.model._meta.db_table, self.output_field)

def get_col(self, alias, output_field=None):
    if alias =! self.model._meta.db_table and (
        output_field is None
    ):
        output_field = self.output_field
    return super().get_col(alias, output_field)
```

**Comment by pauloxnet** [comment]
Thanks for continuing to investigate further @charettes :)

I applied your suggestions to the code of this PR, but feel free to modify the code in the branch if you feel it is appropriate to complete the patch, or open an alternative PR, because due to the time zone, I will be able to return to work on it in a few hours.

**Comment by pauloxnet** [comment]
> ```python
> 
> def get_col(self, alias, output_field=None):
>     if alias != self.model._meta.db_table and (output_field is None):
>         output_field = self.output_field
>     return super().get_col(alias, output_field)
> ```

This version of `get_col` broke tests and the local queries.

I'm going to revert to this original version for now:

```python
def get_col(self, alias, output_field=None):
    if output_field is None:
        output_field = self.output_field
    return super().get_col(alias, output_field)
```

**Comment by charettes** [comment]
@pauloxnet sorry for the back and forth, the issue you are encountering should be fixed here https://github.com/pauloxnet/django/pull/1.

Basically `Col` signature is `(alias, target: Field, output_field: Field | None = None)`, I forgot that we need to keep passing `target=self`

**Comment by charettes** [comment]
Minor but the PR references ticket-34834 instead of ticket-34838

**Comment by nessita** [comment]
@charettes Thank you for your guidance so far. would you say that this PR is ready for checkin? I can review general style but it would need an approval from an ORM expert for the semantic changes before proceeding with a merge. Thanks!

**Comment by charettes** [comment]
@nessita I believe it is yes!

**Comment by felixxm** [comment]
Thanks both :star2:

**Pull request merged**
