### PR TITLE
Fixed #26448 -- Improved the docs for running tests with different da…

### PR DESCRIPTION
**Pull request by krisys**
…tabase backends

### CODE REVIEW

**Comment by krisys** [comment]
@timgraham , Jenkins doesn't seem to show why docs build failed? Generating docs locally did not result in any problem though. Any pointers regarding this will be helpful. Thanks.

**Comment by charettes** [comment]
@krisys, `SQLite` was considered a spelling error.

**Comment by charettes** [comment]
You should be able to reproduce locally with `cd docs && sphinx-build -b spelling`

**Comment by timgraham** [comment]
merged in 361cb7a857f1ca69754c0e3a0038097d09508f2c, thanks!

**Comment by krisys** [comment]
Thanks, @charettes  and @timgraham .

**Pull request closed without merging**
