### PR TITLE
Attempt to group by ref by default.

### PR DESCRIPTION
**Pull request by charettes**
Doing a test run on Oracle for a mailing list discussion:

https://groups.google.com/g/django-developers/c/1hqw_HTpn_8/m/EwCYMlTiCAAJ

### CODE REVIEW

**Comment by charettes** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
@charettes Unfortunately, you cannot group by column aliases on Oracle.

**Comment by charettes** [comment]
@felixxm I guess we could have a database feature for that which the compiler could use to perform [the subquery pushdown detailed on the mailing list](https://groups.google.com/g/django-developers/c/1hqw_HTpn_8/m/EwCYMlTiCAAJ).

That would allow us to remove 6dbe56ed7855f34585884a2381fb1cec22ddc824 and potentially add support for [subquery group by on Oracle](https://github.com/django/django/search?q=supports_subqueries_in_group_by).

**Comment by felixxm** [comment]
Creating a subquery only looks like a good solution for a limited number of cases. As far as I'm aware it will also change an execution plan and can cause a performance regression :thinking:

**Comment by charettes** [comment]
I'm not versed enough in Oracle and its buffer cache to take position here so I'll close this PR for now. It'd be great if you could chime in on the django-developer thread though since you have a more knowledge in this area.

An interesting finding though is that we could likely change back `Expression.get_group_by_cols(self, alias)` signature to `(self)` and have the caller special case `alias is not None`: if the database supports `GROUP BY` reference then default to it otherwise call `expr.get_group_by_cols()`.

**Pull request closed without merging**
