### PR TITLE
I have Implemented ABS method in expressions for Django models to use ABS method in Django ORM.

### PR DESCRIPTION
**Pull request by Sushil2308**
**Use Case:**
This pull request introduces the ABS (absolute value) method in Django expressions. The ABS method can be used in expressions to calculate the absolute value of a numerical field, providing flexibility for developers when implementing various formulas or computations in Django models.

**Details:**
Added ABS method in expressions.
Supports Integer, Float, and Decimal fields.
Use cases include implementing custom formulas or calculations in Django models.

**How developers can use this:**

# views.py
from django.shortcuts import render
from django.db.models import F, ABS
from .models import NumberModel

def abs_example(request):
    # Annotate the queryset with the absolute value of the 'value' field
    queryset = NumberModel.objects.annotate(abs_value=ABS(F('value')))

    # Retrieve the annotated values
    result_list = list(queryset.values('value', 'abs_value'))

    return render(request, 'abs_example.html', {'result_list': result_list})

{% for result in result_list %}
    Value: {{ result.value }} | Absolute Value: {{ result.abs_value }}<br>
{% endfor %}

Thanks :)

### CODE REVIEW

**Comment by felixxm** [comment]
`Abs()` function is already implemented.

**Comment by Sushil2308** [comment]
But Abs() is a python function and I have implemented on the ORM level.

**Comment by felixxm** [comment]
No, it's not https://docs.djangoproject.com/en/5.0/ref/models/database-functions/#abs.

Please check docs or use support channels if you have further question.

**Comment by Sushil2308** [comment]
Ok...

**Pull request closed without merging**
