### PR TITLE
Fixed #27119 -- Cached BaseFormSet.management_form property

### PR DESCRIPTION
**Pull request by claudep**
Thanks Karol Sztajerwald for the initial patch.

### CODE REVIEW

**Comment by timgraham** [comment]
Sorry, it wasn't captured in the PR but discussing with @charettes, his opinion is that the test you wrote isn't needed (although I don't know if it hurts). Rather, he was looking for a test that shows the cached property is cleared if a formset is validated multiple times (or something like that).

I think the initial patch doesn't need crediting since it's my suggestion from the ticket (and you needn't credit me).

**Comment by charettes** [comment]
An additional test doesn't hurt here. As Tim pointed out I just wanted to make sure `management_form` is cleared in `BaseFormSet.full_clean()`.

**Comment by claudep** [comment]
Simon, do you have a use case where this management form caching might be problematic? So I can build a test which makes sense...

**Comment by charettes** [comment]
@claudep maybe that was me being over cautious. I figured out that if you call `full_clean()` manually on an already validated formset instance you might as well have assigned some newer data to the formset. In this case the cached `management_form` would be bound to the old data.

**Comment by claudep** [comment]
Yes, I tried that way, but once full_clean has been called, all subform errors are already cached, too. So I failed to create a realistic test case. But this does no mean there is none, of course.

**Comment by charettes** [comment]
@claudep if all subforms are already cached anyway I don't see much benefit to test it since this use case is simply not supported. Sorry for wasting both yours and @Backscratcher time.

**Comment by claudep** [comment]
It's not wasting time, it was worth checking!

**Pull request merged**
