### PR TITLE
Allow ordering of models in the admin index

### PR DESCRIPTION
**Pull request by olivierdalang**
This PR allows to display the models in a specific order per app on the admin index and the app index, using a new **`order_in_index`** option on `ModelAdmin`.

When left to default (None), the models are sorted alphabetically (backwards compatible).

This helps deal with a common case where there is some logical order between models that does not match alphabetical order (e.g. `Continents, Countries, Counties, Cities` is much more usable than `Cities, Continents, Counties, Countries`). There is no easy way to achieve this, except by prepending verbose_name with spaces, which is not very elegant.

### CODE REVIEW

**Comment by felixxm** [comment]
Accepted ticket is required for all new features.

**Comment by olivierdalang** [comment]
Oops my bad, I'm not used to the process yet... I'll open a ticket. Can this stay open in the mean time ?

**Comment by hramezani** [comment]
Can be related to [this ticket](https://code.djangoproject.com/ticket/25671)

**Comment by olivierdalang** [comment]
> Can be related to [this ticket](https://code.djangoproject.com/ticket/25671)

Thanks hadn't found it. I reopened the ticket, hope this is OK.

**Comment by carltongibson** [comment]
Closing as per ticket-25671

**Pull request closed without merging**
