### PR TITLE
Fixed #35873 -- Corrected Form.as_table() call in form docs.

### PR DESCRIPTION
**Pull request by Antoliny0919**
#### Trac ticket number

ticket-35873

#### Branch description
Modified the incorrect part of the as_table call example.

#### Checklist
- [x] This PR targets the `main` branch. 
- [x] The commit message is written in past tense, mentions the ticket number, and ends with a period.
- [x] I have checked the "Has patch" ticket flag in the Trac system.
- [ ] I have added or updated relevant tests.
- [x] I have added or updated relevant docs, including release notes if applicable.
- [ ] I have attached screenshots in both light and dark modes for any UI changes.

### CODE REVIEW

**Comment by sarahboyce** [comment]
Thank you for this @Antoliny0919 

Looking at the docs, I see that the [docs for as_div()](https://docs.djangoproject.com/en/5.1/ref/forms/api/#as-div) formats the html with a structure like:
```
...containing one field, such as:

.. code-block:: pycon

    >>> f = ContactForm()
    >>> f.as_xx()

… gives HTML like:

.. code-block:: html
```
I think this looks easier to read than the printing. Do you think we should align `as_div()`, `as_p()`, `as_ul()`, and `as_table()` to format this the same?

**Comment by Antoliny0919** [comment]
> Thank you for this @Antoliny0919
> 
> Looking at the docs, I see that the [docs for as_div()](https://docs.djangoproject.com/en/5.1/ref/forms/api/#as-div) formats the html with a structure like:
> 
> ```
> ...containing one field, such as:
> 
> .. code-block:: pycon
> 
>     >>> f = ContactForm()
>     >>> f.as_xx()
> 
> … gives HTML like:
> 
> .. code-block:: html
> ```
> 
> I think this looks easier to read than the printing. Do you think we should align `as_div()`, `as_p()`, `as_ul()`, and `as_table()` to format this the same?

@sarahboyce 
I didn't notice this part :)
I think that's a good idea. I agree to make as_p, as_ul, and as_table the same as the output format of as_div.
It is a much better improvement in terms of readability. 💪

**Review by sarahboyce — APPROVED** [review]
Thank you!

**Comment by Antoliny0919** [comment]
I have one question :) @sarahboyce 
Is there no need to generate Issue when modifying simple docs as above?

**Comment by sarahboyce** [comment]
> I have one question :) @sarahboyce Is there no need to generate Issue when modifying simple docs as above?

You don't have to create a ticket for very small changes - if it's bigger, we can create a ticket
It's hard to judge. Typos are ones where we don't need a ticket for example

**Comment by smithdc1** [comment]
`as_div()` is the recommended way. The other methods are kept for backward compatability.

The html for ul/table/p take up quite a bit of room on the page.

How about we shrink that whole section to just a short note saying they exist, but they are not recommend?

**Comment by sarahboyce** [comment]
> `as_div()` is the recommended way. The other methods are kept for backward compatability.
> 
> The html for ul/table/p take up quite a bit of room on the page.
> 
> How about we shrink that whole section to just a short note saying they exist, but they are not recommended?

Ok so, how about for p/ul/table we remove the examples and have something like:
```
.. warning::
    Using ``as_table()`` is not recommended, use :meth:`.Form.as_div` instead.
```
So we end up with:
screenshot of the docs with warnings for p/ul/table

**Comment by smithdc1** [comment]
Maybe even without the warnings, as there's a similar note on line 661. 🤔

**Comment by sarahboyce** [comment]
So just remove the examples, no further references that it's not recommended

**Comment by Antoliny0919** [comment]
Should I remove both html, pycon code blocks? or only remove html code block ??

**Comment by sarahboyce** [comment]
> Should I remove both html, pycon code blocks? or only remove html code block ??

I think, given @smithdc1 feedback, we should go with your original suggestion: https://github.com/django/django/commit/92380531172caf54d0029b0512806655dd3ae8f5
Sorry for messing you about.
I think David is highlighting that we might want to deprecate as_p/ul/table in future and so my suggestion feels more like we're investing in it

**Review by sarahboyce — APPROVED** [review]
Thank you!

**Pull request merged**
