### PR TITLE
Refs #27795 -- Removed unneeded force_text calls from the Oracle backend.

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
I saw that `introspection.py` files for other backends had been already fixed in https://github.com/django/django/commit/8346680e1ca4a8ddc8190baf3f5f944f6418d5cf. I didn't audit any other files 🤔.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
I checked `django/db/backends/oracle/*`.

**Comment by timgraham** [comment]
Looks good, thanks.

**Pull request merged**
