### PR TITLE
Removed Oracle NULL workaround in AreaField.

### PR DESCRIPTION
**Pull request by sir-sigurd**
Unused since 1b1ea63f6a4784e213c059c69beccaea20bc1a92.

### CODE REVIEW

**Comment by sir-sigurd** [comment]
buildbot, test on oracle.

**Comment by sir-sigurd** [comment]
buildbot, test on oracle.

**Comment by sir-sigurd** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Pull request merged**
