### PR TITLE
Fixed #34971 -- Doc'd additional loggers.

### PR DESCRIPTION
**Pull request by AryanGHM**
Hello, as a new contributor, I have created a pull request (PR) to enhance the original patch proposed for this [ticket](https://code.djangoproject.com/ticket/34971). Please consider this PR as a draft.

### CODE REVIEW

**Comment by felixxm** [comment]
Thanks for this patch :+1: However, #17492 is under review, there is no need for a new PR.

**Comment by nessita** [comment]
@AryanGHM Hello! Do you have time to work on this? If yes, I'm inclined to close PR #17492 since it hasn't had a response/update in 10 days, so we could re-open this one instead. Let me know please!

**Comment by nessita** [comment]
Reopening then!

**Comment by AryanGHM** [comment]
@nessita Thank you very much! Please inform me if anything needs to be changed, and if there is anything from the last PR that isn't mentioned here for refreshment.

**Comment by nessita** [comment]
> @nessita Thank you very much! Please inform me if anything needs to be changed, and if there is anything from the last PR that isn't mentioned here for refreshment.

Thank you for your contribution. As a first step, I would suggest to ensure that the proposed changes follows [the guidelines](https://docs.djangoproject.com/en/dev/internals/contributing/writing-documentation/#guidelines-for-restructuredtext-files). Specifically, the lines should be wrapped at 79 cols and there shouldn't be multiple blank lines between paragraphs.

**Comment by AryanGHM** [comment]
Alright thanks. I will look into it.

**Comment by nessita** [comment]
> Alright thanks. I will look into it.

Thanks, I have pushed some edits and merged this work. Welcome aboard :boat:!

**Comment by AryanGHM** [comment]
Thank you it was my pleasure!

**Pull request merged**
