### PR TITLE
Fixed #24472 - Defined internal types explicitly for related fields

### PR DESCRIPTION
**Pull request by coldmind**
https://code.djangoproject.com/ticket/24472

### CODE REVIEW

**Comment by timgraham** [comment]
I left a reply on the ticket, did you get notified about it?

**Comment by coldmind** [comment]
@timgraham, yes, I just left answer there.

**Comment by timgraham** [comment]
Could you add tests?

**Comment by coldmind** [comment]
@timgraham, yes, I will try to add some soon.

**Comment by timgraham** [comment]
Ping me if you resume work on this issue, or send a new PR.

**Pull request closed without merging**
