### PR TITLE
Fixed #24653 -- Fixed MySQL database introspection when using 'read_default_file' option

### PR DESCRIPTION
**Pull request by zshimanchik**

### CODE REVIEW

**Comment by timgraham** [comment]
Any ideas if we could add a test for this? I guess the existing tests passing might be good enough.

By the way, the "[1.9.x]" prefix is only needed for commits to the `stable/1.9.x` branch.

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
@claudep, any concerns with this?

**Comment by claudep** [comment]
Looks good, and yes, existing tests passing is sufficient IMHO.

**Comment by timgraham** [comment]
merged in 65aa94200b3d10d515b15a78898c3692cd57e6c7, thanks!

**Pull request closed without merging**
