### PR TITLE
Refs #27795 -- Removed unneeded force_text calls in widgets.py.

### PR DESCRIPTION
**Pull request by jdufresne**

### CODE REVIEW

**Comment by timgraham** [comment]
Did you audit only that file? I'm not sure exactly how @claudep is going about this. but it would be nice to check all of `django.forms`, for example, rather than going file by file.

**Comment by jdufresne** [comment]
Yes, so far only this file was audited as unneeded uses of `force_text()` were noticed while working on PR #8385. I'll try to find some time to audit more of `django.forms`.

**Comment by claudep** [comment]
Wait, I'll revive my sleeping patch...

**Comment by claudep** [comment]
Here we go: #8390

**Comment by jdufresne** [comment]
Closing in favor fo @claudep's more complete patch.

**Pull request closed without merging**
