### PR TITLE
Fixed #27171 -- Added unicode_literals and coding preamble to all files in startapp template on Python 2.

### PR DESCRIPTION
**Pull request by baterson**
If you using non askii symbols on python2, like Cyrillic alphabet, you still have an error
'SyntaxError: Non-ASCII character' because encoding not specified. 
Also admin and views templates needed unicode_literals too.
For example, when you put some comments with non askii characters or raise error message with it.

### CODE REVIEW

**Comment by timgraham** [comment]
This was added in `models.py` to mitigate a possible migration bug [#24949](https://code.djangoproject.com/ticket/24949). I'm not convinced of the value of these changes, especially with the end of Python 2 support so near.

**Comment by baterson** [comment]
So in next versions  `{{ unicode_literals }}` variable will be deleted from that templates? If not, this changes will be helpful for people who working with python2 and use non askii alphabet . I think many of them, specify encoding every time, like me.

**Comment by timgraham** [comment]
There will be one more version to support Python 2 (Django 1.11), then yes, this will be removed.

@MarkusH, since you introduced the first unicode_literals, any opinion?

**Comment by MarkusH** [comment]
I guess that makes sense, yes. I put it into new files all the time anyway.

**Comment by timgraham** [comment]
Okay, we also need a Trac ticket and a test update.

**Comment by baterson** [comment]
@timgraham sorry it is my first contribute, can you explain a bit, what should I do next

**Comment by timgraham** [comment]
Create a ticket: https://code.djangoproject.com/newticket
Add a test similar to the one in 5d428908218e3692d1bc7e4ada6235029ae9e45c

**Comment by baterson** [comment]
thanks, I'll do it today, later

**Comment by baterson** [comment]
I update test case and create ticket https://code.djangoproject.com/ticket/27171#ticket

**Comment by timgraham** [comment]
Not in `tests.py-tpl` though?

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by baterson** [comment]
Not sure `tests.py` need it, but I can modify it too, for complete change.

**Comment by baterson** [comment]
Update it too

**Pull request merged**
