### PR TITLE
Update make.bat to add option spelling

### PR DESCRIPTION
**Pull request by swright573**
Spelling is an existing option in Makefile but had been left out of make.bat.

### CODE REVIEW

**Review by carltongibson — CHANGES_REQUESTED** [review]
Hi @swright573 — thanks for this. 

Can you please revert the unrelated changes (or pull then into a separate PR if you mean to propose them)? 

I suspect the `spelling` option omission is no more than a statement of the age of the project, and that it never got added to the `.bat` file, so in principle seems a good  addition.

**Comment by swright573** [comment]
Sorry for the trouble. I have closed this pull request and will submit a new one.

This is my first pull request in the "real" world and I screwed it up. I think I know why. I made my change to make.bat in the main branch of my fork of django/django. I submitted the pull request thinking that it was for the state of the branch at that moment and any changes I committed after that would not be included. That was my error. What I should have done is created a new branch and changed only the one file (make.bat) that I intended to submit. If I had other changes I was working on, I should have created another branch for that work. Again sorry for the trouble.

**Comment by carltongibson** [comment]
Hi @swright573, no problem at all!  

Your description sounds correct. A branch changing just the single file should open a clean PR. 

Welcome aboard! ⛵️

**Comment by carltongibson** [comment]
Hi @swright573, no problem at all!  

Your description sounds correct. A branch changing just the single file should open a clean PR. 

Welcome aboard! ⛵️

**Pull request closed without merging**
