### PR TITLE
Updated template tests to create their own engine.

### PR DESCRIPTION
**Pull request by prestontimmons**
This continues work to treat Django templates as a library.

### CODE REVIEW

**Comment by timgraham** [comment]
Looks okay to me. Does the `Engine()` need to be initialized for each test method or could we put that in `setUpClass()` instead?

**Comment by prestontimmons** [comment]
Good idea. This uses ``setUpClass()`` now.

**Comment by timgraham** [comment]
It would probably be wise to call `super()` in the `setUpClass()` methods, at least on those classes that inherit `SimpleTestCase` or below.

Got your commit bit setup? Want to merge this yourself? Guidelines are documented in [Handling pull requests](https://docs.djangoproject.com/en/dev/internals/contributing/committing-code/#handling-pull-requests).

**Comment by prestontimmons** [comment]
Okay. I'll merge this when I get a chance to review those docs.

**Comment by prestontimmons** [comment]
@timgraham Pushed my first commit. Thanks!

**Pull request merged**
