### PR TITLE
Fixed #26573 -- Added descriptive error message for malformed if/else/elif template tags.

### PR DESCRIPTION
**Pull request by inondle**
Patch for ticket https://code.djangoproject.com/ticket/26573

### CODE REVIEW

**Comment by timgraham** [comment]
I suspect it would be more appropriate to raise `TemplateSytaxError` here or elsewhere. A test that verifies the message, likely using `self.assertRaisesMessage`, is also needed.

**Comment by inondle** [comment]
Ok, I'll get started on that

**Comment by inondle** [comment]
@timgraham 

I wasn't sure about where to put this test but I placed it inside the `tests/template_tests/syntax_tests/test_if.py` file. Is that a good spot or is somewhere else more suitable?

**Comment by timgraham** [comment]
Yes, that seems a likely candidate.

**Comment by inondle** [comment]
@timgraham updated pull request

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
The debug view doesn't highlight the correct line in this case. Could you investigate that?

a

**Comment by inondle** [comment]
Yeah ill look into it

**Comment by inondle** [comment]
@timgraham 

So I think I've figured out this weird behavior. The issue is caused by the fact that when the parser is going through each template tag it selects a certain function[1] to evaluate each type of token. When it encounters an `{% if ... %}` tag it selects the `do_if` function in defaulttags.py[2]. 

This function runs through the whole if/elif/else/endif series and checks all of these tags. If an error is raised in one of the tags following the `if` tag the parser will catch the error raised by `do_if` and raise another error with the `do_if` function's error embedded inside it. 

These two errors, one from the parser and one from `do_if`, can have conflicting information as seen above. The parser was evaluating the `if` tag and reports that the error occurred there whereas the `do_if` function was evaluating the `else if` tag and reports the error there.

[1] https://github.com/django/django/blob/2f0e0eee450775a71ac3eb42707dcd970ede42c8/django/template/base.py#L510
[2] https://github.com/django/django/blob/2f0e0eee450775a71ac3eb42707dcd970ede42c8/django/template/defaulttags.py#L891

**Comment by inondle** [comment]
My guess would be that the easiest way to fix this would be to create a new function to evaluate the if tags, elif tags, else tags, and endif tags individually. That way the parser and tag-eval-function would stay on the same tag and any errors that occur should agree with each other.

**Comment by timgraham** [comment]
I'm not too familiar with this code. I don't mind committing this as is and then possibly addressing that issue in a separate ticket if necessary.

**Comment by inondle** [comment]
Sounds good, these two issues arent very related so it makes sense to open up a new ticket

**Pull request merged**
