### PR TITLE
Removed Jinja2 dependency from admin_checks tests.

### PR DESCRIPTION
**Pull request by jdufresne**

### CODE REVIEW

**Comment by timgraham** [comment]
I guess the dummy backend could be used instead, as long as https://github.com/django/django/pull/10474 isn't accepted.

**Comment by jdufresne** [comment]
Good point. I'll rework this patch to use dummy until a decision is made there.

**Comment by jdufresne** [comment]
Updated to use dummy backend.

**Comment by carltongibson** [comment]
Hey @jdufresne. This is fine. 

Can I just ask about the motivation? On the [ticket for removing the dummy backend](https://code.djangoproject.com/ticket/29820) you have: 

> ...is there an expectation that developers will install test/requirements/py3.txt before running tests? The ​documentation suggests this is so.

`jinja2` is there, so why are we jumping through the hoops to avoid it here? 
(I'm not seeing it.)

Ta.

**Comment by jdufresne** [comment]
Good question.

I think Django should take one of two positions with regards to internal testing:

1. Expect environments to first install `tests/requirements/py3.txt` before running tests

The [documentation suggests this is the case](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/unit-tests/#quickstart). I also think it is the preferable approach as it ensures tests environments are more consistent; allowing easier to reproduce test failures and fewer surprises by skipped tests.

If this is agreeable, I would prefer to close this PR as unmerged. There are a number of `@skipIf`s that could be removed with this assumption in place.

```
./tests/model_fields/test_imagefield.py:101:@skipIf(Image is None, "Pillow is required to test ImageField")
./tests/model_fields/test_imagefield.py:195:@skipIf(Image is None, "Pillow is required to test ImageField")
./tests/model_fields/test_imagefield.py:309:@skipIf(Image is None, "Pillow is required to test ImageField")
./tests/model_fields/test_imagefield.py:318:@skipIf(Image is None, "Pillow is required to test ImageField")
./tests/model_fields/test_imagefield.py:327:@skipIf(Image is None, "Pillow is required to test ImageField")
./tests/model_fields/test_imagefield.py:337:@skipIf(Image is None, "Pillow is required to test ImageField")
./tests/model_fields/test_imagefield.py:348:@skipIf(Image is None, "Pillow is required to test ImageField")

./tests/forms_tests/tests/test_renderers.py:44:@unittest.skipIf(jinja2 is None, 'jinja2 required')
./tests/template_backends/test_jinja2.py:17:@skipIf(jinja2 is None, "this test requires jinja2")

./tests/template_tests/syntax_tests/test_numpy.py:13:@skipIf(numpy is False, "Numpy must be installed to run these tests.")
```

I'll happily open a PR to do so.

2. Allow tests to run in mixed environments that may not have all of the basic

This seems to be the current state in practice. If this is desirable then Jinja2 may not exists which should not cause the tests to fail.

---

WDYT? Shall we go with 1?

**Comment by timgraham** [comment]
It could be okay - probably that discussion should happen on the django-developers mailing list. I think part of the reason for the current approach is to ensure that all of Django's optional dependencies are optional. Probably mocking could be used to "uninstall" a library to test an alternate code path if needed. The other reason was to ease onboard of new contributors but install dependencies seems less of a hurdle these days.

**Comment by carltongibson** [comment]
There's a third option, which we [use on DRF](https://github.com/encode/django-rest-framework/blob/18ad3290ef228dce8bb9d0feb5903f650f0ebc9f/tox.ini#L30-L34)

```
[testenv:base]
; Ensure optional dependencies are not required
deps =
        django
        -rrequirements/requirements-testing.txt
```

Here we have a build that just installs the required items and runs the tests. It was a bit of a pain to get going (in that you need to make sure all the skipIfs are in place) but it has saved us a few times, when we forget to import from compat say, i.e. when we illicitly make an optional required. 

(This'd probably be my favoured route — but, Yes, as ever, mailing list... 🙂)

**Comment by timgraham** [comment]
Right, that's what we're doing now, absent a build on Jenkins.

It'd be slightly complicated by https://github.com/django/django/pull/10406 which suggests adding a somewhat optional (it's difficult to identify which tests need to be skipped merely by code review) dependency on sqlparse for SQLite.

**Comment by jdufresne** [comment]
If I run tests locally without first installing `requirements/py3.txt`, this is the only test that fails for me. I see 1041 skipped tests. So some diligence has already been done to ensure tests work in mixed environments.

**Comment by carltongibson** [comment]
@jdufresne Super!

**Comment by jdufresne** [comment]
I think point you both raised is a good one: by not making dependencies required for tests, we help ensure that they aren't required at runtime. So how about we stick to the status quo for now and continue with option "2" from above. If so, I think using the dummy backend is a good choice so the test runs with or without Jinja2 installed.

**Comment by timgraham** [comment]
I added a [master-no-requirements](https://djangoci.com/job/master-no-requirements/) build to Jenkins. All tests are passing.

**Pull request merged**
