### PR TITLE
Fixed #32910 -- Unified different plural equations for the same language in contrib apps.

### PR DESCRIPTION
**Pull request by felixxm**
Thanks Martin Svoboda for the report and initial patch.

~~Regression in e3e48b00127c09eafe6439d980a82fc5c591b673.~~

### CODE REVIEW

**Review by carltongibson — APPROVED** [review]
OK, so looks good. Thanks @felixxm. I'd leave it to give @claudep a chance to look too but...

**Comment by claudep** [comment]
Discussion is happening on the ticket for now.

**Comment by felixxm** [comment]
I removed release notes.

**Review by claudep — APPROVED** [review]
Looks good, thanks!

**Comment by felixxm** [comment]
Thanks both :star2:

**Pull request merged**
