### PR TITLE
Fixed #22705 -- Fixed QuerySet.bulk_create() on models without any fieds for Oracle.

### PR DESCRIPTION
**Pull request by timgraham**
Fixed on other backends by 134ca4d.

https://code.djangoproject.com/ticket/22705

### CODE REVIEW

**Comment by charettes** [comment]
LGTM

**Comment by timgraham** [comment]
The test doesn't pass on Oracle.
Query: `INSERT INTO "BULK_CREATE_NOFIELDS" ("ID") SELECT DEFAULT FROM DUAL UNION ALL SELECT DEFAULT FROM DUAL`
Error: `ORA-00936: missing expression`
Possibly related to [#22669](https://code.djangoproject.com/ticket/22669). Need advice from Oracle experts on how to proceed. @shaib @jarshwah @felixxm?

**Comment by felixxm** [comment]
You should add ``pk_default_value``
```python
class DatabaseOperations(BaseDatabaseOperations):
    ....
    def pk_default_value(self):
        return "NULL"
```
to ``backends/oracle/operations.py``  (like in ``backends/sqlite3/operations.py``) to get
```sql
INSERT INTO "BULK_CREATE_NOFIELDS" ("ID") SELECT NULL FROM DUAL UNION ALL SELECT NULL FROM DUAL
```

**Comment by felixxm** [comment]
If you want to put default value into ``ID`` then I think that:
```sql
INSERT INTO "BULK_CREATE_NOFIELDS" ("ID") VALUES (DEFAULT)
```
is only way

**Comment by felixxm** [comment]
We can also add ``pk_default_value``:
```python
class DatabaseOperations(BaseDatabaseOperations):
    ...
    def pk_default_value(self):
        return "NULL"

```
to ``backends/oracle/operations.py`` (like in ``backends/sqlite3/operations.py``) to obtain:
```sql
INSERT INTO "BULK_CREATE_NOFIELDS" ("ID") 
SELECT NULL FROM DUAL UNION ALL SELECT NULL FROM DUAL
```
it will work with appropriate db trigger (which fill pk if it is ``Null``).

**Comment by timgraham** [comment]
buildbot, test on oracle.

**Comment by timgraham** [comment]
Thanks Mariusz, updated with your suggestion and the tests are now passing (except for Oracle GIS which are existing failures).

**Pull request merged**
