### PR TITLE
Fixed #34484, Fixed #34482 -- Fixed cloning/deep cloning HttpRequest, HttpResponse, and their subclasses.

### PR DESCRIPTION
**Pull request by felixxm**
ticket-34482
ticket-34484

Regressions in d7f5bfd241666c0a76e90208da1e9ef81aec44db and 6220c445c40a6a7f4d442de8bde2628346153963.

Thanks Adam Johnson and Márton Salomváry for reports.

### CODE REVIEW

**Comment by felixxm** [comment]
@adamchainz Thanks :+1: updated.

**Review by adamchainz — APPROVED** [review]

**Comment by adamchainz** [comment]
Hopefully, we can restore picklea-bility in the future, but it will need to pass the new tests.

**Review by nessita — APPROVED** [review]
Looks good, thank you!

**Comment by felixxm** [comment]
Thanks both for checking :+1:

**Pull request merged**
