### PR TITLE
Refs #15667 -- Removed trailing newline from widget attrs.html template.

### PR DESCRIPTION
**Pull request by ivanchenkodmitry**
Let's remove last "\n" in attrs rendering.
With this characters select options becomes like this (example from django-money)

            <option value="XFU" \n>UIC-Franc</option>
            \n\n
            <option value="USD" selected\n>US Dollar</option>
            \n\n
            <option value="UGX" \n>Uganda Shilling</option>
            \n\n
            <option value="UYU" \n>Uruguayan peso</option>

'\n' in the ends of options is unuseful when you printing the form.
Also now in most of tests people are using condition like this:

`<option value="USD" selected>US Dollar</option> in form.as_p`

Such tests become failed with the last '\n' in the option tag.
I think this is important as case of backward compatibility.

Thanks.

### CODE REVIEW

**Comment by MarkusH** [comment]
This PR is empty. Did you forget to commit some changes?

**Comment by timgraham** [comment]
Maybe GitHub is ignoring newline changes in the diff? Could you add a test for that so it's not inadvertently re-added? Thanks.

**Comment by ivanchenkodmitry** [comment]
Yes, Looks like Git ignore the empty line.
I'll try to cover this with tests

**Comment by timgraham** [comment]
Here's the test I came up with it -- unfortunately, even without your patch the newline isn't there so the test passes. I'm not sure why. I can reproduce the problem but after downloading your branch I still see the problem.

@prestontimmons, any ideas about how to deal with this? I fear that requiring developers to edit files without affecting the trailing newline will be difficult to enforce, so perhaps some other solution would ease this.

```diff
diff --git a/tests/forms_tests/widget_tests/test_widget.py b/tests/forms_tests/widget_tests/test_widget.py
index 3911627..f1c551f 100644
--- a/tests/forms_tests/widget_tests/test_widget.py
+++ b/tests/forms_tests/widget_tests/test_widget.py
@@ -3,6 +3,8 @@ from __future__ import unicode_literals
 from django.forms import Widget
 from django.test import SimpleTestCase
 
+from .base import WidgetTest
+
 
 class WidgetTests(SimpleTestCase):
 
@@ -10,3 +12,14 @@ class WidgetTests(SimpleTestCase):
         widget = Widget()
         self.assertIs(widget.value_omitted_from_data({}, {}, 'field'), True)
         self.assertIs(widget.value_omitted_from_data({'field': 'value'}, {}, 'field'), False)
+
+
+class WidgetAttrsTest(WidgetTest):
+
+    def test_no_trailing_newline_in_attrs(self):
+        class AttrsWidget(Widget):
+            template_name = 'django/forms/widgets/attrs.html'
+
+        widget = AttrsWidget()
+        output = widget.render('name', 'value', attrs={}, renderer=self.django_renderer)
+        self.assertEqual(output, '')
```

**Comment by prestontimmons** [comment]
@timgraham Yes, the newline enforcement is tricky to remember. There were some tests that failed at one point, but they may have all been updated to use `assertHTMLEqual`. Other options may be to use the `spaceless` tag, or add the ability to strip to the `include` tag.

The reason the test you wrote still passes is this line:

https://github.com/django/django/blob/b52c73008a9d67e9ddbb841872dc15cdd3d6ee01/django/forms/renderers.py#L32

I was able to produce the failure with a small change:

```diff
diff --git a/tests/forms_tests/widget_tests/test_widget.py b/tests/forms_tests/widget_tests/test_widget.py
index 3911627..87bab90 100644
--- a/tests/forms_tests/widget_tests/test_widget.py
+++ b/tests/forms_tests/widget_tests/test_widget.py
@@ -3,6 +3,8 @@ from __future__ import unicode_literals
 from django.forms import Widget
 from django.test import SimpleTestCase
 
+from .base import WidgetTest
+
 
 class WidgetTests(SimpleTestCase):
 
@@ -10,3 +12,16 @@ class WidgetTests(SimpleTestCase):
         widget = Widget()
         self.assertIs(widget.value_omitted_from_data({}, {}, 'field'), True)
         self.assertIs(widget.value_omitted_from_data({'field': 'value'}, {}, 'field'), False)
+
+
+class WidgetAttrsTest(WidgetTest):
+
+    def test_no_trailing_newline_in_attrs(self):
+        class AttrsWidget(Widget):
+            template_name = 'django/forms/widgets/input.html'
+
+        widget = AttrsWidget()
+        output = widget.render('name', 'value', attrs={}, renderer=self.django_renderer)
+        self.assertEqual(
+            output, '<input type="" name="name" value="value" />',
+        )
```

**Comment by timgraham** [comment]
Thanks Preston. I updated this branch.

**Comment by ivanchenkodmitry** [comment]
Thank you guys!
this is really what I need.

**Comment by timgraham** [comment]
Perhaps `{% include %}` could do `.rstrip('\n')` on whatever it renders. I don't think that's likely to break a use case (famous last words).

**Comment by prestontimmons** [comment]
Jinja2 does something similar:

http://jinja.pocoo.org/docs/dev/templates/#whitespace-control

* a single trailing newline is stripped if present
* other whitespace (spaces, tabs, newlines etc.) is returned unchanged

**Comment by timgraham** [comment]
The idea was raised previous in [#9198](https://code.djangoproject.com/ticket/9198) but Malcolm said, "For backwards compatibility reasons we cannot change the default behaviour now (there will be templates that rely on the newline being inserted)." I'm skeptical about that. I'll write to the mailing list later.

**Comment by carljm** [comment]
It seems quite likely to me that there are templates in the wild relying on preservation of the final newline. People render preformatted text (e.g. text emails) using DTL. I probably have some text email templates in older projects myself that would break with that change.

We could add a new option to `{% include %}`, though.

**Comment by adamchainz** [comment]
I too have used DTL for text emails that would break under that behaviour. New option to `include` sounds good to me.

**Comment by timgraham** [comment]
In the long run, I think removing the traling newline is quite a more sensible default. For example, I wouldn't expect this code to have a newline inserted between it:
```
{% include "foo.txt" %}
{% include "bar.txt" %}
```
An option for  `{% include %}` seems superfluous given that if you were writing 
```
{% include "foo.txt" %}{% include "bar.txt" %}
```
now you can write the first thing which is much more intuitive.

 How about a `keep_trailing_newline` TEMPLATES option for backwards compatibility for those who don't want to adapt their templates for the new behavior?

**Comment by carljm** [comment]
An engine option may be better than an option to `{% include %}`, though it doesn't allow us to ensure that we strip the newline in the specific case of attrs.

How we default the engine option I guess just depends on how seriously we take backwards compatibility. If we default it to strip and make people add the config to preserve the old behavior, that's not really backwards compatible. Historically (as seen in Malcolm's comment) we would choose to err on the side of actual backwards compatibility in a case like this, even if it didn't result in the ideal future behavior. But the adaptation isn't hard in this case, so I won't object if the choice is to break back-compat.

If it's not a per-include choice, of course, we have to break overall back-compat to preserve form-attr-rendering back-compat.

**Comment by timgraham** [comment]
[django-developers thread](https://groups.google.com/d/topic/django-developers/QQy31BrJBm8/discussion)

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Pull request merged**
