### PR TITLE
overview.txt audience clarification

### PR DESCRIPTION
**Pull request by garwoodpr**
Non-programmers will not reach this point; the true audience is a novice.
I do not have write privileges to this repo, if this change is appropriate, please commit. 
Edits to the entire tutorial will follow.

### CODE REVIEW

**Comment by aaugustin** [comment]
One of the original design goals of the Django Template Language was to be usable by non-programmers.

Perhaps we could have a discussion on whether this goal was achieved, but that was the intent.

**Comment by garwoodpr** [comment]
I think it is a noble goal, worth continued pursuit, which deserves a continued dialogue. It is my opinion (holding aside cs students who are not yet programmers) that a non-programmer will not be able to complete the introductory tutorial.

**Comment by garwoodpr** [comment]
I think it is a noble goal, worth continued pursuit, which deserves a continued dialogue. It is my opinion (holding aside cs students who are not yet programmers) that a non-programmer will not be able to complete the introductory tutorial.

**Comment by timgraham** [comment]
I think it's not worth fretting over.

**Comment by ChristineLaMuse** [comment]
Well for what it's Worth You Helped Me :)

**Comment by ChristineLaMuse** [comment]
So I'd Call it a Success ... Cause I'm as Stubborn as a Goat! :)

**Pull request closed without merging**
