### PR TITLE
Fixed #31831 -- Fixed migration operations ordering when adding order_with_respect_to and constraints/indexes.

### PR DESCRIPTION
**Pull request by iurisilvio**
ticket-31831

### CODE REVIEW

**Comment by felixxm** [comment]
@iurisilvio Thanks, however this patch is a partial fix. For example, try to create a new app with models:
```python
# Create your models here.
class Look(models.Model):
    pass


class LookImage(models.Model):
    look = models.ForeignKey('Look', on_delete=models.CASCADE, related_name='images')
    field = models.IntegerField()

    class Meta:
        order_with_respect_to = 'look'
        indexes = [models.Index(fields=['look', '_order'])]
```
generated (initial) migration crashes with 
```
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: LookImage has no field named '_order'
```
I think `order_with_respect_to` should be included in `CreateModel()`'s options in this scenario, even if it uses a foreign key.

**Comment by iurisilvio** [comment]
I fixed the create model case too. I just added the `order_wrt_set` dependency and the optimizer included the `AlterOrderWithRespectTo` operation in `CreateModel`.

**Comment by felixxm** [comment]
I think we have the same issue for `Meta.constraints` maybe also for `index_together` and `unique_together` :thinking: What about adding `order_wrt_set` to dependencies for all of them, e.g.
```python
if order_with_respect_to:
    related_dependencies.append((app_label, model_name, '_order', 'order_wrt_set'))
for index in indexes:
    ...
for constraint in constraints:
    ....
```

**Comment by iurisilvio** [comment]
I tried to reorder the model creation and it worked too.

```diff
diff --git a/django/db/migrations/autodetector.py b/django/db/migrations/autodetector.py
index ac5af4d7d7..8e28281d67 100644
--- a/django/db/migrations/autodetector.py
+++ b/django/db/migrations/autodetector.py
@@ -625,6 +625,18 @@ class MigrationAutodetector:
                 for name in sorted(related_fields)
             ]
             related_dependencies.append((app_label, model_name, None, True))
+            if order_with_respect_to:
+                self.add_operation(
+                    app_label,
+                    operations.AlterOrderWithRespectTo(
+                        name=model_name,
+                        order_with_respect_to=order_with_respect_to,
+                    ),
+                    dependencies=[
+                        (app_label, model_name, order_with_respect_to, True),
+                        (app_label, model_name, None, True),
+                    ]
+                )
             for index in indexes:
                 self.add_operation(
                     app_label,
@@ -632,9 +644,7 @@ class MigrationAutodetector:
                         model_name=model_name,
                         index=index,
                     ),
-                    dependencies=related_dependencies + [
-                        (app_label, model_name, '_order', 'order_wrt_set')
-                    ],
+                    dependencies=related_dependencies,
                 )
             for constraint in constraints:
                 self.add_operation(
@@ -663,18 +673,6 @@ class MigrationAutodetector:
                     ),
                     dependencies=related_dependencies
                 )
-            if order_with_respect_to:
-                self.add_operation(
-                    app_label,
-                    operations.AlterOrderWithRespectTo(
-                        name=model_name,
-                        order_with_respect_to=order_with_respect_to,
-                    ),
-                    dependencies=[
-                        (app_label, model_name, order_with_respect_to, True),
-                        (app_label, model_name, None, True),
-                    ]
-                )
 
             # Fix relationships if the model changed from a proxy model to a
             # concrete model.
```

**Comment by iurisilvio** [comment]
I updated the PR with your suggestion, but will also add tests for these cases and for update model cases too, they probably will fail.

**Comment by iurisilvio** [comment]
I added test unique_together and index_together and indexes. They failed as expected and I fixed it too.

**Comment by iurisilvio** [comment]
It is good for another review. :)

**Comment by felixxm** [comment]
> I tried to reorder the model creation and it worked too. Looks like a cleaner solution and `order_with_respect_to` never depends on index/constraint/uniquetogether/indextogether.

Agreed, I pushed this suggestion.

**Comment by felixxm** [comment]
@iurisilvio Thanks :+1: Welcome aboard :boat: 

I moved tests which work without this patch to a separate commit and added `self.subTest()` to test each operation separately.

**Pull request merged**
