### PR TITLE
Refs #34146 -- Fixed typos in tutorial.

### PR DESCRIPTION
**Pull request by carltongibson**
- Fixed formatting on index page.
- Removed duplicate What's next section.

Thanks to Tim Graham for the report.

### CODE REVIEW

**Review by tim-schilling — APPROVED** [review]

**Comment by timgraham** [comment]
How about calling this an advanced tutorial? It's not tightly coupled to the existing tutorial except for a few mentions of the polls app that could be generalized. The advice could apply to beginners in any project. I'd prefer to keep the tutorial short and focused.

**Comment by carltongibson** [comment]
I think an introduction to Django's 3rd party ecosystem is a great end to the introductory tutorial. The idea was discussed at length at DjangoCon, and was positively received when discussed on social media channels after that. I think we should keep it now as it is. It mirrors nicely to the _Writing a 3rd-party app_ advanced tutorial.

**Review by felixxm — APPROVED** [review]

**Comment by timgraham** [comment]
I see. In the future, it would be nice to raise "change of philosophy" stuff like this on the mailing list, if only as a courtesy to people like me not at DjangoCon or engaged in social media. We went from avoiding mention of third-party packages to putting a package that < 50% of surveyed users use in the tutorial.

I wonder if Django maintainers now assume responsibility for the toolbar's compatibility with new versions of Django (e.g. https://github.com/jazzband/django-debug-toolbar/pull/1737, perhaps a stretch example since most tutorial users are probably using SQLite). Hopefully the latest toolbar release is never broken by a new Django release.

**Comment by carltongibson** [comment]
Hey @timgraham — OK, sorry you didn't pick up on this earlier... TBH I don't see it as a change of philosophy. In particular I was defending the principle during the review phase, e.g. the discussion here: https://github.com/django/django/pull/16271#discussion_r1085029475

DDT was agreed (basically by all) to be stable enough, and proven to be there for the long-haul. It's one of the most popular packages out there (there's not one that's going to be used by an absolute majority I would imagine) and it's been supported ≈forever. It was already popular in a JKM blog post from 2010 which was cited. 

Problem: new users don't even know about one of Django's biggest strengths, the 3rd-party ecosystem — it's almost like we forgot to mention (say) the ORM. Question: can we guide new users to the third-party app ecosystem, in a way that doesn't leave us on the hook for updating an e.g. _Awesome Django_ type list? (That last bit is the _avoiding mention_ point right?) I think what we've ended up hits that pretty well. 

Truly sorry you don't like it. I think it's a massive win.

**Pull request merged**
