### PR TITLE
Refs #25484 -- Removed incorrect unquoting in {% static %}.

### PR DESCRIPTION
**Pull request by timgraham**
As discussed in the comments of https://github.com/django/django/pull/7494.

### CODE REVIEW

**Comment by apollo13** [comment]
Do you think a test which reuses a static storage backends which actually add `?some=param&another=param` in the URL method (to simulate API keys or so) would be doable? This would then also allow testing if we actually escape that properly -- cause currently I do not see any test for the actual escaping (or did I miss anything?).

**Comment by timgraham** [comment]
The tests for the lines
```
if context.autoescape:
    url = conditional_escape(url)
```
added in the original PR were also added in the original PR: https://github.com/django/django/blob/12c1d6fe8f03f068f6010e3c8e0f441bf2567e7c/tests/template_tests/syntax_tests/test_static.py#L54-L63

I also manually checked this is working as expected with `S3BotoStorage` as reported in the ticket, but this isn't going through a different, untested code path.

**Comment by apollo13** [comment]
The tests you just linked look wrong, `test_static_escapes_urls` should result in `test.html%3Ffoo%3D1%26bar%3D2` (ie the output of `escape(urlquote(u"test.html?foo=1&bar=2"))`). And the same when autoesacping is off -- ie to actually test if autoescaping works properly we'd need a storage backend which adds the params in the URL method.

**Comment by timgraham** [comment]
Ready for review again.

**Pull request merged**
