### PR TITLE
Fixed #28856 -- Fixed an issue with caching of coerced gfk pointing to mti model.

### PR DESCRIPTION
**Pull request by charettes**
https://code.djangoproject.com/ticket/28856

### CODE REVIEW

**Comment by timgraham** [comment]
Looks good. I edited the release note and moved `to_python()` to try to make it more consistent with the ordering of methods in `Field`.

Did you consider trying to add a test for `to_python()` besides the contenttypes tests so that a "core" method isn't only tested via contrib.

Do you want to apply this patch or the 1.11 version for 2.0?

**Comment by charettes** [comment]
> Looks good. I edited the release note and moved `to_python()` to try to make it more consistent with the ordering of methods in `Field`.

Thanks for that!

> Did you consider trying to add a test for `to_python()` besides the contenttypes tests so that a "core" method isn't only tested via contrib.

I thought about it but I wanted to push the PR first before it was getting late. I'll add some.

> Do you want to apply this patch or the 1.11 version for 2.0?

I'd be more confident pushing the 1.11 patch for 2.0.

**Comment by timgraham** [comment]
I added a test, did you have something different in mind?

**Comment by charettes** [comment]
@timgraham the test is perfect, thanks! Feel free to merge this PR. I should be able to do it later today if don't beat me to it.

**Pull request merged**
