### PR TITLE
Fixed #20629 -- Rephrased custom user models admonition.

### PR DESCRIPTION
**Pull request by rixx**
https://code.djangoproject.com/ticket/20629

### CODE REVIEW

**Comment by MarkusH** [comment]
Considering the experience that most people have made with adding a custom user model at a later stage, what's your opinion on rephrasing the admonition to be more supportive towards custom user models. Even if you don't know you need one right now, having to migrate at a later stage is a hell of a lot more complex than just having a plain custom user model in an `accounts` app.

**Comment by rixx** [comment]
This is already a try of being less scary and more supportive of custom user models as per the original ticket – I think this is a good idea. While the Django docs state clearly that **starting with a custom user model is recommended** … they do so in the custom user model docs. Once you've found those, it's probably too late, though.

Anyways, we might also consider inlining the admonition below the paragraph that follows it. Removing the admonition status in itself makes the comments less scary, I'd say. Opinions?

**Comment by MarkusH** [comment]
Incorporating the notes about the model design into the surrounding paragraphs is fine with me. Here's different shot at a rewrite (also removing the "Django expects your custom ..." paragraph):


> When you start with a custom user model please consider the database design you are planning to use. On the one hand, keeping all user related information in one model means you don't have to fetch a related model with further information from the database. This removes possible database joins but comes with the cost of large user models. On the other hand, it may be more suitable to store app-specific user information in a model that has a relation with your custom user model. This allows each app to specify its own user data requirements without potentially conflicting with or breaking assumptions by other apps. It also means that you would keep your user model as simple as possible, following the minimum requirements Django expects custom user models to meet.

This paragraph would assume that one has already made the decision to use a custom user model. It removes the whole should or shouldn't. Instead it focuses on how to design the custom user model, which is what the section is about, IMO.

**Comment by rixx** [comment]
Thank you for your review and suggestions! I drafted a mix of our solutions – I'd be happy to adjust it some more, if anybody has suggestions. I think it's alright the way it is, but it's a bit long/unwieldy, so finding a more concise phrasing might be better. (I'll have another go in a day or two, if nobody else has any ideas.)

**Comment by MarkusH** [comment]
I like it as well. Thanks. I'll mark it as ready for commit so Carlton or Mariusz have a final look.

**Comment by felixxm** [comment]
@rixx @MarkusH I pushed some final edits. Can you take a look?

**Comment by rixx** [comment]
@felixxm Looks good to me, thank you.

**Comment by felixxm** [comment]
@rixx Thanks!

**Pull request merged**
