### PR TITLE
Fixed #23155: Added request argument to user_login_failed

### PR DESCRIPTION
**Pull request by gavinwahl**
https://code.djangoproject.com/ticket/23155

### CODE REVIEW

**Comment by timgraham** [comment]
Looks good. Any concerns with these edits? http://dpaste.com/32TMW7M
(in particular, can you spot any problems with making `_request` an explicit argument of `authenticate()`? I don't think there's any backwards compatibility concerns since the function doesn't accept position args.

**Comment by gavinwahl** [comment]
The disadvantage of making it an explicit argument is that now it can be
passed as the first positional argument. This has caused confusing errors
for me in the past when I mistakenly pass a keyword argument as a
positional argument.

I thought about using the python3 keyword-only argument syntax in the docs,
to make the request argument more clear:

    authenticate(*, _request=None, **credentials)

But I'm not sure if that's acceptable because it's specific to python 3.

**Comment by timgraham** [comment]
I guess I'd rather have a more self-explanatory function signature than obfuscate the code a bit and have to scan the function to see what kwargs are popped off, but other opinions are welcome.

I'm not familiar with that syntax you proposed, so I think it would probably cause some confusion.

**Comment by gavinwahl** [comment]
I'd prioritize good error messages, but it's up to you.

**Comment by timgraham** [comment]
The discussion continues on the ticket. Gavin, maybe you want to assign it to yourself so you get notified of comments.

**Comment by timgraham** [comment]
Closing due to inactivity and the alternate direction proposed on the ticket.

**Comment by timgraham** [comment]
Rebased following 4b9330ccc04575f9e5126529ec355a450d12e77c and merged in f0f3de3c96694fd3602541fa6074930667509ac8, thanks!

**Pull request closed without merging**
