### PR TITLE
Fixed #24995 -- Fixed renaming a ForeignKey target on MySQL

### PR DESCRIPTION
**Pull request by EikeDehling**

### CODE REVIEW

**Comment by EikeDehling** [comment]
https://code.djangoproject.com/ticket/24995

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
It looks like the new tests passes even if the fix is reverted.

**Comment by timgraham** [comment]
Eike, any reply to this? Does the test work as a regression test on your system?

**Comment by timgraham** [comment]
Closing due to lack of follow up.

**Pull request closed without merging**
