### PR TITLE
Refs #373 -- Used a feature flag to disable composite subquery test on MySQL.

### PR DESCRIPTION
**Pull request by charettes**
Per [this comment](https://github.com/django/django/pull/18404/files/8fc4eb2824c6a46187a080b71a139159a207e0f3#r1824252314) from @timgraham.

cc @sarahboyce, @csirmazbendeguz

### CODE REVIEW

**Review by LilyFirefly — APPROVED** [review]

**Review by felixxm — APPROVED** [review]

**Comment by csirmazbendeguz** [comment]
Thanks, I wasn't aware!

**Comment by charettes** [comment]
@csirmazbendeguz no problem, we really should do a better job at documenting these.

We have so many that over the years I've defaulted to assuming we already have one so I came to learn about a lot of them 😅

**Review by sarahboyce — APPROVED** [review]
Thank you all :star:

**Comment by Sionigdha** [comment]
## AI Code Review

### tests/foreign_object/test_tuple_lookups.py
LGTM

**Pull request merged**
