### PR TITLE
Fixed broken links in docs.

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Comment by atombrella** [comment]
I found a few more:

`django/docs/ref/contrib/syndication.txt.txt:1028: WARNING: broken link: https://help.apple.com/itc/podcasts_connect/#/itcb54353390 (Anchor '/itcb54353390' not found)`
`django/docs/ref/request-response.txt.txt:867: WARNING: broken link: https://www.owasp.org/index.php/SameSite (404 Client Error: Not Found for url: https://owasp.org/index.php/SameSite)` (not sure why it fails)
`django/docs/ref/contrib/staticfiles.txt.txt:284: WARNING: broken link: https://developer.yahoo.com/performance/rules.html#expires (Anchor 'expires' not found)`
`django/docs/ref/contrib/sitemaps.txt.txt:223: WARNING: broken link: https://www.sitemaps.org/protocol.html#prioritydef (HTTPSConnectionPool(host='www.sitemaps.org', port=443): Max retries exceeded with url: /protocol.html (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)))`

**Comment by felixxm** [comment]
@atombrella Thanks :+1: 

> `django/docs/ref/contrib/syndication.txt.txt:1028: WARNING: broken link: https://help.apple.com/itc/podcasts_connect/#/itcb54353390 (Anchor '/itcb54353390' not found)`

It's rather a Sphinx issue, because https://help.apple.com/itc/podcasts_connect/#/itcb54353390 works properly.

> 
> `django/docs/ref/request-response.txt.txt:867: WARNING: broken link: https://www.owasp.org/index.php/SameSite (404 Client Error: Not Found for url: https://owasp.org/index.php/SameSite)` (not sure why it fails)

I think we can use https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite instead.

> `django/docs/ref/contrib/staticfiles.txt.txt:284: WARNING: broken link: https://developer.yahoo.com/performance/rules.html#expires (Anchor 'expires' not found)`

It's also rather a Sphinx issue, because link works properly :shrug:

> `django/docs/ref/contrib/sitemaps.txt.txt:223: WARNING: broken link: https://www.sitemaps.org/protocol.html#prioritydef (HTTPSConnectionPool(host='www.sitemaps.org', port=443): Max retries exceeded with url: /protocol.html (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)))`

TBH, I don't know what to do with `www.sitemaps.org` that didn't renew certicates. Do you have propositions?

**Comment by atombrella** [comment]
> I think we can use https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite instead.

Seems good.

> > `django/docs/ref/contrib/staticfiles.txt.txt:284: WARNING: broken link: https://developer.yahoo.com/performance/rules.html#expires (Anchor 'expires' not found)`
> 
> It's also rather a Sphinx issue, because link works properly 

Ah, yes. When you've accepted the privacy policy, the link works properly. I think this is why Sphinx fails.

> > `django/docs/ref/contrib/sitemaps.txt.txt:223: WARNING: broken link: https://www.sitemaps.org/protocol.html#prioritydef (HTTPSConnectionPool(host='www.sitemaps.org', port=443): Max retries exceeded with url: /protocol.html (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)))`
> 
> TBH, I don't know what to do with `www.sitemaps.org` that didn't renew certicates. Do you have propositions?

It seems Google also got annoyed, and created a duplicate.
https://www.google.com/sitemaps/protocol.html#prioritydef

**Comment by felixxm** [comment]
> > > `django/docs/ref/contrib/sitemaps.txt.txt:223: WARNING: broken link: https://www.sitemaps.org/protocol.html#prioritydef (HTTPSConnectionPool(host='www.sitemaps.org', port=443): Max retries exceeded with url: /protocol.html (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)))`
> > 
> > 
> > TBH, I don't know what to do with `www.sitemaps.org` that didn't renew certicates. Do you have propositions?
> 
> It seems Google also got annoyed, and created a duplicate.
> https://www.google.com/sitemaps/protocol.html#prioritydef

`www.sitemaps.org` renewed certificate (valid until 4.05.2020 :smile: ) so it can stay for now.

**Pull request merged**
