### PR TITLE
Updated Python license for 2022.

### PR DESCRIPTION
**Pull request by felixxm**
See https://github.com/python/cpython/commit/ba00f0d93a4aea85ae8089f139856a7c450584d7#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7

### CODE REVIEW

**Comment by pauloxnet** [comment]
it's really required to add every years ? or the starting year is enough ?

**Comment by smithdc1** [comment]
I had the same thought but this is reflecting an upstream change and I think consistency is important even if we may question their decision.

**Comment by felixxm** [comment]
> it's really required to add every years ? or the starting year is enough ?

Yes, it's not our decision :shrug: We have to copy it as it is.

**Review by smithdc1 — APPROVED** [review]

**Comment by pauloxnet** [comment]
Ok, now it's clear.

**Review by pauloxnet — APPROVED** [review]

**Comment by felixxm** [comment]
Thanks  both :+1:

**Pull request merged**
