### PR TITLE
Fixed #26431 -- translate_url() creates an incorrect URL when optiona…

### PR DESCRIPTION
**Pull request by jekka-ua**
https://code.djangoproject.com/ticket/26431

### CODE REVIEW

**Comment by timgraham** [comment]
Did you see the suggestion on the ticket to treat it as a bug in `reverse()` and solve the issue there?

**Comment by jekka-ua** [comment]
I saw, but i don't know is it a 'feature' or a 'bug' :)

knbk also wrote "I think it's a better idea to treat this asymmetry as a bug", but there is no conclusion

**Comment by timgraham** [comment]
If you're willing to try, it would be useful to see what the alternate solution looks like.

**Comment by jekka-ua** [comment]
ok.. i'll think about it

**Comment by timgraham** [comment]
Closing due to inactivity.

**Pull request closed without merging**
