### PR TITLE
Fixed #31866 -- Fixed locking proxy models in QuerySet.select_for_update(of=())

### PR DESCRIPTION
**Pull request by danifus**
https://code.djangoproject.com/ticket/31866

### CODE REVIEW

**Comment by danifus** [comment]
Thanks! I knew there was going to be a proper way of doing that.

I was also intrigued by what functionality would require `dict[Model, None]`...

Let me know if you're happy with it and I can squash these commits

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
@danifus Thanks :+1:

**Comment by felixxm** [comment]
I added release notes.

**Comment by danifus** [comment]
@felixxm Thanks for your help!

**Pull request merged**
