### PR TITLE
Fixed #33891 -- Fixed test command crash when running in parallel using spawn.

### PR DESCRIPTION
**Pull request by felixxm**
Thanks Kevin Renskers for the report.

Regression in 41c4cb253c137edf5a96b7408ea55d57d6e0602a.

ticket-33891

### CODE REVIEW

**Comment by felixxm** [comment]
@kevinrenskers Does it work for you?

**Comment by felixxm** [comment]
Unfortunately, adding a reasonable regression test is probably not feasible :disappointed:

**Review by carltongibson — APPROVED** [review]
OK, looks good. Thanks. 👍

**Comment by kevinrenskers** [comment]
> @kevinrenskers Does it work for you?

Yes, thanks 👍

**Comment by felixxm** [comment]
Thanks both for checking :heart:

**Comment by kevinrenskers** [comment]
@carltongibson I got your comment on https://code.djangoproject.com/ticket/34010, about the fix not working after all, only now getting another error. Sadly I can't open the ticket, I get a 503 error so I'll respond here.

> I'm confused you confirmed that d4db417c8e6935222d198925dd4c5ac1ca737909 works for you. Can you provide a sample project?

I'm not sure why that seemed to work. Maybe I made a mistake updating Django to the commit with the fix, or maybe I ran the tests without the parallel flag 🤔

I can email you a closed source project, if it won't be shared with other people.

**Comment by carltongibson** [comment]
Hi @kevinrenskers. It was @felixxm' comment, but yes, some reproduce is needed please.  


(The AppRegistry error could well show a problem in your project but without seeing it it's hard to say.)

**Comment by kevinrenskers** [comment]
Just let me know where to send the project.

**Comment by carltongibson** [comment]
@kevinrenskers The email on my profile is fine. Please make sure to include reproduce steps for getting the project bootstrapped. Thanks!

**Comment by kevinrenskers** [comment]
Done!

**Pull request merged**
