### PR TITLE
Fixed #28959 -- Fixed 'No, take me back' button on admin's inline popup.

### PR DESCRIPTION
**Pull request by jschneier**
https://code.djangoproject.com/ticket/28959

### CODE REVIEW

**Comment by timgraham** [comment]
Yes, a selenium test.

**Comment by jschneier** [comment]
I glanced through them. Can you point me at an auspicious location?

**Comment by timgraham** [comment]
There aren't too many subclasses of AdminSeleniumTestCase, find one that makes the sense.

**Comment by kezabelle** [comment]
@jschneier have you force-pushed over the top of your patch and subsequently accidentally omitted the change (which I think was 14df428c001fc84d3cd9fe970a02a3cb419dc8e6?) All I can see now in the PR is the test `test_inline_uuid_pk_with_popup_cancel_delete`

**Comment by jschneier** [comment]
I was trying to write a failing test while not downloading selenium which evidently failed.

**Comment by carltongibson** [comment]
@jschneier The django-box VM is worth checking out. https://github.com/django/django-box

It has the dependencies preinstalled. In the VM, you can run the selenium tests like: 

    runtests36-sqlite3 admin_widgets --selenium chrome --parallel 1

**Comment by jschneier** [comment]
It’ll take me a few days (likely the weekend) to get to this. I’ve attached the patch for someone to run with if there is a deadline to hit, it’s pretty straightforward.

**Comment by jschneier** [comment]
Didn't come through via email so adding it here. 
```patch
commit 14df428c001fc84d3cd9fe970a02a3cb419dc8e6
Author: Josh Schneier <josh.schneier@gmail.com>
Date:   Fri Jan 12 10:38:39 2018 +0800

    Fix #28959 -- Close popup when clicking 'No, take me back' on inline popup

diff --git a/django/contrib/admin/static/admin/js/cancel.js b/django/contrib/admin/static/admin/js/cancel.js
index 3f7dfb42a7..fa86a657dd 100644
--- a/django/contrib/admin/static/admin/js/cancel.js
+++ b/django/contrib/admin/static/admin/js/cancel.js
@@ -3,7 +3,12 @@
     $(function() {
         $('.cancel-link').on('click', function(e) {
             e.preventDefault();
-            window.history.back();
+
+            if (window.location.search.indexOf('&_popup=1') === -1) {
+                window.history.back();
+            } else {
+                window.close();
+            }
         });
     });
 })(django.jQuery);
```

**Pull request merged**
