### PR TITLE
Fixed #28264 -- Made FilePathField sort files and directories when recursive=True.

### PR DESCRIPTION
**Pull request by srinivasreddy**
Fixes https://code.djangoproject.com/ticket/28264

### CODE REVIEW

**Comment by timgraham** [comment]
It doesn't seem the correct test(s) are modified. The `if recursive` branch of the form field is modified but the test that's modified has `recursive=False`. Make sure the test fails without the fix applied. There might be some existing uses of `f.choices.sort()` that aren't required in the tests. These could be removed in a separate pull request.

**Comment by srinivasreddy** [comment]
Without the patch, removing sort() on `recursive=True` test case fails it.

@timgraham  Pls review again

**Comment by timgraham** [comment]
Still if the second `sorted()` change is reverted, the tests pass. It could be nice to change the test to use a dedicate "test" directory anyway as it's annoying to have to update these tests if a file is added to `django/forms/`.

**Comment by srinivasreddy** [comment]
Agreed

**Comment by timgraham** [comment]
Could you make the test directory change in a separate PR? Then we'll rebase this. Please change all the tests in this file that are use django.forms. I'd use a name like `filepathfield_test_dir` and file names like `a`, `b`, etc. We don't need to copy the names that were in `django/forms`. Don't we need some test subdirectories also? With the new `sorted()` under `self.allow_folders` reverted, there still aren't any test failures.

**Comment by srinivasreddy** [comment]
@timgraham  Done.

**Comment by timgraham** [comment]
After the rebase, a test change for the second `sorted()` is still needed.

**Comment by srinivasreddy** [comment]
@timgraham I added one more test case which is missing

**Comment by timgraham** [comment]
Does that test fail with the second `sorted()` in the patch removed? As far as I tested, it doesn't. Also, the build is reporting a failure on Python 3.6 although I can't reproduce it.

**Comment by srinivasreddy** [comment]
cache files in  __pycache__  are included, that's why it is failing. Need to exclude the files in __pycache__ folder.

**Comment by srinivasreddy** [comment]
Done.

**Comment by timgraham** [comment]
I guess the pycache change should be a separate ticket/PR. I think it would be appropriate to create a pycache directory so that the test isn't dependent on Python create that directory at runtime.

**Comment by srinivasreddy** [comment]
How about completely disabling writing __pycache__ folder with `PYTHONDONTWRITEBYTECODE`? You okay with that approach?

**Comment by charettes** [comment]
@srinivasreddy the tests suite should be able to pass with `PYTHONDONTWRITEBYTECODE` disabled as well.

**Comment by srinivasreddy** [comment]
makes sense

**Comment by timgraham** [comment]
I still don't see a test failure with the second `sorted()` removed. It looks like we need two sibling directories in `filepathfield_test_dir` so that they can be sorted.

**Comment by srinivasreddy** [comment]
@timgraham  Done

**Pull request merged**
