### PR TITLE
Fixed #27282 -- Allowed using an integer DATABASES['PORT'] for Oracle.

### PR DESCRIPTION
**Pull request by Zapelini**
this change fixes https://code.djangoproject.com/ticket/27282#ticket

### CODE REVIEW

**Comment by timgraham** [comment]
buildbot, test on oracle.

**Comment by Zapelini** [comment]
Can you please add this fix to branches stable/1.10.x and stable/1.11.x? 
Thank you in advance.

**Comment by timgraham** [comment]
No, if it's not a regression from a previous release or a major bug in a new feature it won't be backported. See our [supported versions policy](https://docs.djangoproject.com/en/dev/internals/release-process/#supported-versions).

**Comment by Zapelini** [comment]
Ok, thank you. ;)

**Pull request merged**
