### PR TITLE
Refs #24121 -- Added __repr__() to AdminSite, DefaultAdminSite, and ModelAdmin.

### PR DESCRIPTION
**Pull request by tlebrize**

### CODE REVIEW

**Review by felixxm — COMMENTED** [review]
@tlebrize Thanks for this patch :+1: I left comments.

**Comment by felixxm** [comment]
@tlebrize Do you have time to keep working on this?

**Comment by Edald123** [comment]
Hi! I would like to continue working on this if @tlebrize doesn't have more time. If yes, in which classes can I help? :)

**Comment by tlebrize** [comment]
Hello, sorry for leaving that hanging, I forgot about it.
@felixxm thanks for the input, these all look good ! I only have one doubt about the `<...>` notation, isn't it somewhat standard ?
@Edald123 it's up to you, I haven't started on any of felixxm's comments.

**Comment by felixxm** [comment]
> @felixxm thanks for the input, these all look good ! I only have one doubt about the `<...>` notation, isn't it somewhat standard ?

Yes, see [`__repr__` docs](https://docs.python.org/3/reference/datamodel.html?highlight=__repr__#object.__repr__).

**Comment by felixxm** [comment]
Closing due to inactivity.

@Edald123 Feel-free to send a new version of this patch.

**Pull request closed without merging**
