### PR TITLE
Fixed #32394 -- Changed project template settings to use relative STATIC_URL.

### PR DESCRIPTION
**Pull request by MarkusH**
Refs #25598 which added original support for relative STATIC_URL and MEDIA_URL.

@apollo13 that might be of interest to you :)

### CODE REVIEW

**Review by apollo13 — APPROVED** [review]
Mhm, that should not cause any problems -- famous last words :D

**Comment by apollo13** [comment]
Mhm that made me think about it a bit more. My latest commit in that area was:
https://github.com/django/django/commit/7dbbe65647a54283fadf2c51f11a750a74425d7b#diff-b6f3108584c2db0b4c53253b6b3b5d5c60fbb3a82e7ed6544922fe689631fa43

Now if someone access STATIC_URL on the module level, this value would get cached and then be wrong. But I guess in such a case one has to set a absolute URL anyways.

**Comment by felixxm** [comment]
Thanks :+1: I would add a small note in ["Backwards incompatible changes in 4.0"](https://docs.djangoproject.com/en/dev/releases/4.0/#miscellaneous) e.g. _"Starting with 4.0 new projects are generated with STATIC_URL ...."_.

**Comment by felixxm** [comment]
Maybe we should prefer relative URLs also in [docs](https://docs.djangoproject.com/en/dev/howto/static-files/) :thinking:.

**Comment by MarkusH** [comment]
I've pushed 2 more commits. One that updates the use of `STATIC_URL` and `MEDIA_URL` in the docs to use relative paths. And the same for tests. Not sure if we want to include the latter.

**Comment by felixxm** [comment]
@MarkusH Thanks :+1: I squashed the last two commits and pushed minor edits.

**Comment by MarkusH** [comment]
Thanks @felixxm

**Pull request merged**
