### PR TITLE
Fixed #32469 -- Made assertQuerysetEqual() respect maxDiff when ordered=False.

### PR DESCRIPTION
**Pull request by pope1ni**
Fixes ticket-32469. This may interest you @adamchainz given your love of all things testing?

### CODE REVIEW

**Comment by timgraham** [comment]
I don't think documentation changes or release notes are needed. Generally there's little value in including `versionchanged` annotations when none of the surrounding documentation has changed.

Incidentally, I'm unsure that `assertQuerysetEqual` provides much value these days.

In the new test example, I would instead use: 
```python
self.assertCountEqual([p.name for p in Person.objects.order_by('name')], names)
```

**Review by adamchainz — APPROVED** [review]
LGTM!

**Comment by pope1ni** [comment]
> I don't think documentation changes or release notes are needed. Generally there's little value in including `versionchanged` annotations when none of the surrounding documentation has changed.

I guess that's fair, particularly the second point.

> In the new test example, I would instead use:
> 
> ```python
> self.assertCountEqual([p.name for p in Person.objects.order_by('name')], names)
> ```

I really don't follow. How would that be testing that `assertQuerysetEqual()` supports `maxDiff`?

**Comment by timgraham** [comment]
My thought was that it might be better to promote `assertCountEqual` and `assertSequenceEqual` rather than to enhance `assertQuerysetEqual` (particularly after `assertQuerysetEqual` no longer calls `repr()` by default). But it looks like `assertSequenceEqual` doesn't work when both arguments are QuerySets so I guess `assertQuerysetEqual` still provides value. But at least in Django's test suite, I'd advocate for only using `assertQuerysetEqual` to compare two querysets. I don't insist you modify your test. It's just an idea for a separate discussion. Sorry that wasn't clear.

**Review by recepsirin — APPROVED** [review]

**Comment by felixxm** [comment]
@pope1ni Thanks :+1: I pushed small edits to tests.

**Comment by felixxm** [comment]
> But at least in Django's test suite, I'd advocate for only using assertQuerysetEqual to compare two querysets. 

We've replaced ~600 `assertQuerysetEqual()` to `assertSequenceEqual()/assertCountEqual()` in 3f7b3275627385f8f7531fca01cdda50d4ec6b6e.

**Pull request merged**
