### PR TITLE
GSoC'23 Discussion -- Allow moving a model between apps.

### PR DESCRIPTION
**Pull request by DevilsAutumn**
So after all my research i created a new migration  ```MoveModel``` to move a model between apps. I have also tested the code with some case like ```m2m field``` , ```foreign key```  and renaming and moving model. It worked quite smooth for me even for reverse migration but i'm still trying to test it with as many cases as possible. I have also added a ```MoveModelPlaceholder``` for building dependencies.
The moving models changes will be automatically detected and ```MoveModel``` operation will be added in the app from which model is moved and ```MoveModelPlaceholder``` will be placed in the app to which model is moved.

Im still trying to figure out how can we create table for moved model on empty database when the old app is removed from ```INSTALLED_APPS```.

Any feedback is highly appreciated.

### CODE REVIEW

**Comment by eugenenelou** [comment]
Hello, thanks for taking up this subject.

I believe that to handle removing the old app from `INSTALLED_APPS`, you'll have to make `MoveModelPlaceholder` be able to create the model in the state if it does not exist.

**Comment by shaib** [comment]
Hi,

In a private project (whose code I am not at liberty to share), I took a different approach. 

Disclaimer: I was less ambitious -- the detector wasn't involved, I only defined migration operations, and those operations did not fully take care of the foreign keys. The intended use was to edit the `models.py` files, run `makemigrations` and edit the resulting migrations.

I divided the move operation differently, in a way which made editing easier, but also I think is generally more correct: Instead of one `MoveModel` which does everything, followed by a no-op, I had 
- a `SendModel` in the source/old app which removed the model in the state, and renamed the table to fit the target/new app, 
- and a `ReceiveModel` in the new/target app, which was just calling `CreateModel` under `SeparateDatabaseAndState` to work on the state only.

The reason I think this is more correct is that with this division, the migration in each app only works on models in that app(*).

`SendModel` was an easy edit from `DeleteModel`, and `ReceiveModel` (as hinted) a trivial editing from `CreateModel` as generated by an unmodified migration autodetector.

An important consequence of the fact that `ReceiveModel` is so close to `CreateModel` is that one may implement a `ReceiveOrCreateModel`, which is essentially just a `CreateModel` modified so that if it finds the table already existing, it does nothing in the database. With that operation, if the old/source app is later removed, the only change required in the new app's migration is to drop the dependency on the old app.

This approach does make things a little more complicated when handling foreign keys pointing into the moved model. One cannot switch their targets in one operation as done in the current code, but should instead add operations to change them from FK to the base type before the `SendModel`, and change them "back" from the base type to a FK to the new model, after `ReceiveModel`. But this complication falls mainly on the autodetector, and again, minimizes the changes required later for removing the old app completely; and in my book, the framework taking complications on itself to simplify the lives of users is a Good Thing:tm:.



(*) True, `SendModel` does rename the table "into" the new app, but technically, it doesn't touch the new app's models, and removing this impurity would require weird behavior like a double rename -- first from the source app to a "neutral" name, then from the "neutral" name to the target app.

**Comment by DevilsAutumn** [comment]
hey @shaib , Thanks for reviewing!

> This approach does make things a little more complicated when handling foreign keys pointing into the moved model. One cannot switch their targets in one operation as done in the current code, but should instead add operations to change them from FK to the base type before the `SendModel`, and change them "back" from the base type to a FK to the new model, after `ReceiveModel`. But this complication falls mainly on the autodetector, and again, minimizes the changes required later for removing the old app completely; and in my book, the framework taking complications on itself to simplify the lives of users is a Good Thing™️.

Sorry but i didn't understand what exactly do you mean by **"base type"** here? Are you suggesting to create a new field operation ,something like ```ChangeFieldReference``` or adding ```AlterField``` operation before ```SendModel``` and after ```RecieveModel``` would work (possibly with some modifications)?

**Comment by shaib** [comment]
> 
> > This approach does make things a little more complicated when handling foreign keys pointing into the moved model. One cannot switch their targets in one operation as done in the current code, but should instead add operations to change them from FK to the base type before the `SendModel`, and change them "back" from the base type to a FK to the new model, after `ReceiveModel`. 
> 
> Sorry but i didn't understand what exactly do you mean by **"base type"** here? Are you suggesting to create a new field operation ,something like `ChangeFieldReference` or adding `AlterField` operation before `SendModel` and after `RecieveModel` would work (possibly with some modifications)?
> 

The "base type" I'm referring to is the type of the underlying database field for the FK, determined to match the pointed model's PK (by default this is `BigIntegerField`, but the PK type can be changed at the project, app and model levels). I'm suggesting to add `AlterField` ops before `SendModel` (FK->simple field) and after `ReceiveModel` (simple field -> FK).

> And i feel it might create some problem while turning off old app, let us say for example you have two apps `cars` and `tires` , `cars` have one model say `foo` which is referenced by m2m field present in model say `bar` in `tires` app. both of them have initial migrations files for creating models. And then we moved `foo` from `cars` to `tires` and after running `makemigrations` command you removed `cars` and applied migrations on empty database, so the initial migration in `tires` will try to create model `bar` with m2m field to `cars.foo` but since `cars` is not there it will give error, so we have to manually remove that field ,right? because at point of creating `bar` model, our database is empty and`RecieveModel` for creating model in state will be in next migration file.
> 
> With my approach , after turning off old app you have to replace `MoveModelPlaceholder ` with `CreateModel` operation for moved model, remove the dependencies along with the fields referencing moved model and run `makemigration` which will add `AddField` operation for all the referencing fields in a new file.

Removing an app, when other apps have (past) dependencies on it, will always (I think) require editing of past migrations; and I cannot, at this time, see a way to make it straightforward in all scenarios. A user will need to apply thought and judgment.

So first, please note that the way you suggest to handle this case -- remove the referencing field in the initial migration, and rely on `makemigrations` to add it back later -- 
1. Is available to the user also with the approach I'm suggesting, and
2. Adds migrations which will break in production because they add columns and tables which already exist. 

For this to work in both scenarios (empty DB vs production data), you'd need to do one of two things:
- Tell whoever runs the migrations in production that "when these migrations fail, skip them", which is bad (esp. if you have more than one deployment; when you're in production, you don't want upgrades to include manual steps)
- Take the operations added by `makemigrations` and add them into the already-applied (in "production") migrations, so that they're only applied in new databases. And even this is brittle -- things can happen between the model move and the app removal; it may be that if you take operations from newly-created migrations and add them into old migrations, you'll break migrations that have been added later.

I want to stress, we do need the migrations in a project to always support both cases: Running on an empty DB, and Running in production. On one hand, there's tests and sometimes projects get deployed more than once, and on the other, projects keep developing after being deployed.

With this in mind -- the correct solution in your `cars` and `tires` example is to (manually) add the `CreateModel` operation for model `foo` into the initial migration of the `tires` app, and this is regardless of which approach is taken with the move operations. That is the best way to get things to keep working smoothly. However, for that to go as smooth as possible, that `CreateModel` should reflect model `foo` as it was at the time the dependency on it was introduced -- or, at the latest, at the time it was moved into the `tires` app.

So, whether or not you accept my approach, I think we need to help the user write the correct `CreateModel` operation into an older migration. My approach makes it available as part of the `ReceiveModel` or `ReceiveOrCreateModel` operation; it can be done also as added information in the `MoveModelPlaceholder` operation, as comments added to the migration file, or even as a separate management command ("show me a CreateModel for model x after migration y").

All in all, I think that the principle, that operations working on models should remain, as much as possible, in their own app, has some other benefits -- for example, I think it makes the whole thing more squash-friendly. Including model structure in the migration which adds it to an app makes things more readable, in case you want to follow migration history.

So I think it's a principle worth investing in.

**Comment by DevilsAutumn** [comment]
I agree with your suggestion to keep operations working on models ,as much as possible, in their own app. 👍 

> I'm suggesting to add AlterField ops before SendModel (FK->simple field) and after ReceiveModel (simple field -> FK).

one small doubt, Should ```AlterField``` be added even for the ```FKs``` present in models of other apps? Like if we have models in ```app_2``` and ```app_3``` which are referencing a model in ```app_1``` then after moving that model from ```app_1``` , we will have AlterField for ```FKs``` from ```app_2``` and ```app_3``` just before ```SendModel``` (in same migration file),right? 

>we do need the migrations in a project to always support both cases: Running on an empty DB, and Running in production. 

What if we add ```AlterField``` operations after ```ReceiveModel``` by default and pass a list (say ```optional_operations``` or ```skip_operations```) of ```AddField``` operation for fields referencing that model in same migration file? Then users will get an option to replace operaions based on where they are running them(production or empty db).

**Comment by shaib** [comment]
> I agree with your suggestion to keep operations working on models ,as much as possible, in their own app. +1
> 

Thanks!

> > I'm suggesting to add AlterField ops before SendModel (FK->simple field) and after ReceiveModel (simple field -> FK).
> 
> one small doubt, Should `AlterField` be added even for the `FKs` present in models of other apps? Like if we have models in `app_2` and `app_3` which are referencing a model in `app_1` then after moving that model from `app_1` , we will have AlterField for `FKs` from `app_2` and `app_3` just before `SendModel` (in same migration file),right?
> 

In keeping with the principle -- no, IMO the alter-fields should be added in migrations in their own apps, with dependencies set to fix the order. I'm feeling a little less strongly about this, because these changes are really just part of the move operation (preparation and cleanup). So maybe more opinions would be good here.

> > we do need the migrations in a project to always support both cases: Running on an empty DB, and Running in production.
> 
> What if we add `AlterField` operations after `ReceiveModel` by default and pass a list (say `optional_operations` or `skip_operations`) of `AddField` operation for fields referencing that model in same migration file? Then users will get an option to replace operaions based on where they are running them(production or empty db).

The only reason to have the `AddField` in the first place, is in order to help with app removal. But as we said, app removal requires editing of past migrations anyway, and that editing (or even just squashing, if one is very lucky) could change the `AlterField` to `AddField` -- the information is all there anyway.

Having just written the above paragraph, it occurred to me that instead of editing past migrations for app removal, a mechanism like squashing could be used -- which replaces the past migrations with "new past migrations". Seems worth investigating, though at this point it's just a half-baked idea and the details are entirely unclear to me.

**Comment by DevilsAutumn** [comment]
>In keeping with the principle -- no, IMO the alter-fields should be added in migrations in their own apps, with dependencies set to fix the order. I'm feeling a little less strongly about this, because these changes are really just part of the move operation (preparation and cleanup). So maybe more opinions would be good here.

Switching to base type and then again to the Fks seems to be a little time consuming process 🤔 as for every model which has fk to the moved model will be re-created twice, .

Instead we can do another thing --> In 1st migration file in old app: rename model table (only in database) --> In 1st migration file in new app: create new model in state only as well as alter referencing fields of models present in new app --> In 2nd migration file in old app: alter referencing fields of models present in old app and delete model from only state.(replacing the past migrations with "new past migrations" point is not included yet).

>Having just written the above paragraph, it occurred to me that instead of editing past migrations for app removal, a mechanism like squashing could be used -- which replaces the past migrations with "new past migrations". Seems worth investigating, though at this point it's just a half-baked idea and the details are entirely unclear to me.

Would surely look into it.

**Comment by shaib** [comment]
Hi, this is just to let you know that I probably won't have time for this until the weekend.

**Comment by DevilsAutumn** [comment]
> Hi, this is just to let you know that I probably won't have time for this until the weekend.

No worries ,  I'll wait.  👍

**Comment by DevilsAutumn** [comment]
>Instead we can do another thing --> In 1st migration file in old app: alter model table (using ```AlterModelTable```)--> In 1st migration file in new app: create new model (using ```CreateModel```) in state only and add ```AlterField``` for fks (if any) of models in new app pointing to the moved model --> In 2nd migration file in old app: add ```AlterField``` for fks (if any) of models in old app pointing to the moved model  and add ```DeleteModel``` for deleting old state of model only. Then if we run ```squashmigrations``` command , we'll have moved model migration operations in new app.

Hey @shaib , any opinions about this approach?

**Comment by shaib** [comment]
Hi, sorry for the delay. I took a look at the migrations. The general approach seems sensible, and an improvement to my suggestion: The breaking of my one operation `SendModel` into `AlterModelTable` and `DeleteModel(in state only)` allows you to simplify the handling of FKs pointing to the moved model -- now they can be "moved" from the model in the old app to a model in the new app, at a point in time where both models exist and point to the same table. Clever.

I find it hard to assess if there are risks in having, temporarily, two models point to the same table. My basic instinct is that it will be fine, but it may require more careful examination.

The promise of squash working automatically seems a bit exaggerated -- unless something major changed since I last looked at it, squash works mostly within one app; and as is clearly visible in the graph, there is a dependency line `cars/0003` -> `tires/0002` -> `cars/0002` -> `tires/0001`, which prevents any automatic squashing (e.g. if you squash `cars/0002` and `cars/0003`, the result needs to happen both before and after `tires/0002`). And indeed, your `0001_squashed_0003` migration in cars has the `tires` dependency commented out, but it does need it (creates a FK to `tires.tires`), and it has the "replaces `cars/0001`" designation commented out, but it does repeat the creation of the `Cars` model.

But all in all, I'd say you're on the right track.

**Comment by DevilsAutumn** [comment]
> I have also created a [draft proposal](https://gist.github.com/DevilsAutumn/7a3cd4567d0aef9d096abf2e0b9f7ffd) and posted it on the [forum](https://forum.djangoproject.com/t/gsoc-2023-discussion-moving-models-between-apps/18942/5), would be really helpful if you could take a look and provide your feedback there .

@felixxm @charettes would you mind taking a look at my proposal and provide some feedback please?

**Comment by carltongibson** [comment]
Hi @DevilsAutumn — I had a look at your proposal. It's looks good. Exact implementation details can be worked on during the project. The goal at this stage is to show that you have a firm grasp. Please do submit.

**Comment by DevilsAutumn** [comment]
@carltongibson Okay, thanks!

**Comment by DevilsAutumn** [comment]
Thankyou @shaib for your help and support! My proposal got accepted into Google summer of code 2023.

**Pull request closed without merging**
