### PR TITLE
Used assertRaisesMessage() in various tests.

### PR DESCRIPTION
**Pull request by hramezani**

### CODE REVIEW

**Comment by felixxm** [comment]
@hramezani Can you explain what this change fix?

**Comment by hramezani** [comment]
> @hramezani Can you explain what this change fix?

Sorry, it was wrong. I changed the title.
There are more tests like this. We can keep open the PR, K will fix them as well.

**Comment by hramezani** [comment]
@felixxm I replaced `assertRaisee` with `assertRaisesMessage` in more tests.
There are still more that can be replaced but need more changes, So I haven't changed them.

**Comment by felixxm** [comment]
@hramezani Thanks :+1: I think it's worth to merge this. I pushed a few more.

**Pull request merged**
