### PR TITLE
Fixed #33727 -- Fixed color contrasts in admin header.

### PR DESCRIPTION
**Pull request by malnajdi**
Hello Team, 

This is my first easy picked ticket to get familiar on the contribution process.
Kindly let me know if i needed to do any changes to this PR.

Thanks.

### CODE REVIEW

**Review by felixxm — COMMENTED** [review]
@malnajdi Thanks :+1: 

As far as I'm aware, @thibaudcolas's suggestion was to remove `border-bottom` on focus instead of changing it's color, so I'd modify `#user-tools a:focus, #user-tools a:hover,
#logout-form button:active, #logout-form button:hover` rule to the
```css
#user-tools a:focus, #user-tools a:hover,
#logout-form button:active, #logout-form button:hover {
    text-decoration: none;
    border-bottom: 0;
}
```
We should also keep 24px heading on smaller screens, it can be done by removing `font-size: 1.25rem;` for `#branding h1` from `responsive.css`.

**Comment by malnajdi** [comment]
> @malnajdi Thanks +1
> 
> As far as I'm aware, @thibaudcolas's suggestion was to remove `border-bottom` on focus instead of changing it's color, so I'd modify `#user-tools a:focus, #user-tools a:hover, #logout-form button:active, #logout-form button:hover` rule to the
> 
> ```css
> #user-tools a:focus, #user-tools a:hover,
> #logout-form button:active, #logout-form button:hover {
>     text-decoration: none;
>     border-bottom: 0;
> }
> ```
> 
> We should also keep 24px heading on smaller screens, it can be done by removing `font-size: 1.25rem;` for `#branding h1` from `responsive.css`.

done as suggested.

**Comment by felixxm** [comment]
@thibaudcolas Can you take a look?

**Review by thibaudcolas — CHANGES_REQUESTED** [review]
Almost there! Just need to remove the color override on hover/focus to fix the contrast issue.

**Comment by malnajdi** [comment]
> Almost there! Just need to remove the color override on hover/focus to fix the contrast issue.

removed.

**Review by felixxm — APPROVED** [review]
@malnajdi Thanks for updates :+1: Welcome aboard :boat:

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Comment by malnajdi** [comment]
> @malnajdi Thanks for updates +1 Welcome aboard boat

Thanks a lot @felixxm

**Pull request merged**
