### PR TITLE
Fixed #27110 -- Prevented makemigrations from creating the django_migrations table.

### PR DESCRIPTION
**Pull request by timgraham**
https://code.djangoproject.com/ticket/27110

### CODE REVIEW

**Comment by timgraham** [comment]
@SydneyUniLibrary-Jim, would you care to review since this follows your work in 76ab8851181675a59425f9637bdbf3f2de95f6f1? Thanks.

**Comment by SydneyUniLibrary-Jim** [comment]
Without the monkey patch in ```test_makemigrations_other_datbase_is_readonly``` (I only just noticed the typo in this name) there is no longer anything emulating a readonly database.

With this patch ```makemigrations``` fails with my read-only database. I see the following exception:
<pre>  (... snip ...)
  File "/usr/lib/python3.5/site-packages/django/core/management/commands/makemigrations.py", line 100, in handle
    loader.check_consistent_history(connection)
  File "/usr/lib/python3.5/site-packages/django/db/migrations/loader.py", line 276, in check_consistent_history
    applied = recorder.applied_migrations(ensure_schema=False)
  File "/usr/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 70, in applied_migrations
    return set(tuple(x) for x in self.migration_qs.values_list("app", "name"))
  (... snip ...)
django.db.utils.ProgrammingError: relation "django_migrations" does not exist
LINE 1: ...igrations"."app", "django_migrations"."name" FROM "django_mi...
                                                             ^<pre>

**Comment by timgraham** [comment]
Thanks Jim, hopefully the latest patch should fix that.

**Comment by timgraham** [comment]
I need some advice about the MySQL failure. If I put `test_readonly_database` in a separate `TestCase there's no failure, otherwise the test that runs after it, `test_run_before`, errors with "An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block." I guess it's something related to MySQL handling of the schema changes (the first test is temporarily renaming the django_migrations table, then changing it back).

**Comment by charettes** [comment]
I haven't dig into the whole issue but I know that MySQL automatically issues a COMMIT when using DDL.

**Comment by timgraham** [comment]
I think tests that make schema changes need to go in `TransactionTestCase` then.

**Comment by timgraham** [comment]
Jim, could you check the latest patch?

**Comment by timgraham** [comment]
An alternate proposal about consulting database routers is under discussion in [#27142](https://code.djangoproject.com/ticket/27142). It would be nice to have some confirmation that it solves your use case.

**Comment by timgraham** [comment]
Closing in favor of https://github.com/django/django/pull/7194.

**Pull request closed without merging**
