### PR TITLE
Document django.template.context_processors.tz

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by berkerpeksag** [comment]
Looks good to me, but since this is not a typo fix you need to create a ticket at https://code.djangoproject.com/newticket See https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/submitting-patches/#submitting-patches for details.

**Comment by bmispelon** [comment]
The context processor is briefly mentioned in https://docs.djangoproject.com/en/1.9/topics/i18n/timezones/#get-current-timezone.

Would it be possible to rewrite that section and link to this new reference documentation? Something like "Alternatively, you can activate the tz context processor (link) and use the TIME_ZONE context variable".

Thanks.

**Comment by scop** [comment]
Makes sense to me, updated. Hopefully I got the way to link to `tz()` right.

**Comment by bmispelon** [comment]
Thanks! :sparkles:

**Pull request merged**
