### PR TITLE
Refs #27236 -- Clarified that "historical migrations" means "already applied".

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Comment by carltongibson** [comment]
Yes, I think it clarifies the meaning somewhat. 👍 

@collinanderson do you think this assists some?

**Review by carltongibson — APPROVED** [review]

**Comment by collinanderson** [comment]
Hmm... I'm not sure I like defining "historical migrations" as "already applied". What if I need to take an old database backup and apply migrations to it? Now those "historical migrations" _aren't_ applied. Can I apply these historical migrations to an old database backup after 5.1? It's unclear to me what the behavior would be after after 5.1.

**Comment by collinanderson** [comment]
Isn't the main point that deprecated migrations operations are never auto-generated by Django any more, and generally shouldn't be used in new migrations, but the migration operations won't actually be removed?

(If they are being removed, then it should say what replacement operation I should be using instead so I can go into my historic migrations and edit them to remain compatible.)

**Comment by felixxm** [comment]
or .... https://code.djangoproject.com/ticket/27236#comment:36

**Comment by felixxm** [comment]
Closing in favor of #15861.

**Pull request closed without merging**
