### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by mHulb**
Fixed two very minor typos I noticed while reading the documentation.

### CODE REVIEW

**Comment by timgraham** [comment]
I'm not positive that the current version is incorrect. Can you cite a grammar rule?

**Comment by mHulb** [comment]
My line of thinking was that the verbs "implement" and "accept" should be in [third-person singular](https://en.wiktionary.org/wiki/third-person_singular) form. 

Since "it" is a singular pronoun and "__init__() method" is a singular noun, the corresponding verbs (implement, accept) should have an [s appended to them](https://en.wiktionary.org/wiki/-s#Suffix) satisfy this rule.

**Comment by cjerdonek** [comment]
I'm pretty sure the current wording is correct and that the tense (or mood?) is called the subjunctive. For example, [this grammar site](http://grammarist.com/grammar/subjunctive-mood/) provides the following example:

> I suggest that he implement a budget cut in March.

**Comment by mHulb** [comment]
Hey, that's something I had actually never heard of! Didn't even think that far, just assumed it was a typo because it didn't sound "right" to me. Thanks for the lesson in English grammar.

I was a bit over-eager to contribute something (no matter how trivial), I guess.

**Pull request closed without merging**
