### PR TITLE
Fixed 24286: Moved django/core/files/locks.py to django/utils/locks.py

### PR DESCRIPTION
**Pull request by gmunumel**
ticket_24286: moved django/core/files/locks.py to django/utils/locks.py

### CODE REVIEW

**Comment by timgraham** [comment]
You also need to update the imports to reference the new location. Docs build failure is unrelated to your changes (as you haven't changed any documentation).

**Comment by gmunumel** [comment]
Thanks for the help @timgraham. As you said, this error should be normal. Anyways I changed all the imports I found. Let me know if everything ok. Thanks.

**Comment by timgraham** [comment]
I think it might be clearer to put this in `django/utils/files/locks.py` -- any thoughts on that?

**Comment by timgraham** [comment]
Did you try running the tests? I think an `__init__.py` file is needed in `django/utils/files`. Please squash commits when you are finished, thanks.

**Comment by gmunumel** [comment]
It is good now? Maybe I'm missing something, hahaha. It's the first time I squashed commits.

**Comment by timgraham** [comment]
After some more consideration (see the ticket), I don't think there's much value to the change. Sorry for the wasted effort, but hopefully you learned a couple things you can apply in future contributions.

**Comment by gmunumel** [comment]
Yes, actually. Don't worry. :+1:

**Pull request closed without merging**
