### PR TITLE
Enabled GROUP BY and ORDER BY selected aliases.

### PR DESCRIPTION
**Pull request by charettes**
Per @apollo13's request in https://github.com/django/django/pull/15831#issuecomment-1253406423

### CODE REVIEW

**Comment by apollo13** [comment]
Wow this already looks great. There seems to be one failure with nulls first/last which is probably due to the fact that nulls first/last is a hack :D I will test it against psycopg3 asap to see how many failures it fixes

**Comment by apollo13** [comment]
buildbot, test on oracle.

**Comment by apollo13** [comment]
The generated query when it fails is:
```sql
SELECT DISTINCT "ordering_author"."id", "ordering_author"."name", "ordering_author"."editor_id", (
    SELECT MAX(U0."pub_date") AS "last_date" FROM "ordering_article" U0 
        WHERE (U0."author_id" = ("ordering_author"."id") AND UPPER(U0."headline"::text) LIKE UPPER('%Article%')) GROUP BY U0."author_id"
    ) AS "last_date", "last_date" 
FROM "ordering_author" ORDER BY 
"last_date" ASC NULLS FIRST
```

Somehow it pushes the `last_date` alias into the select clause again.

Btw, do we need to hide this behind a database future flag (ie do all databases have to support this)?

**Comment by charettes** [comment]
@apollo13 I think the latest pushed changes should do.

Also notes for the future, `SQLCompiler.get_extra_select` doesn't some very nasty stuff by using a regex to scan the `order_by` SQL to extract the bits before the `DESC NULLS` bits. There's likely a better way to do that as that seems very brittle.

I would actually argue that we should deprecate this behaviour of automatically augmenting the `SELECT`  clause when ordering by fields that are not selected [just like SQLAlchemy did](https://docs.sqlalchemy.org/en/14/changelog/changelog_14.html?highlight=release+notes#change-b2e18f8a880fe1298d5ab33ea2e1a524).

**Comment by apollo13** [comment]
Wow thanks. That was fast :)

> by using a regex to scan

Yeah, and depending on how you constructed the `ORDER BY` the regex is not correct either :D Luckily we can get rid of it in a separate commit. 

> I would actually argue that we should deprecate this behaviour of automatically augmenting the SELECT clause when ordering by fields that are not selected [just like SQLAlchemy did](https://docs.sqlalchemy.org/en/14/changelog/changelog_14.html?highlight=release+notes#change-b2e18f8a880fe1298d5ab33ea2e1a524).

Would love to, but backwards compat will probably prevent us from doing it :/

**Comment by apollo13** [comment]
buildbot, test on oracle.

**Comment by charettes** [comment]
> Would love to, but backwards compat will probably prevent us from doing it :/

It would require a deprecation period but it's achievable by having the warning point at including fields you want to order by in the `values` call that you made. [That's the approach SQLAlchemy took](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#migration-20-query-distinct).

**Comment by apollo13** [comment]
Okay, so Oracle doesn't support grouping by alias :D I guess we will hide it behind a database feature flag then.

**Comment by apollo13** [comment]
Hrmpf, I do not think we can easily use database feature checks at that level of the Query class. Is there any chance we can move this part https://github.com/django/django/pull/16084/files#diff-fd2300283d1546e36141373b0621f142ed871e3e8856e07efe5a22ecc38ad620R2234 somewhere where `using` or the `connection` object exists?

**Comment by charettes** [comment]
@apollo13 yeah it shouldn't be too hard.

In `SQLCompiler.get_group_by` we just have to special case `expressions` that are instances of `Ref` and turn them into `expr.source` based on a `self.connection.features.supports_group_by_ref` flag.

**Comment by charettes** [comment]
I assume we might need something similar for ordering but the latest commit should address the `GROUP BY` issue on Oracle.

**Comment by charettes** [comment]
buildbot, test on oracle.

**Comment by apollo13** [comment]
`ODER BY` should be fine! I will rebase my psycopg3 onto it for testing and will then pass this one on for review to @felixxm

**Comment by apollo13** [comment]
So I added your commits to my psycopg branch and so far it looks relatively great. I needed to add https://github.com/apollo13/django/commit/d9f4bab2d03d62cce1370b01ff8a0ed965b31ed2 so expression wrappers are properly aliased as well. Is this correct?

There is one remaining failure in https://github.com/apollo13/django/actions/runs/3118674080/jobs/5058118585 that I do not know how to fix:
```
======================================================================
ERROR: test_aggregation_exists_multivalued_outeref (aggregation.tests.AggregateTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/django/django/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/psycopg/cursor.py", line 725, in execute
    raise ex.with_traceback(None)
psycopg.errors.GroupingError: subquery uses ungrouped column "aggregation_book.publisher_id" from outer query
LINE 1: ... "aggregation_book" U0 WHERE U0."publisher_id" = ("aggregati...
                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/usr/local/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/__w/django/django/tests/aggregation/tests.py", line 1667, in test_aggregation_exists_multivalued_outeref
    self.assertCountEqual(
  File "/usr/local/lib/python3.10/unittest/case.py", line 1188, in assertCountEqual
    first_seq, second_seq = list(first), list(second)
  File "/__w/django/django/django/db/models/query.py", line 394, in __iter__
    self._fetch_all()
  File "/__w/django/django/django/db/models/query.py", line 1876, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/__w/django/django/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "/__w/django/django/django/db/models/sql/compiler.py", line 1518, in execute_sql
    cursor.execute(sql, params)
  File "/__w/django/django/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/__w/django/django/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/__w/django/django/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/__w/django/django/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/__w/django/django/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/site-packages/psycopg/cursor.py", line 725, in execute
    raise ex.with_traceback(None)
django.db.utils.ProgrammingError: subquery uses ungrouped column "aggregation_book.publisher_id" from outer query
LINE 1: ... "aggregation_book" U0 WHERE U0."publisher_id" = ("aggregati...
                                                             ^
```

I tried a few things but it then broke other tests :D Basically the `Exists` of this test is not aliased but replicated in the `GROUP BY`. Any ideas, fixes? :)

**Comment by charettes** [comment]
> I needed to add https://github.com/apollo13/django/commit/d9f4bab2d03d62cce1370b01ff8a0ed965b31ed2 so expression wrappers are properly aliased as well. Is this correct?

It seems correct yes, it might break future things like https://github.com/django/django/pull/16121/files#diff-359ab56295cce36b9597e1d65185f695f271955617b40f43df58ce3fe76fd0c8R1258 but it is correct for now.

> I tried a few things but it then broke other tests :D Basically the Exists of this test is not aliased but replicated in the GROUP BY. Any ideas, fixes? :)

I decided to move all of this work in a single PR for an easier review. I pushed an extra commit in #15831 that should deal with the failure.

**Pull request closed without merging**
