### PR TITLE
Fixed #30725 -- Fixed width of DateTimeField inputs in admin tabular inline.

### PR DESCRIPTION
**Pull request by minho42**
This fixed CSS issue of shrunken DateTimeField input box in admin when using user's own local timezone in settings.TIME_ZONE instead of "UTC" or other timezones.

https://code.djangoproject.com/ticket/30725

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Comment by felixxm** [comment]
obraz

Let's clarify where is an issue, when `TIME_ZONE = 'UTC'` we display a note
```
Note: You are 2 hours ahead of server time.
```
which prevents `datetime` paragraph from being shorter than ~ 217 pixels. I don't think that we should set `width: auto` because fields will have various widths:
obraz
Removing `min-width: 0;` should be enough.

**Comment by felixxm** [comment]
@elky Can you take a look?

**Comment by elky** [comment]
@felixxm looks good to me. Can you please also check it doesn't break anything on mobile?

**Comment by minho42** [comment]
Thanks for reviewing @felixxm and @elky 

If I just remove `min-width: 0;` without adding `'width: auto;'`
'Date' field is Okay.
But 'Time' field is shrunken a bit hiding seconds e.g. `[20:24:1]`

Please check again with the timezone set to your own local timezone.

**Comment by felixxm** [comment]
Removing only `min-width` works for me on firefox and chrome (also on mobile).

Before:
obraz

After:
obraz

**Comment by minho42** [comment]
@felixxm 

I tested with other fields next to the DateTimeField to look like issue reporter's screenshot.
https://code.djangoproject.com/attachment/ticket/30725/firefox.png

> You need to put the DateTimeField in the TabularInline along with other fields such as CharField and Text field. When there are a number of fields, the TabularInline becomes scrollable from left to right and the text box of the DateTimeField becomes very small.

Screen Shot 2019-09-17 at 18 32 10

**Comment by felixxm** [comment]
@elky Thanks for checking, it looks good on mobile.

**Comment by minho42** [comment]
Thanks @felixxm 
Yes it fixed.
I reverted my changes and applied your code.

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Pull request merged**
