### PR TITLE
Add Filtered Aggregate to Postgres contrib app

### PR DESCRIPTION
**Pull request by funkybob**
This adds support for PG9.4 "aggrgate() FILTER (WHERE ...)" to annotate.

### CODE REVIEW

**Comment by funkybob** [comment]
Currently this is failing because FilterAgg triggers its field to be added to the GROUP BY clause...

```
SELECT "postgres_tests_filteraggparentmodel"."id",
    COUNT("postgres_tests_filteraggtestmodel"."id") FILTER(WHERE "postgres_tests_filteraggtestmodel"."integer_field" = 0) AS "zero_count",
    COUNT("postgres_tests_filteraggtestmodel"."id") AS "child_count" 
FROM "postgres_tests_filteraggparentmodel" 
LEFT OUTER JOIN "postgres_tests_filteraggtestmodel" ON ("postgres_tests_filteraggparentmodel"."id" = "postgres_tests_filteraggtestmodel"."parent_id") 
GROUP BY "postgres_tests_filteraggparentmodel"."id", "postgres_tests_filteraggtestmodel"."integer_field"
```

**Comment by charettes** [comment]
Did you try subclassing `django.db.models.aggregates.Aggregate` instead?

**Comment by funkybob** [comment]
Yeah, I did, and it came up with a less meaningful error.

However, digging further exposed:

1. Adding "contains_aggregate = True" _prob
2. Like Aggregate does, I added a `get_group_by_cols` method that returns an empty list.

Tests now pass.

I removed the "contains_aggregate" property, and it still passes.

**Comment by funkybob** [comment]
In order to make deriving from Aggregate work, I need to add:

```
    def resolve_expression(self, *args, **kwargs):
        return Expression.resolve_expression(self, *args, **kwargs)
```

Which feels very hacky to me...

**Comment by charettes** [comment]
Since there's no performance benefit of using `FILTER` on PostgreSQL over `COUNT(CASE WHEN)` I'd rather see an additional `filter` kwarg added to aggregation functions (`Count`, `Sum`, ...) that makes conditional aggregates more readable. The [django-aggregate-if](https://github.com/henriquebastos/django-aggregate-if) project used a similar syntax and it makes the code more readable IMHO.

We could even define `as_postgresql` method to use `FILTER` if we want to make are automatically generated queries more readable.

**Comment by jarshwah** [comment]
I thought I wrote a comment here but obviously not. You need `contains_aggregate` for when another expression wraps the filter aggregate. Need a test to ensure that works also.

**Comment by timgraham** [comment]
Is this meant to be merged (if so, is there a ticket?)? I thought someone said something like "this should be in third-party package" but I could be thinking about something else.

**Pull request closed without merging**
