### PR TITLE
Fixed #28576 -- Added color interpretation method to GDALBand.

### PR DESCRIPTION
**Pull request by ndalton12**
Adds color interpretation method to GDALBand. [Ticket](https://code.djangoproject.com/ticket/28576)

### CODE REVIEW

**Comment by claudep** [comment]
@yellowcap Care to take a look?

**Comment by claudep** [comment]
@ndalton12 This isn't going to enter 1.11. Even for 2.0, the new feature freeze has passed now (but I think you should still target 2.0 temporarily).

**Comment by yellowcap** [comment]
The color interpretation can also be set, we could also add the [`SetColorInterpretation`](http://www.gdal.org/gdal_8h.html#ab29a78b421ca97f50a8f1ac9d6035df4) functionality. But that was not the goal of the ticket, so I think its fine like this too.

**Comment by ndalton12** [comment]
Just FYI, I've updated the docs to temporarily target 2.0

**Comment by claudep** [comment]
@timgraham Do you think we could give a chance to this patch to enter 2.0?

**Comment by claudep** [comment]
Awesome, thanks!

**Comment by ndalton12** [comment]
Thanks for the reviews/comments guys.

**Pull request merged**
