### PR TITLE
Fixed OpenLayers.Layer.OSM constructor in openlayers-osm.html.

### PR DESCRIPTION
**Pull request by bgaechter**
Old constructor didn't work anymore

### CODE REVIEW

**Comment by timgraham** [comment]
Can you provide any additional details? Is it broken in Django 1.9 and/or 1.8?

**Comment by bgaechter** [comment]
I tested it with Django 1.9 and OpenLayers 2.13.1.
The error says: "Uncaught TypeError: OpenLayers.Layer.OSM.Mapnik is not a constructor".
After changing the constructor it works again.

**Comment by timgraham** [comment]
@claudep, can you advise? Not sure if it's been broken since its introduction in b16b72d415808073da0418de93bf32f71ead959d. Not sure if we should try for a test too.

**Comment by claudep** [comment]
Ticket and test, yes please!

**Comment by timgraham** [comment]
@bgaechter, any chance you can provide a ticket and test?

**Comment by timgraham** [comment]
Closing due to lack of follow up.

**Comment by claudep** [comment]
I investigated about adding a test. This does not belong to JS tests, and I'm reluctant to add a live server test with network dependencies. I think we could just commit this, only fools never change their mind!

**Comment by claudep** [comment]
Committed in 4e2ee866275. Thanks!

**Pull request closed without merging**
