### PR TITLE
Updated OWASP Top 10 link in security topic.

### PR DESCRIPTION
**Pull request by grammy-jiang**
The latest version of OWASP Top 10 list is 2021, and OWASP has a page for this project. So referring to the project homepage is better than a specific version of it.

### CODE REVIEW

**Comment by felixxm** [comment]
@grammy-jiang Thanks :+1: What do you think about using https://owasp.org/Top10/ instead?

**Comment by grammy-jiang** [comment]
Hi, @felixxm, both of them are okay to me:
* from the url, both of them are not limited to only one yearly report
* from the context in the document, readers will expect the page list some pullet points about security issues, and both of urls have these pullet points

So, if you prefer https://owasp.org/Top10/, I am okay to turn to this link.

**Comment by grammy-jiang** [comment]
Hi, @felixxm, updated!

**Comment by felixxm** [comment]
@grammy-jiang Thanks :+1: Welcome aboard :boat:

**Pull request merged**
