### PR TITLE
Refs #21171 -- Made Collector.delete() rollback in the correct database.

### PR DESCRIPTION
**Pull request by charettes**
Noticed here https://github.com/django/django/pull/10448/files#r430711757

### CODE REVIEW

**Comment by felixxm** [comment]
Can we add a test?

**Comment by charettes** [comment]
It would be quite involved as it would require using `TransactionTestCase` with `databases = {'default', 'other'}` and making `delete_batch` with a `mock` `side_effect`. If you think that's worth doing I can give it a shot.

**Comment by felixxm** [comment]
It's a regression, so I think it's worth. Thanks!

**Comment by felixxm** [comment]
On the other side it's really niche :shrug:

**Comment by charettes** [comment]
Thanks for the merge, never got to spend time writing a test.

**Pull request merged**
