### PR TITLE
Make checks to the HTTP methods more efficient.

### PR DESCRIPTION
**Pull request by KommuSoft**

### CODE REVIEW

**Comment by smithdc1** [comment]
I'm not sure this is more efficient.

```
In [1]: from django.utils.datastructures import OrderedSet

In [2]: http_list = ['get', 'post', 'put', 'patch', 'delete', 'head', 'options', 'trace']

In [3]: http_ordered_set = OrderedSet(['get', 'post', 'put', 'patch', 'delete', 'head', 'options', 'trace'])

In [4]: %timeit 'get' in http_list
92.9 ns ± 0.272 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [5]: %timeit 'get' in http_ordered_set
449 ns ± 2.81 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [8]: %timeit 'error' in http_list
427 ns ± 4.55 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [9]: %timeit 'error' in http_ordered_set
447 ns ± 4.11 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

**Comment by charettes** [comment]
yeah even if `list.__contains__` is `O(n)` and `set.__contains__` is `O(1)` in theory it doesn't make much of a difference when `n` is small and bounded like it's the case here.

I assume most of the `set_contains` time is spent doing `PyObject_Hash` which is not necessary when comparing each values in `list_contains`.

https://github.com/python/cpython/blob/81f87bbf9f65702062021a78abd9b8f82c98a414/Objects/listobject.c#L422-L436
https://github.com/python/cpython/blob/81f87bbf9f65702062021a78abd9b8f82c98a414/Objects/setobject.c#L1797-L1815

**Comment by KommuSoft** [comment]
The interesting part is, if I use `OrderedSet` from the [`orderedset` package](https://pypi.org/project/orderedset/), with as test:

```
from orderedset import OrderedSet
from timeit import timeit

http_list = ['get', 'post', 'put', 'patch', 'delete', 'head', 'options', 'trace']

http_ordered_set = OrderedSet(['get', 'post', 'put', 'patch', 'delete', 'head', 'options', 'trace'])

def f():
    return 'get' in http_list

def g():
    return 'get' in http_ordered_set

def h():
    return 'trace' in http_list

def i():
    return 'trace' in http_ordered_set

def j():
    return 'error' in http_list

def k():
    return 'error' in http_ordered_set

print(timeit(f, number=1000000))
print(timeit(g, number=1000000))
print(timeit(h, number=1000000))
print(timeit(i, number=1000000))
print(timeit(j, number=1000000))
print(timeit(k, number=1000000))
```
(the second is thus always the hashset).

I got:
```
0.08802980100153945
0.067581251001684
0.12704176000261214
0.06573162101267371
0.14386638600262813
0.074997046001954
```
second run:
```
0.061050588003126904
0.06561586199677549
0.12597569399804343
0.06581024199840613
0.14262849699298386
0.06996185499883723
```
:)

**Comment by KommuSoft** [comment]
Perhaps it would make more sense to remove the `OrderedSet` then and work with one of the `orderedset` package, since this seems to have less overhead. Of course not to determine if a HTTP method is valid, but more in general to achieve more speedup.

**Comment by pope1ni** [comment]
> Perhaps it would make more sense to remove the `OrderedSet` then and work with one of the `orderedset` package, …

The `orderedset` package use Cython, so of course it'll be faster. Is this the lowest hanging fruit for improving the performance of processing a request? If not, I feel attention is best focused elsewhere.

The threshold for adding new dependencies to Django is quite high. A small improvement such as this is unlikely to meet that threshold.

**Comment by KommuSoft** [comment]
> The `orderedset` package use Cython, so of course it'll be faster.

Well it is not that much the fact that it uses `Cython`, since Python's builtin sets, etc. make use of C++ data structures. I only meant that the overhead is (likely) not hashing, etc., it is simply the fact that the `OrderedSet` in Django will now result in two calls: one for the `OrderedSet`, and one for the dictionary it wraps. An idea could be to subclass the dictionary, and slightly thus alter the constructor, this would get rid of the double call. Another idea could be to look if we need the collection to be ordered, if not, then a `set` itself is sufficient, but at that moment, I'm not sure we can do this, because some packages might depend on the fact that it is a list.

**Comment by KommuSoft** [comment]
Ok, I found I think a way which is quite inelegant, but basically uses a dictionary as an ordered set, like Django's `OrderedSet` class:

```
In [1]: http_list = ['get', 'post', 'put', 'patch', 'delete', 'head', 'options', 'trace']                                                                                                    

In [2]: http_set = {'get': (), 'post': (), 'put': (), 'patch': (), 'delete': (), 'head': (), 'options': (), 'trace': ()}                                                                     

In [3]: %timeit 'get' in http_set                                                                                                                                                            
30 ns ± 1.39 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [4]: %timeit 'get' in http_list                                                                                                                                                           
28.5 ns ± 3.8 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [5]: %timeit 'trace' in http_set                                                                                                                                                          
33.3 ns ± 1.09 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [6]: %timeit 'trace' in http_list                                                                                                                                                         
95 ns ± 2.15 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [7]: %timeit 'error' in http_set                                                                                                                                                          
29.8 ns ± 0.58 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [8]: %timeit 'error' in http_list                                                                                                                                                         
106 ns ± 2.05 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```

**Pull request closed without merging**
