### PR TITLE
Fixed #33442 -- Allowed GeoIP2 to use DB-IP Lite datasets.

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
I'm a bit annoyed to create a test for this, looks a bit complicated.

**Comment by felixxm** [comment]
@claudep Thanks for this patch :+1: I confirmed locally that it works. It's probably not worth to add "lite" databases to our test suite.

**Review by pauloxnet — APPROVED** [review]

**Comment by claudep** [comment]
Is an entry in release notes worth it?

**Comment by felixxm** [comment]
> Is an entry in release notes worth it?

IMO, it won't hurt.

**Comment by felixxm** [comment]
@claudep Thanks for docs changes :+1:

**Pull request merged**
