### PR TITLE
Fixed #26919 -- Included admin action form's media in changelist view's media

### PR DESCRIPTION
**Pull request by stkrp**
https://code.djangoproject.com/ticket/26919

### CODE REVIEW

**Comment by charettes** [comment]
This is missing regression tests.

Please uncheck _patch needs improvement_ and _needs tests_ on the [Trac ticket](https://code.djangoproject.com/ticket/26919) when it's added to the patch. Thanks!

**Comment by timgraham** [comment]
@stkrp, do you plan to add a test or should we close this and let someone else do it?

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by stkrp** [comment]
I'm sorry for the delay.

**Comment by timgraham** [comment]
merged in b387189d86aa6f0b8dd5e9ff2facb725e6beb7a9, thanks!

**Pull request closed without merging**
