### PR TITLE
Fixed #29882 - add --routines when cloning mysql

### PR DESCRIPTION
**Pull request by danizen**
- Added '--routines' to mysqldump when cloning for parallel test run.
- No tests provided as mysqldump is external.
- Ticket #29882 has a reference to a repository that reproduced issue and shows it is fixed.

### CODE REVIEW

**Comment by thomazzo** [comment]
That wouldn't work as you could be overriding one the `mysqldump` options

**Comment by adamchainz** [comment]
Yes @danizen , @thomazzo is right - his PR #10581 implements correct algo

**Comment by qeternity** [comment]
Disappointing, seems like a pretty blatant attempt to quicky steal attribution @danizen

**Comment by adamchainz** [comment]
@qeternity it's not, if you see the ticket there was no PR from @thomazzo originally and Dan was eager to contribute. Please use the principle of charity when interpreting others' actions on the internet https://en.wikipedia.org/wiki/Principle_of_charity

**Pull request closed without merging**
