### PR TITLE
Updated admin's XRegExp to 3.2.0.

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Comment by felixxm** [comment]
I think `xregexp.js` is a better option for now because versions 4+ introduced new dependencies, e.g. `babel`.

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Comment by AndreasDickow** [comment]
is there a chance that an update to latest (5.1.0) could take place? 
The old dependency of 3.2.0 was seen as a potential thread by the pentesters of my application.

**Comment by felixxm** [comment]
> is there a chance that an update to latest (5.1.0) could take place?

Sure, feel-free to prepare PR.

**Pull request merged**
