### PR TITLE
Fixed #29007 -- Fixed DecimalValidator crash on NaN, SNan, Inf, and Infinity values.

### PR DESCRIPTION
**Pull request by bfabio**
https://code.djangoproject.com/ticket/29007

### CODE REVIEW

**Comment by charettes** [comment]
Thank you for your contribution. Would it be possible to move the tests to `tests.validators.tests.py` instead? You should be able to test the `DecimalValidator` directly there without dealing with the model layer.

**Comment by bfabio** [comment]
> Would it be possible to move the tests to tests.validators.tests.py instead?

Sure, it's much better that way. Sorry, I'm not familiar with the codebase.

**Comment by bfabio** [comment]
@charettes Can you take a look at it?

**Comment by timgraham** [comment]
I think we should also include similar tests for `DecimalField.clean()` as the second case in this patch still fails:
```diff
diff --git a/tests/forms_tests/field_tests/test_decimalfield.py b/tests/forms_tests/field_tests/test_decimalfield.py
index d3fa222..637c159 100644
--- a/tests/forms_tests/field_tests/test_decimalfield.py
+++ b/tests/forms_tests/field_tests/test_decimalfield.py
@@ -32,6 +32,14 @@ class DecimalFieldTest(FormFieldAssertionsMixin, SimpleTestCase):
             f.clean('a')
         with self.assertRaisesMessage(ValidationError, "'Enter a number.'"):
             f.clean('łąść')
+        with self.assertRaisesMessage(ValidationError, "'Enter a number.'"):
+            f.clean('Infinity')
+        with self.assertRaisesMessage(ValidationError, "'Enter a number.'"):
+            f.clean('sNaN')
+        with self.assertRaisesMessage(ValidationError, "'Enter a number.'"):
+            f.clean('+Infinity')
+        with self.assertRaisesMessage(ValidationError, "'Enter a number.'"):
+            f.clean('-Infinity')
         self.assertEqual(f.clean('1.0 '), decimal.Decimal("1.0"))
         self.assertEqual(f.clean(' 1.0'), decimal.Decimal("1.0"))
         self.assertEqual(f.clean(' 1.0 '), decimal.Decimal("1.0"))
```
I wonder how you reproduced this issue because the other cases already pass without the patch. Can you open a new ticket with details rather than referencing the old ticket?

**Comment by timgraham** [comment]
@bfabio, are you able to continue work on this?

**Comment by bfabio** [comment]
@timgraham I'll try to take a look at it in the next few weeks.

**Comment by bfabio** [comment]
> I wonder how you reproduced this issue because the other cases already pass without the patch.

@timgraham I didn't test against the tree as it was on October 10th, but as of today they don't pass with master without the patch.

**Comment by timgraham** [comment]
The tests that pass are:
```
with self.assertRaisesMessage(ValidationError, "'Enter a number.'"):
    f.clean('Infinity')
with self.assertRaisesMessage(ValidationError, "'Enter a number.'"):
    f.clean('+Infinity')
with self.assertRaisesMessage(ValidationError, "'Enter a number.'"):
    f.clean('-Infinity')
```
You should really open a new ticket that demonstrates how to reproduce the crash reported in [#7777](https://code.djangoproject.com/ticket/7777#comment:17), otherwise this patch doens't have a tracking ticket. Thanks.

**Comment by timgraham** [comment]
I guess closing this meant you didn't want to pursue it any further. I split out the `DecimalField` fix in https://github.com/django/django/pull/9567 and will continue the validator fix here.

**Comment by bfabio** [comment]
@timgraham I was going to create a new ticket and open a new PR. Sorry for the misunderstanding.

**Pull request merged**
