### PR TITLE
Rename the context object from DetailView class.

### PR DESCRIPTION
**Pull request by alephmelo**
The detail.html received an object 'question' via context, so we needed to rename the default object from DetailView class to 'question'. Before it was getting an error. 

```python
    # file_name: polls/views.py
    context_object_name = 'question'

### CODE REVIEW

**Comment by timgraham** [comment]
This works for me as-is. `DetailView` [adds that object](https://github.com/django/django/blob/1175027641f512d33909cb766563328c6b171578/django/views/generic/detail.py#L105-L107) to the context without this change.

**Comment by alephmelo** [comment]
Without this line I get this error.


error

**Comment by timgraham** [comment]
`q_id` may be a typo in your project. This is usually `question_id`.

**Comment by alephmelo** [comment]
I'm using ```q_id``` instead of ```question_id```, that is why I don't think is a typo. 
In my project I used:
```python 
# file_name: polls/views.py
context_object_name = 'q'
```
And this is my ```detail.html```
```html
<h1>{{ q.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' q.id %}" method="post">
{% csrf_token %}
{% for choice in q.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>
```
Anyway, thank you for your attention to this matter. 
:+1:

**Pull request closed without merging**
