### PR TITLE
Simplified SelectFilter2 with Element.closest().

### PR DESCRIPTION
**Pull request by jdufresne**
https://developer.mozilla.org/en-US/docs/Web/API/Element/closest

### CODE REVIEW

**Comment by jdufresne** [comment]
Hmm, while all browsers supported by the admin have `.closest()` available, it looks like PhantomJS does not.

**Comment by charettes** [comment]
Looks like PhantomJS has been pretty much dead for a while https://github.com/ariya/phantomjs/issues/15344

**Comment by pope1ni** [comment]
I guess there is puppeteer instead? I had been using a python-based version called pyppeteer, but that hasn't been maintained in a while. Recently I noticed a fork, pyppeteer2, that is aiming to get up to feature parity with the latest puppeteer...

**Comment by jdufresne** [comment]
> I guess there is puppeteer instead? 

Thanks for this suggestion. Turns out, the latest version of `grunt-contrib-qunit` now uses puppeteer instead of PhantomJS. So just upgrading it was enough. I've now included this in the latest revision.

**Pull request merged**
