### PR TITLE
Refs #17208 -- Converted changeform_view and delete_view into CBV

### PR DESCRIPTION
**Pull request by yoongkang**
Abstracted the changeform_view to a CBV.

Hopefully this will make it more readable.

### CODE REVIEW

**Comment by sasha0** [comment]
It needs rebase and definitely docs.

**Comment by timgraham** [comment]
Did you reject the approach used in earlier versions of the patch that subclassed more specific class-based views like `UpdateView`, `CreateView`, `DeleteView`?

I have mixed feelings about this conversion in general. I guess it makes the views easier to customize, but on the other hand, I think it makes the code more difficult to follow (however I haven't used CBGVs a lot, so it might just be me).

**Comment by timgraham** [comment]
Hi Yoong Kang, any response to my question about the design of this?

**Comment by yoongkang** [comment]
Hi Tim, maybe I need to revisit this later when I have more time. Closing this for now...

**Pull request closed without merging**
