### PR TITLE
Fixed #23173 -- Fixed incorrect stripping of SCRIPT_URL

### PR DESCRIPTION
**Pull request by bpeschier**
Fixed incorrect stripping of SCRIPT_URL

### CODE REVIEW

**Comment by MarkusH** [comment]
buildbot, test this please.

**Comment by MarkusH** [comment]
LGTM

**Comment by bmispelon** [comment]
:shipit:

**Comment by MarkusH** [comment]
Merged in 336512fae77ec214ad6db24166b9a8676007cc09. Thanks.

**Pull request closed without merging**
