### PR TITLE
Fixed #26791 -- Replaced LiveServerTestCase port ranges with binding to port 0.

### PR DESCRIPTION
**Pull request by timgraham**
https://code.djangoproject.com/ticket/26791

[django-developers thread](https://groups.google.com/d/topic/django-developers/_TD8IkSLgqE/discussion)

### CODE REVIEW

**Comment by timgraham** [comment]
buildbot, test on selenium.

**Comment by charettes** [comment]
That was also on my to-do list :) Looks promising!

**Comment by timgraham** [comment]
buildbot, test on selenium.

**Comment by timgraham** [comment]
buildbot, test on selenium.

**Pull request merged**
