### PR TITLE
Fixed #31177 -- Used "raise from" when wrapping exceptions, all over the codebase

### PR DESCRIPTION
**Pull request by cool-RR**
Following [31166](https://code.djangoproject.com/ticket/31166) , I made a regex search to find 90% of places where we use "raise" and should use "raise from".

Trac ticket: https://code.djangoproject.com/ticket/31177

If this is too big for one PR, I could split it to smaller chunks.

@shaib @felixxm If you're interested in giving your opinion here, that'll be helpful.

### CODE REVIEW

**Comment by felixxm** [comment]
Closing per ticket.

**Comment by cool-RR** [comment]
Can this be reopened? And is anyone interested in reviewing?

**Comment by cool-RR** [comment]
I'll do a separate PR for the style guide.

But I think there's a problem with your approach. If we implement the "raise from" policy in little bits, it might take anywhere between 5-10 years until the last case of a missing "raise from" will be fixed. This means:

1. We wouldn't be able to use the Flake8 rule that Jon wrote to ensure that new code follows this policy.
2. People will see plain `raise` in `except` clauses and they wouldn't know it's not okay.
3. People will learn to not give any meaning when they see the text "During handling of the above exception, another exception occurred" in their stacktraces when they're debugging. This is a sort of a chicken-and-egg problem.

What do you think?

**Comment by jdufresne** [comment]
@carltongibson What is the downside to fixing this all in one go? The word "radical" doesn't really communicate this to me. We make many other system wide changes to adopt new best practices. 

Is there a specific exception handler you think shouldn't be chained? If so I think we can allow for special cases when they are identified and reasoned.

**Comment by carltongibson** [comment]
Hey @jdufresne. 

My _concern_ is precisely that bulk edits are themselves _unreasoned_. (The individual changes are not given consideration.) I see us introduce a lot of regressions, which then get reported and we fix. I'd prefer to go slower, and measure twice, cut once for that reason. Maybe there's little risk here, but I'm not sure about that so I'm initially _skeptical_. I hope that makes sense.

**Comment by cool-RR** [comment]
@carltongibson 

I opened a separate PR for the style guide.

Will it help if I split this PR into multiple PRs for similar cases? e.g. form validation, import errors, etc

**Comment by carltongibson** [comment]
@cool-RR No, don't do that.

**Comment by carltongibson** [comment]
OK, sorry for the delay in review. I needed to double-check. 

I'm -1 on this change. I've posted to the mailing list as to why: https://groups.google.com/d/msg/django-developers/ibEOt3A9c2M/sOL7YV5LFwAJ

**Comment by carltongibson** [comment]
Closing as per ticket.

**Pull request closed without merging**
