### PR TITLE
Updated Oracle docs links to the Oracle 12c

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Comment by timgraham** [comment]
Is there a reason to prefer Oracle 11 instead of 12?

**Comment by felixxm** [comment]
Oracle 11g is the min supported version and in all other places in doc with have reference to Oracle 11g. I wanted to keep consistency. Should I update all references to the Oracle 12c?

**Comment by timgraham** [comment]
Yes, that would be fine. For other databases we have links to the latest stable version but I guess the Oracle docs don't provide that?

**Comment by felixxm** [comment]
Not yet.

**Pull request merged**
