### PR TITLE
Refs #25466 -- Removed unused DeprecationInstanceCheck.

### PR DESCRIPTION
**Pull request by adamchainz**
# Trac ticket number

N/A

# Branch description

Unused since ff419de263138e905dff44c5cb806310c70f32aa.

# Checklist
- [x] This PR targets the `main` branch. 
- [x] The commit message is written in past tense, mentions the ticket number, and ends with a period.
- [x] I have checked the "Has patch" ticket flag in the Trac system.
- [x] I have added or updated relevant tests.
- [x] I have added or updated relevant docs, including release notes if applicable.
- [x] I have attached screenshots in both light and dark modes for any UI changes.

### CODE REVIEW

**Comment by felixxm** [comment]
https://github.com/django/django/pull/13156#issuecomment-659321997

**Comment by adamchainz** [comment]
I agree with @jdufresne ’s comment there, and now it’s been another four years without usage. Let’s apply YAGNI and clean up...

**Comment by felixxm** [comment]
> I agree with @jdufresne ’s comment there, and now it’s been another four years without usage. Let’s apply YAGNI and clean up...

Fine, but you will reintroduce it if needed :wink:

**Review by sarahboyce — APPROVED** [review]
Thank you

**Comment by adamchainz** [comment]
> Fine, but you will reintroduce it if needed 😉

I will code it from scratch when called.

**Pull request merged**
