### PR TITLE
Fixed #29019 -- Warn the user about M2M fields being defined in REQUIRED_FIELDS

### PR DESCRIPTION
**Pull request by lnagel**
Please see https://code.djangoproject.com/ticket/29019#comment:5 for a full explanation of the issue.

### CODE REVIEW

**Comment by timgraham** [comment]
I don't think this is the right approach (adding a check that may or may not be correct depending on whether or not the manger is correct). I didn't test it, but I think that even with a custom manager, `createsuperuser` will still crash with the error on the ticket.

**Comment by lnagel** [comment]
@timgraham Could you elaborate why do you think adding this warning is a bad idea / that this is not the right approach?

Advising the user that they also have to write an appropriate create_superuser function seemed to be pretty much the only thing we can do if a M2M field has been configured in REQUIRED_FIELDS.

**Comment by lnagel** [comment]
Just to add that I actually did test writing a custom manager with overriding the create_superuser function and it works well (without the crash you are assuming).

**Comment by timgraham** [comment]
If they have written a custom manager, then the warning still appears, correct?

**Comment by lnagel** [comment]
Yes, the warning still appears, but it does not crash (it's not an error). I was advised that providing a warning in this case would be appropriate, since it can be silenced with SILENCED_SYSTEM_CHECKS.

**Comment by timgraham** [comment]
I guess my opinion on silencing system checks differs from the advice you received. Anyway, I fail to see how writing a custom manager would resolve the crash on the ticket (as far as I see, the manager isn't consulted before the place that crashes). Can you explain it or provide your test project so I can take a look and see if I'm missing something?

**Comment by lnagel** [comment]
Now that you mention it and upon reviewing the original stacktrace, I guess we missed it back then that `createsuperuser.py` would also need some attention in this case. Since there is no code to support M2M fields there either, then for me the case for raising a warning against using M2M fields is even stronger (though the warning text could be adapted to remove the suggestion about writing a custom manager).

The alternative of course is to add M2M support also to `createsuperuser.py`, but one still would not get around the requirement of a custom manager IMO.

**Comment by timgraham** [comment]
We prefer to spend time fixing bugs (fix createsupercuser crash in this case) rather than adding warning that something isn't supported.

As the documentation discusses, adding any field in `REQUIRED_FIELDS` typically requires a custom manager. This isn't the type of thing that we use system checks for.

**Comment by lnagel** [comment]
OK, clear!

**Pull request closed without merging**
