### PR TITLE
Fixed 34039 - added min-width to the admin searchbar on small devices.

### PR DESCRIPTION
**Pull request by clytaemnestra**
Fix for: https://code.djangoproject.com/ticket/34039.

### CODE REVIEW

**Comment by felixxm** [comment]
@clytaemnestra Thanks for this patch :+1: As far as I'm aware, we should stretch the entire block not only the search bar to get:
image

instead of

image

**Review by thibaudcolas — APPROVED** [review]
🌈 tested in Firefox 104, Chrome 92, Ubuntu 20.04 – and Safari 15.6.1 macOS 12.5.1

@felixxm we ended up only fixing the width of the input, not whether or not the whole toolbar (and its background) spans the whole of the screen or not. This whole flexbox implementation is a bit harder to work on.

If we want to fix the toolbar’s background taking up the whole width – could we make that as a separate ticket?

**Review by thibaudcolas — CHANGES_REQUESTED** [review]
Actually I just realised we have more work to do on the tests 🤦

**Review by thibaudcolas — APPROVED** [review]

**Comment by clytaemnestra** [comment]
Tests are fixed. 

@felixxm I created another ticket for that issue: https://code.djangoproject.com/ticket/34047, as agreed above. I could pick it up and check it out, once it's approved.

**Comment by felixxm** [comment]
@thibaudcolas Due to the fact that fixing #16091 is complicated with the current HTML structure, maybe it would be better to close ticket-34047 as a duplicate and fixed both issues together. What do you think?

**Comment by felixxm** [comment]
Closing due to inactivity.

**Pull request closed without merging**
