### PR TITLE
Fixed #26676 -- Prevented prefetching to_attr from caching its result in through attr.

### PR DESCRIPTION
**Pull request by charettes**
Thanks Ursidours for the report.

### CODE REVIEW

**Comment by charettes** [comment]
Suggestions for a better commit message are welcome.

**Comment by akaariai** [comment]
I don't think we should do this change. There is a big performance penalty for generating the querysets.

**Comment by charettes** [comment]
Can you point out where this affect performance? From my initial testing it looks like there not any more work done than before bdbe50a491ca41e7d4ebace47bfe8abe50a58211.

Maybe you are referring to c92123cc1dceeb800b3b8900e2e530ed19d78863 which generates a filtered queryset since Django 1.10? This fix is not related to this change.

**Comment by Ursidours** [comment]
Many thanks Simon for the patch, It works perfectly ! 
I've followed your suggestion and I've opened ticket 26690 about adding an option to explicitly ask for the object stored by prefetch_related to be a queryset or a list. This would allow the developer to choose between flexibility and performance.

**Comment by akaariai** [comment]
I misread the added test, I thought it was testing that to_rooms was a QuerySet instance, while the test checks the rooms attr. Sorry for the noise.

**Pull request merged**
