### PR TITLE
Fixed #26212 - make FileField pickleable

### PR DESCRIPTION
**Pull request by koterpillar**

### CODE REVIEW

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by charettes** [comment]
I see that `lazy_number` is not directly tested but if you could add a test for the underlying issue in `tests/i18n` that would be great!

**Comment by timgraham** [comment]
@claudep, look okay to you? How do you feel about backport to 1.8 and/or 1.9?

**Comment by claudep** [comment]
Looks good. OK to backport to 1.9, not sure about 1.8.

**Comment by timgraham** [comment]
merged in b59f963ad2a49322725b20fac71661bd49643443, thanks!

**Pull request closed without merging**
