### PR TITLE
Fixed #29048 -- Added **extra_context arg to as_vendor methods in database functions.

### PR DESCRIPTION
**Pull request by priyanshsaxena**
Added the required argument to as_sqlite, as_mysql, as_oracle and
as_postgresql methods in classes directly or indirectly derived from
class Func.

### CODE REVIEW

**Comment by timgraham** [comment]
@bobort, can you check if PyCharm is appeased with these changes?

**Comment by bobort** [comment]
Yes, PyCharm seems appeased.  However, in the patch, there are references to the super methods that do not pass on the **extra_context.

**Comment by timgraham** [comment]
Right, well maybe it's better to wontfix the ticket than to complicate things with unused parameters.

**Comment by bobort** [comment]
Then I suggest removing the **extra_context parameter from the SQLiteNumericMixin, as that is where the whole thing started.

**Comment by priyanshsaxena** [comment]
How about only as_sqlite methods be passed the ``**extra_context`` argument ?

**Comment by timgraham** [comment]
`**extra_context` is needed in `SQLiteNumericMixin` because subclasses use it.  Other `as_vendor()` methods aren't in a similar position in the inheritance chain where `**extra_context` is likely to be used. I guess if I had to vote, I'm leave things as is since I don't use PyCharm. @jarshwah, any input?

**Comment by jarshwah** [comment]
There are a bunch of geo functions that require extra_context too. It's definitely required a lot more than just for some sqlite functions.

I don't see any harm in solidifying the API around extra_context being apart of the signature and passed up through super() if someone wants to do that work. It'll improve other dev environments (like vscode) as well as pycharm.

I think extra_context was first provided so that engines could override data provided to the template directly from the `as_vendor` method without writing a bunch of pre/post super() code that manipulated `self`. First class support in the expressions api probably makes sense.

**Comment by timgraham** [comment]
Priyansh, can you update each case to pass `extra_context` to `as_sql()` or `super()`?

**Comment by priyanshsaxena** [comment]
@timgraham I am working on it.

**Comment by timgraham** [comment]
I rebased this and removed some unrelated cosmetic changes. Following the rebase, however, there are many new database functions to update.

**Pull request merged**
