### PR TITLE
Fixed #32096 -- Fixed crash of various expressions with JSONField key transforms.

### PR DESCRIPTION
**Pull request by felixxm**
ticket-32096

I'm going to audit remaining expressions.

Thanks Igor Jerosimić for the report and Simon Charette for the analysis.

### CODE REVIEW

**Review by charettes — COMMENTED** [review]
@felixxm looks about right for the `OrderableAggMixin` case. Should we include the `ExpressionWrapper` and `FieldGetDbPrepValueIterableMixin` cases in this PR as well?

`KeyTransform` happens to be an undocumented API but until we add support from transforms to `F` (it currently drops the `__lang` part silently ticket-31639) it's the only way to _dig_ into `JSONField` data.

It's kind of hard to draw the line as to what should actually be backported since the issue has been around for a while in `OrderableAggMixin`, `ExpressionWrapper` and `FieldGetDbPrepValueIterableMixin` but only happen to break a reported use case in 3.1 due to a change in behavior in a private API that is the only way to work around an ORM limitation.

**Comment by felixxm** [comment]
> Should we include the ExpressionWrapper and FieldGetDbPrepValueIterableMixin cases in this PR as well?

Yes I would like to fix them. I'm going to audit remaining `expression.as_sql()`s tomorrow.

**Comment by felixxm** [comment]
I fixed the second issue with `__in` lookup, it was tricky because we have here two regressions in 6789ded0a6ab797f0dcdfa6ad5d1cfa46e23abcd and 1251772cb83aa4106f526fe00738e51c0eb59122.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
I fixed an issue with `ExpressionWrapper`.

**Comment by felixxm** [comment]
Window expressions are not affected because `partition_by` is wrapped with `ExpressionList`. I added extra tests.

**Comment by felixxm** [comment]
I fixed the last issue with `ExclusionConstraint`. It's ready for review.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Review by charettes — APPROVED** [review]
Thanks for all the adjustments @felixxm, patch LGTM.

**Review by carltongibson — APPROVED** [review]
Super. Thanks @felixxm (and @charettes for the links on the ticket, which allowed me to follow-along 😀) — Good stuff!

**Pull request merged**
