### PR TITLE
Fixed #27571 -- Conditionally add TEST_DATABASE_PREFIX to db name

### PR DESCRIPTION
**Pull request by alexander-alvarez**
https://code.djangoproject.com/ticket/27571

### CODE REVIEW

**Comment by timgraham** [comment]
Hi, is there a Trac ticket that explains the issue? It's required for all non-trivial (typo) fixes such as this. Thanks.

**Comment by alexander-alvarez** [comment]
just made one: https://code.djangoproject.com/ticket/27571

**Comment by timgraham** [comment]
Please take a look at my reply on the ticket.

**Comment by timgraham** [comment]
Closing per ticket.

**Pull request closed without merging**
