### PR TITLE
Fixed #26024 -- Fixed regression in ConditionalGetMiddleware ETag support.

### PR DESCRIPTION
**Pull request by samifahed**

### CODE REVIEW

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
Did you check if there's a reason that the quote stripping can't happen in `get_conditional_response()`?

**Comment by samifahed** [comment]
@timgraham there are 2 other places where `get_conditional_response()`:
* `CommonMiddleware` which is stripping the quotes
* `django.views.decorators.http.condition` decorator for which you give a callable that computes the etag/last modified and uses them in the `get_conditional_response()`, I'm not sure if we should actually strip the quotes here.

**Comment by timgraham** [comment]
@syphar, as the author of the patch that caused the regression (7a40fef17ab7918cbb1ddc3ba080f42b420f7a48), do you have any advice?

**Comment by syphar** [comment]
@timgraham @samifahed I looked into it. 
IMHO: 

- etag-unquoting stripping has to stay separate from `get_conditional_response` because the [@condition](https://github.com/syphar/django/blob/98839e906632dfe77c6f6906d61d62868a0541dc/django/views/decorators/http.py#L88) decorator uses the result of the callable to get the etag. Only alternative would be to let the decorator do `quote_etag` and then later on `unquote_etag` in `get_conditional_response` later on ... 
- I agree it's a little unclean, since unquoting the etag from the `If-None-Match` header happens in `parse_etags` which is called inside of `get_conditional_response`. 

- what both fixes forget is that [`quote_etag`](https://github.com/syphar/django/blob/a0c75b49511ac9eab391bda5afa8a2455e2e5817/django/utils/http.py#L249-L249) does more than adding quotes. This has to be properly reverted too. 

My approach would be something like this here: 
https://github.com/django/django/compare/master...syphar:fix_etag

**Comment by samifahed** [comment]
I agree with @syphar's approach, what do you think @timgraham?

**Comment by samifahed** [comment]
@timgraham I updated the PR with @syphar's commit, I think it makes more sense. I'll be glad to fix it if there is anything missing in it

**Comment by timgraham** [comment]
How about some unit tests for the `unquote_etag()` function?

**Comment by syphar** [comment]
@timgraham https://github.com/django/django/pull/5919/files#diff-01a1ff7510f29ab8ea151390573f5736R164

**Comment by syphar** [comment]
I could provide more if needed :)

**Comment by timgraham** [comment]
As long as it fails if any part of `etag.strip('"').replace('\\"', '"').replace('\\\\', '\\')` are removed, it should be sufficient. Sorry for my blindness. :-)

**Comment by timgraham** [comment]
merged in 186b6c61bfe85afa4d6bf213d04a28dd2853fed2, thanks!

**Pull request closed without merging**
