### PR TITLE
Fixed #24020 -- Refactored SQL compiler to use expressions & refactored select_related() implementation

### PR DESCRIPTION
**Pull request by akaariai**
This pull requests does two important changes to the ORM:
  1) The ORM uses internally expressions. SELECT clauses are expressions, ORDER BY clauses are expressions and so on. The conversion to expressions is currently done in the compiler to keep the scope of the
patch somewhat manageable.
  2) The way select_related() queries are implemented is refactored. The compiler sets up the query, and the QuerySet iterator() uses the data generated by the compiler. Previously both the compiler and the iterator calculated the select columns which resulted in a bad DRY violation. The new way is 30% faster on djangobench query_select_related tests.
  3) Queries now have context variable. In essence this is a store for custom per-query variables. The context is currently used only internally, but exposing it in the QuerySet API could be a good addition. Things like choosing the time zone, SRID for gis or active language could be implemented using context.
  4) Database converters now work on expressions instead of internal_type. It is of course possible to get the internal type from expression.output_field.get_internal_type(). In addition converters now have access to context.

Tests pass on SQLite and PostgreSQL. There are still some failures on MySQL. Tests likely fail on Oracle, but I haven't tested this yet.

### CODE REVIEW

**Comment by jarshwah** [comment]
https://gist.github.com/jarshwah/35adcc1916216aecfd38

The fix you put in to check for klass_info == None was correct. It was lucky it wasn't triggered on other backends. The patch.diff notes above highlight why - the fast path was being taken after setting the query up where on oracle it wasn't.

There's a much bigger problem with Oracle though. You're now ignoring the `with_col_aliases=True`, which means the "col AS Col5" aliases are no longer being created. I tried for a few hours to get it to work but came up really short. Making the `Col` type apply its own alias breaks GROUP BY. Trying to apply an alias like it was before pollutes so many methods with `with_col_aliases` argument. See the "fix-attempt.patch" in the gist above.

I'll try and take another look tomorrow to see if I can come at it from a different angle. It's just really hard to know when an alias is required when columns for each join are being generated in different parts of the code, with no way that I can find to communicate the "seen" columns.

**Comment by akaariai** [comment]
The select list generated by get_select contains generated aliases. Maybe it is possible to fill missing aliases directly in as_sql?

**Comment by akaariai** [comment]
I've fixed a couple of review notes above, and also fixed a couple of other minor issues I found while skimming the patch.

I think the patch should now be ready for review, and hopefully ready for commit before 1.8 alpha freeze.

**Comment by timgraham** [comment]
Oracle failures: http://dpaste.com/1SQAPJN
Queries for second test: http://dpaste.com/2R52XET

**Comment by timgraham** [comment]
Here are my cosmetic suggestions: http://dpaste.com/1P3EWJY
It would take me hours to fully understand everything that's going on, but at a high level the comments you have written seem very helpful.

**Comment by timgraham** [comment]
buildbot, retest this please.

**Comment by timgraham** [comment]
buildbot, retest this please.

**Comment by timgraham** [comment]
merged in 0c7633178fa9410f102e4708cef979b873bccb76.

**Comment by akaariai** [comment]
Huge thank you to all of you who participated in getting this committed!

**Pull request closed without merging**
