### PR TITLE
Refctored and deprecated total unique constraints

### PR DESCRIPTION
**Pull request by ShmuelTreiger**
`total_unique_constraints` implies to me that it will return a number. Instead, I renamed it `list_unique_constraints` as it returns a list of the constraints. Could also rename it `all_unique_constraints`, but I found `list` to be more descriptive.

### CODE REVIEW

**Comment by felixxm** [comment]
Thanks for this patch :+1: however "total" means that it impacts all rows, as opposed to partial constraints. It's not confusing to me and the proposed name is not correct.

**Comment by ShmuelTreiger** [comment]
While "total" may mean that to you--someone who is heavily involved in Django development--it does not mean that to the average person. I would encourage you to find a more descriptive title which adequately conveys your intentions.

**Comment by ShmuelTreiger** [comment]
If you're insistent on keeping "total" in the name, `list_total_unique_constraints` would also be better, as it additionally informs me that I'm getting a list.

**Comment by felixxm** [comment]
This is a private API, and keeping the word `total` in its name is crucial for readability, because it doesn't return partial constraints. IMO it's not worth changing.

**Comment by ShmuelTreiger** [comment]
Ultimately, your project. Thanks for the work you do!

**Pull request closed without merging**
