### PR TITLE
Fixed #25594 -- Propagated validators from model to form fields

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by auvipy** [comment]
hi did you forget about this PR?

**Comment by claudep** [comment]
I'll revisit the PR once someone confirms the approach taken in the PR is viable.

**Comment by LuRsT** [comment]
@claudep, seems like nobody has confirmed, would you like to poke people to check this PR?

**Comment by auvipy** [comment]
> @claudep, seems like nobody has confirmed, would you like to poke people to check this PR?

maybe @felixxm is the person

**Comment by wagnerluis1982** [comment]
Is this PR still relevant to remain open?

**Comment by nessita** [comment]
I'm doing some PR housekeeping. I'll be closing this since I believe that the diff is too outdated to review it properly.

@claudep If you still would like to have this reviewed, could you please rebase onto main and ping for me to re-open? It would also help if you could add a small description about the goal of the changes. Thanks!

**Pull request closed without merging**
