### PR TITLE
Fixed #25093 -- Added __len__ attribute to utils.datastructures.OrderedSet

### PR DESCRIPTION
**Pull request by darkryder**
Are test cases needed?

### CODE REVIEW

**Comment by charettes** [comment]
Could you also add a test for this in `test_datastructures`?

**Comment by timgraham** [comment]
LGTM

**Comment by darkryder** [comment]
Rebased.

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
merged in f675afa13ce89ea25a9798b2f7a57b091bb83dfa, thanks!

**Pull request closed without merging**
