### PR TITLE
Fixes #392 -- Enable Sphinx extension and update source links

### PR DESCRIPTION
**Pull request by zachborboa**
https://github.com/django/djangoproject.com/issues/392

### CODE REVIEW

**Comment by pauloxnet** [comment]
It can be interesting to investigate if we can add a test in this PR and also to have an idea of what we'll see in the documentation.

**Review by camilonova — APPROVED** [review]

**Comment by zachborboa** [comment]
> It can be interesting to investigate if we can add a test in this PR and also to have an idea of what we'll see in the documentation.

Tests have been added

**Comment by pauloxnet** [comment]
> > It can be interesting to investigate if we can add a test in this PR and also to have an idea of what we'll see in the documentation.
> 
> Tests have been added

Thanks. Can you provide also a screenshot of how it looks ?

**Comment by zachborboa** [comment]
> Thanks. Can you provide also a screenshot of how it looks ?

screenshot:
image

**Comment by zachborboa** [comment]
Ready for review. Thank you

**Comment by smithdc1** [comment]
This ticket on trac seems related to this PR. https://code.djangoproject.com/ticket/29942

**Comment by zachborboa** [comment]
> This ticket on trac seems related to this PR. https://code.djangoproject.com/ticket/29942

Agreeing with the ticket. Quite a lot more of the helpful `[source]` links could be added to the docs when the import failures get fixed.

The errors are currently being silently ignored, but can be unhidden when generating the docs by increasing verbosity:
```bash
$ cd django/docs/
$ export SPHINXOPTS="-v"
$ run make html
```

The solution is to probably install the required modules in the environment where the docs are generated. This would fix errors like missing the `psycopg2` module for postgres so that source links to modules like `django.contrib.postgres.aggregates.BitAnd` are added to sections missing them like https://docs.djangoproject.com/en/dev/ref/contrib/postgres/aggregates/#bitand.

**Review by pauloxnet — APPROVED** [review]

**Pull request closed without merging**
