### PR TITLE
Fix for Persian locale params

### PR DESCRIPTION
**Pull request by remohammadi**
Reference: http://lh.2xlibre.net/locale/fa_IR/

### CODE REVIEW

**Comment by timgraham** [comment]
Do you have a colleague who can +1 these changes?

**Comment by maziaramini** [comment]
+1

**Comment by mousavian** [comment]
+1  for this changes.

**Comment by mostafah** [comment]
Are the numbers going to be localized with Persian digits too? If so, decimal and thousand separators should be proper Persian characters. But if that’s not the case, then these are correct values for an English number in Iranian locale and I can bless this PR with a :+1:!

**Comment by hamidfzm** [comment]
+1 for these changes.

**Comment by emojahedi** [comment]
+1

**Comment by remohammadi** [comment]
@mostafah Unfortunately the current code doesn't provide localized digits. I'm thinking to work on it by patching `django.utils.formats`. Glibc has placed "alternate digits" in Dates section, and it has place for dual digit alternatives. Are you aware of any language which has a different symbol for `10*X + Y` in place of `XY`?

**Comment by mostafah** [comment]
@remohammadi That would be awesome. This may be a little off-topic here, but since you asked, it never occurred to me that any language should have such modification to the Arabic numeral system (our familiar ten-digit number system). I took a quick look around [CLDR](http://cldr.unicode.org/index) (specially [this chart](http://www.unicode.org/cldr/charts/26/by_type/numbers.number_formatting_patterns.html) that shows number formatting variations) and didn’t see such a thing. But there mush be some reason for glibc to have dual-digit alternatives.

**Comment by timgraham** [comment]
merged in f1ff9407c94c4574d100efc3d224c1f79e2fb53d, thanks.

**Comment by ahmadpanah** [comment]
+1

**Comment by babaei** [comment]
+1

**Comment by timgraham** [comment]
Thanks all, this has been merged. No more +1s needed. :-)

**Pull request closed without merging**
