### PR TITLE
Fixed #31495 - Corrected note about admin i18n in tutorial.

### PR DESCRIPTION
**Pull request by ovkulkarni**
ticket-31495

### CODE REVIEW

**Comment by adamchainz** [comment]
Please retitle your PR in accordance with the guidelines: "Fixed #31495 -- Removed incorrect localization guidance from tutorial."

**Comment by carltongibson** [comment]
Like maybe: 

```
Since :doc:`translation </topics/i18n/translation>` is turned on by default, if
you have set :setting:`LANGUAGE_CODE`, the login screen will be displayed in
your own language.
```

(Separately, is there a case for LocaleMiddleware to be activated by default?)

**Comment by adamchainz** [comment]
LGTM. Small suggestions:
* "if you have set" -> "if you set" - readers are unlikely to have changed it by this point
* "your language" -> "the given language"  - people can identify as "having" more than one language
* Parenthetical about this being conditional on Django having translations

```
Since :doc:`translation </topics/i18n/translation>` is turned on by default, if
you set :setting:`LANGUAGE_CODE`, the login screen will be displayed in the
given language (if Django has appropriate translations).
```

**Comment by claudep** [comment]
+1 for Adam suggestion.

**Comment by carltongibson** [comment]
CI failure is unrelated.

**Pull request merged**
