### PR TITLE
Corrected used JS libraries in GIS widget docs.

### PR DESCRIPTION
**Pull request by felixxm**
Follow up to 1833eb3f3e3bda5052637f1a51a27fa1b11b6871.

### CODE REVIEW

**Review by carltongibson — APPROVED** [review]
Great. Thanks.

**Review by hramezani — APPROVED** [review]
LGTM :+1:

**Review by claudep — APPROVED** [review]
Sure, and sorry for this missed update of my part.

**Review by ngnpope — APPROVED** [review]

**Comment by felixxm** [comment]
Thanks y'all :star2:

**Pull request merged**
