### PR TITLE
Improved variable names in QuerySet.delete().

### PR DESCRIPTION
**Pull request by expert-m**
The doc says:

```
The delete method, conveniently, is named [delete()](https://docs.djangoproject.com/en/4.0/ref/models/instances/#django.db.models.Model.delete). This method immediately deletes the object and returns the number of objects deleted and a dictionary with the number of deletions per object type. Example:

>>> e.delete()
(1, {'blog.Entry': 1})
```

And if we check `Collector.delete` we will see:
```python3
return sum(deleted_counter.values()), dict(deleted_counter)
```
 
But in `QuerySet.delete` I see:
```python3
deleted, _rows_count = collector.delete()

# Clear the result cache, in case this QuerySet gets reused.
self._result_cache = None
return deleted, _rows_count
```

So, we need to swap `_rows_count` and `deleted`. It won't change the logic, but will fix the code from misunderstanding.

### CODE REVIEW

**Comment by timgraham** [comment]
Thanks for raising this. I think this is intentional as is, but I agree the names aren't very good. How about `num_deleted, num_deleted_per_model`?

**Comment by expert-m** [comment]
> Thanks for raising this. I think this is intentional as is, but I agree the names aren't very good. How about `num_deleted, num_deleted_per_model`?

Thank you for checking. I have updated the names.

**Comment by timgraham** [comment]
@felixxm please take a look.

**Comment by felixxm** [comment]
@expert-m Thanks for this patch :+1: Welcome aboard :boat:  

> @felixxm please take a look.

Looks good, thanks :+1:

**Pull request merged**
