### PR TITLE
Fixed #21936 -- Refactored DeleteView to be compatibale with SuccessMessageMixin

### PR DESCRIPTION
**Pull request by auvipy**
docs and release notes remain

### CODE REVIEW

**Comment by auvipy** [comment]
@timgraham needs your kind review and after fixing from review how would I squash all commits in a single commit?

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
Can you get the tests passing?

**Comment by timgraham** [comment]
Closing due to inactivity.

**Comment by lskillen** [comment]
@auvipy @timgraham 

I realise this has been closed due to inactivity, but should it pick up again it's got a :+1: from me (as a Django user).  We've seen the effect of not having this in several places and although it is easy to workaround it would be nice for the functionality to be innate.  Cheers!

**Comment by auvipy** [comment]
@lskillen yeah!!! but sorry I couldnt manage time to complete the pr! but will resend again!

**Comment by auvipy** [comment]
running messages_tests gives the follwing error

File "/usr/lib/python3.4/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'unittest.loader.ModuleImportFailure'>: attribute lookup ModuleImportFailure on unittest.loader failed

**Comment by auvipy** [comment]
and generic_views tests give following

File "/home/asif/dj/tests/generic_views/test_edit.py", line 432, in test_delete_with_form_as_post
    self.assertRedirects(res, 'http://testserver/list/authors/')
  File "/home/asif/dj/django/test/testcases.py", line 315, in assertRedirects
    RemovedInDjango20Warning, stacklevel=2)
django.utils.deprecation.RemovedInDjango20Warning: assertRedirects had to strip the scheme and domain from the expected URL, as it was always added automatically to URLs before Django 1.9. Please update your expected URLs by removing the scheme and domain.

----------------------------------------------------------------------
Ran 203 tests in 3.821s

FAILED (errors=1)

**Comment by bittner** [comment]
@auvipy Please pick this up again. Would be good to have this implemented.

**Comment by auvipy** [comment]
@bittner yes I am reopening it again within 2-3 days :)

**Comment by brianmay** [comment]
Status report?

**Comment by auvipy** [comment]
https://github.com/django/django/pull/8138 this was the last update. you could give some feed back or take over if interested

**Pull request closed without merging**
