### PR TITLE
pass object to user.has_perm inside of admin permission checks

### PR DESCRIPTION
**Pull request by ryanpineo**

### CODE REVIEW

**Comment by timgraham** [comment]
Thanks for the patch, however, a ticket that describes the problem as well as tests are needed. I think the proposal will break things as described in https://code.djangoproject.com/ticket/13539.

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by ryanpineo** [comment]
Hi Tim, thanks for the quick response.  It seems like this is actually a lot bigger problem than I originally thought.  I'll see if I can try implementing any of the ideas on the ticket.

**Comment by timgraham** [comment]
Okay, I'll close this for now.

**Pull request closed without merging**
