### PR TITLE
Refs #28066 -- Fixed nondeterministic ordering test failure in sessions_tests.

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Comment by timgraham** [comment]
I wonder why the previous test doesn't have that issue (or if it might).

**Comment by felixxm** [comment]
In the previous version we didn't check `session` elements ([tests/sessions_tests/tests.py](https://github.com/django/django/pull/8353/files#diff-cbc3b4686f1040ae6e926c69d7151261R187)), moreover it was empty.

**Comment by timgraham** [comment]
Sorry, I meant the `test_cycle` test right above the one you changed.

**Comment by felixxm** [comment]
I think that it is not a issue for the `test_cycle`, because it doesn't reload session data.

**Pull request merged**
