### PR TITLE
Fixed running TransactionsPerRequestTests in isolation.

### PR DESCRIPTION
**Pull request by jdufresne**

### CODE REVIEW

**Comment by jdufresne** [comment]
If it is instead preferable to add `django.contrib.auth` to `available_apps`, I can make that change instead. Let me know.

**Comment by charettes** [comment]
@jdufresne it would seem wrong to me to reference `'django.contrib.auth'` into a test for a core feature.

**Comment by timgraham** [comment]
Did you run into this in any particular way? 11856ea44e4dd1ff2358c559c0d04ac848832c23 is the same issue -- I wonder if it's going to pop up again and again. It started happening after cb7bbf97a74fa7800865e3615f196ad65dc4f281. I wonder if moving backend to inner imports in `django/contrib/auth/backends.py` would be a better solution.

**Comment by jdufresne** [comment]
> Did you run into this in any particular way?

I was investigating a different issue. My changes had created a test failure in this class. So to iterate quickly, I started testing against this class only. That is when I noticed it didn't pass on the master branch in isolation. It fails because the auth middleware is loaded, but not the auth app & models. Seemed like a straight forward fixed, so I created the PR.

**Comment by jdufresne** [comment]
If there is a deeper, more fundamental fix in the works, I will withdraw this PR in preference to that.

**Comment by timgraham** [comment]
I don't have anything in mind besides reverting the change that caused the problem:
```diff
diff --git a/django/contrib/auth/backends.py b/django/contrib/auth/backends.py
index 64f9af3..0b51502 100644
--- a/django/contrib/auth/backends.py
+++ b/django/contrib/auth/backends.py
@@ -1,8 +1,6 @@
 from django.contrib.auth import get_user_model
 from django.contrib.auth.models import Permission
 
-UserModel = get_user_model()
-
 
 class ModelBackend:
     """
@@ -10,6 +8,7 @@ class ModelBackend:
     """
 
     def authenticate(self, request, username=None, password=None, **kwargs):
+        UserModel = get_user_model()
         if username is None:
             username = kwargs.get(UserModel.USERNAME_FIELD)
         try:
@@ -96,6 +95,7 @@ class ModelBackend:
         return False
 
     def get_user(self, user_id):
+        UserModel = get_user_model()
         try:
             user = UserModel._default_manager.get(pk=user_id)
         except UserModel.DoesNotExist:
@@ -137,6 +137,8 @@ class RemoteUserBackend(ModelBackend):
         user = None
         username = self.clean_username(remote_user)
 
+        UserModel = get_user_model()
+
         # Note that this could be accomplished in one try-except clause, but
         # instead we use get_or_create when creating unknown users since it has
         # built-in safeguards for multiple threads.
```
Not that it might not break again in the future for some reason. The fundamental problem is `ALWAYS_MIDDLEWARE` in `runtests.py` includes contrib middleware. I'm not sure if it's practical to change that though.

**Comment by jdufresne** [comment]
I can confirm that your patch does allow running the test in isolation. I don't mind including it in the fix. Do you think it still makes sense to override the middleware setting to `[]` as a signal of intent? Or would you consider that unwanted noise?

**Comment by timgraham** [comment]
I think if we accept the need to put `MIDDLEWARE=[]` in tests, then there's no point in my patch considering that we won't be able to detect the need for `MIDDLEWARE=[]` if it's there. We might audit all `available_apps` usage and `INSTALLED_APPS` overriding and see if this fix is needed elsewhere. This could be quite tedious.

**Comment by jdufresne** [comment]
I wrote the following script to run all Django tests in isolation. As expected, this found `TransactionsPerRequestTests`, but it found no other tests that fail in isolation. So, AFAICT, this is the only test that needs modification to run in isolation. The script only ran against SQLite due to the time consuming nature of setup & destroy of the database for every test with other backends.

```
import ast
import os
import subprocess

pwd = os.getcwd() + os.sep


def parse_run(path):
    rel_path = path[len(pwd):]
    python_path = '.'.join(rel_path[:-3].split('/'))

    class ClassVisitor(ast.NodeVisitor):
        def visit_ClassDef(self, node):
            if any(isinstance(n, ast.Name) and n.id.endswith('TestCase') for n in node.bases):
                path = '%s.%s' % (python_path, node.name)
                print('***** %s' % path)
                subprocess.check_call(['python', 'runtests.py', '--noinput', path])

    visitor = ClassVisitor()

    with open(path) as fp:
        tree = ast.parse(fp.read(), path)
    visitor.visit(tree)


for dirpath, dirnames, filenames in os.walk(pwd):
    for fn in filenames:
        if fn.startswith('test') and fn.endswith('.py'):
            parse_run(os.path.join(dirpath, fn))
```

**Comment by timgraham** [comment]
Thanks for investigating. As a separate task, it could be useful to incorporate an option in `runtests.py` to run tests in isolation.

**Pull request merged**
