### PR TITLE
Refs #29799 -- Draft for per-field-instance lookup registration/unregistration.

### PR DESCRIPTION
**Pull request by Himanshu-Balasamanta**
@carltongibson @charettes Opening this draft PR to seek guidance if this approach to solving [#29799](https://code.djangoproject.com/ticket/29799) is correct. 
The code is written just to enable instances of a Field to be disabled for certain lookups where the number of lookups and targets are both only one.
Based on reviews shall make changes and implement other cases.

### CODE REVIEW

**Comment by charettes** [comment]
Hello @Himanshu-Balasamanta!

You might be interested in https://github.com/django/django/pull/11408 and https://github.com/charettes/django/commit/ccc58bf2eb43722e894ca8e451cab7db1b83af43 which are bit more complete feature wise and include tests. There might be chunks of work that can be reused.

**Comment by carltongibson** [comment]
Hey @Himanshu-Balasamanta — just the quickest glance here... 

You can address the linting errors etc.

Then **more significant** start thinking about the documentation changes for this — look through the custom lookup docs and think where we'd need changes to explain unregistration at the class level, and the per-instance equivalents. 

Thinking through the docs is often helpful to settle the behaviour questions. ("It's better if we do it this way because that feels more natural to use") 

Hopefully you should have lots to go on. Happy to discuss here: remember that you don't need perfect code for the proposal, but (rather) a proposal that shows you've considered the project and have a reasonable plan. Make sense?

**Comment by Himanshu-Balasamanta** [comment]
Hi @carltongibson . Yes I agree. I also agree that thinking about the documentation changes is a good starting point.
This PR has a lot of unnecessary code, which I shall clean and then fix the linting errors.

**Comment by Himanshu-Balasamanta** [comment]
Changes made:
-  get_lookups() now returns instance_lookups as well as class_lookups when called by an instance and only class_lookups when called by a class
- _clear_cached_lookups() can now be called by ForeignKey class. (Earlier `get_lookups.cache_clear()` had to be used, see [custom_lookups.tests.LookupTests.test_lookups_caching](https://github.com/django/django/blob/main/tests/custom_lookups/tests.py#L319) .)

PS : 
- registration and unregistration of lookups for instances is not yet implemented, so output of none of the test cases changed.
- Making _clear_cached_lookups() work for ForeignKey actually is worth a ticket of it's own. The solution I implemented here is a temporary one, [correct solution](https://stackoverflow.com/questions/2877110/python-new-style-classes-and-subclasses-function) shall be implemented in a separate PR in due course of time.

**Comment by Himanshu-Balasamanta** [comment]
Hi @carltongibson , I fixed the linting errors by running `pre-commit run --all-files` . I think it should pass the linting tests also now.

This PR is only the implementation of RegisterLookupMixin.get_lookups() and RegisterLookupMixin.get_lookup() API.

Opened it to get some feedback.

**Comment by felixxm** [comment]
Closing in favor of #15787.

**Pull request closed without merging**
