### PR TITLE
feat: URLValidator Error Cause

### PR DESCRIPTION
**Pull request by dopry**
The URLValidator lets you know there is something wrong with the URL, but not why it is wrong.  This commit adds a cause to the errors and more detail to the error message.

### CODE REVIEW

**Comment by DevilsAutumn** [comment]
Hi @dopry , thanks for this patch. however, all features require [an accepted ticket](https://code.djangoproject.com/newticket).

**Comment by nessita** [comment]
Hello @dopry! Thank you for your first contribution. As @DevilsAutumn mentioned, non trivial changes like this would need an accepted ticket and also a higher level consideration to evaluate whether a change like this is desirable in other validators.
For more details about contributing to Django, please see [the documented guidelines for requesting features](https://docs.djangoproject.com/en/stable/internals/contributing/bugs-and-features/#requesting-features).

**Comment by charettes** [comment]
> I'm not requesting a feature. I'm adding one. What a wonderful way to discourage contributors.

@dopry I empathize with your sentiment but in order to ensure the project maintenance can be sustained we can't simply add features without proper consideration of concerns like backward compatibility and interactions with others features.

One simple feature added by a contributor can turn into what other users might consider a bug hence the Django developers community has agreed on a process that requires that any new feature request be [at the very least discussed on ticket tracker before being considered for inclusion](https://docs.djangoproject.com/en/5.0/internals/contributing/writing-code/submitting-patches/#non-trivial-patches).

This very process you find bureaucratic is likely what has allowed Django to remain relevant for so long, for you try it out, and possibly made you care enough about it to take a few minutes of your time to submit this PR.

**Comment by dopry** [comment]
@charettes I didn't say just merge it and not discuss it. I was told my pr was closed because I did it wrong and that my effort was unacceptable because I didn't ask permission first. At least that is what I got out of it... 

What if instead of just closing the PR someone directed people from that forum to the PR for discussion, or said something like.. Hey this looks great, if you want to get the communities attention post your PR on this forum for discussion. 

I understand architectural and quality control processes need to be in place. The approach to enforcement is what discourages contributors.

**Comment by dopry** [comment]
@charettes @nessita @DevilsAutumn 

In addition 
* none of the documentation linked by the github actions bot says anything about requiring a ticket. 
* none of the comments align with the guidelines in the linked patch review checklist. 

I read the requesting features and it says

> As with most open-source projects, code talks. If you are willing to write the code for the feature yourself or, even better, if you’ve already written it, it’s much more likely to be accepted. Fork Django on GitHub, create a feature branch, and show us your work!

I followed the documented guidelines and my PR was closed for arbitrary undocumented reasons or a clear explanation of how to move forward. The discussion i was promised for showing my work never happened.

**Comment by nessita** [comment]
> @charettes I didn't say just merge it and not discuss it. I was told my pr was closed because I did it wrong and that my effort was unacceptable because I didn't ask permission first. At least that is what I got out of it...

Hey @dopry, I understand that you may feel frustrated, but I think this sentence is an overstatement. The intention behind closing your pull request was to ensure alignment with project standards, rather than dismissing your effort. See below for more details about this.

> What if instead of just closing the PR someone directed people from that forum to the PR for discussion, or said something like.. Hey this looks great, if you want to get the communities attention post your PR on this forum for discussion.

Perhaps the message I posted before closing this PR was missed:

*Hello @dopry! Thank you for your first contribution. As @DevilsAutumn mentioned, non trivial changes like this would need an accepted ticket and also a higher level consideration to evaluate whether a change like this is desirable in other validators.
For more details about contributing to Django, please see [the documented guidelines for requesting features](https://docs.djangoproject.com/en/stable/internals/contributing/bugs-and-features/#requesting-features).*

We never close PRs without an explanation, and in fact in this case:
1. we acknowledged and thanked your contribution,
2. we provided an explanation of why we closed it, and
3. we shared a link that explains how to get the community attention for discussion.

Regarding:
> none of the documentation linked by the github actions bot says anything about requiring a ticket.

I don't think this is accurate. There is certainly room for improvement but the link from the "first contributor" bot message points to https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/submitting-patches/ which says:

*[...] If you have identified a contribution you want to make and you’re capable of fixing it (as measured by your coding ability, knowledge of Django internals and time availability), claim it by following these steps: [...] If a ticket for this issue doesn’t exist yet, create one in our [ticket tracker](https://code.djangoproject.com/).*

Also in the [Non-trivial patches section](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/submitting-patches/#non-trivial-patches) of the same page it says:

*A “non-trivial” patch is one that is more than a small bug fix. It’s a patch that introduces Django functionality and makes some sort of design decision.
If you provide a non-trivial patch, include evidence that alternatives have been discussed on the [Django Forum](https://forum.djangoproject.com/) or [django-developers](https://docs.djangoproject.com/en/dev/internals/mailing-lists/#django-developers-mailing-list) list.
If you’re not sure whether your patch should be considered non-trivial, ask on the ticket for opinions.*

Lastly, you do have a valid point that the sentence you quoted is misleading, so I have created ticket-35546 to make the docs less ambiguous. Thank you for taking the time to reply! Please do not forget to always abide to the [Django Code of Conduct](https://www.djangoproject.com/conduct/) when commenting.

**Comment by dopry** [comment]
@nessita  regardless it was off putting and dismissive from my perspective, and I'm sure I'm not the only potential contributor who ends up feeling that way. Most of them probably don't speak up.  It may be worthwhile for the Django community to think about that if it wants to stay relevant in the long term. In the mean time, I won't waste my time trying to contribute to Django.

**Pull request closed without merging**
