### PR TITLE
Fixed #24424 -- Fixed SQLite migrations crash when removing the last column of a table.

### PR DESCRIPTION
**Pull request by oxplot**
In case the migration has removed all fields but before dropping the
table (in case some other one-to-one relationship is still referencing
it).

An example is a migration that removes the last foreign key field of a model that is referenced by the model whose foreign key is being removed (e.g. one-to-one relationship).

After removing the last field, doing the copy generates an invalid INSERT such as this:

```sql
INSERT INTO "app_model__new" () SELECT  FROM "app_model" 
```

Another example is simply renaming a custom PK which the regression test in this PR covers.

### CODE REVIEW

**Comment by timgraham** [comment]
This patch is mostly the same as https://github.com/django/django/pull/4325.

@MarkusH, are you still against this approach?

**Comment by MarkusH** [comment]
buildbot, ok to test.

**Comment by MarkusH** [comment]
@timgraham Since this test doesn't exclude any backends I'm ok with it.

**Comment by oxplot** [comment]
@timgraham I [agree](https://code.djangoproject.com/ticket/24424#comment:31) with @MarkusH 's [earlier comment](https://code.djangoproject.com/ticket/24424#comment:11) on this issue. But it's been quite a while and nothing is done so this fix seems to be something to move things along.

**Comment by MarkusH** [comment]
Sadly what I expected: tests are still failing on MySQL. If you have an idea how to fix that I'm all in.

**Comment by oxplot** [comment]
@MarkusH Like I [suggested in the bug](https://code.djangoproject.com/ticket/24424#comment:31), we can add a temp column if the op is a delete and it's of the the last column. This is always an intermediate op after which another column is added (I'm not sure of this, but I'm guessing).

**Comment by timgraham** [comment]
How about shipping this change to fix the bug on SQLite while skipping the test on MySQL. We could treat that as a separate issue and revert the SQLite change when fixing it properly. Any downside Markus?

**Comment by MarkusH** [comment]
I think it's a fundamental flaw in Django's migration framework that we should fix instead. Currently there's not way to replace (not alter) a primary key column from what I can tell. Hence my reservation on this patch. It's a band-aid for a way more complicated problem I've yet to figure out how to express (hence no ticket)

**Comment by timgraham** [comment]
Okay, I guess we'll close this then.

**Pull request closed without merging**
