### PR TITLE
Fixed #30966 -- Fixed Migration crashes due to foreign key issue, depending on otherwise irrelevant order.

### PR DESCRIPTION
**Pull request by hramezani**
Description on [ticke comment](https://code.djangoproject.com/ticket/30966#comment:4).

### CODE REVIEW

**Comment by felixxm** [comment]
@hramezani This issue was fixed by #12665. Can we add a test that will assert model's state instead of checking that `migrate` doesn't crash? :thinking:

**Comment by hramezani** [comment]
> @hramezani This issue was fixed by #12665. Can we add a test that will assert model's state instead of checking that `migrate` doesn't crash?

I will work on it.

**Comment by hramezani** [comment]
> @hramezani This issue was fixed by #12665. Can we add a test that will assert model's state instead of checking that `migrate` doesn't crash?

@felixxm, I couldn't add a test to check the model's state which fails without #12665 based on @MarkusH [comment](https://code.djangoproject.com/ticket/30966#comment:16).

I rebased this patch so we could merge it.

**Comment by felixxm** [comment]
I added test based on Markus comment (see #12682).

**Comment by felixxm** [comment]
Closed in favor of #12682.

**Pull request closed without merging**
