### PR TITLE
Refs #32013 -- Added backward incompatibility note about ModelChoiceIterator changes.

### PR DESCRIPTION
**Pull request by felixxm**
ticket-32013

### CODE REVIEW

**Review by carltongibson — APPROVED** [review]
This is fine. 

In might be tempted to add a `In most cases this proxies transparently but, if you need..` but maybe that’s saying too much?

**Comment by jaap3** [comment]
In my opinion the additional note about transparently proxying comparisons (and str (others?)) would be welcome. If not here, then maybe on the docs for `ModelChoiceIteratorValue`? It would've helped me reason about the other `.choices` manipulating code I mentioned in ticket-32013.

**Comment by carltongibson** [comment]
@jaap3 Fancy suggesting a change to this https://docs.djangoproject.com/en/3.1/ref/forms/fields/#modelchoiceiteratorvalue ?

**Comment by felixxm** [comment]
Thanks both :rocket:

**Review by jdufresne — APPROVED** [review]
Thanks all for the report and doc clarification.

**Comment by jaap3** [comment]
Thanks everyone 👍

**Pull request merged**
