### PR TITLE
[1.11.x] Fixed #28487 -- Fixed force_bytes() decoding of non-unicode strings.

### PR DESCRIPTION
**Pull request by mrogaski**
No different than the patch from @jjkalucki, but I added an appropriate regression test.
https://code.djangoproject.com/ticket/28487

### CODE REVIEW

**Comment by timgraham** [comment]
My bytes/unicode understanding isn't good but it's not obvious to me how the new behavior matches the document behavior, "Return a bytestring version of 's', encoded as specified in 'encoding'." Could you explain? If this is a bug, it looks like a really old one (since c5ef65bc).

**Comment by claudep** [comment]
I would be strictly opposed to change the behavior of a heavily-used function like `force_bytes` in a released version. `encoding` is supposed to be the destination encoding, not the source one.

**Comment by mrogaski** [comment]
I have to admit, I had misinterpreted the documentation to mean that encoding was an input qualifier (so the usage of force_bytes in #28174 is problematic.  I also agree that changing behavior so fundamentally is a bad idea.  
I'm going to close this PR and figure out a better solution to #28174's use of force_bytes.  I will also submit a separate PR with unit tests for the current encoding behavior and a tweak to the documentation to specify encoding applies to input.

**Comment by timgraham** [comment]
The new PR is https://github.com/django/django/pull/8985.

**Pull request closed without merging**
