### PR TITLE
Added django.utils.functional.cached_classproperty

### PR DESCRIPTION
**Pull request by chessmaster04**
Added decorator cached_classproperty to django.utils.functional

### CODE REVIEW

**Comment by smithdc1** [comment]
Hi @chessmaster04 

A few initial comments from me

- I can't see a ticket on trac for this? This would be a new feature so would require a ticket.

https://code.djangoproject.com

- It would require docs and tests

- I'm not sure Django should include a small standalone class like this? What's the compelling case to include this in Django itself?

**Comment by felixxm** [comment]
@chessmaster04 Thanks for this patch, see Simon's [comment](https://code.djangoproject.com/ticket/30864#comment:2). Discussion on the [DevelopersMailingList](https://code.djangoproject.com/wiki/DevelopersMailingList) may also be required.

**Comment by chessmaster04** [comment]
> Hi @chessmaster04
> 
> A few initial comments from me
> 
> * I can't see a ticket on trac for this? This would be a new feature so would require a ticket.
> 
> https://code.djangoproject.com
> 
> * It would require docs and tests
> * I'm not sure Django should include a small standalone class like this? What's the compelling case to include this in Django itself?

Yes, It is a new feature.
Django has a lot of methods for caching, like cached_page and cached_property.
Сaching improves response times.
My task was as follows. I needed a class with static properties. And their values ​​were calculated. Therefore, I used the classproperty decorator and since the calculations did not change while the program was running, I needed to cache them. Django has only cached_property, but my properies must be classproperty, so I needed create cached_classproperty.
What do you think about it?
Do I need create discussion on the DevelopersMailingList?
Thanks!

**Comment by felixxm** [comment]
Closing per ticket.

**Pull request closed without merging**
