### PR TITLE
Fixed #29705 -- Fixed ImageField RuntimeError crash for WebP files.

### PR DESCRIPTION
**Pull request by winkidney**
Ref: https://code.djangoproject.com/ticket/29705

### CODE REVIEW

**Comment by claudep** [comment]
I think we need to wonder if that code to get image dimensions is still a gain (speed, memory) nowadays versus simply opening the image with pillow and getting the `size` attribute.
@hugovk might give us some hints about that question.

**Comment by hugovk** [comment]
You could try increasing the chunk size in case of `RunTimeError`.

With this code:
```python
from PIL import ImageFile as PillowImageFile

p = PillowImageFile.Parser()

file_or_path = "Tests/images/hopper.webp"

chunk_size = 1024

file = open(file_or_path, 'rb')

data = file.read(chunk_size)

p.feed(data)

print(p.image.size)
```
I got:
```
Traceback (most recent call last):
  File "webp.py", line 13, in <module>
    p.feed(data)
  File "/Users/hugo/github/Pillow/src/PIL/ImageFile.py", line 400, in feed
    im = Image.open(fp)
  File "/Users/hugo/github/Pillow/src/PIL/Image.py", line 2624, in open
    im = _open_core(fp, filename, prefix)
  File "/Users/hugo/github/Pillow/src/PIL/Image.py", line 2610, in _open_core
    im = factory(fp, filename)
  File "/Users/hugo/github/Pillow/src/PIL/ImageFile.py", line 102, in __init__
    self._open()
  File "/Users/hugo/github/Pillow/src/PIL/WebPImagePlugin.py", line 52, in _open
    self._decoder = _webp.WebPAnimDecoder(self.fp.read())
RuntimeError: could not create decoder object
```

And the same with:
```python
chunk_size = 1024 * 2
chunk_size = 1024 * 3
```

But with:
```python
chunk_size = 1024 * 4
```
I get:
```
(128, 128)
```

**Comment by winkidney** [comment]
@hugovk Awesome!
I have tried in your way, but the chunk size for me is larger than `1024 * 4`.

For a larger webp file, the chunk-size must be larger.

So I guess that PIL have to read all bytes of webp file to get meta data for that.

You may download another webp file and have a try.

Finally, I get the size for my file : `https://img3.doubanio.com/view/status/m/public/a606779b213ae14.webp`.

If we can't get the proper size at one time, fallback to Image.open() may be a better way for us.

we should avoid codes like this:

```

from PIL import ImageFile as PillowImageFile

p = PillowImageFile.Parser()

file_or_path = "Tests/images/hopper.webp"

chunk_size = 1024

file = open(file_or_path, 'rb')

while True:
     file.seek(0)
    try:
        data = file.read(chunk_size)
        p.feed(data)
        return
    except RuntimeError:
        chunk_size *= 2    # just example
        continue
```

**Comment by winkidney** [comment]
Ref: https://developers.google.com/speed/webp/docs/riff_container

**Comment by hugovk** [comment]
`get_image_dimensions` already has a `while 1:` loop that does `chunk_size *= 2` before re-looping.

Perhaps adding `except RuntimeError` in here might do it:
```python
except struct.error:
   ...
   pass
except RuntimeError:
   pass
```

**Comment by winkidney** [comment]
@hugovk Yes it works the same way but more simple and easier to unstandard.

But I think we have another problem to solve:

The `expect RuntimeError`  statment may be a endless-loop in case of the file is invalid

```
from PIL import ImageFile as PillowImageFile

    p = PillowImageFile.Parser()
    if hasattr(file_or_path, 'read'):
        file = file_or_path
        file_pos = file.tell()
        file.seek(0)
    else:
        file = open(file_or_path, 'rb')
        close = True
    try:
        chunk_size = 1024
        while 1:
            data = file.read(chunk_size)
            if not data:
                break
            try:
                p.feed(data)
            except zlib.error as e:
                if e.args[0].startswith("Error -5"):
                    pass
                else:
                    raise
            except struct.error:
                pass
            except RuntimeError:
                 # where the endless loop occurs if RuntimeError always occurs.
                pass
            if p.image:
                return p.image.size
            chunk_size *= 2
        return (None, None)
    finally:
        if close:
            file.close()
        else:
            file.seek(file_pos)
```

Another question: 

What if the struct.error occurs?

It seems that the `data` variable will not combine the old chunk and the new chunk together.

**Comment by winkidney** [comment]
I have made changes to detect if the chunk size is larger thant the file size but no easy way found.

While 
```python
if hasattr(file_or_path, 'read'):
        file = file_or_path
        file_pos = file.tell()
        file.seek(0)
    else:
        file = open(file_or_path, 'rb')
        close = True
    try:
        # Most of the time Pillow only needs a small chunk to parse the image
        # and get the dimensions, but with some TIFF files Pillow needs to
        # parse the whole file.
        chunk_size = 1024
        file_size = file.size
```
the error occurs:

```
AttributeError: '_io.BufferedReader' object has no attribute 'size'
```
So I think the current PR works better, any idea?

**Comment by winkidney** [comment]
I've made a new PR that following your advice.

I missed that the data is combined by p.feed, very sorry for that : )

Thanks for your help.

**Comment by winkidney** [comment]
@timgraham Hi Tim, I have an old project named "Pinry" which using django-1.8, is there any plan to apply this patch (cherry-pick ? ) to that version of django?

**Comment by timgraham** [comment]
No, see our [supported versions policy](https://docs.djangoproject.com/en/dev/internals/release-process/#supported-versions) and [Supported Versions](https://www.djangoproject.com/download/#supported-versions) table. Django 1.8 is completely unsupported (including no patches for security issues).

**Comment by winkidney** [comment]
@timgraham thanks a lot

**Comment by mixxorz** [comment]
Hi there. I've just encountered this issue while working on [kirigamico/wagtail-webp](https://github.com/kirigamico/wagtail-webp)

When do you think this will be included in a Django release? I tried to look for it in the patch releases but it doesn't seem to be there.

**Comment by timgraham** [comment]
It's on the master branch to be released as Django 2.2 in April.

**Pull request merged**
