### PR TITLE
Fixed #28835 -- Made development server shutdown on SIGTERM.

### PR DESCRIPTION
**Pull request by bkabrda**
Hi, I've run into an issue where shutting down django devserver in a container (e.g. in kubernetes/openshift environment) doesn't work well. The original report is at [1].

Explanation:
* kubernetes/openshift send SIGTERM to PID 1 in the container when shutting the container down.
* If `manage.py runserver` is an entrypoint, it gets executed as PID 1 in container.
* Linux kernel won't propagate SIGTERM to any process that is PID 1 (in or outside of container) if it doesn't have a handler installed for this signal.

The implication of this is that the container with django devserver will not do "soft" shutdown on SIGTERM and Kubernetes/Openshift will wait for timeout and kill the container with SIGKILL. Therefore the container will keep hanging and occupying system resources during the whole timeout.

Even though I understand that people should only use devserver for development and not for deployment, I think it's quite common to first make the container working with devserver for development and then consider Gunicorn or similar solution when moving from early stage of the project. IOW, I think this would really be beneficial for people using Kubernetes like environments to develop/deploy Django apps.

Thanks for considering!

[1] https://github.com/sclorg/s2i-python-container/issues/93

### CODE REVIEW

**Comment by timgraham** [comment]
Thanks for the contribution. A [Trac ticket](https://code.djangoproject.com/) and (if possible; perhaps using mocking) a test are required.

**Comment by bkabrda** [comment]
I opened a Trac ticket: https://code.djangoproject.com/ticket/28835
I'll add tests if and when it's acknowledged that this is indeed a Django issue and a patch will be accepted for it.

**Comment by bkabrda** [comment]
I amended the commit with a simple test, so it should be ready for review now. I needed to do some refactoring of the utility functions to be able to test this, but I believe I didn't break anything, so it should be fine.

**Comment by bkabrda** [comment]
Ok, so this seems to be failing on Windows... unfortunately I have no windows machine in my disposal and have very little knowledge of Windows internals. [1] seems to suggest that this is not (easily) possible on Windows. Would it make sense to make the test only work on non-Windows OSs?

[1] https://stackoverflow.com/a/1230853

**Comment by orf** [comment]
Isn't the recommendation to run something like `tiny-init` or `dumb-init` as pid 1 to take care of things like this? Is this still an issue if you do?

**Comment by bkabrda** [comment]
I'm not sure if this is a recommendation, I guess different best practice guides will recommend different things. Using a process manager makes this issue go away, but I consider that to be a workaround; this should work correctly without a process manager.

**Comment by orf** [comment]
Linux treats PID 1 as a special case and gives it special responsibilities, leading to these signal issues as well as issues with reaping zombie processes. Essentially manage.py would have to act as an init process.

It is certainly the recommendation if you run into any signal or zombie processes issue, and docker provides a `--init` flag for this. IMO it would be better to print a warning if python is running as pid 1 specifying that there might be issues.

That being said, it perhaps is a bit heavyweight for just experimenting.

**Comment by carltongibson** [comment]
Right. Good. A rabbit-hole. 🙂

My initial take on the patch itself is roughly positive: 

* Its a small change
* I don't see a problem with adding the signal handler
* So, if it helps..., well...

**Comment by carltongibson** [comment]
Given that this was initially _Accepted_, I've marked this as _Ready for checkin_, on the basis of the patch itself. This will invite another opinion on whether it's right for us (vs e.g. a _wontfix_). 

Thanks for the effort @bkabrda!

**Comment by timgraham** [comment]
The test fails if port 8000 is already in use (I discovered this when checking the patch locally and having another runserver instance running). This could be solved by binding to port zero (see 81cdcb66bc74a0768d13f0e18872d46739028e64).

My other thought is that perhaps this would be fixed for free if we switch the server that runserver wraps to gunicorn as discussed in [#21978](https://code.djangoproject.com/ticket/21978). If so, maybe we could spend time there instead.

**Comment by carltongibson** [comment]
Good catch @timgraham! (#21978 looks a good idea.) 

My take on this patch was that it was probably worth it because it was small. If we can resolve the port issue keeping it small that's great. Otherwise it might not be worth it. @bkabrda I've marked the ticket as Patch needs improvement. If you want to address this issue and uncheck that, we can have another look. (Otherwise let us know and we can close it off.) Ta!

**Comment by bkabrda** [comment]
Hi folks, sorry for the late reply. Having gunicorn as default when using runserver would certainly be great (and would render this PR unnecessary), since gunicorn handles this scenario well.

**Comment by carltongibson** [comment]
Hi @bkabrda. Integrating gunicorn may be _some time_ away. Did you want to try adopting Tim's suggestion on this patch in the meantime? (Or is the `--init` type work around enough for you for now?) Thanks!

**Comment by bkabrda** [comment]
@carltongibson if using gunicorn by default is on the roadmap, I'm absolutely fine with that even if it takes some time to get that implemented and released.

**Comment by carltongibson** [comment]
@bkabrda OK great. I shall close this one off. If you want to revisit at any time let us know. Thanks for the input!

**Comment by frenzymadness** [comment]
Is there any info/roadmap describing when gunicorn will be used as a default development server?

**Comment by orf** [comment]
Given the lack of Windows support for Gunicorn, this doesn't seem like it will happen very soon unfortunately.

**Pull request closed without merging**
