### PR TITLE
sqlsequencereset command refactoring

### PR DESCRIPTION
**Pull request by axil**
Draft implementation of the sqlsequencereset command refactoring as suggested by Simon Charette in ticket #31730 (https://code.djangoproject.com/ticket/31730). So far only for the postgres backend.

### CODE REVIEW

**Comment by felixxm** [comment]
@axii Do you have time to keep working on this?

**Comment by felixxm** [comment]
buildbot

**Comment by axil** [comment]
@felixxm Yes, I think I'll handle this by the end of the month.

**Comment by felixxm** [comment]
Closing due to inactivity.

**Pull request closed without merging**
