### PR TITLE
Fixed #28102 -- Add example for DIRS in TemplatesSetting

### PR DESCRIPTION
**Pull request by Windsooon**
Add example to put the full path for DIRS in TemplatesSetting

Ticket: https://code.djangoproject.com/ticket/28102

### CODE REVIEW

**Comment by timgraham** [comment]
This isn't correct, at least for the definition of `BASE_DIR` in the settings file generated by `startproject`. The built-in widget templates are located where Django is installed, not in the project.

**Comment by timgraham** [comment]
It would be better to include an actual code example rather than the `django_installed_path` psuedocode. For example, the path to the Django install is given by `import django; django.__path__`.

**Comment by Windsooon** [comment]
I wonder if better to put all the basic path example code in a particular page so we can just link to that page, just incase we will use them in other place.

**Comment by timgraham** [comment]
A possibility is:
```
>>> import django
>>> django.__path__[0] + '/forms/templates'
'/home/tim/code/django/django/forms/templates'
```
I'm not sure if this is the best approach.

**Pull request merged**
