### PR TITLE
Fixed #30252 -- Clarified need to reopen forms.ImageField.image file to access raw image data.

### PR DESCRIPTION
**Pull request by hramezani**
[ticket 30252](https://code.djangoproject.com/ticket/30252)

### CODE REVIEW

**Comment by hramezani** [comment]
Hi, @carltongibson Thanks for the edit.
Sure, it makes sense to have an example there.
I will do it as soon as possible.

**Comment by hramezani** [comment]
@carltongibson 
[ticket 30252](https://code.djangoproject.com/ticket/30252) is related to `django.forms.fields.ImageField`. we have the `image` attribute on `django.forms.fields.ImageField` after validation, which is a `Pillow` image instance. it needs to reopen the image to access its raw data. I already added an example for it.

But, [Ticket 13750](https://code.djangoproject.com/ticket/13750) is related to `django.db.models.ImageField`. I can add another example to this ticket too if you prefer.

**Comment by carltongibson** [comment]
@hramezani You're totally right. Good catch. 👍 Let's address them as separate PRs.

**Comment by felixxm** [comment]
@hramezani Thanks for updates :+1: I pushed minor edits.

**Comment by felixxm** [comment]
Merged in 2282d9f2e5d08fc782087ebe97ab195303a6e79b.

**Pull request closed without merging**
