### PR TITLE
Fixed #24249 -- Improved field shadowing validation in model multi-inheritance

### PR DESCRIPTION
**Pull request by ar45**
Improve forbidding field shadowing in model
multi-inheritance more than one generation.

### CODE REVIEW

**Comment by timgraham** [comment]
buildbot, test this please.

**Comment by timgraham** [comment]
Looks like `get_parent_list()` returns an unordered set, so the error message generated by the test is non-deterministic.

**Comment by ar45** [comment]
what would be the right way then, 1) change `get_parent_list()` to return a tuple, 2) do it inline, 3) create a new method to get it ordered.

**Comment by timgraham** [comment]
You'll need to do a bit of research. I'd try changing the return type of `get_parent_list()` to a list and see if anything breaks (seems a bit misleading to return a set when method name has "list" in it). Another option might be `django.utils.datastructures import OrderedSet`.

**Comment by timgraham** [comment]
buildbot, test this please.

**Comment by charettes** [comment]
I think using an `OrderedSet` converted to a `list` upon return might be required else parents may appear twice when deal with diamond inheritance. e.g.

```
class A(models.Model): pass

class B(A): pass

class C(A): pass

class D(B, C): pass

>>> D._meta.get_parent_list()
[B, A, C, A]
```

**Comment by charettes** [comment]
It might be worth [adding a test](https://github.com/django/django/blob/955f70904a3762894162b46c9bc97cc9abcee5dc/tests/model_meta/tests.py) for `get_parent_list()` to make sure it's working properly in this case.

**Comment by ar45** [comment]
The reason I've chosen list over OrderedSet, because OrderedSet doesn't have a way of bulk update.
But @charettes your right.

Does this make sense now, introducing an additional loop?

**Comment by charettes** [comment]
I opened a ticket about the [ordering of `get_parent_list`](https://code.djangoproject.com/ticket/24266).

**Comment by timgraham** [comment]
`get_parent_list()`

**Comment by timgraham** [comment]
buildbot, test this please.

**Comment by timgraham** [comment]
merged in 4d73303ee974c5f1ea6af984d4578d817825026d, thanks.

**Pull request closed without merging**
