### PR TITLE
Fixed #28628 --Replaced '\d' in regexes with [0-9] for more strict matching.

### PR DESCRIPTION
**Pull request by JunyiJ**
In Python2 and Python3 '\d' in regular expression matches to different patterns. To avoid errors, '\d' was replaced with [0-9].

### CODE REVIEW

**Comment by wkschwartz** [comment]
The matching rules for `\d` are identical in Pythons 2 and 3. In both versions, `u'\d'` matches Unicode decimal characters and `b'\d'` matches `b'[0-9]'`. Unless some test started failing or you have a particular use case that's stopped working, I'm not sure this PR is necessary. Personally, I find `\d` more legible than `[0-9]`.

**Comment by JunyiJ** [comment]
Based on Python3's document, what '\d' corresponding to is slightly different from Python2:

> Matches any Unicode decimal digit (that is, any character in Unicode character category [Nd]). This includes [0-9], and also many other digit characters.

However, I actually kind of agree with you that '\d' seems to be more robust. But if someone intended to use only [0-9], she/he might meet problem with the current version of django.

**Comment by timgraham** [comment]
It would be good to add tests to show what benefit each change has.

**Comment by timgraham** [comment]
Junyi, do you want to move forward with this or should we close it? Absent some tests to show some benefit, I'm not sure.

**Comment by JunyiJ** [comment]
Hi, @timgraham. You can close it. Thanks!

**Pull request closed without merging**
