### PR TITLE
Removed BaseSpatialOperations.truncate_params.

### PR DESCRIPTION
**Pull request by sir-sigurd**
Unused since 32969c3931dea8488ee4ad2849eab43e31e5542e.

### CODE REVIEW

**Comment by sir-sigurd** [comment]
buildbot, test on oracle.

**Comment by sir-sigurd** [comment]
buildbot, test on oracle.

**Comment by sir-sigurd** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Pull request merged**
