### PR TITLE
[WIP] Prevented post_migrate receivers from running if the required migrations are not applied.

### PR DESCRIPTION
**Pull request by charettes**
This is related to multiple bug such as:

[#24299](https://code.djangoproject.com/ticket/24299), [#22411](https://code.djangoproject.com/ticket/22411) and [#24524](https://code.djangoproject.com/ticket/24524).

### CODE REVIEW

**Comment by charettes** [comment]
@MarkusH, if the `post_migrate` signal was either dispatching the state of the applied migrations or the final `apps` state we could remove all this boiler plate.

**Comment by charettes** [comment]
The `migrations_import_path` check is required because of the `MIGRATION_MODULES` usage in `runtests.py`.

**Comment by MarkusH** [comment]
I kind of like the approach at a first glance :smile: . Need to think about it. Dispatching `apps` should be too big of a problem.

**Comment by charettes** [comment]
> I kind of like the approach at a first glance

I can't say I do :)

> Dispatching apps should be too big of a problem.

Are you referring to the discussion that took place about not dispatching anything until you're done with your refactor?

**Comment by MarkusH** [comment]
>> Dispatching apps should be too big of a problem.

> Are you referring to the discussion that took place about not dispatching anything until you're done with your refactor?

ARG, shouldn't: Dispatching apps should not be a problem

**Pull request closed without merging**
