### PR TITLE
Refs #34572 -- Added missing GDAL_PIXEL_TYPES from GDAL 3.5+.

### PR DESCRIPTION
**Pull request by claudep**
See https://github.com/OSGeo/gdal/blob/6e9103bd5/gcore/gdal.h#L62

### CODE REVIEW

**Comment by felixxm** [comment]
@claudep Thanks! I will install it locally and check

**Comment by felixxm** [comment]
I have one more error with this patch:
```
ERROR: test_compressed_file_based_raster_creation (gis_tests.gdal_tests.test_raster.GDALRasterTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/django/tests/gis_tests/gdal_tests/test_raster.py", line 452, in test_compressed_file_based_raster_creation
    compressed.bands[0].metadata["IMAGE_STRUCTURE"]["PIXELTYPE"], "SIGNEDBYTE"
KeyError: 'IMAGE_STRUCTURE'
```
but that's a separate issue.

**Comment by felixxm** [comment]
See [MIGRATION_GUIDE](https://github.com/OSGeo/gdal/blob/911cdaf435d13641988ff5584bbf253e16cfe1c4/MIGRATION_GUIDE.TXT#L4-L9).

**Comment by felixxm** [comment]
> See [MIGRATION_GUIDE](https://github.com/OSGeo/gdal/blob/911cdaf435d13641988ff5584bbf253e16cfe1c4/MIGRATION_GUIDE.TXT#L4-L9).

I think we can skip setting `pixeltype` on GDAL 3.7, see [docs](https://gdal.org/user/raster_data_model.html#image-structure-domain):

_"Starting with GDAL 3.7, this metadata item is no longer used, as the Int8 data type is used for signed bytes."_

**Comment by felixxm** [comment]
@claudep Can you [document](https://docs.djangoproject.com/en/4.2/ref/contrib/gis/gdal/#the-ds-input-dictionary) new datatypes?

**Comment by claudep** [comment]
We could link the second enumeration to the first list of datatypes. Do you know if it's possible to link to a `.. object::` section or if we should add a new `.. _gdal-raster-datatype:` tag?

**Comment by felixxm** [comment]
> We could link the second enumeration to the first list of datatypes. Do you know if it's possible to link to a `.. object::` section or if we should add a new `.. _gdal-raster-datatype:` tag?

It's probably not possible, see [docs](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#directive-object).

**Review by felixxm — COMMENTED** [review]
@claudep Thanks :+1:

**Pull request merged**
