### PR TITLE
Fixed #24226 -- Changed admin EMPTY_CHANGELIST_VALUE from (None) to -

### PR DESCRIPTION
**Pull request by andela-oifedapo**
Fixes #24226

### CODE REVIEW

**Comment by timgraham** [comment]
buildbot, test this please.

**Comment by timgraham** [comment]
Updated the failing test, added a release note, and merged in e4a578e70e2e48ab792e38c67579808a1def6024, thanks.

**Comment by andela-oifedapo** [comment]
@timgraham Any way I could get author credit for this?

**Comment by timgraham** [comment]
Please submit a PR adding your name to AUTHORS.

**Pull request closed without merging**
