### PR TITLE
FIxed TIcket 31354: Include Port in Host when not default

### PR DESCRIPTION
**Pull request by dgcgh**
When constructing the authority (host+port) for a URI it should
include the port number if the port is not the standard port for
the given scheme (80 for HTTP, 443 for HTTPS).

This change ensures that calls to request.build_absolute_uri()
will return a correct URL when the SERVER_PORT (or X_FORWARDED_PORT)
is something other than the default.

### CODE REVIEW

**Comment by dgcgh** [comment]
@apollo13 is this closer to what you were thinking? I think you may have wanted to handle the port extraction in the `_get_host_and_port` method, but I think it's better to keep the logic for resolving the port in one place.

**Comment by Automobileservices4** [comment]
#12679

**Comment by apollo13** [comment]
@dgcgh This PR looks certainly a bit cleaner, though what worries me is that we are doing work here multiple times in `get_port`. Ie if `X_FORWARDED_HOST` is set there should be no need to look into `HOST` at all. Not that parsing regexes is the end of the world, but it is extra validation for stuff that will never get used.

Also now that https://github.com/django/django/pull/12679/files#diff-0eb6c5000a61126731553169fddb306eR155 moved out you'd also have to duplicate it for `get_raw_uri` where we'd want to replace `_get_raw_host` with the new functionality too.

**Comment by dgcgh** [comment]
I thought that `get_raw_uri` was the valid use case for an unvalidated `_get_raw_host`. Is there another you can point me at? do we want `get_raw_uri` to get the normalized version of the `host:port`? if so maybe there isn't a valid use case for an unvalidated version of `get_host`.

we can check for a port on the various host headers slightly more efficiently than the validation regex, which was surprising to me because I'm used to simple regular expressions (those without backtracking, or lookahead) being nearly as fast as `split()` or `replace()`. we get a nearly 50% performance boost from doing a split and integer parse to check that the last colon delimited slice is a port (assuming the header is well formed):
```
In [8]: timeit.timeit('anre.match("[::1]:8080")', setup='''import re; anre=re.compile(r"^([a-z0-9.-]+|\[[a-f0-9]*:
   ...: [a-f0-9\.:]+\])(?::(\d+))?$")''')                                                                         
Out[8]: 0.9723994840169325

In [10]: timeit.timeit('x="[::1]:8080".split(":")[-1]; int(x)')                                                   
Out[10]: 0.5013509549899027
```
Though it seems unlikely that someone would want the port from the request without fetching the host at some point, and it makes me wonder when syntax validation _should_ occur. It might be better to lazily populate an instance variable with the canonical host and port number. That would mean we could relocate the port resolution logic to `_get_raw_host_and_port` and have both `get_port` and `get_host` take that path. what do you think?

**Comment by dgcgh** [comment]
@apollo13 also, I see your point about `HTTP_HOST` not needing to be parsed if `X_FORWARDED_HOST` is present. I decided to go with this cascade pattern to prevent having to test all of the conditions in each clause. I think it's easier to read, but it is work that we can avoid.

**Comment by apollo13** [comment]
> I thought that get_raw_uri was the valid use case for an unvalidated _get_raw_host. 

Yes, but that also means we'd have two functions which basically do the same (with only a slight variance). I'd like to go towards one function if possible.

> do we want get_raw_uri to get the normalized version of the host:port?

Hard to say, I'd dig in the history of that file to see how it changed and which tickets were affected. Because as you pointed out the test coverage is probably not optimal.

> In [10]: timeit.timeit('x="[::1]:8080".split(":")[-1]; int(x)') 

That alone is not correct though as an IPv6 addr without a port would then need extra handling.

>  what do you think?

Dunno, it depends a little bit on what the promises of the actual functions are. I'll do some code digging tomorrow.

**Comment by dgcgh** [comment]
| That alone is not correct though as an IPv6 addr without a port would then need extra handling.

that's what the `int(x)` is for, if the address doesn't have a port then we'll get some number with a bracket in it, we just have to `try:` it and pass if an exception is thrown....
now that I test that, the failure case is terrible:
```
In [10]: timeit.timeit('''x="[::1]".split(":")[-1] 
    ...: try: 
    ...:     y=int(x) 
    ...: except: 
    ...:     pass 
    ...: ''')                                                                                                     
Out[10]: 1.6620176819851622
```
but we can use `x.isdigit()`, that's better:
```
In [17]: timeit.timeit('''x="[::1]".split(":")[-1] 
    ...: if x.isdigit(): 
    ...:   pass 
    ...: else: 
    ...:   pass 
    ...: ''')                                                                                                     
Out[17]: 0.37632922403281555
```

What worries me about this approach is what will happen if the selected host header is not well formed. where will that error be exposed, and will it provide the user with a useful diagnosis?

**Comment by apollo13** [comment]
So I took my time machine and found https://code.djangoproject.com/ticket/25099#comment:7 which introduced the splitting between raw and validated hosts.

So I'd argue that the `raw` methods should use the unvalidated host header as much as possible. `get_raw_uri` literally only exists (in Django's use at least) for the 500 templates so I am okay with not keeping the behaviour 100%, but we should keep invalid host headers as they serve as debugging aid.

**Comment by dgcgh** [comment]
okay, so we're stuck with `_get_raw_host` doing basically what it currently does, so we do need two code paths. Though I could roll `_get_host_and_port` into `get_host` without losing any functionality. It seems that the leaky abstraction may have been using `_get_raw_host` in `get_host`. (if I'm reading that correctly)

**Comment by felixxm** [comment]
Superseded by #12844.

**Pull request closed without merging**
