### PR TITLE
#31169 Ensure the parallel test worker has initialised django and uses the test db names

### PR DESCRIPTION
**Pull request by bragradon**

### CODE REVIEW

**Comment by bragradon** [comment]
Hi @carltongibson 

I encounter this issue on a work project which should be a normal Django project.

**Comment by BrandonNav** [comment]
@carltongibson 

I was curious on whether the Django test suite would work on my laptop. I do encounter this issue with the current master branch of Django (MacOS 10.14.6) 

Steps I did:

```
$ git clone https://github.com/YourGitHubName/django.git django-repo
$ cd django-repo/tests
$ python -m pip install -e ..
$ python -m pip install -r requirements/py3.txt
$ ./runtests.py --parallel 4
```

**Comment by bragradon** [comment]
@carltongibson

I was curious on whether the Django test suite would work on my laptop. I do encounter this issue with the current master branch of Django (MacOS 10.14.6)

Steps I did:

```
$ git clone https://github.com/YourGitHubName/django.git django-repo
$ cd django-repo/tests
$ python -m pip install -e ..
$ python -m pip install -r requirements/py3.txt
$ ./runtests.py --parallel 4
```

**Comment by carltongibson** [comment]
Hi @bragradon. Thanks for the follow-up. Your steps are correct. 

I need to look into the setup in `runtests.py` to see exactly what state we need to pass to the workers to get them set up right.

**Comment by felixxm** [comment]
Closing in favor of #12646

**Pull request closed without merging**
