### PR TITLE
Fixed #29654 -- Made Truncator use ellipsis character instead of three dots.

### PR DESCRIPTION
**Pull request by debugger22**
Fixes https://code.djangoproject.com/ticket/29654#ticket

### CODE REVIEW

**Comment by jeffyancey** [comment]
@claudep  pointed out:

>  But there are many more occurrences in the Django source code and comments. We should be consistent. Does this need a discussion?

Should we expand this ticket to find and replace `...` with ellipses throughout the project?

**Comment by charettes** [comment]
@jeffyancey the master is Python 3 only and were previously using `__future__.unicode_literals` so this shouldn't be an issue.

**Comment by claudep** [comment]
Are you able to continue or do you want some help?

**Comment by debugger22** [comment]
I got a little busy with my day job. I'll try and finish it up by the end of this week. If anyone wants to help, they are most welcome.

**Comment by timgraham** [comment]
Continued in https://github.com/django/django/pull/10306.

**Comment by timgraham** [comment]
Completed in https://github.com/django/django/pull/10324.

**Pull request closed without merging**
