### PR TITLE
Refs #33029 -- Fixed window switching in Selenium test.

### PR DESCRIPTION
**Pull request by yj7**
[ticket-33029](https://code.djangoproject.com/ticket/33029) 

https://github.com/django/django/pull/14823#issuecomment-934321839

### CODE REVIEW

**Comment by yj7** [comment]
buildbot, test on selenium

**Comment by yj7** [comment]
@carltongibson 

Have made the changes to tests. Please take a look.

**Comment by carltongibson** [comment]
buildbot, test on selenium.

**Comment by carltongibson** [comment]
buildbot, test on selenium.

**Review by carltongibson — DISMISSED** [review]
Hi @yj7 — thanks for this. Looks like it does the job just right. 👍

**Comment by carltongibson** [comment]
Hmmm. Not 100% sure this has got it. Failure on #14941 https://djangoci.com/job/pull-requests-selenium/database=sqlite3,label=bionic-pr,python=python3.10/321/

**Comment by carltongibson** [comment]
One issue I have here is this doesn't (yet) reproduce for me locally. 🤔

**Comment by carltongibson** [comment]
Hi @yj7 --- let's resolve this in #14941. Thanks!

**Pull request closed without merging**
