### PR TITLE
Fixed #33637 -- Improved initial zoom level in MapWidget.

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by felixxm** [comment]
@claudep Thanks for this patch :+1: Does `default_zoom` have any meaning now? I tried to change it but it doesn't seems to have any impact on the map.

**Comment by claudep** [comment]
`default_zoom` is the zoom used when you add a new geometry value (and such initially blank).

**Comment by felixxm** [comment]
> `default_zoom` is the zoom used when you add a new geometry value (and such initially blank).

I tried to change it but it makes no visible difference :thinking: : 
- `default_zoom = 12`:
  image
- `default_zoom = 99`:
  image
- `default_zoom = 1`:
  image

**Comment by claudep** [comment]
It should work, e.g. with this admin code:
```
@admin.register(YourModel)
class YourModelAdmin(admin.GISModelAdmin):
    gis_widget_kwargs = {'attrs': {'default_zoom': 8}}
```

**Comment by felixxm** [comment]
> It should work, e.g. with this admin code:
> 
> ```
> @admin.register(YourModel)
> class YourModelAdmin(admin.GISModelAdmin):
>     gis_widget_kwargs = {'attrs': {'default_zoom': 8}}
> ```

Right, it works. I tried to override it in the `OLMapWidget.js` which obviously didn't change anything as `zoom_default` is also defined in `OSMWidget`.

**Pull request merged**
