### PR TITLE
Ticket #18054 -- Add deprecation note for contrib.markup

### PR DESCRIPTION
**Pull request by nagisa**
https://code.djangoproject.com/ticket/18054

### CODE REVIEW

**Comment by noa-lucent** [comment]
[major] In  the new import-time warning still uses . The ticket explicitly calls for an accelerated deprecation, so this needs to be a  (or the Django-specific ). With  the message stays silent for most projects and the deprecation never reaches users.

**Comment by noa-lucent** [comment]
[major] In `django/contrib/markup/__init__.py` the new import-time warning still uses `PendingDeprecationWarning`. The ticket explicitly calls for an accelerated deprecation, so this needs to be a `DeprecationWarning` (or the Django-specific `RemovedInDjango16Warning`). With `PendingDeprecationWarning` the message stays silent for most projects and the deprecation never reaches users.

**Comment by noa-lucent** [comment]
[major] The new release-note section is labeled ``django.utils.markup``, but the package being deprecated is ``django.contrib.markup``. As written, the note misdirects readers. Could you fix the module name and rework the copy so it actually tells people what to do (e.g., install and use the relevant third-party markup libraries) rather than just paraphrasing the ticket discussion?

**Comment by noa-lucent** [comment]
[major] The ticket specifically called out adding an entry to ``docs/internals/deprecation.txt`` (and to flag the accelerated schedule). I don’t see that change in this PR yet, so the documentation package is incomplete.

**Comment by timgraham** [comment]
@noa-lucent please don't use this repository for testing.

**Pull request closed without merging**
