### PR TITLE
Fixed #35100 -- Reworked GeoIP2 database initialization.

### PR DESCRIPTION
**Pull request by ngnpope**
ticket-35100.

### CODE REVIEW

**Comment by ngnpope** [comment]
@felixxm After #17706, this should be the last piece related to GeoIP2 😅

**Comment by felixxm** [comment]
It seems that countries shipped with cities only have subset of fields available :thinking:

**Comment by ngnpope** [comment]
> It seems that countries shipped with cities only have subset of fields available 🤔

Nah. I just needed to rebase after #17706 which added the extra fields 🤦🏻

**Review by felixxm — COMMENTED** [review]
@ngnpope Thanks :+1:

**Pull request merged**
