### PR TITLE
Fixed #35422 -- Fixed migrations crash when altering GeneratedField referencing rename field.

### PR DESCRIPTION
**Pull request by felixxm**
Thanks Sarah Boyce for the report and Simon Charette for the implementation idea.

ticket-35422

### CODE REVIEW

**Comment by charettes** [comment]
Ok so MySQL doesn't support repointing field references in generated field expressions so we might need a feature flag for that?

**Comment by felixxm** [comment]
> Ok so MySQL doesn't support repointing field references in generated field expressions so we might need a feature flag for that?

Maybe it's enough to skip these tests on MySQL :thinking: MySQL raises a really clear error message: _"Column 'pink' has a generated column_ dependency.", so I would leave it as it is.

**Comment by charettes** [comment]
Sounds good to me!

**Review by sarahboyce — APPROVED** [review]
Thank you this looks great! 
I will rebase and merge shortly 👍

**Pull request merged**
