### PR TITLE
Fixed #34445 -- Forced lazy() to cast to string when a result type of str is specified

### PR DESCRIPTION
**Pull request by shangxiao**

### CODE REVIEW

**Comment by felixxm** [comment]
`str()` call was removed in fe8484efda257e151d9c1ca5151e546c9262bf0f. @aaugustin Do you remember why? :thinking:

**Comment by ngnpope** [comment]
Also see #11314 which looked to strip out a lot of the complexity after the removal of Python 2. I put in a lot of review and thought it was nearly finished… Time flies!

**Comment by felixxm** [comment]
@shangxiao This issue can be fixed by 4b902b230bbc9efc84539e013b75b63f1ad6e3a5 it's also mentioned in the https://github.com/django/django/pull/11314/commits/9bd855a3386acbfeba231b8afcdfa688c3eaa1c2#r309157402.

I'd prefer to take 9bd855a3386acbfeba231b8afcdfa688c3eaa1c2, 4b902b230bbc9efc84539e013b75b63f1ad6e3a5, and your test method instead of adding a `str()` call. What do you think?

**Comment by shangxiao** [comment]
@felixxm Ok that sounds good 👍 simplifies things 🎉

**Comment by felixxm** [comment]
Superseded by #16707.

**Pull request closed without merging**
