### PR TITLE
Fixed #24624 -- Replaced obsoleted rel.opts in admindocs view

### PR DESCRIPTION
**Pull request by claudep**
Thanks Scott Sanders for the report. Refs #24381.

### CODE REVIEW

**Comment by claudep** [comment]
1.8 release note is missing. I'd write:
`* Fixed a regression in the model detail view of :mod:``django.contrib.admindocs``
  when a model as a ``ManyToOne`` relation (:ticket:``24624``).`

**Comment by MarkusH** [comment]
I think you're missing a verb after "admindocs"

**Comment by MarkusH** [comment]
I don't understand the `Refs #24381` in the commit message

**Comment by claudep** [comment]
I think that removal of ForeignObjectRel.opts has been committed in 24381, which was the cause of this regression (as suggested by the OP). Am I wrong?

**Comment by claudep** [comment]
Sorry, `when a model as` -> `when a model has`

**Comment by MarkusH** [comment]
You're right. I was looking for a larger patch.

**Comment by timgraham** [comment]
Looks good, I made minor edits to your comment with the release note.

**Pull request merged**
