### PR TITLE
Fixed #31731 -- Removed unreachable code for resetting sequences of auto-created m2m tables in sequence_reset_sql().

### PR DESCRIPTION
**Pull request by Ravindar24**
Removed dead code for condition check on model._meta.many_to_many for 'f.remote_field.through' from postgres/Oracle operations.py

### CODE REVIEW

**Comment by auvipy** [comment]
no related tests? or any tests to check this won't regress?

**Comment by felixxm** [comment]
@Ravindar24 Thanks :+1: Welcome aboard :boat:

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by Ravindar24** [comment]
@felixxm Thanks a lot for you support and guidance 😃

**Pull request merged**
