### PR TITLE
Fixed #30934: Include database alias in `django.db.backends` debug output 

### PR DESCRIPTION
**Pull request by abhijeetviswa**
Original PR: #11994 

Went through the patch checklist and changed patch notes and added version added admonition to documentation.

Thanks to @codeinthehole for the ticket and patch. I simply added the documentation.

### CODE REVIEW

**Comment by abhijeetviswa** [comment]
@felixxm  Tagging you here since you had set the triage back from `Ready for checkin` to `Accepted`.

**Comment by felixxm** [comment]
I don't know why you created a new PR since the original one is still waiting for a review.

**Comment by abhijeetviswa** [comment]
@felixxm The original had two reviewers who accepted the changes and it was marked as `Ready for checkin` in the original ticket. However, you had pushed it back to `Accepted` because it didn't follow the patch guidelines. I just fixed those changes and created a new PR.

**Comment by felixxm** [comment]
The original PR is still waiting for a proper review, I just ask Carlos to review ticket before he will mark it as "ready for checkin". If you want to help then please leave comments in the original PR and give an author a chance to fix them.

**Comment by abhijeetviswa** [comment]
Ohh my bad. I thought that since the originanl author hadn't fixed the PR for 8 weeks, I could work on it. Should've left a comment on the ticket as well.

Sorry for the trouble.

**Pull request closed without merging**
