### PR TITLE
Fixed typos in comments and docs

### PR DESCRIPTION
**Pull request by minho42**
Some of them were found by reading, and the others were by script.

### CODE REVIEW

**Comment by carltongibson** [comment]
@minho42 two weeks later 🙂 

Could you please share the script that you use so we can perhaps see if we can’t catch more of these errors at a single pass? Thanks!

**Comment by minho42** [comment]
Hi @carltongibson, 
I made my script public.
https://github.com/minho42/typofinder

I don't think there's more to catch at the moment.
Half of them were found by just reading docs and codes :)

**Comment by carltongibson** [comment]
Hey @minho42. Thanks for the script. Looks very handy. Let me play with it a while... 👍

**Comment by atombrella** [comment]
In `ref/middleware.txt`, there's an instance of "the the".

**Comment by minho42** [comment]
Thanks!

**Comment by atombrella** [comment]
I found a few more using: `pcregrep -M --color=always -r "(\b[A-bBIZa-z]+)\s+\1\b " **/*.txt` although it also checks for variable names that are the same as the last word of the line. My other command only checked for instances on the same line.

**Pull request merged**
