### PR TITLE
Add `django.template.Engine.get_default_backend` for easier access to backend methods

### PR DESCRIPTION
**Pull request by peterthomassen**

### CODE REVIEW

**Comment by felixxm** [comment]
@peterthomassen Thanks for this patch, however all new features require [an accepted ticket](https://code.djangoproject.com/newticket). Please [follow the guidelines with regards to requesting features](https://docs.djangoproject.com/en/stable/internals/contributing/bugs-and-features/#requesting-features).

**Comment by peterthomassen** [comment]
I posted on the list (https://groups.google.com/g/django-developers/c/BfB9QsDMMAI) and shall open a ticket subsequently, depending on the discussion outcome.

**Comment by peterthomassen** [comment]
Here's the ticket: https://code.djangoproject.com/ticket/33943

I'd appreciate if you could let me know how to proceed (in particular, whether the next steps happen on the list, on the bug tracker, or here).

**Comment by carltongibson** [comment]
Hi @peterthomassen — Let's follow-up on the mailing list (where I replied with some initial queries). 
I'll close this for now, while we discuss. We can re-open if we decide to proceed. Thanks! 👍

**Pull request closed without merging**
