### PR TITLE
Removed unnecessary parentheses and change double quote to single quote in model check messages.

### PR DESCRIPTION
**Pull request by shangdahao**

### CODE REVIEW

**Comment by srinivasreddy** [comment]
I am -0 on this.  I do not see real value in this cleanup.

**Comment by neoatmatrix** [comment]
-0

**Comment by timgraham** [comment]
If you found a few other cleanups it might be fine. Looking at the file, one thing that could be fine is merging lines like:
```
index_together = [
    ["m2m"],
]
```
to: `index_together = [['m2m']]`.
That was another pattern that I changed when reviewing your other PR.

**Comment by shangdahao** [comment]
Thanks for suggestions, I have make a little more cleanups. Feel free to close this PR if you think there are no value.

**Pull request merged**
