### PR TITLE
#33090 extend sensitive post parameter filtering

### PR DESCRIPTION
**Pull request by Oluwayhemisi**

### CODE REVIEW

**Comment by shangxiao** [comment]
@Oluwayhemisi Hi & welcome ❤️ Is this PR still a draft? If so can you mark it draft until it's ready to review.

**Comment by sarahboyce** [comment]
Hi @Oluwayhemisi :wave: it looks like your commits from https://github.com/django/django/pull/16592 are appearing here, I think only the changes in 7c4d6a0536eed9fa34eda445418312ee7b5a78b7 are wanted here :thinking:

**Comment by Oluwayhemisi** [comment]
@sarahboyce I've fixed the issue

**Comment by Oluwayhemisi** [comment]
> @Oluwayhemisi Hi & welcome heart Is this PR still a draft? If so can you mark it draft until it's ready to review.

@shangxiao yes it's a draft. There was an issue with the branch which i already fixed in the new PR [https://github.com/django/django/pull/16772]

**Pull request closed without merging**
