### PR TITLE
✍️ Change wording on default response page

### PR DESCRIPTION
**Pull request by mermop**
Changes the wording of the default response page to be a little friendlier.

This weekend I was coaching at a Django Girls workshop. The point in the workshop at which this page comes up comes after students actually have done quite a lot of work and it's a pretty needlessly negative message to receive.

### CODE REVIEW

**Comment by timgraham** [comment]
Good suggestion. No need to update the po files. Another option could be to simply remove that sentence.

**Comment by mermop** [comment]
So just the update to `django/views/debug.py` is enough @timgraham?

**Comment by timgraham** [comment]
Do you think that sentence is adding value compared to just removing it?

**Comment by mermop** [comment]
I think it probably works either way - your call.

**Comment by timgraham** [comment]
I was thinking that removing it will save translators some work.

**Comment by timgraham** [comment]
merged in eb7fb565e6483637fc4ee251940b86db813485a0, thanks!

**Pull request closed without merging**
