### PR TITLE
Fixed #28201 -- Added null chars validator to CharField and TextField

### PR DESCRIPTION
**Pull request by alejandrozf**
Added default null characters validation to CharField and TextField in
order to avoid raising errors on database layer. Added tests for both
fields.

### CODE REVIEW

**Comment by francoisfreitag** [comment]
Hi @alejandrozf,

Thank you for submitting that PR! I think you should open it against the master branch, the Django team will then port the patch to other releases when that's necessary.

**Comment by alejandrozf** [comment]
Got it @francoisfreitag . Thanks, I'll be change it now.

**Comment by alejandrozf** [comment]
@francoisfreitag should I close this PR and reopened against master because the conflicts?

**Comment by chukkwagon** [comment]
@alejandroz I saw that it was released in 2+, do you know the status of this ticket in terms of release in 1.11?

**Pull request closed without merging**
