### PR TITLE
[4.0.x] Updated translations from Transifex.

### PR DESCRIPTION
**Pull request by felixxm**
~~in progress ....~~

This also fixes i18n tests related to e4430f22c8e3d29ce5d9d0263fba57121938d06d.

### CODE REVIEW

**Comment by felixxm** [comment]
@claudep Can you take a look?

**Comment by claudep** [comment]
Thanks, looks really good. I'd just want to integrate some more Hebrew translations which are not possible with Transifex due to a Transifex bug. I'll push to your branch.

**Comment by felixxm** [comment]
> I'll push to your branch.

Please do, thanks :+1:

**Comment by claudep** [comment]
@uri-rodberg, would you like to also update plural translations from the conf resource. If yes, then please download https://raw.githubusercontent.com/django/django/284d1d1cea0d9dcba7cccea8ad8e7f6b9b10e134/django/conf/locale/he/LC_MESSAGES/django.po and send me the updated file.

**Comment by kezabelle** [comment]
Fair warning, I don't know the workflow, or requirements for acceptance (given these are presumably _generated_ from Transifex, thus can't be fixed locally). There look to be a few occurrences where `"…"` has been translated to `"..."`. I don't know that it specifically matters, so I'm just pointing it out (and in the process I'll probably learn something ;))

**Comment by uri-rodberg** [comment]
> @uri-rodberg, would you like to also update plural translations from the conf resource. If yes, then please download https://raw.githubusercontent.com/django/django/284d1d1cea0d9dcba7cccea8ad8e7f6b9b10e134/django/conf/locale/he/LC_MESSAGES/django.po and send me the updated file.

Done.

**Comment by claudep** [comment]
Thanks, I think the PR should now be ready.

**Review by claudep — APPROVED** [review]

**Comment by felixxm** [comment]
> Fair warning, I don't know the workflow, or requirements for acceptance (given these are presumably _generated_ from Transifex, thus can't be fixed locally). There look to be a few occurrences where `"…"` has been translated to `"..."`. I don't know that it specifically matters, so I'm just pointing it out (and in the process I'll probably learn something ;))

@kezabelle We have dozens of languages and currently they are handled at Transifex. I'm skeptical about the idea that we'll have an additional task to translate (even) simple strings.

**Comment by felixxm** [comment]
@claudep Thanks for help :1st_place_medal:

**Pull request merged**
