### PR TITLE
Fixed #26022 -- Cleaned up assertRaises* test assertions.

### PR DESCRIPTION
**Pull request by hramezani**
Convert `assertRaises` and `assertRaisesMessage` to ontext manager version.

Convert without regular experesion `six.assertRaisesRegex` tests to `assertRaisesMessage` .

### CODE REVIEW

**Comment by hramezani** [comment]
@timgraham Why `default` check failed? i dont changed `test_raster.py`.

**Comment by hramezani** [comment]
@timgraham Checks passed!!!

**Comment by hramezani** [comment]
@timgraham All fixes done.

**Comment by hramezani** [comment]
@timgraham I fix reported problem. as you mentioned there is a lot of pep8 and style problem, maybe I create a PR to fix that . can you give me your pep8 configure file.

**Comment by timgraham** [comment]
Could you please fix all instances of that problem that you touched? It would be nice to have to modify all those lines again. I think basically `with assertRaises*( ):` should never be multined. Our flake8 ignores are in `setup.cfg`. I think most of them are there because we have so many violations it would be a lot of work to fix them all but maybe someday.

**Comment by hramezani** [comment]
@timgraham Ok .

**Comment by timgraham** [comment]
Another option that might make the patch a bit less invasive is to use this style as done in https://github.com/django/django/pull/6003:
```python
with self.assertRaisesMessage(
    TypeError,
    "select_template() takes an iterable of template names. "
    "Use get_template() if you want to load a single template "
    "with its name."
):
```
(putting the closing parenthesis on its own line)

**Comment by hramezani** [comment]
@timgraham Problems fixed.

**Comment by hramezani** [comment]
@timgraham I merged my branch with current master branch in my local repository. Do you want to push it up?

**Comment by timgraham** [comment]
Merged first three commits in 3d0dcd7f5af378d3ab6adb303b913e6c7b2e0ee5, 253adc2b8a52982139d40c4f55b3fd446e1cb8f3, and 26ad01719d73823e65c0358a2ee9941e0a888a63. I guess there might be some remaining flake8 cleanups in the fourth commit. Feel free to rebase it and send a separate pull request. Thanks for that tedious but useful work!

**Pull request closed without merging**
