### PR TITLE
Minor edits to password validation tests/docs (refs #16860).

### PR DESCRIPTION
**Pull request by timgraham**
@erikr, my other question is if there would be any benefit to including a `code` for each validation error.

### CODE REVIEW

**Comment by erikr** [comment]
I don't directly see a useful scenario for that. But I guess it would be fairly simple and not do any harm. 

Thanks for the tweaks to the patch, btw.

**Comment by timgraham** [comment]
@loic, do you think using `code` and `params` has any benefit for this patch (1daae25bdcd735151de394a5578c22257e3e5dc7)?

**Comment by loic** [comment]
Definitely. Not providing them prevents customisation of the error messages and `as_data() / as_json()` become much less useful.

**Comment by timgraham** [comment]
Added a commit (to be squashed) with those updates.

**Comment by loic** [comment]
LGTM

**Pull request merged**
