### PR TITLE
Fixed #25279 -- Made prefetch_related_objects() public

### PR DESCRIPTION
**Pull request by adamchainz**
[Ticket 25279](https://code.djangoproject.com/ticket/25279)

### CODE REVIEW

**Comment by timgraham** [comment]
Suggested edits: http://dpaste.com/3V6K7F3
Please squash commits when updating. I'll promote the ticket to RFC and wait for Loic's review.

**Comment by charettes** [comment]
@ecederstrand, do you think making this API public as is will make work toward (#25464)[https://github.com/django/django/pull/5356] harder or impossible?

**Comment by ecederstrand** [comment]
I'm +0 on this, as I'm completely new to the Django codebase. What I want in https://github.com/django/django/pull/5356 is a way to gain control of the queryset used for prefetching, to avoid the mandatory IN clause. Either by using the original query as a subquery for the ID field, or by providing a completely different queryset. AFAICS, this requires a change to the prefetch_related_objects() API, although only by adding an optional attribute.

**Comment by adamchainz** [comment]
@timgraham done, sorry for dealy.

I don't think this makes #5356 harder or easier, since the same optional kwarg can be added to both functions.

**Comment by timgraham** [comment]
merged in ef33bc2d4d5e66b08cba2a318aa700ba1e28ba81, thanks!

**Comment by adamchainz** [comment]
Cheers!

**Pull request closed without merging**
