### PR TITLE
Fixed #25865 -- Made OSMGeoAdmin to require GDAL only if transformation is really needed.

### PR DESCRIPTION
**Pull request by sir-sigurd**
https://code.djangoproject.com/ticket/25865

### CODE REVIEW

**Comment by auvipy** [comment]
would u re-base?

**Comment by timgraham** [comment]
@claudep, any further thoughts about whether or not to move forward with this?

**Comment by claudep** [comment]
I think that very few people will be able to use the OSMGeoAdmin without GDAL, but well, this doesn't harm, so let's go forward.

**Comment by timgraham** [comment]
okay, @sir-sigurd could you please rebase at your convenience?

**Comment by timgraham** [comment]
Rebased in https://github.com/django/django/pull/6269.

**Pull request closed without merging**
