### PR TITLE
Add black settings to pyproject.toml for black project CI

### PR DESCRIPTION
**Pull request by cooperlees**
Hi Django,

We know you're not a black formatted project (and that's fine) but we would like to use you for our CI as you give us ~1900 source files that need formatting. This is very valuable for us.

You have a few files that on purpose have syntax errors and some other files that don't offer us much value so we need to exclude them.

This PR adds to your already existing `pyproject.toml` the files we need to ignore to get a reliable black run.

Would this be considered to help our CI?

Thanks!

### CODE REVIEW

**Comment by cjerdonek** [comment]
> Would this be considered to help our CI?

@cooperlees The best thing to do is to file a ticket first, and it can be discussed there: https://code.djangoproject.com/query

**Comment by cooperlees** [comment]
Ok. I thought that would be spammy since this is just config that causes no changes to your project that does not use black. Will create the ticket and do the dance tho I guess.

**Comment by cjerdonek** [comment]
>  I thought that would be spammy

No, it's not spammy! It's just the way that PR's are tracked.

**Comment by cjerdonek** [comment]
Closing per: https://code.djangoproject.com/ticket/32818#comment:2

**Pull request closed without merging**
