### PR TITLE
Fixed #31293 -- Allowed MultiPartParser to handle double-quoted encoded headers.

### PR DESCRIPTION
**Pull request by 007gzs**
ticket-31293

### CODE REVIEW

**Comment by 007gzs** [comment]
I'm Sorry, I have rebase upstream/master in my branch. Now the file changed is not what I expected, what should I do

**Comment by 007gzs** [comment]
Now it looks ok in https://github.com/django/django/compare/master...007gzs:rfc2231_master . Is there anything I need to do

**Comment by carltongibson** [comment]
I have the patch rebased locally. I could not push yesterday PM as GitHub had issues. I will force push the patch again later today. 

Thanks for your input @007gzs!

**Comment by 007gzs** [comment]
Thank you. What should I do if I want to merge the changes into version 2.2 and 3.0? Create a new ticket?

**Comment by felixxm** [comment]
@007gzs 

> Thank you. What should I do if I want to merge the changes into version 2.2 and 3.0? Create a new ticket?

Backporting doesn't require a separate ticket. Unfortunately, this patch doesn't qualify for a backport.

**Comment by 007gzs** [comment]
> Backporting doesn't require a separate ticket. Unfortunately, this patch doesn't qualify for a backport.


I think https://github.com/django/django/pull/12490 needs to merge into 2.2 and 3.0

**Comment by felixxm** [comment]
> > Backporting doesn't require a separate ticket. Unfortunately, this patch doesn't qualify for a backport.
> 
> I think #12490 needs to merge into 2.2 and 3.0

No, see our [backporting policy](https://docs.djangoproject.com/en/3.0/internals/release-process/).

**Comment by felixxm** [comment]
Thanks both :+1: I pushed minor edits to tests.

**Pull request merged**
