### PR TITLE
[WIP] Fixed #24935 -- Refactored conditional GET handling

### PR DESCRIPTION
**Pull request by syphar**
first basis for discussion

### CODE REVIEW

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
Is this still a work in progress? Anything in particular you wanted to discuss? That code is complicated so not sure I could give much feedback without a detailed review.  The tests passing is at least a good sign.

**Comment by timgraham** [comment]
@syphar, any response to my previous question? It looks mostly good to me (some suggested cosmetic edits: http://dpaste.com/1CB3Q7J, and I think we might want to rename `handle_conditional_get()` to something like `get_conditional_response()` since "handle" doesn't have a clear meaning).

Does this enable new functionality (in which case it would be nice to have tests) or is it merely a refactoring?

**Comment by syphar** [comment]
@timgraham sorry, didn't see the original comment 

- it's definitely a refactoring (or, more exact a cleanup), as a preparation to fix some related bug that really annoyed me. 
- due to the fact that the conditional get handling was different in all the locations, the exact behavior in these locations definitely changes in detail. (like `CommonMiddleware` not checking the the preconditions, so it was never returning a `PRECONDITION FAILED` response). 
- same for returning the original response vs generating a new one. This also was handled differently. 

Yes, I'm quite sure that due to the fact the testsuite still passes from all the previous locations, is a good indicator this is a very good change and cleanup in the code. 
It changes functionality in detail though. 

Question to me is if I should add tests for the detailed new behavior to all the places, or just test the one _handle_ method in more detail.

**Comment by timgraham** [comment]
A single set of tests seems okay to me.

**Comment by timgraham** [comment]
I don't mind merging this as-is and leaving tests to future improvements. The outstanding question I have is about renaming `handle_conditional_get()` -- do you think `get_conditional_response()` is an okay name or would you choose something else?

**Comment by timgraham** [comment]
merged in 7a40fef17ab7918cbb1ddc3ba080f42b420f7a48, thanks!

**Pull request closed without merging**
