### PR TITLE
Refs -- #18597 feat(BaseModelFormSet): Cleanup queryset prep in init and instance fetching

### PR DESCRIPTION
**Pull request by agalazis**
cleanup related to enabling custom prefetched inlines see https://code.djangoproject.com/ticket/18597

### CODE REVIEW

**Comment by agalazis** [comment]
@WhyNotHugo want to have a look?

**Review by WhyNotHugo — APPROVED** [review]
Makes sense to me. I assume the intent is to follow up with a PR that changes `_get_instance_by_queryset_index` to use a pre-fetched queryset.

**Comment by agalazis** [comment]
yes  but also allow overwriting it  in general

**Comment by WhyNotHugo** [comment]
If the intent is for it to be overridden, then I don't think the name should start with `_`. This is usually an indicator that it's a private API, not intended to be used by external consumers, nor promising any stability.

**Comment by agalazis** [comment]
I was more interested denote that they are protected and should only be used by sublasses. I was having in mind `_` for protected vs `__` for private but you know better the coding style of this project adn whether its ok to be entirely public. I will change it this afternoon thanks.

**Comment by agalazis** [comment]
fixed @WhyNotHugo  feel free to have a look

**Comment by WhyNotHugo** [comment]
Everything looks good to me, but I'm not a maintainer.

Maybe mention it [here](https://code.djangoproject.com/ticket/18597) to get more eyes on it?

**Comment by felixxm** [comment]
@agalazis Do you have time to keep working on this?

**Comment by agalazis** [comment]
Yes I ll be   back on it within next 2 weeks

**Comment by felixxm** [comment]
Closing due to inactivity.

**Pull request closed without merging**
