### PR TITLE
Fixed #32653 -- Made quoting names in the Oracle backend consistent with db_table.

### PR DESCRIPTION
**Pull request by felixxm**
ticket-32653

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Review by carltongibson — APPROVED** [review]
OK, looks good. Thanks!

**Comment by felixxm** [comment]
@carltongibson Thanks for checking :+1:

**Comment by kingbuzzman** [comment]
@felixxm can this be applied to 2.2? that’s where i found the issue

**Pull request merged**
