### PR TITLE
Refs #24125 -- Added a test to ensure that we can render the admindocs TemplateDetailView

### PR DESCRIPTION
**Pull request by kairichard**
Without throwing an exception when using more than one Engine
This adds tests for 511a53b3142551a1bc3093ed1b6655f57634f510

Refs #24125.

### CODE REVIEW

**Comment by timgraham** [comment]
Please search for "#24125" in admindocs/views.py to see the places that need to be addressed.

**Comment by kairichard** [comment]
I add new commit addressing all admindoc views

**Comment by timgraham** [comment]
Are you aiming to add support for multiple engines or only to add these tests?

**Comment by kairichard** [comment]
Actually I only wanted to add those tests as a regression. But since you it
might be a good idea to actually create another Ticket for multi-engine
support.
https://code.djangoproject.com/ticket/24957#ticket

**Comment by timgraham** [comment]
In my mind, that's why #24125 is still open.

**Comment by kairichard** [comment]
Ok, sorry, should have read more closely. So I would add a warning and
documentation if there is more than one engine.  But I think that should
not be part of this PR.
Because this one just deals with adding missings tests for changes to the
admindocs from the following commits:
https://github.com/django/django/commit/655f52491505932ef04264de2bce21a03f3a7cd0#diff-b08680e8c8451c804eb8b58220e8b3d5
and
https://github.com/django/django/commit/511a53b3142551a1bc3093ed1b6655f57634f510#diff-b08680e8c8451c804eb8b58220e8b3d5

OTOH: Would you say multiple engines should be supported?

**Comment by timgraham** [comment]
We can merge these tests and keep the ticket open to support multiple engines (if you or anyone else cares to implement that).

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
merged in 3c593ba79e5bdee46419e2aa6b14e7ce8bc01758, thanks!

**Pull request closed without merging**
