### PR TITLE
Fixed #28626 -- Dropped support for PostgreSQL 9.3.

### PR DESCRIPTION
**Pull request by timgraham**
https://code.djangoproject.com/ticket/28626

### CODE REVIEW

**Comment by timgraham** [comment]
@Mactory, can you provide a patch to address the comments in `introspection.py` from 3a5299c19cd5a38f7fa0f45ed2df7b10f0c9cf5d and d6b9aab37c41a772e5519e46b42b39958f99cadd?

**Comment by timgraham** [comment]
or @socram8888, can you help with constructing the `WITH ORDINALITY` queries?

**Comment by Mactory** [comment]
Sorry for not answering faster. I'm currently quite busy, but I'll try to look into it. Do you have an ETA until the fix has to be completed?

**Comment by timgraham** [comment]
It's not urgent.

**Comment by charettes** [comment]
@timgraham the following should do

```diff
diff --git a/django/db/backends/postgresql/introspection.py b/django/db/backends/postgresql/introspection.py
index f060546..3eff5cb 100644
--- a/django/db/backends/postgresql/introspection.py
+++ b/django/db/backends/postgresql/introspection.py
@@ -145,17 +145,12 @@ class DatabaseIntrospection(BaseDatabaseIntrospection):
         # Loop over the key table, collecting things as constraints. The column
         # array must return column names in the same order in which they were
         # created.
-        # The subquery containing generate_series can be replaced with
-        # "WITH ORDINALITY" when support for PostgreSQL 9.3 is dropped.
         cursor.execute("""
             SELECT
                 c.conname,
                 array(
                     SELECT attname
-                    FROM (
-                        SELECT unnest(c.conkey) AS colid,
-                               generate_series(1, array_length(c.conkey, 1)) AS arridx
-                    ) AS cols
+                    FROM unnest(c.conkey) WITH ORDINALITY cols(colid, arridx)
                     JOIN pg_attribute AS ca ON cols.colid = ca.attnum
                     WHERE ca.attrelid = c.conrelid
                     ORDER BY cols.arridx
@@ -183,16 +178,13 @@ class DatabaseIntrospection(BaseDatabaseIntrospection):
                 "options": options,
             }
         # Now get indexes
-        # The row_number() function for ordering the index fields can be
-        # replaced by WITH ORDINALITY in the unnest() functions when support
-        # for PostgreSQL 9.3 is dropped.
         cursor.execute("""
             SELECT
-                indexname, array_agg(attname ORDER BY rnum), indisunique, indisprimary,
-                array_agg(ordering ORDER BY rnum), amname, exprdef, s2.attoptions
+                indexname, array_agg(attname ORDER BY arridx), indisunique, indisprimary,
+                array_agg(ordering ORDER BY arridx), amname, exprdef, s2.attoptions
             FROM (
                 SELECT
-                    row_number() OVER () as rnum, c2.relname as indexname,
+                    c2.relname as indexname,
                     idx.*, attr.attname, am.amname,
                     CASE
                         WHEN idx.indexprs IS NOT NULL THEN
@@ -206,9 +198,8 @@ class DatabaseIntrospection(BaseDatabaseIntrospection):
                     END as ordering,
                     c2.reloptions as attoptions
                 FROM (
-                    SELECT
-                        *, unnest(i.indkey) as key, unnest(i.indoption) as option
-                    FROM pg_index i
+                    SELECT *
+                    FROM pg_index i, unnest(i.indkey, i.indoption) WITH ORDINALITY koi(key, option, arridx)
                 ) idx
                 LEFT JOIN pg_class c ON idx.indrelid = c.oid
                 LEFT JOIN pg_class c2 ON idx.indexrelid = c2.oid
```

**Pull request merged**
