### PR TITLE
Support conversion of an HttpResponse into a boolean

### PR DESCRIPTION
**Pull request by JasonGrace2282**
# Trac ticket number
N/A

# Branch description
Provide a concise overview of the issue or rationale behind the proposed changes.

This change allows usage in testing tools such as `pytest`. Here is a (slightly contrived) example - it should be easy to visualize checking the status codes of views from here.
```py
ok_response = HttpResponse("Request successful!", status=200)
assert ok_response
failed_response = HttpResponse(status=403)
assert failed_response  # fails in pytest
```
Based on [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status), any status code < 400 is acceptable to be considered "successful".

I would like to document this somewhere, but I'm not sure where I should document this. Any feedback would be appreciated :)

# Checklist
- [X] This PR targets the `main` branch. 
- [X] The commit message is written in past tense, mentions the ticket number, and ends with a period.
- [ ] I have checked the "Has patch" ticket flag in the Trac system.
- [X] I have added or updated relevant tests.
- [ ] I have added or updated relevant docs, including release notes if applicable.
- [ ] I have attached screenshots in both light and dark modes for any UI changes.

### CODE REVIEW

**Comment by JasonGrace2282** [comment]
Seems there are some places in the code base where `if response` is used - marking as a draft until I get the chance to fix those.

**Comment by RealOrangeOne** [comment]
This feels to me like a real foot-gun. A method which returns `Optional[HttpResponse]` and is checked using `if return_value` suddenly changes behaviour.

With that said, it appears `requests` implements this API: https://github.com/psf/requests/blob/79b74ef704dc0d804937c0d015c5e9c3b02b79bd/src/requests/models.py#L730-L738.

**Comment by JasonGrace2282** [comment]
Yes, I could definitely see this being a breaking change. If it's too big of a breaking change, it's not a big deal to call it off.
However, I still feel like this would be an improvement and something that could be added in 6.0.0.

**Comment by felixxm** [comment]
TBH, the proposed behavior seems really unexpected, confusing, and backward incompatible. I don't think it's worth adding. You can always start a new discussion on the [Django Forum](https://forum.djangoproject.com/), if you don't agree.

**Pull request closed without merging**
