### PR TITLE
Fixed #31493 -- Replaced var with const and let keywords in JavaScript.

### PR DESCRIPTION
**Pull request by jdufresne**
The unused fallback of globals.django in jquery.init.js was removed. It
is always included before jsi18n-mocks.test.js and it always sets the
global value.

https://code.djangoproject.com/ticket/31493

### CODE REVIEW

**Comment by adamchainz** [comment]
Seems cromulent to me. I'm not familar with the test coverage - is there anything that isn't covered with tests that needs manual checking?

**Comment by pope1ni** [comment]
buildbot, test on selenium.

**Comment by pope1ni** [comment]
@adamchainz I just triggered the selenium tests, as that should verify that some of the behaviour not tested in the javascript unit tests works as expected. Other than that, this seems straightforward.

**Comment by pope1ni** [comment]
buildbot, test on selenium.

**Comment by pope1ni** [comment]
buildbot, test on selenium.

**Comment by pope1ni** [comment]
Well, I think things seem fine. (After three runs, there have been three different intermittent failures/timeouts in the selenium tests.)

**Comment by adamchainz** [comment]
Oh, Selenium.

**Comment by jdufresne** [comment]
buildbot, test on selenium.

**Comment by jdufresne** [comment]
Some of these tests have failed intermittently in the past as well and I'm unable to reliable make them fail locally to debug them.

**Comment by jdufresne** [comment]
I rebased to resolve conflicts and ran `compress.py` to rebuild minified files.

The `compress.py` script now has the argument `--language_out=ECMASCRIPT_2015` so google-closure-compiler keeps the `const` and `let` keywords in the output.

**Comment by jdufresne** [comment]
buildbot, test on selenium.

**Comment by adamchainz** [comment]
@jdufresne this conflicts with the admin `change_form.js` now 😉

**Comment by carltongibson** [comment]
That's my fault. I've done it in the wrong order. 🙂 (This one was harder.) 

I can update when reviewing if you don't get to it Jon.

**Comment by jdufresne** [comment]
Rebased :slightly_smiling_face:

**Comment by jdufresne** [comment]
buildbot, test on selenium.

**Comment by jdufresne** [comment]
I added a 2nd commit that removes the IIFEs with an plain block. Now that all variables are defined with block scoping, a block is sufficient to ensure the global namespace is not polluted.

This also means the `'use strict';` directive can no longer live at the top of the IIFE, so it was changed to global strict mode.

**Comment by jdufresne** [comment]
buildbot, test on selenium.

**Comment by carltongibson** [comment]
buildbot, test on selenium.

**Pull request merged**
