### PR TITLE
Fixed #29788 -- Added support for Oracle Managed File (OMF) tablespaces.

### PR DESCRIPTION
**Pull request by felixxm**
Ticket [29788](https://code.djangoproject.com/ticket/29788).

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
@VackarAfzal Does this patch work for you? For me it works in both cases UMF and OMF.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by VackarAfzal** [comment]
Looks good!

**Pull request merged**
