### PR TITLE
Fixed #26369 -- Default formfield callback override

### PR DESCRIPTION
**Pull request by jpic**
https://code.djangoproject.com/ticket/26369

### CODE REVIEW

**Comment by timgraham** [comment]
I didn't see any consensus on the mailing list about adding a new setting.

**Comment by jpic** [comment]
Started thread here: https://groups.google.com/forum/#!topic/django-developers/TblESVmxGfw

**Comment by adamchainz** [comment]
I left my comment the [mailing list thread](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/django-developers/TblESVmxGfw/JJSK_f4wEAAJ) of this already. Basically I don't think this is necessary.

However if it does get added, I think a callback is a very restricted and un-django-ish way of doing this. It would be better to define a signal that gets called when a modelform constructs the form field for a model field. Any listeners to this signal could return a new form field to replace the default. This would allow multiple listeners without adding a new setting.

**Comment by adamchainz** [comment]
(Can you remove the '@adamchainz' from your commit title please? GitHub emails me about each time you push a new one after amending/rebasing because it gets a new commit SHA.)

**Comment by jpic** [comment]
Ooops, absolutely !

**Comment by jpic** [comment]
Adam reported on the ML that this doesn't work when registering signals in the advised place, apps.py

I don't want to maintain this patch anymore and would instead focus into just making default form fields really usable out of the box by marrying a JS framework.

**Comment by jpic** [comment]
This has been implemented in a [third party extension](https://github.com/yourlabs/djhacker)

**Pull request closed without merging**
