### PR TITLE
Fixed #29338 -- Allowed using union query in Subquery

### PR DESCRIPTION
**Pull request by cansarigol**
Ticket: [#29338](https://code.djangoproject.com/ticket/29338)

### CODE REVIEW

**Comment by EugeneKovalev** [comment]
hi @cansarigol thank you for the PR. Unfortunately, it won't work for cases with OuterRefs in multiple parts of UNION.

I am testing it with:

```
a = ModelA.objects.annotate(
        foo=Subquery(
            ModelB.objects.filter(
                list_id=OuterRef('list_id')
            ).values('name').distinct().union(
                ModelC.objects.filter(
                    modela_id=OuterRef('id')
                ).values('name').distinct()
            )
        )
    ).values('foo')
```

The thing is that `self.query.where.children` contains WhereNodes only from the first union compiler
```
ModelB.objects.filter(
                list_id=OuterRef('list_id')
            ).values('name').distinct()
```.

modela_id=OuterRef('id')` disappears. You do not get it from anywhere. **That's the point #1** 
 
Moreover, when iteration `for compiler in compilers:` gets the second compiler aka 
```
ModelC.objects.filter(
                    modela_id=OuterRef('id')
                ).values('name').distinct()
```
you do this `compiler.query.where.children = exact_children + related_exacts`
As I mentioned before, related_exacts contain only list_id=OuterRef('list_id'). So the problem is that you get WhereNodes from the 1st compiler to the 2nd compiler as well. **That's the point #2**

Any thoughts?

**Comment by EugeneKovalev** [comment]
@cansarigol @auvipy 
I created a new PR. https://github.com/django/django/pull/11339 Please, have a look. What do you think guys?

@cansarigol as I understand, you try to change the code where it is not supposed to be changed. As a result, the fix is very large and not understandable easily. Correct me if I am wrong.

Thanks!

**Comment by cansarigol** [comment]
Thanks, @EugeneKovalev for your review. You are right my code is complicated and large. I'm not happy either. I couldn't find a solution on how to narrow it. By the way, @felixxm already answered a solution.

IMO your test query approach is wrong. After union, the result will have just one column name as `list_id`. Would it be nicer like this:
```
a = ModelA.objects.annotate(
        foo=Subquery(
                ModelB.objects.values('list_id', 'name').distinct().union(
                    ModelC.objects.values('id', 'name').distinct()
                ).filter(list_id=OuterRef('id')).values('name')[:1]
            , output_field=models.IntegerField())
        ).values('foo')
```

**Comment by felixxm** [comment]
@cansarigol Please take into account that as [​​per the documentation](https://docs.djangoproject.com/en/stable/ref/models/querysets/#union): _"only LIMIT, OFFSET, COUNT(*), ORDER BY, and specifying columns (i.e. slicing, count(), order_by(), and values()/values_list()) are allowed on the resulting QuerySet."_, so you cannot `filter()` on combined queries, e.g. `qs1.union(q2).filter(...)` will not work.

**Comment by cansarigol** [comment]
I know but this would be a development subject and I would document it. I thought like this.

**Comment by felixxm** [comment]
This ticket is not about adding a `filter()` support to combined queries, it is about using combined queries in `Subquery()`. We shouldn't mix that.

**Pull request closed without merging**
