### PR TITLE
Fixed #26593 -- Leveraged deferrable_sql() in SchemaEditor

### PR DESCRIPTION
**Pull request by MarkusH**

### CODE REVIEW

**Comment by charettes** [comment]
LGTM, was it related to a ticket? I remember someone raising a related concern somewhere (IRC, @developers or Trac).

**Comment by MarkusH** [comment]
No ticket yet. Someone was asking on IRC yesterday how to make the addition of FKs not deferrable and I stumbled over `connection.ops.deferrable_sql()` being unused. Wrote it down before I forgot it.

**Comment by charettes** [comment]
As it's not completely trivial I would create a ticket for keep track of the motivation behind the change (a django-user on IRC).

**Comment by MarkusH** [comment]
There we go, @charettes: https://code.djangoproject.com/ticket/26593

**Pull request merged**
