### PR TITLE
Fixed #27653 -- Improved Ukrainian locale formats.

### PR DESCRIPTION
**Pull request by illia-v**

### CODE REVIEW

**Comment by timgraham** [comment]
Thanks, could you ask a Ukrainian colleague to review the patch?

**Comment by claudep** [comment]
Maybe @sorenabell?

**Comment by sorenabell** [comment]
Looks good. The main Ukrainian pecularity - datetime order _date.month.year_ is preserved.

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by claudep** [comment]
Thanks Zoriana for the prompt review!

**Comment by sorenabell** [comment]
Always happy to help)

**Pull request merged**
