### PR TITLE
WIP Add failing test case for admin filter_horizontal refresh data loss.

### PR DESCRIPTION
**Pull request by benkonrath**
This is test that demonstrates the data loss problem from Django Trac issue 22955.

https://code.djangoproject.com/ticket/22955

### CODE REVIEW

**Comment by benkonrath** [comment]
Hmmm. This test fails on Firefox but passes on Chrome when the Selenium tests are enabled. I guess the Selenium tests aren't automatically run by the CI server. Is there a way to enable the Selenium tests for specific pull requests?

**Comment by timgraham** [comment]
buildbot, test on selenium.

**Comment by benkonrath** [comment]
Looks like the Firefox driver isn't installed and the test specifically demonstrates an issue with Firefox.

http://djangoci.com/job/pull-requests-selenium/database=sqlite3,python=python2.7/12/console

Is this a bug in the CI server?

**Comment by timgraham** [comment]
No, we're currently only running the selenium tests with Chrome as there have been issues with Firefox on the CI servers. I'm checking if these issues still exist.

**Comment by timgraham** [comment]
buildbot, test on selenium.

**Comment by charettes** [comment]
FWIW I've had issues with FF and selenium in another project and I had to update it to the latest selenium release to fix it.

**Comment by timgraham** [comment]
It worked and the test failed as expected.

**Comment by timgraham** [comment]
Do you plan to attempt a fix? If not, we can close this PR in the meantime.

**Comment by benkonrath** [comment]
I am planning to tackle this but I won't have time for a few weeks. I'll close this for now. I'll reopen or submit a new PR when I'm actively working on this again. Thanks for checking in.

**Pull request closed without merging**
