### PR TITLE
Fixed #32034 -- Removed redundant get_app_config() call in AdminSite.app_index.

### PR DESCRIPTION
**Pull request by rsalmaso**
Ticket https://code.djangoproject.com/ticket/32034

### CODE REVIEW

**Comment by felixxm** [comment]
@rsalmaso Thanks :+1: Please add in a separate commit tests for `title`. `admin_views.tests.AdminViewBasicTest` looks like a good place.

**Comment by felixxm** [comment]
@rsalmaso Thanks :+1:

**Comment by rsalmaso** [comment]
@felixxm thanks
Do you think it is worth to backport to django 3.1/2.2?

**Comment by felixxm** [comment]
We don't backport cleanups.

**Pull request merged**
