### PR TITLE
[1.7.x] Fixed #24337 - Added stronger documentation warning about automatic fake-initial.

### PR DESCRIPTION
**Pull request by carljm**
https://code.djangoproject.com/ticket/24337

### CODE REVIEW

**Comment by carljm** [comment]
@timgraham I'm assuming that when patching the docs for 1.7.x, I should ignore the isort failure.

**Comment by timgraham** [comment]
Yes, and the new sentence looks good.

**Comment by MarkusH** [comment]
LGTM

**Comment by carljm** [comment]
Looks like 1.7.x is broken on spatialite -- ignoring that too.

**Pull request merged**
