### PR TITLE
Refs #17235 -- Made MultiPartParser leave request.FILES immutable

### PR DESCRIPTION
**Pull request by vinayinvicible**
Extended on top of @hirokiky's patch

Ref: https://code.djangoproject.com/ticket/17235

### CODE REVIEW

**Comment by claudep** [comment]
I didn't follow this closely, but did you try adding a `mutable` argument to `MultiValueDict`. Having the name `Immutable` in a class name whose instances can be mutable depending on a variable looks a bit weird.

**Comment by vinayinvicible** [comment]
Initial suggestions and patch were to have a new class rather than changing `MultiValueDict`.
Having the ability to toggle mutability on seemingly immutable class does seem weird.
We can either add functionality to `MultiValueDict` or give a better name to the new class.

**Comment by apollo13** [comment]
@vinayinvicible Can you check where `MultiValueDict` is used throughout Django. This might make it easier to decide on whether or not to add the `mutable` flag to `MultiValueDict` itself.

Since `QueryDict` inherits `MultiValueDict` dict and also adds it's own mutability to it, it might be worth checking if `QueryDict` couldn't not inherit the new class then…

**Comment by felixxm** [comment]
Closing due to inactivity and lack of follow up.

**Pull request closed without merging**
