### PR TITLE
Refs #34383 -- Corrected margins in admin fieldsets with multiple fields on the same line on small screens.

### PR DESCRIPTION
**Pull request by felixxm**
Regression in d687febce5868545f99974d2499a91f81a32fef5.

Before:

before

After:

after

### CODE REVIEW

**Comment by felixxm** [comment]
JavaScript tests failure is not related, see #16700.

**Review by knyghty — APPROVED** [review]
LGTM! 💚

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Review by smithdc1 — APPROVED** [review]
Hmm. Looks like we should allow the accessibility team to also approve mergers PRs.

**Comment by felixxm** [comment]
Thanks both for checking :+1:

**Comment by felixxm** [comment]
buildbot, test this please.

**Comment by felixxm** [comment]
buildbot, test this please.

**Pull request merged**
