### PR TITLE
Improved style of n-tuple wording in docs and comments.

### PR DESCRIPTION
**Pull request by ngnpope**
Following on from https://github.com/django/django/pull/16943#discussion_r1232751444.

### CODE REVIEW

**Comment by felixxm** [comment]
:thinking: Is it worth changing? I don't see a difference and it creates extra work for documentation translators.

**Comment by smithdc1** [comment]
AP style guide says to spell out numbers one through nine, in general. Source:

https://twitter.com/APStylebook/status/745342288302321665?t=FZilLqGno5kvfTGOo4kmGA&s=19

**Comment by ngnpope** [comment]
I had wondered, but then when attempting to look up "two-tuple" or "three-tuple" there are not really any decent sources that phrase it in this way. Everything typically prefers "2-tuple", "3-tuple", etc.

There are only a handful of cases so I don't think it'll be onerous. Excluding docstrings it amounts to 13 changes over 11 lines.

**Comment by ngnpope** [comment]
> AP style guide says to spell out numbers one through nine, in general. Source:
> 
> https://twitter.com/APStylebook/status/745342288302321665?t=FZilLqGno5kvfTGOo4kmGA&s=19

I think this is a case of noting the "-- with many exceptions" bit at the end of that... Also, looking at the article on Wikipedia for [Tuple](https://en.wikipedia.org/wiki/Tuple), there are no cases of spelling it out...

**Comment by ngnpope** [comment]
Also probably clearer and less ambiguous as a style in case you ever had something like "A list containing two 2-tuples" which is easier to grasp than "A list containing two two-tuples" 😆

**Comment by shangxiao** [comment]
I'm with Nick on this :P  2-tuple seems to be more common and for me at least easier to grok than "two-tuple".

Sounds like the AP guide recommendation is for numbers used in isolation? 🤷‍♂️

**Review by nessita — APPROVED** [review]
I'm also +1 to this change. The literature that we followed at the university, while studying computer science, used N-tuple as style. I really had to re-read the sentence using "two-tuple" to understand what it meant!

Also, a quick look at the Python docs also uses N-tuple (2-tuple, etc).

**Review by felixxm — APPROVED** [review]
Persuaded.

**Pull request merged**
