### PR TITLE
Renamed docs/README to README.rst.

### PR DESCRIPTION
**Pull request by Someoneece**
Changed docs/REAME to docs/README.md to make a beautiful readme file

### CODE REVIEW

**Comment by felixxm** [comment]
@Someoneece Thanks :+1: We should rename to `docs/README.rst` to keep the same format for all `README` files.

**Comment by felixxm** [comment]
@Someoneece Welcome aboard :boat:

**Comment by felixxm** [comment]
Merged in 6c9c823e7a58827af9f3127d884aef4ac0a7251e.

**Comment by Someoneece** [comment]
Thanks for accepting my pull request

**Pull request closed without merging**
