### PR TITLE
Refs #27468 - Changed default Signer algorithm to SHA-256.

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
Some more tests and docs added. Note that I'm not attached to using the `blake2s` algorithm. It's just a proposal and I'd be fine reverting to `sha256` if preferred.

**Comment by felixxm** [comment]
@ubernostrum James, Can I ask for your opinion?

**Comment by pope1ni** [comment]
Perhaps this may help: https://research.kudelskisecurity.com/2017/03/06/why-replace-sha-1-with-blake2/

I have some questions:

1. Why not use the faster `blake2b` over `blake2s`? Do we still care about 32-bit platforms?
2. If we go for SHA-2 (`sha256`) over BLAKE2, is that enough?
    - It is over three years since moving to SHA-2 was suggested.
    - It looks as though progress is being made toward attacking SHA-2.
    - Should we use SHA-3 (`sha3_256`)? It is a bit slower, but may avoid us doing this again in a couple of years.
 
It is a shame that BLAKE3 isn't quite ready yet as it looks interesting.

Various useful links:
- https://blake2.net/
- https://www.csoonline.com/article/3256088/why-arent-we-using-sha3.html
- https://bugs.python.org/issue39298
- https://github.com/BLAKE3-team/BLAKE3

P.S. The ticket reference in the commit message should be 27468, not 27463!

**Comment by PaulMcMillan** [comment]
From a conservative security standpoint, SHA2 is probably the right choice at this time.

We're using it in the HMAC construction, which practically tends to make attacks much harder (IIRC, even HMAC-MD5 is still not shown fully broken). SHA2 is extremely well scrutinized, has well-understood performance properties, and is widely accepted and supported. I have no particular feelings about SHA2 vs. SHA3 other than the potential performance implications. I'm comfortable with the security margin on HMAC-SHA256 for the foreseeable future.

While I agree that blake2 is definitely faster, and probably plenty secure, choices like this aren't the place to be pushing that selection envelope. It hasn't had the same level of scrutiny, and it won't get it. Customers are of course always capable of changing the algo, but it's probably better to make a conservative choice out of the box.

Do we have any evidence that the performance of this function has an impact on real-world use cases? I would expect all these choices to be indistinguishable when signing less than hundreds of megabytes.

If we do end up using blake2 as this PR suggests, we'll probably get pushback about using it with the hmac construction rather than the native keyed hash feature.

**Comment by claudep** [comment]
Thanks Paul, that makes sense. Just switched the patch to sha256.
Nick, thanks for your input, too.

**Comment by claudep** [comment]
Isn't this PR now ready for a final review by mergers?

**Comment by felixxm** [comment]
> Isn't this PR now ready for a final review by mergers?

I was waiting for James' opinion.

**Comment by claudep** [comment]
I see, but after one month, shouldn't we going forward, considering we got feedback from Paul?

**Comment by felixxm** [comment]
@claudep Agreed, it's on my list for this week.

**Comment by jaylynnconley12** [comment]
wow

**Comment by felixxm** [comment]
@claudep Thanks :+1: I pushed minor edits and moved release notes to the "Security" section.

**Comment by collinanderson** [comment]
I wouldn't mind having a longer removal timeline (maybe 5.0). Probably not worth holding this up though.

**Comment by felixxm** [comment]
We made [a set of related changes](https://docs.djangoproject.com/en/dev/internals/deprecation/#deprecation-removed-in-4-0) and decided to keep the standard deprecation period. I think it's enough.

**Comment by felixxm** [comment]
Django 3.2 is LTS, so it will be supported until April 2024.

**Pull request merged**
