### PR TITLE
Add missing closing quotation marks

### PR DESCRIPTION
**Pull request by PeterW-LWL**

### CODE REVIEW

**Comment by felixxm** [comment]
Thanks. Ticket is not required for a typo.

**Comment by carltongibson** [comment]
> Ticket is not required...

No, sure. I was just wondering if there was one, so I could tick it off. (If not, no worries)

**Comment by PeterW-LWL** [comment]
I just made a quick fix as described in the documented [here](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/submitting-patches/#typo-fixes-and-trivial-documentation-changes).

**Comment by carltongibson** [comment]
OK. Thanks @PeterW-LWL.

**Pull request merged**
