### PR TITLE
Stopped deleting from the geometry_columns view on PostGIS

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by timgraham** [comment]
Could you add to the commit message some explanation or reference to the original ticket that added this?

**Comment by claudep** [comment]
Sure, something like: "On PostGIS < 2, geometry_columns was a table which should be manually maintained."

**Comment by timgraham** [comment]
Ah okay, "geometry_columns is a table that was manually maintained."

**Comment by claudep** [comment]
"On PostGIS < 2, geometry_columns was a table that was manually maintained. It's a view on PostGIS 2."

**Comment by timgraham** [comment]
It still is a table on PostGIS < 2 hence when I chose present tense but I understand what you wrote also.

**Comment by claudep** [comment]
Ah OK, I see..

**Comment by claudep** [comment]
Merged in 9715b99f91

**Pull request closed without merging**
