### PR TITLE
Fixed #26632 -- Skip admin list_display_links checks if get_list_display is defined.

### PR DESCRIPTION
**Pull request by desecho**

### CODE REVIEW

**Comment by charettes** [comment]
What about adding a hint to the error that you should override `get_list_display_link()` to return dynamic results if `get_list_display()` was overrode?

**Comment by desecho** [comment]
@charettes Currently, I silence all errors if get_list_display() is overridden. Do you want to bring the errors back or create a new error or else?

**Comment by timgraham** [comment]
@charettes, I'm also not certain what you're suggesting.

**Comment by charettes** [comment]
What I was trying to explain is that in the case of static mismatch between `list_display` and `list_display_links` the error raised should _hint_ at overriding `get_list_display_links` instead of defining them statically using `list_display_links` if `get_list_display` has been overridden.

For example, in the case described on the ticket

```python
class QuestionAdmin(admin.ModelAdmin):
    list_display_links = ['id', 'pub_date', 'question_text',]

    def get_list_display(self, request):
        return ['id', 'pub_date', 'question_text']
```

The error could be

```python
hint = None
if obj.get_list_display.__code__ is not ModelAdmin.get_list_display.__code__:
    # XXX: The wording could be adjusted here.
    hint = "Override %s.get_list_display_links() to return dynamic results." % (
        obj.__class__.__name__,
    )
checks.Error(
    "The value of '%s' refers to '%s', which is not defined in 'list_display'." % (
     label, field_name
    ),
    obj=obj.__class__,
    id='admin.E111',
    hint=hint,
)
```

I'm just thinking that this could prevent users from returning a dynamic set of list fields that don't include all of the statically defined `list_display_links`.

I wouldn't oppose to disable the check altogether instead like @desecho proposed if you think it isn't worth the effort or could be source of false positives. We'd just have to make sure not to skip the `admin.E110` check and add a note that `obj.get_list_display.__func__ is ModelAdmin.get_list_display` should be used when moving to Python 3.

**Comment by timgraham** [comment]
> I'm just thinking that this could prevent users from returning a dynamic set of list fields that don't include all of the statically defined list_display_links.

I don't see a problem with `get_list_display()` returning a subset of `list_display_links` like this:
```python
class QuestionAdmin(admin.ModelAdmin):
    list_display_links = ['id', 'pub_date', 'question_text',]

    def get_list_display(self, request):
        if request.user.is_superuser:
            return self.list_display_links
        return ['id', 'pub_date']
```
or did I miss what you meant? My understanding of your proposal is that this would continue to raise an error.

**Comment by charettes** [comment]
I personally find it odd that `list_display_links` could end up being a superset of `list_display` for but it looks like the current implementation handles that fine so feel free to ignore my previous concerns.

**Comment by timgraham** [comment]
Thanks Simon, I updated the patch for your other comments.

**Pull request merged**
