### PR TITLE
added encode and decode methods to django cache session backend. ticket #23764

### PR DESCRIPTION
**Pull request by mcrowson**
Merged cleanly locally

### CODE REVIEW

**Comment by mcrowson** [comment]
ticket #23764

**Comment by charettes** [comment]
Isn't this going to break when trying to decode already existing sessions that have not been encoded?

**Comment by mcrowson** [comment]
looking at the try within the decode, I think it would just return an empty session, essentially logging users out. After they log in again their new sessions would be encoded.

**Comment by timgraham** [comment]
I think forcing all users to log out when Django is upgraded isn't acceptable. We've had similar fixes in the past where we've had to add a workaround to prevent it.

**Pull request closed without merging**
