### PR TITLE
Minor clean-up

### PR DESCRIPTION
**Pull request by pope1ni**
Hi @timgraham,

These commits just have some very minor documentation fixes or tweaks, e.g. to use a constant, so I wasn't sure that they warranted a ticket. Please let me know if any of them do...

Thanks!

### CODE REVIEW

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
buildbot, test this please.

**Comment by timgraham** [comment]
I'm not if the `LookupError` change is an improvement. It seems to make the code less explicit, especially in cases like `numpy` where it's raising the more specific exceptions.

Other commits merged in 81463ce0a147dbbc8a0c7d2ae0d5ca02cce97984, a346a88d46e420d21374377c2027f78c8989503b, and f1664a27345d09b91892cbaa46a7ab73bd62b219. For future reference, you might like to note our [commit message guidelines](https://docs.djangoproject.com/en/dev/internals/contributing/committing-code/#committing-guidelines).

**Comment by pope1ni** [comment]
Thanks Tim.

Will bear the commit messages in mind next time. Don't worry about the `LookupError` change if you feel it is less clear.

**Pull request closed without merging**
