### PR TITLE
Added contributor guidelines for performance optimizations.

### PR DESCRIPTION
**Pull request by sarahboyce**
# Branch description

This is following from a discussion within https://github.com/django/django/pull/18322

- Probably want to mention "trade-offs" and "discretion"
- I wouldn't describe myself as a performance person, if we want to give specific performance benchmarking recommendations beyond django-asv, would appreciate help in wording this
- Unsure if I should separate the advice between the performance regression and "suggested performance optimization" (a performance regression could perhaps be treated as a "bug" for example)
- Might make sense to say that test coverage of the code being optimized is a pre-requisite to accepting a performance optimization 🤔

### CODE REVIEW

**Comment by smithdc1** [comment]
Hi Sarah -- I think this makes sense and is just the right balance. 

I was thinking originally that `django-asv` is just one way and that there are less onerous approaches that we could point to. However, there are so many that we couldn't document them so the generic "show us your steps" guidance seems the best approach.

**Comment by sarahboyce** [comment]
> Hi Sarah -- I think this makes sense and is just the right balance.

In that case, marking it ready for review 👍

**Review by claudep — APPROVED** [review]
Thanks, looks good!

**Review by hramezani — APPROVED** [review]

**Comment by sarahboyce** [comment]
Thank you all ⭐

**Pull request merged**
