### PR TITLE
Fixed 32661 -- Improved logic for datetime.time objects in timezone.i…

### PR DESCRIPTION
**Pull request by abhiabhi94**
…s_naive() and timezone.is_aware()

Co-authored-by: ikeren <itay@demisto.com>

Thanks Armin Stepanjan for the report.

### CODE REVIEW

**Comment by abhiabhi94** [comment]
I think the two functions `timezone.is_naive()` and `timezone.is_aware()` return values, which are complements of each other. Please let me know if I'm wrong here.

I have used this logic to avoid duplication in code. In my opinion, maybe we can start a deprecating cycle for one, asking people to use the other, but it will require changes in our codebase too.

**Comment by abhiabhi94** [comment]
buildbot, test on oracle

**Review by felixxm — COMMENTED** [review]
@abhiabhi94 Thanks for this patch :+1: 

All new tests work without the patch, because this issue is more tricky and it is not `TimeField`-specific. `tzinfo` subclasses may not specify the UTC offset, e.g. `pytz.timezone('Europe/Paris')`, in such cases we need to also check `tzinfo`.

We should move tests with `EAT` to a separate commit as an extra test coverage. I would also add regression tests: `test_is_aware_utcoffset_unknown`, `test_is_naive_utcoffset_unknown`, and extra assertions to the `test_aware_datetime_unsupported` and `test_aware_time_unsupported` for time zones from  `get_timezones('Europe/Paris')`.

**Comment by felixxm** [comment]
>  In my opinion, maybe we can start a deprecating cycle for one, asking people to use the other, but it will require changes in our codebase too.

I don't see a reason to deprecate any of them.

**Comment by felixxm** [comment]
Regression in 432678dbc1dd4f80203468d83bb0eb6c20ed5247. @aaugustin, can you take a look?

We can basically restore `tzinfo is not None` check, or treat `tzinfo` without the UTC offset as not a proper `datetime.tzinfo` and mark this ticket as _"invalid"_ 🤔.

**Comment by abhiabhi94** [comment]
@felixxm Thanks for the review

> I don't see a reason to deprecate any of them.

If an object is timezone aware, it won't be naive, and vice-versa? In case my previous statement is correct, I don't think we need a separate function for the two cases. We can probably negate the output of one in case we need the other.

> All new tests work without the patch, because this issue is more tricky and it is not TimeField-specific. tzinfo subclasses may not specify the UTC offset, e.g. pytz.timezone('Europe/Paris'), in such cases we need to also check tzinfo.
We should move tests with EAT to a separate commit as an extra test coverage. I would also add regression tests: test_is_aware_utcoffset_unknown, test_is_naive_utcoffset_unknown, and extra assertions to the test_aware_datetime_unsupported and test_aware_time_unsupported for time zones from get_timezones('Europe/Paris').

I have updated the patch with these changes. Some tests in the `humanize_tests` package seem to break after this change. I haven't investigated much into it as of now. Will try to look more into it soon.

**Comment by felixxm** [comment]
> If an object is timezone aware, it won't be naive, and vice-versa? In case my previous statement is correct, I don't think we need a separate function for the two cases. We can probably negate the output of one in case we need the other.

Yes, but it is not a reason to deprecate and remove documented API.

**Comment by abhiabhi94** [comment]
> Some tests in the humanize_tests package seem to break after this change.

Fixed

**Comment by aaugustin** [comment]
Hello,

This code has been working well for over 10 years so let's be careful. Here's my analysis. 

The [docs](https://docs.python.org/3/library/datetime.html#determining-if-an-object-is-aware-or-naive) say:

> A datetime object d is aware if both of the following hold:
>
> 1. d.tzinfo is not None
> 2. d.tzinfo.utcoffset(d) does not return None
>
> Otherwise, d is naive.

This hasn't changed this Python 2.7. (I didn't check further back.)

This was explicitly the implementation before 432678dbc1dd4f80203468d83bb0eb6c20ed5247.

Also, the documentation of datetime.utcoffset, `value.utcoffset()` literally implemented as `None if value.tzinfo is None else value.tzinfo.utcoffset(value)`.

As a consequence of the above, each of the following propositions are strictly equivalent:

```python
# `value` is naive

# not (`value` is aware)  # by definition of a naive datetime

# substitute definition of an aware datetime
not (value.tzinfo is not None and value.tzinfo.utcoffset(value) is not None)

# simplify boolean logic
value.tzinfo is None or value.tzinfo.utcoffset(value) is None

# express the shortcut logic of the `or` operation in Python
True if value.tzinfo is None else (value.tzinfo.utcoffset(value) is None)

# replace `True` by a tautology
(None is None) if value.tzinfo is None else (value.tzinfo.utcoffset(value) is None)

# factor out the the `is None` test
(None if value.tzinfo is None else value.tzinfo.utcoffset(value)) is None

# substitute definition of value.utcoffset()
value.utcoffset() is None
```

Therefore I believe the change proposed here is wrong for at least three reasons:

- Any logic changes in this area will diverge from the definition in the Python docs.
- The proposed logic is redundant — if `value.tzinfo is None`, then `value.utcoffset() is None`: this is the first six words of the documentation of datetime.utcoffset: "If tzinfo is None, returns None"; I don't see how adding this redundant logic is an improvement.
- The proposed logic is wrong — if you wanted to go back to the previous implementation, you should use `and` instead of `or` in `is_naive`.

Finally, I believe that have two one-liner convenience functions implemented as `value.utcoffset() is None` and `value.utcoffset() is not None` is fine. I don't see the need for adding a level of indirection and the overhead of a function call here.

**Comment by aaugustin** [comment]
I saw this PR was intended for https://code.djangoproject.com/ticket/32661 but I don't think it's the right level for fixing this issue. is_naive/is_aware are explicitly documented to work with `datetime.datetime` objects. If you give them another type of object, anything could happen. If Django calls them on `datetime.time` object, that's the problem that needs fixing.

(Generally speaking aware `datetime.time` objects are an aberration. There are no circumstances where it makes sense to use them. There's only two ways: 1. aware datetime 2. date + time + tzinfo as three separate pieces of information.)

**Comment by felixxm** [comment]
@aaugustin Thanks :+1: This issue is not with related with calling `is_naive()`/`is_aware()` with `datetime.time` objects, but with handling `tzinfo` which don't declare `utcoffset`. I agree that we should treat them as naive.

**Comment by abhiabhi94** [comment]
Thanks Aymeric for the detailed explanations.

@felixxm Should the additional test for saving timezone aware time objects on unsupported database be made in a separate pull-request or should i create a separate ticket for it first? I'm writing this about e1357dcffa8ed1f30503513826f45b118d5d090e

**Comment by felixxm** [comment]
@abhiabhi94 I moved extra test coverage to the #14600.

**Pull request closed without merging**
