### PR TITLE
Fixed #26623 -- Add support for DJANGO_REMOTE_USER_VAR.

### PR DESCRIPTION
**Pull request by adelton**

### CODE REVIEW

**Comment by adelton** [comment]
Rebased on master (-> 783e564670351cd49c71b3a6f7ecede5702a729e) to resolve merge conflict due to 9baf692a58de78dba13aa582098781675367c329..

**Comment by adelton** [comment]
Rebase on latest master (-> ea30e7ca34994facd15ed04e64952c88f3ba9735).

**Comment by adelton** [comment]
Moved the change documentation to 1.11 release notes (-> 6b467ff30e9ec839df9546f48254726c75055401).

**Comment by timgraham** [comment]
Closing per ticket.

**Comment by adelton** [comment]
For the record, `django-identity-external` in https://github.com/adelton/django-identity-external / https://pypi.python.org/pypi/django-identity-external implements this functionality in external middleware.

**Pull request closed without merging**
