### PR TITLE
Moved RequestSite import to the toplevel.

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
Since running on Python 3.9, I've seen several errors like `cannot import name 'RequestSite' from partially initialized module 'django.contrib.sites.requests'`. Hopefully this will fix this!

**Review by blockchainGuru1018 — APPROVED** [review]

**Comment by blockchainGuru1018** [comment]
it's looks ready to merge to main branch

**Comment by felixxm** [comment]
@claudep Thanks :+1:

**Comment by claudep** [comment]
I'm rather annoyed with several projects with this error (and a bit surprised there are not more reports about this).
@felixxm, do you think pushing it to 4.0.x would be an option?

**Comment by felixxm** [comment]
> I'm rather annoyed with several projects with this error (and a bit surprised there are not more reports about this). @felixxm, do you think pushing it to 4.0.x would be an option?

For me it's a cleanup, so theoretically it doesn't qualify. Can you share a project that reproduces this issue?

**Comment by claudep** [comment]
That's the problem, I cannot reproduce it at will, as it is probably a race condition issue. It may be related to django-ratelimit usage (see the traceback in https://dpaste.org/pdeF). But you can forget that, it's probably something I'm doing wrong somewhere.

**Comment by kezabelle** [comment]
@claudep is the problem occurring _on_ 4.0/master, or on 3.2 but newly using py3.9? Do you have any [callable rates](https://django-ratelimit.readthedocs.io/en/latest/rates.html#callables) or any fancy [RATELIMIT_VIEW](https://django-ratelimit.readthedocs.io/en/latest/settings.html#ratelimit-view) that could be at play?

**Comment by claudep** [comment]
On 3.2 but newly using py3.9 (after Debian 10 to 11 migration).
My usage of the ratelimit decorator:
```
    path('login/', ratelimit(key='ip', rate='5/3m', method=ratelimit.UNSAFE, block=True)(
        views.LoginView.as_view()
    ), name='login'),
```

**Comment by kezabelle** [comment]
Hmmm. Upside, it happening on 3.2 means it's not another occurrence of [ticket 33107](https://code.djangoproject.com/ticket/33107) via [ticket 33099](https://code.djangoproject.com/ticket/33099). Downside is ... your decorator usage doesn't look particularly out of the ordinary, and none of the `import` related changes in the [py3.9 release notes](https://docs.python.org/3/whatsnew/3.9.html) _sound_ like they'd be relevant (though `importlib.util.resolve_name` does have a change which is related to invalid relative imports, changing the `ValueError` to `ImportError`), so all we have to go on is the stacktrace, which unfortunately looks to only be a symptom rather than surfacing the cause, where-ever & whatever that might be :(

Possibly you could use `python -m pdb ...` to get into a debug REPL when the exception is thrown, and inspect things like `sys.modules`, but I'm not entirely sure what you'd be able to glean. Another option might be to trace open syscalls (that's `strace` on linux I think? On OSX I only have `opensnoop`) for the process, looking for any touching `contrib/sites` and working back from there to presumably locate the first callers, if any...

**Comment by claudep** [comment]
Thanks a lot @kezabelle for your help on this. If I had a mean to reproduce it, I would certainly try to follow your advices regarding debugging. However it happens only once in a while and only with WSGI on production. So if moving that import is solving the issue for me, I'm not so motivated to debug the issue more closely.

**Comment by rhertzog** [comment]
I have the problem in Django 2.2.25 with Python 3.9 as well. See https://code.djangoproject.com/ticket/33420

It's not fully reproducible either but one thing is sure, is that I don't use django-ratelimit in the project where I got the error. It would be nice to have this fixed in other versions, even though it's not a security fix.

**Pull request merged**
