### PR TITLE
Fixed #30602 ExtractYear optimizations with DurationFields

### PR DESCRIPTION
**Pull request by cecedille1**

### CODE REVIEW

**Comment by charettes** [comment]
Hello @cecedille1!

Thank you for your contribution but I don't think `ExtractYear` is meant to work with `DurationField`, at least it's not tested. I wouldn't be against adding support for it on all backends but it should probably be done but it involves more work.

It will probably be easy to add for PostgreSQL as this patch demonstrates but it will be harder on other backends that don't have native `DurationField` support. We should probably add support for extracting months and days as well and maybe even expose `__years`, `__months`, and `__days` lookup.

**Comment by cecedille1** [comment]
Hello @charettes, I thank you for the review

I agree that the behavior is not tested, but ExtractYear and the Extract family are meant to be used with DurationFields. The base Extract class has code that [specificaly targets DurationFields]( https://github.com/django/django/blob/master/django/db/models/functions/datetime.py#L53)

Backends without support for DurationFields will break with the ValueError `Extract requires native DurationField database support.` that is already raised in this case.

ExtractDay and ExtractMonth work fine because they don't have the special case implemented by ExtractYear to optimize the use of DB indices.

The generated SQL is broken for every case of ExtractYear + DurationField on every backend because of a special case, so broken support in some uncommon backends is still better that no support at all.

**Comment by charettes** [comment]
Well it looks like you are right, partial `DurationField` support for `Extract` was added in https://github.com/django/django/commit/43a4835edf32c57eb74c0eb207c276734a34abcf, thanks for correcting me.

In this case this PR makes sense as as bugfix.

**Comment by felixxm** [comment]
`DurationField` is modeled in Python by `timedelta` (see [documentation](https://docs.djangoproject.com/en/2.2/ref/models/fields/#durationfield)), so even with this fix it will always return 0 for `ExtractYear`, `ExtractYear`, `ExtractMonth` or `ExtractWeek` which is unexpected. I think we should raise `ValueError` in such cases.

**Comment by cecedille1** [comment]
I discovered the bug by doing this request
```
Contact.objects.annotate(
    age=ExtractYear(Func('birthdate', function='age', output_field=DurationField())
).filter(
   age__gte=18,
)
```
and the generated SQL is incorrect, that *really* is unexpected. With an extra Cast arround ExtractYear as a workarround, the correct behaviour is restored.

```
    age=Cast(ExtractYear(Func('birthdate', function='age', output_field=DurationField()), IntegerField())
```

Maybe I should add a note to the documentation that query on the DB on intervals with years won't work because they are not representable in Python.

**Comment by felixxm** [comment]
I would raise `ValueError` for set of lookups like that don't work properly (e.g. [datetime.py](https://github.com/django/django/blob/f03b7bd11461e8b525c27d5344f8cd3a21c9565e/django/db/models/functions/datetime.py#L72-L75)).

**Pull request closed without merging**
