### PR TITLE
Added SpatialFeatures.empty_intersection_returns_none.

### PR DESCRIPTION
**Pull request by timgraham**
(for reference, `supports_empty_geometry_collection` was added in 1a85b07bddbf43da00311bdbb3ef5519a3165dc6)

### CODE REVIEW

**Comment by timgraham** [comment]
I'm not completely sure if the feature is best named. Perhaps the existing `supports_empty_geometry_collection` name from 1a85b07bddbf43da00311bdbb3ef5519a3165dc6 is generalizable to other databases? Asking @claudep or @sir-sigurd for possible expertise.

**Comment by claudep** [comment]
The patch looks fine to me, but I would also like to hear Sergey's opinion.

**Comment by timgraham** [comment]
buildbot, test on oracle.

**Review by felixxm — APPROVED** [review]
@timgraham Thanks :+1: Do you want to wait for Sergey?

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by timgraham** [comment]
We could wait a couple more weeks until the feature freeze.

**Pull request merged**
