### PR TITLE
Fixed #31901 -- Prevented content overflowing in the admin changelist with navigation sidebar.

### PR DESCRIPTION
**Pull request by 007gzs**
[ticket_31901](https://code.djangoproject.com/ticket/31901)

### CODE REVIEW

**Comment by knyghty** [comment]
Thanks, this seems to fix it. It looks like it only happens on pages with a right sidebar.

This has caused a (very minor) issue, the search button drops onto the next line at some screen sizes:
Screenshot 2020-08-19 at 22 15 47

**Comment by 007gzs** [comment]
What is your browser? It works right in my browser

**Review by knyghty — COMMENTED** [review]
There is a specific screen size where the search bar is very small and the actions are cramped/weird, but I don't think it's worth dealing with here.

I haven't tested every possible admin feature, but it looks like a good improvement 👍

**Comment by 007gzs** [comment]
@knyghty Will this ticket be available in 3.1.1 on September 1?

**Comment by felixxm** [comment]
@007gzs This patch causes an issue with tabular inlines, see

obraz

Previously we had a scrollbar (which is not perfect), currently it's hidden.

**Comment by rbtsolis** [comment]
I'm not sure if this is the same Issue that I've, the content (Detail View) is blocked if I have the sidebar open ej:

Captura de pantalla de 2020-08-26 01-25-13

And this happend if I try to close it:
Captura de pantalla de 2020-08-26 01-25-28

Is just hidden the letters not the sidebar, I deactivated it with:

`admin.site.enable_nav_sidebar = False`

**Comment by felixxm** [comment]
@rbtsolis That's a different issue. Have you checked my [comment](https://code.djangoproject.com/ticket/31946#comment:2) on Trac?

**Comment by 007gzs** [comment]
In the change-form page, only a few cases will cause the page dislocation problem, so only the change-list page will be processed for the time being

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Comment by felixxm** [comment]
@007gzs Thanks :+1:

**Pull request merged**
