### PR TITLE
Fixed #29427 -- Ensured request has _body even when RequestDataTooBig is raised

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by carltongibson** [comment]
Hi @claudep, this looks fine. (In your looking at this, did you happen to see why/where the _response_ fails to be sent because the _request_ is missing the `_body`? (It's curious...)

(That looks like the underlying bug (?) but it's not exercised here...)

Thanks!

**Comment by claudep** [comment]
Sure, it makes sense to test creating a response from the request, I will explore a bit more.

**Comment by carltongibson** [comment]
Hey @claudep, thanks. (I attached a project to the ticket, that fails to reproduce the issue with the suggested middleware... — maybe that's handy. 🙂)

**Comment by claudep** [comment]
Closing until someone is able to provide a reproducible project.

**Pull request closed without merging**
