### PR TITLE
Removed unneeded escapes in regexes.

### PR DESCRIPTION
**Pull request by felixxm**
Special characters lose their special meaning inside sets of characters.

"-" lose its special meaning if it's placed as the first or last character.

Follow up to 7c6b66383da5f9a67142334cd2ed2d769739e8f1.

### CODE REVIEW

**Review by ngnpope — APPROVED** [review]
👍🏻

**Comment by nessita** [comment]
There seems to be a one regex that could also be cleaned up?

./django/db/models/sql/query.py:55:EXPLAIN_OPTIONS_PATTERN = _lazy_re_compile(r"[\w\-]+")

**Comment by ngnpope** [comment]
> There seems to be a one regex that could also be cleaned up?
> 
> ./django/db/models/sql/query.py:55:EXPLAIN_OPTIONS_PATTERN = _lazy_re_compile(r"[\w-]+")

`\w` inside `[]` still makes sense: It's not the same as `[w]`.

From https://docs.python.org/3/library/re.html:

> `[]`
>
> Used to indicate a set of characters. In a set:
> - ...
> - Special characters lose their special meaning inside sets. For example, `[(+*)]` will match any of the literal characters `'('`, `'+'`, `'*'`, or `')'`.
> - Character classes such as `\w` or `\S` (defined below) are also accepted inside a set, although the characters they match depends on whether [ASCII](https://docs.python.org/3/library/re.html#re.ASCII) or [LOCALE](https://docs.python.org/3/library/re.html#re.LOCALE) mode is in force.
> - ...

That list of special characters is not exhaustive, thus why `[\.]` is also simply `[.]`.

**Comment by nessita** [comment]
> > There seems to be a one regex that could also be cleaned up?
> > ./django/db/models/sql/query.py:55:EXPLAIN_OPTIONS_PATTERN = _lazy_re_compile(r"[\w-]+")
> 
> `\w` inside `[]` still makes sense: It's not the same as `[w]`.

I know! I forgot to use literal escaping format in the comment (I have added it now). See the updated comment, the referenced regex currently is:

```python
 # https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS
EXPLAIN_OPTIONS_PATTERN = _lazy_re_compile(r"[\w\-]+")
```

**Comment by ngnpope** [comment]
Adjusted my grepping and also found these:
```
django/contrib/flatpages/forms.py:13:r"^[-\w/\.~]+$"
django/contrib/gis/geometry.py:10:r"^(SRID=(?P<srid>\-?[0-9]+);)?"
docs/conf.py:57:r"^https?://(?:[^/\.]+\.)*example\.(?:com|net|org)(?::\d+)?/"
docs/conf.py:58:r"^https?://(?:[^/\.]+\.)*(?:example|invalid|localhost|test)(?::\d+)?/"
docs/releases/1.6.txt:782:r"^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$"
tests/gis_tests/inspectapp/tests.py:170:r"    geom = models.PolygonField\(([^\)])*\)"
tests/urlpatterns_reverse/urls.py:64:r"^price/[\$]([0-9]+)/$"
```

**Review by nessita — APPROVED** [review]
LGTM

**Comment by felixxm** [comment]
Thanks for reviews :+1:

**Pull request merged**
