### PR TITLE
Refs #24628 -- Added a second test and a docstring comment to avoid regression.

### PR DESCRIPTION
**Pull request by carljm**

### CODE REVIEW

**Comment by carljm** [comment]
@timgraham I'd be inclined to backport this, just to avoid unnecessary deltas in the same areas of code. Do you have a strong opinion either way?

**Comment by timgraham** [comment]
Yes, I'm in favor of that backporting philosophy. Also in favor of no blank line at the end of a docstring and a simple (#24628) at the end of the sentence for a ticket reference.

**Comment by carljm** [comment]
@timgraham Oops, should have waited for your review. I'll use the simpler ticket reference and avoid the extra blank lines in future. Want me to push a style fixup commit for this?

**Comment by timgraham** [comment]
I guess it helps so that other contributors don't copy that style. :-)

**Comment by carljm** [comment]
Done.

**Pull request merged**
