### PR TITLE
Refs #28477 -- Reduced complexity of aggregation over qualify queries.

### PR DESCRIPTION
**Pull request by charettes**
cc @timgraham

### CODE REVIEW

**Comment by charettes** [comment]
buildbot, test on oracle.

**Comment by timgraham** [comment]
No issues on CockroachDB. Thanks!

**Comment by charettes** [comment]
FWIW I've developed a nifty little tool that runs the whole test suite, records the produced unparametrized SQL queries, dump them to YAML file indexed by the test name, and allows to catch SQL changes betwen changesets. Here's the output for this change change against the main branch

```diff
--- test_filter_count (expressions_window.tests.WindowFunctionTests):postgresql:9bd174b9a7
+++ test_filter_count (expressions_window.tests.WindowFunctionTests):postgresql:61f598b3f3
@@ -1,13 +1,8 @@
 SELECT COUNT(*)
 FROM
-  (SELECT "col1"
+  (SELECT *
    FROM
-     (SELECT *
-      FROM
-        (SELECT "expressions_window_employee"."id" AS "col1",
-                RANK() OVER (PARTITION BY "expressions_window_employee"."department"
-                             ORDER BY "expressions_window_employee"."salary" DESC) AS "qual0"
-         FROM "expressions_window_employee"
-         GROUP BY "col1",
-                  "expressions_window_employee"."department") "qualify"
-      WHERE "qual0" = %s ) "qualify_mask") subquery
+     (SELECT RANK() OVER (PARTITION BY "expressions_window_employee"."department"
+                          ORDER BY "expressions_window_employee"."salary" DESC) AS "department_salary_rank"
+      FROM "expressions_window_employee") "qualify"
+   WHERE "department_salary_rank" = %s) subquery
--- test_related_ordering_with_count (expressions_window.tests.WindowFunctionTests):postgresql:9bd174b9a7
+++ test_related_ordering_with_count (expressions_window.tests.WindowFunctionTests):postgresql:61f598b3f3
@@ -1,6 +1,3 @@
-SELECT COUNT(*)
-FROM
-  (SELECT "expressions_window_employee"."id" AS "col1"
-   FROM "expressions_window_employee"
-   LEFT OUTER JOIN "expressions_window_classification" ON ("expressions_window_employee"."classification_id" = "expressions_window_classification"."id")
-   GROUP BY "col1") subquery
+SELECT COUNT(*) AS "__count"
+FROM "expressions_window_employee"
+LEFT OUTER JOIN "expressions_window_classification" ON ("expressions_window_employee"."classification_id" = "expressions_window_classification"."id")
```

I wonder if adding it as an option to `runtests.py` might be interesting or even hook it up to CI via Github actions. It would make it easy to identify unexpected changes in SQL generation.

**Comment by felixxm** [comment]
@charettes Thanks :+1: 

> I wonder if adding it as an option to `runtests.py` might be interesting or even hook it up to CI via Github actions. It would make it easy to identify unexpected changes in SQL generation.

Sounds great! We could add a tag that triggers SQL analysis, e.g. `compare SQL`.

**Pull request merged**
