### PR TITLE
Fixed #26401 -- Allowed use of auth logic without auth in INSTALLED_APPS.

### PR DESCRIPTION
**Pull request by jdufresne**
<https://code.djangoproject.com/ticket/26401>

### CODE REVIEW

**Comment by collinanderson** [comment]
Would it be possible to write a test for this so an import doesn't get accidentally added? (Or maybe that's not possible)

**Comment by timgraham** [comment]
Also, this patch seems a bit invasive to resolve the regression in 1.9. What tests did you do exactly?

**Comment by jdufresne** [comment]
> Would it be possible to write a test for this so an import doesn't get accidentally added? (Or maybe that's not possible)

I'll try to look into this when I have some time. I'll see what is possible.

> Also, this patch seems a bit invasive to resolve the regression in 1.9. What tests did you do exactly?

I mostly tested this against my own project which:

1. Uses `django.contrib.auth`, but not the database models
2. Uses `django.contrib.admin`

Forms needed to be split up as some forms reference `User` at import time. To avoid importing models through forms, non-auth-model projects can import from `base_forms`. The admin has been changed to do this so it too can be used without auth models.

If you have any suggestions to make the change less invasive, I'm happy to investigate it. I could break the PR into smaller commits if you think it would help.

**Comment by jdufresne** [comment]
I'm not working on this ATM. Closing.

**Pull request closed without merging**
