### PR TITLE
Fixed #32913 -- Made watchman reloader tests less flaky.

### PR DESCRIPTION
**Pull request by pope1ni**
ticket-32913

### CODE REVIEW

**Comment by felixxm** [comment]
@abhiabhi94 Can you confirm that this patch works for you?

**Comment by abhiabhi94** [comment]
> @abhiabhi94 Can you confirm that this patch works for you?

I ran the tests for close for about `3132` iterations, and they seemed to pass every time. For what it's worth, the script used was:
```sh
#!/usr/bin/bash

iteration=0
while true; do
    iteration=$((iteration + 1))

    ./runtests.py utils_tests.test_autoreload.WatchmanReloaderTests.test_glob
    if [[ $? -ne 0 ]]; then
        echo -e "-----------\nit failed in the $iteration iteration--------------------\n"
        break
    fi
    echo -e "-------------\nrunning the $iteration iteration\n-----------------\n"
done

```

**Review by abhiabhi94 — APPROVED** [review]
Thanks, @pope1ni, for the patch. I have a suggestion, but don't know whether it is feasible.

Since this change makes the test slower on all machines, can we instead use some sort of approach where the flaky tests are re-run with an increased time out only if they fail.

**Comment by felixxm** [comment]
> Since this change makes the test slower on all machines, can we instead use some sort of approach where the flaky tests are re-run with an increased time out only if they fail.

I don't think it's worth additional complexity.

**Comment by felixxm** [comment]
@pope1ni Thanks :+1:

**Pull request merged**
