### PR TITLE
Refs #29892 -- Made Selenium tests wait for popups to be ready.

### PR DESCRIPTION
**Pull request by jdufresne**
Fixes intermittent test failure:

    ======================================================================
    FAIL: test_inline_with_popup_cancel_delete (admin_views.tests.SeleniumTests)
    Clicking ""No, take me back" on a delete popup closes the window.
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File ".../django/tests/admin_views/tests.py", line 4840, in test_inline_with_popup_cancel_delete
        self.assertEqual(len(self.selenium.window_handles), 1)
    AssertionError: 2 != 1

https://code.djangoproject.com/ticket/29892

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Comment by felixxm** [comment]
`test_inline_with_popup_cancel_delete()` still sometimes fails but with a different error:
```
ERROR: test_inline_with_popup_cancel_delete (admin_views.tests.FirefoxSeleniumTests)
Clicking ""No, take me back" on a delete popup closes the window.
----------------------------------------------------------------------
Traceback (most recent call last):
  ...
  File "django/tests/admin_views/tests.py", line 4839, in test_inline_with_popup_cancel_delete
    self.wait_for_popup(num_windows=1)
  File "django/django/contrib/admin/tests.py", line 43, in wait_for_popup
    self.wait_until(lambda d: len(d.window_handles) == num_windows, timeout)
  File "django/django/contrib/admin/tests.py", line 36, in wait_until
    WebDriverWait(self.selenium, timeout).until(callback)
  File "... site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
```

**Comment by jdufresne** [comment]
buildbot, test on selenium.

**Comment by jdufresne** [comment]
Thanks for catching that.

I dug a bit deeper. The intermittent errors occur because the new popup's JavaScript has not finished loading before the next `.click()` or other action occurs. I've fixed this by modifying `.wait_for_popup()` to now also wait for the popup's JavaScript to be fully loaded by waiting calling `.wait_page_ready()` which inspects `document.readyState`.

The method was renamed to `.wait_for_and_switch_to_popup()` as it now switches windows to execute JavaScript. All callers were switching to the window anyway.

**Comment by jdufresne** [comment]
buildbot, test on selenium.

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Pull request merged**
