### PR TITLE
Refs #31224 -- Removed incorrect @sync_to_async(thread_sensitive=True) example.

### PR DESCRIPTION
**Pull request by andrewgodwin**
It does not support thread_sensitive when used as a decorator, yet.

### CODE REVIEW

**Comment by adamchainz** [comment]
Docs failure is fixed by rebasing on latest master for sphinx upgrade.

**Comment by jaylynnconley12** [comment]
Thank you

**Comment by andrewgodwin** [comment]
That's the thing, this is rebased directly on top of current master, I just verified. Not quite sure why it's failing.

**Comment by felixxm** [comment]
Docs failure is not related with this PR, see #12698.

**Comment by felixxm** [comment]
@andrewgodwin Thanks :+1:

**Pull request merged**
