### PR TITLE
Fixed #30686 -- Stopped Truncator.chars truncating HTML entities

### PR DESCRIPTION
**Pull request by tdhooper**
Ticket https://code.djangoproject.com/ticket/30686

### CODE REVIEW

**Comment by tdhooper** [comment]
Ticket https://code.djangoproject.com/ticket/30686

**Comment by apollo13** [comment]
Note to mergers (if we are going to merge this and not replace with a real parser): Check for regular expression backtracking

**Comment by carltongibson** [comment]
I'm not at all happy about taking this approach, vs bringing in an HTML parser, but the status of HTML5lib is questionable, so possibly pulling this in (if we're sure it's ≈sound) would be OK as a stop-gap. 

I'll re-open so we can assess if someone has bandwidth to look.

**Comment by carltongibson** [comment]
See test cases from #11660

**Comment by apollo13** [comment]
I don't think the PR is correct in it's current form:
```
print(Truncator('aAAAAAAAbc').chars(3, html=True))
print(Truncator('a&AAAAAAA;bc').chars(3, html=True))
```
returns:
```
aA…
a&AAAAAAA;bc
```
The first result is correct, but the second one is wrong.

**Comment by felixxm** [comment]
Closing due to inactivity.

**Pull request closed without merging**
