### PR TITLE
Fixed #29373 -- Added long_description in setup.py.

### PR DESCRIPTION
**Pull request by carltongibson**
As per [Tim's comment on ticket](https://code.djangoproject.com/ticket/29373#comment:8). 

Uploaded to TestPyPI for preview: https://test.pypi.org/project/Django-TestPyPI-Upload/

### CODE REVIEW

**Comment by timgraham** [comment]
Thanks for testing that. Do you see any reason not to use a context manager (`with open(...) as f`) to close the file?

**Comment by carltongibson** [comment]
> Do you see any reason not to use a context manager...

No. I hadn't considered to be honest. (Was more thinking about the PyPI side.) I'll look at that in a moment.

**Comment by carltongibson** [comment]
OK. https://github.com/django/django/pull/9918/commits/96f9f9b09c760d9dbbdadc320541eafc9102171a. Builds correctly. (Didn't upload; can do if needed.)

**Comment by adamchainz** [comment]
👍

**Pull request merged**
