### PR TITLE
Refs #27060 -- Add db_index support for inspectdb command

### PR DESCRIPTION
**Pull request by pahaz**
I'm using `inspectdb` for some legacy Django based projects.

I have a problem with indexes as described here: https://code.djangoproject.com/ticket/27060

I understand that it's not so simple to fix all edge cases. And it is a reason why there has been no activity on this issue for three years.

But, It will help me if at least `db_index` indexes are supported by the inspectdb.

### CODE REVIEW

**Comment by pahaz** [comment]
Related issue https://github.com/django/django/pull/7083
This PR may be interesting for @akki @claudep and @imgraham

And the last PR related to the inspectdb command: https://github.com/django/django/pull/11260
Maybe also interesting for @felixxm and @scop

**Comment by pahaz** [comment]
Is it going to be merged? Any suggestions?

**Comment by auvipy** [comment]
this is on review Queue so have some patience.

**Comment by felixxm** [comment]
@pahaz Thanks for this patch, however ticket 27060 is about adding support for `Meta.indexes` to the `inspectdb` not about the `db_index` option. Mainly because it can be hard to ensure that an inspected index is exactly the same as an index created by Django (type, ordering, operator classes, `fillfactor` etc.). That's why we accepted a ticket to support `Meta.indexes` where these options may be included.

**Pull request closed without merging**
