### PR TITLE
Fixed #28403 -- Added missing formats in FORMAT_MODULE_PATH docs.

### PR DESCRIPTION
**Pull request by Ashaba**
added DATE_INPUT_FORMATS and
DATETIME_INPUT_FORMATS to FORMAT_MODULE_PATH settings example

### CODE REVIEW

**Comment by Ashaba** [comment]
Can we just add a note in the readme?, Perhaps siting that ```the locale structure can be used but then advise to use formats instead```?

**Comment by Ashaba** [comment]
Sure, I am okay with adding the comment as suggested. It clearly brings it out. Thank you @carltongibson

**Comment by carltongibson** [comment]
I added the note in https://github.com/Ashaba/django/pull/1. I'm still not 100% sure about the need for it. I thought may Tim could decide when merging 🙂

Other than that this looks good to go.

**Comment by Ashaba** [comment]
@carltongibson How do we look now? With the addition of the note. And perhaps you could guide on the commits. Do you think 3 commits is a good thing?

**Comment by carltongibson** [comment]
> Do you think 3 commits is a good thing?

Finally we need 1 commit. But I think letting Tim decide on the "Note..." is good, so the two is fine for now. (The merge commit isn't needed, but...) Tim can Squash when merging. (If that's not OK he can say.) 

Thanks for the effort!

**Comment by timgraham** [comment]
I relocated Carlton's note to a more suitable location, perhaps. Check if it looks fine.

**Comment by carltongibson** [comment]
Looks good to me.

**Pull request merged**
