### PR TITLE
Refs #33526 -- Made CSRF_COOKIE_SECURE/SESSION_COOKIE_SECURE/SESSION_COOKIE_HTTPONLY don't pass on truthy values.

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Review by adamchainz — APPROVED** [review]
💯 agree with your assessment in the ticket - truthy is dangerous when users tend to parse strings.

The patch LGTM 👍

**Review by jacobtylerwalls — APPROVED** [review]
Looks great. I see there's an identical situation with `SESSION_COOKIE_HTTPONLY`, but no reason not to merge this as is.

**Comment by felixxm** [comment]
Thanks both :1st_place_medal: I added `SESSION_COOKIE_HTTPONLY` to this patch.

**Comment by felixxm** [comment]
buildbot, test this please.

**Pull request merged**
