### PR TITLE
Fixed #34649 -- Fixed headless deprecation warning on Selenium 4.8+.

### PR DESCRIPTION
**Pull request by aokugel**

### CODE REVIEW

**Comment by aokugel** [comment]
[ticket-34649](https://code.djangoproject.com/ticket/34649)

**Comment by smithdc1** [comment]
Did you manage to see this working in Firefox?

**Comment by aokugel** [comment]
@smithdc1 ./runtests.py --selenium=firefox --headless passes the 78 tests.

**Comment by smithdc1** [comment]
Super. Thanks for confirming.👍

**Review by felixxm — APPROVED** [review]
@aokugel Thanks :+1: Welcome aboard :boat:

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Pull request closed without merging**
