### PR TITLE
[donotmerge] testing jenkins

### PR DESCRIPTION
**Pull request by apollo13**
This is to test jenkins PR integration

### CODE REVIEW

**Comment by apollo13** [comment]
buildbot, test on selenium.

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Comment by apollo13** [comment]
buildbot, test on selenium.

**Comment by apollo13** [comment]
buildbot, test on selenium.

**Comment by apollo13** [comment]
Ok, the triggers only seem to work if the PR did change

**Comment by apollo13** [comment]
```
Running GitHub Pull Request trigger check for May 15, 2019, 4:10:25 PM on django/django
GitHub rate limit before check: GHRateLimit{remaining=3896, limit=5000, resetDate=Wed May 15 16:35:00 UTC 2019}
Comment matched to pattern: state has changed (new comment found - 'buildbot, test on selenium.')
Comment matched to pattern: matching comment buildbot, test on selenium.
Finished GitHub Pull Request trigger check for django/django at May 15, 2019, 4:10:26 PM. Duration: 1239ms
```

**Comment by apollo13** [comment]
Ironically this seems to be fixed by removing the github pr request plugin. I'll update ansible :D

**Pull request closed without merging**
