### PR TITLE
Refs #27025 -- Removed unneeded sqlite3 transaction management workaround in Python 3.6

### PR DESCRIPTION
**Pull request by timgraham**
Obsolete per https://bugs.python.org/issue10740#msg274816

### CODE REVIEW

**Comment by timgraham** [comment]
Would you prefer `sys.version_info < (3, 6)` in a new feature flag? If so, what name?

**Comment by charettes** [comment]
What about setting SQLite's `autocommits_when_autocommit_is_off` feature to False on Python > 3.6?

**Comment by charettes** [comment]
Is this because it would cause issues here? https://github.com/django/django/blob/271581df606b307d89c141e8b1a50ace763bea81/django/db/backends/base/base.py#L375-L404

**Comment by timgraham** [comment]
Correct

**Comment by timgraham** [comment]
@aaugustin, any thoughts about the current approach vs. a new feature flag?

**Comment by aaugustin** [comment]
I started writing an answer but there are too many open questions.

I'd like to check what got fixed exactly in Python 3.6. If memory serves, the biggest problem, `create savepoint`, was fixed, but I think there are still some cases where sqlite3 commits when it shouldn't, perhaps before DDL statements (to be confirmed).

In any case I'm in favor of fine grained flags with comments explaining what they do, otherwise it will be difficult to maintain the logic in the future.

**Comment by timgraham** [comment]
If it's easier to keep the status quo until Django supports Python 3.6+ that's fine with me.

**Comment by timgraham** [comment]
Closing for now as I don't have time to do further investigation right now.

**Comment by timgraham** [comment]
Aymeric, I found https://github.com/python/cpython/commit/ab994ed8b97e1b0dac151ec827c857f5e7277565 "sqlite3 no longer implicitly commit an open transaction before DDL statements" (also in Python 3.6+). Does that address your concern?

I revised this patch a bit since the March 2017 version. When dropping support for Python 3.5, we can eliminate the `autocommits_when_autocommit_is_off` feature flag but  `_start_transaction_under_autocommit()` is still needed.

**Comment by aaugustin** [comment]
Yes, it does.

**Pull request merged**
