### PR TITLE
Fixed #28233 -- Used a simpler example in the aggregation "cheat sheet" docs.

### PR DESCRIPTION
**Pull request by Rajesh-Veeranki**
https://code.djangoproject.com/ticket/28233

### CODE REVIEW

**Comment by timgraham** [comment]
The meaning of the new wording isn't clear to me. Maybe including the formula of the calculation would help.

**Comment by Rajesh-Veeranki** [comment]
Added a simplified SQL query that is executed. Please, let me know if it requires any more change.

**Comment by liushigit** [comment]
The added explanation is good. But the example itself doesn't demostrate a very useful use case. Maybe change the `Sum` to `Avg`? @Rajesh-Veeranki

**Comment by Rajesh-Veeranki** [comment]
We can make it `Avg` which makes it evaluate the average of the price per page of all books. (In short Avg of Avg)

I also suggest we also add an additional example like this

`Book.objects.all().aggregate(price_per_page=Sum(F('price'), output_field=FloatField())/Sum(F('pages'), output_field=FloatField()))` which makes it evaluate the more meaningful average in my opinion and translates to 
`SELECT (SUM(price) / SUM(pages)) AS avg_price_per_page FROM app_book`

**Comment by liushigit** [comment]
That's a good idea! I think both use cases will be useful.

**Comment by Rajesh-Veeranki** [comment]
I have updated the examples. Wondering, if there is a standard test database against which these queries are executed? Please let me know if there is one. As of now, I'm using dummy values, which may be fine?. Also please suggest any more changes required.

**Comment by timgraham** [comment]
@jarshwah, I see you added the original "Cost per page" example in f59fd15c4928caf3dfcbd50f6ab47be409a43b01. Any input here? Personally, I think I would prefer to see simple explanations of queries in English rather than than diving into how they translate to SQL.

**Comment by jarshwah** [comment]
Considering it's a cheat sheet, the aim is to show how different aggregates can be constructed. I readily admit that cost_per_page is a trivial and silly example, and am open to the changing - provided multiple expressions are combined in some way.

I think if you want to have examples that link simplified SQL and queries together, then another section would probably be more appropriate.

That said, I don't feel strongly about this. I'd usually defer to @timgraham regarding docs

**Comment by timgraham** [comment]
I haven't used aggregation too much so I'm not sure if I can give a good suggestion. I tired `Book.objects.aggregate(alias=Max('price') - Avg('price'), output_field=FloatField()))` as a naive try to compute the price difference between the most expensive book and the average price, but it gives `'FloatField' object has no attribute 'resolve_expression'`.

**Comment by jarshwah** [comment]
`output_field` is an argument of expressions, not aggregate/annotate. Either of these will (should) work:

```
Book.objects.aggregate(alias=ExpressionWrapper(
    Max('price') - Avg('price'), output_field=FloatField()
))

#or

Book.objects.aggregate(alias=Max('price', output_field=FloatField()) - Avg('price'))
```

**Comment by timgraham** [comment]
Oops, do you think it's feasible/worth trying to improve that error message? Is it correct to say that all kwarg values should be expressions, i.e. have `resolve_expression`?

**Comment by jarshwah** [comment]
Actually yes, improving that error would be really helpful. I'm fairly sure all args and kwargs to aggregate and annotate should be expressions

**Comment by timgraham** [comment]
Proposed patch:
```diff
diff --git a/docs/topics/db/aggregation.txt b/docs/topics/db/aggregation.txt
index 2bc30f8..129df68 100644
--- a/docs/topics/db/aggregation.txt
+++ b/docs/topics/db/aggregation.txt
@@ -67,11 +67,11 @@ In a hurry? Here's how to do common aggregate queries, assuming the models above
     >>> Book.objects.all().aggregate(Max('price'))
     {'price__max': Decimal('81.20')}
 
-    # Cost per page
+    # Difference between highest price book and average price
     >>> from django.db.models import F, FloatField, Sum
-    >>> Book.objects.all().aggregate(
-    ...    price_per_page=Sum(F('price')/F('pages'), output_field=FloatField()))
-    {'price_per_page': 0.4470664529184653}
+    >>> Book.objects.aggregate(
+    ...     price_diff=Max('price', output_field=FloatField()) - Avg('price')))
+    {'price_diff': 46.85}
 
     # All the following queries involve traversing the Book<->Publisher
     # foreign key relationship backwards.
```
and created https://code.djangoproject.com/ticket/28277#ticket for adding the discussed validation.

**Comment by Rajesh-Veeranki** [comment]
Eliminating the confusing example and adding this makes sense to me. BTW you missed the Max import
 `from django.db.models import FloatField, Max`

**Comment by timgraham** [comment]
Thanks for pointing out the imports that need updating. I think we don't need to import Avg/Max again since they are used previously in the shell session.

**Pull request merged**
