### PR TITLE
Fixed #23892 -- Clarified compatibility policy for migrations.

### PR DESCRIPTION
**Pull request by carljm**
https://code.djangoproject.com/ticket/23892

### CODE REVIEW

**Comment by MarkusH** [comment]
Sounds good. I'd empathize the second paragraph (like in the first paragraph).

**Comment by carljm** [comment]
Maybe; I didn't want to overuse emphasis. We don't do a lot of it in the docs. So I just emphasized the one takeaway point that you need to know if you don't get anything else.

**Comment by aaugustin** [comment]
LGTM

**Comment by timgraham** [comment]
merged in e35c70bef44805d47f6a4ae692be878184c4fe1f, thanks.

**Pull request closed without merging**
