### PR TITLE
[1.7.x] Fixed #24104 - Fixed check to look on field internal type instead of class instance

### PR DESCRIPTION
**Pull request by coldmind**
https://code.djangoproject.com/ticket/24104

Backport of #3865 to 1.7.x

### CODE REVIEW

**Comment by timgraham** [comment]
Think we need documentation on this -- particularly because the way that works on 1.7 isn't go to on 1.8, right?

**Comment by coldmind** [comment]
In 1.8 it look for `field.many_to_many`, here we should look for internal type since we don't have it here. What part of changes should be documented? Do you mean add a note here https://docs.djangoproject.com/en/1.7/howto/custom-model-fields/ ?

**Comment by timgraham** [comment]
Mainly the 1.7.4/1.8 release notes I think. Btw, you can ignore that test failure. I've switch the pull request builder over to Ubuntu 14.04 but that's an expecture failure on the 1.7 branch.

**Comment by coldmind** [comment]
I added release notes for 1.7 (pull request is created for 1.7.x branch so there are no references of 1.8).

**Comment by MarkusH** [comment]
LGTM.

Could you apply the comments from the patch that I actually committed (38c17871bb6dafd489367f6fe8bc56199223adb8):

```patch
diff --git a/tests/schema/fields.py b/tests/schema/fields.py
index fc609a2..596671a 100644
--- a/tests/schema/fields.py
+++ b/tests/schema/fields.py
@@ -30,6 +30,8 @@ class CustomManyToManyField(RelatedField):
         )
         self.swappable = swappable
         self.db_table = kwargs.pop('db_table', None)
+        if kwargs['rel'].through is not None:
+            assert self.db_table is None, "Cannot specify a db_table if an intermediary model is used."
         super(CustomManyToManyField, self).__init__(**kwargs)

     def contribute_to_class(self, cls, name):
@@ -44,6 +46,7 @@ class CustomManyToManyField(RelatedField):
     def get_internal_type(self):
         return 'ManyToManyField'

+    # Copy those methods from ManyToManyField because they don't call super() internally
     contribute_to_related_class = ManyToManyField.__dict__['contribute_to_related_class']
     set_attributes_from_rel = ManyToManyField.__dict__['set_attributes_from_rel']
     _get_m2m_attr = ManyToManyField.__dict__['_get_m2m_attr']
diff --git a/tests/schema/tests.py b/tests/schema/tests.py
index 6ffdadf..7419e77 100644
--- a/tests/schema/tests.py
+++ b/tests/schema/tests.py
@@ -1313,6 +1313,9 @@ class SchemaTests(TransactionTestCase):
             self.assertEqual(item[0], None if connection.features.interprets_empty_strings_as_nulls else '')

     def test_custom_manytomanyfield(self):
+        """
+        #24104 - Schema editors should look for many_to_many
+        """
         # Create the tables
         with connection.schema_editor() as editor:
             editor.create_model(AuthorWithM2M)
```

**Comment by coldmind** [comment]
Just updated the PR

**Comment by MarkusH** [comment]
Merged in 3d4a826174b7a411a03be39725e60c940944a7fe. Thanks!

**Pull request closed without merging**
