### PR TITLE
Fixed #24472 -- Defined internal types explicitly for related fields

### PR DESCRIPTION
**Pull request by Akash-Kumar-Sen**
[Ticket - 24472](https://code.djangoproject.com/ticket/24472)
Following PR #4296

### CODE REVIEW

**Comment by shangxiao** [comment]
I'm not sure I see the point of adding extra boilerplate like this as the name of the field can be determined from the class; and the fact that the ticket & PR never got updated to add some simple tests over the last decade tells me that nobody has a use for it.

If we really wanted this for consistency's sake we can do this:

```
class OneToOneField:
    @classmethod
    def get_internal_type(cls):
        return cls.__name__
```

gives:

```
>>> field = OneToOneField()
>>> field.get_internal_type()
'OneToOneField'
>>> OneToOneField().get_internal_type()
'OneToOneField'
```

**Comment by Akash-Kumar-Sen** [comment]
- I also don't see any other reason than consistency.
- Deriving the string from using `cls.__name__` makes more sense rather than hardcoding it.

**Comment by felixxm** [comment]
> If we really wanted this for consistency's sake we can do this:
> 
> ```
> class OneToOneField:
>     @classmethod
>     def get_internal_type(cls):
>         return cls.__name__
> ```
> 
> gives:
> 
> ```
> >>> field = OneToOneField()
> >>> field.get_internal_type()
> 'OneToOneField'
> >>> OneToOneField().get_internal_type()
> 'OneToOneField'
> ```

It works this way from the very beginning:

https://github.com/django/django/blob/b81e974e9ea16bd693b194a728f77fb825ec8e54/django/db/models/fields/__init__.py#L973-L974

**Comment by felixxm** [comment]
Closing per ticket.

**Pull request closed without merging**
