### PR TITLE
Fixed #28838 -- Fixed crash on Model.save() after annotate.

### PR DESCRIPTION
**Pull request by shangdahao**
https://code.djangoproject.com/ticket/28838

### CODE REVIEW

**Comment by shangdahao** [comment]
Thanks Carlton.

It's a good idea to place for the test case in `test/annotations`.

I am not sure is it a good idea to re-use existing models to build the test case.
It need to change the `base_manager` to a custom manager which has annotate in `get_queryset` to trigger the test case failure, for example:
```
def test_update_fields_after_annotate(self):
    class PublisherManager(Manager):
        def get_queryset(self):
            return super().get_queryset().annotate(
                rating_avg=Avg('book__rating')
            )
    Publisher.add_to_class('customer_manager', PublisherManager())
    Publisher._meta.base_manager_name = 'customer_manager'
    publisher_preupdate = Publisher.objects.get(pk=self.p1.id)
    publisher_preupdate.name = 'name_changed'
    publisher_preupdate.save()
    publisher_postupdate = Publisher.objects.get(pk=self.p1.id)
    self.assertEqual(publisher_postupdate.name, 'name_changed')
```
And it will need restore `Publisher` after the test case. 
I think it's a little complicated.
Maybe it's more clear to use new models to build the test case.

**Comment by carltongibson** [comment]
Hi @shangdahao — I think we **should** be able to reproduce the issue without going via the manager. We just need an annotated _instance_ which we then `update`. 

So... does fetching like this still raise the issue? 

```
instance = Publisher.objects.annotate(rating_avg=Avg('book__rating')).first()
instance.name = "updated"
instance.save()
```
 
This way we don't need to add the annotation in the manager's `get_querset` method.

**Comment by shangdahao** [comment]
Hi @carltongibson , I think you are wrong, the code you gave can't raise the issue.

In SQLite, the code:

```
instance = Publisher.objects.annotate(rating_avg=Avg('book__rating')).first()
instance.name = "updated"
instance.save()
```
will produce these sql:
```
"SELECT "testapp_publisher"."id", "testapp_publisher"."name", "testapp_publisher"."num_awards", AVG("testapp_book"."rating") AS "rating_avg" FROM "testapp_publisher" LEFT OUTER JOIN "testapp_book" ON ("testapp_publisher"."id" = "testapp_book"."publisher_id") GROUP BY "testapp_publisher"."id", "testapp_publisher"."name", "testapp_publisher"."num_awards" ORDER BY "testapp_publisher"."id" ASC LIMIT 1",
"BEGIN",
"UPDATE "testapp_publisher" SET "name" = 'updated', "num_awards" = 10 WHERE "testapp_publisher"."id" = 1"
```
which will not raise the issue.

we need sql like this to raise the issue:
```
"SELECT "testapp_publisher"."id", "testapp_publisher"."name", "testapp_publisher"."num_awards", AVG("testapp_book"."rating") AS "rating_avg" FROM "testapp_publisher" LEFT OUTER JOIN "testapp_book" ON ("testapp_publisher"."id" = "testapp_book"."publisher_id") GROUP BY "testapp_publisher"."id", "testapp_publisher"."name", "testapp_publisher"."num_awards" ORDER BY "testapp_publisher"."id" ASC LIMIT 1",
"BEGIN",
UPDATE "testapp_publisher" SET "name" = updated, "num_awards" = 10 WHERE "testapp_publisher"."id" IN (SELECT U0."id", AVG(U1."rating") AS "rating_avg" FROM "testapp_publisher" U0 LEFT OUTER JOIN "testapp_book" U1 ON (U0."id" = U1."publisher_id") WHERE U0."id" = 1 GROUP BY U0."id")
```
the subquery of the last sql, ` SELECT U0."id", AVG(U1."rating") AS "rating_avg"` will raise the issue.

This is because in `models.save() ` , it will use [`_base_manager`](https://github.com/django/django/blob/ff05de760cc4ef4c7f188e163c722ec3bc1f0cbf/django/db/models/base.py#L811). if we define a customer manager which has  related fields annotate, and change the `base_manager_name` to it, it will raise the issue.

I also test it on MySQL, it don't have the issue, because for MySQL the query is broken into a SELECT and then an UPDATE.

**Comment by carltongibson** [comment]
Hi @shangdahao 

>  I think you are wrong, the code you gave can't raise the issue.

OK fine. Quite likely: I haven't tested that it just seemed it should be possible to annotate the model correctly without needing to go via the manager (which just returns the queryset right?) 

I'll have a play and see if I can make it work. If not then yes lets add the new models. 

Thanks for the effort!

**Comment by timgraham** [comment]
I pushed an edit to move the test to a different location in order to reuse models. Feel free to check it.

**Comment by carltongibson** [comment]
+1 on the moved tests. (The new manager does the trick.)

**Pull request merged**
