### PR TITLE
Documentation: Fix import reverse

### PR DESCRIPTION
**Pull request by johnsardine**
Import from the correct location as stated in the note here https://docs.djangoproject.com/en/1.10/ref/urlresolvers/

Apologies if there is anything missing in this PR. It's my first contribution as I noticed an error while following the tutorial

### CODE REVIEW

**Comment by pope1ni** [comment]
The `django.core.urlresolvers` package was moved to `django.urls` in 1.10, so the documentation is correct. If you are using an older version of Django, please look at the appropriate version of the documentation.

**Comment by johnsardine** [comment]
I understand. In my settings.py it states the following

`Generated by 'django-admin startproject' using Django 1.10.2.`

But if I import like this `from django.urls import reverse`

It shows the following

screenshot 2016-10-19 18 11 26

screenshot 2016-10-19 18 13 22

Do you have any advice?

Thank you

**Comment by timgraham** [comment]
As the traceback shows "Django Version: 1.8.12". Looks like you're using a different version from the one that you used to generate the project.

**Comment by johnsardine** [comment]
@timgraham Oh, I'm so sorry for this. I was so excited to contribute that I overlooked such a basic verification.

Thanks

**Pull request closed without merging**
