### PR TITLE
Fixes #30280 -- Made get_FIELD_display functions return strings again

### PR DESCRIPTION
**Pull request by matthiask**

### CODE REVIEW

**Comment by matthiask** [comment]
The naive version of using `str()` fails. The old version used `force_str(..., strings_only=True)` to preserve ints, datetimes etc. 

I think the best solution is to simply reintroduce the `force_str` call in this case. I updated the pull request.

**Comment by timgraham** [comment]
Please add a test that demonstrates the use case/need for `force_str()` then.

**Comment by matthiask** [comment]
I changed the test. I'm very aware that the example is artificial (there is an obvious alternative which wouldn't trigger the regression) but so will be many others. It does not change the fact that code which worked with 2.1 does not work with 2.2 anymore. I could even agree with the breakage ("coerce the result of get_*_display yourself if you require strings") but then it would be worth it adding a release note for this.

**Comment by timgraham** [comment]
Sorry, I thought the existing test was fine. What I meant was, also demonstrate why `force_str()` is required instead of `str()`.

**Comment by matthiask** [comment]
Oh, right.

When I added `str()` a few tests in other packages started failing, e.g. https://github.com/django/django/blob/d26b2424437dabeeca94d7900b37d2df4410da0c/tests/model_fields/tests.py#L160 --

**Comment by matthiask** [comment]
I wanted to add a minimal change to Django since a candidate has already been released. The gender=m/f choice field in `tests/choices/` annoys me very much though, so here's an additional commit replacing the tests with functionally equivalent but neutral tests in `tests/model_fields/`.

**Comment by timgraham** [comment]
Please use 4952aee0b9003eaf6071bf7ed4022aafa8e7e288 here. Additional refactoring can be done in a separate PR.

**Comment by matthiask** [comment]
Right, sorry. I force-pushed the branch back to the version you specified; will open a pull request later containing https://github.com/matthiask/django/tree/mk/ungender-choices

**Comment by matthiask** [comment]
Thanks 💜

**Pull request merged**
