### PR TITLE
Forced utf-8 encoding when loading common passwords in CommonPasswordValidator.

### PR DESCRIPTION
**Pull request by felixxm**
Follow up to 28eac41510eb9de728bdfbc22a36f33ac75394f2 (see #11391)

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot

**Comment by felixxm** [comment]
buildbot

**Comment by bsolomon1124** [comment]
Relevant comment from @bluetech:

> The `encoding='utf-8'` is needed to maintain the previous behavior. Before, `str.decode()` was used, which defaults to `utf-8`. Now, without an explicit encoding, `locale.getpreferredencoding(False)` is used, which is not necessarily UTF-8.

(Assumed to mean `bytes.decode()`) rather than `str` - which does indeed [default to utf-8](https://docs.python.org/3/library/stdtypes.html#bytearray.decode) for all of Python 3.

So, yes, _if_ the goal is to prevent a regression and maintain existing behavior, then it seems right that `gzip.open()` should use `encoding="utf-8"`.

However:

- `gzip.open(..., encoding='utf-8')` would then be called on any custom `password_list_path` that the user specifies.  Let's say that's a Windows user with UTF-16; should they be forced to use utf-8 and raise, or should a new `encoding`/ keyword be put into `__init__`
- As pointed out in #11391, all of `CommonPasswordValidator.DEFAULT_PASSWORD_LIST_PATH` is ASCII characters, meaning (as far as I know) that _not_ specifying an encoding should not hurt for the default file because encodings really start to diverge only after the first 128 characters of the character set.

Don't want to make this more complicated, but trying to put relevant info in one place.

**Comment by felixxm** [comment]
`utf-8` encoding was there since `CommonPasswordValidator` introduction in 1daae25bdcd735151de394a5578c22257e3e5dc7. I don't think it was ever an issue for users, because it is a static list and changing its encoding is straightforward (I don't believe that a lot of people have been forced to do that). Forcing `utf-8` is always safer than trusting a default encoding from locals.

**Pull request merged**
