### PR TITLE
Fixed DatabaseFeatures.has_case_insensitive_like on MySQL and Oracle.

### PR DESCRIPTION
**Pull request by felixxm**
Incorrect since its introduction in 20bab2cf9d02a5c6477d8aac066a635986e0d3f3.

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by timgraham** [comment]
Perhaps rather than skipping the test where this feature is used, it would be better (easier to detect if the feature is set incorrectly) if the test assertions results were modified based on `connection.features.has_case_insensitive_like`?

**Comment by felixxm** [comment]
@timgraham Good idea. Thanks. I updated PR.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Pull request merged**
