### PR TITLE
Added meaningful titles to ..admonition:: directives.

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Review by ngnpope — APPROVED** [review]
Nice 🙂

**Review by hramezani — APPROVED** [review]

**Comment by timgraham** [comment]
I quite prefer (and have always encouraged) adding helpful titles rather than nondescript "Note" headings. See [7th bullet](https://docs.djangoproject.com/en/dev/internals/contributing/writing-documentation/#guidelines-for-restructuredtext-files).

**Comment by felixxm** [comment]
> I quite prefer (and have always encouraged) adding helpful titles rather than nondescript "Note" headings. See [7th bullet](https://docs.djangoproject.com/en/dev/internals/contributing/writing-documentation/#guidelines-for-restructuredtext-files).

Thanks. Most of these notes are quite complex, but I will try to figure out meaningful titles.

**Comment by felixxm** [comment]
@timgraham I added titles. Thanks for the review :+1:

**Comment by felixxm** [comment]
Thanks y'all for reviews :+1:

**Pull request merged**
