### PR TITLE
Fixed #30819 -- Fixed year determination in admin calendar widget for two-digit years.

### PR DESCRIPTION
**Pull request by farhaanbukhsh**
Completing this PR: https://github.com/django/django/pull/11904

### CODE REVIEW

**Comment by farhaanbukhsh** [comment]
@felixxm is there any improvement needed here?

**Comment by felixxm** [comment]
@farhaanbukhsh You need to uncheck `Patch needs improvement` and `Needs tests` flags on the ticket-30819 if you think that it's ready for another round of reviews.

**Comment by farhaanbukhsh** [comment]
> @farhaanbukhsh You need to uncheck `Patch needs improvement` and `Needs tests` flags on the [ticket-30819](https://code.djangoproject.com/ticket/30819) if you think that it's ready for another round of reviews.

Done!

**Comment by farhaanbukhsh** [comment]
Any update on this PR? 🙈

**Comment by felixxm** [comment]
@farhaanbukhsh Thanks :+1: I added release notes, reorganized commits and pushed minor edits.

Off-topic: You don't need to leave comments to ping reviewers. We have many PRs in a queue, so please be more patient.

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Pull request merged**
