### PR TITLE
Refs #23919 - Remove Jython and pypy workarounds

### PR DESCRIPTION
**Pull request by orf**
[Ticket](https://code.djangoproject.com/ticket/23919)

Seeing as Django currently doesn't support Jython or PyPy we should perhaps also remove references them to from the documentation?

### CODE REVIEW

**Comment by claudep** [comment]
I think I would open a proper ticket for this issue. You didn't touch the docs in your patch. Any reason?

**Comment by srinivasreddy** [comment]
I thought we are still supporting Jython, PyPy. Since when did we stop?

**Comment by claudep** [comment]
Jython does not yet support Python 3, and master is Python 3 only. I'm not sure about PyPy.

**Comment by orf** [comment]
Pypy is 3.3 or 3.2 iirc. I can update the docs as well, not sure why I left
them out.

**Comment by timgraham** [comment]
I have very little pypy/Jython experience but I'm not sure if the removal has much benefit. I'd expect those projects to support Python 3 at some point. If this code is removed now, it's more likely that released versions of Django will be incompatible. If we leave this code in, other incompatibilities may arise in new Django code, but at least these issues may not have to be fixed again (though I realize they may not still be relevant in the Python 3 versions of Jython/pypy).

**Comment by srinivasreddy** [comment]
@timgraham  Agreed.

**Comment by claudep** [comment]
I would be more enclined to let the PyPy part, which has already Python 3 support than Jython. If we cleanly remove Jython support, the patch can be used later to reintroduced that support. Jython on Python 3 is announced for many years now, but has seen few progress.

**Comment by orf** [comment]
Good point. Shall I change this MR to remove the documentation instead?

**Comment by claudep** [comment]
Please let's discuss that on a ticket instead.

**Comment by timgraham** [comment]
https://github.com/jython/jython3 has some activity as of July but as there's no activity at http://www.jython.org/ and https://github.com/beachmachine/django-jython since 2015, removing the documentation might be fine. I'd create a ticket and put "2.0" in the keywords field. If there's no change in Jython's Python 3 status before the Django 2.0 release, I'll remove `docs/howto/jython.txt` or at least add a note that this is only supported in older Django releases that support Python 2.

**Pull request closed without merging**
