### PR TITLE
Refs #26085 : check that ForeignKey to Site is not equal to None.

### PR DESCRIPTION
**Pull request by jibaku**
My first PR to fix Refs #26085. Feedback on the PR welcomed.

### CODE REVIEW

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by jibaku** [comment]
the « default » test seems to skip a lot for tests. But I cannot find why.

**Comment by timgraham** [comment]
There's an error (creating foreign key constraints for the new model, I think) because the `django_site` table doesn't exist. I'm not immediatley sure how to resolve this.
```
Traceback (most recent call last):
  File "./runtests.py", line 441, in <module>
    options.debug_sql, options.parallel)
  File "./runtests.py", line 258, in django_tests
    extra_tests=extra_tests,
  File "/home/jenkins/workspace/pull-requests-trusty/database/postgres/label/trusty-pr/python/python2.7/django/test/runner.py", line 532, in run_tests
    old_config = self.setup_databases()
  File "/home/jenkins/workspace/pull-requests-trusty/database/postgres/label/trusty-pr/python/python2.7/django/test/runner.py", line 482, in setup_databases
    self.parallel, **kwargs
  File "/home/jenkins/workspace/pull-requests-trusty/database/postgres/label/trusty-pr/python/python2.7/django/test/runner.py", line 726, in setup_databases
    serialize=connection.settings_dict.get("TEST", {}).get("SERIALIZE", True),
  File "/home/jenkins/workspace/pull-requests-trusty/database/postgres/label/trusty-pr/python/python2.7/django/db/backends/base/creation.py", line 70, in create_test_db
    run_syncdb=True,
  File "/home/jenkins/workspace/pull-requests-trusty/database/postgres/label/trusty-pr/python/python2.7/django/core/management/__init__.py", line 117, in call_command
    return command.execute(*args, **defaults)
  File "/home/jenkins/workspace/pull-requests-trusty/database/postgres/label/trusty-pr/python/python2.7/django/core/management/base.py", line 339, in execute
    output = self.handle(*args, **options)
  File "/home/jenkins/workspace/pull-requests-trusty/database/postgres/label/trusty-pr/python/python2.7/django/core/management/commands/migrate.py", line 149, in handle
    self.sync_apps(connection, executor.loader.unmigrated_apps)
  File "/home/jenkins/workspace/pull-requests-trusty/database/postgres/label/trusty-pr/python/python2.7/django/core/management/commands/migrate.py", line 270, in sync_apps
    cursor.execute(statement)
  File "/home/jenkins/workspace/pull-requests-trusty/database/postgres/label/trusty-pr/python/python2.7/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/jenkins/workspace/pull-requests-trusty/database/postgres/label/trusty-pr/python/python2.7/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/jenkins/workspace/pull-requests-trusty/database/postgres/label/trusty-pr/python/python2.7/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "django_site" does not exist
```

**Comment by flaiming** [comment]
I started to work on this as it's tagged as easy pick for newbies and just discovered that there is already patch for that :) At least I can check if I'm on the right track.
But wouldn't be better to allow null Site FK relation and just redirect to default site (defined by SITE_ID in settings) than to throw HTTP 404?

**Comment by jibaku** [comment]
@flaiming : I think it better to raise a 404, to spot the problem more easily. A redirect to the default site can hide a problem. Explicit is better than implicit in that case I think.

But solving the problem spotted by @timgraham (django.db.utils.ProgrammingError: relation "django_site" does not exist) would help me for this issue.

**Comment by flaiming** [comment]
@jibaku : Ok, that makes sense.

I gathered that the django_site error is caused because contenttypes are migrated before sites app. I don't have solution to that either, but I'll look into it.

**Comment by claudep** [comment]
It's a known issue that test models cannot depend on contrib apps, on the rule that apps without migrations cannot depend on apps with migrations. We workarounded this limitation in two different approaches:
* In 90720d54, we added a fake `Site` model in the test models. In this case, this would be possible but would require mocking apps.get_model to return the appropriate Site model during the test.
* For the `sites_framework` tests, we added migrations for the test models.

**Comment by timgraham** [comment]
Closing in favor of https://github.com/django/django/pull/6427.

**Pull request closed without merging**
