### PR TITLE
Fixed #25361: Unpickling of QuerySet fails in presence of abstract intermediate model

### PR DESCRIPTION
**Pull request by LegoStormtroopr**
This is to fix this issue with pickling fields on abstract models.

https://code.djangoproject.com/ticket/25361#comment:2

### CODE REVIEW

**Comment by LegoStormtroopr** [comment]
I should mention this is a little ugly in how it resolves the issue by using `import_string`, but I'm not sure how to get around it. On the plus side it will resolve it for *most* cases where this is a problem. But if you inherit from an abstract models that is outside of models.py you will run into issues.

Feedback appreciated.

**Comment by timgraham** [comment]
I think we need a programmatic way to retrieve the path of an abstract model, not just a way that guesses the path. By the way, the pull request should go to master and include a test, perhaps in `tests/model_regress/test_pickle.py`.

If it's not a regression from a previous release or a major bug in a new feature it won't be backported. See our [supported versions policy](https://docs.djangoproject.com/en/dev/internals/release-process/#supported-versions).

**Comment by LegoStormtroopr** [comment]
I'd be happy to add a test and find a cleaner method of doing this, I just wanted a few pointers.

However, I need this in v1.8 as I can't upgrade and 1.8 is in LTS. If I have to spend a half a day working out a solution, I'd rather one I can use in the more immediate future (eg. for 1.8) rather than one I can use as some indefinite point in time (eg. master, 1.10, etc...).

**Comment by LegoStormtroopr** [comment]
Nevermind - I have a monkey patch working which should work until the bug is fixed or I upgrade. Thanks anyway. https://gist.github.com/LegoStormtroopr/f014801e63474971e7ffc23980f0b1d1

**Pull request closed without merging**
