### PR TITLE
Fixed #30461 -- Added pathlib.Path support for `path` parameter for `GeoIP2`.

### PR DESCRIPTION
**Pull request by lsnk**

### CODE REVIEW

**Comment by felixxm** [comment]
Some documentation changes are also required, e.g. [GEOIP_PATH](https://docs.djangoproject.com/en/stable/ref/contrib/gis/geoip2/#geoip-path).

**Comment by lsnk** [comment]
> Some documentation changes are also required, e.g. [GEOIP_PATH](https://docs.djangoproject.com/en/stable/ref/contrib/gis/geoip2/#geoip-path).

Fixed

> Could you also complement the tests?

Changed test a bit but it's tricky since GEOIP_PATH should be specified for tests from outside.

**Comment by claudep** [comment]
I created an alternate pull request in #11648 to add a new `to_path` utility, as I think this use case will happen in a lot more spaces in Django.

**Comment by felixxm** [comment]
@lsnk Thanks for this patch :+1: but I prefer Claude's solution.

Superseded by #11648.

**Pull request closed without merging**
