### PR TITLE
[5.1.x] Updated translations from Transifex.

### PR DESCRIPTION
**Pull request by nessita**
#### Branch description
Updated Translations from Transifex in preparation for the 5.1.2 release.

### CODE REVIEW

**Review by claudep — APPROVED** [review]
Thanks, I meant to work on that, then forgot. You rock!

**Comment by felixxm** [comment]
Thanks :+1: We normally add a short note to release notes:
```
Also, the latest string translations from Transifex are incorporated.
```

**Comment by nessita** [comment]
> Thanks 👍 We normally add a short note to release notes:
> 
> ```
> Also, the latest string translations from Transifex are incorporated.
> ```

Yes, this, thank you! I wanted to add it but then I forgot. Adding it now.

**Comment by nessita** [comment]
@claudep I should also "forward port" this revno, once landed, to `main`, right? So a future transifex import for 5.2 has a "smaller" diff.

**Comment by felixxm** [comment]
> @claudep I should also "forward port" this revno, once landed, to `main`, right?

Yes, please do :+1:

**Pull request merged**
