### PR TITLE
Refs #32681 -- Fixed VariableDoesNotExist when rendering some admin template.

### PR DESCRIPTION
**Pull request by felixxm**
Regression in 84609b3205905097d7d3038d32e6101f012c0619.

Follow up to 4e5bbb6ef2287126badd32842b239f4a8a7394ca.

Thanks Sourav Kumar for the report.

See [comment](https://code.djangoproject.com/ticket/32681?replyto=11#comment:11).

### CODE REVIEW

**Review by Rquaicoo — APPROVED** [review]

**Comment by felixxm** [comment]
buildbot, test on selenium

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Review by kezabelle — APPROVED** [review]
LGTM.

**Comment by felixxm** [comment]
Thanks both :+1:

**Comment by juanramb** [comment]
@felixxm could you please backport this to 3.2 branch? Thanks in advance

**Comment by felixxm** [comment]
@juanramb Django 3.2 is in extended support so it doesn't receive bugfixes anymore (except security fixes and data loss bugs), see [Django’s release process](https://docs.djangoproject.com/en/stable/internals/release-process/) for more details.

**Comment by juanramb** [comment]
Oh, I see. I am migrating to 3.2 because of 3.1 security issues. I cannot use 4.x because I'm stuck in python 3.7 but now Django 3.2 does not work in my setup making the admin app completely useless. Is there a way of avoiding this bug without this patch?

**Comment by AurangZ** [comment]
Just wondering, as this is a regression bug, should it not be included in the extended support?

**Pull request merged**
