### PR TITLE
Fixed #32390 -- Dropped support for Oracle 12.2 and 18c.

### PR DESCRIPTION
**Pull request by felixxm**
ticket-32390

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Review by auvipy — APPROVED** [review]
looks good

**Review by carltongibson — APPROVED** [review]
Yep, super. Thanks @felixxm 👍

**Comment by felixxm** [comment]
Thanks for checking :+1:

**Pull request merged**
