### PR TITLE
Simplify how the lazy CSRF token is implemented.

### PR DESCRIPTION
**Pull request by alex**
This significantly improves performance on PyPy. The previous implementation would generate a new class on every single request, which is relatively slow.

### CODE REVIEW

**Comment by fijal** [comment]
This + https://github.com/django/django/pull/4084 gives django admin rendering on pypy a nice boost. The (warmed up) performance goes up from 25ms/render on my machine to about 7-8ms/render. I did not do very proper measurments, but the difference is very significant

**Comment by timgraham** [comment]
merged in 8099d33b6553c9ee7de779ae9d191a1bf22adbda, thanks.

**Comment by timgraham** [comment]
Unfortunately this resulted in a regression for this case:
```python
import json

from django.http import HttpRequest
from django.template.context_processors import csrf
from django.test import SimpleTestCase
from django.utils.encoding import force_text


class TestContextProcessor(SimpleTestCase):

    def test_force_text_on_token(self):
        request = HttpRequest()
        request.META['CSRF_COOKIE'] = 'test-token'
        token = csrf(request).get('csrf_token')
        self.assertEqual(json.dumps(force_text(token)), '"test-token"')
```
See [ticket #24836](https://code.djangoproject.com/ticket/24836). I'll revert the patch unless either of you has an idea of how we could fix it.

**Comment by carljm** [comment]
@timgraham Why is ticket 24836 not a straight-up bug in `force_text`? It seems to be a simple case of `force_text` not doing what it is explicitly documented to do ("Similar to smart_text, except that lazy instances are resolved to strings, rather than kept as lazy objects.")

Seems to me that this PR revealed a latent bug in `force_text`. So we should fix `force_text`, not revert this PR.

**Pull request closed without merging**
