### PR TITLE
Fixed allow_migrate() signature in documentation

### PR DESCRIPTION
**Pull request by MarkusH**

### CODE REVIEW

**Comment by timgraham** [comment]
Update `tests/check_framework/test_multi_db.py:    def allow_migrate(self, db, app_label, model=None, **hints):` too?

**Comment by MarkusH** [comment]
Thanks Tim for pointing that out. In fact there are more changes to it required. Another commit coming up.

**Comment by timgraham** [comment]
Okay, I guess I'd backport at least the docs change to 1.8/1.9.

**Comment by MarkusH** [comment]
Merged in 228427ab1ab6aaafed4eacfb532f7ddb6cc1ed6c and 18afd50a2beae2e72cfc4841a6b80f253fe52a1b
and backported to 765f6d80414648e64c201f5e05bfd188326abc6a (1.9) and 3af5643d82735a2831a828609397af1a271a814a (1.8)

**Pull request closed without merging**
