### PR TITLE
Fixed #34671 -- Fixed collation introspection for views and materialized views on Oracle.

### PR DESCRIPTION
**Pull request by felixxm**
Thanks Philipp Maino for the report.

ticket-34671

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
@PMaino Does it work for you?

**Comment by PMaino** [comment]
@felixxm Thanks a lot, this is fixing the issue for me.
Stupid question what happens from here? How do integrate this in my code?

**Comment by felixxm** [comment]
> @felixxm Thanks a lot, this is fixing the issue for me. Stupid question what happens from here? How do integrate this in my code?

Thanks for checking :+1: This bugfix will be included in Django 5.0+, so you can wait for Django 5.0, or use locally patched version of Django.

**Review by sarahboyce — APPROVED** [review]

**Comment by sarahboyce** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
> buildbot, test on oracle.

Thanks for checking :+1: I was already built on Oracle, see [logs](https://djangoci.com/view/PR%20Builders/job/pull-requests-oracle/621/).

**Comment by PMaino** [comment]
cheers @felixxm and @sarahboyce 
If it's not too much hassle can you point to some documentation or let me know how i can get a locally path version and distribute this to our prod servers as well?

**Comment by sarahboyce** [comment]
> cheers @felixxm and @sarahboyce If it's not too much hassle can you point to some documentation or let me know how i can get a locally path version and distribute this to our prod servers as well?

You might find this useful: https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/
Following from what Mariusz was saying, it might make sense for you to fork this repository. Then there are branches for the releases, you might want to cherry pick this commit being applied here to the branch of your Django version. Then keep an eye on security releases :eyes: as you will want to keep your fork up-to-date.
Django 5.0 is scheduled for the start of December. When that is out, you can upgrade and discard your fork :+1:

**Comment by PMaino** [comment]
thanks a lot @sarahboyce :-)

**Pull request merged**
