### PR TITLE
[Experiment] Unsafe queryset (non)copying

### PR DESCRIPTION
**Pull request by jarshwah**
I thought it would be interesting to check what performance would look like if we were to disable certain safety mechanisms the ORM imposes. I've done this by adding an `unsafe` queryset method which, currently, only disables the copy procedure when chaining queryset methods together.

I benchmarked the following queryset using djangobench, and it's consistently about 1.3 - 1.4 times faster. Note that no actual SQL is being generated and sent to the server. Improvements diminish as soon as you interact with the database because it's responsible for a larger percentage of overall time. I also benchmarked the memory usage which is close enough to 1kb less.

```
qs = Book.objects.unsafe().filter(
        pages__lte=1000
    ).filter(
        author__region__startswith='region_'
    ).values('author__name').annotate(
        pagesum=Sum('pages'),
        counted=Count('*'),
        avgpg=Avg('pages')
    )
```

I think for querysets where the number of chained methods grows quite large there's value in looking to provide opt-in optimisations. Would anyone else be interested in something like this?

### CODE REVIEW

**Comment by timgraham** [comment]
I think this is similar to the `inplace()` method Anssi proposed in https://code.djangoproject.com/ticket/20880. I rebased that patch a week or so ago and plan to send a PR when I get some time to clean it up a little more.

**Comment by adamchainz** [comment]
I've optimized this problem in the past by having a module level queryset object like:

```
the_books = Book.objects.filter(
    pages__lte=1000
).filter(
    author__region__startswith='region_'
).values('author__name').annotate(
    pagesum=Sum('pages'),
    counted=Count('*'),
    avgpg=Avg('pages')
)

def fetch_the_books():
    return the_books.all()
```

This avoids all the work of copying *plus* the work of constructing the filters etc. And if the queryset can't be created at import time it can always be cached in a module global.

`unsafe()` seems a bit *too* unsafe to me, there is a lot of code (e.g. paginators) that relies on the copying behaviour and `unsafe` would lead to hard to troubleshoot bugs.

**Comment by timgraham** [comment]
I guess we can close this for now. Feel free to reopen if you continue work on it, Josh.

**Comment by jarshwah** [comment]
It was just an experiment to see what overhead could be avoided. The inplace patch you've linked to should do the same thing. I'd just be wary of Adams comments above, and provide a way to escape out of inplace for things like the paginator.

**Pull request closed without merging**
