### PR TITLE
Typo: Use strict comparison

### PR DESCRIPTION
**Pull request by camilonova**
Thank you :)

### CODE REVIEW

**Comment by timgraham** [comment]
Is there a bug with the current version? What about double equals vs. triple equals later in the snippet?

**Comment by camilonova** [comment]
Is better to do the strict comparison. Is not a bug just but makes it explicit and remove jshint warnings.

**Comment by timgraham** [comment]
So does the same reasoning apply to == vs === later in the snippet?

**Comment by camilonova** [comment]
You are right. I just updated the PR.

**Pull request merged**
