### PR TITLE
Fixed #34058 -- Changed sequence types when altering pre-Django 4.1 auto fields on PostgreSQL.

### PR DESCRIPTION
**Pull request by felixxm**
Thanks Anders Kaseorg for the report.

Regression in 2eea361eff58dd98c409c5227064b901f41bd0d6.

ticket-34058

### CODE REVIEW

**Comment by felixxm** [comment]
@andersk Can you confirm if it works for you?

**Comment by andersk** [comment]
Yes, this seems to work.

**Comment by felixxm** [comment]
> Yes, this seems to work.

Many thanks for your confirmation :tada:

**Review by carltongibson — APPROVED** [review]
Looks good. Nice test 😅

**Review by charettes — APPROVED** [review]

**Pull request merged**
