### PR TITLE
Removed lhs_only argument from KeyTransform.preprocess_lhs().

### PR DESCRIPTION
**Pull request by laymonage**
The `key_transforms` variable is not declared if `lhs_only` is `True`. 

Honestly, looking at it again, maybe we should remove `lhs_only` altogether. It's only there for micro-optimization by not creating and returning the `key_transforms`, but I think the performance difference is negligible. We can simplify the implementation by just always returning the `key_transforms` and changing [this line](https://github.com/django/django/blob/master/django/db/models/fields/json.py#L410) to:

```diff
diff --git a/django/db/models/fields/json.py b/django/db/models/fields/json.py
index 340b7ee875..4139b30384 100644
--- a/django/db/models/fields/json.py
+++ b/django/db/models/fields/json.py
@@ -407,7 +407,7 @@ class KeyTransformExact(JSONExact):
         if connection.vendor == 'sqlite':
             rhs, rhs_params = super().process_rhs(compiler, connection)
             if rhs == '%s' and rhs_params == ['null']:
-                lhs, _ = self.lhs.preprocess_lhs(compiler, connection, lhs_only=True)
+                lhs, *_ = self.lhs.preprocess_lhs(compiler, connection)
                 lhs = 'JSON_TYPE(%s, %%s)' % lhs
         return lhs, lhs_params
```

### CODE REVIEW

**Comment by felixxm** [comment]
@laymonage Thanks for this patch, however all bugfixes require [an accepted ticket](https://code.djangoproject.com/newticket) and a regression test. I'm not sure how this can crash as we use `lhs_only` only on SQLite :thinking:

**Comment by felixxm** [comment]
Removing `lhs_only` as a cleanup sounds good.

**Comment by laymonage** [comment]
> @laymonage Thanks for this patch, however all bugfixes require [an accepted ticket](https://code.djangoproject.com/newticket) and a regression test. I'm not sure how this can crash as we use `lhs_only` only on SQLite

@felixxm Yeah, I know that we do not use it on other databases, so this crash won't really happen unless it is explicitly used in other contexts. However, the cause of this crash (i.e. `NameError`) is trivial because it's not even related to the database, just an overlooked undeclared variable reference. Even though it's not documented, the method works fine if the `NameError` is resolved and it's just good practice in general, so I don't see why we shouldn't fix it.

I can write a ticket and test if we can proceed with this.

**Comment by felixxm** [comment]
> Even though it's not documented, the method works fine if the NameError is resolved and it's just good practice in general, so I don't see why we shouldn't fix it.

I wouldn't say that extra checks for unreachable scenarios, added just in case, is really a good practice.

> I can write a ticket and test if we can proceed with this.

I would rather remove `lhs_only` as a cleanup.

**Comment by laymonage** [comment]
> I wouldn't say that extra checks for unreachable scenarios, added just in case, is really a good practice.

Well, the extra check can be replaced by declaring `key_transform = []` at the start of the method. I was referring to avoiding the `NameError` in general, not in adding an extra check :slightly_smiling_face:

> I would rather remove lhs_only as a cleanup.

Yes, I also thought so in the PR's description. Let me change the patch in a moment.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Pull request merged**
