### PR TITLE
fix #28421 delete extra tests

### PR DESCRIPTION
**Pull request by Windsooon**
I think 
https://github.com/django/django/blob/master/tests/forms_tests/tests/test_formsets.py#L220
already test this output.

### CODE REVIEW

**Comment by timgraham** [comment]
The other test doesn't have a delete checkbox.

**Comment by Windsooon** [comment]
Do you think we should also test checkbox in test_formset_initial_data?

**Comment by timgraham** [comment]
This test looks fine to keep.

**Comment by Windsooon** [comment]
Do you think it's a good idea to create a base class to just test all the **assertHTMLEqual** output?
Or I don't know how to split the tests correctly.

**Comment by timgraham** [comment]
The idea is to split lines 494 to 584 into separate tests based on the parts that are independent. For example, the part that starts with the comment "Should be able to get deleted_forms" could be split off.

**Pull request closed without merging**
