### PR TITLE
Fixed #29541 -- Fixed crash of Cursor.execute() when Cursor.setinputsizes() is called without arguments with cx_Oracle 6.4.

### PR DESCRIPTION
**Pull request by felixxm**
Ticket [29541](https://code.djangoproject.com/ticket/29541).

### CODE REVIEW

**Comment by timgraham** [comment]
Probably it makes sense to backport to 2.0.x if this is the only change required. Can you add a release note for 2.0.8 (I just added the stub)? Maybe we should update ref/databases for 1.11 if the fix won't be made there.

**Comment by felixxm** [comment]
@anthony-tuininga fixed this issue in the https://github.com/oracle/python-cx_Oracle/commit/fee92abe5a6a0937e4789d251dc50825cb434113, so it should be fixed in the 6.4.1 version. Now I'm not sure if we will backport this fix to 2.0.x or 1.11.x, but if not then IMO there is no need to document that this version is invalid.

**Comment by timgraham** [comment]
Great! Yea, I don't know if we need to apply this to master, depending on how quickly 6.4.1 will be released.

**Comment by felixxm** [comment]
Calling `Cursor.setinputsizes()` without any parameters is useless, so I think that we can merge this to the master.

**Pull request merged**
