### PR TITLE
Enabled GitHub Code of Conduct.

### PR DESCRIPTION
**Pull request by adamchainz**
As per [GitHub docs](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project).

With this file in place, it will be linked when opening a new pull request, and it will check off one point of the [“Community profile checklist”](https://github.com/django/django/community).

The existence is also used to determine “maintainability” by some projects like [Snyk advisor](https://snyk.io/advisor/python/Django).

### CODE REVIEW

**Comment by felixxm** [comment]
@adamchainz Thanks :+1:

**Comment by carltongibson** [comment]
> The existence is also used to determine “maintainability” by some projects like Snyk advisor.

👍 to the PR here — thanks @adamchainz! But this is SO backwards 😆 (Oh well)

**Comment by felixxm** [comment]
> +1 to the PR here — thanks @adamchainz! But this is SO backwards laughing (Oh well)

I merged this to increase discoverability of CoC, not to satisfy a 3rd-party advisor.

**Comment by jefftriplett** [comment]
@adamchainz thank you for doing this. 

I know it's annoying and it makes me grumpy to think that GitHub can't identify that projects like Django not only have a Code of Conduct but **both** of their example/suggested CoC's are based on Django's Code of Conduct. Yet here we are.

**Pull request merged**
