### PR TITLE
Added YugabyteDB to list of third-party DB backends.

### PR DESCRIPTION
**Pull request by Sfurti-yb**
YugabyteDB is a Postgres compatible database and has a backend for Django overriding features supported differently in YugbayteDB as compared to Postgres.

We would love to get listed on the list of third party backends on the databases page. 

Please let us know in case any changes are required to help us get listed here.

Thanks!

### CODE REVIEW

**Comment by Sfurti-yb** [comment]
We have run the django test suite to verify that it works. The usage is also documented [here](https://docs.yugabyte.com/preview/integrations/django-rest-framework/) to confirm that it works.

** Note- The module name was recently changed from yb-bqckend to django_yugabytedb which is not yet updated in the doc

**Comment by felixxm** [comment]
> We have run the django test suite to verify that it works. The usage is also documented [here](https://docs.yugabyte.com/preview/integrations/django-rest-framework/) to confirm that it works.

But we cannot verify this without testing it manually. Moreover, in the future, we will not be able to easily check if it supports the latest versions of Django. Please, first set up CI in `django-yugabytedb` with all supported versions of Django.

**Comment by Sfurti-yb** [comment]
Okay, we will setup a CI and give an update here. Thanks!

**Comment by Sfurti-yb** [comment]
@felixxm We have added the CI setup, with the `migrations` and `schema` test modules added. Please take a look. Thanks!

**Comment by felixxm** [comment]
IMO, there is more work to do:
- merge CI,
- add classifiers, e.g. `Framework :: Django`, `Framework :: Django :: 3.2`, `Framework :: Django :: 4.0`.
- prepare a stable release (`django-yugabytedb==4.0.0` is pre-alpha),
- update outdated docs, e.g.
  - ["Installing in Python Virtual Environment From Source"](https://github.com/yugabyte/yb-django/blob/main/README.rst#installing-in-python-virtual-environment-from-source): you've released on PyPI so users don't have to install from source anymore
- document more caveats:
  - dropping primary keys is not supported,
  - changing the column types doesn't work in many cases.

**Comment by Sfurti-yb** [comment]
@felixxm  All the changes are made according to the previous comment. Please let us know the next steps. Thanks!

**Comment by ymahajan** [comment]
@felixxm - Please let us know if this PR can be merged now? Please treat this on priority, many of our community users looking forward to this integration.

**Comment by felixxm** [comment]
> @felixxm - Please let us know if this PR can be merged now? Please treat this on priority, many of our community users looking forward to this integration.

This PR is only about mentioning `django-yugabytedb` in the list of 3rd-party database backend and does not in any way block folks from using it.

**Comment by Sfurti-yb** [comment]
@felixxm, since the CI setup PR is approved and merged now, could you tell the next steps to get this one approved as well.

**Comment by felixxm** [comment]
@Sfurti-yb Thanks :+1:  Welcome aboard :boat:

**Comment by Sfurti-yb** [comment]
Thank you @felixxm for being such a great help. When do the changes made here reflect on this [page](https://docs.djangoproject.com/en/4.0/ref/databases/#using-a-3rd-party-database-backend)

**Pull request merged**
