### PR TITLE
Fixed #31042 -- Removed AdminSeleniumTestCase.get_css_value() in favor of Selenium .is_displayed().

### PR DESCRIPTION
**Pull request by jdufresne**
https://code.djangoproject.com/ticket/31042

### CODE REVIEW

**Comment by carltongibson** [comment]
Question: Is this correct? 

> The style property is not useful for completely learning about the styles applied on the element, since it represents only the CSS declarations set in the element's inline style attribute, not those that come from style rules elsewhere, such as style rules in the <head> section, or external style sheets. To get the values of all CSS properties for an element you should use Window.getComputedStyle() instead. -- [MDN HTMLElement.style docs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style)

**Comment by jdufresne** [comment]
> CSS uses property instead of attribute.

Changed the `.get_css_value()` parameter to be named `prop` (avoided `property` to avoid shadowing the Python builtin). I also updated to the wordage in the docstring.

> I checked all uses and we only have 'display'.

Correct.

> We should convert to camelCase or document that we're accessing via JS.

Change what exactly to camelCase? As only `display` is used, and it has no 2nd word, I believe there is nothing left to convert. If I missed anything can you please identify it explicitly?

Let me know if you find the docstring changes sufficient.

> `jQuery()` could select multiple elements.

Yes, but jQuery's `.css` only operates on the first element in the list. From [the docs](https://api.jquery.com/css/):

> Get the value of a computed style property for the first element in the set of matched elements …

So this is the same "first element" behavior as before.

I've updated the docstring to help communicate this.

> Question: Is this correct?

Excellent point! The previous version returned the computed property. I've updated the PR so that it now continues to do so.

**Comment by jdufresne** [comment]
Although, now that I'm looking at this again ...

As `display` is the only CSS property analyzed, perhaps it would make more sense to assert Selenium `.is_displayed()` method instead. The diff for such a change is below. WDYT? Should I go ahead with this simplification?

```diff
diff --git a/django/contrib/admin/tests.py b/django/contrib/admin/tests.py
index d2d5eb1d09..748e67fd3f 100644
--- a/django/contrib/admin/tests.py
+++ b/django/contrib/admin/tests.py
@@ -133,14 +133,6 @@ class AdminSeleniumTestCase(SeleniumTestCase, StaticLiveServerTestCase):
         with self.wait_page_loaded():
             self.selenium.find_element_by_xpath('//input[@value="%s"]' % login_text).click()
 
-    def get_css_value(self, selector, prop):
-        """
-        Return the value of the computed style property of the first DOM
-        element matched by the given selector.
-        """
-        return self.selenium.execute_script(
-            'return window.getComputedStyle(document.querySelector("%s")).%s;' % (selector, prop))
-
     def select_option(self, selector, value):
         """
         Select the <OPTION> with the value `value` inside the <SELECT> widget
diff --git a/tests/admin_widgets/tests.py b/tests/admin_widgets/tests.py
index f854f4dc20..851e7eb123 100644
--- a/tests/admin_widgets/tests.py
+++ b/tests/admin_widgets/tests.py
@@ -743,19 +743,19 @@ class DateTimePickerSeleniumTests(AdminWidgetSeleniumTestCase):
         # First, with the date picker widget ---------------------------------
         cal_icon = self.selenium.find_element_by_id('calendarlink0')
         # The date picker is hidden
-        self.assertEqual(self.get_css_value('#calendarbox0', 'display'), 'none')
+        self.assertFalse(self.selenium.find_element_by_id('calendarbox0').is_displayed())
         # Click the calendar icon
         cal_icon.click()
         # The date picker is visible
-        self.assertEqual(self.get_css_value('#calendarbox0', 'display'), 'block')
+        self.assertTrue(self.selenium.find_element_by_id('calendarbox0').is_displayed())
         # Press the ESC key
         self.selenium.find_element_by_tag_name('body').send_keys([Keys.ESCAPE])
         # The date picker is hidden again
-        self.assertEqual(self.get_css_value('#calendarbox0', 'display'), 'none')
+        self.assertFalse(self.selenium.find_element_by_id('calendarbox0').is_displayed())
         # Click the calendar icon, then on the 15th of current month
         cal_icon.click()
         self.selenium.find_element_by_xpath("//a[contains(text(), '15')]").click()
-        self.assertEqual(self.get_css_value('#calendarbox0', 'display'), 'none')
+        self.assertFalse(self.selenium.find_element_by_id('calendarbox0').is_displayed())
         self.assertEqual(
             self.selenium.find_element_by_id('id_birthdate_0').get_attribute('value'),
             datetime.today().strftime('%Y-%m-') + '15',
@@ -764,11 +764,11 @@ class DateTimePickerSeleniumTests(AdminWidgetSeleniumTestCase):
         # Then, with the time picker widget ----------------------------------
         time_icon = self.selenium.find_element_by_id('clocklink0')
         # The time picker is hidden
-        self.assertEqual(self.get_css_value('#clockbox0', 'display'), 'none')
+        self.assertFalse(self.selenium.find_element_by_id('clockbox0').is_displayed())
         # Click the time icon
         time_icon.click()
         # The time picker is visible
-        self.assertEqual(self.get_css_value('#clockbox0', 'display'), 'block')
+        self.assertTrue(self.selenium.find_element_by_id('clockbox0').is_displayed())
         self.assertEqual(
             [
                 x.text for x in
@@ -779,11 +779,11 @@ class DateTimePickerSeleniumTests(AdminWidgetSeleniumTestCase):
         # Press the ESC key
         self.selenium.find_element_by_tag_name('body').send_keys([Keys.ESCAPE])
         # The time picker is hidden again
-        self.assertEqual(self.get_css_value('#clockbox0', 'display'), 'none')
+        self.assertFalse(self.selenium.find_element_by_id('clockbox0').is_displayed())
         # Click the time icon, then select the 'Noon' value
         time_icon.click()
         self.selenium.find_element_by_xpath("//a[contains(text(), 'Noon')]").click()
-        self.assertEqual(self.get_css_value('#clockbox0', 'display'), 'none')
+        self.assertFalse(self.selenium.find_element_by_id('clockbox0').is_displayed())
         self.assertEqual(
             self.selenium.find_element_by_id('id_birthdate_1').get_attribute('value'),
             '12:00:00',
```

**Comment by carltongibson** [comment]
Hey @jdufresne. Yes, that seems sensible. Good thoughts! :)

**Comment by jdufresne** [comment]
Done! :slightly_smiling_face:

**Comment by pope1ni** [comment]
> ...avoided `property` to avoid shadowing the Python builtin...

:+1:

> Change what exactly to camelCase? As only `display` is used, and it has no 2nd word,...

My point was that we should convert kebab-case to camelCase if this were to remain a generic function to get a CSS value. For example, I woulld expect to look up `'box-shadow'`, not `'boxShadow'`, which is what would be required if accessing as `element.style.boxShadow`.

> I've updated the docstring to help communicate this.

Yes, I was just asking for clarity.

> Question: Is this correct?

:eagle: Well spotted.

> ...perhaps it would make more sense to assert Selenium `.is_displayed()` method instead.

Haha. Nice, much better!

**Pull request merged**
