### PR TITLE
Fixed #25436 -- Protocol relative openlayers js / update OpenLayers to 2.13.1

### PR DESCRIPTION
**Pull request by blueyed**
This includes the fix for https://code.djangoproject.com/ticket/25436 and an update to the current bugfix release of the OpenLayers JS lib.

### CODE REVIEW

**Comment by blueyed** [comment]
Unfortunately this does not work currently: https://github.com/openlayers/openlayers.github.io/issues/53 - waiting for feedback there.

**Comment by timgraham** [comment]
@blueyed, please bump the ticket to "Accepted" once we're no longer blocked on making the relative protocol change. I'll close this for now.

**Comment by blueyed** [comment]
@timgraham
It would be possible to use  CDN already..

**Comment by timgraham** [comment]
Can you submit the PR?

**Comment by blueyed** [comment]
Submitted https://github.com/django/django/pull/7056 as a follow-up.

**Pull request closed without merging**
