### PR TITLE
Fixed #27356 -- Admin lookup_allowed incorrectly returns False for a nested reverse OneToOneField

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Comment by felixxm** [comment]
docs build failure is not related with this PR

**Comment by tobiasmcnulty** [comment]
I've tested this locally and it seems to work, however, the same problem seems to exist for `ForeignKey` fields if they appear after a `OneToOneField` (this test fails, even with the code in this PR):

	diff --git a/tests/admin_filters/tests.py b/tests/admin_filters/tests.py
	index 4a49f4c..55bf03b 100644
	--- a/tests/admin_filters/tests.py
	+++ b/tests/admin_filters/tests.py
	@@ -235,7 +235,7 @@ class EmployeeAdmin(ModelAdmin):
	 
	 
	 class EmployeeProfileAdmin(ModelAdmin):
	-    list_filter = ['employee__employeeinfo__description']
	+    list_filter = ['employee__employeeinfo__description', 'employee__department__code']
	 
	 
	 class DepartmentFilterEmployeeAdmin(EmployeeAdmin):
	@@ -686,6 +686,17 @@ class ListFiltersTests(TestCase):
	         queryset = changelist.get_queryset(request)
	         self.assertEqual(list(queryset), [john_profile])
	 
	+    def test_listfilter_onetoone_foreignkey(self):
	+        john_profile = EmployeeProfile.objects.create(employee=self.john)
	+
	+        modeladmin = EmployeeProfileAdmin(EmployeeProfile, site)
	+        request = self.request_factory.get('/', {'employee__department__code': 'DEV'})
	+        changelist = self.get_changelist(request, EmployeeProfile, modeladmin)
	+
	+        # Make sure the correct queryset is returned
	+        queryset = changelist.get_queryset(request)
	+        self.assertEqual(list(queryset), [john_profile])
	+
	     def test_relatedonlyfieldlistfilter_manytomany(self):
	         modeladmin = BookAdminRelatedOnlyFilter(Book, site)
	 
Am I missing something here or should this work as well? I would at least like to better understand what the `if not prev_field or field not in prev_field.get_path_info()[-1].target_fields:` line is supposed to do before merging this.

**Comment by felixxm** [comment]
It is not allowed to filter on values that would be found from local model anyways, hence if you want to filter on `employee__department__code` then you should use `employee__department_id` instead.

```diff
--- a/tests/admin_filters/tests.py
+++ b/tests/admin_filters/tests.py
@@ -235,7 +235,7 @@ class EmployeeAdmin(ModelAdmin):
 
 
 class EmployeeProfileAdmin(ModelAdmin):
-    list_filter = ['employee__employeeinfo__description']
+    list_filter = ['employee__employeeinfo__description', 'employee__department_id']
 
 
 class DepartmentFilterEmployeeAdmin(EmployeeAdmin):
@@ -686,6 +686,17 @@ class ListFiltersTests(TestCase):
         queryset = changelist.get_queryset(request)
         self.assertEqual(list(queryset), [john_profile])
 
+    def test_listfilter_onetoone_foreignkey(self):
+        john_profile = EmployeeProfile.objects.create(employee=self.john)
+
+        modeladmin = EmployeeProfileAdmin(EmployeeProfile, site)
+        request = self.request_factory.get('/', {'employee__department_id': 'DEV'})
+        changelist = self.get_changelist(request, EmployeeProfile, modeladmin)
+
+        # Make sure the correct queryset is returned
+        queryset = changelist.get_queryset(request)
+        self.assertEqual(list(queryset), [john_profile])
+
```

**Comment by timgraham** [comment]
I'm not following why the case Tobias presented isn't valid. If it's not valid, it seems like it should raise an error during the `list_filter` system check rather than having a `DisallowedModelAdminLookup` at runtime.

**Comment by tobiasmcnulty** [comment]
Also, according to the comment in the code it **is** allowed to filter on fields that can be found from the local model anyways, and the comment suggests that the line edited by this PR is special-casing that allowance.

Whether or not something is allowed should be controlled only by `list_filter` and Django's underlying ability to make the join, not by anything in this method, if I understand correctly.

**Comment by felixxm** [comment]
I think it's typo in comment and should be `It is not allowed`. [Condition](https://github.com/django/django/commit/8f30556329b64005d63b66859a74752a0b261315#diff-3c42de3e53aba87b32c494f995a728dfR347): ```field not in prev_field.get_path_info()[-1].target_fields)``` prevents such situation (it was added in [8f3055](https://github.com/django/django/commit/8f30556329b64005d63b66859a74752a0b261315)). Moreover after removing it `admin_views.tests.AdminViewBasicTest.test_disallowed_filtering` fails which leads to [732198](https://github.com/django/django/commit/732198ed5c2a127249970e0cd4218d093a38e9a2) and security issue fix, but I can not find more details.

I can try to move those restrictions to `list_filter`.

**Comment by timgraham** [comment]
I don't think the comment is a typo. The idea is that `list_filter = ['employee__department__id']` is fine even if the user can't access `Department` because `department_id` is a local field of `Employee`.

**Comment by timgraham** [comment]
@felixxm, plan to return to this soon?

**Comment by felixxm** [comment]
I don't have idea how to fix this without breaking `admin_views.tests.AdminViewBasicTest.test_disallowed_filtering`. Maybe I will back to this issue later.

**Pull request closed without merging**
