### PR TITLE
Fixed #26006 -- Fixed incorrect object reference in SingleObjectMixin.get_context_object_name().

### PR DESCRIPTION
**Pull request by chmarr**
Changed 'self.object' to 'obj' to be consistent with the rest
of the method. No impact on test cases.

### CODE REVIEW

**Comment by timgraham** [comment]
Could you please add a test as well as a mention in the 1.9.1 release notes?

**Comment by chmarr** [comment]
@timgraham: You bet.

**Comment by chmarr** [comment]
Test case added. The custom view that highlights the problem is admittedly convoluted, highlighting how rarely someone will run into this, but also highlights that the level where self.object _must_ be set could be better defined. Release notes updated. Also, hopefully I didn't break anything with a "git push --force".

**Comment by chmarr** [comment]
Amended commit to fix merge conflict.

**Comment by timgraham** [comment]
merged in 4b2dcfe04f5d9938e40c569ffdd169f3a712145d, thanks!

**Pull request closed without merging**
