### PR TITLE
Refs #31015: Test geometry round-trip on Oracle 18.

### PR DESCRIPTION
**Pull request by sir-sigurd**

### CODE REVIEW

**Comment by sir-sigurd** [comment]
buildbot, test on oracle.

**Comment by sir-sigurd** [comment]
buildbot, test on oracle.

**Comment by sir-sigurd** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
Closing per ticket.

**Pull request closed without merging**
