### PR TITLE
Added raw sql streaming example with headers to docs/howto/outputting-csv

### PR DESCRIPTION
**Pull request by alan-hicks**
Example of a lightweight wrapper streaming results from raw sql
with headers.  Demonstrates adding headers in a generator function,
using datetime to format an attachment filename, and using
cursor.execute with params.

### CODE REVIEW

**Comment by charettes** [comment]
I'm not convinced this adds much value to the existing example. Maybe we could alter it to output columns and a timestamp'ed filename instead?

By the way using [`seek()`, `read()` and `truncate()` was deemed too un-Pythonic to be used as en example](https://code.djangoproject.com/ticket/21179) in the original ticket so you might want to re-use the `Echo` object.

**Comment by alan-hicks** [comment]
Example updated to use Echo() instead of StringIO

Typical column count can be between 10-50 so unrealistic to include them in a filename.

Although a common use case, there appear to be no streaming csv examples from a google or stackexchange search that output a header row followed by data from a sql cursor. Either header or data is straightforward, it's the combination of both that is the value of this example.

This example can be copy, pasted and used as the basis for most real world raw sql output.

**Comment by timgraham** [comment]
I don't know, this is repeating a lot from the first example. In my opinion, the Django docs needn't explain or demonstrate every use case here. Maybe some concepts could be explained better so that someone could arrive at the code you wrote by reading the existing example. Providing copy/paste examples seems more suitable to a site like https://djangosnippets.org/.

**Comment by alan-hicks** [comment]
Ok, if it doesn't add enough value then it shouldn't add noise.

**Pull request closed without merging**
