### PR TITLE
Refs #30102 -- Optimized the `page_not_found` view after #30070.

### PR DESCRIPTION
**Pull request by illia-v**
https://code.djangoproject.com/ticket/30102

### CODE REVIEW

**Comment by timgraham** [comment]
Tests are breaking because even though the context variables aren't used in the template, it makes them available for tests (`response.context`). I guess we might have to "wontfix" the ticket and instead add a comment about this.

**Comment by illia-v** [comment]
Hm. Agree.

Is there a way of adding the context variables to responses without rendering templates?

**Comment by timgraham** [comment]
I don't think so. Template context variables are only relevant for ... templates. :-)

**Comment by carltongibson** [comment]
An alternative here is to add a `404.html` for the failing tests. (Adding one globally triggers a failure ref 784377544e01322b0d09e5cf4e8f6dda159df854.) Not worth the effort I think. This'll hardy be a performance bottleneck.

**Comment by carltongibson** [comment]
Closing as per ticket.

**Pull request closed without merging**
