### PR TITLE
Fixed #28754 - Fixed validation of 0.x.x.x when x!=0 addresses

### PR DESCRIPTION
**Pull request by timgivois**
https://code.djangoproject.com/ticket/28754

### CODE REVIEW

**Comment by timgraham** [comment]
Did you see [my concerns](https://code.djangoproject.com/ticket/28754#comment:5) on the ticket?

**Comment by timgivois** [comment]
Yes @timgraham, I'm should work on a version that comes from master, right? I'm going to close this thread as this version doesn't apply to master..

**Comment by timgraham** [comment]
You can change the target branch and push a new commit to this PR. The main concern is about increasing the complexity of the regular expression for perhaps minimal gain.

**Comment by timgivois** [comment]
Oh, yes, you are right. I was thinking, as master is using `ipaddress` instead of a regex, we could add one or two simple regex along with the package parsing to detect `0.x.x.x when x!=0`, what do you think?

**Comment by timgraham** [comment]
Perhaps we should check if cpython would change `ipaddress.IPv4Address()` to fix the issue. If so, I don't think it's so critical that we patch Django for existing Python versions.

**Comment by timgivois** [comment]
Yes, that would be a better approach.

**Comment by timgivois** [comment]
yes, I agree with that.

**Pull request closed without merging**
