### PR TITLE
Fixed #25484 -- Made static template tag render escaped URLs.

### PR DESCRIPTION
**Pull request by alix-**
https://code.djangoproject.com/ticket/25484

### CODE REVIEW

**Comment by alix-** [comment]
Missed past tense in commit, message. Sorry.

**Comment by charettes** [comment]
Buildbot, add to whitelist.

**Comment by alix-** [comment]
Done! 👍

**Comment by timgraham** [comment]
The test is in staticfiles_tests but you haven't touched `contrib.staticfiles`. The code is shared, but I wonder if a test also/or in `tests/template_tests/syntax_tests/test_static.py` would be appropriate.

**Comment by apollo13** [comment]
@timgraham I just look over the patch in master, what is the `unquote` doing there? This is potentially wrong if the file in question contains a for instance `&amp;` etc…

**Comment by timgraham** [comment]
Without `unquote()` the URLs in the new tests render as `/static/test.html%3Ffoo%3D1%26bar%3D2` and a URL encoded like that isn't treated as having a query string and so gives a 404  -- tested this in `<img src="{% static "..."%}`. This is the behavior before this patch.

I can't say confidently that patch is correct one way or another, though, so if you want to think about that more, great!

Unrelated, but I noticed that this patch seems required to test the `urljoin(PrefixNode.handle_simple("STATIC_URL"), path)` branch of `StaticNode.handle_simple()`. Otherwise the two test files modified here are testing the same code.
```diff
diff --git a/tests/template_tests/syntax_tests/test_static.py b/tests/template_tests/syntax_tests/test_static.py
index 0cbe23a..cd04b28 100644
--- a/tests/template_tests/syntax_tests/test_static.py
+++ b/tests/template_tests/syntax_tests/test_static.py
@@ -5,7 +5,7 @@ from django.utils.six.moves.urllib.parse import urljoin
 from ..utils import setup
 
 
-@override_settings(MEDIA_URL="/media/", STATIC_URL="/static/")
+@override_settings(INSTALLED_APPS=[], MEDIA_URL="/media/", STATIC_URL="/static/")
 class StaticTagTests(SimpleTestCase):
     libraries = {'static': 'django.templatetags.static'}
 
````
I'll make that change after the investigation is finished here.

**Comment by apollo13** [comment]
Ok, so for my following analysis I am completely ignoring what Django currently allows for or not, I am only thinking about what I'd expect it to do. Given that staticfiles operates on files and in general as such has no concept of query params, I think it is safe to assume and expect that the static functions are passed filenames/paths. Filenames (or rather file paths) literally allow basically every character aside from a null byte (depending on your system).

Iff we agree that this assumption is correct the following steps seem logical:
 * To generate a URL, we are forced to run the file through urlquote, since it might contain characters not suitable in this form as part of the URL (most notably a "?" since that would mark the start of the query params).
 * Since URL generation can add API access keys, the final URL can indeed contain unquoted "&" and "?", which is completely valid and should be allowed.
 * When it comes to HTML though, we still have to run it through HTML escape since it might contain otherwise invalid or (thanks to browser parsing of & in that context) ambiguous characters.

Here is a sample python script to play with:
```
from django.utils.html import escape
from django.utils.http import urlquote

# Arguments to static are imho are supposed to files, this means
# that literally everything has to be accepted as is. As a result
# I'd expect
static_file = 'test.html?foo=2&bar=3'
# be literally a file named such without any query params.

# To use this file name as part of the URL we'd need to urlquote it:
static_file_quoted = urlquote(static_file)

# to use it inside HTML we still need to apply escaping
static_file_final = escape(static_file_quoted)

static_url = "http://apolloner.eu/~apollo13/%s?real=param" % static_file_final

# the resulting html for tests in browsers

print("""<!DOCTYPE html>
<html>
    <head>
      <title>TESTPAGE</title>
    </head>
    <body>
        <div>
      <a href="%s">TEST LINK</a>
        </div>
    </body>
</html>
""" % static_url)
```

Run it and safe it as html locally to play with it, I've add two files on apolloner.eu which you can use to check if you reached the correct endpoint:
 * http://apolloner.eu/~apollo13/test.html%3Ffoo%3D2%26bar%3D3
 * http://apolloner.eu/~apollo13/test.html

FWIW, I am in favor of breaking backwards compat here if needs be.

**Comment by timgraham** [comment]
That analysis looks correct. `Storage.url()` is responsible for returning a quoted URL, so `{% static %}` is only responsible for applying `conditional_escape` and shouldn't `unquote()`. PR: https://github.com/django/django/pull/7714.

**Pull request merged**
