### PR TITLE
Fixed #29654 -- Made Truncator use ellipsis character instead of three dots. -- Test cases and .po

### PR DESCRIPTION
**Pull request by ovelindstrom**
Additional patch to PR #10280 

Fixed the test cases and changed the .po-files for all the translations.

Additional fixes to https://code.djangoproject.com/ticket/29654#ticket

### CODE REVIEW

**Comment by timgraham** [comment]
po files shouldn't be changed as those updates have to be made in Transifex. In the future, please run the tests locally and fix failures before creating a pull request.

**Comment by ovelindstrom** [comment]
Withdrawn.

**Comment by ovelindstrom** [comment]
@timgraham Should we just dump this PO and redo it the right way?

**Comment by timgraham** [comment]
No need to open a new PR, you can amend this one.

**Comment by debugger22** [comment]
Commits not preserved :(

**Comment by ovelindstrom** [comment]
Let us reopen #10280 and skip this PR. @timgraham

**Pull request closed without merging**
