### PR TITLE
Fixed #28284 -- Prevented Paginator's unordered object list warning from evaluating a QuerySet.

### PR DESCRIPTION
**Pull request by orf**
Ref: [#28284](https://code.djangoproject.com/ticket/28284)

### CODE REVIEW

**Comment by timgraham** [comment]
As in the first example at https://docs.djangoproject.com/en/dev/topics/pagination/, `object_list` might not be a queryset and thus might not have a `model` attribute.

**Comment by orf** [comment]
Hmm, good point, I assumed the hasattr checks would suffice for this case. I could add an explicit isinstance check, perhaps? If it's not a query set then the current code is fine.

**Comment by timgraham** [comment]
I think ducktyping with `hasattr` is preferred to `isinstance` (which would couple pagination with `django.db`). Perhaps you can add a test for paginating a list in a separate PR that we can merge before this one.

**Comment by timgraham** [comment]
Well actually, I guess a list wouldn't pass the `hasattr(self.object_list, 'ordered')` check -- not sure if there's a different datastructure that would pass that but not have `model`.

**Comment by orf** [comment]
Well, we could always do `getattr(self.object_list, 'model', self.object_list)` as the thing to be formatted, just in case?

**Comment by orf** [comment]
Model can also be none, which isn't great, no idea how to handle that.

**Comment by orf** [comment]
@timgraham I added a test for an object that has an `ordered` attribute but not a `model` one. Also, with properties, `hasattr()` actually executes the property, so I used a `getattr` with a `None` default to only execute it once.

The warning now displays `Model: <model repr>` if there is a model, otherwise it displays `object_list: <repr of object_list>`.

**Pull request merged**
