### PR TITLE
Refs #27090 -- Added real database sequence introspection

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
@claudep Sorry 😞. I assumed that _"Squash and merge"_ would behave differently and keep you as an author.

**Comment by claudep** [comment]
@felixxm I'm granting you my pardon :-)

**Pull request merged**
