### PR TITLE
Changed signatures of setting_changed signal receivers.

### PR DESCRIPTION
**Pull request by adamchainz**

### CODE REVIEW

**Review by ngnpope — APPROVED** [review]
LGTM. This is something that only became possible with being able to specify keyword-only arguments since Python 3.0.

(Test failure is unrelated and flaky.)

**Comment by adamchainz** [comment]
> (Test failure is unrelated and flaky.)

Is this being investigated?

**Comment by felixxm** [comment]
> > (Test failure is unrelated and flaky.)
> 
> Is this being investigated?

Yes, see ticket-32831.

**Comment by felixxm** [comment]
@adamchainz Thanks :+1:

**Pull request merged**
