### PR TITLE
Fixed #25132 -- Added the get_value() method to the QuerySet class

### PR DESCRIPTION
**Pull request by thedrow**
The method gets a single value from a single object and returns it.
I also covered get() with tests that match get_value()'s tests.

### CODE REVIEW

**Comment by charettes** [comment]
Isn't this already achievable with `values_list('field', flat=True).get(pk=1)`?

**Comment by thedrow** [comment]
I'm not sure but I think that would return a list anyway. I'd like to fetch a single field from the database.

**Comment by charettes** [comment]
I just tried it and it returns a single value from the database. I don't think we need to introduce another method for this use case.

**Comment by thedrow** [comment]
@charettes I just checked myself and it returned a tuple with the field's value.
The method just provides some syntax sugar for those who need it.

**Comment by charettes** [comment]
It cannot return a tuple if you use the `flat=True` kwarg. You even use this method in your `get_value` implementation.

**Comment by thedrow** [comment]
That's a surprise. I would suggest a documentation change instead.

**Pull request closed without merging**
