### PR TITLE
Added EMAIL_USE_SSL to the Core Settings Topical Index Docs.

### PR DESCRIPTION
**Pull request by github-user-en**
Added `EMAIL_USE_SSL` to the Core Settings Topical Index.

#### Trac ticket number

N/A

#### Branch description

Added `EMAIL_USE_SSL` to the Core Settings Topical Index.

#### Checklist
- [x] This PR targets the `main` branch. 
- [x] The commit message is written in past tense, mentions the ticket number, and ends with a period.
- [x] I have checked the "Has patch" ticket flag in the Trac system.
- [ ] I have added or updated relevant tests.
- [x] I have added or updated relevant docs, including release notes if applicable.
- [ ] I have attached screenshots in both light and dark modes for any UI changes.

### CODE REVIEW

**Comment by cliff688** [comment]
Hello.

Rename your PR to "Added EMAIL_USE_SSL to the Core Settings Topical Index Docs." so the title says exactly what the patch does.

**Review by cliff688 — APPROVED** [review]

**Comment by github-user-en** [comment]
Ah! My bad. Thanks for pointing out.
Did both of those changes.

**Review by cliff688 — APPROVED** [review]
Thank you!
Now you should squash your commits into one. Squashed commits are preferred.

**Review by mahfuztbt — APPROVED** [review]

**Comment by github-user-en** [comment]
Makes sense! Thanks for pointing out.
Squashed the two commits into one.

**Review by sarahboyce — APPROVED** [review]
Well spotted - thank you!
Welcome onboard @github-user-en :boat:

**Pull request merged**
