### PR TITLE
Fixed #25822 -- Added require_HEAD, require_OPTIONS, require_PUT, require_DELETE decorators.

### PR DESCRIPTION
**Pull request by CrazyPython**
Issue opened by me on ticket tracker here: https://code.djangoproject.com/ticket/25822

### CODE REVIEW

**Comment by sir-sigurd** [comment]
Could you rework commit message in accordance with the [guidelines](https://docs.djangoproject.com/en/1.9/internals/contributing/committing-code/#committing-guidelines)?

**Comment by sir-sigurd** [comment]
Tests should be added also.

**Comment by aaugustin** [comment]
The discussion on the ticket questions the usefulness of this addition.

**Comment by timgraham** [comment]
Closing per ticket.

**Pull request closed without merging**
