### PR TITLE
Replaced isinstance test by field attribute

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by timgraham** [comment]
Did you have a particular motivation? See [#24227](https://code.djangoproject.com/ticket/24227) for some discussion.

**Comment by claudep** [comment]
No, I just stumbled over this while browsing code for another issue. Do you think we could commit this (piece meal) or would you like to do at all at once with #24227? Feel free to close the PR in the latter case.

**Comment by timgraham** [comment]
I don't know. I think it's difficult to make a decision about the replacements in general without seeing how custom fields with  use the flags. For example, it looks like this change would impose the requirement that a custom field with `many_to_many=True` have a `value_from_object()` method (currently undocumented) that return a queryset. Should we be concerned and/or document requirements like this? If we start changing some isinsatnce checks but not others, it could be confusing to authors trying to make custom fields work.

**Comment by claudep** [comment]
Let's close it for now.

**Pull request closed without merging**
