### PR TITLE
Refs #25612 -- Implemented MFA.

### PR DESCRIPTION
**Pull request by Yona5**
https://groups.google.com/g/django-developers/c/T-kBSvry6z0/
https://code.djangoproject.com/ticket/25612

Opening this PR to get early feedback and community participation.

How-to: 

- Add django.contrib.mfa to INSTALLED_APPS
- Run migration
- Set MFA_IS_ACTIVE to True in the settings module
- Include django.contrib.mfa.urls in the URLconf
- Install the third-party package qrcode
- Go to the admin page and login. MFA is at the top-right corner

Notes:

The mfa app aims to implement 2fa with only a QR code generator dependency.

It supports TOTP, email, and SMS. However, SMS is not yet fully implemented as validating phone numbers and sending SMSs require other dependencies. So, how do we go about it?

One possible solution is performing a simple phone number validation, handing the OTP (using a signal) to developers, and letting them handle the process of sending the SMS. This approach also opens up the door to voice calling.

Next steps:

- Make changes and improvements
- Add tests
- Write documentation
- Remove a CSS dependency
- Stick with qrcode or try to support other QR code generators

FAQ:

- Why not support HOTP?
Authenticator apps such as Authy, and Microsoft don't support HOTP.
Both TOTP and HOTP are similar from the users' point of view.

### CODE REVIEW

**Comment by apollo13** [comment]
Hi, as I pointed out in https://groups.google.com/g/django-developers/c/GEJwPyItjwE -- at the very least we need to support Webauthn. After that TOTP is an okayish fallback; we will never support SMS in core though.

**Comment by Yona5** [comment]
Is there a reason why SMS will never be supported? If it’s a security concern, compared to the other 2fa options, SMS can be less secure. However, it still does its job at preventing account takeovers. It helped block 100% of automated bots, 96% of bulk phishing attacks, and 76% of targeted attacks [1].

Let me reiterate what I said in that discussion. Webauthn supports 2fa. But this doesn’t seem to be what it is trying to achieve primarily; It is a passwordless authentication and should be an alternative to the password-based Django auth [2].

[1] https://security.googleblog.com/2019/05/new-research-how-effective-is-basic.html
[2] https://www.apple.com/newsroom/2022/05/apple-google-and-microsoft-commit-to-expanded-support-for-fido-standard/

**Comment by apollo13** [comment]
> Is there a reason why SMS will never be supported?

I did not say it will never be supported, I just said that we wouldn't add it in core. Given that sending SMS usually requires a paid service and dependency on external APIs I wouldn't want to see this inside core. 

> However, it still does its job at preventing account takeovers.

Sure, but so does a TOTP I'd say? Basically every second factor makes account takeovers harder.

> Webauthn supports 2fa. But this doesn’t seem to be what it is trying to achieve primarily; It is a passwordless authentication and should be an alternative to the password-based Django auth

Just because the main focus of apple and microsoft for webauthn will be on passwordless authentication, this doesn't make the 2fa factor of it any less useful. Think of services like Github, Dropbox, Google, Gitlab etc… They do __all__ support 2fa webauthn. It is also somewhat forward thinking because the code to handle resident & non-resident keys is roughly the same. And no matter how we spin it, a hardware based second factor utilizing webauthn is afaik the only factor providing a phishing resistant experience -- why would you not want to add it? With attestation it can even offer higher assurance like restricting to your company issues tokens etc…

Last but not least I think a change like adding mfa will need a DEP. There are several design decisions to consider which I do not think can be discussed simply inside a PR.

 * What does `is_authenticated` mean in the context of mfa. 
 * How are we going to expose the LoA (level of authentication). 
 * Assuming the LoA is not high enough for certain actions, how can be reprompt.

**Comment by Yona5** [comment]
> I did not say it will never be supported, I just said that we wouldn't add it in core. 

Yea. The question was about its support in core. 

>Given that sending SMS usually requires a paid service and dependency on external APIs I wouldn't want to see this inside core.

As mentioned in the notes section of the first comment, here is one proposed solution. Django can focus on generating and verifying OTPs when it comes to SMS. And developers will handle the rest of the process, such as sending the SMS. I hope this addresses the problem.

> ...this doesn't make the 2fa factor of it any less useful...

Valid points. I am not questioning Webatuhn as 2fa or its ability to protect users. It primarily promotes passwordless authentication, and using it as 2fa in Django defeats the purpose. But again, this is only a suggestion. Webatuhn 2fa is a legit use case.

>why would you not want to add it?

I had updated my answer before I saw your reply. Please take a look at the previous comment.

>What does is_authenticated mean in the context of mfa.

It behaves as it did before.

>How are we going to expose the LoA (level of authentication).

If I understood your question correctly, it's through the settings module.


The MFA app introduces only one change to the login flow. It starts its job after Django authenticates the user and right before it logs in the user. It checks whether MFA is active in the settings module and whether the user has activated MFA.

If the above conditions are met, it redirects the user to a page where they can enter an OTP. If the OTP is valid, it will log in the user. If multiple invalid attempts are made, it'll prompt the user to try again after some time.

Otherwise, it has no involvement in Django's login process.

Maybe I have missed something, but let me know if this needs a  DEP.

**Comment by apollo13** [comment]
> As mentioned in the notes section of the first comment, here is one proposed solution. Django can focus on generating and verifying OTPs when it comes to SMS.

I think in general one would not generate and validate those OTPs in Django at all when using SMS, so it is imo way more important to get the base class API right than supporting SMS. Once the base class is correct then adding SMS is just a matter of calling an external service. If you are wondering now why I am saying that one would not generate or validate OTPs when sending SMS is because there are services like https://developer.nexmo.com/api/verify which I think are preferred over manually sending your OTP SMS. Why? Given that those services provide limited control over the text they are rather spam safe and usually have a better chance of arriving on the enduser device (due to the fact that they are also shortlived providers tend to give them preferential treatment when they get overloaded).

> That being said, it does not have to be an either/or situation. When/if Django supports Webauthn, it can also provide a way to use Webauthn as 2fa.

Again, no from my side. We are not going to add mfa without supporting the strongest form of authentication that we can have. Supporting webauthn is also relatively critical in terms of API extensibility and readiness. TOTP/Email/SMS all basically just require a simple text box and that's it. Any more advanced authentication (like webauthn) will require some more advanced frontend capabilities. And to ensure that our API can handle that nicely we will have to implement one of those.

> > What does is_authenticated mean in the context of mfa.
> 
> It behaves as it did before.

That is a good start.

> > How are we going to expose the LoA (level of authentication).
> 
> If I understood your question correctly, it's through the settings module.

Yeah I am not sure if that is enough. For instance github asks you to reenter your password (or security) for some sensitive things. If we want to support something like this we might have to store the used token and it's "security level" in the session etc… Note that I am not saying that we have to support something like this but we should consider those things.

> Maybe I have missed something, but let me know if this needs a DEP.

Let's put it this way: I honestly do not know what is easier. Writing a DEP is not easy and rewriting code a hundred times (a few times substantially) isn't easy either. In the end it helps if a DEP is accepted because then we decided what we want to implement and can mostly follow the DEP. Without a DEP we will go through quite a few iterations of code. Nevertheless I think even without a DEP we should at first very clearly decide on *what* we want to support and get consensus on that before you invest substantial time in implementing something that will not be merged. For instance there is a very very high reluctance in adding settings to Django, yet PR currently proposes 9 with inconsistent naming etc.

**Comment by ollytheninja** [comment]
Given the issue and discussion referenced are 7 years old now, I think it would be wise to have some more discussion about what modern authentication might look like in Django before something like this is added.

While TOTP will only be a second factor, however many organizations are adopting "magic link" as a single factor for authentication. Similarly as discussed in this thread, WebAuthN is generally tied to a device (i.e. "something I have" factor) and used as a second factor after password ("something I know" factor). However it is starting to be adopted more and more as a single factor for authentication.
It would therefore make more sense to me, for a "MFA" module to adopt a pluggable approach where the developer can choose which factors and in which combination they want to use them (this includes whether or not password is even used).

The other major issue as raised previously in this thread is "confidence" or "risk" of a session.
Such a module could provide functionality similar to the `login_required` decorator / mixins to allow the developer to kick a user back to some extra authentication if their session does not meet a certain level (e.g. only authenticated with a single factor).
This would also allow modern SaaS authentication services such as Duo Security, Okta etc. to provide device attestation etc. as a risk score as part of authentication to add to such a score.

Such a pluggable architecture would also mean new mechanisms can be plugged in without Django needing to decide for example whether to support SMS.

Is there a reason this can't be a third party module first and then adopted into contrib once it has been adopted / tested?

**Comment by StevenMapes** [comment]
Currently I'm using this https://github.com/oliwarner/django-multifactor for MFA because it supports additional custom transport factors pretty easily so I wrote one to use AWS SNS. It doesn't support WebAuthN as a native factor but does allow users to choose which factors and fallbacks they wish to enable and allows you to specify how many factors are required per view allowing some to have more then 2-factors be required

**Comment by carltongibson** [comment]
I'm going to close this currently. As much as there's appetite for a solution here, there's still an amount of background work to be done before considering a PR: 

> ...even without a DEP we should at first very clearly decide on what we want to support and get consensus on that...

Thanks for the input so far @Yona5! 

> Is there a reason this can't be a third party module first and then adopted into contrib once it has been adopted / tested?

Likely, it can: there's already (several? 🤔) options. A good first step would be an overview of those.

**Pull request closed without merging**
