### PR TITLE
Refs #28622 -- Clarified security implications of PASSWORD_RESET_TIMEOUT.

### PR DESCRIPTION
**Pull request by spookylukey**
I meant to write this up after the [discussion](https://groups.google.com/d/msg/django-developers/65iOQunvkPY/pP5mF-44AQAJ) for [ticket 28622](https://code.djangoproject.com/ticket/28622), finally got around to it :-)

### CODE REVIEW

**Comment by felixxm** [comment]
@spookylukey Thanks! I moved this to the related PR #11705.

**Comment by felixxm** [comment]
Merged in 45304e444e0d780ceeb5fc03e6761569dfe17ab2.

**Comment by spookylukey** [comment]
Thanks @felixxm . I think there is now a small typo/grammar issue — "make difference" should be "make a difference" or "make any difference".

**Comment by felixxm** [comment]
Good catch, thanks :+1: Fixed in 28e769dfe6a65bf604f5adc6a650ab47ba6b3bef.

**Pull request closed without merging**
