### PR TITLE
[WIP] Fixed #28469 -- Added missing HttpResponse subclasses

### PR DESCRIPTION
**Pull request by adamchainz**
[ticket](https://code.djangoproject.com/ticket/28469)

### CODE REVIEW

**Comment by adamchainz** [comment]
This is WIP atm. I have only added 2XX status codes and haven't added some custom behaviour such as `HttpResponseNoContent` blocking `content` like `HttpResponseNotModified` does.

The docs are tricky - rather than keep them in status code order, I made the redirect classes a heading of their own, before the rest. Whilst this cuts back on the noise newcomer have to sift before discovering `HttpResponseRedirect`, it does make it harder to scroll through and read off all the classes... Still wondering on this point 🤔

**Comment by ngnpope** [comment]
Sorry about that. The mobile website doesn't provide the review feature (and a lot of other things).

**Comment by adamchainz** [comment]
I'm going to follow Tim's recommendation from the mailing list and document {{http.HTTPStatus}} as a way of getting at the more obscure types, rather than implement them all. I'm sure 99.999% of Django app's don't need `HttpResponseMultiStatus`

**Comment by timgraham** [comment]
Please reopen if you return to this.

**Pull request closed without merging**
