### PR TITLE
Refs #25251 -- Filtered out skipped tests when processing the test suite to set _next_serialized_rollback.

### PR DESCRIPTION
**Pull request by romgar**
Reported at https://github.com/django/django/pull/7528#issuecomment-437196837.

### CODE REVIEW

**Comment by timgraham** [comment]
Could you add a regression test? Currently we have a non-deterministic failure when running the entire test suite which would be quite difficult to debug if this regresses.

**Comment by timgraham** [comment]
I tried adding a test but it doesn't pass. I may have very well made a mistake somewhere as I didn't get very far in my investigation but I added the test here in case you look at the issue before I get back to it.

**Comment by timgraham** [comment]
The patch is working now. The issue was that the test needed to `skipUnlessDBFeature` instead of `skip`. With `skip`, the test was already filtered out somewhere before `reorder_postprocess()`.

**Comment by romgar** [comment]
Thanks @timgraham. I'm quite busy these days, I really appreciate your help.

**Comment by timgraham** [comment]
Can reproduce with `./tests/runtests.py --parallel=1 -v 2 --reverse migration_test_data_persistence inspectdb` and even comment out tests in `inspectdb` until you have these minimal tests:
```
test_persistence (migration_test_data_persistence.tests.MigrationDataNormalPersistenceTestCase) ...
ok
test_include_views (inspectdb.tests.InspectDBTransactionalTests) ... ok
test_foreign_data_wrapper (inspectdb.tests.InspectDBTransactionalTests) ... skipped 
test_persistence (migration_test_data_persistence.tests.MigrationDataPersistenceTestCase) ... failed
```
The issue is that a test will only have `__unittest_skip__` set if a skip decorator is applied to the test class, not if a test method is decorated. I'm not sure of a solution so I'm afraid it might be time to revert the original patch until someone has time to dive in.

**Pull request merged**
