### PR TITLE
Fixed #25030 - observe existing (external) authentication even for POST.

### PR DESCRIPTION
**Pull request by adelton**

### CODE REVIEW

**Comment by timgraham** [comment]
This breaks a test:
```
======================================================================
FAIL: test_double_login_is_not_allowed (admin_views.tests.AdminViewPermissionsTest)
Regression test for #19327
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/tests/admin_views/tests.py", line 1538, in test_double_login_is_not_allowed
    self.assertEqual(login.status_code, 200)
AssertionError: 302 != 200
```

**Comment by adelton** [comment]
I guess that test is no longer relevant because with login being done on separate URL (/admin/login), the issue https://code.djangoproject.com/ticket/19327 can no longer happen. Or am I missing some context?

**Comment by timgraham** [comment]
I'm not sure without looking into the code and related issues a bit more. Maybe @claudep can give his input as author of be0ad629 where the check for `request.method == 'GET'` was added.

**Comment by claudep** [comment]
I'll comment on the ticket.

**Comment by adelton** [comment]
Per comments in https://code.djangoproject.com/ticket/25030, moving the logic change to django.contrib.auth so every login would benefit from it: a497f111cf959b23163c030745e4cb18be7eb0a9.

**Comment by timgraham** [comment]
Have you had a look at the test failures?

**Comment by adelton** [comment]
> Have you had a look at the test failures?

Not yet reall. We are looking at changing behaviour so I assume most of them are expected. What I currently wonder most at this point is whether the approach, changing `django.contrib.auth.views.login` the way the last patch does it looks like the approach you've envisioned.

**Comment by timgraham** [comment]
I didn't have any approach envisioned myself; maybe that was Claude.

The patch doesn't seem to allow already logged in users to view the login page (e.g. if they want to login to a different account) and the test failures about redirect loops don't seem good. So unless you can investigate and explain why these issues are okay, I'd say the patch is a no go at this point.

**Comment by carljm** [comment]
I haven't fully taken in everything on the ticket regarding the admin and GET vs POST and `RemoteUserMiddleware`, so I don't have a proposed approach either. But the current patch here is seriously backwards-incompatible; I think it's a non-starter.

**Comment by adelton** [comment]
Let me dig deeper into the test failures to see what behaviours exactly are changing. I'll report back.

**Comment by carljm** [comment]
To clarify, my problem with this PR is the backwards incompatible change in behavior itself. As Tim says, currently an authenticated user can view a login page and login as a different user. I don't think that is a capability we can or should just remove. 

The current behavior is simpler and more predictable and flexible than the proposed behavior.  If you want the proposed behavior in your project right now, it is very easy to implement by wrapping the login view with your own view that checks authenticated status and redirects if authenticated. If we accepted this PR there would be no reasonable way to get back the current behavior. 

So I don't think that my objection to this PR will be changed by any investigation of the failing tests.

**Comment by adelton** [comment]
For the record, `mod_intercept_form_submit` in version 1.0.1 added configuration directive `InterceptGETOnSuccess` to force the method in the request to be shown (and reported to Django) as `GET`. So this change is no longer needed.

**Pull request closed without merging**
