### PR TITLE
Used bytes.hex() and bytes.fromhex() in postgis.pgraster to simplify.

### PR DESCRIPTION
**Pull request by sir-sigurd**
That was missed in 93cdd07e8fb08d7bb3f1e4a7117aa9d0d76581cd.

### CODE REVIEW

**Comment by charettes** [comment]
buildbot, test on oracle.

**Comment by charettes** [comment]
Ah missed it was PostgreSQL only.

**Comment by felixxm** [comment]
@sir-sigurd I think I found one more:
```diff
diff --git a/django/contrib/gis/gdal/geometries.py b/django/contrib/gis/gdal/geometries.py
index 42fbeecd08..32acf27025 100644
--- a/django/contrib/gis/gdal/geometries.py
+++ b/django/contrib/gis/gdal/geometries.py
@@ -39,7 +39,6 @@
   True True
 """
 import sys
-from binascii import b2a_hex
 from ctypes import byref, c_char_p, c_double, c_ubyte, c_void_p, string_at
 
 from django.contrib.gis.gdal.base import GDALBase
@@ -328,7 +327,7 @@ class OGRGeometry(GDALBase):
     @property
     def hex(self):
         "Return the hexadecimal representation of the WKB (a string)."
-        return b2a_hex(self.wkb).upper()
+        return self.wkb.hex().upper()
 
     @property
     def json(self):
```

**Comment by sir-sigurd** [comment]
@felixxm I'm not sure about that because it changes the return type. Currently `OGRGeometry.hex` returns `bytes` despite docstring saying that it returns a string.

**Comment by felixxm** [comment]
@sir-sigurd You're right. I missed that.

**Pull request merged**
