### PR TITLE
Remove unused code and duplicate import

### PR DESCRIPTION
**Pull request by sanchjat**
Remove unused code and duplicate import.

ref : https://lgtm.com

### CODE REVIEW

**Comment by felixxm** [comment]
I don't see any value in removing `from functools import partial` or ` from os import path`. Moreover some most of removed variables should stay, e.g.
``` python
f = get_object_or_404(FlatPage, url=url, sites=site_id)
```
Please don't send such PR without reconsidering a code.

**Comment by sanchjat** [comment]
@felixxm if every one import like that then in case we have lot of import statement.. also by mistake anyone can override in class.. but if we use like`functools.partial` no risk of override

**Comment by sanchjat** [comment]
@felixxm also `var globalThreshold = 50;` we are not using it anywhere... I will revert `f = get_object_or_404(FlatPage, url=url, sites=site_id)` this changes..

**Comment by charettes** [comment]
> also var globalThreshold = 50; we are not using it anywhere...

It seems to be a configuration option for grunt-contrib-qunit coverage plugin.

**Pull request closed without merging**
