### PR TITLE
Fixed #28936 - Unescape regex escapes outside groups in simplify_regex

### PR DESCRIPTION
**Pull request by okcleary**

### CODE REVIEW

**Comment by charettes** [comment]
I didn't go through the full ticket description but [could `re.escape` be used for this purpose](https://docs.python.org/3/library/re.html?highlight=re#re.escape)?

**Comment by okcleary** [comment]
I don't believe so - as far as I am aware there is no standard library function to reverse regex escaping.

**Review by codingjoe — APPROVED** [review]
To confirm, `re.escape` cannot be utilized here. Besides the code looks fine. I also verified that the method isn't documented. No deprecation needed, however a release not could be added, but I leave this to the whoever is merging this.

**Comment by carltongibson** [comment]
Closing as per ticket.

**Pull request closed without merging**
