### PR TITLE
Fixed #28050: Added Template path to TemplateSyntaxError exception message.

### PR DESCRIPTION
**Pull request by kapilgarg1996**
[Ticket](https://code.djangoproject.com/ticket/28050)

### CODE REVIEW

**Comment by timgraham** [comment]
I guess that's helpful for templates rendered outside of `runserver`, but for the debug view, it's adding redundant information. I wonder if we could avoid that.

screenshot from 2017-04-07 13 23 57

**Comment by kapilgarg1996** [comment]
@timgraham  Can we remove the template name from debug view because i think exception message should always contain template name. Also the exception message will now hold template name as well as the line number in the template so we can safely remove that data from debug template.

What do you suggest ?

**Comment by timgraham** [comment]
There might be a possibility for the debug view to modify `TemplateDoesNotExist`'s message so the redundant template names aren't added. In any case, a test is required.

**Comment by timgraham** [comment]
Closing in hopes of an alternate solution.

**Pull request closed without merging**
