### PR TITLE
Refs #24215 -- Prevented pending lookup pollution by abstract models.

### PR DESCRIPTION
**Pull request by charettes**

### CODE REVIEW

**Comment by charettes** [comment]
The tests could be removed if [#24215](https://code.djangoproject.com/ticket/24215) adds system checks to make sure there's no pending lookup on application initialization.

**Comment by aaugustin** [comment]
Looks reasonable to me.

**Comment by carljm** [comment]
Looks good to me as well. With this change we do want to be confident that concrete models which inherit an abstract base with lazy relations will resolve that relation - I assume there are already tests covering that case?

**Comment by charettes** [comment]
> With this change we do want to be confident that concrete models which inherit an abstract base with lazy relations will resolve that relation - I assume there are already tests covering that case?

Yes, in the [`model_inheritance`](https://github.com/django/django/blob/e519ee1d352e0e36fcb8edc9d33ec2845f663d3a/tests/model_inheritance/models.py#L57-L66) test app.

I'm going to close this in favor of #3984 which includes a similar commit (3e7b896617a9fe1f315b757a45f92a58d707575f).

**Comment by carljm** [comment]
I don't think you should close this, I think you should merge it. It's a much smaller/simpler change than #3984, and can be made independently. Smaller incremental changes in general are better. #3984 can easily adapt to having this bit merged in from master. I'm not sure that #3984 is close enough to being ready that we can assume it's going in.

**Comment by charettes** [comment]
Okay, I'll proceed with merging then!

**Pull request merged**
