### PR TITLE
Fixed trailing whitespaces in documentation

### PR DESCRIPTION
**Pull request by christophehenry**
Related to [#r1860770421](https://github.com/django/django/pull/18266/files#r1860770421).
Ping @nessita.

### CODE REVIEW

**Comment by sarahboyce** [comment]
Thank you Christophe
There is also this recent PR https://github.com/django/django/pull/18843/ which I am inclined to accept, I'm sure we'll merge something here :+1:

**Comment by nessita** [comment]
Thank you Sarah, #18843 wasn't on my radar, I will comment there and merge ASAP.

@christophehenry I'll ping when changes are in `main` (should be in the next couple of hours). Thank you for this PR though! I'll close it since the other one has these changes in (sorry I was not aware of that one...).

**Comment by nessita** [comment]
@christophehenry Trailing spaces removal is landed, please feel free to rebase onto main :100:

**Comment by christophehenry** [comment]
Done!

**Pull request closed without merging**
