### PR TITLE
Fixed #34285 -- Allow to do array access on filtered array aggregates

### PR DESCRIPTION
**Pull request by nils-van-zuijlen**
https://code.djangoproject.com/ticket/34285

### CODE REVIEW

**Comment by charettes** [comment]
@nils-van-zuijlen thanks for the patch! You'll want to submit your changes against the `main` branch, mergers will take care of backporting [if the patch is eligibile per the backport policy](https://docs.djangoproject.com/en/4.1/internals/release-process/#supported-versions-policy). I don't think it's the case with this patch.

**Comment by felixxm** [comment]
> I don't think it's the case with this patch.

We will backport to Django 4.2 as it's at pre-release alpha status.

**Comment by nils-van-zuijlen** [comment]
The point of opening this patch against 3.2 is that
1. The proposed fix does not work for nested int arrays and I don't know how to fix that
2. The tests I wrote are failing with a different exception than the one in the issue on main, so what should be done there?

**Comment by charettes** [comment]
> The proposed fix does not work for nested int arrays and I don't know how to fix that

I think it's ok to propose a patch that doesn't work with nested arrays at first, maybe we'll be able to guide you towards a solution from there.

> The tests I wrote are failing with a different exception than the one in the issue on main, so what should be done there?

It's hard to tell without seeing what the actual exception is on `main` but submitting a PR might also help in figuring out how to resolve the issue?

**Comment by nils-van-zuijlen** [comment]
Moved to https://github.com/django/django/pull/16512

**Pull request closed without merging**
