### PR TITLE
Fixed #25823 -- Made admindocs "View documentation" string consistent.

### PR DESCRIPTION
**Pull request by gunchleoc**
Changed a string for consistency.

cf. https://code.djangoproject.com/ticket/25823

### CODE REVIEW

**Comment by timgraham** [comment]
Would you like to try rebasing and squashing your commits?

**Comment by gunchleoc** [comment]
Yes I would - I spent more time fighting git today than doing the actual fix. There seem to be multiple ways of how to do that, what would you recommend?

**Comment by timgraham** [comment]
https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/working-with-git/ should help.

**Comment by claudep** [comment]
Note to the committer: do not backport as strings are frozen for 1.9.

**Comment by gunchleoc** [comment]
OK, tried and failed. I need to rebase my master branch, because that's where the problem starts. I tried `git rebase -i HEAD~6` so I could see a bit of the history, then set 2 commits that are now somewhere in the middle to `skip` and found out how to save and exit vim. git then wants me to run a commit with `--allow-empty` which I had to run twice, but then it wants a new commit message and it still is in rebase status afterwards. So, I'm stumped.

I guess the easiest way will be to just delete my fork and recreate this patch off a brand new fork + branch? I don't have any other new code that we would need in my repository yet.

**Comment by timgraham** [comment]
Here's what I did to fix it up:
```
$ git rebase master
(fix conflicts) 
$ git rebase --skip
$ git rebase -i HEAD~2
```
merged in 89b6856aa615bff5cccd1eeef61ab02d6e38498a, thanks!

**Comment by gunchleoc** [comment]
Thanks for rebasing :)

**Pull request closed without merging**
