### PR TITLE
Fixed #34247 -- Ordered CreateModel operations first when sorting migrations.

### PR DESCRIPTION
**Pull request by michaelschem**
I've been having trouble regenerating all my Django migrations from scratch.  We have hundreds of models and many complex relationships.  I kept getting the error `Cannot resolve operation dependencies` when generating and I noticed that proxy models that were foreign keys of other models seemed to be the culprit.  This is an update to the sort method that ensures that we put proxy model based CreateModel and regular model CreateModel operations at the top and fixes my problem.

### CODE REVIEW

**Comment by felixxm** [comment]
@michaelschem Thanks for this patch :+1: If you believe it's an issue in Django, then please create a [new ticket](https://code.djangoproject.com/newticket) in Trac and follow our [bug reporting guidelines](https://docs.djangoproject.com/en/dev/internals/contributing/bugs-and-features/#reporting-bugs). All bugfixes require [an accepted ticket](https://code.djangoproject.com/newticket).

**Comment by michaelschem** [comment]
@felixxm ok, created https://code.djangoproject.com/ticket/34247#ticket

**Review by emarhin — APPROVED** [review]
👍

**Comment by felixxm** [comment]
Closing per ticket.

**Pull request closed without merging**
