### PR TITLE
Fixed #29772 -- Made LazyObject proxy __lt__() and __gt__().

### PR DESCRIPTION
**Pull request by kingbuzzman**
Discussion: https://code.djangoproject.com/ticket/29772

### CODE REVIEW

**Comment by kingbuzzman** [comment]
Quite frankly, id like to commit this into 1.11+ and then merged with the higher versions -- if its at all possible.

**Comment by charettes** [comment]
@kingbuzzman that's not going to happen per our backport policy https://docs.djangoproject.com/en/2.1/internals/release-process/#supported-versions-policy

**Comment by kingbuzzman** [comment]
@charettes ok. No worries.

**Comment by charettes** [comment]
@kingbuzzman please rebase your PR against the master branch. This is not going to be backported to 2.0 or 2.1 either. It should be in 2.2.

**Comment by kingbuzzman** [comment]
@charettes would this be master?

**Comment by kingbuzzman** [comment]
o_O i don't know what happened, when i rebased it closed the PR, it sorry for the spam

**Comment by kingbuzzman** [comment]
@charettes how do i rebuild tests again? The closing/opening/rinse/repeat i did by mistake, caused 2 of the tests to abort and thus fail.

**Comment by charettes** [comment]
@kingbuzzman it looks like you're in a good spot now, the mariadb tests are know to fail from time to time so I wouldn't worry about it.

**Comment by kingbuzzman** [comment]
As a follow up. For all those of you that want to use this right now:

Add patch code somewhere at startup:

```python
# Patch code start
import django
from distutils.version import LooseVersion

if LooseVersion(django.__version__) < '2.2':
    import operator
    django.utils.functional.SimpleLazyObject.__lt__ = django.utils.functional.new_method_proxy(operator.lt)
    django.utils.functional.SimpleLazyObject.__gt__ = django.utils.functional.new_method_proxy(operator.gt)
else:
    raise Exception("We made it to 2.2! We can officially delete this patch code now :D")

# Patch code end
```

The "patch" will alert you when you can delete it.

Then just use it.

```python
# Example:

import datetime
from django.utils.functional import SimpleLazyObject
from django.core.validators import MinValueValidator
from django import forms

min_date_today_validator = MinValueValidator(SimpleLazyObject(datetime.date.today))


class ExampleForm(forms.Form):
    name = forms.CharField(required=True)
    dob = forms.DateField(required=True, validators=[min_date_today_validator])

# Will show you the error...
print(ExampleForm({'name': 'John', 'dob': datetime.date.today() - datetime.timedelta(days=1)}).errors)

# Other examples..
min_date_today_validator(datetime.date.today() + datetime.timedelta(days=1))
min_date_today_validator(datetime.date.today())
# Will raise a validation error
min_date_today_validator(datetime.date.today() - datetime.timedelta(days=1))
```

**Pull request merged**
