### PR TITLE
Refs #20910 -- Replaced snippet directive with code-block.

### PR DESCRIPTION
**Pull request by funkybob**
Any reasons for our custom "snippet::" directive in the docs appear to have long passed into invalid obscurity.
I've replaced all uses with code-block, with a view to later being able to use :emphasize-lines: to further improve the docs.

### CODE REVIEW

**Comment by funkybob** [comment]
I caught @ubernostrum on IRC who believed it was to add the :filename: directive, which the Sphinx docs say is what :caption: is for, so...

**Comment by carltongibson** [comment]
Thanks for the follow up! Good info. 👍🏽

**Comment by claudep** [comment]
Looks good, thanks!

**Comment by carltongibson** [comment]
Since this is a docs fix, we'd normally back port to 2.1. I'm not sure about that though because of the code change. (Surely no-one is using this code but...) 

One solution would be to split into two commits. One to just the docs using `code-block` and the other removing the `snippet` directive. Then we could back port just the one. ???

The other is to delay back porting (which we could do if/when we found conflicts occurring.)

I'll hold off for now.

**Comment by timgraham** [comment]
This needs to be tested with djangoproject.com. Some changes may also be needed there, e.g. 1be21651988374fc5b9b3cf8eb9afb76de229ff0 and the "copy to clipboard" feature. Probably it's fine to backport to 2.1 but since the older versions of the docs still use snippet, djangoproject.com will have to work with both.

**Pull request merged**
