### PR TITLE
Fixed #28115 -- Fixed IP address validation in geoip2 module.

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by timgraham** [comment]
Looks okay -- is it possible to test the first commit?

**Comment by claudep** [comment]
I don't see a test that would make much sense...

**Comment by timgraham** [comment]
How about something like this for `gis_tests/test_geoip2py`:
```python
@mock.patch('socket.gethostbyname', return_value='expected')
def test_check_query(self, gethostbyname):
    g = GeoIP2()
    self.assertEqual(g._check_query('127.0.0.1'), '127.0.0.1')
    self.assertEqual(g._check_query('invalid-ip-address'), 'expected')
```

**Comment by claudep** [comment]
Oh, you meant the second commit!

**Comment by claudep** [comment]
OK, test included, thanks.

**Pull request closed without merging**
