### PR TITLE
Updated humanize translation catalog es_AR

### PR DESCRIPTION
**Pull request by TheCraftsmen**
Is similar to the ticket https://code.djangoproject.com/ticket/21415 but for the Argentina translation case

### CODE REVIEW

**Comment by charettes** [comment]
Translations are managed on [Transifex](https://www.transifex.com/projects/p/django/) rather than through GitHub. See [Localizing Django](https://docs.djangoproject.com/en/dev/internals/contributing/localizing/#translations) for details.

**Comment by TheCraftsmen** [comment]
But you see the ticket in the link is the same case.

**Comment by charettes** [comment]
Oops you might be right! @claudep do you have any insight on whether or not this should be handled in Transifex?

**Comment by TheCraftsmen** [comment]
OK  i'm going to make a new pull request with the .mo

**Pull request closed without merging**
