### PR TITLE
Fixed #29759 -- Fixed crash on Oracle when fetching a returned insert id with cx_Oracle 7.

### PR DESCRIPTION
**Pull request by felixxm**
Ticket [29759](https://code.djangoproject.com/ticket/29759).

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by gloaec** [comment]
Hello there. 
I'm having this issue with `Django 1.11.16`. Is there a way you guys can backport this to the LTS `1.11.16` as well.

**Comment by timgraham** [comment]
You need to use cx_Oracle 6.x with Django 1.11.x.

**Comment by gloaec** [comment]
[User] : Already solved problem that could be backported on LTS in 30 sec
[Django] : Plz downgrade
|User] : Wow, thanks !

Just kidding, but well, you get the point right ?

**Comment by timgraham** [comment]
We have a [supported versions policy](https://docs.djangoproject.com/en/dev/internals/release-process/#supported-versions) that explains which fixes are backported. LTS only receives security and data loss fixes.

**Comment by gloaec** [comment]
Understood. No hard feelings.

**Pull request merged**
