### PR TITLE
Fix #24707 - url resolution: uncallable views passed via import raise a better error

### PR DESCRIPTION
**Pull request by hjwp**
Wasn't sure to make the PR against master or 1.8.x, but it applies cleanly and merges on both...

### CODE REVIEW

**Comment by hjwp** [comment]
hm.  that isort fail seems to be doing its check against master instead of 1.8.x.

**Comment by MarkusH** [comment]
Please open the PR against the master branch.

**Comment by hjwp** [comment]
can do!

**Comment by hjwp** [comment]
cf #4564

**Pull request closed without merging**
