### PR TITLE
Fixed #24463 -- Removed old functionality from HttpRequest

### PR DESCRIPTION
**Pull request by gitaarik**
https://code.djangoproject.com/ticket/24463

### CODE REVIEW

**Comment by collinanderson** [comment]
Buildbot, test this please.

**Comment by gitaarik** [comment]
It was complaining about the unused `os` import, I removed that and updated my PR.

**Comment by collinanderson** [comment]
Buildbot, add to whitelist.

**Comment by timgraham** [comment]
I didn't see an obvious explanation of why the comments were removed?

**Comment by gitaarik** [comment]
This comment:

    # Failing that, fall back to _get_scheme(), which is a hook for
    # subclasses to implement.

I moved to the `_get_scheme()` method itself. Then the other comments became obvious/ambiguous in my opinion.

I think this comment:

    # First, check the SECURE_PROXY_SSL_HEADER setting.

is quite obvious when you're doing:

    if settings.SECURE_PROXY_SSL_HEADER:

Then this comment:

    # Failing that, fall back to _get_scheme(), which is a hook for
    # subclasses to implement.

Is ambiguous because it's already explained in the `_get_scheme()` method itself, which I think is better, to put the explanation of a method in the docstring of the method itself.

**Comment by timgraham** [comment]
Okay, thanks. merged in ccff08c194b0b7f8a86bf9c5dd6d5be473760a1b.

**Pull request closed without merging**
