### PR TITLE
WIP: Fixed #30213 -- Add a Watchdog autoreloader

### PR DESCRIPTION
**Pull request by orf**
Ticket: https://code.djangoproject.com/ticket/30213

Still WIP, there are some tricky issues around threads here that I need to resolve.

### CODE REVIEW

**Comment by claudep** [comment]
Great, I already started patching my virtualenvs to start testing it!

**Comment by felixxm** [comment]
Closing due to inactivity.

**Comment by Alexerson** [comment]
Hey there, I stumbled on this pull request while trying to figure out a way to improve the speed of my local dev setting. I'm (locally) running Django in Docker and for some reason the current reloader is slowing down my system quite a bit. I looked into Watchman but the lack of properly packaged support for Ubuntu makes it hard to implement. 
@orf : Do you mind if I try to work on this and if so, can you give more details about what's left (a.k.a. the "tricky issues around threads").

**Comment by orf** [comment]
> @orf : Do you mind if I try to work on this and if so, can you give more details about what's left (a.k.a. the "tricky issues around threads").

Hey @Alexerson, please feel free to take it over! I can't quite remember the specifics, but it was something to do with how `watchdog` calls callbacks in a different thread.

Please assign yourself on the ticket and give it a go. Also note that we improved the performance a bit in #12750, I'd love to know if that improves the speed of your local dev setting.

**Comment by Alexerson** [comment]
Actually, this sound exactly like my issue! I'll check if this fixes my problem. If so, I must admit I'll probably won't try to implement watchdog ^^ Otherwise, I'll give it a go.

**Comment by NyanKiyoshi** [comment]
Yes, when running docker for development, you do need to switch to watchman otherwise it will cost a lot of resources and even often fail to detect changes without having to restart the container.

**Pull request closed without merging**
