### PR TITLE
Fixed #31443 -- Fixed login redirection in auth mixins when LOGIN_URL is off-site URL.

### PR DESCRIPTION
**Pull request by minusf**

### CODE REVIEW

**Comment by minusf** [comment]
sorry, not what i wanted.  only 836a84f, that adds the test.  sorry for the mess

**Comment by 28Rahul28** [comment]
Is this merged? I saw a ticket in easy picking to add test but here i see that the tests has been added!!

**Comment by felixxm** [comment]
> Is this merged? I saw a ticket in easy picking to add test but here i see that the tests has been added!!

No, it's not merged. Test was added but the "Needs test" flag wasn't unchecked on the ticket that's why it didn't appear in the review queue again.

**Comment by felixxm** [comment]
@minusf Thanks :+1: I moved tests to `AccessMixinTests`.

**Comment by felixxm** [comment]
Merged in cc7c16af98e4c9a7146c248c8567aac7a50e0fbb.

**Pull request closed without merging**
