### PR TITLE
Closed #11028 -- Regression test for admin search on m2m fields

### PR DESCRIPTION
**Pull request by albertoconnor**
Searching with the admin across Many2Many Field raised a
Programming Error before cf70c96ce08bec8834ada695451cc915f7558dbd.
The added tests for regression.

### CODE REVIEW

**Comment by timgraham** [comment]
I am not sure this is really testing the bug in the ticket -- neither `Genre` nor `Band` are inherited models. Are inherited models not needed to reproduce the issue? The bisected commit doesn't really seem like it would fix the issue.

**Comment by albertoconnor** [comment]
I was able to reproduce the issue without inherited models. It raised a ProgrammingError, though it may have been a different programming error. I also verify that this test fails before the commit bisect found.

I could change it to add inheritance, but I didn't find it was needed.

**Comment by timgraham** [comment]
I couldn't reproduce a `ProgrammingError` with the patch applied to 414c762c3abfebb2670a3b26aba7028d62303cfe (the commit before the commit you said fixed the issue):
```diff
diff --git a/tests/regressiontests/admin_changelist/tests.py b/tests/regressiontests/admin_changelist/tests.py
index 709fa76..694762e 100644
--- a/tests/regressiontests/admin_changelist/tests.py
+++ b/tests/regressiontests/admin_changelist/tests.py
@@ -164,6 +164,26 @@ class ChangeListTests(TestCase):
         # There's only one Group instance
         self.assertEqual(cl.result_count, 1)
 
+    def test_search_over_m2m_field(self):
+        class BandAdmin(admin.ModelAdmin):
+            list_filter = ['genres']
+            search_fields = ['genres__name']
+
+        genre = Genre.objects.create(name='Rock')
+        band = Band.objects.create(
+            name="The Weatherthans",
+            nr_of_members=5,
+        )
+        band.genres.add(genre)
+
+        m = BandAdmin(Band, admin.site)
+        request = self.factory.get('/band/', data={SEARCH_VAR: 'Rock'})
+
+        ChangeList(request, Band, m.list_display, m.list_display_links,
+                   m.list_filter, m.date_hierarchy, m.search_fields,
+                   m.list_select_related, m.list_per_page,
+                   m.list_editable, m)
+
     def test_distinct_for_through_m2m_in_list_filter(self):
         """
         Regression test for #13902: When using a ManyToMany in list_filter,
```

**Comment by albertoconnor** [comment]
I found the same thing. I will start back at the beginning and focus on reproducing the issue in the inherited form in the past. It isn't clear the type of inheritance but I will try all of the options.

**Pull request closed without merging**
