### PR TITLE
Refs #26001 -- Handled relationship exact lookups in ModelAdmin.search_fields.

### PR DESCRIPTION
**Pull request by sarahboyce**
Based off feedback from f223729f8f8380901473b244c0fc7c7dc397e3f1.

I can also revert if a fix isn't so simple :+1:

### CODE REVIEW

**Review by charettes — APPROVED** [review]
Thanks @sarahboyce! I don't think the change warrants a revert as it was still an improvement over the previous situation of crashing.

I've got nothing to add to the changes you made they are excellent!

I think a different approach could have been taken here where we would have constructed the `django.db.models.lookup.Exact` instances against the specified fields and simply resolved term for each terms but that would have required more invasive work.

For example, if your search terms are `["123456", "foo@example.com"]`, your search fields are `["email", "age__exact"]` then it's somewhat wasteful to do `cast(age as text) = 'foo@example.com'` as we know it's not a possible value for this column (assuming it's an `IntegerField`) and it will not be indexed so it might require a full table scan.

I think that we could possibly have used `queryset.query.build_filter` (or one of it's siblings such as `build_lookup`) to build `Lookup` instances that can be passed directly to `filter()` and catch `ValueError`/`TypeError` raised during lookup construction to _elide_ the ones that have invalid values.

**Comment by sarahboyce** [comment]
Thank you for the review and suggested approaches Simon - they both sound interesting :+1: 
Happy to refactor and change the approach in future

**Comment by pauloxnet** [comment]
Interesting analysis as ever, I'm asking a question only to see if I understood it correctly:

> For example, if your search terms are `["123456", "foo@example.com"]`, your search fields are `["email", "age__exact"]` then it's somewhat wasteful to do `cast(age as text) = 'foo@example.com'` as we know it's not a possible value for this column (assuming it's an `IntegerField`) ...

Is this true also for date/datetime field that accept also string values?

**Comment by charettes** [comment]
@pauloxnet yes, for the `__exact` case there a many possible mismatches possible between non-textual fields and search terms.

The approach taken here is to avoid the `__exact` crash by casting non-textual columns to text and comparing them against search terms but we know for sure that an integer/datetime/uuid field cannot exactly match `"some-search-term"`.

FWIW a similar _problem_ exists for `__(i)?contains` lookups but it's harder to resolve entirely because Django has historically taken a stance to do an implicit cast to text to allow search for part of data. For example, in the case of UUID field, it might be interesting to allow to search for components of the UUID or for parts of an integer field.

**Comment by pauloxnet** [comment]
@charettes thanks again for the explanation :+1:

**Pull request merged**
