### PR TITLE
Fixed #34320 -- Fixed introspection of constraints on truncated column names on Oracle.

### PR DESCRIPTION
**Pull request by nabil-rady**
Not sure what tests should I write, but hopefully people could help me.

### CODE REVIEW

**Comment by felixxm** [comment]
@nabil-rady Thanks :+1: 

> Not sure what tests should I write, but hopefully people could help me.

You can add a schema test and check if the constraint is preserved for renamed field with a long name, e.g.
```diff
diff --git a/tests/schema/tests.py b/tests/schema/tests.py
index bc603cb772..c25704fcf6 100644
--- a/tests/schema/tests.py
+++ b/tests/schema/tests.py
@@ -13,6 +13,7 @@ from django.db import (
     OperationalError,
     connection,
 )
+from django.db.backends.utils import truncate_name
 from django.db.models import (
     CASCADE,
     PROTECT,
@@ -2072,6 +2073,36 @@ class SchemaTests(TransactionTestCase):
         with self.assertRaises(IntegrityError):
             NoteRename.objects.create(detail_info=None)
 
+    @isolate_apps("schema")
+    def test_rename_field_with_check_to_truncated_name(self):
+        class AuthorWithLongColumn(Model):
+            title_with_very_looooooong_name = PositiveIntegerField(null=True)
+
+            class Meta:
+                app_label = "schema"
+
+        self.isolated_local_models = [AuthorWithLongColumn]
+        with connection.schema_editor() as editor:
+            editor.create_model(AuthorWithLongColumn)
+        old_field = AuthorWithLongColumn._meta.get_field(
+            "title_with_very_looooooong_name"
+        )
+        new_field = PositiveIntegerField(null=True)
+        new_field.set_attributes_from_name("renamed_title_with_very_long_name")
+        with connection.schema_editor() as editor:
+            editor.alter_field(AuthorWithLongColumn, old_field, new_field, strict=True)
+
+        new_field_name = truncate_name(
+            new_field.column, connection.ops.max_name_length()
+        )
+        constraints = self.get_constraints(AuthorWithLongColumn._meta.db_table)
+        check_constraints = [
+            name
+            for name, details in constraints.items()
+            if details["columns"] == [new_field_name] and details["check"]
+        ]
+        self.assertEqual(len(check_constraints), 1)
+
     def _test_m2m_create(self, M2MFieldClass):
         """
         Tests M2M fields on models during creation
```

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by nabil-rady** [comment]
I tried the test without the fix and it failed  due to `strict` being `True`. So the test is working fine.

**Comment by felixxm** [comment]
Merged in 6bdc3c58b65eb32fd63cd41849f00a17a36b4473.

**Comment by timgraham** [comment]
Missing a test skip for backends that don't support check constraints? The final assertion fails on Snowflake (0 != 1).

**Comment by felixxm** [comment]
> Missing a test skip for backends that don't support check constraints? The final assertion fails on Snowflake (0 != 1).

Good catch :dart: we should wrap it with:
```python
@skipUnlessDBFeature("supports_column_check_constraints", "can_introspect_check_constraints")
```
Would you like to prepare a patch?

**Pull request closed without merging**
