### PR TITLE
Refs #23919 -- [WIP] Replaced All super(ClassName, self) with super() in django

### PR DESCRIPTION
**Pull request by auvipy**

### CODE REVIEW

**Comment by charettes** [comment]
I suggest you replace all occurrences of the code base in a single commit.

**Comment by auvipy** [comment]
OK. then allow me some more time. don't you think smaller moduler changes are better

**Comment by charettes** [comment]
I don't see any benefit in a large number of commits for such a change.

**Comment by auvipy** [comment]
OK

**Comment by charettes** [comment]
By the way, you could probably write sed script to automate the process.

**Comment by auvipy** [comment]
never used before, anything like http://askubuntu.com/questions/747450/how-do-i-call-a-sed-command-in-a-python-script this?

**Comment by aaugustin** [comment]
Over the 1371 instances of super() in the code base there's a risk we have a smart hack somewhere where super calls the grandparent instead of the parent.

I think the correct way to do this would be with a 2to3 transform or a script that checks the AST to ensure that `ClassName` is indeed the name of the class in which the `super()` call happens.

These changes have to be scripted; it's absolutely impossible to review them otherwise. For this reason I don't think it's productive to continue doing them one by one.

**Comment by adamchainz** [comment]
+1 to being careful

> where super calls the grandparent instead of the parent.

We had a grandparent super call at work that came up when upgrading to Python 3. We actually used a regex [one liner](https://tech.yplanapp.com/2016/08/24/upgrading-to-python-3-with-zero-downtime/) like sed to change them all, but luckily a test caught this one. Using a 2to3 transform/AST tool for Django though is sensible, we have to be as cautious as possible 🌵

**Comment by auvipy** [comment]
I am checking the tool you mentioned in the article.

**Comment by aaugustin** [comment]
Adam and I are saying that while `sed` allows automating what you were doing manually, it's still insufficient because removing parameters from `super()` can change the semantics of the call in (uncommon) cases.

You can learn about `sed` -- it's a valuable tool -- but don't bother submitting a PR where parameters to `super()` are just just removed with sed: the consensus of committers is that it's insufficient.

**Comment by timgraham** [comment]
Continued in https://github.com/django/django/pull/7905.

**Pull request closed without merging**
