### PR TITLE
Fixed #28278 -- Fixed invalid HTML for a required AdminFileWidget.

### PR DESCRIPTION
**Pull request by kakulukia**
Error inside clearable_file_input.html

### CODE REVIEW

**Comment by timgraham** [comment]
Could you add a test for that?

**Comment by kakulukia** [comment]
ok, will try to do that :)

**Comment by kakulukia** [comment]
@timgraham where would i put this test? Could you point me to where it makes sense to add that test. Preferably where some other template files are tested already. Just startet the test suit and saw that there are 11440 test. :) There probably is one doing what i want to for another template.

A test trying to render all input elements on one admin page would make the most sense i think.

**Comment by timgraham** [comment]
Look at af1f986360dc6bb6e75e960dbc191707541128ac for a similar fix.

**Comment by kakulukia** [comment]
Okay, i tried to implement a test for that, but this is more broken than i thought it was
there are THREE templates for the clearable_file_input(.html)
2 of em are identical
django/forms/templates/django/forms/widgets/clearable_file_input.html
django/forms/jinja2/django/forms/widgets/clearable_file_input.html
1 of em got enhanced
django/contrib/admin/templates/admin/widgets/clearable_file_input.html

Here is the commit that changed it:
https://github.com/kakulukia/django/commit/b52c73008a9d67e9ddbb841872dc15cdd3d6ee01
Its a pretty big change and it looks like you where involved in commiting it?
Somebody should have a look at this who knows more about the Django internals than i do. I feel out of place here.

That totally is against DRY but im not able to judge if it might be neccessary here.

Anyways, i found the place where that very test should go:
tests/forms_tests/widget_tests/test_clearablefileinput.py
But adding a new test for the admin widget brought up a 
django.template.exceptions.TemplateDoesNotExist: admin/widgets/clearable_file_input.html

I dont know why this is happening, because the template is there .. the test suit is running fine but something seems to not be setup the right way?

Any advice?

**Comment by timgraham** [comment]
Oh, I didn't notice this was the admin widget template. In that case, look at `tests/admin_widgets` for a test.

**Comment by kakulukia** [comment]
But do you know why DRY is violated here? 2 times?

**Comment by timgraham** [comment]
The templates in django/forms/templates are for the Django template language.
The templates in django/forms/jinja2 are for the Jinja template language.
The admin's template is customized with a `<span>` for styling purposes.

**Comment by kakulukia** [comment]
Is the an HTML linter ready to be indes for tests like this in the rest suit?

**Comment by kakulukia** [comment]
*used

**Comment by timgraham** [comment]
I'm not sure what you mean. There are some tests in `admin_widgets` that are checking HTML. Can you follow that pattern?

**Comment by kakulukia** [comment]
the test suit already has an HTML validator/linter included that kicked in as i was trying to render the broken widget template, but there is no test validating the resulting HTML :(

Test is included now!

**Pull request merged**
