### PR TITLE
Update global_settings.py

### PR DESCRIPTION
**Pull request by vttn**
Add Shona to languages

### CODE REVIEW

**Comment by felixxm** [comment]
Adding a new language requires Transifex setup first. Do you intend to start a Shona translation for Django and take the role of Shona language coordinator? If you do, we can set it up on Transifex. Please give us your Transifex username. (\cc @claudep)

**Comment by vttn** [comment]
@felixxm I can be a Shona language coordinator. My username is vttn. How soon can I have the Shona language option available on Django.

**Comment by felixxm** [comment]
@claudep Can you help? :point_up:

**Comment by claudep** [comment]
@vttn Shona team has been created on Transifex with you as the team coordinator. It's still time to target Shona integration in Django 3.1 (to be finally released in August). You should at least fully translate the "core" ressource on Transifex, then feel free to ping me for the next integration steps.

**Comment by claudep** [comment]
@vttn Did you encounter any difficulty with using Transifex? Tell me if I can help in any way.

**Comment by vttn** [comment]
@claudep there must be a easier way to bring in new languages into Django. The challenge I see is understanding context. If Django was to enable Shona, I know at least one other person who is willing to spend their time doing the translations.

**Comment by claudep** [comment]
@vttn, if you just want to enable Shona in your project without contributing Shona translations into Django, you can always complement the LANGUAGES setting.

However, it would be so nice to have Shona translations of Django itself. Then the process is to start by translating in the Transifex tool. I agree it's sometimes difficult to translate "isolated" strings, but there is a "Context" tab in Transifex that points you to the file(s) where the string is used. You can then browse Django files to find more context. And you have me when you are stuck :-) It is good if you can bring someone else into the process of translating, it's always easier to motivate one another.

"Tu peux le faire", like we say here :sunglasses:

**Pull request closed without merging**
