### PR TITLE
Move jQuery files to vendor subdirectory

### PR DESCRIPTION
**Pull request by treyhunner**
This was discussed in #4577.  This will hopefully make it more clear which files are independently maintained outside of Django.

### CODE REVIEW

**Comment by timgraham** [comment]
You may squash the commits and could you please also add the 1.9 release note in "backwards incompatible changes"?

**Comment by oinopion** [comment]
Did CI fail because of rebase?

**Comment by MarkusH** [comment]
Just the occasional Jenkins / Github hiccups, @oinopion

**Comment by aaugustin** [comment]
Merged (with a negligible edit of the commit message) in 788071e.

**Pull request closed without merging**
