### PR TITLE
Fixed 27709 -- Fixed get_for_models() when cache is empty

### PR DESCRIPTION
**Pull request by inglesp**

### CODE REVIEW

**Comment by charettes** [comment]
Hey Peter, it looks like I didn't understand the ticket at first, sorry for that. What do you think of this approach instead: https://github.com/django/django/compare/master...charettes:ticket-27709-proxy-model-contenttypes-cache.

A lot of tests in our suite clear the contenttypes cache and even delete the existing records so we should avoid making `get_for_models()` a simple wrapper around `get_for_model()` IMHO.

**Comment by inglesp** [comment]
Hi @charettes, thanks for taking a look.

I'm a bit concerned that you've installed some kind of spyware on my machine because your proposed fix is character-for-character identical to the alternate fix I mentioned in the ticket :).

I don't understand your point about why we should avoid making `get_for_models()` a simple wrapper around `get_for_model()`.  What are the risks to doing so?  Is it just that the test suite might run slightly slower?

**Comment by charettes** [comment]
> I'm a bit concerned that you've installed some kind of spyware on my machine because your proposed fix is character-for-character identical to the alternate fix I mentioned in the ticket :).

I promise I didn't do such thing :) I'm glad we agreed upon the same implementation.

> I don't understand your point about why we should avoid making get_for_models() a simple wrapper around get_for_model(). What are the risks to doing so? Is it just that the test suite might run slightly slower?

It might make the Django's test suite slower but the biggest issue IMO is that the number of queries executed by the method might change in subtle ways which could break user existing tests (just like it broke the test you changed here) and cause performance regressions for users that were expecting the method to perform such optimizations which is why this method was introduced for in the first place f04af7080b12744c8f06fb8228ef683d556690d0.

**Comment by inglesp** [comment]
It seems not to have a significant affect on the speed of the Django test suite, but you make a good point about needlessly breaking existing tests.  I'll close this and you can turn https://github.com/django/django/compare/master...charettes:ticket-27709-proxy-model-contenttypes-cache into a PR.

**Pull request closed without merging**
