### PR TITLE
Fixed #31660 -- Fixed queryset crash when grouping by m2o relation.

### PR DESCRIPTION
**Pull request by felixxm**
ticket-31660

Regression in 3a941230c85b2702a5e1cd97e17251ce21057efa.

Thanks Tomasz Szymański for the report.

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
@charettes True, I will try to track it down.

**Comment by felixxm** [comment]
@charettes I tried:
```diff
diff --git a/django/db/models/sql/query.py b/django/db/models/sql/query.py
index ce18098fd2..b12a9f6ab1 100644
--- a/django/db/models/sql/query.py
+++ b/django/db/models/sql/query.py
@@ -1308,7 +1308,8 @@ class Query(BaseExpression):
             if num_lookups > 1:
                 raise FieldError('Related Field got invalid lookup: {}'.format(lookups[0]))
             if len(targets) == 1:
-                col = self._get_col(targets[0], join_info.final_field, alias)
+                joined_field = getattr(join_info.final_field, 'field', join_info.final_field)
+                col = self._get_col(targets[0], joined_field, alias)
             else:
                 col = MultiColSource(alias, targets, join_info.targets, join_info.final_field)
         else:

```
but it causes few failures :thinking: , e.g.

- `test_in_subquery` (`queries.tests.ToFieldTests`),
- `test_filter_reverse_non_integer_pk` (`queries.tests.Queries4Tests`),
- `test_recursive_fk_reverse` (`queries.tests.ToFieldTests`).

**Comment by charettes** [comment]
@felixxm I see, since this is addressing a regression I say we ship this solution for now and create a ticket to investigate _why_ this is happening in the first place. The fact only a few tests fail and that some of them are related to `ForeignObject.to_field`, which has proven to be poorly tested over the years, makes me believe that it's close to to the desired solution. Happy to get assigned this investigation ticket based on your initial work, thank you for doing that by the way!

**Comment by felixxm** [comment]
@charettes Thanks :+1: I created ticket-31677.

**Pull request merged**
