### PR TITLE
Removed unused and unnecessary words from docs/spelling_wordlist.

### PR DESCRIPTION
**Pull request by smithdc1**
Removed words contained within the Enchant dictionary

Maybe a bit speculative. There are many words which have now made it into the `en_US` dictionary and are no longer required in Django's custom wordlist. This passes locally for me atleast, but I'm slightly unsure if folk will get different dictionaries from the underlying sources?

### CODE REVIEW

**Comment by felixxm** [comment]
@smithdc1 Thanks :+1: however we need to be consistent with `djangoproject.com` which runs on Ubuntu 18.04 (see failures in #14714). We should change GitHub actions to use Ubuntu 18.04 in the `docs` check (see #14715).

**Comment by pope1ni** [comment]
Thanks @smithdc1. I agree with @felixxm on this - we should be developing for production and targeting the same versions as closely as possible.

Please do revisit this when djangoproject.com uses 20.04. I really appreciate these efforts that go into unglamorous, background maintenance. 🙂

**Comment by felixxm** [comment]
@smithdc1 You can rebase and check again with #14715. Maybe some of these words can be removed, but not `Django`.

**Comment by felixxm** [comment]
Inly few words should be reverted according to logs:
- Django
- iOS
- covariance
- viewable
- interoperability
- unmaintained

**Comment by pope1ni** [comment]
Sorry for closing prematurely, indeed there is some clean up that can be done now.

It looks like you've removed some names that are referenced in the old release notes which will need to remain.

**Comment by smithdc1** [comment]
> I really appreciate these efforts..

Thank you! For me it's all about learning, writing a few short scripts today to get the relavent info out of the logs was an enjoyable challenge for me. 

> It looks like you've removed some names

Yes, I guess locally it passes for me as it picks the names up from the contributors, but I am unsure why that doesn't work here. Anyway there's only a handful so I've added them back.

**Review by pope1ni — APPROVED** [review]
Thanks @smithdc1.

**Pull request merged**
