### PR TITLE
Fixed #32610 -- Fixed get_git_changeset() on Linux.

### PR DESCRIPTION
**Pull request by felixxm**
ticket-32610

### CODE REVIEW

**Review by carltongibson — APPROVED** [review]
OK, ~~assuming CI is happy~~, this looks right. Hmm. CI is NOT happy. 

Refs: 

* https://docs.python.org/3.9/library/subprocess.html#subprocess.Popen
* https://docs.python.org/3.9/library/subprocess.html#converting-an-argument-sequence-to-a-string-on-windows

```
  File "C:\Jenkins\workspace\pull-requests-windows\database\sqlite3\label\windows\python\Python39\django\utils\version.py", line 89, in get_git_changeset
    raise subprocess.CalledProcessError(git_log.returncode, git_log.args)
subprocess.CalledProcessError: Command 'git log --pretty=format:%ct --quiet -1 HEAD' returned non-zero exit status 1.

```

**Comment by felixxm** [comment]
`shell=True` is required on Windows. Unfortunately passing a sequence to `subprocess.run()` behaves differently on Linux, i.e. the first item specifies the command string, and any additional items are treated as additional arguments to the shell itself.

**Comment by felixxm** [comment]
buildbot, test this please.

**Comment by felixxm** [comment]
buildbot, test this please.

**Review by carltongibson — APPROVED** [review]
OK, so testing locally on Windows, this works fine. 

I think given the CI issue, just reverting the single line is OK. 

Thanks @felixxm !

**Pull request merged**
