### PR TITLE
Omit 'just' from docs when explaining context processors

### PR DESCRIPTION
**Pull request by ana-balica**
This is a trivial documentation improvement.

### CODE REVIEW

**Comment by timgraham** [comment]
If this is an improvement worth making, I suppose it could be useful to audit all usage of "just" in the docs.

**Comment by MarkusH** [comment]
Only spotted that at that moment. Not sure it's worth spending time investigating all occurrences, though.

**Comment by timgraham** [comment]
My reservation is annoying documentation translators with trivial changes like this.

**Comment by MarkusH** [comment]
Aren't those kind of changes detected by gettext?

**Comment by timgraham** [comment]
I'm not sure how it works but I figured the modified sentence will appear as a new string requiring translation. @claudep?

**Comment by claudep** [comment]
Transifex is clever enough to provide the diff with the old string as a suggestion to translators, so it's not so much an issue. Just :-) don't backport it to old stable versions (not available for translations)!

**Pull request merged**
