### PR TITLE
Fixed #24195 -- Deconstructed the limit_choices_to option of related fields.

### PR DESCRIPTION
**Pull request by bogdal**
This PR fixes https://code.djangoproject.com/ticket/24195

### CODE REVIEW

**Comment by charettes** [comment]
The changes are looking good. Could you possibly add a test for this change for `ForeignKey`, `ManyToManyField` and `OneToOneField` in the [`field_deconstruction` test app](https://github.com/django/django/blob/802dd1ffc5cfa3d547efeb285dac70884b99e16d/tests/field_deconstruction/tests.py)?

**Comment by timgraham** [comment]
builldbot, add to whitelist.

**Comment by timgraham** [comment]
Could you move the refactoring and additional tests into a separate commit so that the fix for the ticket doesn't include unrelated changes? Thanks.

**Comment by timgraham** [comment]
Does https://github.com/django/django/pull/7517 (making `Q` deconstructible) help with that?

**Comment by MarkusH** [comment]
> Does https://github.com/django/django/pull/7517 (making `Q` deconstructible) help with that?

Only had a quick look, but seems like that's what is needed.

**Comment by bogdal** [comment]
@timgraham @MarkusH thanks for the advice. I assume that I should wait for the #7517 PR.

**Comment by bogdal** [comment]
I have just rebased to master. As the #7517 PR is merged, `limit_choices_to` is fully supported now.

**Pull request merged**
