### PR TITLE
Fixed #27513 -- Made Signal.send/send_robust a tiny bit faster

### PR DESCRIPTION
**Pull request by adamchainz**
[Ticket](https://code.djangoproject.com/ticket/27513)

### CODE REVIEW

**Comment by adamchainz** [comment]
Hang about, just realized `send` with receivers can be optimized with a list comp.

**Comment by adamchainz** [comment]
Test failures are all in `
settings_tests.tests.TestComplexSettingOverride.test_complex_override_warning` which seems unrelated

**Comment by charettes** [comment]
I'm not sure yet about what's causing the failure but I can reproduce locally on Python 3.5 with your patch and cannot without it.

**Comment by adamchainz** [comment]
Oh yes, maybe something about `override_settings`'s signal is broken 😢

**Comment by charettes** [comment]
@adamchainz it's alright you just have to change the `stacklevel` [here](https://github.com/django/django/commit/eabc3b6c8dd67e9ff49da9f2f41cc653898cd0a1#diff-98bf7c9f19d570f28fc0e001c36affffR103) which was relying on the internal the signaling infrastructure.

**Comment by charettes** [comment]
Actually you'll have to make it `6` only on Python3. Use `5 if django.utils.six.PY2 else 6`.

**Comment by charettes** [comment]
I think this is related to the scoping rule changes of list comprehension in Python 3.

**Comment by adamchainz** [comment]
Yes makes sense. Thanks!

**Pull request merged**
