### PR TITLE
Refs #32655 -- Improved error if iter_test_cases() is passed a string.

### PR DESCRIPTION
**Pull request by cjerdonek**
https://code.djangoproject.com/ticket/32655

### CODE REVIEW

**Comment by felixxm** [comment]
@cjerdonek Thanks :+1: Is there anything left for this ticket? I'm asking because you used `Refs...` instead of `Fixed...` in your commit message.

**Comment by cjerdonek** [comment]
Thanks, @felixxm. I just did that because there was also discussion of deprecating `extra_tests` on the ticket. Alternatively, it could be marked "Fixed" and a new ticket opened.

**Comment by felixxm** [comment]
Yes, right. I still believe that we should deprecate it. Let's keep it as a `Refs`. Thanks :+1:

**Comment by cjerdonek** [comment]
> Let's keep it as a Refs

Okay, sure. Then maybe the ticket's title can be updated to reflect the expanded scope.

**Comment by felixxm** [comment]
> Then maybe the ticket's title can be updated to reflect the expanded scope.

Updated.

**Comment by cjerdonek** [comment]
Great, thank you.

**Pull request merged**
