### PR TITLE
[WIP] On the search for a trace :D

### PR DESCRIPTION
**Pull request by apollo13**

### CODE REVIEW

**Comment by apollo13** [comment]
buildbot, test this please.

**Comment by apollo13** [comment]
buildbot, test this please.

**Comment by auvipy** [comment]
all checks passed!! congratzz!!

**Comment by apollo13** [comment]
buildbot, test this please.

**Comment by apollo13** [comment]
buildbot, test this please.

**Comment by apollo13** [comment]
buildbot, test this please.

**Comment by apollo13** [comment]
buildbot, test this please.

**Comment by apollo13** [comment]
buildbot, test this please.

**Pull request closed without merging**
