### PR TITLE
Refs #18726 -- Added test for excluding circular related fields with F() expression.

### PR DESCRIPTION
**Pull request by felixxm**
Fixed in f19a4945e1191e1696f1ad8e6cdc6f939c702728. (@charettes thanks :star2: ). 

Ticket [18726](https://code.djangoproject.com/ticket/18726).

### CODE REVIEW

**Comment by charettes** [comment]
Are you sure it's 9dc367dc10594ad024c83d398a8e3c3f8f221446 that fixed the issue? f19a4945e1191e1696f1ad8e6cdc6f939c702728 looks like a better candidate.

**Comment by felixxm** [comment]
Yes I checked that. On 2aaabe2004e1953eb7d7057edcf2fabd37f7394d it is raising:
```
django.db.utils.ProgrammingError: missing FROM-clause entry for table "u1"
LINE 1: ...s_objectb" U0 INNER JOIN "queries_objectb" U2 ON (U1."id" = ...
```

**Comment by charettes** [comment]
That's really strange, 9dc367dc10594ad024c83d398a8e3c3f8f221446 only changed a method signature but only following commits make use of it.

**Comment by felixxm** [comment]
@charettes Ahh, you're right. I copied & pasted wrong hash :man_facepalming:

**Pull request merged**
