### PR TITLE
Fix #25694: Fix incorrect _uniq suffix on indexes during migrations.

### PR DESCRIPTION
**Pull request by jdufresne**
<https://code.djangoproject.com/ticket/25694>

### CODE REVIEW

**Comment by timgraham** [comment]
Trouble on Oracle:
```
======================================================================
FAIL: test_alter_field_add_index_to_integerfield (schema.tests.SchemaTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/tests/schema/tests.py", line 1866, in test_alter_field_add_index_to_integerfield
    self.assertEqual(self.get_constraints_for_column(UniqueTest, 'year'), [])
AssertionError: Lists differ: ['SYS_C00275653'] != []

First list contains 1 additional elements.
First extra element 0:
SYS_C00275653

- ['SYS_C00275653']
+ []
```

**Comment by jdufresne** [comment]
I see. I can reproduce locally as well.

Sorry, I'm not very well versed in Oracle, why does this constraint exist? Do all `IntegerField`s have a default constraint on Oracle? If it isn't too much trouble, do you have any information you can link to that explains the source of this?

I chose to test using an `IntegerField` instead of `CharField` as the [PostgreSQL backend adds additional indexes to for the `LIKE` operator](https://github.com/django/django/blob/fc4b4fd5850989458d6e54de12a29b2e40e94ce8/django/db/backends/postgresql/schema.py#L107-L125) that I was hoping to avoid working around, but maybe that will be simpler.

**Comment by charettes** [comment]
@jdufresne try `SELECT * FROM ALL_CONSTRAINTS WHERE CONSTRAINT_NAME = 'SYS_C00275653'` for more details. I think it might be caused by the fact the field is `NOT NULL`.

**Comment by jdufresne** [comment]
buildbot, test on Oracle.

**Comment by timgraham** [comment]
merged in 16614dcd5cad50648ef75021b919fc90dd449312, thanks!

**Pull request closed without merging**
