### PR TITLE
Fixed #26075 Added clearer wording on makemigrations command

### PR DESCRIPTION
**Pull request by ArcTanSusan**
Fixed verbiage when using the makemigrations command to make less
misleading.

### CODE REVIEW

**Comment by MarkusH** [comment]
Can you please wrap the code at 119 chars.

Could you also change the commit message to "Fixed #26075 -- Added clearer wording in makemigrations for one-off values"

Thank you :)

**Comment by ArcTanSusan** [comment]
@MarkusH Should this PR also have unit test(s) to check that wording?

**Comment by MarkusH** [comment]
> @MarkusH Should this PR also have unit test(s) to check that wording?

I don't mind not having them, for this kind of change. But if you're keen to write one, I'm all in.

**Comment by ArcTanSusan** [comment]
I fixed the col 80 flake8 problem. There are no unit tests in this PR.

**Comment by MarkusH** [comment]
Thanks for your work. Merged in b0803d64c4cd24c580a503cfe268e521128f45d7

**Pull request closed without merging**
