### PR TITLE
Fixed #32027 -- Fixed wrapping of long words in admin error messages.

### PR DESCRIPTION
**Pull request by matthiask**
https://code.djangoproject.com/ticket/32027#comment:1

Before:
image

After:
image

### CODE REVIEW

**Comment by carltongibson** [comment]
Hi @matthiask this is a behaviour change. Can I get you to open a Trac ticket for it please? Ta.

**Comment by matthiask** [comment]
@carltongibson Sure, will do. Thanks for the feedback.

(I'll do the same for the other CSS PRs too, then.)

**Comment by felixxm** [comment]
@matthiask Thanks :+1: I think we should do the same for `ul.errorlist li`.

**Comment by matthiask** [comment]
@felixxm Thanks for the feedback! I have updated the PR.

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Pull request merged**
