### PR TITLE
Simplified a bit GeoAggregate classes

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
Reporting Josh's comment from !3920:
> Mostly looks fine to me. If it gets merged, it'll make what I plan to do a lot easier, which is create a list of disallowed expressions, of which aggregates will also be included.
>Removal of the old gis.sql.aggregates.GeoAggregate is probably the wrong move. The regular aggregates.Aggregate base class has code in it to support old-style custom aggregates (see _patch_aggregate method), but I've not tested it with GeoAggregates. We can remove this in 2.0 I think.

**Comment by claudep** [comment]
I removed `gis.sql.aggregates.GeoAggregate` because I also removed `spatial_aggregate_sql` and was a bit annoyed to keep it just for compatibility, as I doubt we have many custom geo aggregates in the wild. I understand this is backwards incompatible. I'll see if I can improve that...

**Comment by akaariai** [comment]
I wouldn't worry too much about backwards compatibility for GeoAggregates.

**Comment by claudep** [comment]
We could also choose to skip 1.8 for this and concentrate on 1.9. @jarshwah?

**Comment by jarshwah** [comment]
Up to you but the patch looks really clean so I have no issues with landing it now.

**Comment by claudep** [comment]
So you are leaving your reticence about dropping deprecated GeoAggregate code?

**Comment by jarshwah** [comment]
Yes. If yourself and Ansii aren't concerned then I don't mind. The use case
for custom gis aggregates seems slim and easily fixed.

**Comment by claudep** [comment]
Merged in a34fba5e5

**Pull request closed without merging**
