### PR TITLE
Added Python 3.12 to daily builds.

### PR DESCRIPTION
**Pull request by felixxm**
See https://github.com/actions/setup-python/issues/514.

### CODE REVIEW

**Review by carltongibson — APPROVED** [review]
Oh, lovely! 🦄

**Comment by hugovk** [comment]
Also add `312` to `tox.ini`?

https://github.com/django/django/blob/321ecb40f4da842926e1bc07e11df4aabe53ca4b/tox.ini#L27

**Comment by felixxm** [comment]
> Also add `312` to `tox.ini`?
> 
> https://github.com/django/django/blob/321ecb40f4da842926e1bc07e11df4aabe53ca4b/tox.ini#L27

No. Python 3.12 is not officially supported (and cannot be). We're adding it to daily builds to catch issues with pre-releases.

**Comment by hugovk** [comment]
I see tox as a way to help end users easily test different versions, and the Trove classifier as a way to signal official support, but fair enough.

Anyway, really good 3.12 is already being tested on CI to help catch things early! 👍

**Pull request merged**
