### PR TITLE
Add normalize to floatformat

### PR DESCRIPTION
**Pull request by pinguin999**
If arg is "n", it will use Decimal normalize function:

https://docs.python.org/3.5/library/decimal.html#decimal.Decimal.normalize

### CODE REVIEW

**Comment by timgraham** [comment]
I'm not sure if going down the path of allowing string or integer arguments is a good idea -- it might be better to implement a custom template tag that meets your needs.

Design decisions are usually made on the [django-developers mailing list](https://groups.google.com/forum/#!forum/django-developers). Could you ask for feedback on this idea there?

**Comment by pinguin999** [comment]
Hi tim

thank you for the feedback. Do you have a better idea for the parameter?
The normalize function does exactly what I expect the floatformat to do (by default). 
Or should I add a normalize function to the defaultfilters?

In my project I have it as a custom template tag. 

Kolja

**Comment by timgraham** [comment]
I don't know if there's enough demand to justify adding this functionality to the existing template tag, so I suggested bringing it up on the mailing list. I don't think we're going to add any more built-in filters to Django since it's easy to write custom filters.

**Comment by timgraham** [comment]
Closing until the requisite discussion takes place. Also a ticket, docs, and tests are required.

**Pull request closed without merging**
