### PR TITLE
Fixed #21183 -- Filter block on the right covers information in admin

### PR DESCRIPTION
**Pull request by viciu**
Added filter toggle functionality to admin.
Collapse/expand state is remebered thanks to cookies.

Thanks Tuttle for the report.

### CODE REVIEW

**Comment by timgraham** [comment]
Closing due to lack of follow-up. Please send a new PR if you can update this, thanks!

**Comment by mevinbabuc** [comment]
Is there any development on this issue ? This is very annoying. It would be helpful if it was resolved.

**Comment by charettes** [comment]
@mevinbabuc, the pull request was closed due to lack of follow-up.

The proposed patch needs adjustments based the provided feedback from reviewers. Given the lack of interest to push things forward the suggested fix ended up rotting here.

If you're affected by this issue and are interested to see it fixed in the next Django release I would suggest you start from where this patch was left and proceed to [complete the required steps to get it merged](https://docs.djangoproject.com/en/dev/internals/contributing/).

**Comment by zubus** [comment]
Any way to do this currently?

**Pull request closed without merging**
