### PR TITLE
Fixed #28324 -- Made feedgenerators write feeds with deterministically ordered attributes.

### PR DESCRIPTION
**Pull request by gsauthof**
This simplifies the caching and comparison of generated feeds.
https://code.djangoproject.com/ticket/28324

### CODE REVIEW

**Comment by timgraham** [comment]
I'm not sure if the performance penalty is worth it. As you may know, Django provides [SimpleTestCase.assertXMLEqual()](https://docs.djangoproject.com/en/stable/topics/testing/tools/#django.test.SimpleTestCase.assertXMLEqual()) for comparison in tests. I don't see the relevance to caching as that's based on the request parameters, isn't it?

By the way, the first step in a proposal like this is to write to the the [django-developers mailing list](https://groups.google.com/forum/#!forum/django-developers), not to create a pull request.

**Comment by gsauthof** [comment]
I say the change is worth it. The extra sorting during XML writing shouldn't affect performance much because many elements don't have any attributes and elements with attributes only have a small number of them. Likely, there is no element that has more than 3 attributes. Thus, sorting is very cheap. Besides, the performance of the feed generator should be dominated by the IO operations.

I use the feedgenerator in a static serving scenario. That means the feeds aren't generated on the web-server but rsynced to the webserver. Thus, when they are byte-identical nothing gets copied and the web-server can happily serve the unchanged files from its cache. Or even reply with a 304 not-modified to conditional requests. In contrast to that when the feeds aren't byte identical for no reason the web-server must invalidate its cache and can't reply with a 304.

You know, the web-server/reverse-proxy really would be the wrong place to implement something equivalent to `assertXMLEqual()`.

**Comment by timgraham** [comment]
Please write to the mailing list to make sure there's consensus about that, thanks.

**Comment by gsauthof** [comment]
I've sent an email to the django-developers mailinglist a few minutes ago.

**Comment by timgraham** [comment]
Ok, it seems there's no objection. A Trac ticket is also needed.

**Comment by timgraham** [comment]
Perhaps we should add a unit test for `SimplerXMLGenerator` rather than testing this indirectly through `FeedGenerator`?

**Comment by gsauthof** [comment]
You can add just another test-case that directly tests SimplerXMLGenerator, if you like. Would only makes sense if SimplerXMLGenerator has other users that also depend on the ordering of attributes, though.

But I wouldn't remove the existing 'indirect' one. I mean, you probably can establish the ordered-attributes property by other means - and if you replace the SimplerXMLGenerator then you can re-use this test case.

**Comment by timgraham** [comment]
dumpdata's `XMLSerializer` also uses `SimplerXMLGenerator`. It was patched in 5bc3123479bd97dc9d8a36fa9a3421a71063d1da to pass `OrderedDict`s to enforce orderign. As far as I tested, this change would make those changes redundant. These are the only two uses of `SimplerXMLGenerator` in Django (feedgenerator and serializers) and it's not a documented API. @charettes, do you think we should proceed with this change and revert the redundant `OrderedDict`s in `XMLSerializer`?

**Comment by charettes** [comment]
@timgraham that makes sense to me!

**Comment by timgraham** [comment]
Updated in https://github.com/django/django/pull/8660.

**Pull request closed without merging**
