### PR TITLE
Fixed #25781 -- Simplified admin_views tests with client.force_login().

### PR DESCRIPTION
**Pull request by awwester**
https://code.djangoproject.com/ticket/25781

### CODE REVIEW

**Comment by timgraham** [comment]
This looks good from a quick glance and it would also be helpful to rename `self.u1 -> self.superuser` -> `self.u2 -> self.adduser`, etc.

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by awwester** [comment]
sure, i'll make that change in the next few days and update. Thanks.

**Comment by awwester** [comment]
@timgraham hey actually it's using that format (u1, u2, etc) in 22 different test files. I think it should stay as-is in this PR or would you like me to change that in admin_views.tests anyway?

**Comment by timgraham** [comment]
I think it'll help readability to use more descriptive names here.

**Comment by awwester** [comment]
users have been renamed and actually a lot of them could be removed because they weren't being used in all the classes they were defined. I also noticed in a lot of places client.login(username, password) could be removed as well in favor of client.force_login(user)

**Comment by timgraham** [comment]
merged in 550107ff756beeb17b465e98c26c59e3dcc5eb3e, nice work and thanks!

**Pull request closed without merging**
