### PR TITLE
Fixed #18349 -- Added ipv6 support to django.contrib.gis.geoip.

### PR DESCRIPTION
**Pull request by MRigal**
Thanks to j and fcurella for original patches.

This is rebased and documented version of previous PR #1986

### CODE REVIEW

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
Are you familiar with MaxMind's geo databases? It looks like this format is now "legacy" and there's a new format that presumably supports both IPv4 & 6. http://dev.maxmind.com/geoip/geoip2/geolite2/
Maybe we should be adding support for that instead?

**Comment by timgraham** [comment]
\cc @fcurella since you worked on the initial patch. Any ideas about my previous comment?

**Comment by fcurella** [comment]
I haven't look into geo stuff for a long time. I'll brush up and look at this tomorrow

**Comment by fcurella** [comment]
The new format comes with much nicer and more pythonic bindings (http://geoip2.readthedocs.org/en/latest/), which should make writing the new code much easier than what it was with the legacy API

**Comment by MRigal** [comment]
I had mentioned in the bug report that GeoIP2 would be better. I just didn't want to spend to much time on it and still close the ticket.
But great job @fcurella !

**Comment by fcurella** [comment]
@MRigal If you'd like to follow the work on #5062, your feedback is welcome :)

**Pull request closed without merging**
