### PR TITLE
Added Algerian Arabic language.

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by felixxm** [comment]
@claudep Thanks :+1: Can you add release notes?

**Comment by claudep** [comment]
Sure, it's out of question to merge this in stable, right?

**Comment by felixxm** [comment]
I was thinking about 3.1 :thinking: but I'm fine to backport this to 3.0.1. Are you going to fetch translations before [January, 2nd](https://github.com/django/django/blob/master/docs/releases/3.0.1.txt#L5)?

**Comment by claudep** [comment]
I don't always fetch translations for .1 releases, depending on the activity, I sometimes wait for the .2 release. After some thoughts, I think it would be wiser to commit this for 3.1.

**Comment by felixxm** [comment]
@infosrabah @claudep Thanks.

**Pull request merged**
