### PR TITLE
ticket_33616 Supporting robust on_commit handlers.

### PR DESCRIPTION
**Pull request by Dulalet**
Ticket #33616. Robust option added for on_commit handler.

### CODE REVIEW

**Review by ab-revanthgss — COMMENTED** [review]
@Dulalet Shouldn't we catch the exceptions raised by `func()` and stop the pipeline if the robust mode is enabled?

I think the implementation should be similar to what we have in the `send_robust()` function on the Signal module.
[https://docs.djangoproject.com/en/4.0/topics/signals/#sending-signals](https://docs.djangoproject.com/en/4.0/topics/signals/#sending-signals)

**Comment by jarshwah** [comment]
This will also require some changes to the documentation pages and an entry in the latest release notes.

**Comment by felixxm** [comment]
@Dulalet Do you have time to keep working on this?

**Comment by felixxm** [comment]
Closing due to inactivity.

**Pull request closed without merging**
