### PR TITLE
Simplified collapse.js with Element.closest().

### PR DESCRIPTION
**Pull request by jdufresne**
https://developer.mozilla.org/en-US/docs/Web/API/Element/closest

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Comment by felixxm** [comment]
@jdufresne Please update minified version of `collapse.js`.

**Comment by jdufresne** [comment]
:+1: Done.

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Comment by felixxm** [comment]
@jdufresne Thanks :+1:

**Pull request merged**
