### PR TITLE
Removed unnecessary import

### PR DESCRIPTION
**Pull request by sanchjat**
Removed unnecessary import.

As `functools` is already imported so instead of importing partial again `from functools import partial` . we can use it from `functools`.

### CODE REVIEW

**Comment by sanchjat** [comment]
pull-requests-windows

**Comment by sanchjat** [comment]
pull-requests-windows

**Comment by felixxm** [comment]
@sanchjat Windows build starts automatically, you don't need to call it manually. Please don't close/reopen your PRs multiple times, it only generates unnecessary notifications.

**Comment by felixxm** [comment]
We added `import functools` to make clear that `lru_cache` is used from `functools` rather then from `lru_cache` package. I don't see value in removing `from functools import partial` because it is clear that `partial` is from `functools`, it's more readable (IMO) and consistent with other code.

**Pull request closed without merging**
