### PR TITLE
Fixed #35187 -- Fixed @sensitive_variables/sensitive_post_parameters decorators crash with .pyc-only builds.

### PR DESCRIPTION
**Pull request by felixxm**
Thanks Jon Janzen for the implementation idea.

Thanks Marcus Hoffmann for the report.

Regression in 38e391e95fe5258bc6d2467332dc9cd44ce6ba52.

ticket-35187

### CODE REVIEW

**Comment by felixxm** [comment]
I don't see a reasonable (and valuable) way to test this. We could mock `inspect.getsourcelines()` to raise an exception, but since it's no longer used I don't see much value in such a test.

**Review by bigfootjon — APPROVED** [review]
I don’t think there’s a rest case to be added for this change, but perhaps we should have a test of pyc only projects?

**Comment by felixxm** [comment]
> I don’t think there’s a rest case to be added for this change, but perhaps we should have a test of pyc only projects?

Do you think it's possible to add tests for `.pyc`-only Django to the daily builds (as we did for `pypy`, #17499)? Would you like to work on this?

**Review by charettes — APPROVED** [review]

**Comment by bigfootjon** [comment]
> Do you think it's possible to add tests for .pyc-only Django to the daily builds (as we did for pypy, https://github.com/django/django/pull/17499)? Would you like to work on this?

I have no experience working with pyc-only projects but it sounds interesting to work on, so yes I can work on that.

Do you want me to file a ticket?

**Review by carltongibson — APPROVED** [review]
Makes sense. Thanks all.

**Comment by felixxm** [comment]
Thanks y'all for review :rocket: 

> Do you want me to file a ticket?

Ticket is not necessary at this stage.

**Comment by bigfootjon** [comment]
@felixxm, I've put up https://github.com/django/django/pull/17870 to add the daily pyc-only job. Please review at your convenience.

**Pull request merged**
