### PR TITLE
Moved migration exception classes to shared module

### PR DESCRIPTION
**Pull request by MarkusH**
This PR aims to provide a base cleanup before introducing more helpful exceptions in migrations when something fails.

### CODE REVIEW

**Comment by aaugustin** [comment]
Looks good.

I'm not sure why `IrreversibleError` was defined as a class attribute. It was introduced in 3b810c5656774b4e1a89fd69ff26935e0a5833d2. Perhaps @andrewgodwin can confirm if he had a reason?

**Comment by MarkusH** [comment]
Actually, I think I should update the tests too ...

**Comment by andrewgodwin** [comment]
Exceptions as class attributes is just a thing I do occasionally when I don't want to make a module for them and they're error codes for one specific class. There's no real reason to not have it separate.

**Comment by MarkusH** [comment]
Thanks Andrew.

**Pull request merged**
