### PR TITLE
Fixed #34140 -- Format python code blocks in documentation files under docs/releases

### PR DESCRIPTION
**Pull request by jvzammit**
# [Ticket \#34140](https://code.djangoproject.com/ticket/34140) -- part of it

## What have I done?

This is a "child" of https://github.com/django/django/pull/16261

As discussed in there (long comments thread, sorry) I applied the:

1. manual changes for `blacken-docs` to work
2. the changes by `blacken-docs` command

in _two_ separate commits.

Edit: Third commit fixes an error that I couldn't replicate locally with `make html` -- it needed the whole `sphinx-build` command. I expect this commit to be squashed on merge.

In order for the PR to not be huge, I worked on and applied the changes only to the `docs/releases` directory (and all its children).

So the objective of this PR is twofold:

1. Agree that this is the right direction going forward. If it is, we can split the work into separate PRs based on structure of the docs _and_ the current output of `blacken-docs` command when ran over the whole `docs` directory.

~~2. Merge this PR~~ Release notes will not be changed as part of this effort.

Thanks for the help so far @carltongibson @felixxm @adamchainz @pauloxnet @benjaoming @smithdc1

### CODE REVIEW

**Comment by pauloxnet** [comment]
I think the release notes are perhaps the only exception to code formatting because they reflect very old versions of the code based on very old Python versions. I would leave them as the last step if not completely excluded from this activity.

**Comment by jvzammit** [comment]
@pauloxnet I agree, makes sense. What do you think about the approach? I.e. steps 1 & 2 above?

**Comment by carltongibson** [comment]
Thanks for this @jvzammit! I didn't get to it this week, but you're on my list for next. 🎁

**Comment by pauloxnet** [comment]
> @pauloxnet I agree, makes sense. What do you think about the approach? I.e. steps 1 & 2 above?

Steps 1 & 2 make sense to me, maybe we can start from a small module and see what happen.

**Comment by jvzammit** [comment]
Closing in favour of https://github.com/django/django/pull/16496

**Pull request closed without merging**
