### PR TITLE
 Fixed #30097 -- Made 'obj' arg of InlineModelAdmin.has_add_permission() optional.

### PR DESCRIPTION
**Pull request by MaximZemskov**
Ticket [#30097](https://code.djangoproject.com/ticket/30097).

### CODE REVIEW

**Comment by carltongibson** [comment]
Hi @MaximZemskov. Thanks for this. The new test fails without the change so there's something amiss. 

@jdufresne: Do you have capacity to have a look at this? (Say if not: no worries!) Should this case have been part of be6ca89396c031619947921c81b8795d816e3285? (The [`auto_created` branch is adjusted but the other one not](https://github.com/django/django/commit/be6ca89396c031619947921c81b8795d816e3285#diff-3c42de3e53aba87b32c494f995a728dfR2024).) Thanks!

**Comment by timgraham** [comment]
I think it's needed. Basically, backwards compatibility is broken for third-party code that calls `InlineModelAdmin.has_add_permission()`  without `obj`.

`super()` doesn't get `obj` because `BaseModelAdmin.has_add_permission()` doesn't take it.

**Comment by jdufresne** [comment]
Yup. I agree with Tim. My change was backwards incompatible. This looks like a good approach to the fix.

**Comment by timgraham** [comment]
When the deprecation ends, I expect we'll remove `=None` from the signature, so I added a documentation note instead of changing the documented signature. I made a few other cosmetic edits and I think is good to go.

**Pull request merged**
