### PR TITLE
Fixed #33985 -- Used app_config.verbose_name in ContentType.__str__().

### PR DESCRIPTION
**Pull request by hrushikeshrv**
Fixes [#33985](https://code.djangoproject.com/ticket/33985)

### CODE REVIEW

**Comment by mh-firouzjah** [comment]
@felixxm so what changed your mind? there is no diff in our commits

**Comment by felixxm** [comment]
> @felixxm so what changed your mind? there is no diff in our commits

@hrushikeshrv assigned the ticket to themself and promised to fixed failing tests soon.

**Comment by hrushikeshrv** [comment]
@felixxm the tests are failing because they expect the `app_labeled_name` of `ContentType` to be lowercased. For example, one test case expects `ContentType.app_labeled_name` to be `'contenttypes_tests | site'`, while the value is `'Contenttypes_Tests | site'`. Should I resolve this by modifying `ContentType.app_labeled_name` or by modifying the tests?

**Comment by felixxm** [comment]
> Should I resolve this by modifying `ContentType.app_labeled_name` or by modifying the tests?

We should update assertions.

**Review by m-aciek — APPROVED** [review]

**Pull request merged**
