### PR TITLE
Implement `get_object_or_none`

### PR DESCRIPTION
**Pull request by dhilipsiva**
Often, when writing API-based Django application, I have a need to send different JSON replies based on which object was not found. I always end-up writing this every time. So added it thinking that many people will be needing this too.

### CODE REVIEW

**Comment by dhilipsiva** [comment]
I have also written test cases and documentation for the same.

**Comment by timgraham** [comment]
Thanks for the patch. This idea was marked "won't fix" in [#2659](https://code.djangoproject.com/ticket/2659). If you'd like to revisit this decision, please use the [django-developers mailling list](https://groups.google.com/forum/#!forum/django-developers).

**Comment by dhilipsiva** [comment]
Apologies. I did a search on GitHub Issues and I could not find anything related to this patch. Didn't realize that the linked issue existed over there.

**Comment by collinanderson** [comment]
( use .first() for this)

**Comment by dhilipsiva** [comment]
Thanks for the input :smile:. But I think it makes my code a little less pragmatic. :stuck_out_tongue:

**Comment by dhilipsiva** [comment]
Also it doesn't raise MultipleObjectsFound error

**Pull request closed without merging**
