### PR TITLE
Fast mssql tests for Django 1.8

### PR DESCRIPTION
**Pull request by akaariai**

### CODE REVIEW

**Comment by akaariai** [comment]
A backwards compatible approach for https://github.com/django/django/pull/5801

**Comment by timgraham** [comment]
Are you happy to commit this without any tests? I'm not so enthusiastic. ;-)

Another idea would be to ask django-mssql to include these changes (at least for 1.8/1.9). I believe it'd be easy for it to override the `BaseDatabaseWrapper.constraint_checks_disabled()` method with the implementation here and also to bundle a custom `loaddata` command (with a bit of copy/paste).

**Comment by akaariai** [comment]
Changes needed to mssql  can be found here: http://dpaste.com/050H9QX

The test execution speed on Django 1.8 was about half an hour with this patch. I got a lot of failures, it is hard to know which of those (if any) are caused by this patch.

**Comment by akaariai** [comment]
It seems if we were able to detect cases where we don't have any fixture to load, and bail out early in those cases, we would get tolerable performance. I'll check in to this.

Another option would be some for of a hook in loaddata, so that the conditional change in loaddata would be done by the backend instead. I think that would work, too, as the hook wouldn't need to contain a lot of code.

**Comment by akaariai** [comment]
With a change which skips constraint mangling in fixture loading I get a runspeed of around 2500 seconds on 1.8 branch. I think that is good enough for 1.8, so lets just do that. I'll get back to this tomorrow with a complete patch for 1.8 and mssql.

**Comment by akaariai** [comment]
See https://github.com/django/django/pull/5905 instead.

**Pull request closed without merging**
