### PR TITLE
Update Select2 to version 4.0.7

### PR DESCRIPTION
**Pull request by codingjoe**
Update vendored Select2 dependency to the latest minor release (4.0.3 -> 4.0.7).
<details>
<summary>Change log</summary>

### New features/improvements
- Do not close on select if Ctrl or Meta (Cmd) keys being held (#5222)

### Bug fixes
- Fixed issue where single select boxes would automatically reopen when they were closed (#5490, #5492)

### Miscellaneous
- Move almost and jquery-mousewheel to devDependencies (#5489)

### New features/improvements
- Add style property to package.json (#5019)
- Implement `clear` and `clearing` events (#5058)
- Add `scrollAfterSelect` option (#5150)
- Add missing diacritics (#4118, #4337, #5464)

### Bug fixes
- Fix up arrow error when there are no options in dropdown (#5127)
- Add `;` before beginning of factory wrapper (#5089)
- Fix IE11 issue with select losing focus after selecting an item (#4860)
- Clear tooltip from `select2-selection__rendered` when selection is cleared (#4640, #4746)
- Fix keyboard not closing when closing dropdown on iOS 10 (#4680)
- User-defined types not normalized properly when passed in as data (#4632)
- Perform deep merge for `Defaults.set()` (#4364)
- Fix "the results could not be loaded" displaying during AJAX request (#4356)
- Cache objects in `Utils.__cache` instead of using `$.data` (#4346, #5486)
- Removing the double event binding registration of `selection:update` (#4306)

#### Accessibility
- Improve `.select2-hidden-accessible` (#4908)
- Add role and aria-readonly attributes to single selection dropdown value (#4881)

### Translations
- Add Turkmen translations (`tk`) (#5125)
- Fix error in French translations (#5122)
- Add Albanian translation (`sq`) (#5199)
- Add Georgian translation (`ka`) (#5179)
- Add Nepali translation (`ne`) (#5295)
- Add Bangla translation (`bn`) (#5248)
- Add `removeAllItems` translation for clear "x" title (#5291)
- Fix wording in Vietnamese translations (#5387)
- Fix error in Russian translation (#5401)

### Miscellaneous
-  Remove duplicate CSS selector in classic theme (#5115)

### Bug fixes
- Replace `autocapitalize=off` with `autocapitalize=none` (#4994)

### Translations
- Vietnamese: remove an unnecessary quote mark (#5059)
- Czech: Add missing commas and periods (#5052)
- Spanish: Update the 'errorLoading' message (#5032)
- Fix typo in Romanian (#5005)
- Improve French translation (#4988)
- Add Pashto translation (`ps`) (#4960)
- Add translations for lower and upper Sorbian (`dsb` and `hsb`) (#4949)
- Updates to Slovak (#4915)
- Fixed Norwegian `inputTooShort` message (#4817, 4896)
- Add Afrikaans translation (`af`) (#4850)
- Add Bosnian translation (`bs`) (#4504)

### New features / Improvements
- Make tag matching case insensitive [https://github.com/select2/select2/commit/cb9a90457867ffb14c7b1550bb67e872e0a5c2dd, https://github.com/select2/select2/commit/1167bace78cd3b1a918c1b04f3bac54674eab62b]
- Support selecting options with blank or `0` option values [https://github.com/select2/select2/commit/16b4840c0e2df0461998e3b464ee0a546173950d, https://github.com/select2/select2/commit/0358ee528765157234643d289bce6b8ca5889c72]

### Bug fixes
- Fix issue with entire form losing focus when tabbing away from a Select2 control (#4419)
- Fix UMD support for CommonJS [https://github.com/select2/select2/commit/45a877345482956021161203ac789c25f40a7d5e]

### Documentation
- Github Pages documentation has been deprecated, replaced with https://github.com/select2/docs
- Add django-autocomplete-light to integrations [https://github.com/select2/select2/pull/4597]
- Correct typo in options page [https://github.com/select2/select2/pull/4389]
- Correct misspelling in AJAX query parameters example [https://github.com/select2/select2/pull/4435]
- "highlight" should be "focus" in focus example [https://github.com/select2/select2/pull/4441]
- Correct misspelling in `<select>` serialization example [https://github.com/select2/select2/pull/4538]
- Correct typos in documentation [https://github.com/select2/select2/pull/4663]

### Translations
- Add `errorLoading` Hungarian translation [https://github.com/select2/select2/commit/7d1d13352321e21670ff1c6cba7413aa264fd57a]
- Add `errorLoading` German translation [https://github.com/select2/select2/commit/4df965219ea4c39147fde9335bc260840465933a]
- Add Slovene language [https://github.com/select2/select2/commit/8e6422c570a87da8d89c45daf0d253695a943c84]
- Add `errorLoading` Galician translation [https://github.com/select2/select2/commit/8fcc6202c37f4e06d951342bf142a3b906b6b8e3]
- Add `errorLoading` Thai translation [https://github.com/select2/select2/commit/625fc78ee616baedf64aa37357403b4b72c7363c]
- Add `searching` and `errorLoading` Finnish translations [https://github.com/select2/select2/pull/4730]
- Add `errorLoading` Turkish translation [https://github.com/select2/select2/commit/fd4a0825315c7055347726d5818c999279f96ff8, https://github.com/select2/select2/commit/751b36767f9f28b9de9428d5e8035c9a404915d9]
- Add Armenian language [https://github.com/select2/select2/commit/f6fa52dcc02341df1523f50348f2effc54ee2911]
</details>

### CODE REVIEW

**Comment by codingjoe** [comment]
buildbot, test on selenium.

**Comment by codingjoe** [comment]
buildbot, test on selenium.

**Comment by LemonAndroid** [comment]
Why are you vendoring a javascript library in the first place?

**Comment by codingjoe** [comment]
> Why are you vendoring a javascript library in the first place?

Good question @LemonAndroid! We didn't want to use a CDN as it would break local development. This is something we in GeoDjango, but to be fair, you need an internet connection to see the map data anyways.

It would be more elegant to get the data via npm, no one has build a good release pipeline for that yet.

**Comment by LemonAndroid** [comment]
Maybe you should all switch to *Ruby on Rails*.

**Comment by codingjoe** [comment]
@carltongibson I tested it locally, the selenium tests fail, because bowser is too slow. What should I do now?

__can you maybe also delete the previous comment, for it being unrelated__

**Comment by carltongibson** [comment]
Hey @codingjoe. 

OK, I'll have a look. (Grrr. Selenium.) 

(Comment deleted.)

**Comment by LemonAndroid** [comment]
Ruby on Rails, sorry for unrelated comment

**Comment by LemonAndroid** [comment]
Ruby on Rails, sorry for unrelated comment

**Comment by LemonAndroid** [comment]
Ruby on Rails, sorry for unrelated comment

**Comment by LemonAndroid** [comment]
Ruby on Rails, sorry for unrelated comment

**Comment by LemonAndroid** [comment]
Ruby on Rails, sorry for unrelated comment

**Comment by LemonAndroid** [comment]
Ruby on Rails, sorry for unrelated comment

**Comment by LemonAndroid** [comment]
Ruby on Rails, sorry for unrelated comment

**Comment by codingjoe** [comment]
cc @kevin-brown

**Comment by carltongibson** [comment]
buildbot, test on selenium.

**Comment by carltongibson** [comment]
Grrr. So we're one from two on the Selenium builds, which are passing for me locally... (@apollo13 Do you have any thoughts there...?)

I just want to compare the checksums with the official package but, looks good!

**Comment by codingjoe** [comment]
> Grrr. So we're failing on the Selenium builds, which are passing for me locally... (@apollo13 Do you have any thoughts there...?)

We could wait until the statement is true, and add a timeout in case it isn't. That is common in selenium, but not really for that scenario. I'll try something.

> I just want to compare the checksums with the official package but, looks good!

I took files from the GitHub release. I figured, that's as close to the source as it gets.

**Comment by codingjoe** [comment]
buildbot, test on selenium.

**Comment by codingjoe** [comment]
@carltongibson I don't know why the other tests are failing, but selenium works :P

**Comment by codingjoe** [comment]
#workedOnMyMachine

**Comment by carltongibson** [comment]
Hey @codingjoe, OK, thanks, I'll have a play... 😬

> I took files from the GitHub release. I figured, that's as close to the source as it gets.

I'm quite sure you did. I still feel it's incumbent upon me to verify an error didn't slip in. 🙂

**Comment by felixxm** [comment]
We should add a short release note (`Minor features -> django.contrib.admin`), e.g.
```
 * Select2 library is upgraded from version 4.0.3 to 4.0.7. 
```

**Comment by apollo13** [comment]
> Grrr. So we're failing on the Selenium builds, which are passing for me locally... (@apollo13 Do you have any thoughts there...?)

Are they failing consistently on this PR and work on others? Then I fear there is something systematic behind it due to the upgrade? That said, selenium tests are hard to write and tend to break differently in different environments :( Don't have any good ideas on this one.

**Comment by carltongibson** [comment]
OK, thanks for the input @apollo13! I'm about to look into it now... 😬

@codingjoe: Checksums are correct, **except** for `js/i18n/sq,js`, which is correct except it has Windows line endings (CRLF) in the `select2-4.0.7` distribution, against Unix line endings (LF) in the checkin here. (I would open an issue there but it looks like https://github.com/select2/select2/issues/4703...)

**Comment by carltongibson** [comment]
buildbot, test on selenium.

**Comment by carltongibson** [comment]
I think we're looking at (guess) microseconds here. The visually observable behaviour in the browser is correct but putting a breakpoint into the test, the problem `results` variable is stale (from the previous assertion). 

I've tried just adding an additional assert, to buy a little time, but it maybe a new variable name, or breaking the test cases up a bit (or a less heavy `wait()` than the approach Joe tried in 20f79347dc0bade8043657a0675fe1c08d901845) may be needed.

**Comment by carltongibson** [comment]
buildbot, test on selenium.

**Comment by carltongibson** [comment]
buildbot, test on selenium.

**Comment by carltongibson** [comment]
buildbot, test on selenium.

**Comment by carltongibson** [comment]
Woot. 🎉

**Comment by carltongibson** [comment]
Sorry, I got excited by the tests passing. Release note. (Can you add that and squash @codingjoe? If not I'll do it tomorrow.)

**Comment by codingjoe** [comment]
buildbot, test on selenium.

**Comment by codingjoe** [comment]
buildbot, test on selenium.

**Comment by codingjoe** [comment]
buildbot, test on selenium.

**Comment by codingjoe** [comment]
buildbot, test on selenium.

**Comment by codingjoe** [comment]
@carltongibson :ok: it's done!

**Pull request merged**
