### PR TITLE
Fixed typos in test names and comment

### PR DESCRIPTION
**Pull request by minho42**

### CODE REVIEW

**Comment by carltongibson** [comment]
Hi @minho42. Thanks for this, again. 

[You seem to be sending in a small PR every couple of weeks with a few typos corrections](https://github.com/django/django/pulls?utf8=%E2%9C%93&q=+is%3Apr+author%3Aminho42+). Are you able to combine all your fixes into one PR, which would be easier to review and cleaner in the commit history?

**Comment by minho42** [comment]
Hi @carltongibson, 
Thanks for reviewing. 

Did you mean to combine all the previously merged commits with the current one?
If that's the case, I need some time to find out how.

**Comment by carltongibson** [comment]
Hi @minho42. No, I meant combine all the still-to-come fixes you can find into one PR. 

Are you using a script/tool to find these errors? Can we run that on the whole repo?

**Comment by minho42** [comment]
@carltongibson 
I'm using my own script to find typos which is still work in progress to go public.
Typos I found are from searching the whole repo, and going through those manually.
I found some here and there once in a while.
It's not like I'm separating all findings to small PRs.
But I can definitely combine as much as I can for the future fixes :)
Thanks again for your work.

**Comment by carltongibson** [comment]
Hi @minho42. Sounds like a good tool! Can you share a preliminary version so we can play?

**Comment by minho42** [comment]
Hi @carltongibson 
I'll try to make it a public repo soon! 
Will let you know.

**Comment by minho42** [comment]
Thanks!

**Comment by minho42** [comment]
Hi @carltongibson
Just made my script public. 
https://github.com/minho42/typofinder

**Pull request merged**
