### PR TITLE
Optimized backends tests by specifying a database table.

### PR DESCRIPTION
**Pull request by felixxm**
`backends.tests.FkConstraintsTests.test_check_constraints`:
Database | Before | After
--- | --- | ---
MySQL | 720s | 0.78 s
MariaDB | 188s | 0.65 s

### CODE REVIEW

**Comment by carltongibson** [comment]
🍿

**Comment by carltongibson** [comment]
So was it quicker? e.g. https://djangoci.com/job/pull-requests-bionic/database=mysql,label=bionic-pr,python=python3.8/10902/ still took 20mins? 🤔

**Comment by carltongibson** [comment]
Never mind — messages crossed. You filled in the table. 😀 (Now my 🍿 doesn't make sense.)

**Comment by felixxm** [comment]
I compared times of a single test `backends.tests.FkConstraintsTests.test_check_constraints` :smile:

**Review by carltongibson — APPROVED** [review]
Super thanks

**Pull request merged**
