### PR TITLE
Disallowed importing concrete models without an application.

### PR DESCRIPTION
**Pull request by aaugustin**
Removed fragile algorithm to find which application a model belongs to.

Fixed #21680, #21719. Refs #21794.

### CODE REVIEW

**Comment by aaugustin** [comment]
@timgraham I checked that there's nothing else to do in the code.

If I remember correctly, you had seen a paragraph of docs related to this that didn't make sense. I couldn't find it again. Do you remember where it is? If that helps, the "Features removed in 1.9" section of the release notes is correct.

**Comment by aaugustin** [comment]
Perhaps we should write a test for this...

**Comment by aaugustin** [comment]
... of course, anyone who dares change this code will feel free change the test, so I don't see much point in writing an artificial test.

**Comment by timgraham** [comment]
Just the doc you already updated -- I already replaced the weird text with the current description. Check the 1.8 docs for the old version (which could be fixed) https://docs.djangoproject.com/en/1.8/ref/models/options/#app-label

**Comment by loic** [comment]
LGTM

**Comment by aaugustin** [comment]
I don't understand why the tests don't pass, it looks like Jenkins didn't pick my fix. I'll rebase on top of the next commit to master and force push to see if I can get the tests to pass.

**Pull request merged**
