### PR TITLE
Fixed #19580 -- Unify reverse foreign key and m2m unsaved model querying

### PR DESCRIPTION
**Pull request by ahsanshafiq742**

### CODE REVIEW

**Comment by auvipy** [comment]
did you uncheck patch needs improvement on the ticket?

**Comment by ahsanshafiq742** [comment]
> did you uncheck patch needs improvement on the ticket?

Yes! I did it.

**Comment by ProProgrammer** [comment]
Hey @carltongibson requesting some help
First of all - Extremely sorry if this is not the right place to ask for help - please do guide me what medium should I use next time for queries of this nature.

**Setup:**
I was looking at Easy Pickings and noticed everything was assigned and none of the easy pickings were easy enough for me to understand.
For this particular PR #11807, I noticed you left a comment here: https://github.com/django/django/pull/8570#pullrequestreview-113506649

**Request:**
Would you be able to guide me or point me to someone who can guide me with what knowledge is required to be able to understand how to fix this issue and address your comment on #8570 so I can build on that knowledge and probably contribute to fixing this issue?

**Associated Trac:** https://code.djangoproject.com/ticket/19580

**Comment by ahsanshafiq742** [comment]
> Hey @carltongibson requesting some help
> First of all - Extremely sorry if this is not the right place to ask for help - please do guide me what medium should I use next time for queries of this nature.
> 
> **Setup:**
> I was looking at Easy Pickings and noticed everything was assigned and none of the easy pickings were easy enough for me to understand.
> For this particular PR #11807, I noticed you left a comment here: [#8570 (review)](https://github.com/django/django/pull/8570#pullrequestreview-113506649)
> 
> **Request:**
> Would you be able to guide me or point me to someone who can guide me with what knowledge is required to be able to understand how to fix this issue and address your comment on #8570 so I can build on that knowledge and probably contribute to fixing this issue?
> 
> **Associated Trac:** https://code.djangoproject.com/ticket/19580

**Comment by ahsanshafiq742** [comment]
> @ahsanshafiq742 Thanks for this patch 👍 Have you checked comments from previous versions (#8570, #7098)? Some of them are not addressed, e.g. [#8570 (review)](https://github.com/django/django/pull/8570#pullrequestreview-113177526) or [#8570 (review)](https://github.com/django/django/pull/8570#pullrequestreview-113506649), also release notes are missing.

I'll take care of the comments.

**Comment by sks444** [comment]
Hi @ahsanshafiq742, are you still working on this patch?

**Comment by ahsanshafiq742** [comment]
Yup

**Comment by nMustaki** [comment]
Hi, I've updated the changelog according to the comments on the previous Prs, here it is:

Unified behaviour of ForeignKey and ManyToManyField
---------------------------------------------------

The behavior of nullable related ``QuerySet`` has changed.

Nullable related ``QuerySet`` means a ``QuerySet`` for reverse relation
to a field which can be set to null.

Before, querying a nullable many-to-many relation was an error. For foreign
key relations there was no error. To make the nullable relations consistent
the following changes were made:

* Nullable many-to-many relations now return an empty queryset when the
  relation field is null (no change for foreign keys).
  For example::

      class Car(models.Model):
          drivers = models.ManyToManyField('Driver')

      class Driver(models.Model):
          name = models.CharField()

      Car.objects.create().drivers.all()

  returns ``EmptyQuerySet``
  Previously it would raise ``ValueError``

* For a foreign key relation, trying to add/remove/clear objects when the
  relation field is null is now an error (no change for m2m).
  For example, given these related models::

      class Poll(models.Model):
          question = models.CharField(max_length=200, unique=True, null=True)

      class Choice(models.Model):
          poll = models.ForeignKey(Poll, models.SET_NULL, to_field='question', null=True)
          choice = models.CharField(max_length=200)

      empty_poll = Poll.objects.create(question=None)
      choice = Choice.objects.create(choice='B')

  All the below statements now raise a ``ValueError`` ::

      # Previously created a Choice object with ``poll_id=None``
      empty_poll.choice_set.create()
      empty_poll.choice_set.get_or_create()

      # Previously the ``choice.poll_id`` remained to None
      empty_poll.choice_set.add(choice)

      # Previously did nothing
      empty_poll.choice_set.remove(choice)
      empty_poll.choice_set.clear()

* For a foreign key relation, trying to use a relation of any kind when the
  object isn't saved is now an error (no change for m2m).
  For example invoking::

      Poll(question="How?").choice_set

  now raises a ``ValueError``
  Previously it would return a ``RelatedManager``

**Comment by felixxm** [comment]
Superseded by #13784.

**Pull request closed without merging**
