### PR TITLE
Fixed E117 and F405 flake8 warnings.

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Comment by carltongibson** [comment]
@felixxm Without this CI will fail on all branches right, so backport across the board?

**Comment by felixxm** [comment]
Yes, I will backport this to all branches tested by Jenkins.

**Comment by felixxm** [comment]
@carltongibson I simplified this patch. Previous version can cause some issues with circular `*` imports, so I think we should keep this fix as simple as possible.

**Comment by carltongibson** [comment]
Yep looks better. No need for the `*query_all` if we're only using `Query`... 👍

**Pull request merged**
