### PR TITLE
Removed unnecessary __str__() methods in tests models.

### PR DESCRIPTION
**Pull request by felixxm**
This also changes `assertQuerysetEqual()`s to `assertSequenceEqual()` where appropriate.

Follow up to 555e3a848e7ac13580371c7eafbc89195fee6ea9 and 6461583b6cc257d25880ef9a9fd7e2125ac53ce1.

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Comment by timgraham** [comment]
Even if not necessary, it seems those methods could help with debugging a failed test?

**Comment by felixxm** [comment]
> Even if not necessary, it seems those methods could help with debugging a failed test?

True, but I don't think it's worth to keep them. We have ~ 1260 models and even without this patch only ~290 of them had `__str__` methods. It looks that we added them only for `assertQuerysetEqual()` and its previous behavior with calling `repr()` on values, see 3f7b3275627385f8f7531fca01cdda50d4ec6b6e.

**Review by carltongibson — APPROVED** [review]
OK. Thanks.

**Comment by timgraham** [comment]
I don't see a large benefit of removing code that could be needed to debug failures. We'll have failures like:
```
- <QuerySet [<Author: Author object (2)>, <Author: Author object (1)>]>
+ [<Author: Author object (1)>]
```
Especially on databases that don't use sequential primary keys, developers may need to add the `__str__()` methods back to help debug a failure. I wouldn't say we should add `__str__()` to all models, but if the work is already done...

**Comment by felixxm** [comment]
OK, let's close it.

**Pull request closed without merging**
