### PR TITLE
Fixed #21936 -- Refactored DeleteView to be compatible with SuccessMessa...

### PR DESCRIPTION
**Pull request by cpsimpson**
Refactored DeleteView to use the form related base classes and mixins, like the
other class-based generic editing views.  Added tests for the handling the
DELETE http method and ensuring the SuccessMessageMixin works. Updated DeleteView
documentation to reflect the new base classes.
The majority of the code changes were provided by Simon Charette.

### CODE REVIEW

**Comment by cpsimpson** [comment]
I've gotten my branch into a state where I can't figure out how to rebase properly to get rid of the merge commits.  Anyone have any ideas how I can get this back into a good state?

**Comment by timgraham** [comment]
Does https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/working-with-git/#after-upstream-has-changed help?

**Comment by cpsimpson** [comment]
Those were the instructions I was following.  I think I managed to get the merge commit back out now. So I think I'm getting closer.  Thanks.

**Comment by cpsimpson** [comment]
I'm not sure about the isort failure that I'm getting when it runs the build, either.  I've run isort -rc . in the root folder and commit all modified import statements.  Is there a way to tell what the error is?

**Comment by MarkusH** [comment]
Select the "default" build and click "Console Output" in the left menu: http://djangoci.com/job/isort/31/label=trusty-pr/console

```
ERROR: /home/jenkins/workspace/isort/label/trusty-pr/django/db/backends/sqlite3/schema.py Imports are incorrectly sorted.
```

**Comment by timgraham** [comment]
`_sqlite3` getting moved might be a Python version difference or something. Maybe we need to add it to "known_third_party" or something...

**Comment by cpsimpson** [comment]
That does seem to be the import statement that was causing the issue.  I've reverted my change to that file.  Is marking the import statement somehow something I should do in this pull request, or is it best handled separately?

**Comment by timgraham** [comment]
Separate change will be fine. What is your system/Python version? Latest version of isort?
Ubuntu 14.04/Python 2.7/3.4/isort 3.9.6 here and on CI.

**Comment by cpsimpson** [comment]
OS X (10.10.2), Python 2.7.9, isort 3.9.6

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
Sorry, this has gone stale again as messages tests have been moved out of contrib to `tests/messages_tests`.

**Comment by auvipy** [comment]
@timgraham opened a new pull #4256

**Comment by MarkusH** [comment]
Close as per request

**Pull request closed without merging**
