### PR TITLE
Fixed #32144 -- Made makemessages remove temporary files when locale path doesn't exist.

### PR DESCRIPTION
**Pull request by carltongibson**
Alternative to  #13609 ticket-32144

### CODE REVIEW

**Review by felixxm — APPROVED** [review]

**Comment by felixxm** [comment]
Thanks :1st_place_medal:

**Comment by boxed** [comment]
```python
            except BaseException:
                # Cleanup before exit.
                for build_file in build_files:
                    build_file.cleanup()
                raise
```

I don't understand.. this should have been a finally block:

```python
            finally:
                # Cleanup before exit.
                for build_file in build_files:
                    build_file.cleanup()
```

**Comment by carltongibson** [comment]
No. If it were in a finally block the files would be deleted when we exited the block, and then wouldn't be available where they're used later in the method.

**Comment by boxed** [comment]
Hmm.. But you're still going to stick to that copy pasting 
```python
for build_file in build_files:
    build_file.cleanup()

**Comment by boxed** [comment]
Sure.. if you put it in the same place. But it should be at the end of the function obviously. And only once instead of copy pasted super carefully in three places.

And `except BaseException`? Isn't that just to try to hide that you're doing `except:`? 

Anyway, this code now works as advertised at least. If you subclass `makemessages.Command` and supply your own `build_file_class` the code still has at least two more places where it can fail leading to temporary files left in the file system. I guess that's not a big concern.

**Comment by boxed** [comment]
I got this issue today again. Maybe we can revisit using try/finally to clean up files?

**Pull request merged**
