### PR TITLE
add Georgian mapping for URLify

### PR DESCRIPTION
**Pull request by Lh4cKg**

### CODE REVIEW

**Comment by Lh4cKg** [comment]
@timgraham what is problem in javascript?

**Comment by timgraham** [comment]
Looks good. Do you have a Georgian colleague who can give the mapping a +1?

**Comment by getsadzeg** [comment]
@timgraham Here I'm.

**Comment by timgraham** [comment]
merged in 18571aefe6dcb7d69b910ff57d83221a739c790c, thanks!

**Pull request closed without merging**
