### PR TITLE
Fixed #25415 -- made test runner perform system checks

### PR DESCRIPTION
**Pull request by adamchainz**
[Ticket 25415](https://code.djangoproject.com/ticket/25415#ticket)

### CODE REVIEW

**Comment by timgraham** [comment]
What can we do about the failures in the Django test suite? Maybe we could make this opt-in or opt-out. At least when debugging a single test, I think running the systems checks all the time could be overkill.

**Comment by adamchainz** [comment]
I've never found the checks to take too long but there have been more added in Django 1.8.

I guess there are potentially lots of failures since they have been disabled since 685edab9 , nearly a year. We could do opt-out with a decorator for test model classes (admin classes, etc.) that are known to fail the checks. I don't know exactly how we could do opt-in whilst shipping it as default for Django users.

**Comment by timgraham** [comment]
As I just [wrote to the mailing list](https://groups.google.com/d/topic/django-developers/GyuVJ-E6Or4/discussion), I'm fine to proceed with this. We need a separate commit to fix the existing errors/warnings in Django's test suite, as well as documentation for the change and a mention in the release notes.

**Comment by timgraham** [comment]
Closing due to inactivity. Please send a new PR if you return to it.

**Pull request closed without merging**
