### PR TITLE
Inconsistent caching of Site object by SiteManager

### PR DESCRIPTION
**Pull request by rjdp**
Handles Site object caching in SiteManager's get_current method in case of tenant schemas application, as in this case caching Site object based just Site ID is not enough.

### CODE REVIEW

**Comment by charettes** [comment]
I'm afraid this should be done in which ever Django third party you use that implements the `connection. get_schema()` method as it's not part of Django's database connection API.

**Comment by rjdp** [comment]
Thanks, so will it be more suitable to report this to tenant_schemas Developers? what happened is that I am working on a multischema Django app, and get_current_site often returns the wrong site. Kindly let me know your thoughts.

**Comment by charettes** [comment]
@rjdp if that's the third-party app you are using I assume it would be right project to report this to with a reference to this PR.

**Comment by rjdp** [comment]
Coincidentally I happen to use a 3rd party app to solve my issue but I think it is a generic use case of using multiple Db schemas with Django, and this should be taken care off, out of the box. Thanks for your suggestion, I will report this to the 3 rd party app developers. :)

**Comment by charettes** [comment]
@rjdp agreed, you might be interested in [this long standing ticket to add generic support for schema in Django](https://code.djangoproject.com/ticket/6148?cversion=0&cnum_hist=104).

**Pull request closed without merging**
