### PR TITLE
Fixed #28674 -- Removed unused check in QuerySet._batched_insert().

### PR DESCRIPTION
**Pull request by timgraham**
https://code.djangoproject.com/ticket/28674

### CODE REVIEW

**Comment by charettes** [comment]
Not sure if we have tests for this but one subtle difference here is that the `bool(objs)` check performed in `bulk_create` is done before the `objs` is converted to a list. This can change the behavior a bit when passing a generator to `bulk_create`.

**Comment by charettes** [comment]
e.g.

```python
Author.objects.bulk_create(
    Author(name=f"name-{index}") for index in range(100)
)
```

Would pass the `if objs` in `bulk_create`. I suggest we move the `if objs` check there after the `objs = list(objs)` call.

**Comment by timgraham** [comment]
I'm not understanding your point. As far as I can see, the relevant checks are `if objs_with_pk` and `if objs_without_pk` which couldn't be generators. https://github.com/django/django/blob/27193aea0088b238e3ee0f0f235364a34a09265c/django/db/models/query.py#L451-L464

**Comment by charettes** [comment]
@timgraham I missed the `if objs_with_pk` and `if objs_without_pk` checks, please ignore my comment.

**Pull request merged**
