### PR TITLE
Fixed #31937 -- Eased translation of time strings in some languages

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Review by felixxm — COMMENTED** [review]
@claudep Thanks :+1: 

I fixed `utils_tests.test_timesince.TimesinceTests` crash, but it still doesn't pick up Czech translations :thinking:

**Comment by claudep** [comment]
Sorry, I didn't handle the changed translatable strings in core.

**Review by lindacorbett — APPROVED** [review]

**Review by lindacorbett — COMMENTED** [review]
Where the bugs fixed or are they going to be fixed

**Comment by claudep** [comment]
@lindacorbett, fixed for the next Django version (4.0).

**Comment by uri-rodberg** [comment]
@claudep When will the strings be updated in Transifex? I can't see the new strings there. And is there a translation to English there? Is there a way to change the English translations for num==1 from "1 week" to "one week" etc? Or do we prefer to keep them as "1 week"?

**Comment by claudep** [comment]
Generally the new strings are put to Transifex around the time of branching (main -> stable/4.0.x), probably in September according to current roadmap. It could be possible to change the English translation, but it's not in my attributions.

**Pull request merged**
