### PR TITLE
Implementation of ASGI Lifespan protocol

### PR DESCRIPTION
**Pull request by kozzztik**
for ticket
https://code.djangoproject.com/ticket/31508

Here is also solution for problem with sync signals protocol.
Implementation expects that signal receivers return awaitable object or None.
In that case receiver can be:
1. Simple sync code that do some non-blocking staff like raise a flag that server is run in ASGI mode, or copy information of ASGI scope for component internal use.
2. Sync code that will create asyncio Future or Task for blocking staff, and return it as result.
3. Coroutine - finally it is a sync callable returning awaitable object itself. It will work well "as is" (that option used in test).

### CODE REVIEW

**Review by carltongibson — COMMENTED** [review]
Hi @kozzztik. 

I think this is probably too quick... from the ticket, it wasn't clear that we wanted to accept anything for Lifespan at all. (Andrew's [comment:6](https://code.djangoproject.com/ticket/31508#comment:6)) (I/We should probably adjust the ticket status)

The thought was maybe to take a middleware, or document how on Channels. (If folks want this, here's a generic middleware you can use.)

We do need to do something with the signals though. 

Right on the request path we have request started/finished using sync_to_async: 

https://github.com/django/django/blob/009fddc96b88a9aee1232d6a2637f2970fdcfb50/django/core/handlers/asgi.py#L154

It would be good to push that call down into `send()` depending on whether the handler was await able or not. (Similar to how middleware and views are handled now.) 

I'll cc @andrewgodwin to see what his thoughts are. 

Thanks

**Comment by kozzztik** [comment]
@carltongibson nevermind, if it will be decided to not implement it in django - close pull request much easier than open ) If will - here it is.
However looks like it is only way for underlying code to access ASGI startup context. And if Django supports ASGI that will be logical to support its features. it is just few lines of code.

Does it have sense to use sync_to_async here? "request_started" signal is used in classic blocking projects so it is logical to have wrapper to support both blocking and not-blocking implementations.

This signals are new and used only in ASGI context where blocking code have no sense. If someone want to use some of it in this signals, it may be up to him to wrap it?

**Comment by andrewgodwin** [comment]
Yes, I'm personally still not sure what this offers over `app.ready()`, so I don't think we should take this without being really clear what it's solving and then adding documentation that clears up when to use `ready()` vs lifespan events.

The sync/async signals thing is an issue that needs addressing, though - I'd be interested in iterating on that in a separate PR.

**Comment by carltongibson** [comment]
OK, let's close this, and I'll mark the ticket as `wontfix`. Thanks both. 

I've opened ticket-32172 to track making signals async-aware. @kozzztik If you'd like to take that on, it would be super. 
Thanks for the input!

**Comment by kozzztik** [comment]
@carltongibson np, I can take care of any async staff you need. JFYI I have own implementation of websockets & runserver for my project:
https://github.com/kozzztik/tulius/tree/dev/tulius/websockets/asgi
https://github.com/kozzztik/tulius/blob/dev/tulius/websockets/runserver.py
I have a time in next few weeks and will be happy to adapt this code for PR or write new implementation on your taste. Just let me know what is needed.

**Comment by carltongibson** [comment]
@kozzztik Super thanks. I see you've taken ticket-32172 👍 That's super 

Beyond that, there is lots to do — probably merits [discussion on the forum though](https://forum.djangoproject.com/c/internals/async/8): for instance async `runserver` support is needed — we could use Daphne, or in your case you've used `aiohttp` — but can we come up with [a `simple_server` like implementation](https://docs.python.org/3.9/library/wsgiref.html#module-wsgiref.simple_server) (in asgiref say) that would mean we don't need another external dependency? 

Then there's the auto-reloading issue, which is ticket-32173, and so on...

Hence the need for discussion on the forum — but all input very welcomed! 🙂

**Pull request closed without merging**
