### PR TITLE
Refs #25073 -- Copied recently added verbose_names to migrations.

### PR DESCRIPTION
**Pull request by timgraham**

### CODE REVIEW

**Comment by aaugustin** [comment]
This commit abuses the fact that changing `verbose_name` doesn't require a migration. If we're doing this in Django itself, perhaps the migrations framework should acknowledge that fact and not generate migrations when non-significant attributes change (e.g. `verbose_name`, `help_text`, etc.)

In order to remain consistent with the current design of migrations, we should have generated new migrations. I'd like to ping @andrewgodwin and check if he's OK with this change.

**Comment by timgraham** [comment]
I don't have a good reason why I did it this way this time other than I couldn't think of anything that could go wrong. Happy to revert and add the migrations if needed.

**Comment by carljm** [comment]
FWIW, I don't see anything wrong with taking advantage of the fact that certain field attributes don't change the schema in order to minimize the number of migrations. 

I would caution against taking an overly limited view of the "design of the migrations system" -- the system is very flexible, and "just auto detect and then apply" is not its only valid use. Editing past migrations (judiciously and when you know what you are doing) is a perfectly legitimate tool in the migrations toolbox, which is just as available to our users as it is to us, and is sometimes necessary and useful. I'd say this is one such case. 

All of that is orthogonal to the question of whether the migration system should ignore certain field attributes like verbose name that a) don't change the schema and b) don't need to be kept up to date for the sake of data migrations (eg choices). I think it probably should, but I don't think we have to feel bad somehow about making this commit before it does.

**Comment by andrewgodwin** [comment]
I'm fine with this - as mentioned on the recent django-developers thread, I do think we should start thinking about ignoring certain attributes during migration creation. Specifically, verbose_name can fall the wrong side of translation and people's default language, and choices can be dynamic, among other things.

**Comment by aaugustin** [comment]
Thanks everyone for clarifying. As long as there are no third-party migration executors (which could persist verbose_name in database schema comments, for example), the pragmatic approach to minimize the number of migrations works for me.

**Pull request merged**
