### PR TITLE
Fixed #24854 -- Refactored QuerySet._values

### PR DESCRIPTION
**Pull request by Ian-Foote**
Added `django.db.models.sql.query.Query.set_values()` method to handle
query mutation.

### CODE REVIEW

**Comment by Ian-Foote** [comment]
@jarshwah Review?

**Comment by jarshwah** [comment]
Looks good to me. You did show me another spot in sql/query where there appeared to be some duplication between this and that. Is there any opportunity to factor that?

**Comment by MarkusH** [comment]
Thanks for your work. Merged in 698be78d7438aade49d3cac5ea1f9de219d33e42  🔔🔨

**Comment by timgraham** [comment]
No chance to reply to Josh's comment? For next time, I'd try for a more descriptive commit message like "Moved some QuerySet._values() logic to a new Query.set_values() method."

**Comment by MarkusH** [comment]
I'm sitting next to @Ian-Foote and @jarshwah . The other location mentioned above doesn't give any improvement when changing.

**Comment by timgraham** [comment]
Gotcha, thanks!

**Pull request closed without merging**
