### PR TITLE
Fixed #25353 -- Changed LogEntry.action_time to a "date created".

### PR DESCRIPTION
**Pull request by timgraham**
https://code.djangoproject.com/ticket/25353#ticket

### CODE REVIEW

**Comment by timgraham** [comment]
Maybe `default=timezone.now` is a better option.

**Comment by charettes** [comment]
I think `default=timezone.now` is a better option yes.

**Comment by timgraham** [comment]
Oh, it seems that's incompatible with `editable=False`.

**Comment by timgraham** [comment]
Actually this was caused by model initialization with `None` for the field in the manager. I think tests should pass now.

**Comment by charettes** [comment]
LGTM assuming tests pass.

**Pull request merged**
