### PR TITLE
Corrected Slovak local name.

### PR DESCRIPTION
**Pull request by gardenerik**
# Trac ticket number

N/A

# Branch description

When talking about the Slovak language in the form "slovensky", it is correct to use lower case letters.

The same can be found (but already correct) in django/conf/locale/sk/LC_MESSAGES/django.po, line 260.

# Checklist
- [x] This PR targets the `main` branch. 
- [x] The commit message is written in past tense, mentions the ticket number, and ends with a period.
- [ ] I have checked the "Has patch" **ticket flag** in the Trac system.
- [ ] I have added or updated relevant **tests**.
- [ ] I have added or updated relevant **docs**, including release notes if applicable.
- [x] For UI changes, I have attached **screenshots** in both light and dark modes.

### CODE REVIEW

**Comment by felixxm** [comment]
@gardenerik Thanks :+1: 

@jangondol Can you confirm this change?

**Comment by felixxm** [comment]
Looks like a regression in b0ad5081d51afa0a7ca71e865180d02f37fa2cca (ticket-25717).

**Comment by nessita** [comment]
/remind me to check on confirmation in one month

**Review by bmispelon — APPROVED** [review]
I've had the chance to speak to a native Slovak speaker who approved these changes 👍🏻

**Comment by nessita** [comment]
> I've had the chance to speak to a native Slovak speaker who approved these changes 👍🏻

Thank you so much!

**Pull request merged**
