### PR TITLE
Fixed #25517 -- Make ConcatPair.coalesce() idempotent

### PR DESCRIPTION
**Pull request by wsmith323**
Modifed the ConcatPair.coalesce() method so that it can recognize
Coalesce() expressions it has previously added and not add them again.

### CODE REVIEW

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
I'll let someone more familiar with the expressions API comment on the fix, but as for the test, I think it'd be preferred if it didn't use the low level APIs (e.g. `SQLCompiler`) that may be subject to future refactorings. Is that possible?

**Comment by wsmith323** [comment]
I was trying to avoid making assumptions about the test execution environment. Specifically, that its configuration would cause it to execute ConcatPair.coalesce() if I exercised the ORM at a higher level. Perhaps I was being to paranoid. Please advise.

**Comment by timgraham** [comment]
Could you provide that test so I can better understand the concern?

**Comment by wsmith323** [comment]
I have modified the test per your request. My concern is that I don't know how to force the SQL generation down a path that I know includes ConcatPair.coalesce(). It is in the execution path now because Django tests happen to be run on SQLite and SQL generation for SQLite happens to include ConcatPair.coalesce(). That feels too implicit for my taste, but YMMV.

**Comment by jarshwah** [comment]
So I don't think I like this implementation. Traditionally how we enforce idempotency is by returning a copy(self) at some point and then operating on that. Arguably though your solution would seem more performant. I think I'd prefer the simplicity of a copy though, which highlights the intent a lot more clearly. Alternatively, you could swap `self.source_expressions` pre and post coalesce. We also need to consider what happens if you compile the same expression on multiple backends:

```
qs = Model.objects.annotate(c=Concat('a', 'b'))
sqlite_result = list(qs.using('sqlite'))
pg_result = list(qs.using('postgres')) # contains coalesce!
```

Here are both ideas: https://gist.github.com/jarshwah/9dcffab744ed8d48993e

To test, could it be enough to compare the count of all source expressions?

```
pair = ConcatPair(Value('a'), Value('b'))
pair_node_count = len(pair.flatten())
pair.coalesce()
self.assertEqual(len(pair.flatten()), pair_node_count)
```

Depending on the final implementation, you might also want to test the implementation of as_sqlite somehow, considering it is now responsible for behaving correctly. The current test you have is probably good enough. Most expression tests rely on calling public apis and "eventually" getting to the bit you're trying to test. I think this is fine considering CI runs the entire test suite across all backends. That said, if it's possible to test a smaller unit in an easy way (like testing coalesce() directly above), then go for it.

**Comment by akaariai** [comment]
I like the copy alternative. The set_source_expression() alternative has a unlikely, yet possible race condition. The copy alternative doesn't. I don't believe performance issues in this expression are going to affect real code that much, so that shouldn't be a big consideration.

**Comment by wsmith323** [comment]
Let's be clear here. I am not introducing the set_source_expression()-based implementation of ConcatPair.coalesce() with this change. It is already there. I just made it idempotent. Obviously, there are larger issues. Unfortunately, I don't currently have the skill to deal with the larger issues or the bandwidth to gain that skill right now. I will leave the resolution of #25517 to those that do.

**Comment by jarshwah** [comment]
Hi @wsmith323, sorry if I offended you in some way, that was not my intention. I'm aware this bug wasn't caused by you because it was actually caused by me. The `set_source_expression` alternative that akaariai was discussing was my gist proposal, not the existing implementation that you were changing. 

Each change, bug fix, and feature goes through code review. Funnily, it's the small patches that usually get the most thorough of reviews. The issue I was taking with your fix was the way you were making the operation idempotent (by inserting marker attributes). My suggestion to return a copy achieves the same (or very similar) outcome, but remains consistent with the rest of the expressions code.

Thank you for taking the time to contribute back. It'd be really great if you could follow this through to completion, but that's fine if you can't. You were very close to an ideal solution. For reference, https://gist.github.com/jarshwah/9dcffab744ed8d48993e#file-copy-diff is what we should go with.

**Comment by wsmith323** [comment]
Hi @jarshwah. Sorry I appeared offended. I am not. I didn't read your comments as carefully as I should have and mis-interpreted the target of @akaariai 's comments. It did seem to me at the time that things had devolved into somewhat of a bikeshed discussion, as you alluded to. You and the other participants have stronger opinions and much more familiarity with the context of the code in question than I. For what its worth, I agree that the copy solution is the best one. But it shouldn't come from me. You wrote it. You wrote the code that it fixes. You have already written a simple test that should work to test it. Anything I would submit at this point would just be copying your work. I'm not ok with that. This solution should come from you.Best regards.

**Comment by jarshwah** [comment]
No worries, I'll pick it up from here then. Thanks for the report and patch though!

**Pull request closed without merging**
