### PR TITLE
Fixed #26022 -- Used the context manager version of assertRaisesMessage in some tests.

### PR DESCRIPTION
**Pull request by hramezani**
rewrite django admin register decorator some test

### CODE REVIEW

**Comment by timgraham** [comment]
That's fine, do you want to check the rest of the tests to see if there are other instances that it makes sense to change? Of course there's `assertRaises` too. Another thing to look for is `six.assertRaisesRegex`. If a regular expressions isn't used in the message, we could switch those to `assertRaisesMessage`.

**Comment by hramezani** [comment]
there is many test that to be changed. do you say that i do all test in this pull request?

**Comment by timgraham** [comment]
Yes, that's fine. You can use separate commits for each type of change (convert to context manager, replace six.assertRaisesRegex, etc.)  if you like.

**Comment by hramezani** [comment]
@timgraham  i convert all `assertRaisesMessage` to context manager version. please check it. 
I continue to convert remaining types(`assertRaises`, `six.assertRaisesRegex`).

**Comment by hramezani** [comment]
@i close this pull request , I want to create a comperhensive pull request include all type of tests convertion (`assertRaises`, `assertRaisesMessage`, `six.assertRaisesRegex`)

**Pull request closed without merging**
