### PR TITLE
use collections.ChainMap to simplify code

### PR DESCRIPTION
**Pull request by linchiwei123**

### CODE REVIEW

**Comment by felixxm** [comment]
Please don't send the same change multiple times.

**Comment by linchiwei123** [comment]
> Please don't send the same change multiple times.

Sorry, i thought just use ChainMap(*dicts) might better than dict(ChainMap(*dicts))

**Comment by felixxm** [comment]
You can push more commits to the first PR.

**Comment by linchiwei123** [comment]
> push more commits to the first PR

thank you

**Pull request closed without merging**
