### PR TITLE
Used GitHub actions for JavaScript tests.

### PR DESCRIPTION
**Pull request by orf**
See https://github.com/django/django/pull/13840

### CODE REVIEW

**Comment by carltongibson** [comment]
Idea on the other thread was literally just about running these JS tests (especially this week when maybe sorting out dependencies isn't top priority...) 

What's your thought @felixxm? A low touch test-case? (If you'd rather move more slowly, no problem!)

**Comment by felixxm** [comment]
@orf Thanks :+1: I pushed minor edits.

**Comment by felixxm** [comment]
... and we hit the same timeout issue :exploding_head::
```
Fatal error: Navigation Timeout Exceeded: 5000ms exceeded
```
as on Jenkins :wink:

**Comment by orf** [comment]
Hmm, this worked before. Even so bringing them into the repository so other contributors can help fix them is a good thing, no?

And I thought the issue with Jenkins was to do with installing specific nodejs versions?

**Comment by felixxm** [comment]
> And I thought the issue with Jenkins was to do with installing specific nodejs versions?

No, like here sometimes it crashes with timeout error :shrug:

**Comment by orf** [comment]
Yeah, sometimes browser tests can be a pain 😞.

So what do we want to do here? I haven't heard anything back on the forums post about this yet, so I'm unsure of the status.

Even if the tests fail sometimes like Jenkins I still see clear benefits to merging this 🤷‍♀️

**Comment by pope1ni** [comment]
So in the logs it looks like `puppeteer@1.20.0` is being installed. This was released on 16 March 2018. The latest release in v5.5.0.

We're not specifying a version for this package explicitly, relying on `grunt-contrib-qunit`. See 99cefea360435b1f1d3497127253ae504069fc69.

It looks as though it is pinned as `^4.0.0` in the latest version of `grunt-contrib-qunit`, so perhaps we should try bumping `grunt-contrib-qunit` to the latest version (also `4.0.0`). And/or we can explicitly pin a newer version of `puppeteer` in our own `package.json`.

It feels like it is worth a shot to see if this solves the issue.

**Comment by felixxm** [comment]
> So what do we want to do here? I haven't heard anything back on the forums post about this yet, so I'm unsure of the status.

Don't worry, I'm going to merge this.

**Comment by orf** [comment]
> > So what do we want to do here? I haven't heard anything back on the forums post about this yet, so I'm unsure of the status.
> 
> 
> 
> Don't worry, I'm going to merge this.

Awesome! I didn't mean to be pushy I just have the (increasingly!) rare mix of time and motivation to work on this right now. I definitely wouldn't want to go forward if you're not comfortable or have reservations.

Anyway let's see how it goes, and we can regroup on the forum post?

**Comment by felixxm** [comment]
@pope1ni I added your suggestion in a separate commit.

**Comment by felixxm** [comment]
@orf We need another workflow for JavaScript tests that would run hourly on the master branch  (if there is a new changeset). This would allow disabling the [javascript-master](https://djangoci.com/job/javascript-master/) job on Jenkins. Can you help?

**Comment by orf** [comment]
Absolutely! Can you elaborate a bit though: you want it to run hourly, but only if something has been merged?

We can set up an hourly master scheduled job easily enough (can make a PR this evening), but I'm not sure if the "if there is a new changeset" bit is possible.

**Comment by felixxm** [comment]
> Absolutely!

Thanks :+1: 

> Can you elaborate a bit though: you want it to run hourly, but only if something has been merged?

Yes.

> We can set up an hourly master scheduled job easily enough (can make a PR this evening), but I'm not sure if the "if there is a new changeset" bit is possible.

If not, running it daily should be enough.

**Comment by pope1ni** [comment]
It looks as though this question has cropped up before. I think the idea is that you schedule the job and abandon it early if there are no changes - I'm not sure you can prevent a run from starting. Or perhaps the way is to have a scheduled job that performs a bunch of checks and then manually spawns off whichever jobs are appropriate based on whether there were any commits and what files changed, e.g. only spawn the job for the JavaScript tests if a JavaScript file changed within the last hour.

Can't promise that any of these provide the right solution, but may be useful as a starting point:

- https://github.community/t/trigger-action-on-schedule-only-if-there-are-changes-to-the-branch/17887
- https://github.community/t/trigger-workflow-if-there-is-commit-in-last-24-hours/17074/3
- https://stackoverflow.com/questions/63014786/how-to-schedule-a-github-actions-nightly-build-but-run-it-only-when-there-where

**Comment by orf** [comment]
> > Absolutely!
> 
> 
> 
> Thanks :+1: 
> 
> 
> 
> > Can you elaborate a bit though: you want it to run hourly, but only if something has been merged?
> 
> 
> 
> Yes.

I can make it daily then, but am I being stupid? Why not just run the task on a commit to master, rather than up to an hour after?

**Comment by pope1ni** [comment]
> I can make it daily then, but am I being stupid? Why not just run the task on a commit to master, rather than up to an hour after?

I guess it is a matter of resources. (Although this should be less of an issue on GitHub vs Jenkins.)

If the tests take significant time and you run it after every commit you could end up with a large backlog if you push lots of commits as separate pushes in a short period of time. I suspect an hour was used as it covered all of the tests running to completion before the next set started.

**Comment by felixxm** [comment]
> I can make it daily then, but am I being stupid? Why not just run the task on a commit to master, rather than up to an hour after?

Because it's only a control build, we don't need to run it after each commit. This may look unnecessary for JavaScript tests, but we do the same for other [build matrices](https://djangoci.com/view/Main/) on "master":
- hourly: `django-windows`, `django-selenium`, `django-master`,
- daily: `django-mariadb`, `django-oracle`.

**Comment by orf** [comment]
Ahh ok, I understand. I think auto-cancelling "redundant" pipelines might be a better option here? It could also apply to branches: if you've got 3 builds pending, cancel all but the latest one. Github actions doesn't support this out of the box yet, but it's apparently on their roadmap and there is an action we can use to enable this: https://github.com/marketplace/actions/auto-cancel-redundant-workflow

This seems cleaner than a cronjob?

**Comment by pope1ni** [comment]
> Ahh ok, I understand. I think auto-cancelling "redundant" pipelines might be a better option here? It could also apply to branches: if you've got 3 builds pending, cancel all but the latest one. Github actions doesn't support this out of the box yet, but it's apparently on their roadmap and there is an action we can use to enable this: https://github.com/marketplace/actions/auto-cancel-redundant-workflow

That's nice. Makes sense to me.

**Comment by orf** [comment]
PR is here: https://github.com/django/django/pull/13961

**Pull request merged**
