### PR TITLE
Fixed #34639 -- Made admin changelist use distinct() instead of Exists() to prevent duplicates.

### PR DESCRIPTION
**Pull request by charettes**
As discussed [on Trac](https://code.djangoproject.com/ticket/34639#comment:11)

### CODE REVIEW

**Comment by felixxm** [comment]
@betaflag Does it work for you?

**Review by felixxm — COMMENTED** [review]
@charettes Thanks :+1: 

I restored some assertions to avoid regression with undeletable querysets.

**Comment by betaflag** [comment]
Sorry for the late reply, I was in vacations. I've just tested with my repo and it works 🎉 This is amazing, I wasn't expecting it to be fixed so soon. What's the best way to sponsor you / show gratitude for your work ?

**Comment by felixxm** [comment]
@betaflag Thanks for checking :+1: 

> What's the best way to sponsor you / show gratitude for your work ?

If you would like to donate to the DSF you can do this 

- on our website https://www.djangoproject.com/fundraising/ or
- via GitHub sponsors: https://github.com/sponsors/django.

**Pull request merged**
