### PR TITLE
optimized field_names lookup

### PR DESCRIPTION
**Pull request by jack-cvr**

### CODE REVIEW

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
Do you have any benchmarks to share? `get_fields()` does seem to cache its results internally so I'd be curious to know how much this change helps.

**Comment by jack-cvr** [comment]
No matter get_fields cache its results or not. Becouse creating a set() of fields for each object is not necessary.

**Comment by timgraham** [comment]
Thanks for clarifying; merged in a1b9737aeaed4e218e264369e2f6591c8c03aafd.

**Pull request closed without merging**
