### PR TITLE
[1.9.x] Add missing stacklevel for management command deprecation warning

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
@timgraham Opinion?

**Comment by timgraham** [comment]
Could it be helpful to add the command's name to the message (alternatively or in addition to this)?

**Comment by claudep** [comment]
Could be, but if the command is run through the command line, the command name should be obvious, and if it is run through call_command, the `stacklevel=3` should reveal the command name.

**Comment by timgraham** [comment]
Whatever you think. I don't recall any experience with the warning myself.

**Comment by claudep** [comment]
Committed in 5f5d65460.

**Pull request closed without merging**
