### PR TITLE
Fixed #35693 -- Made password validators callable.

### PR DESCRIPTION
**Pull request by Antoliny0919**
#### Trac ticket number

ticket-35693

#### Branch description
[Continue @iamkorniichuk's PR](https://github.com/django/django/pull/18481)
Implemented a `__call__`magic method to enable password validators to perform validate through `__call__`.

#### Checklist
- [x] This PR targets the `main` branch. 
- [x] The commit message is written in past tense, mentions the ticket number, and ends with a period.
- [x] I have checked the "Has patch" ticket flag in the Trac system.
- [x] I have added or updated relevant tests.
- [x] I have added or updated relevant docs, including release notes if applicable.
- [ ] I have attached screenshots in both light and dark modes for any UI changes.

### CODE REVIEW

**Comment by sarahboyce** [comment]
I'm not 100% sure this is worth it just for the consistency, but if we were to do this:

- validators also have an `__eq__` method, if we are adding the call for consistency, I feel like we should add this for consistency. We should also consider whether to inherit from `BaseValidator` for example.
- I would expect the docs in this section to be updated: https://docs.djangoproject.com/en/5.1/topics/auth/passwords/#writing-your-own-validator

**Comment by Antoliny0919** [comment]
> I'm not 100% sure this is worth it just for the consistency, but if we were to do this:
> 
>     * validators also have an `__eq__` method, if we are adding the call for consistency, I feel like we should add this for consistency. We should also consider whether to inherit from `BaseValidator` for example.
> 
>     * I would expect the docs in this section to be updated: https://docs.djangoproject.com/en/5.1/topics/auth/passwords/#writing-your-own-validator

Thank you @sarahboyce !!
I agree with this point as well. Password validators and regular field validators work in different ways. Given this, I’m also not 100% convinced that changing password validators to behave like field validators for the sake of consistency would be particularly useful.
My perspective is that, for the sake of consistency, password validators should also be fully aligned with regular field validators, allowing validation through the is_valid method. However, I believe such a change would be difficult because password validators make use of the additional user parameter.
Perhaps, given the existence of the user parameter, password validators should be considered a different type of validator from regular field validators. In that sense, the current implementation might actually be appropriate.
I think this issue requires discussion.

**Comment by sarahboyce** [comment]
> I think this issue requires discussion.

Yes, having thought some more, any custom password validator (as it doesn't inherit from anything) would not have these changes. So it's not something folks could "rely" on :thinking: 
I am going to ask for more discussion on the ticket :+1:

**Comment by Antoliny0919** [comment]
I have many thought about adding the `__call__` and `__eq__` magic methods to password validators in order to maintain consistency with general validators.
The conclusion is that, in order to maintain consistency between the password validator and standard validators, the password validator should be a customizing form of the standard validator class, while preserving the unique features of the password validator as much as possible.
An example of this would be the `MinimumLengthValidator` for the password validator.
```
@deconstructible
class MinimumLengthPasswordValidator(BaseValidator):
    message = ngettext(
        "This password is too short. It must contain at least "
        "%(limit_value)d character.",
        "This password is too short. It must contain at least "
        "%(limit_value)d characters.",
    ),
    code = "password_too_short"

    def __call__(self, *args, **kwargs):
        return self.validate(*args, kwargs)

    def validate(self, password, user=None):
        if len(password) < self.limit_value:
            params = {"limit_value": self.limit_value}
            raise ValidationError(self.message, code=self.code, params=params)

    def get_help_text(self):
        return ngettext(
            "Your password must contain at least %(limit_value)d character.",
            "Your password must contain at least %(limit_value)d characters.",
            self.limit_value,
        ) % {"limit_value": self.limit_value}
```
I think inheriting from MinLengthValidator to implement it is a good approach as well.
```
@deconstructible
class MinimumLengthPasswordValidator(MinLengthValidator):
    validate = __call__
```
Based on the discussion with Ryan Hiebert, I think it is better to maintain consistency with standard validators for password validators that do not use the user parameter.
Could you please review these changes? @sarahboyce 🙂

**Comment by sarahboyce** [comment]
@Antoliny0919 feel free to continue to work on this branch to make proposals on how to improve validators (including investigating if `MinLengthValidator` can be reused). I have closed the associated ticket but that's not me closing down further thoughts/proposals

**Comment by Antoliny0919** [comment]
If you'd like to discuss anything related to password validators, feel free to join this discussion!
[discussion](https://forum.djangoproject.com/t/improving-consistency-between-field-validators-and-password-validators/37040)

**Pull request closed without merging**
