### PR TITLE
Fixed #25772 -- Corrected len lookup on ArrayField

### PR DESCRIPTION
**Pull request by Uran198**

### CODE REVIEW

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
@mjtamlyn - look okay to you? I'd write the string without backslahes, otherwise looks okay to me. Maybe dict interpolation could be an improvement too, e.g. `CASE WHEN %(lhs)s`.

**Comment by mjtamlyn** [comment]
LGTM. I'm not 100% sure how I feel about hard coding the SQL here, it'd be awesome if we wrote some other expressions, but that's probably just cruft.

**Comment by timgraham** [comment]
merged in 88fc9e2826044110b7b22577a227f122fe9c1fb5, thanks!

**Pull request closed without merging**
