### PR TITLE
Added note to bump stable branch docs config on release.

### PR DESCRIPTION
**Pull request by carltongibson**
django_next_version in docs/conf.py should be bumped in stable branch on final
release.

### CODE REVIEW

**Review by felixxm — COMMENTED** [review]
@carltongibson Thanks :+1: I think we should move this note to the ["Pre-release tasks"](https://docs.djangoproject.com/en/3.2/internals/howto-release-django/#pre-release-tasks), maybe up to the 7th point :thinking: .

**Comment by carltongibson** [comment]
Hey @felixxm -- yes, i was pondering if it's a _When creating the new stable branch_ task. Let's decide tomorrow. 😉

**Comment by timgraham** [comment]
I think it's fine to do when creating a new stable branch. This controls whether the version number or "Development version" appears in the versionadded/changed annotations.

Actually, it might be feasible to remove this in favor of checking `django.VERSION`. If the last three parts of the tuple are `(0, 'alpha', 0)` then it's a pre-alpha development version. It's unclear under what conditions `django.VERSION` can't be imported though (added in 373df56d36891b9ab1f88519bf9e8f3c0b3bb108).

**Comment by carltongibson** [comment]
Hey Tim — thanks for looking — another lurker on my list 🤹‍♂️. 

I've adjusted the comment to go at the _creating new stable branch_ step (which is 9 currently). 

> ...it might be feasible to remove this in favor of checking django.VERSION. ...

That would be better. 

> It's unclear under what conditions django.VERSION can't be imported though (added in 373df56).

Looking above I wonder how this could **ever** (excluding syntax errors and the like) fail now: 

https://github.com/django/django/blob/4a77aeb1f86bc06e18023cac10109e067ed20800/docs/conf.py#L24-L25

If that went wrong we'd want it to crash no? 🤔

I need to have a little dig around.

**Review by felixxm — APPROVED** [review]

**Comment by carltongibson** [comment]
Tim's https://code.djangoproject.com/ticket/21400#comment:6 — reloading Django on the build server to get the right version. Grrr. 

I think merge this for now, and see **if** there's an adjustment as time/bandwidth/motivation permits. 

Thanks both!

**Pull request merged**
