### PR TITLE
 Refs #34118 -- Added Python 3.12 to classifiers and tox.ini, and doc'd Python 3.12 compatibility in Django 4.2.x.

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Review by charettes — APPROVED** [review]

**Review by carltongibson — APPROVED** [review]
Super! 👍

**Comment by pauloxnet** [comment]
Great 😃

**Comment by felixxm** [comment]
Thanks y'all for reviews :rocket:

**Pull request merged**
