### PR TITLE
Fixed #29822 -- Add a Timezone aware datetime widget for admin

### PR DESCRIPTION
**Pull request by Shubh1815**
Ticket :- [https://code.djangoproject.com/ticket/29822](https://code.djangoproject.com/ticket/29822)

Timezone conversion is handled on  frontend using `DateTimeShortcuts.timezoneOffset`.

### CODE REVIEW

**Review by venugopalc80 — APPROVED** [review]

**Review by carltongibson — COMMENTED** [review]
Hi @Shubh1815 — thanks for picking this up. 

At first pass we're missing tests for the new widget — at least some parallel to those for `AdminSplitDateTime` in `tests/admin_widgets`, but likely also UI tests with Selenium, and  `js_tests` for `DateTimeShortcuts.js` — You need to show that with various inputs the transformations are correct. 

With some tests in place, it's easier to think about the implementation, but, it doesn't look like you've used [the suggested `Intl` API from the discussion](https://groups.google.com/g/django-developers/c/ti1wh0S_gLc) — was there a reason for that? 🤔

Also documentation and release notes. The new widget isn't wired up by default, so how are folks to know about it, and how to use it? (Should it be the default going forward? If so, what's the guidance for folks wanting the existing widget.) (`ModelAdmin.formfield_overrides` I suppose… 🤔)

**Comment by Shubh1815** [comment]
Thanks for reviewing the PR @carltongibson. I'll add test and release notes for the new widget.

> it doesn't look like you've used [the suggested `Intl` API from the discussion](https://groups.google.com/g/django-developers/c/ti1wh0S_gLc) — was there a reason for that?

`DateTimeShortcuts.timezoneOffset` stores the offset between server and user's timezone. So, I thought we can use that to convert the time from one timezone to another. I thought this would be a simpler approach than using the `Intl` API.

**Comment by felixxm** [comment]
@Shubh1815 Do you have time to keep working on this?

**Comment by felixxm** [comment]
Closing due to inactivity.

**Comment by ldeluigi** [comment]
New attempt: #15806

**Pull request closed without merging**
