### PR TITLE
Fixes #32076 -- Add async cache methods to Base, Dummy, and LocMem Cache

### PR DESCRIPTION
**Pull request by Andrew-Chen-Wang**
[ticket-32076](https://code.djangoproject.com/ticket/32076)

* Based on DEP 0009 and the implementation found [here](https://github.com/Andrew-Chen-Wang/django-async-redis)
* Copied all doc strings from the synchronous methods
* Adds async cache methods to BaseCache and DummyCache.

Issues I currently see are:

1. The request finished signal being unable to properly close all cache connections (more details in original ticket). This can be found in `django.core.cache` (init file).
2. This has been implemented as per DEP 0009 ~~Lots of times in several areas in Django, the cache is called by doing `if "string" in cache`. The async method cannot handle the magic method `__contains__` unless you use `sync_to_async`. I dislike context switching, so I would rather not touch that, but I can see why people would want to "accidentally" use it, even if in the documentation we mention it will not be performant and people should strive to use `await cache.has_key("string")` instead.~~
3. Current session backend is not handling the async methods. @felixxm Made a good point about being a partial solution and why BaseCache may not be good enough for this implementation; I'm currently writing a session backend for my websocket implementation [found here](https://github.com/pydanny/cookiecutter-django/blob/88b841715623d94bb709aaf1a9722b8a135a2de2/%7B%7Bcookiecutter.project_slug%7D%7D/config/websocket.py) (I'll be moving the code to a separate repository soon to demonstrate the functionality). The issue I immediately ran into was logging in since I wanted to see how I can validate the session for that custom websocket script. If we went with what @felixxm said, then the async methods in BaseCache would look like:

```
async def get_async(value):
    return sync_to_async(self.get(value))
```

The issue I see with that is if a library accidentally doesn't implement the get_async() method, then the error will say that the `get` method is not created when it should really say the dev needs to create the `get_async` method.
4. I'm not going to have time to write documentation (Edit rephrased: I'm terrible at documentation and heavily discouraged). 
5. I've added LocMem to this PR. The only change is that we're adding asyncio.Lock for async context. I think I can rework this to take advantage of the RunTimeError so we know which context we're in. That means we don't need to create two different locks. ~~If you'd like, I can add my setup for LocMem backend. I'm not too sure about the tests though. As I was copying and pasting all those test cases, my computer started burning up...~~

### CODE REVIEW

**Comment by Andrew-Chen-Wang** [comment]
So as I'm implementing LocMem (I think I want to add this in a different ticket), I'm writing the async test cases right next to their synchronous versions. An issue arising is if the currently tested backend doesn't have the `_async` ending, which would support the point that we should use the sync_to_async by default.

Let me know if LocMem should be implemented in this ticket or in a separate ticket btw.

**Comment by Andrew-Chen-Wang** [comment]
Oh yeah... need to support python 3.6/7....

**Comment by Andrew-Chen-Wang** [comment]
Sigh... one Python version, one memcached library... I'm not even sure how to fix this one...

**Comment by felixxm** [comment]
Please don't change a scope of accepted tickets, see [comment](https://code.djangoproject.com/ticket/32076#comment:10).

**Comment by Andrew-Chen-Wang** [comment]
New PR instead of reverting

**Comment by ckcollab** [comment]
new PR here -> https://github.com/django/django/pull/13547

**Pull request closed without merging**
