### PR TITLE
Fixed #24499 -- Dropped support for PostGIS 1.5.

### PR DESCRIPTION
**Pull request by timgraham**
https://code.djangoproject.com/ticket/24499#ticket

### CODE REVIEW

**Comment by timgraham** [comment]
Postponed to Django 2.0 per Claude's request.

**Comment by timgraham** [comment]
@claudep, are you okay to proceed with this? If so, could you review?

**Comment by claudep** [comment]
Tim, the patch looks good. My only reluctance currently is very selfish! My main dev system is still on Debian stable where 1.5 is the installed Postgis version. The next stable is not far away, but meanwhile I would be unable to work on GIS, unless I setup external repositories or docker-style configs (as I need to keep 1.5 to match some production installs).

**Comment by timgraham** [comment]
As you are the main contributor to GIS these days, that's a good reason for me. I'll see if I can use this as motivation to put something together with docker based on our Jenkins playbooks to ease testing.

**Comment by claudep** [comment]
Feel free to rebase and commit this at your convenience.

**Pull request merged**
