### PR TITLE
Fixed #25059 - validate punycoded TLDs in URLValidator

### PR DESCRIPTION
**Pull request by alexey-sveshnikov**

### CODE REVIEW

**Comment by dbrgn** [comment]
Oh wow, TLDs can contain punycode?

Looks good to me. Is there a reference somewhere on valid TLDs?

**Comment by alexey-sveshnikov** [comment]
Surprise! :)

Here you can found a list: https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains#Internationalized_country_code_top-level_domains.

**Comment by shaib** [comment]
This allows much more than punycode; it allows TLDs such as "i-am-a-tld"; I am not sure if there are any rules for this, but I've yet to see a TLD that contains a dash (other than punycode).

The expression had already supported internationalized TLDs (in unicode form); punycode would be something like `r"xn--[a-z0-9]+"`, wouldn't it?

**Comment by alexey-sveshnikov** [comment]
Yes we could do this regexp more specific.

(I did git push -f)

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
LGTM. Shai?

**Comment by shaib** [comment]
Yeah, looks ok. Do the tests pass?

**Comment by timgraham** [comment]
merged in bc98bc56a52860688ea0ae2ec7b9e59ddb72a811, thanks!

**Comment by timgraham** [comment]
Referencing Shai's comment about "i-am-a-tld" -- someone has requested that we allow it: https://github.com/django/django/pull/6123. I'm not sure if we should also allow other dashes in the punycode portion also? e.g. `xn--foo-bar`?

**Pull request closed without merging**
