### PR TITLE
Fixed #32904 -- Made parse_time() more strict.

### PR DESCRIPTION
**Pull request by abhiabhi94**
Thanks Keryn Knight for the report.

### CODE REVIEW

**Comment by felixxm** [comment]
@abhiabhi94 Thanks :+1: I added 3 more assertions.

**Comment by abhiabhi94** [comment]
Thanks, @felixxm. You may as well point me in the direction of any changes that you may want. I will try to make those changes by myself so that you don't potentially spend time on having to do any extra work in future on the patches.

**Comment by abhiabhi94** [comment]
Also, for what it is worth, I think we may use `subTest` here when checking for different values v/s writing the same function call again.

**Comment by felixxm** [comment]
> Also, for what it is worth, I think we may use `subTest` here when checking for different values v/s writing the same function call again.

This is a separate cleanup, addressed in #14415.

**Comment by pope1ni** [comment]
> This is a separate cleanup, addressed in #14415 (at least partly).

I'll rebase that tonight and see if anything else needs addressing there.

**Pull request merged**
