### PR TITLE
Fixed #35754 -- Mapped full-width characters in latex to half-width.

### PR DESCRIPTION
**Pull request by khanxmetu**
#### Trac ticket number

ticket-35754

#### Branch description
Prior to the proposed change, pdf documentation builds rendered curly quotes as full-width due to an issue in `ctex` latex package: https://github.com/CTeX-org/ctex-kit/issues/389. Relevant mappings are added to convert full-width characters to half-width.

#### Checklist
- [x] This PR targets the `main` branch. 
- [x] The commit message is written in past tense, mentions the ticket number, and ends with a period.
- [x] I have checked the "Has patch" ticket flag in the Trac system.
- [ ] I have added or updated relevant tests.
- [ ] I have added or updated relevant docs, including release notes if applicable.
- [ ] I have attached screenshots in both light and dark modes for any UI changes.

### CODE REVIEW

**Comment by khanxmetu** [comment]
I've gone through the contribution checklist, but I'm not entirely sure if this should be considered for backport. What do you think?

**Comment by sarahboyce** [comment]
> I've gone through the contribution checklist, but I'm not entirely sure if this should be considered for backport. What do you think?

We sometimes backport Documentation fixes to the latest stable branch but the merger will decide if this qualifies.
How can I run this locally to generate the pdf of the docs?

**Comment by khanxmetu** [comment]
> How can I run this locally to generate the pdf of the docs?
```bash
cd docs
make latexpdf
ls _build/latex/django.pdf
```

**Comment by pauloxnet** [comment]
> > Where can we see a PDF generated with the fix?
> 
> Here is one from my local build: [django.pdf](https://github.com/user-attachments/files/16993704/django.pdf)

Thanks. The bug seems fixed also opening with my PDF reader in Linux.

**Review by pauloxnet — APPROVED** [review]

**Comment by sarahboyce** [comment]
> > How can I run this locally to generate the pdf of the docs?
> 
> ```shell
> cd docs
> pip install -r requirements.txt
> make latexpdf
> ls _build/latex/django.pdf
> ```
> 
> Note: You may also want to install latex engine related dependencies mainly: texlive and fonts-symbola.
> 
> Edit: Added external dependency notes.

Thank you I was struggling with the dependencies :star:

**Review by sarahboyce — APPROVED** [review]
Welcome onboard @khanxmetu :star:

**Pull request merged**
