### PR TITLE
Fixed #34059 -- Fixed CheckConstraint validation with JSONField key transforms.

### PR DESCRIPTION
**Pull request by shangxiao**
[#34059](https://code.djangoproject.com/ticket/34059)

### CODE REVIEW

**Comment by shangxiao** [comment]
@felixxm as I mentioned on irc this patch only casts postgres as mariadb doesn't support casting to json.

There's also the issue of implementing `get_placeholder()` then short-circuits `Value.as_sql()` which has some NULL-forcing logic (plus any other logic that may be added in the future).

I wonder if @charettes might have any valuable input here? 🙂

One thing I was curious about is whether casting values for check constraints will unnecessarily pollute other queries that don't need it as the db would be inferring the type from the table.

It might be worth pointing out that Simon and I were chatting via email about the possibility of creating an `class CheckCompiler(SQLCompiler)` that could deal with these specific issues. I did create one to deal with Oracle & NULLs and had sort of got it working.

**Comment by felixxm** [comment]
`CheckConstraint`s on `JSONField`s have many caveats (as `JSONField` itself), maybe we should ignore them in `CheckConstraints.validate()` as constraints with `RawSQL` and treat this as a new feature for Django 4.2+ :thinking: After all, they should be rather rare.

**Comment by shangxiao** [comment]
@charettes just also FYI when I was writing tests for this I found this interesting error:

```
constraint.validate(Product, Product(data=Value('null'))) 
```

results in:

```
Traceback (most recent call last):
  File "~/projects/django/tests/constraints/tests.py", line 261, in test_validate_json_not_null
    constraint.validate(Product, Product(data=models.Value("null")))
  File "~/projects/django/django/db/models/constraints.py", line 92, in validate
    if not Q(self.check).check(against, using=using):
  File "~/projects/django/django/db/models/query_utils.py", line 136, in check
    return compiler.execute_sql(SINGLE) is not None
  File "~/projects/django/django/db/models/sql/compiler.py", line 1491, in execute_sql
    sql, params = self.as_sql()
  File "~/projects/django/django/db/models/sql/compiler.py", line 730, in as_sql
    self.compile(self.where) if self.where is not None else ("", [])
  File "~/projects/django/django/db/models/sql/compiler.py", line 517, in compile
    sql, params = node.as_sql(self, self.connection)
  File "~/projects/django/django/db/models/sql/where.py", line 145, in as_sql
    sql, params = compiler.compile(child)
  File "~/projects/django/django/db/models/sql/compiler.py", line 517, in compile
    sql, params = node.as_sql(self, self.connection)
  File "~/projects/django/django/db/models/lookups.py", line 354, in as_sql
    lhs_sql, params = self.process_lhs(compiler, connection)
  File "~/projects/django/django/db/models/lookups.py", line 214, in process_lhs
    lhs_sql, params = super().process_lhs(compiler, connection, lhs)
  File "~/projects/django/django/db/models/lookups.py", line 102, in process_lhs
    sql, params = compiler.compile(lhs)
  File "~/projects/django/django/db/models/sql/compiler.py", line 515, in compile
    sql, params = vendor_impl(self, self.connection)
  File "~/projects/django/django/db/models/expressions.py", line 28, in as_sqlite
    sql, params = self.as_sql(compiler, connection, **extra_context)
  File "~/projects/django/django/db/models/expressions.py", line 944, in as_sql
    arg_sql, arg_params = compiler.compile(arg)
  File "~/projects/django/django/db/models/sql/compiler.py", line 517, in compile
    sql, params = node.as_sql(self, self.connection)
  File "~/projects/django/django/db/models/sql/where.py", line 145, in as_sql
    sql, params = compiler.compile(child)
  File "~/projects/django/django/db/models/sql/compiler.py", line 517, in compile
    sql, params = node.as_sql(self, self.connection)
  File "~/projects/django/django/db/models/sql/where.py", line 145, in as_sql
    sql, params = compiler.compile(child)
  File "~/projects/django/django/db/models/sql/compiler.py", line 517, in compile
    sql, params = node.as_sql(self, self.connection)
  File "~/projects/django/django/db/models/lookups.py", line 357, in as_sql
    return super().as_sql(compiler, connection)
  File "~/projects/django/django/db/models/lookups.py", line 224, in as_sql
    lhs_sql, params = self.process_lhs(compiler, connection)
  File "~/projects/django/django/db/models/lookups.py", line 214, in process_lhs
    lhs_sql, params = super().process_lhs(compiler, connection, lhs)
  File "~/projects/django/django/db/models/lookups.py", line 102, in process_lhs
    sql, params = compiler.compile(lhs)
  File "~/projects/django/django/db/models/sql/compiler.py", line 515, in compile
    sql, params = vendor_impl(self, self.connection)
  File "~/projects/django/django/db/models/expressions.py", line 28, in as_sqlite
    sql, params = self.as_sql(compiler, connection, **extra_context)
  File "~/projects/django/django/db/models/expressions.py", line 1005, in as_sql
    val = output_field.get_db_prep_value(val, connection=connection)
  File "~/projects/django/django/db/models/fields/__init__.py", line 919, in get_db_prep_value
    value = self.get_prep_value(value)
  File "~/projects/django/django/db/models/fields/json.py", line 101, in get_prep_value
    return json.dumps(value, cls=self.encoder)
  File "~/.pyenv/versions/3.10.4/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "~/.pyenv/versions/3.10.4/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "~/.pyenv/versions/3.10.4/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "~/.pyenv/versions/3.10.4/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Value is not JSON serializable
```

**Comment by charettes** [comment]
> There's also the issue of implementing get_placeholder() then short-circuits Value.as_sql() which has some NULL-forcing logic (plus any other logic that may be added in the future).

Do you have more context on the subject?

> just also FYI when I was writing tests for this I found this interesting error:

This is somewhat expected, you are passing a raw SQL literal to `Value` which is not adequate, `Value` should really have been named `Literal`. If Python had a `JSONLiteral` type I guess we could make `Value(JSONLiteral.null)` or `Value(JSONLiteral("nulll"))` work but .

There might be an issue in `JSONField.get_prep_value` to skip dealing with expressions but even if that was working I wouldn't expect `Value("null")` to work.

**Comment by charettes** [comment]
> oh yep I meant that Value.as_sql() [returns early](https://github.com/django/django/blob/10bb21e71e3668f770493e2af0d0e0271830f7a3/django/db/models/expressions.py#L1007) if theres a get_placeholder()

Right if there is an `output_field` specified which defaults to `CharField` if a string is provided as that's a string literal. I assume things work as expected if `output_field=JSONField()` is specified.

> ... based on the [docs](https://docs.djangoproject.com/en/4.1/topics/db/queries/#storing-and-querying-for-none).

Oh well, I didn't know about that. How is one supposed to store and query for `"null"` then? (e.g. `{"foo": "null"}`). That makes `filter(field__foo="null")` and `field__foo=Value("null")` asymmetric doesn't it?

**Comment by shangxiao** [comment]
> Right if there is an `output_field` specified which defaults to `CharField` if a string is provided as that's a string literal. I assume things work as expected if `output_field=JSONField()` is specified?

`output_field=JSONField()` is already being set correctly… I was mostly just wondering if returning early would cause issues. (it could potentially for Oracle if this patch was to naively cast for all backends)

> Oh well, I didn't know about that. How is one supposed to store and query for string `"null"` then? (e.g. `{"foo": "null"}`). That makes `filter(field__foo="null")` and `field__foo=Value("null")` asymmetric doesn't it?

heh yeah I suppose it would be (I also didn't realise this was a feature). It's a bit weird, I personally wouldn't have opted to overload `Value` like that but perhaps there was a good reason for it 🙂

**Comment by felixxm** [comment]
I don't think that I would feel comfortable merging this or #16137 to the stable 4.1 branch. We are already aware of subsequent issues with constraints validation that contain `JSONField` and its different transforms/lookups e.g. handling SQL `NULL` and `JSON` scalar `null`, `__isnull` lookup, etc. Therefore, any solution that is acceptable for backporting would be only partial. It can be difficult for users to distinguish what is and what is not supported :disappointed: 

IMO, we should take a step back and ignore all `CheckConstraint`s on `JSONField`s in `validate_constraints()` and treat this as a new feature for Django 4.2+. What do you think? (\cc @charettes @carltongibson @shangxiao)

**Comment by shangxiao** [comment]
@felixxm Yeah agreed plus I'm not 100% into the patch here. If we look into furthering a check compiler I guess it could be possible to do things more specifically like casting _all_ literals and deal with JSON issues (depending on the problems & solutions)?

**Comment by carltongibson** [comment]
> IMO, we should take a step back and ignore all CheckConstraints on JSONFields in validate_constraints() and treat this as a new feature for Django 4.2+.

I think that's sensible. 👍

**Comment by charettes** [comment]
I think it makes sense to defer to 4.2 which will be supported for a longer time anyway.

**Comment by felixxm** [comment]
I've prepared docs changes #16169, suggestions are welcome (as always).

**Comment by felixxm** [comment]
This was fixed in 0d8fbe2ade29f1b7bd9e6ba7a0281f5478603a43.

**Pull request closed without merging**
