### PR TITLE
Fixed #25550 -- Deprecated direct assignment to the reverse side of a related set.

### PR DESCRIPTION
**Pull request by timgraham**
https://code.djangoproject.com/ticket/25550

### CODE REVIEW

**Comment by charettes** [comment]
FWIW I think this makes a lot of sense. I had a hard time in the past trying to explain to beginners why this kind of assignment was special.

If we were to deprecate this it would also pave the way for an API to attach related objects to an instance and call `.set()` on instance `.save()`. The `ModelForm` `save_m2m()` logic comes to mind as an ugly workaround for this limitation. If I remember correctly DRF also does a lot of stuff to circumvent the fact it cannot attach m2m objects on non existing model instance.

**Comment by collinanderson** [comment]
Idea: Could we first create set() and warn about assignment behavior change, then change assignment to delay saving until save() is called?

**Comment by timgraham** [comment]
The `set()` method already exists. The reason for the immediate save is because the fields to be updated are on the related instances, not the model to which the assignment happens. I don't think `model.save()` updating fields on other models is a good idea. This doesn't happen on reverse assignment on one-to-one, for example -- you still need to save the model that actually contains the database column affected by the reverse relation. Did I miss the point of your suggestion?

**Comment by timgraham** [comment]
This is ready for review.

**Comment by akaariai** [comment]
The patch looks good to me. I hope there are that many users relying on direct assignment to m2m, so that we don't cause unnecessarily large update problems.

The only question I have is should we have some form of assigning data to m2m relation without saving it? Probably not, but I thought to mention it here anyways. The use case would be something like a rest serializer building an object graph without saving anything yet. Then you could alter the object graph, and finally save it manually. As said, likely not a concern for this patch.

**Comment by charettes** [comment]
@akaariai I agree that such an API could be useful, that's what I meant with my first comment.

**Pull request merged**
