### PR TITLE
Fixed #32130 -- Fixed pre-Django 3.1 password reset tokens validation.

### PR DESCRIPTION
**Pull request by felixxm**
ticket-32130

Thanks Gordon Wrigley for the report and implementation idea.

Regression in 226ebb17290b604ef29e82fb5c1fbac3594ac163.

### CODE REVIEW

**Comment by felixxm** [comment]
@tolomea Can you take a look?

**Review by carltongibson — APPROVED** [review]
That looks pretty neat.

Will wait for comment from @tolomea.

Thanks both!

**Comment by tolomea** [comment]
It looks good to me. Although it did take me a couple of seconds to work through how the addition squares up with "round to midnight".

**Comment by felixxm** [comment]
@tolomea Thanks for checking :+1: 
>... me a couple of seconds to work through how the addition squares up with "round to midnight".

Yes, I wanted to restore [the previous behavior](https://github.com/django/django/commit/226ebb17290b604ef29e82fb5c1fbac3594ac163#diff-b93dda4cd6422ff34822c0dcb5f4d89f4c9634093c4220f9acd267535b007be4L44-L48) for old tokens.

**Pull request merged**
