### PR TITLE
Registered psycopg2.extensions.UNICODE only on Python 2

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
@timgraham Do you think this is something we could commit "as is"?

**Comment by timgraham** [comment]
I don't know the reason for the change.

**Comment by claudep** [comment]
Simply because those lines aren't needed on Python 3.
http://initd.org/psycopg/docs/usage.html#unicode-handling

**Comment by timgraham** [comment]
Okay, maybe a commit message like "Removed unnecessary registration of psycopg2 unicode extensions on Python 3" would clarify that.

**Pull request closed without merging**
