### PR TITLE
Fixed #27244 -- Corrected thousand separator for the Greek locale

### PR DESCRIPTION
**Pull request by kappataumu**
Direct link to ticket: https://code.djangoproject.com/ticket/27244. Pinging @spapas @pmav99 for a +1.

### CODE REVIEW

**Comment by timgraham** [comment]
A space is used by https://en.wikipedia.org/wiki/Decimal_mark#Examples_of_use.

**Comment by kappataumu** [comment]
Wikipedia is not a useful resource in this case. 

You'll note that for several countries, in the third row of that table, the thousand separator is a space, while on the fifth row of the table, these same countries are shown using a dot. This is the case for Germany and Italy too, besides Greece. 

If you look in the Django `formats.py` file for the above languages, you'll note that in both the [Italian](https://github.com/django/django/blob/master/django/conf/locale/it/formats.py) and the [German](https://github.com/django/django/blob/master/django/conf/locale/de/formats.py) one, the thousand separator is a dot (in contrast to row 3 of the Wikipedia page, to which you are refering). Greece, like Germany and Italy uses a dot as well.

Hopefully this shows why the given link is not relevant to this discussion.

Furthermore, the code I included in my ticket demonstrates concretely what the correct thousand separator for the Greek locale is. You can run this on any *nix to verify. I'm copying here as well:

```
import locale
locale.setlocale(locale.LC_ALL, "el_GR.UTF-8")
print(locale.nl_langinfo(locale.THOUSEP))
```

For people that use Windows, the locale settings for every country and region can be easily viewed from the GUI as well by navigating to Control Panel > Clock, Language, and Region > Change date, time or number formats > Selecting Greek (Greece) from the dropdown and clicking on "Additional Settings...".

For convenience, I am including a screenshot here (excuse the high contrast theme):

image

Hopefully this clears things up a bit!

**Comment by spapas** [comment]
Hello, I think that both ways to write the thousand separator (using a dot or a space) are valid. I think that in school we were mostly using the dot-thousand separator but at my university most books (silently) switched to the space-thousand separator.

For me, using a space (instead of a dot) as the thousand separator is preferable because when you use the dot as a thousand separator and see a number written as "1.234" you may confuse it to the fractional 1234/1000 instead of the integer 1234. If you instead see "1 234" you'll know immediately what is it. Unfortunately we live in an international environment and it's very common to have such situations. The behavior of windows you describe has bitten me many times with CSVs containing fractional, US numbers (with dots for the fractional part) that Excel recognises as integers 👎 

Also about your argument about EU countries using the dot, France is actually using a space (https://github.com/django/django/blob/master/django/conf/locale/fr/formats.py -- IIRC I copied the formats.py from France for the greek locales).

**Comment by kappataumu** [comment]
The thousand separator for the Greek locale is a dot across at least Linux and Windows and I gave a way for users of both operating systems to verify this. This is consistent with industry use as well, namely all banks, the Greek IRS, bills, price listings in online and offline shops, literally everywhere.

Screenshots and links can be provided.

@spapas, I understand that not using a dot is a personal preference of yours, and this is exactly why Django offers a way to override format localization on a per-project setting.

**Comment by spapas** [comment]
This is not a personal preference -- both representations (dot or space) are valid in most European countries  including Greece. If you want I can scan  (or refer to you) books that use either the space or the dot representation!

I just think that Django should default to the *best* of these two (space being better than dot is a personal opinion and I've explained above the reason).

**Comment by kappataumu** [comment]
I understand your point and thanks for taking the time to make it. I hope I'm not coming across as accusing you of being *at fault* or anything. 

Since we are having this discussion, could you confirm my point, for the non-Greek audience here, that the thousand separator commonly seen in Greece, across the industry, in government use and as found in newspapers and other material, is in fact a dot?

I think this would move the discussion forward.

**Pull request merged**
