### PR TITLE
Fixed #27635 -- Used secrets module in django.utils.crypto.

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot

**Comment by felixxm** [comment]
@claudep Thanks for this patch :+1: Maybe we should use `secrets` instead of `random` also in `django/template/defaultfilters.py` and `django/utils/lorem_ipsum.py`. What do you think?

**Comment by claudep** [comment]
See https://github.com/django/django/pull/7756#issuecomment-269544852 about using `secrets` in other modules. I also think it should be reserved to security-sensible domains.

**Comment by claudep** [comment]
Do we know if we have to keep this branch at all?

**Comment by charettes** [comment]
@claudep [it's documented as not available on all systems](https://docs.python.org/3/library/random.html?highlight=systemrandom#random.SystemRandom) so it's possibly still required.

An interesting note though is that `SystemRandom.seed()` is available but has no effect so we could at least remove the `using_sysrandom=False` branch to get code coverage there.

**Comment by claudep** [comment]
I'm not sure to follow. Feel free to take over the patch.

**Comment by charettes** [comment]
@claudep in short it looks like `secrets.SystemRandom` won't be available on all system as it's mainly an alias for `random.SystemRandom`. If this patch was reduced to only swapping line 14 by keeping the `random` assignment it should be good to go.

**Comment by pope1ni** [comment]
So I think that the fallback should be removed for the following reasons:
1. There are no tests covering this as shown in the [coverage report](https://djangoci.com/view/%C2%ADCoverage/job/django-coverage/HTML_20Coverage_20Report/).
2. The [commit](https://github.com/django/django/commit/1525874238fd705ec17a066291935a9316bd3044) that introduced the fallback makes no reference to a ticket and added no tests.
3. It doesn't look as though the exception is triggered there because:
   - Other standard library modules instantiate `random.SystemRandom()` and don't bother catching the exception, but I can't imagine that these modules cannot be imported because `NotImplementedError` would be raised, e.g. [crypt](https://github.com/python/cpython/blob/e42b705188271da108de42b55d9344642170aa2b/Lib/crypt.py#L10), [secrets](https://github.com/python/cpython/blob/e42b705188271da108de42b55d9344642170aa2b/Lib/secrets.py#L22).
   - Our check for `random.SystemRandom()` is therefore insufficient as shown when compared to [this](https://github.com/python/cpython/blob/964663089547ca110199e23867b46b07ff4be88c/Lib/test/test_random.py#L283-L288) in cpython's tests.
4. Given the above, have we ever received a bug report that things break because the fallback would never have triggered?
5. Do we want to make this work? Given it never worked, can we guarantee it does the right thing?

See my incoming alternate pull request...

**Comment by claudep** [comment]
I like the approach Nick took in his patch.

**Pull request closed without merging**
