### PR TITLE
Fixed #26134 -- Updated MySQL GIS function names to OpenGIS standard

### PR DESCRIPTION
**Pull request by fmalina**
https://code.djangoproject.com/ticket/26134

Fix deprecation warnings such as:
    .../django/db/backends/mysql/base.py:112:
    Warning: 'GEOMFROMTEXT' is deprecated and will be removed in a future release.
    Please use ST_GEOMFROMTEXT instead

### CODE REVIEW

**Comment by timgraham** [comment]
Are all the new names available in MySQL 5.5 (minimum supported version for Django 1.10)?

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by fmalina** [comment]
The GIS aliases exist from 5.6. GIS features can be either exception from the minimum supported MySQL version or increase this to 5.6 (5.5 GA was released end of 2010). MySQL GIS users should be encouraged to use MySQL 5.7 > as there are spatial indexes available for InnoDB.

For reference docs updates would be needed here:
https://docs.djangoproject.com/en/1.9/ref/contrib/gis/install/#installation
and here:
https://docs.djangoproject.com/en/1.9/ref/databases/#mysql-notes

**Comment by timgraham** [comment]
Thanks, have left a comment on the ticket.

**Comment by timgraham** [comment]
I guess we'll close this for now as fmalina indicated he doesn't want to work on an approach that maintains support for MySQL 5.5.

**Pull request closed without merging**
