### PR TITLE
Updated the python shell example to python 3.4.3 in the simple install guide.

### PR DESCRIPTION
**Pull request by KamranMackey**

### CODE REVIEW

**Comment by timgraham** [comment]
It might be nice to use generic version numbers like A.B.C so we're not having to continually update this. Thoughts on that?

**Comment by KamranMackey** [comment]
Sure thing, @timgraham. :)

**Comment by KamranMackey** [comment]
How does that look, @timgraham?

**Comment by timgraham** [comment]
merged in 4c2197db32deaea2f0c3d04c2c36bb7df6a2e06c, thanks.

**Comment by KamranMackey** [comment]
No problem, @timgraham.

**Pull request closed without merging**
