### PR TITLE
#25633: Updated Spatialite installation instructions for MacOS

### PR DESCRIPTION
**Pull request by dhepper**
Using the latest available version from KyngChaos, as Gaia-SINS does not provide MacOS binaries anymore.

### CODE REVIEW

**Comment by rixx** [comment]
We could consider adding a checksum check in these instructions – as far as I can see, this is the only place in the docs where we encourage the download of third-party software and sudo-moving it to be executed, so including something like a ``sha256`` check or similar might be a good idea.

**Comment by dhepper** [comment]
The docs already have instructions to [install packages from kyngchaos.com](https://docs.djangoproject.com/en/2.2/ref/contrib/gis/install/#kyngchaos-packages). 

These docs currently say:

> William Kyngesburye provides a number of geospatial library binary packages that make it simple to get GeoDjango installed on macOS without compiling them from source. 

That leaves it up to the reader to decide if they want to trust the packages. They come with an installation routine, but they are not signed.

I'd argue that the Spatialite Tools package carries the same level of trust and just lacks a comfortable installation routine. IMHO, adding a hash that we calculated would signal that the Django docs consider this specific version of the package to be trustworthy.

I have not verified the package myself, so I personally would not feel comfortable making that call. I don't want to put that burden on anyone else either, so I'm -1 on providing a hash.

**Comment by rixx** [comment]
Agreed, thank you for explaining your reasoning.

**Comment by rixx** [comment]
Apart from the commit message formatting (I think you want "Fixed #25633 -- Updated GeoDjango KyngChaos installation instructions" or something like that) this looks good to go.

**Pull request merged**
