### PR TITLE
adding wrap to url

### PR DESCRIPTION
**Pull request by vorujack**
added wrap to urls.
usage : 
url(r'^$', include('suburl'), wrap=[wrap1, wrap2])

### CODE REVIEW

**Comment by vorujack** [comment]
whats the test my code fails?

**Comment by timgraham** [comment]
This is being discussed at https://code.djangoproject.com/ticket/25409. We need to make a design decision about this first before writing code. Feel free to add your thoughts to the ticket and/or mailing list discussion. Thanks!

**Comment by danihodovic** [comment]
@timgraham was a conclusion ever reached on this feature?

**Comment by timgraham** [comment]
No, there's no activity on the ticket since 3 years ago.

**Pull request closed without merging**
