### PR TITLE
[WIP] Fixed #27426 -- Allowed customizing the test Client's request factory.

### PR DESCRIPTION
**Pull request by ana-balica**
Allow injecting a different request factory to be used by the test
client. Hence refactor the Client to no longer inherit directly
from the RequestFactory.

### CODE REVIEW

**Comment by charettes** [comment]
Making sure this doesn't break [DRF's custom test clients](https://github.com/tomchristie/django-rest-framework/blob/d55e176a1e882d498b63b46a01f0ac389428f084/rest_framework/test.py) would be good sanity check for backward compatibility.

**Comment by timgraham** [comment]
I think we also lost `defaults` and `errors` attributes from inheritance, for example. Unknown if it's important or if anyone is relying on it.

**Comment by ana-balica** [comment]
It breaks DRF custom test client. Not sure what is the way forward in those cases: create 2 types of clients and later deprecate the former one?

`defaults` and `errors` could be added back via properties to not break other people's code.

**Comment by carljm** [comment]
The implementation relies on `Client` overriding the `request` method from `RequestFactory`, which this PR breaks. So all the methods doing `response = self.factory.whatever(...)` will not get back a response, just a request, because that's what `RequestFactory.request` does, and `Client.request` (which passes the request to the handler to get back a response) will never be called. So we need to get the stuff done in `Client.request` back into the codepath somehow.

I don't think this PR (once fixed) breaks any documented API, so even if it does break the DRF custom client, I think that's because they are taking advantage of undocumented facts about the current inheritance tree. Also I don't think it would be too hard for them to work around this change in a way that could support both earlier and later versions of Django.

**Comment by ana-balica** [comment]
First attempt at making it work.
With the current refactor the API is more flexible, but looks ugly. To create a custom RequestFactory, the developer should implement the following interface:

```python
class CustomRequestFactory(object):
    def __init__(self, **defaults):
        self.defaults = defaults
        self.cookies = SimpleCookie()
        self.errors = BytesIO()

    def _base_environ(self, **request):
        pass

    @property
    def extra_environ(self):
        pass

    # GET and all the other HTTP methods
    def get(self, path, data=None, secure=False, **extra):
        pass
```

One method looks private (`_base_environ`), the other one isn't clear (`extra_environ`). Meh :/

Also it's super nasty to rely on the internal state of the factory. Call to `get` will set the `extra_environ` property, which is a hidden trick.

```python
self.factory.get(path, data=data, secure=secure, **extra)
response = self.request(**self.factory.extra_environ)
```

One better way is to do:
```python
request = self.factory.get(path, data=data, secure=secure, **extra)
response = self.request(request)  # or self.get_response(request)
```

I'll keep on trying things. All thoughts are very welcome!

**Comment by carljm** [comment]
Ok, I can think of one approach here that might be nice enough to consider: we could introduce a new `EnvironFactory` whose methods return raw WSGI environ dicts, and then `RequestFactory` could wrap an `EnvironFactory` to wrap the environs returned by all its methods in `WSGIRequest` classes. And then `Client` would actually take an `EnvironFactory`, not a `RequestFactory`.

But I am still not convinced that we should move forward with this change. The benefits are theoretical (AFAIK they are not driven by any real-world need to customize the request-factory for a test client), and even if it would be better code architecture, we have to balance real-world utility of the change against the cost of breaking existing code. I don't think the cost-benefit analysis stacks up, unfortunately.

**Comment by timgraham** [comment]
That's my feeling as well  with regards to purity vs. possibility of breaking other people's code.

**Comment by ana-balica** [comment]
Probably the only real world example is DRF's [RequestFactory](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/test.py#L142) that has a more flexible way of encoding data. Nevertheless I agree that'll break other people's code if trying to do it properly.

Thanks for you in input folks! Learned a lot. Invaliding.

**Pull request closed without merging**
