### PR TITLE
WIP/RFC: refactor/revisit tests/runtests

### PR DESCRIPTION
**Pull request by blueyed**
This is required/useful to use with other test runners then, e.g.
pytest.

### CODE REVIEW

**Comment by pope1ni** [comment]
I'm closing this as it is stale, a work in progress, and there is not really much detail on what it solves.

Please create a ticket detailing the problem being addressed in more detail if you wish to pick this up again.

**Comment by blueyed** [comment]
@pope1ni 
Fair enough, thanks for cleaning up things.
However, there is some reasoning in the commit message already - IIRC this came out of me trying to use pytest with Django's testsuite.

**Comment by pope1ni** [comment]
Thanks @blueyed. I noticed the references to `pytest`. I presume that you're referring to using it as the test runner for Django's test suite rather than for the tests for a project using Django.

My thinking was that the details I've asked for would include the explaining how the tests would be invoked using `pytest` and what each of the required changes are to make the current code compatible.

**Comment by smithdc1** [comment]
https://code.djangoproject.com/ticket/30415

I _think_ it was related this ticket which was closed as 'needsinfo'.

**Comment by blueyed** [comment]
@smithdc1 yes, thanks for linking.
@pope1ni yes, it is meant for using other test runners, specifically pytest here.

This was apparently from when I've started to look into making pytest more compliant to Python's unittest etc, but has stalled since then.
I might come back to it after all, but likely not in the near future.

AFAICT it would still make sense to have this as a (refactoring) step, but apparently needs some review of the ticket and PR, which even myself am not into anymore currently.
Therefore I'm still fine with it being closed for now.
Thanks again for everything.

**Pull request closed without merging**
