### PR TITLE
Fixed #22603 -- Organized django.db.backends classes

### PR DESCRIPTION
**Pull request by timgraham**
Not sure if `DatabaseWrapper` classes should remain in `base.py` or if it's more clear to have them in a new `wrapper.py` file as I've done. Some `base.py`'s have version checking logic so it seemed a bit cleaner to have the wrapper separated from that, and also every other `DatabaseFoo` class is in `foo.py`.

### CODE REVIEW

**Comment by claudep** [comment]
As for me I think that the wrapper classes belongs to base, but if you really feel it's cleaner the way you choose, then go ahead. Or maybe ask another dev.

**Comment by manfre** [comment]
My vote is for  `DatabaseWrapper` should to remain in `base.py`.

**Comment by timgraham** [comment]
Fine with me. Does `BaseDatabaseWrapper` belong in `db.backends.base.base.py` or `db.backends.base.__init__.py`)?

**Comment by timgraham** [comment]
To answer my last question, I've left `BaseDatabaseWrapper` in `base.base`.

Currently I've left import aliases for the base classes for backwards compatibility:

`django.db.backends`:
* `BaseDatabaseClient`
* `BaseDatabaseFeatures`
* `BaseDatabaseIntrospection`
* `BaseDatabaseOperations`
* `BaseDatabaseValidation`
* `BaseDatabaseWrapper, FieldInfo, NO_DB_ALIAS, TableInfo`

`django.db.backends.schema`:
* `BaseDatabaseSchemaEditor`

`django.db.backends.creation`:
* `BaseDatabaseCreation`

It would be more consistent if we removed them and imported directly from `base`. If backwards compatibility is a concern, we could deprecate the `schema` and `creation` modules as they're now empty except for the aliases, but deprecating what's in `backends.__init__()` isn't so easy. I'm inclined to consider this mostly private API and clean it up with a note in the release notes. I think the number of external backends is sufficiently small that the overhead of a deprecation is more than asking those people to update their code.

Thoughts on this?

**Comment by claudep** [comment]
I agree. But I think a final review by our ORM masters would be great.

**Comment by akaariai** [comment]
The proposed structure looks good to me.

**Comment by timgraham** [comment]
Okay, this is ready for review (removed old aliases and added a release note). I think I'll squash commits before merging.

**Pull request merged**
