### PR TITLE
Fixed #32668 -- Separated test-collection setup from test-run setup in runtests.py.

### PR DESCRIPTION
**Pull request by cjerdonek**
https://code.djangoproject.com/ticket/32668

### CODE REVIEW

**Comment by cjerdonek** [comment]
@felixxm I remember now why I made a variable for `connection.features.gis_enabled`. It was to avoid having to sprinkle the following disclaimer throughout the code, since the flag would be evaluated only in one spot:

```python
# This function should be called only after calling django.setup(),
# since it calls connection.features.gis_enabled.
```

**Comment by felixxm** [comment]
> @felixxm I remember now why I made a variable for `connection.features.gis_enabled`. It was to avoid having to sprinkle the following disclaimer throughout the code, since the flag would be evaluated only in one spot:
> 
> ```python
> # This function should be called only after calling django.setup(),
> # since it calls connection.features.gis_enabled.
> ```

Thanks for the clarification, we can add it to this PR.

**Comment by cjerdonek** [comment]
> Thanks for the clarification, we can add it to this PR.

Okay, I did that.

**Comment by cjerdonek** [comment]
Resolved conflicts.

**Comment by felixxm** [comment]
@cjerdonek Thanks :+1: I squashed some commits.

**Comment by cjerdonek** [comment]
> Thanks 👍 I squashed some commits.

Great, thanks a lot for your help, @felixxm.

**Pull request merged**
