### PR TITLE
Removed unneeded Oracle workaround in GISFunctionsTests.test_num_points.

### PR DESCRIPTION
**Pull request by sir-sigurd**

### CODE REVIEW

**Comment by sir-sigurd** [comment]
buildbot, test on oracle.

**Comment by timgraham** [comment]
I guess it's a change in Oracle 12. I get `AssertionError: 2 != 1` on Oracle 11. @jtiai, any opinion if we should care about supporting Oracle 11 for GIS tests?

**Comment by timgraham** [comment]
I started a thread about [dropping support for Oracle 11.2](https://groups.google.com/d/topic/django-developers/IawbBWzPXaA/discussionv). If there's agreement to drop support after Django 1.11, we can merge this in a few weeks after the `stable/1.11.x` branch is created for Django 1.11 alpha.

**Comment by timgraham** [comment]
I put this on my drop support for Oracle < 12.1 branch: https://github.com/django/django/pull/7971.

**Pull request closed without merging**
