### PR TITLE
command makemessages: emulate xgettext --directory option

### PR DESCRIPTION
**Pull request by terencehonles**
Allow a user to specify a directory other than the current directory to search for translatable files.

### CODE REVIEW

**Comment by claudep** [comment]
Hi Terence, we would first need a Django ticket and a use case for this request.

**Comment by terencehonles** [comment]
Thanks @claudep I added https://code.djangoproject.com/ticket/29797

**Comment by carltongibson** [comment]
Closing as per ticket.

**Comment by terencehonles** [comment]
@claudep @carltongibson I replied on the ticket tracker, but I do not agree with the decision and the suggested alternatives are not applicable or will not work.

**Pull request closed without merging**
