### PR TITLE
Fixed #28858 -- Removed unnecessary "else" statements.

### PR DESCRIPTION
**Pull request by timgraham**
Opinions on this patch are welcome. I'm not sure if it's an improvement.
https://code.djangoproject.com/ticket/28858

### CODE REVIEW

**Comment by srinivasreddy** [comment]
+1 I like this programming style and follow always.

**Comment by orf** [comment]
I also like this, it seems cleaner and reduces indentation which is a plus. Is there a flake8 plugin we can enable on the linter for this?

**Comment by pope1ni** [comment]
+¾ - I largely agree with what Adam said in the ticket on this - where it doesn't impact readability, which is fine in the majority of cases.

**Comment by jonashaag** [comment]
I think this is a disimprovement when`elif` is used to distinguish between disjoint cases, where you'd use `switch ... case` or `cond` (Lisp) in other languages.

### Reason 1: code structure

`switch ... case` is the most readable construct for case distinctions:

```
# Very generalised form of switch ... case
switch:
  case a(foo):
    ...
  case b(foo):
    ...
  case c(foo):
    ...
  otherwise:
    ...
```

The closest you can get in Python is

```python
if a(foo):
  ...
elif b(foo):
  ...
elif c(foo):
  ...
else:
  ...
```

Compare this to:

```python
if a(foo):
  ...
if b(foo):
  ...
if c(foo):
  ...
...
```

It dedents the `else` case, losing the visual clue that this is one of the 4 cases that are being considered.

### Reason 2: Additional reasoning complexity

`switch ... case` and `elif` cascades make it very clear that these cases are *disjoint* (that is, ignoring implicit fallthrough, which is horrible design). Multiple `if` blocks without `elif` require you to parse every single `if` block for `return` statements (etc.) in order to understand the code structure. So by having less visual and semantic structure, multiple `if` blocks have higher reading/understanding complexity.

### Reason 3: No advantages?

Not sure here, but I don't see any advantages of using `if` over `elif` cascades other than that you can lose one level of indentation in the "otherwise" case, and the otherwise case *only*, which isn't really that much of an improvement considering that all other cases are indented anyways.

**Comment by timgraham** [comment]
Yes, that was along the lines of my thoughts. Not using elif  doesn't make it obvious that the conditions are mutually exclusive - you have to check each branch for a return statement. See https://stackoverflow.com/a/22783232 for an example.

**Comment by srinivasreddy** [comment]
But it makes sense to raise exceptions with stacked if conditions.  
```
if something:
   raise SomeExeption(....)
if another:
   raise  AnotherException(...)
```
I find the above pattern much better than
```
if something:
   raise SomeExeption(....)
elif another:
   raise  AnotherException(...)

```

**Comment by jdufresne** [comment]
Just my personal opinion, I prefer the style proposed in this PR for the following cases:

1. Raising an exception inside an `if` statement. It is understood as an exceptional case that immediately returns early.
2. Return early guard clauses for the same reason as exceptions.

I do not prefer this style for:

1. chained `if`/`elif` that look like `switch`/`case` statements of other languages. My preference here is the same as others have said, it makes the mutual exclusiveness less clear.
2. `if`/`else` return statements on the same line without additional logic. For example, I don't think the following should have the `else` removed:

```py
if some_condition():
    return 42
else:
    return None
```

**Comment by timgraham** [comment]
Is the point of #2 to have the return statements lined up?

**Comment by jdufresne** [comment]
Right. Although, I'd probably write that example as `return 42 if some_condition() else None`. Either way, I think it is only my personal preference and nothing more. I don't feel it must be codified in the style guide unless there is a lot of agreement or provides a measurable readability or performance improvement (which I don't believe is the case).

**Comment by timgraham** [comment]
I'm not going to spend more time on this.

**Pull request closed without merging**
