### PR TITLE
Fixed #32372 -- Made examples in related objects reference docs consistent.

### PR DESCRIPTION
**Pull request by jackaitken**
Made change to improve consistency between examples of a reverse relationships.

### CODE REVIEW

**Comment by felixxm** [comment]
@jackaitken Thanks :+1: Welcome aboard :boat:

**Comment by jackaitken** [comment]
> @jackaitken Thanks 👍 Welcome aboard ⛵

Thank you, Mariusz! and thank you for you help.

**Comment by timgraham** [comment]
It seems that the sentence that follows should be updated ... `reporter.article_set`.

**Comment by jackaitken** [comment]
Yes, I missed that. Should I make an additional PR on the same ticket or
should I open a new ticket?

**Comment by timgraham** [comment]
Same ticket please.

**Comment by jackaitken** [comment]
Okay thanks.

**Pull request merged**
