### PR TITLE
Ticket-24753: Add test which demonstrates issue

### PR DESCRIPTION
**Pull request by mdentremont**
- Test demonstrates an issue where the condition used in a case
  statement is filtering objects from the queryset

### CODE REVIEW

**Comment by mdentremont** [comment]
Test demonstrates the following: https://code.djangoproject.com/ticket/24753

**Comment by timgraham** [comment]
Thanks, do you plan to work on a fix? If not, we can close this pull request as whoever works on the fix will be able to incorporate your test.

**Comment by mdentremont** [comment]
@timgraham I'm not sure when I would have time, but I could.

My intention was to raise awareness/understanding with the unit test, and whoever picked up the ticket could steal it for their pull request.

@akaariai commented on the ticket saying he was going to look into it soon, I'll let him take over if this is the case.

**Comment by timgraham** [comment]
Okay, we can reopen this or you can send a new PR if so. Thanks for the test!

**Pull request closed without merging**
