### PR TITLE
Fixed #26814 -- Updated error message to point to mysqlclient.

### PR DESCRIPTION
**Pull request by ad-m**
See trac issue https://code.djangoproject.com/ticket/26814 .

### CODE REVIEW

**Comment by timgraham** [comment]
The error message is correct in that the `mysqlclient` package provides a module named `MySQLdb`. See also https://github.com/PyMySQL/mysqlclient-python/issues/44. I guess we might consider a slight rephrasing of the current proposal.

**Comment by ad-m** [comment]
Package ```mysqlclient``` provide ```MySQLdb``` module too.

**Comment by timgraham** [comment]
What I'm saying is that the current error message isn't mentioning pip installable names. 

Something like this would make more sense to me: ""Error loading MySQLdb module: %s.\n Have you installed mysqlclient or MySQL-Python?"

**Comment by timgraham** [comment]
merged in 92d323ccb5239e3f04b6cb749521fffa71318923, thanks!

**Pull request closed without merging**
