### PR TITLE
Fixed #25966 -- Relaxed model import policy regarding apps ordering

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
@aaugustin I'd like to have your opinion about this patch.

**Comment by aaugustin** [comment]
To be honest I don't this this is the right approach. First, it introduces a dependency loop between the app config and the app registry. Second, it breaks the guarantees of the three-stage loading sequence. If we decide to do that, then we should merge the two first stages properly, not accidentally with an isolated workaround.

To make the test pass, I would just swap the order of apps in `INSTALLED_APPS` :-)

That said, "put the app that defines your user model early enough in INSTALLED_APPS" may not be considered a satisfactory resolution. Actually there's some value in lifting constraints on the order of INSTALLED_APPS, as that order controls five different things.

The idea in this patch is to change `get_user_model` to attempt an import of the model isn't imported yet. I think that's the right idea in general but, as anything that involves more than one app (the app calling get_user_model() and the app providing that model) it should live in the app registry, not in the app config.

I submitted an entirely untested proposal in #6547. Do you think implementing `get_user_model()` with this new app registry method would solve the issue raised in Trac ticket 25966?

**Comment by aaugustin** [comment]
To be clear - the main difference between your proposal and mine is that I don't change the `check_*_ready()` calls. They're important. You'll have to bring strong arguments to the table or walk over my dead body to relax them :-)

**Comment by claudep** [comment]
Thanks for your input. Moving the logic at the registry level makes much sense.
I'll comment on your PR.

**Comment by timgraham** [comment]
I guess we can close this in favor of the other PR?

**Comment by aaugustin** [comment]
Yes. we can.

**Pull request closed without merging**
