### PR TITLE
Fixed #35127 -- Made Model.full_clean() ignore GeneratedFields.

### PR DESCRIPTION
**Pull request by felixxm**
Thanks Claude Paroz for the report.

Regression in f333e3513e8bdf5ffeb6eeb63021c230082e6f95.

ticket-35127

### CODE REVIEW

**Review by shangxiao — APPROVED** [review]
Nice quick fix.

We've seen this pop up once before, I was almost going to suggest defining something alongside fields in a similar spirit to `concrete_fields` though not sure it's worth it.

Are there any more instances of accessing `fields` that we should check or have you checked already?

**Review by claudep — APPROVED** [review]
Thanks for the quick fix!

**Comment by felixxm** [comment]
Thanks both for checking :+1: 
 
> We've seen this pop up once before, I was almost going to suggest defining something alongside fields in a similar spirit to `concrete_fields` though not sure it's worth it.

Yes, there are a few places, but I don't think it's worth adding `concrete_non_generated_fields`. Maybe later on the `main` as a cleanup.
 
> Are there any more instances of accessing `fields` that we should check or have you checked already?

I'll check other places, but even If I find something, it will be a separate bug.

**Comment by charettes** [comment]
I wonder if this is a missed opportunity to branch of `field.editable` instead.

Per [the docs](https://docs.djangoproject.com/en/5.0/ref/models/fields/#editable) these are already skipped during model validation. Is it not the case?

**Comment by felixxm** [comment]
> I wonder if this is a missed opportunity to branch of `field.editable` instead.
> 
> Per [the docs](https://docs.djangoproject.com/en/5.0/ref/models/fields/#editable) these should be skipped during model validation. Is it not the case?

I don't think that would work :thinking:, because `AttributeError` is raised when getting a value for deferred generated fields and `clean()` will still try to do this even when we early return from `validate()`.

**Comment by charettes** [comment]
@felixxm what I meant is something like that

```diff
diff --git a/django/db/models/base.py b/django/db/models/base.py
index 61925f63ea..ec0e975837 100644
--- a/django/db/models/base.py
+++ b/django/db/models/base.py
@@ -1628,7 +1628,7 @@ def clean_fields(self, exclude=None):

         errors = {}
         for f in self._meta.fields:
-            if f.name in exclude or f.generated:
+            if f.name in exclude or not f.editable:
                 continue
             # Skip validation for empty fields with blank=True. The developer
             # is responsible for making sure they have a valid value.
```

which seems more correct based on the `Field.editable` documentation

> They are also skipped during [model validation](https://docs.djangoproject.com/en/5.0/ref/models/instances/#validating-objects).

And happens to resolve this issue as [`GeneratedField.editable` must be set to `False`](https://github.com/django/django/blob/4879907223d70ee1a82474d9286ccfa5dae96971/django/db/models/fields/generated.py#L18-L20).

FWIW the full test suite passes on SQLite except for `model_fields.test_binaryfield.BinaryFieldTests.test_max_length` which seems to be violating the documentation.

**Comment by felixxm** [comment]
> @felixxm what I meant is something like that

Right :+1: We can change this on the `main` branch (as a separate cleanup) since it breaks some tests.

**Comment by charettes** [comment]
Agreed likely safer, I'll create a ticket about it and target `main`. Thanks for the discussion.

**Pull request merged**
