### PR TITLE
Fixed #26398 -- Made FieldFile.open respect its mode argument

### PR DESCRIPTION
**Pull request by koterpillar**

### CODE REVIEW

**Comment by koterpillar** [comment]
https://code.djangoproject.com/ticket/26398

**Comment by timgraham** [comment]
merged in a52a531a8b34f049fba11c3ee7b010af7534bf90, thanks!

**Comment by koterpillar** [comment]
What happened to the Windows build failure though?

**Comment by timgraham** [comment]
Fixed by adding `obj.normal.close()` to the end of the test.

**Pull request closed without merging**
