### PR TITLE
Refs #30923 -- Fixed an example of rendering templates in contrib.sites docs.

### PR DESCRIPTION
**Pull request by alasdairnicol**

### CODE REVIEW

**Comment by tomagi671** [comment]
Close

**Comment by CarlosMirdeSouza** [comment]
I used the wrong tag, i am doing a comment.

**Comment by alasdairnicol** [comment]
@carlosmirdesouza I can see the red x, but I can’t see any details about which checks failed. The commit only changes 3 lines in the docs and looks ok to me.

**Comment by felixxm** [comment]
@alasdairnicol Are you going to prepare a patch for `howto/custom-template-tags.txt` examples? If not I fine to move this patch forward.

**Comment by alasdairnicol** [comment]
@felixxm No, I'm afraid I'm not going to have time to prepare a patch any
time soon. I'm not familiar enough with the template engine to write a
patch based on Claude's suggestion on the Trac ticket. It would be great if
you merged this fix for the sites docs for now.

**Comment by felixxm** [comment]
@alasdairnicol Thanks :+1:

**Pull request merged**
