### PR TITLE
Corrected note about long names in search docs.

### PR DESCRIPTION
**Pull request by adursun**

### CODE REVIEW

**Comment by felixxm** [comment]
Thanks for this patch, however I don't see much value in this change and we try to avoid small wording changes unless it's a big problem as it creates extra work for documentation translators.

**Comment by adursun** [comment]
The original text mentions `more combinations which appear in the source string`, but `the longer name` has less combinations in the source string, so it is not a close match. My patch was about meaning.

**Comment by felixxm** [comment]
@adursun Thanks, agreed :+1: Welcome aboard :boat:

**Comment by adursun** [comment]
Thank you @felixxm! Keep up the great work :+1:

**Pull request merged**
