### PR TITLE
Fixed #29514 -- Fixed get_default_timezone()/utc equality.

### PR DESCRIPTION
**Pull request by timgraham**
https://code.djangoproject.com/ticket/29514

### CODE REVIEW

**Comment by timgraham** [comment]
@sir-sigurd, do you think it's better to keep some of the original changes like in `django/contrib/sessions/backends/file.py` and `django/core/files/storage.py`? I'm not sure if the changed versions perform worse if `timezone.utc` is reverted to use pytz.

**Comment by sir-sigurd** [comment]
> I'm not sure if the changed versions perform worse if timezone.utc is reverted to use pytz.

They perform a little bit worse:
```
In [9]: %timeit datetime.datetime.fromtimestamp(1, pytz.utc)
1.39 µs ± 17.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [10]: %timeit datetime.datetime.utcfromtimestamp(1).replace(tzinfo=pytz.utc)
1.36 µs ± 12.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```
```
In [12]: %timeit datetime.datetime.now(pytz.utc)
1.4 µs ± 18.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [13]: %timeit datetime.datetime.utcnow().replace(tzinfo=pytz.utc)
1.31 µs ± 16.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

**Comment by jdufresne** [comment]
Was this revert commit intended to be backported to the `stable/2.1.x` branch? That branch is sill using `utc = datetime.timezone(ZERO, 'UTC')`.

https://github.com/django/django/blob/stable/2.1.x/django/utils/timezone.py#L57

**Comment by timgraham** [comment]
My mistake, I added the backport now.

**Pull request merged**
