### PR TITLE
Fixed #29248 -- Renamed field-box CSS class to fieldBox

### PR DESCRIPTION
**Pull request by faheel**
https://code.djangoproject.com/ticket/29248

### CODE REVIEW

**Comment by faheel** [comment]
@carltongibson In which file under `docs/release/` should I add a note about this change? `2.0.5.txt` or `2.1.txt`?

**Comment by carltongibson** [comment]
It'll have to be `2.1.txt`.

**Comment by faheel** [comment]
Under the "Miscellaneous" subsection under "Backwards incompatible changes in 2.1", or under the ":mod:`django.contrib.admin`" subsection (doesn't already exist)?

**Comment by faheel** [comment]
I've added the note to the "Miscellaneous" subsection. Let me know if it needs to be changed.

**Comment by timgraham** [comment]
I updated the release note to specify "The *admin* CSS class" and also to double the backticks there, as single backticks don't have a visible effect in the rendered docs.

**Pull request merged**
