### PR TITLE
Fixed ``call_command`` example in the docs

### PR DESCRIPTION
**Pull request by rfleschenberg**

### CODE REVIEW

**Comment by timgraham** [comment]
The documented version works fine as far as I know, did you try it?

**Comment by rfleschenberg** [comment]
Hey Tim,

I did, but maybe I am missing something?

Not working:
```
>>> call_command("flush", "verbosity=0")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/rene/.virtualenvs/hypocaust/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 123, in call_command
    defaults = parser.parse_args(args=[force_text(a) for a in args])
  File "/home/rene/.virtualenvs/hypocaust/local/lib/python3.5/site-packages/django/core/management/base.py", line 58, in parse_args
    return super(CommandParser, self).parse_args(args, namespace)
  File "/usr/lib/python3.5/argparse.py", line 1738, in parse_args
    self.error(msg % ' '.join(argv))
  File "/home/rene/.virtualenvs/hypocaust/local/lib/python3.5/site-packages/django/core/management/base.py", line 64, in error
    raise CommandError("Error: %s" % message)
django.core.management.base.CommandError: Error: unrecognized arguments: verbosity=0
```

Working:
```
>>> call_command("flush", "--verbosity=0")
You have requested a flush of the database.
This will IRREVERSIBLY DESTROY all data currently in the 'hypocaust' database,
and return each table to an empty state.
Are you sure you want to do this?

    Type 'yes' to continue, or 'no' to cancel: 
```

I tried it on Django 1.10, but since the example is the same in the 1.10 docs as in the master docs, I guessed that the bug also applies to master.
```
>>> from django import VERSION
>>> VERSION
(1, 10, 7, 'final', 0)
>>> 
``

**Comment by rfleschenberg** [comment]
I just reproduced with the current master, looks the same.

**Comment by timgraham** [comment]
Thanks, when I tested with another command, it was passing the string as an arg so an error wasn't raised.

**Pull request merged**
