### PR TITLE
Fixed #25198 -- Added optional argument "include_hidden" to model_to_dict()

### PR DESCRIPTION
**Pull request by 1st**
Task description here - https://code.djangoproject.com/ticket/25198

### CODE REVIEW

**Comment by charettes** [comment]
What about `only_editable` as a kwarg name instead? The `hidden` concept isn't part of the model field API and it's not clear to me it should mean `not editable`.

**Comment by 1st** [comment]
@charettes it's bad idea to have parameters with True value by default

**Comment by charettes** [comment]
I'm not sure about the rationale behind this statement.

We have plenty of instances of kwarg defaulting to `True`. Have a look at the `_meta` API or ironically the `django.db.models.Field`'s `editable` kwarg.

**Comment by 1st** [comment]
@charettes okey, we can think about better name. I proposed `include_hidden` and you proposed `only_editable`.

For me it's strange to call this `model_to_dict(obj, only_editable=False)`. Why only editable? I need all, including editable and non-editable fields!

What about name `get_all=True` to return list of all fields? But in this case it will be strange to have in place arguments like `fields` and `exclude`. Need some time to get more information from other reviewers.

**Comment by charettes** [comment]
I agree that both names are not ideal, I just proposed an alternative in order to avoid mixing form and model concepts.

Other naming suggestions are welcome.

**Comment by timgraham** [comment]
Closing per ticket.

**Pull request closed without merging**
