### PR TITLE
Minimize doc images

### PR DESCRIPTION
**Pull request by pauloxnet**
#### Trac ticket number

"N/A"

#### Branch description

Provide minimized docs images generated with https://docs.djangoproject.com/en/stable/internals/contributing/writing-documentation/#minimizing-images

#### Checklist
- [x] This PR targets the `main` branch.
- [x] The commit message is written in past tense, mentions the ticket number, and ends with a period.
- [ ] I have checked the "Has patch" ticket flag in the Trac system.
- [ ] I have added or updated relevant tests.
- [ ] I have added or updated relevant docs, including release notes if applicable.
- [ ] I have attached screenshots in both light and dark modes for any UI changes.

### CODE REVIEW

**Comment by RealOrangeOne** [comment]
How did you compress the images? This seems to have saved just 31 _bytes_.

**Comment by thibaudcolas** [comment]
I don’t think I’d recommend going ahead with this, the gains feel too low compared to the drawback of having a new copy of the images in the git history.

It’d be great to make those images smaller still, but it looks like that’d require a corresponding change to our docs about compressing images, or a switch of those icons to SVG (which would also be great for other theming reasons).

**Comment by pauloxnet** [comment]
> I don’t think I’d recommend going ahead with this, the gains feel too low compared to the drawback of having a new copy of the images in the git history.

To better support new Djago contributors, I tried to re-read the documentation contribution guide and follow all the steps there. I ran the suggested image compression commands and, since there were some differences with the files, I submitted a PR, as I think a new contributor who trusts what he reads could have done. If this kind of PR is not considered useful, but rather harmful to the history of git, then we should add a warning in the documentation with this information to avoid the frustration of a new contributor who follows the guide and has a legitimate PR rejected.

> It’d be great to make those images smaller still, but it looks like that’d require a corresponding change to our docs about compressing images, or a switch of those icons to SVG (which would also be great for other theming reasons).

Speaking in general about image compression in the documentation I agree that we could improve the experience in several ways:
- use a format with better compression for the same support (eg: webp)
- use different image sizes for different user resolutions
- use SVG vector images (I talked about this with Simon at DjangoCon US)

The ideas above are OT in this PR and I should open separate issues or a topic on the forum

**Comment by felixxm** [comment]
@pauloxnet Thanks for this patch, however, this is something that fellows do (aa8c36118c34a1d19680754aca18b22152f1099c, 72b7b59680fecb0bf7108fc00cc27b0476aae107) once in a while (e.g. before the final release of a new version). I don't think it's worth doing more often.

**Comment by pauloxnet** [comment]
> @pauloxnet Thanks for this patch, however, this is something that fellows do once in a while (e.g. before the final release of a new version). I don't think it's worth doing more often.

Ok, it makes sense to me, but maybe we need to add this information also in the "[Writing documentation](https://docs.djangoproject.com/en/stable/internals/contributing/writing-documentation/)" doc pages, so that also people that read that page for the first time will knows that the "[Minimizing images](https://docs.djangoproject.com/en/stable/internals/contributing/writing-documentation/#minimizing-images)" paragraphs is used only from Django Fellow once in a while, and don't want them to run locally and then send a PR with small changes.

**Comment by felixxm** [comment]
> > @pauloxnet Thanks for this patch, however, this is something that fellows do once in a while (e.g. before the final release of a new version). I don't think it's worth doing more often.
> 
> Ok, it makes sense to me, but maybe we need to add this information also in the "[Writing documentation](https://docs.djangoproject.com/en/stable/internals/contributing/writing-documentation/)" doc pages, so that also people that read that page for the first time will knows that the "[Minimizing images](https://docs.djangoproject.com/en/stable/internals/contributing/writing-documentation/#minimizing-images)" paragraphs is used only from Django Fellow once in a while, and don't want them to run locally and then send a PR with small changes.

For me, this information is for folks who add (or modify) images in their doc changes and as such it should stay in docs, i.e if you want to add (or modify) image to the docs, please optimize them. Of course, we cannot remember about everything when reviewing PRs that's why periodical optimizations made by maintainers are fine.

**Comment by pauloxnet** [comment]
I close this PR, which at least had the merit of having highlighted a gap of information in the documentation. I opened the PR #18717 to try to improve the documentation page on writing the documentation itself.

**Pull request closed without merging**
