### PR TITLE
Fixed #25519 -- Added support for SCRIPT_NAME for admin view site

### PR DESCRIPTION
**Pull request by DheerendraRathor**
Used request.META['SCRIPT_NAME'] to determine if SCRIPT_NAME is set.
If it is indeed there and site_url is '/' then used this as site_url

### CODE REVIEW

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
Could you add a mention about this behavior in `docs/ref/contrib/index.txt` where `AdminSite.site_url` is mentioned, as well as in the 1.10 release notes?

**Comment by DheerendraRathor** [comment]
Should I close this PR and create new with docs or a new PR just for doc will be fine?

**Comment by timgraham** [comment]
You can [amend this one](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/working-with-git/).

**Comment by DheerendraRathor** [comment]
I've updated the PR with docs and also added the same in 1.10 release notes

**Comment by timgraham** [comment]
merged in 59e85f09c6c8171d5b24290d455e351063d81f5a, thanks!

**Pull request closed without merging**
