### PR TITLE
Do not repoint relations on superclasses when migrating a subclass's name change

### PR DESCRIPTION
**Pull request by MatthewWilkes**
When renaming a class the migrations framework follows all references backwards in order to repoint their foreign keys to the new location. However, the current implementation doesn't differentiate between relations by virtue of a direct relation to the subclass and those that it inherits from a superclass.

This change explicitly checks that the model that each found relation field belongs to is the same one being renamed. Without this, any project that has a renamed subclass will generate superfluous migrations for the parent class on every invocation of makemigrations, leaving incorrect migrations in eggs and spurious database records if not caught.

### CODE REVIEW

**Comment by MarkusH** [comment]
Thanks for the patch @MatthewWilkes . Can you check if the test works on the recent master and 1.8. It does for me. I just pushed a couple of fixes regarding the migration state (see #4097).

If the error still persists, we do need a ticket on Trac to keep track of the issue.

Thanks.

**Comment by MatthewWilkes** [comment]
Hi @MarkusH, thanks for the speedy response! I can confirm this is working on the newest master and `stable/1.8.x`, #4097 looks like a much sturdier fix to the problem and the issues in general.

Apologies for not adding a trac ticket, I was bitten by this today when trying to put a 1.7.4 site live, so I just dove right in, I've not contributed to Django before.

That said, would this fix be appropriate for the 1.7.x line, or is #4097 likely to be backported?

**Comment by MarkusH** [comment]
The patch in #4097 won't be backported to 1.7. 1.8+ has a different migration state handling than 1.7 which caused other problems the PR fixes.

If your patch fails on 1.7 we need a ticket as well (just select 1.7 as a version on Trac) and add a link to this PR here if that fixes the problem and please go ahead and add a short note to the release notes (`docs/releases/1.7.5.txt` as of now).

**Comment by MatthewWilkes** [comment]
Thanks for your help! I've made #4155 for the 1.7 specific merge, and trac ticket 24354 to track this change.

**Pull request closed without merging**
