### PR TITLE
Fixed #24100 -- Dispatched migration plan, state and loader to post_migrate signal

### PR DESCRIPTION
**Pull request by MarkusH**
https://code.djangoproject.com/ticket/24100

### CODE REVIEW

**Comment by charettes** [comment]
I guess this will also require documentation and tests.

**Comment by timgraham** [comment]
Please reopen when it's ready for review.

**Comment by charettes** [comment]
@MarkusH, do you mind if I add the required tests and release notes to complete the patch?

What do you think about also dispatching the `plan`, `state` and `loader` in `pre_migrate`? I know the main purpose of this patch is to deal with the `ContentType` mess but I can think of a couple of use for the `plan` provided in `pre_migrate`.

Also, I remember a discussion about adding a `post_migration` signal that would be fired after each `Migration` is applied. Does it ring a bell?

**Comment by MarkusH** [comment]
Feel free to go ahead. The only thing I don't really like yet is to expose `ProjectState` (and hence `ModelState`) as a public API. I have too many ideas I want to go ahead with soon that might need some refactoring in that area.

**Comment by charettes** [comment]
I think I could submit a reasonable fix for the content type rename issue without exposing the `ProjectState` (`state`).

What I have in mind is hooking to the `pre_migrate` signal and insert a `RenameContentType` operation after each `RenameModel` operation.

**Comment by charettes** [comment]
Superseded by #5835

**Pull request closed without merging**
