### PR TITLE
Fixed #35792 -- Updated the _get_group_permissions method of ModelBackend.

### PR DESCRIPTION
**Pull request by BonaFideIT**
#### Trac ticket number

ticket-35792

#### Branch description

Changed the `_get_group_permissions` method of the `ModelBackend` to match the suggestion from the ticket.

#### Checklist
- [x] This PR targets the `main` branch. 
- [x] The commit message is written in past tense, mentions the ticket number, and ends with a period.
- [x] I have checked the "Has patch" ticket flag in the Trac system.
- [ ] I have added or updated relevant tests.
- [ ] I have added or updated relevant docs, including release notes if applicable.
- [ ] I have attached screenshots in both light and dark modes for any UI changes.

### CODE REVIEW

**Comment by sarahboyce** [comment]
SQL before:
```sql
SELECT "django_content_type"."app_label" AS "content_type__app_label",
       "auth_permission"."codename" AS "codename"
FROM "auth_permission"
INNER JOIN "auth_group_permissions" ON ("auth_permission"."id" = "auth_group_permissions"."permission_id")
INNER JOIN "auth_group" ON ("auth_group_permissions"."group_id" = "auth_group"."id")
INNER JOIN "auth_user_groups" ON ("auth_group"."id" = "auth_user_groups"."group_id")
INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id")
WHERE "auth_user_groups"."user_id" = 3
```

SQL after:
```sql
SELECT "django_content_type"."app_label" AS "content_type__app_label",
       "auth_permission"."codename" AS "codename"
FROM "auth_permission"
INNER JOIN "auth_group_permissions" ON ("auth_permission"."id" = "auth_group_permissions"."permission_id")
INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id")
WHERE "auth_group_permissions"."group_id" IN
    (SELECT U0."id"
     FROM "auth_group" U0
     INNER JOIN "auth_user_groups" U1 ON (U0."id" = U1."group_id")
     WHERE U1."user_id" = 3)
```

@django/triage-review do you see any concerns here?

**Comment by charettes** [comment]
@sarahboyce the query is semantically the same but some backends, notably MySQL, are sometimes pretty bad at dealing with these kind of subqueries.

For example, the _right_ way to perform this query at the database level is likely to do something like (Python equivalent)

```python
user_group_ids = {aug.group_id for aug in auth_user_groups if aug.user_id == 3}
user_auth_group_permissions = [
    agp
    for agp in auth_group_permissions
    if agp.group_id in user_group_ids
]
```

But I've often seen MySQL *not* materialize subqueries for reuse

```python
user_auth_group_permissions = [
    agp
    for agp in auth_group_permissions
    if agp.group_id in {
        aug.group_id for aug in auth_user_groups if aug.user_id == 3
    }
]
```

In all cases it's very atypical for Django projects to have more than a thousands `auth_permission` or `auth_user_groups` so in the catastrophic case where MySQL isn't smart enough to materialize the subquery it should not make a significant difference in latency.

**Comment by sarahboyce** [comment]
Thank you @charettes :star: 

> In all cases it's very atypical for Django projects to have more than a thousands auth_permission or auth_user_groups (per user) so in the catastrophic case where MySQL isn't smart enough to materialize the subquery it should not make a significant difference in latency.

I agree it's atypical 

I think this reads a little nicer and in the (hopefully) fairly unlikely case this upsets someone's project, we could revert
I plan to land this in a couple of days, unless anyone is strongly against this change :+1:

**Review by sarahboyce — APPROVED** [review]
Thank you @BonaFideIT - welcome onboard :boat:

**Pull request merged**
