### PR TITLE
Fixed #14415 -- Do not ignore DB test name setting

### PR DESCRIPTION
**Pull request by boaz85**
Modified the code so it will take DATABASES['db-name']['TEST']['NAME'] into account while it decides which databases to create for tests. Using this setting is essential when testing with different tables in different databases

### CODE REVIEW

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
Did you consider trying to write a test for this change? If not, did you try testing it manually?

**Comment by boaz85** [comment]
I did consider, but couldn't think of a standard way to do this.
I tested it in two projects:
1. A real project where I actually faced this issue.
2. A clean test project with this setup:
* Two DBs in the DATABASES setting. The only difference between them is that the non-default one has ['TEST']['NAME'] setting.
* One django app that contains two models.
* A database router that redirects each model to be handled on a different db (db_for_write and  allow_migrate were overridden to achieve this).
* One test case that only creates one row in each model table.

Before the fix I got 
`ProgrammingError: relation "some_relation" does not exist`

Because Django didn't find the second model table on the first DB. It wan't created because it shouldn't be created on the default db, but the second db was not created because Django assumed it is already exists (after ignoring the ['TEST']['NAME'] setting).

After the fix the test has passed.

**Comment by shaib** [comment]
@boaz85 three points:
- I agree that there is no good way to add a test for the fix.
- when no test-name is defined, you should use the default test-name in the signature rather than the production name. This is required to make behavior consistent when one of the databases has the test name specified and the other doesn't.
- Please review the relevant documentation and see if anything needs to be changed. If so, it may be also useful to add a note in the release notes.

Thanks for working on this!

**Comment by boaz85** [comment]
I changed the code to use _get_test_db_name_ to get the db name for the signature. It behaves exactly like Shai suggested and seems to be cleaner.

I didn't find any doc that should be updated. After all - this is a bug fix and not a new feature, right? Should I update the latest version (1.9.6) release file?

**Comment by timgraham** [comment]
buildbot, test this please.

**Comment by timgraham** [comment]
I think a test something like this might be feasible:
```
from django.db.backends.base.creation import BaseDatabaseCreation
from django.db import connection
import copy
connection = copy.copy(connection)
connection.settings_dict = {..}
self.assertEqual(BaseDatabaseCreation(connection).test_db_signature(), ....)
```
You might be able to do this more elegantly if you look at `tests/backends/tests.py` for other strategies.

This isn't a critical fix or a regression from earlier versions of Django, so it won't be backported to 1.9.

**Comment by boaz85** [comment]
Added regression tests. They all fail without the fix and pass with it.

**Comment by timgraham** [comment]
merged in 5f23f904af387225b685c633014bddbec1cdd256, thanks!

**Pull request closed without merging**
