### PR TITLE
Added new author Sutrisno Efendi

### PR DESCRIPTION
**Pull request by kangfend**
I've added some translations to Indonesian

### CODE REVIEW

**Comment by MarkusH** [comment]
Do you mind pointing me to your contribution / commits to the Django code base. Unfortunately, I couldn't find any.

**Comment by charettes** [comment]
@MarkusH it's probably on Transifex.

**Comment by kangfend** [comment]
Yes, I contribute via transifex

**Comment by charettes** [comment]
Added in afa82aa41a8cd596163990c311c698d25660cccc!

**Pull request closed without merging**
