### PR TITLE
Fixed #27918 -- Add docs for ChoiceWidget.option_template_name

### PR DESCRIPTION
**Pull request by Kulikovpavel**

### CODE REVIEW

**Comment by claudep** [comment]
Thanks, but I think it would be nice to add a short explanation about it under "Selector and checkbox widgets". What do you think?

**Comment by Kulikovpavel** [comment]
Done, @claudep

**Comment by claudep** [comment]
I also thought about adding something along those lines: "Those displaying multiple options present an additional attribute, `option_template_name` which is used to render the individual option." Tim will probably help improving the wording.

I also think it would be nice if the docs would link to the template source. @timgraham, do you know if it's easily doable? That could be a separate commit.

**Comment by Kulikovpavel** [comment]
Something like this?

```
Selector and checkbox widgets
-----------------------------

    These widgets make use of the HTML elements ``select``, ``checkbox`` and ``input`` with ``type='radio'``.
    Those displaying multiple options present an additional attribute, ``option_template_name``,
    which is used to render the individual option. For example, default ``'django/forms/widgets/select_option.html'``
    template:

    .. code-block:: html+django

        <option value="{{ widget.value }}"{% include "django/forms/widgets/attrs.html" %}>
            {{ widget.label }}
        </option>
```

**Comment by claudep** [comment]
@timgraham Do you think a `:source:` role would be adequate to link to the HTML template files? (like https://github.com/python/cpython/blob/master/Doc/tools/extensions/pyspecific.py#L90)

**Pull request merged**
