### PR TITLE
Fixed RelatedGeoModelTest.test_centroid_collect_filter().

### PR DESCRIPTION
**Pull request by felixxm**
Check out https://github.com/django/django/pull/17024#issuecomment-1613786254.

### CODE REVIEW

**Comment by smithdc1** [comment]
Morning. I'm confused (coffee is brewing) At 953f29f700a60fc09b08b2c2270c12c447490c6a I have this one failure. This patch fixes that failure. 

But!

This patch introduces a new failure. 

```
======================================================================
ERROR: test_compressed_file_based_raster_creation (gis_tests.gdal_tests.test_raster.GDALRasterTests.test_compressed_file_based_raster_creation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/envs/gdal37/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/opt/conda/envs/gdal37/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/gdal37/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/workspaces/django/tests/gis_tests/gdal_tests/test_raster.py", line 452, in test_compressed_file_based_raster_creation
    compressed.bands[0].metadata["IMAGE_STRUCTURE"]["PIXELTYPE"], "SIGNEDBYTE"
    ^^^^^^^^^^^^^^^^^
KeyError: 'IMAGE_STRUCTURE'
```

🤯

**Comment by felixxm** [comment]
> This patch introduces a new failure.

This failure is related with GDAL 3.7, rebase should help.

**Review by smithdc1 — APPROVED** [review]
Of course :-)

LGTM!

**Review by claudep — APPROVED** [review]

**Comment by felixxm** [comment]
Thanks both for checking :+1:

**Pull request merged**
