### PR TITLE
Fixed #24531 -- Improved CommaSeparatedIntegerField validation.

### PR DESCRIPTION
**Pull request by BertrandBordage**
`','`, `'1,,1'`, `',1'` etc are no longer considered as valid
comma-separated integer lists.

Additionally, you can now easily create integer list validators
with a custom separator instead of a comma using the function
`django.core.validators.int_list_validator`.

### CODE REVIEW

**Comment by timgraham** [comment]
Hi, it looks like you've sent a pull request without filing a Trac ticket. Please [file a ticket](https://code.djangoproject.com/newticket) to suggest changes and see our [patch review checklist](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/submitting-patches/#patch-review-checklist) for more guidelines.

**Comment by BertrandBordage** [comment]
Hi Tim,
That’s right, there was no Trac ticket as I thought this was trivial enough to skip that, as mentionned in the contribution guidelines.
Sorry about that, I just created [Trac ticket #24531](https://code.djangoproject.com/ticket/24531) to fix that.

**Comment by timgraham** [comment]
Could you add a mention in the 1.9 release notes for the regex changes in the backwards incompatible changes section and also document `int_list_validator` in `docs/ref/validators.txt` since it seems you think that will be useful as a public API?

**Comment by BertrandBordage** [comment]
Of course :) I just did it.
Btw, I noticed missing newlines between titles and `.. data::` etc in *validators.txt*. The `[source]` link is therefore missing in the compiled docs.

**Comment by BertrandBordage** [comment]
(I don’t understand what happens to Jenkins when building docs…)

**Comment by timgraham** [comment]
buildbot, test this please.

**Comment by timgraham** [comment]
merged in 3e64f3d0fc285080b42b78b67565b6ed939f9a24, thanks!

**Pull request closed without merging**
