### PR TITLE
Fixed #29901 -- Allowed overriding an autocomplete/raw_id_fields/radio_fields widget with ModelAdmin.get_formset().

### PR DESCRIPTION
**Pull request by javiermatos**
https://code.djangoproject.com/ticket/29901

### CODE REVIEW

**Comment by timgraham** [comment]
In your use case, I assume the use of `MySelect` is conditional? Otherwise, I assume you would just remove `opening_band` from `raw_id_fields`.

**Comment by javiermatos** [comment]
Thank you for your feedback. I am so sorry but you will have to help me a bit about this (first contribution to Django :P) What do you mean by `MySelect` conditional?

There are three cases (`db_field.name in self.get_autocomplete_fields(request)`, `db_field.name in self.raw_id_fields` and `db_field.name in self.radio_fields`) where the custom widget will get overrided. If I remove `opening_band` from `raw_id_fields`, then my custom widget `MySelect` will be used even without the fix. The idea is not to override the custom widget if it is set in `kwargs`, just as it is in `formfield_for_choice_field` a few lines up:

```
    def formfield_for_choice_field(self, db_field, request, **kwargs):
        """
        Get a form Field for a database Field that has declared choices.
        """
        # If the field is named as a radio_field, use a RadioSelect
        if db_field.name in self.radio_fields:
            # Avoid stomping on custom widget/choices arguments.
            if 'widget' not in kwargs:
                kwargs['widget'] = widgets.AdminRadioSelect(attrs={
                    'class': get_ul_class(self.radio_fields[db_field.name]),
                })
            if 'choices' not in kwargs:
                kwargs['choices'] = db_field.get_choices(
                    include_blank=db_field.blank,
                    blank_choice=[('', _('None'))]
                )
        return db_field.formfield(**kwargs)
```

Maybe I should extend the test a bit more to cover that other case not having `opening_band` in `raw_id_fields`.

**Comment by timgraham** [comment]
My question is why do you have `opening_band ` in `raw_id_fields` if you want to use a custom widget?

**Comment by javiermatos** [comment]
I wanted to have a base raw id field. After that, I wanted to customize it even more, so I set the widget in kwargs for TabularInline.get_formset method (I did it there because I need the request for creating the custom widget). I forgot to remove the field whose widget I was customizing and I realized that in case of conflict, having the field in `raw_id_fields` will make django not to use my custom widget.

Custom widget will prevail for method `formfield_for_choice_field`, so for consistency I think `formfield_for_foreignkey` must behave the same. It make sense for custom widget to override everything else (even when in conflict with `raw_id_fields`).

**Comment by javiermatos** [comment]
Thank you so much for your help Tim! :)

**Pull request merged**
