### PR TITLE
Changed admin templates to use POST for logout

### PR DESCRIPTION
**Pull request by rfleschenberg**
This changes the admin templates to use ``POST`` for logging out. See https://github.com/django/django/pull/12504.

I turned the log out link into a form with a button element styled as a link. I am not that good with CSS, so any suggestions for improvements would be highly appreciated.

It seemed to be the least intrusive approach to me. On https://code.djangoproject.com/ticket/15619 there has been some talk about adding an intermediate page instead, but I am not sure if we want to go there.

I am unsure if I got the color / font-weight of the button right. On my screen it seems to look slightly different to the other ``#user-tools`` links, but when I increase the font size, it seems to look the same. Maybe that is just me / my screen?

Thanks to VectorX from #regex on freenode for helping me adjust the failing test!

### CODE REVIEW

**Comment by apollo13** [comment]
In my firefox the uppercase doesn't seem to get applied to the button:
image

**Comment by apollo13** [comment]
I am getting better results with:
```
diff --git a/django/contrib/admin/static/admin/css/base.css b/django/contrib/admin/static/admin/css/base.css
index 1121d3c59f..a7c0e12605 100644
--- a/django/contrib/admin/static/admin/css/base.css
+++ b/django/contrib/admin/static/admin/css/base.css
@@ -910,8 +910,11 @@ table#change-history tbody th {
   border: none;
   border-bottom: 1px solid rgba(255, 255, 255, 0.25);
   cursor: pointer;
-  font-size: 1em;
+  font: inherit;
   font-weight: inherit;
+  font-size: inherit;
+  letter-spacing: inherit;
+  text-transform: inherit;
   padding: 0;
 }
```
That said, the border of the button is still below the other borders.

**Comment by apollo13** [comment]
I pushed some style fixes, now it seems to behave the same in firefox & chrome at every zoom level.

**Comment by rfleschenberg** [comment]
> I pushed some style fixes, now it seems to behave the same in firefox & chrome at every zoom level.

Thanks! There is a failing check now, but that looks more like a problem in Jenkins:

```
/tmp/jenkins3378407137654648946.sh: 2: /tmp/jenkins3378407137654648946.sh: npm: not found
```

**Comment by apollo13** [comment]
@rfleschenberg do we miss something here or would that be merge-ready? In the latter case we can ask our fellows to give it another look.

**Comment by rfleschenberg** [comment]
> @rfleschenberg do we miss something here or would that be merge-ready? In the latter case we can ask our fellows to give it another look.

Sorry for being late to respond, this somehow slipped through my radar :( I guess I should rebase against current upstream, do some manual testing, then ask for feedback. I'll try to do so ASAP. In the meantime any feedback is much appreciated :)

**Comment by jacobtylerwalls** [comment]
Hi @rfleschenberg forgive me if you know this, but I think filling out a ticket a code.djangoproject.com is the best way to swim with the current here (in a sea of 178 open PRs on GH!) because reviewers tend to rely on the ticket info to assess what's ripe for review. All best, Jacob

**Comment by felixxm** [comment]
Fixed by 94d8ed55fa8e181b98f818a1b2805c66943cfeec.

**Pull request closed without merging**
