### PR TITLE
Fixed #29090 -- Updated Hungarian time formats to use ':' instead of '.'.

### PR DESCRIPTION
**Pull request by danieltatraivertis**
It's about time notation in Hungary, we use officially ':' instead of '.' among hour, minute and second. Also added the leading zeroes to hour. This one is not official, just some standardization. 
I can't provide tests yet, but probably some expert eyes are enough to check.

### CODE REVIEW

**Comment by timgraham** [comment]
I think the original formats (98a69a2c0a9d6a57cc637b0e9a998495fc0bcbd7) are from @nyuhuhuu, so maybe he has an opinion about this.

**Comment by danieltatraivertis** [comment]
I did more research. Officially the dot separator is also correct, but in practice in Hungary, only semicolon used. That's why as a Hungarian I didn't even know dot separator is also correct. However I suggest to replace the dot to semicolon due to practice reasons and also is confusing, because date is also separated by dot. Official source about the topic: http://helyesiras.mta.hu/helyesiras/default/akh12
It's in Hungarian language, but actually the last # 300 rule about the time formating, says both correct, however no mention about preference or practice, still the case the above mentioned.

Also some proof about the use in Hungary:
1.  Check computer local settings for Hungary
2.  Some random article from one of the biggest news site in Hungary and can check the publish datetime: https://index.hu/gazdasag/2018/01/31/kartonpack_mnb_kerek_csaba/
3.  Hungarian authority's website, can check the open times at http://nav.gov.hu/nav/kapcsolat
4.  Ask any Hungarian how would one write 10 hour 44 minutes

(I am really struggling with spamfilter of code.djangoproject.com, so I had to comment here)

**Comment by timgraham** [comment]
Do you have a Hungarian colleague who can review the patch and +1 the changes?

**Comment by nyuhuhuu** [comment]
Thanks for pinging me. The changes from @danieltatraivertis are okay to me.

Dot notation was first ([see previous edition](http://helyesiras.mta.hu/helyesiras/default/akh11#299)). I guess semicolon just made more sense to reflect the representation of that spelling already out in digital news.

NB [Drupal uses](https://www.drupal.hu/) the classic notation.

**Pull request merged**
