### PR TITLE
Fixed #26708 -- Updated the contributing tutorial to use GitHub workflow.

### PR DESCRIPTION
**Pull request by za**
Django ticket: [#26708](https://code.djangoproject.com/ticket/26708)

### CODE REVIEW

**Comment by timgraham** [comment]
This doesn't really address the ticket. Did you plan to make further changes or is it unclear what should be done?

**Comment by za** [comment]
Hi Tim. Yes, I am about to make more changes.

**Comment by timgraham** [comment]
Okay, please send a pull request when it's ready to review.

**Comment by za** [comment]
@timgraham ack.

**Pull request closed without merging**
