### PR TITLE
Fixed #33742 -- Added id to GeoJSON serializer.

### PR DESCRIPTION
**Pull request by solarissmoke**

### CODE REVIEW

**Review by claudep — APPROVED** [review]
This looks totally fine to me, thanks a lot for the patch!

**Comment by solarissmoke** [comment]
@claudep sorry, I've just pushed an amended version which converts PK to a string, the same way we do further down - I think this may be safer for cases where the PK isn't the default integerfield? Let me know what you think.

**Comment by claudep** [comment]
I understand not converting the pk could be an issue if the pk type is not natively JSON serializable, but on the other side, forcing integers to strings is not very elegant IMHO. But as `DjangoJSONEncoder` is already handling several "alternative" types, I think I'd better see your latest changes reverted.

**Comment by solarissmoke** [comment]
@claudep thanks for the feedback! I've reverted to the original set of changes.

**Comment by felixxm** [comment]
@solarissmoke Thanks :+1: I pushed small edits to docs.

**Comment by fchabouis** [comment]
Hi,
Is there any option to keep the previous behavior?
I am serializing one of my model to geojson, but do not want to publish any internal id.
Thanks

**Pull request merged**
