### PR TITLE
Fixed #30870 -- Fixed "migrate --plan" outputs "IRREVERSIBLE" on RunPython operations without docstrings.

### PR DESCRIPTION
**Pull request by hramezani**
[ticket 30870](https://code.djangoproject.com/ticket/30870)
Solution Proposed by @felixxm in the ticket.

### CODE REVIEW

**Comment by felixxm** [comment]
@hramezani Thanks for this patch :+1: After reconsideration I think we should display `IRREVERSIBLE` only for reverse migrations (`backwards is True`). We could also handle `migrations.RunPython.noop` and `migrations.RunSQL.noop` as a special case (in a separate commit).

Release notes are missing. Please add also a test with method without a docstring in a `reverse_code` (it should fail with plan for reverse migrations).

**Comment by felixxm** [comment]
\cc @carltongibson

**Comment by hramezani** [comment]
@felixxm I pushed my changes. I don't know how far is it close to your ideal patch.
You can drop it and work on your patch if you don't time to review it or it is not fit for you.

**Comment by felixxm** [comment]
Superseded by #11911.

@hramezani Thanks for the patch. After another reconsideration, I don't think that we need to warn users if they use `noop`, it's their conscious decision.

**Pull request closed without merging**
