### PR TITLE
Fixed #27561 -- Added Oracle support for binary "or" operator.

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Comment by felixxm** [comment]
Buildbot, test on Oracle.

**Comment by timgraham** [comment]
It would be nice to check if there's evidence of any third-party backends using the `supports_bitwise_or` feature. Otherwise, we can remove it.

**Comment by felixxm** [comment]
From the official [3rd-party-database-backends](https://docs.djangoproject.com/en/1.10/ref/databases/#using-a-3rd-party-database-backend) only [ODBC](https://github.com/lionheart/django-pyodbc) is using `supports_bitwise_or` feature:
```
tests/django16/expressions_regress/tests.py
tests/django14/expressions_regress/tests.py
tests/django15/expressions_regress/tests.py
```
but only in tests based on the old Django versions. I think we can remove `supports_bitwise_or`.

**Comment by felixxm** [comment]
Buildbot, test on Oracle.

**Comment by felixxm** [comment]
I removed `supports_bitwise_or` feature.

**Comment by felixxm** [comment]
Buildbot, test on Oracle.

**Pull request merged**
