### PR TITLE
Improved examples in docs about raw SQL queries.

### PR DESCRIPTION
**Pull request by felixxm**
Regression in 14459f80ee3a9e005989db37c26fd13bb6d2fab2.

### CODE REVIEW

**Review by hramezani — APPROVED** [review]
LGTM

**Review by shangxiao — APPROVED** [review]
Interesting… docs regression 😜

Have you gone rescanned the changes to the blacken-docs commit or should someone do that briefly now?  I looked at the commit, it's quite huge 🤯

**Comment by felixxm** [comment]
> Have you gone and rescanned the changes to the blacken-docs commit or should someone do that briefly now? I looked at the commit, it's quite huge exploding_head

I tried to check it very carefully before merging, but I couldn't notice everything :disappointed: my bad :fire: . I noticed this today by accident. We shouldn't have any more cases like this :crossed_fingers: .

**Comment by felixxm** [comment]
Thanks y'all for reviews :+1:

**Pull request merged**
