### PR TITLE
Fixed #33133 -- Fixed handling NullBooleanField in historical migrations.

### PR DESCRIPTION
**Pull request by felixxm**
See ticket-33133 and https://github.com/jieter/django-tables2/pull/822.

### CODE REVIEW

**Comment by felixxm** [comment]
@jieter Can you confirm that it works for you?

**Comment by jieter** [comment]
@felixxm thanks!

Works as expected:

```
pip install https://github.com/felixxm/django/archive/refs/heads/issue-33133.zip
Collecting https://github.com/felixxm/django/archive/refs/heads/issue-33133.zip
  Downloading https://github.com/felixxm/django/archive/refs/heads/issue-33133.zip
     \ 14.4 MB 7.7 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: sqlparse>=0.2.2 in /Users/jieter/.pyenv/versions/3.9.2/envs/django-tables2/lib/python3.9/site-packages (from Django==4.1) (0.4.2)
Requirement already satisfied: asgiref>=3.3.2 in /Users/jieter/.pyenv/versions/3.9.2/envs/django-tables2/lib/python3.9/site-packages (from Django==4.1) (3.4.1)
Building wheels for collected packages: Django
  Building wheel for Django (PEP 517) ... done
  Created wheel for Django: filename=Django-4.1-py3-none-any.whl size=7911935 sha256=b836b0d791f0ed55309af7c5dcdf51f9c7e900162d9162868605ac8e131c94e4
  Stored in directory: /Users/jieter/Library/Caches/pip/wheels/ff/c7/c1/27beee533115c3939293820cfb72f9a8c61d1543804c7d1acf
Successfully built Django
Installing collected packages: Django
Successfully installed Django-4.1
(django-tables2) ➜  django-tables2 git:(master) ./manage.py test                                                                                                
Found 378 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
...... <snip>
```

(Test database is successfully created, some tests fail, but not related to this issue.)

**Comment by felixxm** [comment]
> Works as expected:

Great, thanks for checking :+1:

**Review by carltongibson — APPROVED** [review]
Yep, looks good thanks. 
(Don't suppose it's worth a test that a removed field returns an existing field here... — no, probably not... 🙂)

**Pull request merged**
