### PR TITLE
Removed lone usage of jQuery in admin's calendar.js.

### PR DESCRIPTION
**Pull request by claudep**
Not sure if this is tested or needs a test at all.

### CODE REVIEW

**Comment by srinivasreddy** [comment]
I think we need a test for this.

**Comment by claudep** [comment]
buildbot, test on selenium

**Comment by claudep** [comment]
buildbot, test on selenium.

**Comment by timgraham** [comment]
Normally we merge additional test coverage in a separate commit from a clean up to avoid the impression that the code change is altering behavior. I'll work on fixing the selenium PR builder but the test works for me.

**Comment by timgraham** [comment]
buildbot, test on selenium.

**Comment by timgraham** [comment]
buildbot, test on selenium.

**Comment by claudep** [comment]
Pushed in 4b67e8dc75b5007 and 8275662a24348c

**Pull request closed without merging**
