### PR TITLE
Removed unused __str__() methods in tests models. 

### PR DESCRIPTION
**Pull request by atombrella**
Maybe there are more of such things in the test suite. Perhaps we can leave this PR to look for more, instead of merging immediately.

### CODE REVIEW

**Comment by adamchainz** [comment]
How did you find these? Ran the test suite with coverage? I see our [Jenkins coverage report](https://djangoci.com/view/%C2%ADCoverage/job/django-coverage/HTML_20Coverage_20Report/) doesn't cover the tests.

**Comment by atombrella** [comment]
> How did you find these? Ran the test suite with coverage? I see our [Jenkins coverage report](https://djangoci.com/view/%C2%ADCoverage/job/django-coverage/HTML_20Coverage_20Report/) doesn't cover the tests.

It was a bit by coincident: I opened a models file in PyCharm, and the `self.name` was highlighted. Then I thought that they're probably more. The content of some of those models file have not been touched for ~8-12 years. I haven't thought of coverage of the tests.

**Comment by hramezani** [comment]
@atombrella I found some of them. it is possible to push to your branch?

**Comment by felixxm** [comment]
I pushed few more.

**Comment by felixxm** [comment]
... and 7 more. 457 `__str__()` methods left.

**Comment by atombrella** [comment]
> @atombrella I found some of them. it is possible to push to your branch?

@hramezani Thank you, please just list them here. I think that's a better approach. @felixxm Please remember to add yourself in ``Co-Authored-By``. Thank you.

It seems that `self.name` caught quite a few of them.

Do you use something like `grep -A 2 -B 10 __str__ --include="*.py" tests/` to check?

**Comment by hramezani** [comment]
> Do you use something like grep -r -A 2 -B 10 __str__ --include="*.py" tests/ to check?

Yes, I do.

Here is the [diff file](https://github.com/django/django/files/4098265/remove_str.txt). It will remove 25 of them.

**Comment by felixxm** [comment]
I used `find -name models.py | xargs grep 'def __str__' `.

**Comment by felixxm** [comment]
I added few more. I think it's a good start that it's worth to merge. We removed 50 methods.

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Pull request merged**
