### PR TITLE
Updated an example of `bulk_create` in docs

### PR DESCRIPTION
**Pull request by illia-v**

### CODE REVIEW

**Comment by timgraham** [comment]
I'd rather use an example that doesn't have to be updated every few years.

**Comment by adamchainz** [comment]
"Python 4.0 released"

**Comment by illia-v** [comment]
@adamchainz, and "Python 2.8 Planned" 😃

**Comment by timgraham** [comment]
Fixed in e2d02c1fc99d8d85ec2a13a745cb786a15a5c6b2, thanks!

**Pull request closed without merging**
