### PR TITLE
Fixed #31124 - Model.get_FOO_display() does not work correctly with i…

### PR DESCRIPTION
**Pull request by woopsix**

### CODE REVIEW

**Comment by zeyneloz** [comment]
Thank you for the patch @woopsix 👍 
In my opinion, `_get_FIELD_display` is not the right place to fix this bug and you should look into  `django.db.models.fields.Field.contribute_to_class`.
The problem is that field `foo` of abstract class contributes to the class and sets `get_field_foo_display` attribute before the field `foo` of the child class. That's why field `foo` from child class (with updated choices) doesn't override existing `get_field_foo_display` attribute, [see this line ](https://github.com/django/django/commit/2d38eb0ab9f78d68c083a5b78b1eca39027b279a#diff-bf776a3b8e5dbfac2432015825ef8afeR766)
You might want to check the [ticket 30931](https://code.djangoproject.com/ticket/30931)

**Comment by woopsix** [comment]
@zeyneloz thanks for the tip.
Can we assume that if the model of the field is not abstract, it should override the method?
I made a change and running the tests works, with that approach

**Comment by zeyneloz** [comment]
> @zeyneloz thanks for the tip.
> Can we assume that if the model of the field is not abstract, it should override the method?
> I made a change and running the tests works, with that approach

Well that would work only for this case but would break the expected behaviour described on [ticket 30931](https://code.djangoproject.com/ticket/30931).
I think the expected behaviour here is unclear for overriding `get_<field>_display` since it is a magic method added by metaclass. Normally I would expect MRO behaviour of python inheritance as a developer but this is a kind of special case.
There are dirty and quick ways to fix this bug but I think this might be time to think more fundamentally about the duties of `contribute_to_class` and similar hooks. Lets discuss this on [the ticket](https://code.djangoproject.com/ticket/31124) before making any changes.

**Comment by felixxm** [comment]
Superseded by #12284 .

**Pull request closed without merging**
