### PR TITLE
Fixed #24951 -- Fixed AssertionError in delete queries involving a foreign/primary key.

### PR DESCRIPTION
**Pull request by timgraham**
Probably not the correct fix, but does work.

https://code.djangoproject.com/ticket/24951

### CODE REVIEW

**Comment by timgraham** [comment]
@akaariai, any advice on this one?

The query looks like:
```sql
DELETE
    FROM "one_to_one_pointer"
    WHERE "one_to_one_pointer"."other_id" IN (
        SELECT U0."other_id" AS Col1
        FROM "one_to_one_pointer" U0
        INNER JOIN "one_to_one_target" U1 ON ( U0."other_id" = U1."id" )
        WHERE U1."name" = %s
    )
```
.. and `self.query.tables` is `['one_to_one_pointer', 'one_to_one_target']` at the AssertionError (as opposed to `['one_to_one_pointer']` before 20bab2cf9d02a5c6477d8aac066a635986e0d3f3.

**Comment by akaariai** [comment]
It might be asserting that there is just one *active* table in the query is the right thing to do. This is doable by checking len([t for t in self.query.tables if self.query.alias_refcount[t] > 0]) == 1.

My unverified guess is that the other_id IN filter creates a join to the other table, and this is then immediately trimmed away. Thus the table gets first reffed, then unreffed. The end result is that it ends up in query.tables with refcount of 0.

BTW it seems the subquery isn't optimal, we could trim the INNER JOIN away and directly select U1.id as that is guaranteed to have the same value as U0.other_id. Not this PR's problem of course...

**Comment by timgraham** [comment]
That does allow the test to pass. We don't currently have a test for the `AssertionError`. Do you think it's important to add one (now or later)? (maybe it's just meant as a check against bugs in Django itself).

**Comment by akaariai** [comment]
I don't think we need to add a test for the AssertionError. Django shouldn't ever generate a query where multiple tables are active when deleting (instead such cases are handled by subqueries). So, testing this would require some kind of a hack where we work around the normal delete mechanism.

In addition, if the assertion were to be removed the result should be an invalid query (delete from ... join ... doesn't work). So, we will get a test failure in that case, too.

**Pull request merged**
