### PR TITLE
Fixed #26238 -- Raised explicit error for non-editable field in ModelForm

### PR DESCRIPTION
**Pull request by claudep**
Thanks Luke Crouch for the report.

### CODE REVIEW

**Comment by charettes** [comment]
Thanks for the patch Claude.

Could you reuse the `Article` model which already have a non-editable field? I'm just trying to avoid unnecessary table creations as this slow down the test suite start up (and constraints clearing on some backends) significantly.

If you really want to use a `BinaryField` here you could inline your `BinaryContent` model definition in the test method using the `isolate_apps` decorator. I think this would be even better.

**Comment by claudep** [comment]
Thanks for the suggestion, I reused the Article model.

**Comment by charettes** [comment]
The patch is looking good to me!

Do you think we should also amend the `BinaryField` documentation to mention it's not usable in forms by default?

**Comment by claudep** [comment]
Do you mean to complete what I added in this patch? If you have an idea about it, please feel free to suggest an adequate wording.

**Comment by charettes** [comment]
This is exactly what I had in mind. The wording and the patch LGTM.

**Pull request merged**
