### PR TITLE
Changed direct user model import with get_user_model method.

### PR DESCRIPTION
**Pull request by hendrikschneider**
It's better to show good practice in docs, isn't it?

### CODE REVIEW

**Comment by timgraham** [comment]
I'm not completely convinced about the change as it could give the impression that the example works with any user model. It might work, but perhaps not if the custom user model doesn't have the `is_staff`/`is_superuser` fields (i.e. if it inherits `AbstractBaseUser` rather than `AbstractUser`. Also, custom user models might have some some different required fields. Perhaps at least some clarification could be added about those points.

**Comment by timgraham** [comment]
What do you think @hendrikschneider?

**Comment by hendrikschneider** [comment]
Hey timgraham,
you are right. I will fix this :)

**Comment by timgraham** [comment]
Closing due to inactivity.

**Pull request closed without merging**
