### PR TITLE
Fixed #34383 -- Fixed layout of admin fieldsets with multiple fields on the same line.

### PR DESCRIPTION
**Pull request by knyghty**

### CODE REVIEW

**Comment by felixxm** [comment]
I think we should remove `flex` from `.aligned` on really small screens
```diff
diff --git a/django/contrib/admin/static/admin/css/responsive.css b/django/contrib/admin/static/admin/css/responsive.css
index a75d1c5d66..058e196968 100644
--- a/django/contrib/admin/static/admin/css/responsive.css
+++ b/django/contrib/admin/static/admin/css/responsive.css
@@ -564,8 +564,6 @@ input[type="submit"], button {
 
     .aligned .form-row,
     .aligned .form-row > div {
-        display: flex;
-        flex-wrap: wrap;
         max-width: 100vw;
     }
 
```
to get ("Change user" view):
image

instead of:

image

**Comment by felixxm** [comment]
@knyghty Thanks :+1: Great team work :handshake:

**Comment by knyghty** [comment]
@felixxm Fixed those, seems to work as I'd expect now... from what I've tested.

**Review by felixxm — COMMENTED** [review]
@knyghty Thanks :+1: 

I added one more minor fix, and pushed changes to tests.

**Comment by felixxm** [comment]
@camarone Does it work for you?

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Pull request merged**
