### PR TITLE
Fixed #30285 -- Fixed the domain in broken link emails being spoofable

### PR DESCRIPTION
**Pull request by orlnub123**
https://code.djangoproject.com/ticket/30285

Is a test needed?

### CODE REVIEW

**Comment by orlnub123** [comment]
The tests seem to be failing due to the sites framework being installed and `SimpleTestCase` not supporting database queries. I'm not sure if I should simply switch the `BrokenLinkEmailsMiddlewareTest` to a `TestCase`, or override the settings to disable the sites framework.

Additionally the `test_referer_equal_to_requested_url` test fails because the sites framework doesn't seem to be completely setup. The `SITE_ID` points to the default site object with a domain of `example.com`.

**Comment by orlnub123** [comment]
The `test_referer_equal_to_requested_url` test could be fixed by imitating what the sitemaps tests do:
https://github.com/django/django/blob/ea60b7bc7464808e34e3cb0aac04455fdd8545eb/tests/sitemaps_tests/base.py#L13-L14

**Comment by timgraham** [comment]
Adding a dependency on `django.contrib.sites` in a "core" middleware doesn't look nice. Maybe it's better to document the caveat.

If a change is to be made... yes, tests are always required.

**Comment by orlnub123** [comment]
That sounds reasonable. I'm still not sure if reliably getting the current site is an intended use case for the sites framework as the docs don't mention anything about it.

Should I close this and create a new PR?

**Comment by felixxm** [comment]
Closing per ticket.

**Pull request closed without merging**
