### PR TITLE
Refs #25684 -- Removed double newline from request/response output of runserver.

### PR DESCRIPTION
**Pull request by rafrafek**
Remove annoying double newline in broken pipe error, which happens all the time on Windows

Before:
picture1

After:
picture2

### CODE REVIEW

**Comment by nabil-rady** [comment]
You should edit the assertion in /tests/servers/test_basehttp.py so that you don't get assertion errors in the CI.

**Comment by rafrafek** [comment]
> You should edit the assertion in /tests/servers/test_basehttp.py so that you don't get assertion errors in the CI.

Thank you! I've updated assertion to match the change

**Comment by nabil-rady** [comment]
Nice, I think you should squash the two commits into one with `git rebase`.

**Comment by rafrafek** [comment]
> Nice, I think you should squash the two commits into one with `git rebase`.

I did it! Thank you for your time and instructions! ⛵️

**Comment by felixxm** [comment]
@rafrafek Thanks :+1: Welcome aboard :boat: 

I fixed one more case (see 0bc5cd628042bf0a44df60a93085a4f991a84dfb).

**Pull request merged**
