### PR TITLE
Fixed #32230 -- Made DataSource and LayerMapping support pathlib.Path.

### PR DESCRIPTION
**Pull request by hramezani**
https://code.djangoproject.com/ticket/32230

### CODE REVIEW

**Comment by felixxm** [comment]
@hramezani Thanks for the patch :+1: We encourage [triage by the community](https://docs.djangoproject.com/en/3.1/internals/contributing/triaging-tickets/#triage-workflow), so feel-free to accept the ticket if you think it's a viable and reasonable feature.

**Review by claudep — APPROVED** [review]
:+1:

**Comment by pope1ni** [comment]
> ...accept the ticket if you think it's a viable and reasonable feature.

I've accepted, as I *suppose* it's reasonable... :wink:

**Comment by hramezani** [comment]
> > ...accept the ticket if you think it's a viable and reasonable feature.
> 
> I've accepted, as I _suppose_ it's reasonable...

Thanks @pope1ni :+1:

**Comment by felixxm** [comment]
@hramezani Thanks :+1:

I've noticed that `LayerMapping` doesn't support `pathlib.Path` either, so I fixed this in a separate commit 931c6e982c078073dfa9b5dc1ef0059f8c787719 and opened PR #13729 with docs fix for Django 3.1. @claudep Can you take a look?

**Comment by claudep** [comment]
Even better, thanks a lot!

**Pull request merged**
