### PR TITLE
2 regression tests provided for bug #23643

### PR DESCRIPTION
**Pull request by feroda**
These are regression tests for https://code.djangoproject.com/ticket/23643
raw fix provided in https://github.com/django/django/pull/4530, but still I have not investigated if there are further implications (i.e: if that patch really solves the issue).

I hope tests will help

### CODE REVIEW

**Comment by timgraham** [comment]
These tests seem to pass on master without the fix applied, so I don't think they are proper regression tests (unless I missed something)?

**Comment by timgraham** [comment]
If you can fix up these tests so they fail before the fix is applied, please add them to https://github.com/django/django/pull/4530.

**Comment by feroda** [comment]
Excuse  me Tim, 
I have tested this code right now also  with the upstream updated django code and I get both tests fails. Maybe have you run they only in python3? Try to run them in and environment python2. This is the behaviour I want to show: python3 -> good ; python2 -> error.

I have tried to merge them with the fix provided in #4530 BUT the fix is not good so I got errors: AttributeError: 'str' object has no attribute '__traceback__' on tests:

view_tests.tests.test_debug.ExceptionReporterTests test_request_and_message
view_tests.tests.test_debug.ExceptionReporterTests test_message_only
view_tests.tests.test_debug.PlainTextReportTests test_message_only
view_tests.tests.test_debug.PlainTextReportTests test_request_and_message

bye

I should work more on this, but I do not know when...

**Comment by timgraham** [comment]
Maybe that's what I did wrong. I confirmed your findings.

**Pull request closed without merging**
