### PR TITLE
Fixed #24911 -- use model as a named argument

### PR DESCRIPTION
**Pull request by 317070**

### CODE REVIEW

**Comment by timgraham** [comment]
A regression test would be useful.

**Comment by rivol** [comment]
Added regression test at https://github.com/rivol/django/commit/5b88cd4b5dcca5a66055d4deeba82b7034651521

I'm not sure what the procedure is when adding test for an existing patch with an open PR - should I create another PR to Django main repo? Should I get PR to 317070/django repo?

**Comment by timgraham** [comment]
You can update this pull request, see https://docs.djangoproject.com/en/1.8/internals/contributing/writing-code/working-with-git/ for tips.

**Comment by 317070** [comment]
Hi rivol, I added your tests to the pull request. Thanks a lot!

**Comment by 317070** [comment]
I'm new here. Do I need to do something extra on the trac or here to show it is ready for merging?

**Comment by timgraham** [comment]
No, patch is in the review queue (see "patches needing review" at https://dashboard.djangoproject.com/). Will get to it sometime soon.

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by 317070** [comment]
No problem. Thanks for pointing out that page! I understand the Trac-process better now, I think.

**Comment by zauddelig** [comment]
Hello your test are valid only for python3, try to make them more python2-friendly, i.e. `super(class,instance).method(...)`

**Comment by timgraham** [comment]
merged in 4352e865a75923a0e5036b4e9ba2a8f0bfae3d63, thanks!

**Pull request closed without merging**
