### PR TITLE
simple support http1.1 keep-alive

### PR DESCRIPTION
**Pull request by zii**
Just want to use persistent connection, any idea?

### CODE REVIEW

**Comment by timgraham** [comment]
There's a ticket about it here: https://code.djangoproject.com/ticket/25619 
Claude offered https://github.com/django/django/pull/5524, but the selenium tests didn't work. Did you test them with your patch?

**Comment by timgraham** [comment]
selenium tests currently fail with `AttributeError: 'ServerHandler' object has no attribute 'has_length'`. Do you want to try to develop a complete patch with tests, etc?

**Comment by zii** [comment]
I'm testing with selenium, yes it stuck :(
```
python runtests.py --selenium chrome
```

**Comment by zii** [comment]
I don't know why it stuck on this request, any idea?
```
GET /test_admin/admin/jsi18n/ HTTP/1.1
Host: localhost:8081
Connection: keep-alive
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML,
like Gecko) Chrome/53.0.2785.116 Safari/537.36
Accept: */*
Referer: http://localhost:8081/test_admin/admin/admin_views/section/1/change/?_t
o_field=id&_popup=1
Accept-Encoding: gzip, deflate, sdch
Accept-Language: zh-CN,zh;q=0.8
Cookie: sessionid=pacii1gfsq4zz8i8nj908swjydoz5c6f; csrftoken=gLjD4Ravyut0xHJqRq
OMPTUVnxfVealPSZOClj2s4UVOaqudLciUHGfElsozsJpS
```

**Comment by zii** [comment]
How odd! It pass the tests after stripping tail newline of response content.

**Comment by zii** [comment]
Use tornado or gevent are fine too.
```
#!/usr/bin/env python
import os
import sys

# http1.1 patch
from django.core.servers import basehttp

def run_tornado(addr, port, wsgi_handler, ipv6=False, threading=False):
    import tornado.wsgi, tornado.httpserver, tornado.ioloop

    container = tornado.wsgi.WSGIContainer(wsgi_handler)
    server = tornado.httpserver.HTTPServer(container)
    server.listen(port=port, address=addr)
    tornado.ioloop.IOLoop.instance().start()

def run_gevent(addr, port, wsgi_handler, ipv6=False, threading=False):
    from gevent import monkey; monkey.patch_all(thread=False)
    from gevent.pywsgi import WSGIServer
    
    WSGIServer((addr, port), wsgi_handler).serve_forever()

basehttp.run = run_gevent

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "www.settings")

    from django.core.management import execute_from_command_line

    execute_from_command_line(sys.argv)
```

**Comment by claudep** [comment]
I've reopened my PR in #8043. If you think the additions in your patch are adding value or fixing things, please tell us why (and ideally show that by tests).

**Pull request closed without merging**
