### PR TITLE
Fixed 10686 -- Added abstract permission inheritance

### PR DESCRIPTION
**Pull request by sergei-maertens**
I'm awaiting feedback before rebasing the commits into a single commit.

### CODE REVIEW

**Comment by timgraham** [comment]
This seems to be two distinct features which could be added in separate commits at least, however, I'm not convinced that `Meta.inherit_permissions` is needed. Is there a problem with something this:
```
class Meta:
    permissions = BaseTask.Meta.permissions + (more permissions)
```

**Comment by sergei-maertens** [comment]
@timgraham you don't get the specific class name in the permission code, say you need `app.view_task1` and `app.view_task2` where Task1 and Task2 are sharing a common ancestor.

I agree with the `inherit_permissions`, I included it because they were both in the same ticket and original patch.

**Comment by sergei-maertens** [comment]
buildbot, test this please

**Comment by timgraham** [comment]
I think if you want to inherit the base permissions, you could do `Meta(BaseTask.Meta)`.

**Comment by sergei-maertens** [comment]
Isn't that a bit counter intuitive? All other attributes (except for a few
obvious ones like abstract) are inherited by default, no?

**Comment by timgraham** [comment]
According to the ticket, "The `inherit_permissions` flag would only be required in the case that one wanted Django's current behavior which is to discard base class permissions when explicit permissions are declared on the child class." I think it's better to use normal inheritance mechanisms, etc.

I'm also a bit hesitant to proceed with an enhancement like this as it adds further coupling between `Meta` and a contrib app. This doesn't seem like good separation of concerns. It could be useful to raise a discussion on the django-developers mailing list to see what others think.

**Comment by sergei-maertens** [comment]
In that case I rest my case, will adapt the changes when I have the time.

**Comment by sergei-maertens** [comment]
I've started the discussion on the mailing list.

**Comment by timgraham** [comment]
When revising this, I'd suggest to implement it as two commits if possible: first the inheritance changes, then the interpolation additions.

**Comment by sergei-maertens** [comment]
Do you want the two commits in a single PR, or 2 PRs? I suspect the former.

**Comment by timgraham** [comment]
Either is okay.

**Comment by timgraham** [comment]
Please send a new PR when you return to it.

**Pull request closed without merging**
