### PR TITLE
Fixed #26289 -- Enabled shell tab completion on systems using libedit.

### PR DESCRIPTION
**Pull request by saghul**
https://code.djangoproject.com/ticket/26289

### CODE REVIEW

**Comment by saghul** [comment]
Ticket: https://code.djangoproject.com/ticket/26289

**Comment by saghul** [comment]
The implementation has been shamelessly stolen from Python itself: https://github.com/python/cpython/blob/3.4/Lib/site.py#L402-L406

**Comment by timgraham** [comment]
Why doesn't Python's implementation suffice? Is this only needed on Python 2?

**Comment by saghul** [comment]
@timgraham I tested it with Python 3.4, and it should suffice, but somehow it doesn't. This was added to CPython in 3.4, so all earlier versions don't have it.

**Comment by timgraham** [comment]
I guess I'm not too happy to add untested, duplicated code without understanding the problem a bit better. I don't use Mac OS myself so not sure if I can help much.

**Comment by saghul** [comment]
It is tested: I tested it (any other person with OSX could give it a try to
confirm), and the code is the same as in CPython. Last, it's not
duplicated, as it's needed in Python < 3.4.

On Tue, Mar 1, 2016 at 4:09 PM, Tim Graham <notifications@github.com> wrote:

> I guess I'm not too happy to add untested, duplicated code without
> understanding the problem a bit better. I don't use Mac OS myself so not
> sure if I can help much.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/django/django/pull/6214#issuecomment-190760766>.
>



-- 
/Saúl
bettercallsaghul.com

**Comment by timgraham** [comment]
By "tested", I mean unit tests. Django master supports Python 2.7 and Python 3.4+, and I don't think we should be adding new features for Python 2.7 at this point.

**Comment by saghul** [comment]
I dug a bit deeper. `code.interact` does not inherit the module globals, but it does take a `local` dict, which Django already prepares. Because globals are not inherited, the new interactive interpreter does not have tab completion *in any Python version*.

Here is a simple test you can try which demonstrates the problem also on Linux: create a file with the following content:

~~~~
import code
code.interact()
~~~~

or just run:

~~~~
python3 -c "import code; code.interact()"
~~~~

And run it with Python 3 >= 3.4. The normal interactive interpreter does have tab completion, this one won't. That's why Django has to do it manually.

**Comment by jarshwah** [comment]
FWIW this is what I have in my own personal `.pythonrc` file on OSX:

```
    # above tries to import readline and rlcompleter and if successful:
    if 'libedit' in readline.__doc__:     # different bind libedit
        readline.parse_and_bind("bind ^I rl_complete")
    else:
        readline.parse_and_bind("tab: complete")
```

The change *looks* fine to me, but I'm struggling to test it properly because I try very very hard never to use the system python for development. I know I've been bitten by loss of tab complete before (http://stackoverflow.com/a/7116997/10583) so it'd be nice to include this in django proper.

**Comment by berkerpeksag** [comment]
If I remember correctly, I wrote the code in `Lib/site.py` so it looks good to me. I tested it on OS X and it works fine.

I'm not sure I understand the comment about `code.interact()`. It normally doesn't have anything to do with code completion (it's `rcompleter`'s duty).  `rcompleter.Completer()` uses `__main__.__dict__` by default as its namespace (which it includes globals, builtins etc.). And they are added to `imported_objects` implicitly by the `exec()` call in line 89.

**Comment by saghul** [comment]
> I'm not sure I understand the comment about code.interact(). It normally doesn't have anything to do with code completion (it's rcompleter's duty). rcompleter.Completer() uses __main__.__dict__ by default as its namespace (which it includes globals, builtins etc.). And they are added to imported_objects implicitly by the exec() call in line 89.

Django sets the completer for a local namespace, so `__main__.__dict__` is not used by rlcompleter: https://github.com/django/django/blob/master/django/core/management/commands/shell.py#L60-L62 and https://github.com/django/django/blob/master/django/core/management/commands/shell.py#L71

**Comment by timgraham** [comment]
merged in 6c33e7333336487a30dbd170c93b2f6e50133de7, thanks!

**Pull request closed without merging**
