### PR TITLE
Fixed #25108 -- Fixed a test which checks None content_type in ImageF…

### PR DESCRIPTION
**Pull request by double-y**
https://code.djangoproject.com/ticket/25108

### CODE REVIEW

**Comment by coldmind** [comment]
I think it is better to use mock to model this situation instead of fixing every time after Pillow registers MIME for image plugin without it.

**Comment by double-y** [comment]
I see. If I add `Image.register_mime(BmpImageFile.format, None)` in the beginning of the test, it passes.
It unregisters the MIME type of BmpImage during the test.
Is this better?

**Comment by coldmind** [comment]
@double-y 

```diff
diff --git a/tests/forms_tests/tests/test_fields.py b/tests/forms_tests/tests/test_fields.py
index bfc88d7..2ef6b8f 100644
--- a/tests/forms_tests/tests/test_fields.py
+++ b/tests/forms_tests/tests/test_fields.py
@@ -44,7 +44,7 @@ from django.forms import (
     Textarea, TextInput, TimeField, TypedChoiceField, TypedMultipleChoiceField,
     URLField, UUIDField, ValidationError, Widget, forms,
 )
-from django.test import SimpleTestCase, ignore_warnings
+from django.test import SimpleTestCase, ignore_warnings, mock
 from django.utils import formats, six, translation
 from django.utils._os import upath
 from django.utils.deprecation import RemovedInDjango110Warning
@@ -846,20 +846,26 @@ class FieldsTests(SimpleTestCase):
         """
         This also tests the situation when Pillow doesn't detect the MIME type
         of the image (#24948).
+        Need to use mock to prevent edition of test each time Pillow
+        adds it for image.
         """
-        f = ImageField()
+        with mock.patch('PIL.Image.MIME') as mocked_mime:
+            mocked_mime.get = mock.MagicMock(
+                return_value=None
+            )
+            f = ImageField()

-        img_path = os.path.dirname(upath(__file__)) + '/filepath_test_files/1x1.bmp'
-        with open(img_path, 'rb') as img_file:
-            img_data = img_file.read()
+            img_path = os.path.dirname(upath(__file__)) + '/filepath_test_files/1x1.bmp'
+            with open(img_path, 'rb') as img_file:
+                img_data = img_file.read()

-        img_file = SimpleUploadedFile('1x1.bmp', img_data)
-        img_file.content_type = 'text/plain'
+            img_file = SimpleUploadedFile('1x1.bmp', img_data)
+            img_file.content_type = 'text/plain'

-        uploaded_file = f.clean(img_file)
+            uploaded_file = f.clean(img_file)

-        self.assertEqual('BMP', uploaded_file.image.format)
-        self.assertIsNone(uploaded_file.content_type)
+            self.assertEqual('BMP', uploaded_file.image.format)
+            self.assertIsNone(uploaded_file.content_type)

     # URLField ##################################################################
```

But with that approach there is some side-effect, `.get` of `Image.MIME` isn't returning to previous state after mocking, so you'll need to complete this patch.

**Comment by coldmind** [comment]
Another approach without mock:

```diff
diff --git a/tests/forms_tests/tests/test_fields.py b/tests/forms_tests/tests/test_fields.py
index bfc88d7..caaeeda 100644
--- a/tests/forms_tests/tests/test_fields.py
+++ b/tests/forms_tests/tests/test_fields.py
@@ -847,19 +847,24 @@ class FieldsTests(SimpleTestCase):
         This also tests the situation when Pillow doesn't detect the MIME type
         of the image (#24948).
         """
-        f = ImageField()
+        from PIL.BmpImagePlugin import BmpImageFile
+        try:
+            Image.register_mime(BmpImageFile.format, None)
+            f = ImageField()

-        img_path = os.path.dirname(upath(__file__)) + '/filepath_test_files/1x1.bmp'
-        with open(img_path, 'rb') as img_file:
-            img_data = img_file.read()
+            img_path = os.path.dirname(upath(__file__)) + '/filepath_test_files/1x1.bmp'
+            with open(img_path, 'rb') as img_file:
+                img_data = img_file.read()

-        img_file = SimpleUploadedFile('1x1.bmp', img_data)
-        img_file.content_type = 'text/plain'
+            img_file = SimpleUploadedFile('1x1.bmp', img_data)
+            img_file.content_type = 'text/plain'

-        uploaded_file = f.clean(img_file)
+            uploaded_file = f.clean(img_file)

-        self.assertEqual('BMP', uploaded_file.image.format)
-        self.assertIsNone(uploaded_file.content_type)
+            self.assertEqual('BMP', uploaded_file.image.format)
+            self.assertIsNone(uploaded_file.content_type)
+        finally:
+            Image.register_mime(BmpImageFile.format, "image/bmp")

     # URLField #################################################################
```

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
merged in a2b999dfcac9bc92513a36ec6b3033ded1561c66, thanks!

**Pull request closed without merging**
