### PR TITLE
Simplified various built-in templates.

### PR DESCRIPTION
**Pull request by ngnpope**
Please consider each of these commits separately.

Regarding the `|length_is` filter: I wonder whether we ought to deprecate and remove this as it is typically only used in `{% if %}` tags - I searched in GitHub - and `{% if sized|length == 1 %}` is clearer than `{% if sized|length_is:'1' %}`. I'm presuming that this filter dates back to before `==` when the, now deprecated, `{% ifequal %}` was widely used and this was a shortcut...

### CODE REVIEW

**Comment by ngnpope** [comment]
👋🏻 @carltongibson and @felixxm I've rebased this one.

Regarding deprecation of `|length_is` as mentioned above, that can be addressed in a separate PR. The admonition will do for now here. Note that, with the last commit in this series, it is no longer used within Django itself.

**Review by carltongibson — COMMENTED** [review]
Hey @ngnpope — thanks for this. Sorry it's taken so long to review. Looked at it lots of times but… 😬

I think we should probably drop d12860e3237e5269d785ccb4fb5f77f6704ea78e and fd16e4cb7eadf70c8942c4f902e0c5fcc504c929. 

* I suspect the first will lead to _I'm getting DEBUG logging errors_ issues, which folks don't like. 
* I think the second would need the deprecation — I don't like the note as a stopping point TBH. (Mood: I'm not sure about the deprecation itself... — the DTL, and provided tags/filters are quite stable at the moment: absent a bigger push for changes there — which sure, let's have it! — I'm not sure a lone deprecation is worth it — but you can push it if you feeling that yourself!)   

Beyond that I think we can take the rest (with a final 👀) as a single cleanup.

**Comment by ngnpope** [comment]
Cool. I'll pick this up next week.

**Comment by ngnpope** [comment]
> * I suspect the first will lead to _I'm getting DEBUG logging errors_ issues, which folks don't like.

Could you elaborate? _(I'll park that commit in another branch anyway so that we can progress the rest.)_

> * I think the second would need the deprecation — I don't like the note as a stopping point TBH. (Mood: I'm not sure about the deprecation itself... — the DTL, and provided tags/filters are quite stable at the moment: absent a bigger push for changes there — which sure, let's have it! — I'm not sure a lone deprecation is worth it — but you can push it if you feeling that yourself!)

I'll spin this separately as the proper deprecation as we can see how it looks.

**Comment by ngnpope** [comment]
Chopped the two commits and rebased. Commits can be squashed on merge. ✔️

**Comment by felixxm** [comment]
> Could you elaborate? _(I'll park that commit in another branch anyway so that we can progress the rest.)_

As far as I'm aware, this:
```
{% for app in app_list %}
```
will start to raise DEBUG logging errors when `app_list` is `None`.

**Comment by felixxm** [comment]
@ngnpope Thanks :+1:

**Pull request merged**
