### PR TITLE
Fixed #35891 -- Confirmed support for GDAL 3.10.

### PR DESCRIPTION
**Pull request by smithdc1**
ticket-35891

### CODE REVIEW

**Review by claudep — APPROVED** [review]
:+1:

**Review by pauloxnet — APPROVED** [review]

**Comment by pauloxnet** [comment]
LGTM

**Comment by nessita** [comment]
@smithdc1 Thank you for this work! :star2: 
I'll merge now but I had this question: how is this support usually confirmed? Did you install the newest GDAL locally and ran the tests? Do we update CI at some point to keep "ensuring" this compatibility?

**Comment by smithdc1** [comment]
Hi @nessita hope all is well. 

I usually test this locally. Osgeo4w makes installing the libraries on windows straight forward. 

However in this case 3.10 isn't yet available (I'm not sure why). To test this patch I used a github codespace as it has conda available and the packages are available from conda-forge so I don't have to build them myself. 

I like using a code space for this as i can just delete it when I get something wrong. 

In CI, we are using the version which comes with that Linux distribution. I think this means were testing the ~oldest supported version. I think that's OK as a full matrix of all supported versions would be huge.

**Comment by nessita** [comment]
> Hi @nessita hope all is well.
> 
> I usually test this locally. Osgeo4w makes installing the libraries on windows straight forward.
> 
> However in this case 3.10 isn't yet available (I'm not sure why). To test this patch I used a github codespace as it has conda available and the packages are available from conda-forge so I don't have to build them myself.
> 
> I like using a code space for this as i can just delete it when I get something wrong.
> 
> In CI, we are using the version which comes with that Linux distribution. I think this means were testing the ~oldest supported version. I think that's OK as a full matrix of all supported versions would be huge.

Thank you so much for the details @smithdc1. Do you think there would be a way to test the versions we support using Github actions, perhaps with a windows base and Osgeo4w as you use? Would that be worth effort/resources?

**Comment by claudep** [comment]
IMO, testing all combinations of external libs would be endless and too much resource-consuming. What we could do however is adding a CI config using the latest Ubuntu with PostGIS (maybe on GitHub?). This wouldn't test the very latest versions, but at least a recent version of GIS libs.

**Comment by nessita** [comment]
> IMO, testing all combinations of external libs would be endless and too much resource-consuming. What we could do however is adding a CI config using the latest Ubuntu with PostGIS (maybe on GitHub?). This wouldn't test the very latest versions, but at least a recent version of GIS libs.

I like this idea. @smithdc1 would you have any capacity to make a PR for this?

**Comment by smithdc1** [comment]
Hi @nessita -- I'm sorry, I don't have capacity to look at this any time soon.

**Comment by nessita** [comment]
@smithdc1 @claudep I've given the "latest postgis in GHA" a try and this is the result: https://github.com/nessita/django/pull/25

It works, but using latest dev versions show a test failure:
```
2025-06-11T18:47:38.1022505Z ======================================================================
2025-06-11T18:47:38.1025719Z ERROR: test_relate_lookup (gis_tests.geoapp.tests.GeoLookupTest.test_relate_lookup)
2025-06-11T18:47:38.1026471Z Testing the 'relate' lookup type.
2025-06-11T18:47:38.1027301Z ----------------------------------------------------------------------
2025-06-11T18:47:38.1027861Z Traceback (most recent call last):
2025-06-11T18:47:38.1039702Z   File "/opt/hostedtoolcache/Python/3.13.4/x64/lib/python3.13/unittest/case.py", line 58, in testPartExecutor
2025-06-11T18:47:38.1040548Z     yield
2025-06-11T18:47:38.1041196Z   File "/opt/hostedtoolcache/Python/3.13.4/x64/lib/python3.13/unittest/case.py", line 651, in run
2025-06-11T18:47:38.1041909Z     self._callTestMethod(testMethod)
2025-06-11T18:47:38.1042275Z     
2025-06-11T18:47:38.1042977Z   File "/opt/hostedtoolcache/Python/3.13.4/x64/lib/python3.13/unittest/case.py", line 606, in _callTestMethod
2025-06-11T18:47:38.1043996Z     if method() is not None:
2025-06-11T18:47:38.1044341Z     ^^^^^^^^^^^^^^^
2025-06-11T18:47:38.1045043Z   File "/home/runner/work/django/django/django/test/testcases.py", line 1550, in skip_wrapper
2025-06-11T18:47:38.1045811Z     return test_func(*args, **kwargs)
2025-06-11T18:47:38.1046236Z     ^^^^^^^
2025-06-11T18:47:38.1046958Z   File "/home/runner/work/django/django/tests/gis_tests/geoapp/tests.py", line 581, in test_relate_lookup
2025-06-11T18:47:38.1048198Z     "Lawrence", City.objects.get(point__relate=(ks.poly, within_mask)).name
2025-06-11T18:47:38.1048574Z     ^^^^^^^^^^^
2025-06-11T18:47:38.1049113Z   File "/home/runner/work/django/django/django/db/models/manager.py", line 87, in manager_method
2025-06-11T18:47:38.1049716Z     return getattr(self.get_queryset(), name)(*args, **kwargs)
2025-06-11T18:47:38.1050129Z     ^^^^^^^
2025-06-11T18:47:38.1050606Z   File "/home/runner/work/django/django/django/db/models/query.py", line 635, in get
2025-06-11T18:47:38.1051034Z     raise self.model.DoesNotExist(
2025-06-11T18:47:38.1051350Z     ^^^^^^^^^^^
2025-06-11T18:47:38.1051661Z gis_tests.geoapp.models.City.DoesNotExist: City matching query does not exist.
2025-06-11T18:47:38.1051967Z 
2025-06-11T18:47:38.1052164Z ----------------------------------------------------------------------
2025-06-11T18:47:38.1052459Z Ran 18772 tests in 253.360s
2025-06-11T18:47:38.1052599Z 
2025-06-11T18:47:38.1052716Z FAILED (errors=1, skipped=624, expected failures=7)
```

Yes, we could NOT use dev and instead use a more stable versions, but the debian-based options that we have are either:
 * [postgis/postgis:17-3.5⁠](https://registry.hub.docker.com/r/postgis/postgis/tags?page=1&name=17-3.5) with postgres 17 and postgis 3.5.2 (but geos=3.9, gdal=3.2, proj=7.2, and sfcgal=1.3.9)
 * [postgis/postgis:17-master⁠](https://registry.hub.docker.com/r/postgis/postgis/tags?page=1&name=17-master) with postgres 17 and postgis dev
 
There are [alpine images](https://hub.docker.com/r/postgis/postgis/) with a middle ground (postgis 3.5.3 and geos=3.13.1, gdal=3.10.2, proj=9.6.0, and sfcgal=2.0.0) so perhaps those are the winners?

**Comment by nessita** [comment]
EDIT: when using the postgis/postgis:17-3.5-alpine image (stable 3.5 postgis, no dev) and `geos=3.13.1, gdal=3.10.2, proj=9.6.0, and sfcgal=2.0.0` the test above keeps failing. See [run logs](https://productionresultssa9.blob.core.windows.net/actions-results/18353b33-f0e9-4c5d-a801-2ba71cc65722/workflow-job-run-0c3855bb-c2a9-563f-a1de-eeec640449d6/logs/job/job-logs.txt?rsct=text%2Fplain&se=2025-06-11T19%3A54%3A38Z&sig=93GuaAZBTDIe4ib1CJtg10Qt2sVHsK0wVxTHM1aiB2Y%3D&ske=2025-06-12T07%3A15%3A35Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-06-11T19%3A15%3A35Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-05-05&sp=r&spr=https&sr=b&st=2025-06-11T19%3A44%3A33Z&sv=2025-05-05).

Installed versions:
```
2025-06-11T19:33:15.3972504Z  POSTGIS="3.5.3 0" [EXTENSION] PGSQL="170" GEOS="3.13.1-CAPI-1.19.2" PROJ="9.6.0 NETWORK_ENABLED=OFF URL_ENDPOINT=https://cdn.proj.org USER_WRITABLE_DIRECTORY=/var/lib/postgresql/.local/share/proj DATABASE_PATH=/usr/share/proj/proj.db" (compiled against PROJ 9.6.0) LIBXML="2.13.8" LIBJSON="0.18" LIBPROTOBUF="1.5.2" WAGYU="0.5.0 (Internal)" TOPOLOGY
```

**Comment by smithdc1** [comment]
Hi @nessita -- We still need to add support for PostGIS 3.5, see [ticket #36009](https://code.djangoproject.com/ticket/36009). This is the cause of the failing test you are seeing. 

As it happens, I'd also started to circle back round to this. I was exploring if we could use conda to install the geospatial libraries as that would allow specific versions. The versions available in conda-forge are also usually very up-to-date. Something like [this](https://github.com/smithdc1/django/pull/6)?

I've not yet explored how using conda to install the geospatial libraries works along side a PostgreSQL service. (I did go down the rabbit hole of getting PostgreSQL installed by conda, but the build that comes with conda-forge doesn't have all the features [1](https://github.com/conda-forge/postgresql-feedstock/issues/205) enabled we need).

**Comment by nessita** [comment]
> Hi @nessita -- We still need to add support for PostGIS 3.5, see [ticket #36009](https://code.djangoproject.com/ticket/36009). This is the cause of the failing test you are seeing.

Thank you for the pointer! Tough my point was that PostGIS 3.5 does not seem to be the issue, since for the "latest stable" docker image, our tests pass. So, to recap, these two provided docker images use PostGIS 3.5 but they vary on geos, gdal, and proj versions:

* [postgis/postgis:17-3.5⁠](https://registry.hub.docker.com/r/postgis/postgis/tags?page=1&name=17-3.5): Tests **OK**, geos=3.9, gdal=3.2, proj=7.2. We could use :100: 
* [postgis/postgis:17-3.5-alpine⁠](https://registry.hub.docker.com/r/postgis/postgis/tags?page=1&name=17-3.5-alpine): Tests **1 ERROR**, geos=3.13.1, gdal=3.10.2, proj=9.6.0. Would not use, yet.

This other image provides PostGIS dev version (I would not use it), and we get the same single failure:
* [postgis/postgis:17-master⁠](https://registry.hub.docker.com/r/postgis/postgis/tags?page=1&name=17-master): Would not use.

> As it happens, I'd also started to circle back round to this. I was exploring if we could use conda to install the geospatial libraries as that would allow specific versions. The versions available in conda-forge are also usually very up-to-date. Something like [this](https://github.com/smithdc1/django/pull/6)?
> I've not yet explored how using conda to install the geospatial libraries works along side a PostgreSQL service. (I did go down the rabbit hole of getting PostgreSQL installed by conda, but the build that comes with conda-forge doesn't have all the features [1](https://github.com/conda-forge/postgresql-feedstock/issues/205) enabled we need).

Thanks for explaining this! I'm not very familiar with Conda, but it's definitely tempting, your GHA experiment makes a good case for it.

How about we lean toward an incremental approach: stick with Docker for the PostGIS service (using the image that has the tests passing right now), and use the latest Ubuntu runner in GitHub Actions for running the test suite, at least for now. That should give us reasonably modern coverage, and more importantly, it keeps things consistent with our current workflows. Introducing a second toolchain for dependency management might add complexity and overhead we don't need just yet (but see below).

If we manage to fix the failing test, a good next step would be to switch to the Alpine-based Docker image, which has newer versions of the geospatial libraries. I will re-purpose my PR for to use the image where tests passes and propose against Django `main`. We could then add more to this new `GeoDjango` workflow.

PS: at this time we may need to move our conversation to a forum post? Or to a ticket? What do you think?

One thing I'm still unsure about is whether we actually need newer geospatial library versions on the system running the test suite, or just on the DB side. If it turns out we need them on both, then the trade-offs might start to look different.

**Comment by nessita** [comment]
Moved the conversation to https://forum.djangoproject.com/t/testing-newer-geospatial-libs/41404.

**Pull request merged**
