### PR TITLE
Updates for branching stable/3.2.x

### PR DESCRIPTION
**Pull request by carltongibson**
* Update man page 
* Remove empty sections from release notes. 

Merge after #13886, #12553 and #13891.

### CODE REVIEW

**Review by felixxm — APPROVED** [review]
@carltongibson Thanks :+1:

We have ["django.contrib.admin"](https://docs.djangoproject.com/en/dev/releases/3.2/#id1) in the _"Backwards incompatible changes in 3.2"_, so I would move there related changes:
https://github.com/django/django/blob/76ae6ccf859bf677bfcb5b992f4c17f5af80ae9d/docs/releases/3.2.txt#L720-L726

**Comment by carltongibson** [comment]
@felixxm im away from the computer... could you push that so I can see when I get back? Thanks 🙏

**Comment by felixxm** [comment]
> @felixxm im away from the computer... could you push that so I can see when I get back? Thanks pray

Pushed.

**Comment by carltongibson** [comment]
🦸‍♂️

**Comment by carltongibson** [comment]
Yes, makes sense, perfect. Thanks @felixxm

**Pull request merged**
