### PR TITLE
Fixed #35712 -- Prevented Q.check() from leaving the connection in an unusable state.

### PR DESCRIPTION
**Pull request by sarahboyce**
Taken from https://github.com/django/django/pull/18522 (with very minor tweaks - had no permissions to push)

### CODE REVIEW

**Comment by ulgens** [comment]
Hey @sarahboyce , @a-p-f 👋🏻 

I found this PR after realizing that updating our project to Django 5.2 causes a significant increase in database query counts for some endpoints. The Trac issue defines the problem as 

> When a model uses a CheckConstraint with RawSQL, trying to save a ModelForm for that model inside a transaction.atomic() block fails.

but the PR applies the fix to all constraints, regardless of them not having RawSQL. Was this expected/intentional?

**Comment by charettes** [comment]
@ulgens [this was discussed slightly on the forum](https://forum.djangoproject.com/t/potential-performance-issue-django-5-2/41418/1). Do you happen to be using atomic views or run model validation in a transaction?

We could revert or adjust the logic to deal with `RawSQL` differently but it'd be great to learn which kind of setups are running into issues here.

**Comment by ulgens** [comment]
@charettes Thanks for the link. Let me try to summarize the usecase:

* We use multiple check constraints per model, to ensure integrity with state machine transitions.
* All checks have their custom violation message.
* We automatically convert Django's validation errors to DRF Validation errors.
* We call model's `full_clean` in `save`, so we can have the violation errors as validation errors, not integrity errors; to have the same result that admin generates, but without depending on a form class.
* In the end, check constraints and their violation messages are automatically used as API validations and error messages.

With this setup in place, updating to 5.2 adds 6-8 extra queries to each endpoint call. In some extreme cases, extra query count is 15+ and/or the final query count doubles the original query count. We are not using any raw sql in any of the constraints.

**Comment by charettes** [comment]
Thanks for sharing!

> We call model's full_clean in save, so we can have the validation errors as validation errors, not integrity errors; to have the same result that admin generates, but without depending on a form class.

Do you happen to wrap your DRF views in `transaction.atomic` or [use `ATOMIC_REQUESTS`](https://docs.djangoproject.com/en/5.2/ref/settings/#std-setting-DATABASE-ATOMIC_REQUESTS). No extra queries (`SAVEPOINT` mostly) should be performed unless you are running model validation within a transaction.

**Comment by ulgens** [comment]
> Do you happen to wrap your DRF views in transaction.atomic or [use ATOMIC_REQUESTS](https://docs.djangoproject.com/en/5.2/ref/settings/#std-setting-DATABASE-ATOMIC_REQUESTS)

ı checked the views and it seems wrapping with `transaction.atomic()` is a common case between affected views. Are those queries useful in transactions even if there is no raw sql usage?

**Comment by charettes** [comment]
Thanks for the details.

Here's the situation at play here

1. It is allowed to use `RawSQL` when defining `CheckConstraint` and `UniqueConstraint` and has been since their introduction
2. In order to implement `Constraint.validate` references to fields must be replaced by values associated with the instance but in the case of `RawSQL` it is an opaque abstraction to the ORM
3. Because the SQL defining the constraint cannot be safely interpreted it most likely will result in a constraint validation which would leave an ungoing transaction unusable.

Now given this patch only tailors to `RawSQL` usage in constraints when performing validation (which will most likely fail anyway) an penalize the usage of `transaction.atomic` view wrapping (which is a more established pattern) I think we should revert its current form and consider either

1. Revert this patch and force users of `RawSQL` in constraints to do their own transaction wrapping.
2. Adapting the logic to only wrap in a transaction when `RawSQL` is used
3. Consider skipping validation entirely when `RawSQL` is used [as we document we do](https://github.com/django/django/blob/ac2d907f459b2cb7ddea7451764e7020ffee08e6/django/db/models/constraints.py#L176-L185) instead of [running the more often than other broken SQL and emitting a warning for it](https://github.com/django/django/blob/ac2d907f459b2cb7ddea7451764e7020ffee08e6/django/db/models/query_utils.py#L150).

Either of 1. and 2. sound possible for a 5.2.x backport but 3. would need to wait for 6.x at least.

**Comment by ulgens** [comment]
@charettes Thanks for your time and effort you put into explaining the situation 🌻

My expected solution to the issue was what you defined as option 2. Do you think it's feasible?

**Comment by charettes** [comment]
@ulgens the problem with 2. is _how_ it should be implemented.

While `any(isinstance(expr, RawSQL) for expr in condition.flatten())` works to identify if an expression is potentially problematic there are usage of `Q.check(...)` that are perfectly valid; it's the usage of `RawSQL` in constraints that require field reference replacement (which are hardcoded as column references in `RawSQL`) that are problem to its `Q.check(...)` usage.

I guess a potential solution could be to have `Constraint.validate` overrides perform the `RawSQL` introspection themselves and wrap their `Q.check` accordingly but that poses all sorts of problems because [you can't catch exceptions in an atomic block](https://docs.djangoproject.com/en/5.2/topics/db/transactions/#controlling-transactions-explicitly) which means you'd have to always explicitly create a savepoint and roll it back via `savepoint_rollback`

2. is doable but a bit involved which is why I lean towards 1. to revert the changes which had unintended consequences and actually [skip validation when `RawSQL` is used like we warn about](https://github.com/django/django/blob/ac2d907f459b2cb7ddea7451764e7020ffee08e6/django/db/models/constraints.py#L176-L185).

```diff
diff --git a/django/contrib/postgres/constraints.py b/django/contrib/postgres/constraints.py
index 90441a51ce..2349e0dea3 100644
--- a/django/contrib/postgres/constraints.py
+++ b/django/contrib/postgres/constraints.py
@@ -195,8 +195,12 @@ def validate(self, model, instance, exclude=None, using=DEFAULT_DB_ALIAS):
             rhs_expression = expression.replace_expressions(replacements)
             if hasattr(expression, "get_expression_for_validation"):
                 expression = expression.get_expression_for_validation()
+            elif self._expression_contains_raw_sql(expression):
+                return
             if hasattr(rhs_expression, "get_expression_for_validation"):
                 rhs_expression = rhs_expression.get_expression_for_validation()
+            elif self._expression_contains_raw_sql(rhs_expression):
+                return
             lookup = PostgresOperatorLookup(lhs=expression, rhs=rhs_expression)
             lookup.postgres_operator = operator
             lookups.append(lookup)
@@ -209,6 +213,8 @@ def validate(self, model, instance, exclude=None, using=DEFAULT_DB_ALIAS):
                 raise ValidationError(
                     self.get_violation_error_message(), code=self.violation_error_code
                 )
+        elif self._expression_contains_raw_sql(self.condition):
+            return
         else:
             # Ignore constraints with excluded fields in condition.
             if exclude and self._expression_refs_exclude(
diff --git a/django/db/models/constraints.py b/django/db/models/constraints.py
index ae2709abb8..494e15ad74 100644
--- a/django/db/models/constraints.py
+++ b/django/db/models/constraints.py
@@ -60,6 +60,12 @@ def _expression_refs_exclude(cls, model, expression, exclude):
                 return True
         return False

+    @staticmethod
+    def _expression_contains_raw_sql(expression):
+        if isinstance(expression, F):
+            return False
+        return any(isinstance(expr, RawSQL) for expr in expression.flatten())
+
     def validate(self, model, instance, exclude=None, using=DEFAULT_DB_ALIAS):
         raise NotImplementedError("This method must be implemented by a subclass.")

@@ -173,7 +179,7 @@ def check(self, model, connection):
             condition = self.condition
             if isinstance(condition, Q):
                 references.update(model._get_expr_references(condition))
-            if any(isinstance(expr, RawSQL) for expr in condition.flatten()):
+            if self._expression_contains_raw_sql(condition):
                 errors.append(
                     checks.Warning(
                         f"Check constraint {self.name!r} contains RawSQL() expression "
@@ -205,6 +211,8 @@ def remove_sql(self, model, schema_editor):
         return schema_editor._delete_check_sql(model, self.name)

     def validate(self, model, instance, exclude=None, using=DEFAULT_DB_ALIAS):
+        if self._expression_contains_raw_sql(self.condition):
+            return
         against = instance._get_field_expression_map(meta=model._meta, exclude=exclude)
         # Ignore constraints with excluded fields in condition.
         if exclude and self._expression_refs_exclude(model, self.condition, exclude):
@@ -630,6 +638,8 @@ def validate(self, model, instance, exclude=None, using=DEFAULT_DB_ALIAS):
             for expr in self.expressions:
                 if hasattr(expr, "get_expression_for_validation"):
                     expr = expr.get_expression_for_validation()
+                elif self._expression_contains_raw_sql(expr):
+                    return
                 rhs = expr.replace_expressions(replacements)
                 condition = Exact(expr, rhs)
                 if self.nulls_distinct is False:
@@ -659,6 +669,8 @@ def validate(self, model, instance, exclude=None, using=DEFAULT_DB_ALIAS):
                     self.get_violation_error_message(),
                     code=self.violation_error_code,
                 )
+        elif self._expression_contains_raw_sql(self.condition):
+            return
         else:
             # Ignore constraints with excluded fields in condition.
             if exclude and self._expression_refs_exclude(
diff --git a/django/db/models/query_utils.py b/django/db/models/query_utils.py
index 3e644a3c26..a372a0f949 100644
--- a/django/db/models/query_utils.py
+++ b/django/db/models/query_utils.py
@@ -10,10 +10,9 @@
 import inspect
 import logging
 from collections import namedtuple
-from contextlib import nullcontext

 from django.core.exceptions import FieldError
-from django.db import DEFAULT_DB_ALIAS, DatabaseError, connections, transaction
+from django.db import DEFAULT_DB_ALIAS, DatabaseError, connections
 from django.db.models.constants import LOOKUP_SEP
 from django.utils import tree
 from django.utils.functional import cached_property
@@ -138,14 +137,8 @@ def check(self, against, using=DEFAULT_DB_ALIAS):
         else:
             query.add_q(self)
         compiler = query.get_compiler(using=using)
-        context_manager = (
-            transaction.atomic(using=using)
-            if connection.in_atomic_block
-            else nullcontext()
-        )
         try:
-            with context_manager:
-                return compiler.execute_sql(SINGLE) is not None
+            return compiler.execute_sql(SINGLE) is not None
         except DatabaseError as e:
             logger.warning("Got a database error calling check() on %r: %s", self, e)
             return True
```

**Comment by sarahboyce** [comment]
@ulgens would you mind opening a ticket? It would be great to have a test which can capture an additional query after this commit. Happy to have a revert :+1:

**Pull request merged**
