### PR TITLE
Refs #23919 - Removed decorator - python_2_unicode_compatible

### PR DESCRIPTION
**Pull request by srinivasreddy**

### CODE REVIEW

**Comment by timgraham** [comment]
The decorator should remain for backwards-compatibility.

**Comment by srinivasreddy** [comment]
Just wondering, is it for the same reason we keep six.py in utils?

**Comment by timgraham** [comment]
Yes, otherwise third-party apps that want to continue supporting Python 2 will have to adapt needlessly.

**Comment by srinivasreddy** [comment]
Atleast in the case of decorator, we could add warning message it will be removed or deprecated in the future versions. However, I am not sure warnings module usage policy in Django project.

**Comment by timgraham** [comment]
I think it's unnecessary overhead to deprecate when we could just remove it when Python 2 is sufficiently old and obsolete, but I'll likely to write to the django-developers mailing list about it.

**Pull request closed without merging**
