### PR TITLE
Fixed #29069 -- Ensure static file serving sends the request_finished signal

### PR DESCRIPTION
**Pull request by orf**
Ticket: https://code.djangoproject.com/ticket/29069

This is just exploring what a fix would look like, and seeing if all the tests pass with the proposed changes. There could be wider implications of this, so not sure if we really should do this or not.

### CODE REVIEW

**Comment by orf** [comment]
Hey @auvipy, this was just an experimental PR, and as per [a comment in the ticket](https://code.djangoproject.com/ticket/29069#comment:5) it might not be sufficient.

**Comment by timgraham** [comment]
How do you want to proceed, Tom?

**Comment by orf** [comment]
I had another experiment today. As far as I can see we can pick only one:

1. Support `sendfile` and other efficient means of sending static files
2. Have the response ended signal fire

The WSGI spec [has a section on this](https://www.python.org/dev/peps/pep-0333/#optional-platform-specific-file-handling). I'll try and summarize what I have found:

We must give an iterable to `wsgi.file_wrapper`, which can optionally be a file like object. We currently pass the underlying file-like object given to the `FileResponse`, which is fine, but when it's `close()` method is called (or it finishes iterating) then the `FileResponse.close()` is not called. The `wsgi.file_wrapper` can try and detect if the file is a real file and if so use more efficient streaming methods.

If we pass the entire `FileResponse` to `wsgi.file_wrapper` then we do not get fast streaming because the response is not an actual file, but the `close()` method is called

If we give the underlying user-controlled value the `FileResponse` is given, we may get streaming but will not get the `FileResponse.close()` called.

I can see two ways to hack around this:

1. Return a mocked instance that wraps the user-supplied value, with a `close()` method that calls `FileResponse.close()`. This is tricky because it *cannot* have attributes or methods like `filenum()` if the *underlying* value does not, because `hasattr()` will be True and things will break.

2. Somehow inject our own logic into the values `close()` method and pass that to `wsgi.wrapper`...

```
old_close = value.close
function fake_close(*args, **kwargs):
    old_close(*args, **kwargs)
    our_response.close()   # send signals
value.close = fake_close 
```

**Comment by timgraham** [comment]
I guess the discussion should move to the ticket. Maybe it's possible to makes sense to omit the `request_started` signal for static files (if possible)?

**Comment by felixxm** [comment]
Closing due to inactivity.

**Pull request closed without merging**
