### PR TITLE
Fixed #31341 -- Doc'd minimal gettext version with ES6 template strings support.

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by cedeber** [comment]
Hi. gettext 0.20.x seems still buggy with templates strings. Looks like the 0.21 should fix that. See [gettext bug report](https://savannah.gnu.org/bugs/?56678). Thanks.

**Comment by claudep** [comment]
Should we mention `the future gettext 0.21`  now and update the docs when it is released? @felixxm, what wording would you suggest?

**Comment by claudep** [comment]
Or maybe just wait for the next gettext release before updating the documentation…

**Comment by felixxm** [comment]
@claudep I'm not sure, we can wait few years for `gettext 0.21` :thinking:  `#56678` is a bug in a new feature so they can release `0.20.2` instead of `0.21`. IMO the current wording is fine, because `gettext` added official support for JavaScript template literals in `0.20`, bugs in their implementation shouldn't impact our docs. We can adjust it later after the next `gettext` release.

**Comment by cedeber** [comment]
In the [gettext log](https://git.savannah.gnu.org/gitweb/?p=gettext.git;a=blob;f=NEWS;h=fdcc14e2d757ffef8983b840cd638d4d137c55a9;hb=HEAD) 0.21 is from December 2019, but not yet released. No ideas why.

**Comment by felixxm** [comment]
@cedeber Thanks for sharing this source. In that case I think we can mention unreleased version of `gettext`, e.g.:
```
JavaScript template strings need ``gettext`` 0.21+.
```

**Pull request merged**
