### PR TITLE
Fixed misplaced period in translatable literal.

### PR DESCRIPTION
**Pull request by ramiro**
Thanks to translator Vláďa Macek (@tottle) who reported this on Transifex.

### CODE REVIEW

**Comment by felixxm** [comment]
@ramiro Thanks but it's not a typo, see [discussion](https://github.com/django/django/pull/11281#discussion_r278580862).

**Comment by ramiro** [comment]
Thanks for the quick reply @felixxm !

I know about the English rule as discussed in the PR you linked in and I suspected it could be the case.  But (and this is something which was also mentioned there) it's inconsistent with the rest of similar literals, the only one having the period inside the quotes is this one the "Deleted" case.

I can work on a PR ... or it would be highly disruptive for translators have this changed at this point for all these literals of the 3.0 relaase cycle, the ideal time would have been as part of #11291 

What do you think?

**Comment by felixxm** [comment]
Agreed, consistency is important, we should change other messages. IMO this should go only to master (3.1) because we don't want to create an extra work for documentation translators.

\cc @carltongibson

**Comment by carltongibson** [comment]
> \cc @carltongibson

Ah, right, yes. Well I'm British, so I think the full-stop should go outside the quotation mark anyway... 😀 — but, yes, I think that is the rule in American English for this to be the case... 

What's interesting from the discussion linked is that multiple reviewers felt it was wrong. 
Grammar rules are meant to codify actual practice, not be prior to it. I would be open to at least discussion of whether we could choose a different style, for reasons of logical consistency over national custom. 

String freeze is officially Nov 18th but happy to say this can be postponed to v3.1 if it would cause undue work.

**Pull request closed without merging**
