### PR TITLE
Fixed #27012 -- Removed nested_view() call to setup_test_environment().

### PR DESCRIPTION
**Pull request by cjerdonek**

### CODE REVIEW

**Comment by timgraham** [comment]
It would be better to make two commits since the docstring changes are unrelated to the bug fix. Maybe you'd want to also make some documentation edits for [setup_test_environment()](https://docs.djangoproject.com/en/dev/topics/testing/advanced/#django.test.utils.setup_test_environment).

**Comment by cjerdonek** [comment]
> It would be better to make two commits since the docstring changes are unrelated to the bug fix. 

@timgraham Should all of the docstring changes go in a separate commit, or just the ones affecting the "bullets"? The last sentence being added in the docstring is related because it says not to do what is being fixed.

Should the documentation edits be in the commit with the code change, or with the commit containing the docstring changes affecting the bullets?

**Comment by timgraham** [comment]
commit 1: code changes, commit 2: docstring + docs

**Comment by cjerdonek** [comment]
Updated. I will make a separate PR for the docstring + docs. Would I need to create a separate ticket or somehow reference the same one?

**Comment by timgraham** [comment]
For just some small edits a ticket probably isn't necessary.

**Pull request merged**
