### PR TITLE
Contributing docs

### PR DESCRIPTION
**Pull request by gabbyprecious**
Worked on the index and new contributors pages
Deleted previous commits
Worked on changes required by Carlton

### CODE REVIEW

**Comment by carltongibson** [comment]
Hey @gabbyprecious — thanks for this — looks good. I'll go over it again in the morning. 👍

**Comment by smithdc1** [comment]
I'm not sure if it's appropriate to include here or how to explain it succinctly but there is something here about knowledge of new vs regular contributor. It's the point I've heard Carlton make when he calls folks 'world experts'. 

The point is that if a new person reads an old (any?) ticket they know more about this than anyone else in the world. It will be not obvious even to regular contributor, if it was it would have been fixed by now. There is a trap here where a new contributor will ask for help and ask questions like 'what do you think here'. It's a perfectly reasonable question but unlikely to get much of a response, as it's effectively asking someone to give up their own time to fix a ticket that you are interested in. It has taken me a _long_ time to understand this! (I'm sorry and forever thankful to those who have helped)

I think there are two things here for the docs are we should give new contributors some more confidence, and to help them ask better questions.

Final comment is I think about personal development. If someone is keen to contribute in a specific area, then there will be packages in the wider ecosystem which are smaller in scope but still need help. I could go contribute on that package for a bit to help understand knowledge of that area of Django (e.g. I contributed to a forms package first, then when I came to Django I had an understanding of how forms worked). But I'm not sure we should be pointing folk elsewhere here...

**Comment by carltongibson** [comment]
Hey @smithdc1 — those are good thoughts. Fancy sketching some suggestions? (We can iterate.) 

Hey @gabbyprecious — I rebased (updated to the latest `master`) and squashed the two commits, and pushed so very tiny cosmetic changes. 

To get your local branch back in sync you can do two things: 

(Assuming the remote for your fork is called `origin`, but it might be called `fork` or ...)

1. Create a new branch from `origin/contributing_docs`. (You can also delete the current local fork)
2. Reset your local branch (I assume `contributing_docs` to the remote)...

    git fetch origin
    git reset --hard origin/contributing_docs

This gets the changes and then sets your branch to be at the same commit as origin/contributing_docs (the remote branch).

**Comment by gabbyprecious** [comment]
Hi @carltongibson I've done this, I will making adding a commit before the week runs out and wil working more on this, durimg the holidays. Thank you very much

**Comment by carltongibson** [comment]
Hey @gabbyprecious Super. I was moving house last week, so had very little capacity, but you're on my list. 👍

**Review by carltongibson — COMMENTED** [review]
Hi @gabbyprecious — right, sorry for the delay! Getting 3.2a1 out the door cost me some — now I'm finally back with you. 

How's your capacity? Are you up for working together to make some improvements here? 
I have some initial thoughts now, and we can communicate to flesh out ideas. 

I think we should break down our steps. To begin lets focus on `new-contributors.txt` and the flow from there. 

Screenshot 2021-02-02 at 11 56 23

Here: 

* The link to the tutorial at the top is good. I think we can change the _Basic tools and workflow_ header to something like "Getting started". 
* We should also link to the Writing Code index page. `writing-code.txt`. "If you're looking for a reference for..." 
* And say this page is for general advice once you're set up and ready to go. 

Let's assume for now users can get this far from `index.html`. We want to guide them to the tutorial, or the reference (if they want something harder). 

We can then review the text further down and add a paragraph touching @smithdc1's point that you need to spend time with a ticket to understand it. 

Quickly looking at the tutorial... 

Screenshot 2021-02-02 at 12 08 49


... I think it links to the wrong page. Rather than submitting patches, it should go to the parent `writing-code.txt` — which has the Working with git info that is needed. 

This page (Writing Code) is the writing code landing page we've talked about and we could develop  it to say more than **just** linking to the sub pages. 

All make sense? I think if we can work those points first, we'll have a good concrete improvement. Let me know your thoughts! 

Thanks. Kind Regards,
Carlton

**Comment by gabbyprecious** [comment]
Oh Hi @carltongibson, are you saying I revert all changes made on this PR and start afresh cause this is not how the contributors guide is now?

**Comment by carltongibson** [comment]
Let's start a fresh one for the changes. 

Leave this one though so we can pull across the textual changes we want at the next step. 

Make sense? 

(I think we need to address it but by bit so it's easier to assess and merge.)

**Comment by gabbyprecious** [comment]
Okay, I'll be making these changes on a new branch:

can you further explain these points:

```
Let's assume for now users can get this far from index.html. We want to guide them to the tutorial, or the reference (if they want something harder).

We can then review the text further down and add a paragraph touching @smithdc1's point that you need to spend time with a ticket to understand it.
```

And What would you like added to the writing code page

**Comment by carltongibson** [comment]
Hey @gabbyprecious...

1. was another way of saying, "Let's not worry about the `index.html` start page just yet". 
2. was (as our follow-up comments) that we'll look at the textual changes next.

Thanks! 🏅

**Comment by carltongibson** [comment]
Hey @gabbyprecious closing in favour of the merged PRs. 

If you want to follow up with any of the wording related changes, or anything else we might have missed in here, then please do! 

Thanks!

**Pull request closed without merging**
