### PR TITLE
Allow chaining of the result of ``refresh_from_db``

### PR DESCRIPTION
**Pull request by lamby**
This will make some common test patterns shorter, ie. not requiring an
extra line, etc.

### CODE REVIEW

**Comment by charettes** [comment]
I'm not sure we want to hijack the return value of this method to save an extra line. This is not a pattern used anywhere else in Django and IMHO the method could be used to return a more valuable value such as a set of the fields updated by the refresh.

**Comment by lamby** [comment]
> This is not a pattern used anywhere else in Django

Obviously not directly the same, but the ORM ``filter``, etc. methods look similar to this if you squint a bit.

Somewhat agree with your general sentiment, but proposing anywa  in case others also like it.

**Comment by charettes** [comment]
> Obviously not directly the same, but the ORM filter, etc. methods look similar to this if you squint a bit.

Right, but it returns a copy of itself in the `QuerySet` case. I should have said the `Model` API.

**Comment by lamby** [comment]
> it returns a copy of itself in the QuerySet case

Quite.

(Just as a thought experiment, I wonder if there are any other methods in the ``Model`` API that could return ``self``.)

**Comment by timgraham** [comment]
@lamby, please use the django-developers mailing list to propose design decision changes like this.

You can check if the idea was raised in the original feature discussion: https://groups.google.com/d/topic/django-developers/Dcqq7zr2VZo/discussion

**Comment by timgraham** [comment]
Closing until the requisite discussion happens and a ticket is created.

**Pull request closed without merging**
