### PR TITLE
Fixed #25617 -- Added case-insensitive unique username validation in UserCreationForm.

### PR DESCRIPTION
**Pull request by nmundar**
https://code.djangoproject.com/ticket/25617

### CODE REVIEW

**Comment by collinanderson** [comment]
This approach seems right to me. Feel free to add a release note too.

**Comment by nmundar** [comment]
Release notes updated, hope the message is ok.

**Comment by timgraham** [comment]
I'd document that in the docs for `UserCreationForm` in `docs/topics/auth/default.txt` too (with a `.. versionchanged:: 1.10` annotation).

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
I realized that this goes against our trend toward trying to make the `UserCreationForm` resusable ([#19353](https://code.djangoproject.com/ticket/19353)). Maybe we could try to move forward with that patch first and then update this to work with custom user models?

Meanwhile I made some minor edits reviewing this before I realized that issue: 
```diff
diff --git a/django/contrib/auth/forms.py b/django/contrib/auth/forms.py
index fb2a7c0..bc0b02b 100644
--- a/django/contrib/auth/forms.py
+++ b/django/contrib/auth/forms.py
@@ -80,7 +80,7 @@ class UserCreationForm(forms.ModelForm):
 
     def clean_username(self):
         username = self.cleaned_data.get('username')
-        if User.objects.filter(username__iexact=username).exists():
+        if username and User.objects.filter(username__iexact=username).exists():
             raise forms.ValidationError(
                 User._meta.get_field('username').error_messages['unique'],
                 code='unique',
diff --git a/docs/releases/1.10.txt b/docs/releases/1.10.txt
index dc48d83..4f07aa5 100644
--- a/docs/releases/1.10.txt
+++ b/docs/releases/1.10.txt
@@ -56,10 +56,6 @@ Minor features
   to prevent an issue where Safari caches redirects and prevents a user from
   being able to log out.
 
-* The :class:`~django.contrib.auth.forms.UserCreationForm` does not allow
-  usernames that differ only in case.
-
-
 :mod:`django.contrib.contenttypes`
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 
@@ -325,6 +321,9 @@ Miscellaneous
 * ``utils.version.get_version()`` returns :pep:`440` compliant release
   candidate versions (e.g. '1.10rc1' instead of '1.10c1').
 
+* The :class:`~django.contrib.auth.forms.UserCreationForm` does not allow
+  usernames that differ only in case.
+
 .. _deprecated-features-1.10:
 
 Features deprecated in 1.10
diff --git a/docs/topics/auth/default.txt b/docs/topics/auth/default.txt
index c115875..428f781 100644
--- a/docs/topics/auth/default.txt
+++ b/docs/topics/auth/default.txt
@@ -1558,10 +1558,12 @@ provides several built-in forms located in :mod:`django.contrib.auth.forms`:
 
     A form for creating a new user.
 
+    To help prevent confusion with similar usernames, the form doesn't allow
+    usernames that differ only in case.
+
     .. versionchanged:: 1.10
 
-        The :class:`~django.contrib.auth.forms.UserCreationForm` does not allow
-        usernames that differ only in case.
+        In older versions, usernames that differ only in case are allowed.
 
 .. currentmodule:: django.contrib.auth
 
diff --git a/tests/auth_tests/test_forms.py b/tests/auth_tests/test_forms.py
index fd02ae9..f38ad75 100644
--- a/tests/auth_tests/test_forms.py
+++ b/tests/auth_tests/test_forms.py
@@ -86,8 +86,10 @@ class UserCreationFormTest(TestDataMixin, TestCase):
         }
         form = UserCreationForm(data)
         self.assertFalse(form.is_valid())
-        self.assertEqual(form["username"].errors,
-                         [force_text(User._meta.get_field('username').error_messages['unique'])])
+        self.assertEqual(
+            form["username"].errors,
+            [force_text(User._meta.get_field('username').error_messages['unique'])]
+        )
 
     def test_invalid_data(self):
         data = {
```

**Comment by nmundar** [comment]
That makes sense. I don't have much experience with CustomUser since my full-time project still uses old approach with separate profile model, but I can give it a go. What about case insensitive USERNAME_FIELD? Should that be left for users to override?

**Comment by timgraham** [comment]
I think case-insensitive is reasonable default that we could allow changing with an attribute on the form.

**Comment by timgraham** [comment]
Hi Neven, think you'll have a chance to finish this soon?

**Comment by nmundar** [comment]
I'm sorry for the delayed response, i'm short on time currently and I won't be able to continue on this.

**Comment by timgraham** [comment]
Thanks for the reply. Please send a new PR if you are able to return to it.

**Pull request closed without merging**
