### PR TITLE
Made register.tag a decorator for echo template tag in testtags.py

### PR DESCRIPTION
**Pull request by atombrella**

### CODE REVIEW

**Comment by timgraham** [comment]
Maybe it's useful to keep one non-decorator usage to test that?

**Comment by atombrella** [comment]
@timgraham Your verdict. I'm going over the template code to find code that's missing coverage, and noticed that one.

**Comment by timgraham** [comment]
Are you saying this change adds coverage? I thought it might decrease it by removing a test for https://github.com/django/django/blob/491eb56fd4dea10248ccced90c31ed64152d09cb/django/template/library.py#L40-L43.

**Comment by atombrella** [comment]
Just checked, coverage does not decrease for that part by this chance. I think the decorator reads nicer, but let's close it to avoid confusion.

**Pull request closed without merging**
