### PR TITLE
Fixed #12738 -- Added a setting for the CSRF token name.

### PR DESCRIPTION
**Pull request by mazlum**
Hello,
I want change csrf token input name (csrfmiddlewaretoken). But Django does not provide this. So i have added this feature to Django core.

Why am i want this?

[Wappalyzer](https://github.com/AliasIO/Wappalyzer/blob/f5a77f3453c796c66f3e597fb30edbc3e2a285c8/src/apps.json#L2471) identifies Django application with "csrfmiddlewaretoken" input name.

### CODE REVIEW

**Comment by timgraham** [comment]
This was previously [closed as wontfix](https://code.djangoproject.com/ticket/12738). You can write to the [django-developers mailing list](https://groups.google.com/forum/#!forum/django-developers) to see if there's consensus to add a new setting. The patch would also require tests and documentation.

**Comment by mazlum** [comment]
So we can document it?

**Comment by timgraham** [comment]
I [wrote to the mailing list](https://groups.google.com/d/topic/django-developers/V8-ifC7i_nU/discussion) for you.

**Comment by timgraham** [comment]
The discussion didn't yield a consensus to move forward with this.

**Pull request closed without merging**
