### PR TITLE
Fixed typos and example in signals.pre_init docs.

### PR DESCRIPTION
**Pull request by hramezani**
[ticket 30571](https://code.djangoproject.com/ticket/30571)

### CODE REVIEW

**Comment by singhpratyush** [comment]
Hi @hramezani, thanks for the fix.

Are we sure we want to keep the actual `kwargs` from the model class nested inside an outer `kwargs`?

With reference to the usecase that I mentioned in [`ticket 30571`](https://code.djangoproject.com/ticket/30571), here's what one will have to do in order to get the actual `kwargs` -

```python
    follower = kwargs['kwargs']['follower']
    following = kwargs['kwargs']['following']
    if follower == following:
        raise ...
```

Which seems little weird, as compared to simply `kwargs.get('follower')`.

**Comment by felixxm** [comment]
@singhpratyush `kwargs` contains `signal` for all types of signals and `kwargs` for `pre_init`. This behavior is there from the very beginning, so changing this would be backward incompatible and I'm not sure if it is doable.

**Comment by singhpratyush** [comment]
@felixxm: That makes sense. Thanks for the explanation :smile:.

**Comment by felixxm** [comment]
@hramezani Sorry, but I've just realized that everything works properly (see [comment](https://code.djangoproject.com/ticket/30571#comment:4)). We should only fix typos in this doc:
- ``` ``__init__()``: ``` -> ``` ``__init__()``. ``` and
- ``tutorial01`` -> ``tutorial02``.

**Comment by hramezani** [comment]
@felixxm Thank you for investigation.
I checked the [tutorial02](https://docs.djangoproject.com/en/2.2/intro/tutorial02/#creating-models), there is no model name `Poll` there. I think we should change the line:
`p = Poll(question="What's up?", pub_date=datetime.now())`
to
`q = Question(question_text="What's new?", pub_date=timezone.now())`

and also
`{'question': "What's up?", 'pub_date': datetime.now()}`
to 
`{'question_text': "What's new?", 'pub_date': timezone.now()}`

**Comment by felixxm** [comment]
@hramezani Yes, good catch  :+1:

**Comment by hramezani** [comment]
@felixxm Done.

**Comment by felixxm** [comment]
@hramezani Thanks!

**Comment by hramezani** [comment]
@felixxm I found a few more like this in the documentation. for example:

- [models signals](https://docs.djangoproject.com/en/2.2/ref/signals/#module-django.db.models.signals)
    in the `note` section(second box) it is better to replace `'polls.Answer'` with `'polls.Choice'`. 
- [custom management commands docs](https://docs.djangoproject.com/en/2.2/howto/custom-management-commands/) refers to `tutorial01` and also `closepoll.py` example refer to `Poll` model which does not exists.

Should I create seprate ticket for each item, or just create one general ticket for all of them?

**Comment by felixxm** [comment]
Custom management commands example imports `Question` as `Poll`so it should work, but yes we can change `tutorial01` to the `tutorial02` and in models signals we can use `polls.Question` or `polls.Choice` instead of `polls.Answer`.

Ticket is not required, you can send a PR. Thanks!

**Pull request merged**
