### PR TITLE
Fixed typo in docs/topics/signals.txt.

### PR DESCRIPTION
**Pull request by amikrop**
Or perhaps meant to be "...connect all signal handlers..."

### CODE REVIEW

**Review by Rquaicoo — CHANGES_REQUESTED** [review]
I think "a signal's handler" is more meaningful to the context

**Comment by amikrop** [comment]
> I think "a signal's handler" is more meaningful to the context

But more than one handlers could exist in the module, so probably plural is needed?

**Comment by amikrop** [comment]
Please let me know if I should take some action, or the maintainers would pick one and make the change.

**Comment by felixxm** [comment]
@amikrop Thanks :+1: Welcome aboard :boat:

**Comment by amikrop** [comment]
> @amikrop Thanks +1 Welcome aboard boat

@felixxm No problem!

**Pull request merged**
