### PR TITLE
Fixed #29584 -- Implemented get_many() in django.core.cache.backends.db

### PR DESCRIPTION
**Pull request by MyungSeKyo**
https://code.djangoproject.com/ticket/29584

### CODE REVIEW

**Comment by timgraham** [comment]
Did you consider trying to avoid much code duplication between `get()` and `get_many()`?

**Comment by MyungSeKyo** [comment]
@timgraham 

```
    def get(self, key, default=None, version=None):
        cache_dict = self.get_many([key], version=version)
        value =  cache_dict.get(key)

        if value is None:
            return default
        else:
            return value
```

How about modifying get() as above?
Could you give me some advice

**Comment by charettes** [comment]
@MyungSeKyo some databases won't optimize `IN (1,)` to `= 1` so we might still want to teach `get_many` to use `=` when `len(keys) == 1`.

**Comment by MyungSeKyo** [comment]
@charettes 
Thanks for the advice!
It is better to fix it that way.
I think I can fix it.

**Comment by MyungSeKyo** [comment]
I rebased latest but

**Comment by timgraham** [comment]
For future reference, that error happens sometimes, especially if your branch contains multiple commits. Try again and it will usually resolve (and it's not really important if one or two builds fail with that error). Avoid creating multiple PRs because then we lose the comment history.

**Pull request closed without merging**
