### PR TITLE
Fixes timezone misinformation

### PR DESCRIPTION
**Pull request by eltronix**
Timezone is already enabled by default in 4.2

### CODE REVIEW

**Comment by felixxm** [comment]
Thanks for this patch, however the docs are correct for Django 4.2:
https://github.com/django/django/blob/791407fef16faa4da6fe2247c24a9055037dd5dd/django/conf/global_settings.py#L43-L44

**Comment by eltronix** [comment]
True, but the docs for that version would still be misleading as they haven't been updated.
https://docs.djangoproject.com/en/4.2/topics/i18n/timezones/

**Comment by shangxiao** [comment]
`USE_TZ = False` for 4.2: https://github.com/django/django/blob/4.2/django/conf/global_settings.py#L44

? 🤔

**Comment by eltronix** [comment]
@shangxiao the patch updates the docs

**Pull request closed without merging**
