### PR TITLE
Fixed #29825 -- Fixed JavaScript ngettext if msgstr is a valid msgid in the same catalog.

### PR DESCRIPTION
**Pull request by jeremy-moffitt**
Per request in https://code.djangoproject.com/ticket/29825 created a unit test that produces a similar issue to the one identified in the bug, however there is a key difference I've not resolved yet...

When the problem happens in OpenStack/Horizon, only the *1st* character of the msgstr is returned
With the unit test here, only the *2nd* character of the msgstr is returned... still a bug and likely due to the same issue, but its not an identical reproduction. 

I will continue to look at this a bit, but wanted to get a similar example uploaded somewhere that could be referenced from the ticket comments

```./runtests.py --selenium=chrome view_tests
Testing against Django installed in 'upstream/django/django' with up to 24 processes
Creating test database for alias 'default'...
Creating test database for alias 'other'...
System check identified no issues (0 silenced).
F.
======================================================================
FAIL: test_javascript_gettext (view_tests.tests.test_i18n.I18nSeleniumTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jeremy/upstream/django/django/test/utils.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/jeremy/upstream/django/tests/view_tests/tests/test_i18n.py", line 432, in test_javascript_gettext
    self.assertEqual(elem.text, "Image")
AssertionError: 'm' != 'Image'
- m
+ Image
```

### CODE REVIEW

**Comment by carltongibson** [comment]
Hi @claudep. When you have capacity, can I ask you to look at this? 

Is the addition to the `.po` file valid: 

```
msgid "Image"
msgstr "Image"
```

The `return value[django.pluralidx(count)];` branch in `ngetext` only looks to make sense if we get a array there (as in the `result` group above). 

(Ref: 

> It's not clear that the "else" block of django.ngettext would be correct for any usage...
> https://bugs.launchpad.net/horizon/+bug/1778189

)

Thanks.

**Comment by claudep** [comment]
@jeremy-moffitt Sorry for being so long to review the patch. I'll try to follow it closer if you can work on it these days.

**Comment by jeremy-moffitt** [comment]
@claudep Just saw the comments here (it was a busy start to the new year), I see the request for changes but I'm not 100% clear on what needs to be updated. I'm not too familiar with the Django contribution workflow but am happy to try updating what I submitted (the original request I received when I filed the bug was to create a test case to reproduce it).

**Comment by claudep** [comment]
#10898 would be my approach of this issue. Thoughts?

**Comment by carltongibson** [comment]
I'm going to close in favour of #10898. Thanks for your work @jeremy-moffitt and @claudep!

**Comment by jeremy-moffitt** [comment]
closing per above (addressed in https://github.com/django/django/pull/10898#pullrequestreview-197162887)

**Pull request closed without merging**
