### PR TITLE
Refs #21548 -- Skipped tests that rely on pillow when it's not installed

### PR DESCRIPTION
**Pull request by bmispelon**

### CODE REVIEW

**Comment by timgraham** [comment]
Not sure it's worth it. Since Pillow 3.0, JPEG/PNG are requirements unless you disable them. I'm trying to fix the Windows failure which seems to be due to an old version of pip which isn't installing the correct Windows binary of Pillow.

**Comment by apollo13** [comment]
Ah, I was just aware of the old PIL code which just skips… we had the import check before :D

**Comment by bmispelon** [comment]
I changed the skip condition to simply test for PIL installation.

**Comment by apollo13** [comment]
lgtm

**Comment by MarkusH** [comment]
We often use

```python
try:
    from a import b
except ImportError:
    b = None


if b is not None:
    ....
````

**Comment by bmispelon** [comment]
Merged in a9215b7c36bff232bcc9416309726290dc74a9e8 (saw your comment too late, sorry Markus 🙉)

**Pull request closed without merging**
