### PR TITLE
Fixed #24799 -- Fixed deleting of empty session cookie when using SESSION_COOKIE_DOMAIN

### PR DESCRIPTION
**Pull request by blopker**

### CODE REVIEW

**Comment by blopker** [comment]
Also, this is my first Django PR! Let me know if I can do anything better. :)

**Comment by charettes** [comment]
Buildbot, test this please.

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
buildbot, test this please.

**Comment by timgraham** [comment]
As this is a candidate for backporting to stable/1.8.x, you could add release notes for 1.8.2.

**Comment by blopker** [comment]
Done!

**Comment by timgraham** [comment]
merged in 2dee853ed4def42b7ef1b3b472b395055543cc00, thanks!

**Pull request closed without merging**
