### PR TITLE
Refs #29548 -- Fix failing tests on MariaDB

### PR DESCRIPTION
**Pull request by orf**
https://code.djangoproject.com/ticket/29548

### CODE REVIEW

**Comment by orf** [comment]
buildbot, test on mariadb.

**Comment by orf** [comment]
buildbot, test on mariadb.

**Comment by timgraham** [comment]
buildbot, test on mariadb.

**Comment by orf** [comment]
buildbot, test on mariadb.

**Comment by orf** [comment]
buildbot, test on mariadb.

**Comment by orf** [comment]
buildbot, test on mariadb.

**Comment by orf** [comment]
buildbot, test on mariadb.

**Comment by orf** [comment]
buildbot, test on mariadb.

**Comment by orf** [comment]
The build does not seem to be showing up in the checks below, but here is the passing Jenkins build: https://djangoci.com/job/pr-mariadb/database=mysql,label=mariadb,python=python3.7/6/

**Comment by orf** [comment]
buildbot, test on mariadb.

**Comment by orf** [comment]
buildbot, test on mariadb.

**Comment by orf** [comment]
buildbot, test on mariadb.

**Pull request merged**
