### PR TITLE
Fixed admin CSS for calendar widget for RTL languages.

### PR DESCRIPTION
**Pull request by ahmadekhalili**
calendar previous next icons in rtl direction is reverse.

### CODE REVIEW

**Comment by felixxm** [comment]
@ahmadekhalili Thanks for this patch :+1: Can you attach screenshots with and without the patch?

**Comment by ahmadekhalili** [comment]
### before fixing
8Sr05H5KZSPX

### after fixing
6NAC5g04QqmH

**Comment by tjni** [comment]
Out of curiosity, I checked what Google Calendar does. The left button becomes the next month button and the right button becomes the previous month button. If we go with that behavior, then I think that the CSS is fine, but the symbol that is drawn on the button in DateTimeShortcuts.js should change.

**Comment by ahmadekhalili** [comment]
Thanks @tjni for useful comment, i fixed it, now calendar previous next icons are in right direction (like second screenshot), and left button becomes the next month and right button becomes the previous month (like other rtl calendars) and in ltr all things is like previous.

**Comment by felixxm** [comment]
@shaib Can you take a look?

**Comment by shaib** [comment]
> @shaib Can you take a look?

Not before the weekend

**Comment by ahmadekhalili** [comment]
@felixxm zzzzzzzzzzz :wink:

**Comment by smithdc1** [comment]
There is no rush. I'm assuming this isn't a release blocker so we have until May before the next feature freeze.

**Review by shaib — APPROVED** [review]
I confirm the problem and that this fixes it. Somewhat to my surprise, it fixes the responsive presentation as well.

**Comment by felixxm** [comment]
@ahmadekhalili Thanks :+1: Welcome aboard :boat: 

@shaib @tjni Thanks for reviews :+1:

**Pull request merged**
