### PR TITLE
Fixed #24621 -- Fixed and documented SessionBase.pop's second argument

### PR DESCRIPTION
**Pull request by adamzap**
https://code.djangoproject.com/ticket/24621

### CODE REVIEW

**Comment by timgraham** [comment]
I don't think that's the actual signature, see https://github.com/django/django/blob/a7bc00e17bebe34cdf23f744937b3c386ee73d81/django/contrib/sessions/backends/base.py#L61-L63

**Comment by adamzap** [comment]
You're right. I'm unsure why `*args` is being passed to `pop` when in every case, `_session` is a `dict`.

I changed `*args` to `default=None` in `pop` to match `get`, and got the same results from running the tests.

Git blame doesn't shed any light on why `*args` is there: bcf7e9a9fe037eff4d5dea0cdd8c35104590e1a8

How should I proceed?

**Comment by timgraham** [comment]
I think it's okay to change `*args` to `default=None` in the code. I guess we'll limit the doc patch to master to avoid confusion in that case.

**Comment by adamzap** [comment]
There you go. Thanks Tim!

**Comment by timgraham** [comment]
buildbot, test this please.

**Comment by timgraham** [comment]
merged in 872eb26f542caead338d6456b345ca2f5c0684e2, thanks!

**Comment by tuky** [comment]
Actually this "fix" introduces an undocumented 1.9 backward incompatibility (or a bug if you will). expected behavior of `some_dict = {}; some_dict.pop('key')` would be a `KeyError`. but this "fix" always passes a `default=None` which suppresses the `KeyError`. At least we were relying on this `KeyError`.

**Comment by timgraham** [comment]
Please report the issue in a Trac ticket and offer a pull request with a regression test if you are able.

**Comment by tuky** [comment]
i will try my best.

**Pull request closed without merging**
