### PR TITLE
Test model signals "sender" parameter is correct when defer() is used

### PR DESCRIPTION
**Pull request by diox**
This was fixed when dynamic classes for deferred instance loading was changed in 7f51876f99851fdc3fef63aecdfbcffa199c26b9.

### CODE REVIEW

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by aaugustin** [comment]
LGTM. I'd merge it if I knew what the proper GitHub protocol was -- squash and merge?

**Comment by timgraham** [comment]
Some tests were added in 535660b852c8899a17b82d20a06c926d8d437db3, do you think these bring additional benefit?

Aymeric, here's how I've been used the green button: https://github.com/django/django/pull/7275.

**Comment by diox** [comment]
The main thing about these changes is that they cover `pre_save` and `post_save`, and the `defer()` call is made after more "normal" calls to test that particular scenario (I made this test while chasing a bug I had with 1.8, and it only triggered in specific conditions that this test is trying to reproduce)

**Comment by timgraham** [comment]
merged in 2b8ccff3b6278f862a2d4840f55a7062747a452f, thanks!

**Pull request closed without merging**
