### PR TITLE
Fixed broken dbshell.test_oracle.OracleDbshellTests tests after 9386586f31b8a0bccf59a1bff647cd829d4e79aa.

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by claudep** [comment]
Many thanks for the fix. I have no oracle to test (and don't want to!).

**Comment by felixxm** [comment]
np :+1: , Oracle is not a "pure-evil" :wink:.

**Comment by claudep** [comment]
```
>>> non_free == pure_evil
True
```
:satisfied:

**Pull request merged**
