### PR TITLE
Fixed #29253 -- Made method_decorator(list) copy attributes.

### PR DESCRIPTION
**Pull request by cjerdonek**
This resolves the following ticket: https://code.djangoproject.com/ticket/29253

### CODE REVIEW

**Comment by cjerdonek** [comment]
You mean `method` instead of `meth`? I could do that.

I'm happy to add something to the release notes, too, though I didn't see anything in the contributing guidelines that said to do so in the case of bug fixes:
https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/submitting-patches

**Comment by auvipy** [comment]
then that is nit needed

**Comment by cjerdonek** [comment]
Okay, but I do see bug fixes mentioned in the release notes, e.g.
https://docs.djangoproject.com/en/2.0/releases/2.0.1/

So someone is adding them :), it just doesn't seem to be stated to do so in the docs.

**Comment by timgraham** [comment]
I documented our practices about release notes in https://github.com/django/django/pull/9857.

**Comment by auvipy** [comment]
please remove mentioning my id on the commit as it floods me with notification, and better to squash commits to a single one

**Comment by timgraham** [comment]
Chris, can you check if https://github.com/encode/django-rest-framework/pull/6043 is a regression? Before this commit, it seems that decorating class-based view methods with either  `@transaction.non_atomic_requests` or `@method_decorator(transaction.non_atomic_requests)` had the same effect but now the latter crashes.

**Comment by cjerdonek** [comment]
Yes, I can look.

**Comment by cjerdonek** [comment]
FYI, I posted a fix here: https://github.com/django/django/pull/10091

**Pull request merged**
