### PR TITLE
[WIP] Fixed #26626 -- Updated decorator_from_middleware() to work with DEP5 style middleware.

### PR DESCRIPTION
**Pull request by carljm**
@timgraham - pushing this so you can take a look, but please don't merge yet; this needs some adjustments and documentation still.

### CODE REVIEW

**Comment by carljm** [comment]
@timgraham I think this is ready to go. New middleware doesn't play 100% nicely with `decorator_from_middleware` and `TemplateResponse` -- because request and response processing are no longer separable, we can't in the general case automatically defer response processing for `TemplateResponse` when a middleware is converted to decorator. Of course, the main benefit of DEP 5 is precisely that "request and response processing are no longer separable," so this isn't avoidable. I was at least able to add automated `TemplateResponse` handling to `MiddlewareMixin`, which takes care of immediate backwards-compatibility.

I'm traveling tomorrow and may not be available all the time. Feel free to ping me with questions or requested changes here, but if I don't get back to you quickly just make whatever changes you feel are needed and merge it; I don't want to hold you up on the beta.

**Comment by timgraham** [comment]
Did you consider requiring middleware using `decorator_from_middleware` to continue implementing `process_request` / `process_response`, etc?

**Comment by timgraham** [comment]
New approach is https://github.com/django/django/pull/6805.

**Comment by carljm** [comment]
Based on the latest mailing list thread (https://groups.google.com/forum/#!topic/django-developers/hNQIaYcN3xM) I'm leaning toward this approach instead of #6805. Neither is perfect, but I think the tradeoff might be better here. However, after discussion with @timgraham in IRC, we are thinking to leave the status quo in place for 1.10 and wait for a ticket to be filed about `decorator_from_middleware` and new-style middleware, in order to have the change be better informed by real-world use cases.

If we do go with this approach, I think it could still use a) more reliable detection of new-style vs old-style middleware (maybe default to old instead of new for middleware using `MiddlewareMixin` so that the behavior of `decorator_from_middleware` with those middleware doesn't change?) and b) a documentation note that you can use `MiddlewareMixin` to take care of the `TemplateResponse` issue for you.

**Comment by timgraham** [comment]
Closing until we resume work on this, inspired by feedback from users.

**Pull request closed without merging**
