### PR TITLE
Fixed #29338 -- Allowed using union query in Subquery

### PR DESCRIPTION
**Pull request by EugeneKovalev**

### CODE REVIEW

**Comment by cansarigol** [comment]
hi @EugeneKovalev, I thought your solution when I was working on version 2.0. But in master branch `resolve_all` has been changed by @charettes 's  [Pr](https://github.com/django/django/commit/35431298226165986ad07e91f9d3aca721ff38ec)

**Comment by felixxm** [comment]
After Simon's patch it's even easier to apply this approach:
```diff
diff --git a/django/db/models/sql/query.py b/django/db/models/sql/query.py
index 08d7faf194..fe20ebf645 100644
--- a/django/db/models/sql/query.py
+++ b/django/db/models/sql/query.py
@@ -1024,6 +1024,9 @@ class Query(BaseExpression):
                 not self.select_for_update):
             clone.clear_ordering(True)
         clone.where.resolve_expression(query, *args, **kwargs)
+        # Resolve compound queries.
+        for combined_query in clone.combined_queries:
+            combined_query.where.resolve_expression(query, *args, **kwargs)
         for key, value in clone.annotations.items():
             resolved = value.resolve_expression(query, *args, **kwargs)
             if hasattr(resolved, 'external_aliases'):
```

I believe that's a proper way to solve this issue. I will add a test and send PR with this approach.

**Comment by felixxm** [comment]
Ok, my previous comment is not entirely true, please find below example that doesn't work properly
```python
qs1 = Company.objects.filter(ceo__salary__gt=OuterRef('salary'))
qs2 = Company.objects.filter(num_employees__lt=OuterRef('company_ceo_set__num_employees'))
Employee.objects.annotate(
    company_name=Subquery(
        qs1.union(qs2).values('name').order_by('name')[:1]
    ),  
).values_list('company_name')
```
patch require more thinking but I believe that @EugeneKovalev approach is correct in general.

@EugeneKovalev Do you want to investigate this and prepare patch against master?

**Comment by EugeneKovalev** [comment]
@felixxm yeah, sure

**Comment by charettes** [comment]
@felixxm it's possible that the nested subquery annotation might have been resolved by recent changes in `master`.

**Comment by felixxm** [comment]
@charettes It still doesn't work properly :disappointed: I added PR with falling test.

Superseded by #11692.

**Pull request closed without merging**
