### PR TITLE
reduce use of django template variables in GIS

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
This:

* wraps module in a function
* moves all the template variables to the top of that function
* puts block extensions in their own functions

**Comment by graingert** [comment]
So that <del>I can sleep at night</del> this code can run under CSP these hooks will have to be replaced with some other API.

**Comment by timgraham** [comment]
A ticket and fixing the test failure is also needed. @claudep, could you confirm this patch is worth pursuing and not obsoleted by some other work, for example?

**Comment by claudep** [comment]
I plan to deprecate this code (the `GeoModelAdmin` stuff) for Django 2.0. If it's important to clean that code before that, I don't mind. If I understand it correctly, testing will be difficult, as it's not broken, only not CSP compliant.

**Comment by timgraham** [comment]
Closing due to inactivity and because tests aren't passing.

**Pull request closed without merging**
