### PR TITLE
Fixed #30498 -- Fixed proxy class caching in lazy().

### PR DESCRIPTION
**Pull request by bluetech**
Ticket: https://code.djangoproject.com/ticket/30498

I split this from PR #11314.

### CODE REVIEW

**Comment by felixxm** [comment]
@bluetech Thanks for this patch :rocket:  Can we add a test?

**Comment by bluetech** [comment]
@felixxm Thanks for taking a look. I didn't add a test because this is a performance bug, not a logic bug (the behavior before is the same, just slower). I can't come up with a test which would not involve peeking into the internal implementation bowls of `lazy` (e.g. check that `__prepare_class__` is only called once).

**Comment by charettes** [comment]
I think it might be worth adding a regression test even if it asserts against internals else this is likely to regress.

```python
def identity(x): return x
lazy_identity = lazy(identity, int)
self.assertTrue(lazy_identity(1).__class__._proxy____prepared)
```

It might be worth adding a comment explain the reasoning behind this assertion.

**Comment by bluetech** [comment]
OK then, I added a test. It fails before and passes after.

**Comment by felixxm** [comment]
@bluetech Thanks for this patch :rocket:

**Comment by felixxm** [comment]
buildbot

**Comment by drewpc** [comment]
@felixxm this patch was merged into django:master on May 22 but has not been released in any of the bug fix releases for 1.11, 2.1, or 2.2 since May.  What needs to happen for this fix to be released in a near-term bug fix release?  Should PRs be opened applying the same fix to those stable branches?

**Comment by felixxm** [comment]
This patch doesn't qualify for a backport.

**Pull request merged**
