### PR TITLE
Fixed #22728 - Prohibited lookups usage for get_or_create and update_or_create

### PR DESCRIPTION
**Pull request by coldmind**
https://code.djangoproject.com/ticket/22728

### CODE REVIEW

**Comment by mjtamlyn** [comment]
I feel like this implementation doesn't prohibit transforms? I'm not sure what the correct behaviour here should be. Where the transform doesn't change the type we could conceivably use it as the default. Otherwise it's not so obvious. For example: `Person.objects.get_or_create(name__unaccent='Eléonore')` could create the name field.

I'm not that convinced that raising a `TypeError` here is necessarily that sensible anyway. What we could do is require that a field used in the `get` portion with a `lookup` is also passed in `defaults`. This of course can only apply if the field is on the model in question.

As an example where this really would be inconvenient, consider the following. It's a slightly simplified example which I'm not sure makes sense in the real world, but I'm sure a similar case could be found.

```
class Person(models.Model):
    name = models.CharField(max_length=255)

class Organisation(models.Model):
    name = models.CharField(max_length=255)
    active = models.BooleanField(default=True)

class Membership(models.Model):
    person = models.ForeignKey(Person)
    organisation = models.ForeignKey(Organisation)

# Business logic applies a constraint - each Person can only be a member of one
# Organisation at a given time. When an organisation is made inactive, the current
# membership list is maintained for historical reasons

person = Person.objects.get(...)
organisation = Organisation.objects.get(...)
Membership.objects.get_or_create(
    organisation__active=True,
    person=person,
    defaults={'organisation': organisation},
)
```

This would move someone's membership from one organisation to another, but only if the first organisation is active. I actually have no idea if this works at present.

**Comment by coldmind** [comment]
@mjtamlyn well, transforms will not work too because of `params = {k: v for k, v in kwargs.items() if LOOKUP_SEP not in k}`, where `LOOKUP_SEP` is `__`.
The main problem is that this issue is working silently, because any args with `__` inside are not actually passed to the creation.
The fact it is doing this silently makes this dangerous, so we need to throw exception.
I don't see much sense to allow it for some exotic situations.

**Comment by mjtamlyn** [comment]
The first thing to make absolutely clear here is that this is backwards incompatible. The lookup version is not ignored completely - it *is* passed to the `get` stage (for `get_or_create`) or the `update` stage (for `update_or_create`). See https://gist.github.com/mjtamlyn/9bfc2966010f514db015

I have to admit I'm struggling to think of a good use case for this (without the ability to handle type-idempotent transforms and pass them to the create step). That doesn't mean that there isn't a good use case. I agree the currently functionality could be considered unexpected, but the presence of code which handles this shows it was an intended feature.

Actually, when digging into the original code which added `get_or_create` (b3a6348b) I spotted another issue with this patch - the (documented but untested) approach of passing `defaults__exact` to the method to handle a field with the name `defaults`. We need to at least special case this.

**Comment by coldmind** [comment]
@mjtamlyn, well, yes, it will be somewhat backwards incompatible. But it is not going to actually break users code, if someone wrote it in the way of this issue, it just will show them that their code is not working correctly.

Yes, lookup is passed to the `get` stage.. I'm not sure if it is correct if it actually not going to be passed to `create()`

I will take a look for the `defaults__exact`, thanks for noticing it

**Comment by mjtamlyn** [comment]
Well, we document exactly the behaviour that we have - with Adrian's original description about which keywords arguments passed to `get_or_create` are passed on to the `create` step, so we have to assume that for as many people who are using it incorrectly due to not reading the docs properly there are users who *are* using it correctly having read the docs.

Fundamentally `get_or_create` is a utility method which has specific, documented behaviour. You are proposing to change that documented behaviour. This puts the patch in a difficult position to start with - you have to have really good reasons to get backwards incompatible changes to Django's public APIs to land.

In this case the arguments boil down to "we can't think of a use case for the feature" and "it will catch some unintended bugs in some cases". I'm unconvinced this is sufficient, but I'd like another core dev to chime in given the full context of what's being proposed.

**Comment by carljm** [comment]
Commented on the ticket rather than here, since my comment is about the core approach to the issue, not the specifics of the code in this PR.

**Comment by coldmind** [comment]
Closing per ticket

**Pull request closed without merging**
