### PR TITLE
Change shell prompts to read "python3" vs "python"

### PR DESCRIPTION
**Pull request by JC-swEng**
Since this is a tutorial written largely for novices, it is more user-friendly to have the shell prompts be "python3". The tutorial states that "This tutorial is written for Django |version|, which supports Python 3.8 and later." So it is safe to assume the user is using python3 for shell prompts. Any experienced python developer who is using an alias such as python-is-python3 will know to substitute python for python3, but a novice will not necessarily know to do the inverse.

### CODE REVIEW

**Comment by pauloxnet** [comment]
I agree with that change. Can you check if there's other tutorial step where you can replace `python` with `python3 ` ?

**Comment by JC-swEng** [comment]
I have updated all txt files in the intro folder by changing "python" to "python3" in shell prompts.

**Review by pauloxnet — APPROVED** [review]

**Comment by pauloxnet** [comment]
I've approved this PR, we'll wait for other that can merge.

**Comment by shangxiao** [comment]
Just FYI I'm not against this change but if you're working in a venv then python & python3 are symlinks to the same binary (and venvs are the recommentation on the install Django page)

**Comment by smithdc1** [comment]
Thanks for the contribution.

`python3` doesn't work on Windows, however. It launches the store so you can install it instead. `python` (or maybe just `py`) are needed.

**Review by carltongibson — COMMENTED** [review]
Thanks for this, but as I understand it `python3` is now something of an outdated legacy of the 2-to-3 transition. 

[PEP 394](https://peps.python.org/pep-0394/) specifies the norms here. The relevant parts: 

> When a virtual environment … is active, the `python` command should refer to the virtual environment’s interpreter and should always be available.
> - https://peps.python.org/pep-0394/#for-python-runtime-distributors

> … `python` remains the preferred spelling for explicitly invoking Python, as this is the spelling that virtual environments make consistently available across different platforms and Python installations.
> - https://peps.python.org/pep-0394/#for-end-users-of-python

Since Django recommends always using a virtual environment, `python` is the simpler, and clearer case. 

Additionally from the PEP: 

> Distributors may choose to set the behavior of the `python` command ... 

As the Python 2 EOL ripens, it's increasingly expected that `python` will point to the (only one there is) `python3` executable. We should _skate to where the puck will be_, I believe is the idiom. 

Having conferred with @felixxm, I'm going to close as `wontfix` on that basis. \

Thanks.

**Pull request closed without merging**
