### PR TITLE
Simplified Options._get_fields(); refs #24328.

### PR DESCRIPTION
**Pull request by timgraham**

### CODE REVIEW

**Comment by collinanderson** [comment]
lgtm

**Comment by PirosB3** [comment]
Looks very nice. +1

**Comment by akaariai** [comment]
I'm working on a larger refactor to _get_fields(), so please don't commit.

**Comment by PirosB3** [comment]
Great! Is your work already on a pull request? Where is it?

**Comment by timgraham** [comment]
Closing per Anssi's comment.

**Pull request closed without merging**
