### PR TITLE
Fixed #33919 -- Fixed adding AutoFields on PostgreSQL.

### PR DESCRIPTION
**Pull request by felixxm**
Thanks Jack Calvin Brown for the report.

Regression in 2eea361eff58dd98c409c5227064b901f41bd0d6.

ticket-33919

### CODE REVIEW

**Comment by felixxm** [comment]
@jackcbrown89 Does it work for you?

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Review by David-Wobrock — APPROVED** [review]

**Review by hramezani — APPROVED** [review]

**Review by realsaeedhassani — APPROVED** [review]

**Review by jackcbrown89 — APPROVED** [review]
@felixxm Thanks for the fix! It works for me

**Comment by felixxm** [comment]
Thanks y'all for checking :+1:

**Pull request merged**
