### PR TITLE
Fixed #34910 -- Improved color contrast for add/change icons in admin.

### PR DESCRIPTION
**Pull request by Hisham-Pak**
Ticket: https://code.djangoproject.com/ticket/34910

### CODE REVIEW

**Review by thibaudcolas — COMMENTED** [review]
Thank you for giving this a go @Hisham-Pak, could you confirm what you’ve done to test this? 

In particular I believe this needs further work for support of the admin’s dark theme – have you tested that?

**Comment by Hisham-Pak** [comment]
Hi @thibaudcolas, thank you for your review. I have visually inspected the color and also looked for its occurrences elsewhere (didn't find any issues). It has passed the contrast [test](https://contrast-grid.eightshapes.com/?version=1.1.0&background-colors=%23121212%2CDark%0D%0A%23ffffff%2CWhite%0D%0A&foreground-colors=70bf2b%2CGreen%20as-is%0D%0A5fa225%2CGreen%20new%0D%0Aefb80b%2CYellow%20as-is%0D%0Ab48c08%2CYellow%20new&es-color-form__tile-size=compact&es-color-form__show-contrast=aaa&es-color-form__show-contrast=aa&es-color-form__show-contrast=aa18&es-color-form__show-contrast=dnp) as well (although contrast ratio did decrease a little bit on dark mode). If there’s anything I might have overlooked, please let me know. Here’s how the changes appear in the current context:

Light Mode
light mode

Dark Mode
dark mode

**Review by thibaudcolas — APPROVED** [review]
Thank you @Hisham-Pak, my bad! This looks spot on, tested in light and dark mode though obviously the contrast grid you provided is enough to validate the change.

**Comment by felixxm** [comment]
@thibaudcolas Thanks for the review :+1: We don't use labels to categorize PRs, you don't need to add them.

**Comment by felixxm** [comment]
@Hisham-Pak Thanks :+1: Welcome aboard :boat:

**Pull request merged**
