### PR TITLE
Fixed #32158 -- Fixed crash in loaddata when table name is a SQL keyword

### PR DESCRIPTION
**Pull request by gnbezerra**
On SQLite, if one tried to load a fixture using loaddata for a model with table name "order", or any other SQL reserved word, it would raise a `sqlite3.OperationalError`.

That happened because, when constructing the SQL query to check constraints, the table name was not being quoted.

Ticket: https://code.djangoproject.com/ticket/32158

### CODE REVIEW

**Comment by gnbezerra** [comment]
Well, apparently the new tests I included break for postgres. Gonna look if I can either fix the postgres implementation as well or limit the test for sqlite.

**Comment by gnbezerra** [comment]
The problem is that I used `assertRaisesMessage`, and the exception message is different for PostgreSQL. For all others the message created on the db backend is the expected:

> Problem installing fixtures: The row in table 'order' with primary key '1' has an invalid foreign key: order.customer_id contains a value '1' that does not have a corresponding value in fixtures_regress_person.id.

but for PostgreSQL the error message is gotten from the database driver:

> Problem installing fixtures: insert or update on table "order" violates foreign key constraint "order_customer_id_9da9253f_fk_fixtures_regress_person_id"\nDETAIL:  Key (customer_id)=(1) is not present in table "fixtures_regress_person".\n

The `Problem installing fixtures:` beginning, common for both, is generated by the loaddata command. I'm gonna check only for this beginning with an `assertRaisesRegex()` method.

**Comment by gnbezerra** [comment]
Why did the first commit had 31 checks and the second one only 7 checks?

**Review by charettes — COMMENTED** [review]
Thank you for your patch George!

The tests you've written for `loaddata` are excellent but the crash during the loading of fixtures is more of a symptom than the actual problem.

We have unit tests in place specifically for `check_constraints`

https://github.com/django/django/blob/302caa40e4caab7d95ef7d0a88a90f935039ab09/tests/backends/tests.py#L608-L626

So I'd be tempted to simply make `backends.models.Article._meta.db_table = 'order'` so it's covered by the existing `test_check_constraints`.

I think it's the easiest and simplest way forward as that would avoid creating yet another table during tests setup.

**Comment by gnbezerra** [comment]
Got it, I created the model for semantic reasons, but it makes sense to not create yet another table during setup.

Maybe setting the db_table to `order` in a largely used model may arise other issues, but if it does it may be even better to find out hidden problems. Just don't know if the reader will understand why a model called Article has "order" as the table name, I may need to put comments explaining that.

Things have been busy for me but I'm still on it, I'll do the changes to the patch later this week.

**Comment by felixxm** [comment]
@gnbezerra Do you have time to keep working on this?

**Comment by felixxm** [comment]
Closing due to inactivity.

**Pull request closed without merging**
