### PR TITLE
Refs #32061 -- Unified DatabaseClient.runshell() in db backends.

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Comment by felixxm** [comment]
@charettes Thanks for this patch :+1:

I added release notes, added tests for `BaseDatabaseClient`, moved `_dsn()` and `_connect_string()` to the `django.db.backends.oracle.utils`, and pushed small edits.

**Comment by charettes** [comment]
Thanks for all of this @felixxm.

I didn't really like how the Oracle changes ended in the first place due to the import avoidance dance of `cx_Oracle` so if you can get it working without too much pain that'll be nice!

**Comment by felixxm** [comment]
I moved `connect_string()` to the `DatabaseClient` on Oracle, it's used only there and this should solve import issues :crossed_fingers:

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Pull request merged**
