### PR TITLE
Fixed #25631 -- Fixed support detection for some DB functions in SpatiaLite backend.

### PR DESCRIPTION
**Pull request by sir-sigurd**

### CODE REVIEW

**Comment by timgraham** [comment]
Your plan on the ticket sounds good. I merged this commit to stable/1.9.x. Would you like to update this for master then?

**Comment by sir-sigurd** [comment]
I'm not sure you understood my proposition, I planned to fully drop SpatiaLite 2.4 i.e set minimum version to 3.0. This involves a bit more work, so I thought to do this within another ticket/pull request. Does this make sense?

**Comment by timgraham** [comment]
Oh okay, I don't mind. Yes, a different ticket pull request is appropriate. Should I merge this to master also?

**Comment by sir-sigurd** [comment]
No, I think this is unnecessary.

**Pull request closed without merging**
