### PR TITLE
Fixed typo in SetPasswordForm()'s docstring.

### PR DESCRIPTION
**Pull request by shitcoding**
Just a typo in SetPasswordForm docstring, not a big deal, but anyways :)

### CODE REVIEW

**Comment by felixxm** [comment]
@shitcoding Thanks :+1: Welcome aboard :boat:

**Comment by timgraham** [comment]
For what it's worth, I don't think it's a typo. The same language is used [in the documentation](https://docs.djangoproject.com/en/dev/topics/auth/default/#django.contrib.auth.forms.SetPasswordForm).

This docstring parallels the `PasswordChangeForm` docstring: "A form that lets a user change their password by entering their old password." It could also just as easily be reworded from "change" to "set". In either case, the meaning is unchanged.

**Comment by shitcoding** [comment]
> For what it's worth, I don't think it's a typo. The same language is used [in the documentation](https://docs.djangoproject.com/en/dev/topics/auth/default/#django.contrib.auth.forms.SetPasswordForm).
> 
> This docstring parallels the `PasswordChangeForm` docstring: "A form that lets a user change their password by entering their old password." It could also just as easily be reworded from "change" to "set". In either case, the meaning is unchanged.

Initially `SetPasswordForm` docstring was "A form that lets a user **change set** their password without entering the old". 
Either change or set is ok but not both at once :)

Anyways, it's not a big deal. I just thought it would be kinda cool to make a contribution to Django development, even though it actually doesn't change anything substantial.
(Look mom, I'm an open source contributor now!)

**Comment by timgraham** [comment]
Oops, I missed "change set". I guess it's fine at this point.

**Pull request merged**
