### PR TITLE
Fixed #29352 -- Allowed specifying a Feed language different from settings.LANGUAGE_CODE.

### PR DESCRIPTION
**Pull request by phenelleevolio**
https://code.djangoproject.com/ticket/29352

### CODE REVIEW

**Comment by phenelleevolio** [comment]
I cant wait to create an account on a new system to talk about bug in django.. (sarcasm)

**Comment by phenelleevolio** [comment]
Should I open trac ticket when the jenkins process that fails too ? 
https://djangoci.com/job/pull-requests-trusty/database=mysql_gis,label=trusty-pr,python=python3.5/17866/console

**Comment by timgraham** [comment]
That failure is unrelated to the patch. My concern about the patch is backwards compatibility. Is there some documentation that suggests the existing behavior is incorrect? That's why I said that the issue needs to be explained.

**Comment by charettes** [comment]
> I cant wait to create an account on a new system to talk about bug in django.. (sarcasm)

You can login using your Github account.

**Comment by phenelleevolio** [comment]
According do django's documentation:
"Settings.LANGUAGE_CODE" is not reliable if you want to get the current language of the execution.. (See https://docs.djangoproject.com/en/2.0/ref/settings/#language-code)

So, when the views.py does "language=settings.LANGUAGE_CODE"
 1) it does not always provide the right language code
 2) it does not allow to override with a different value (*)

(*) Would you change Settings.LANGUAGE_CODE right in the middle of the app execution..?

**Comment by phenelleevolio** [comment]
@charettes 

I agree with you. 
`get_language()` should be default value
self.language needs an override

**Comment by timgraham** [comment]
Docs go in `docs/ref/contrib/syndication.txt` and tests go in `tests/syndication_tests`. A Trac ticket is still needed. See also our [patch review checklist](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/submitting-patches/#patch-review-checklist).

**Comment by phenelleevolio** [comment]
https://code.djangoproject.com/ticket/29352

**Comment by timgraham** [comment]
Will you add tests and docs?

**Comment by timgraham** [comment]
Closing due to inactivity.

**Pull request closed without merging**
