### PR TITLE
Ticket 27704

### PR DESCRIPTION
**Pull request by mehdipourfar**

### CODE REVIEW

**Comment by mehdipourfar** [comment]
I only wanted to send pull request for this single commit. I don't know where I was wrong. can you help me?
https://github.com/mehdipourfar/django/commit/52ee8285ebc6afa8ffd94866a2ba454dadc3ff5c

**Comment by timgraham** [comment]
It looks like you created your branch on stable/2.0.x instead of master. Create a branch off of master and cherry-pick your commit over, then force push that branch to this GitHub branch.

By the way, did you find a deficiency in the approach suggested in the older PR (https://github.com/django/django/pull/7850)? That patch needs a few simplifications as noted there and adds much less new code.

**Comment by mehdipourfar** [comment]
I had not seen it before. It seems to be a more simple solution. The only problem is the widget it use. When there are around 20 choices for a field, it is really hard for user to scroll down and keep control button down to select items.
What do you think?

**Comment by timgraham** [comment]
A checkbox widget should probably be chosen by the user rather than be the default as that would be consistent with other form fields in Django.

**Pull request closed without merging**
