### PR TITLE
Updated datum directory for PROJ 6 in GIS install instructions.

### PR DESCRIPTION
**Pull request by felixxm**
See https://github.com/OSGeo/PROJ/commit/d7366ffdd5cbe5ba6c2d9f917d064085bbc3eddc.

### CODE REVIEW

**Review by claudep — APPROVED** [review]
Thanks a lot, Mariusz. I always wonder why people torture themselves while `apt<replace_with_your_favorite_package_manager> install libproj…` works so nicely :-)

**Comment by smithdc1** [comment]
> Thanks a lot, Mariusz. I always wonder why people torture themselves while `apt<replace_with_your_favorite_package_manager> install libproj…` works so nicely :-)

I'm doing it wrong then as I'm going down this rabbit hole today! :laughing: 

One small note, I think the commit message could refer to version 6 only? Looks like something different will be required for version 7+. See https://github.com/OSGeo/proj-datumgrid

**Comment by felixxm** [comment]
Thanks both :+1: 

> One small note, I think the commit message could refer to version 6 only? Looks like something different will be required for version 7+. See https://github.com/OSGeo/proj-datumgrid

True, thanks :+1: 

> Thanks a lot, Mariusz. I always wonder why people torture themselves while  ...

I noticed this when building PROJ 7, which is not available on my OS :shrug:

**Comment by claudep** [comment]
Hey David, there surely must be use cases for source compiling, but I find packaged software so much more easier and sure that I can't help encouraging people to consider use them, unless there is a compelling reason not to.

**Comment by smithdc1** [comment]
Yes. I was also trying to use different versions than what is generally available. 

I think the answer is probably no, but to check...   could we refer folk to install from conda-forge rather than install from source? 

E.g.  https://anaconda.org/conda-forge/proj

**Comment by claudep** [comment]
Even after what I said above, I still think we should leave source installation instructions, as a last resort installation method.

**Pull request merged**
