### PR TITLE
Fixed #28199 -- Fixed Subquery generating unnecessary/invalid CAST.

### PR DESCRIPTION
**Pull request by timgraham**
https://code.djangoproject.com/ticket/28199

### CODE REVIEW

**Comment by timgraham** [comment]
@charettes @schinckel -- any advice about things to try for a solution?

**Comment by charettes** [comment]
@timgraham it looks like it's caused by the call to `unification_cast_sql` in `as_sql()`, what happens if you completely remove it?

**Comment by timgraham** [comment]
buildbot, test on oracle.

**Comment by schinckel** [comment]
Yeah, I don't recall whether there was a reason that was there. Probably more that I don't know exactly what it's supposed to do.

No failing tests elsewhere means it's either not needed, or needed for something that's not tested, I guess.

**Pull request merged**
