### PR TITLE
add DANGER as option for contrib/messages for showing ERROR in HTML

### PR DESCRIPTION
**Pull request by dhavalveera**

### CODE REVIEW

**Comment by kyungjunleeme** [comment]
Thank you for accepting my suggestion 
# https://github.com/django/django/pull/15468

**Comment by dhavalveera** [comment]
> Thank you for accepting my suggestion
> # #15468

awaiting for the approval to get merged in main branch

**Comment by felixxm** [comment]
Thanks for this patch :+1: However custom logging levels doesn't need to be builtin in Django.

**Comment by dhavalveera** [comment]
> Thanks for this patch 👍 However custom logging levels doesn't need to be builtin in Django.

I actually made this PATCH request because when we're working with the website, we don't have to re-write the CSS code for alerts or something when we're using Bootstrap or a similar UI Framework, so we don't have to get worried about re-writing the CSS Code, because I've already faced this issue for re-writing the CSS Code, because Django doesn't pass `danger` for Message, and Bootstrap or similar UI Framework doesn't use `error` for showing Error Message.


so if it's get merged then it'll be helpful for a lot of users who are using Alert of Bootstrap or other UI Framework to show error, then `danger` will be really helpful.

**Comment by felixxm** [comment]
@dhavalveera Custom logging levels doesn't need to be builtin into Django, see [docs](https://docs.djangoproject.com/en/4.0/ref/contrib/messages/#creating-custom-message-levels). If you're having trouble understanding how Django works, see [TicketClosingReasons/UseSupportChannels](https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels) for ways to get help.

**Pull request closed without merging**
