### PR TITLE
Fixed #10827 -- Made create_permissions() clear the ContentType cache.

### PR DESCRIPTION
**Pull request by guettli**

### CODE REVIEW

**Comment by timgraham** [comment]
Oops, looks like you forgot to include the fix.

I think it would be nice if we didn't have to resort to mock as it seems this could be more robust to future refactorings. Did you try another other approaches like the one I suggested on the mailing list?

**Comment by guettli** [comment]
Yes, the actual fix was missing. I updated the pull request.

You wrote on the django list:

>I think you should aim for a lower level test which calls create_permissions() and 
> update_contenttypes() in the order described in the ticket description. ///

I have not clue how to change the order. The caller of create_permissions is the emit_post_migrate_signal():

```
File ".../django/core/management/sql.py", line 268, in emit_post_migrate_signal
  using=db)
File ".../django/dispatch/dispatcher.py", line 198, in send
  response = receiver(signal=self, sender=sender, **named)
File ".../django/contrib/auth/management/__init__.py", line 117, in create_permissions
  Permission.objects.using(using).bulk_create(perms)
```

Why not call ContentType.objects.clear_cache() in create_permissions()?

**Comment by guettli** [comment]
Topic **mock**: A lot of other tests in django use this module. I don't understand why I should do more work than necessary. If there will be a refactoring in this area, then my code does not make more work. I guess a  refactoring would be to change the line which imports the library. This can be done by script.

**Comment by timgraham** [comment]
The idea is to try to reproduce the problem reported in the ticket with something like:
```python
def test_permissions_clears_content_type_cache(self):
    # tuncate permissions
    call_command('flush')
    # If the ContentType cache isn't cleared, this will fail with an
    # IntegrityError.
    create_permissions()
```
(not sure of the actual steps)
`mock`

**Comment by kvsn** [comment]
Hi Tim, we've investigated this issue and we think your proposed approach for triggering the IntegrityError is quite hard to implement properly for the following reason (see ticket description):

> The real problem here is that create_permissions and update_contenttypes are both connected to the post_syncdb signal, with the former depending on the latter having been run first, but the dispatcher doesn't guarantee order of dispatch (or rather it dispatches in the order the signal handlers are connected, but that order depends on the order in which modules are loading which is not well-defined).

Therefore, the IntegrityError would only be raised in some cases, making it hard for an assertion to be added to the unit test. Using the mock, as proposed by the original author, seems to make more sense in this case.

There still seems to be a problem in the test though: if you mock the clear_cache method, the test could fail of course due to the caching not being empty :) Thoughts?

**Comment by srkunze** [comment]
Not certain how I can assist with the test. The fix is definitely needed. :)

**Comment by timgraham** [comment]
I'd like a test that reproduces something that currently crashes.

**Comment by srkunze** [comment]
@timgraham Sure, I understand that.

I could imagine that the main issue is when a migration changes the pks of content type. Then the cache still might carry the wrong pks.

**Comment by timgraham** [comment]
Closing due to inactivity.

**Comment by guettli** [comment]
It's ok to close this. People having the same problem should find this issue here. Thank you for cleaning up.

**Comment by thauk-copperleaf** [comment]
We got bit by this problem today on 1.9... didn't come across this until hours later :(

**Comment by fingon** [comment]
Got bit by this in 1.11 as well. Sigh.

**Comment by mahadi** [comment]
Found this in 2.1. Actually i dont understand whats the blocking point to fix it? Only the writing of the test?

**Comment by timgraham** [comment]
Yes

**Pull request closed without merging**
