### PR TITLE
[3.2.x] Updated source translation catalogs.

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by felixxm** [comment]
@claudep Thanks :+1: Do we have any changes in JS catalogs?

**Comment by claudep** [comment]
What do you mean? (djangojs.po in admin **did** change)

**Comment by felixxm** [comment]
> What do you mean? (djangojs.po in admin **did** change)

Ahh, sorry, I missed it.

**Comment by carltongibson** [comment]
Thanks for this @claudep! 🥇

**Pull request merged**
