### PR TITLE
Fixed #32595 -- Fixed SchemaEditor.quote_value() crash with bytes.

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Review by rsiemens — APPROVED** [review]
Thanks for the quick stop gap!

**Review by claudep — APPROVED** [review]
Looks good after a quick glance. Sorry, I'm a bit overloaded right now.

**Comment by felixxm** [comment]
Thanks both for checking :star2:

**Review by carltongibson — APPROVED** [review]
Thanks @felixxm. I think this is reasonable to backport to Django 3.2.

**Pull request merged**
