### PR TITLE
Fixed #26698 -- Fixed a dbshell crashes on Postgres with an empty database name.

### PR DESCRIPTION
**Pull request by mieciu**
https://code.djangoproject.com/ticket/26698

### CODE REVIEW

**Comment by charettes** [comment]
Thanks for your contribution, could you possibly add a mention in the `docs/releases/1.9.7.txt` release notes as this will be backported to the `stable/1.9.x` branch.

**Comment by mieciu** [comment]
Sure thing, done!

**Comment by mieciu** [comment]
Just have to fix dbshell test suite

**Comment by mieciu** [comment]
Tests fixed 👍

**Comment by charettes** [comment]
Buildbot, add to whitelist.

**Comment by mieciu** [comment]
Tests pass locally for me... Looking at the Jenkins UI I can't really tell how my change is related to those failing tests.

**Comment by timgraham** [comment]
merged in 19ff506878071ac93de684fe01328707e75e2b3a, thanks!

**Pull request closed without merging**
