### PR TITLE
Fixed #21588 -- Added a note about passing arguments when modifying upload handlers.

### PR DESCRIPTION
**Pull request by berkerpeksag**
https://code.djangoproject.com/ticket/21588

### CODE REVIEW

**Comment by timgraham** [comment]
Maybe it would be better to incorporate this into the `ProgressBarUploadHandler` example. It seems reasonable that would subclass `FileUploadHandler`.

**Comment by berkerpeksag** [comment]
Thanks, I've updated PR.

**Comment by timgraham** [comment]
What I meant was updating the existing line: `request.upload_handlers.insert(0, ProgressBarUploadHandler())`.

**Comment by berkerpeksag** [comment]
Ok, should I add the following sentence to somewhere near the existing line?

```
[...] your custom handler does require passing some arguments, you
need to pass them at the time of initialization of the handler.
```

**Comment by timgraham** [comment]
With that line updated, I think it seems obvious that you should pass the arguments when initializing the class. Do you think there's any opportunity for confusion about that?

**Comment by berkerpeksag** [comment]
I never wrote a custom handler before but reading the section (even with the `ProgressBarUploadHandler(request)` example)  doesn't say much about another custom parameters so adding a short sentence would be good.

**Comment by timgraham** [comment]
Well, what I mean is, how is that different from any other class that takes custom parameters... of course you need to pass them when initializing it? I guess the point is that you can't use the `FILE_UPLOAD_HANDLERS` setting in that case.

**Comment by berkerpeksag** [comment]
The difference is that you need to know how Django calls upload handlers. I didn't know until reading https://github.com/django/django/blob/master/django/http/request.py#L233 for example.

I just updated the PR to change all ProgressBarUploadHandler() examples to ProgressBarUploadHandler(request).

**Comment by timgraham** [comment]
I think that's good enough. Merged in 8f50ff5b15a742f345dade0848a3fbbf2aff629d, thanks!

**Pull request closed without merging**
