### PR TITLE
Fixed #18119 -- Added a DomainNameValidator validator.

### PR DESCRIPTION
**Pull request by berkerpeksag**
https://code.djangoproject.com/ticket/18119

### CODE REVIEW

**Comment by timgraham** [comment]
This is ready for a rebase and update now that the related PR has been merged.

**Comment by timgraham** [comment]
Please send a new PR if someone can update this.

**Comment by JocelynDelalande** [comment]
@timgraham by update you mean rebase ?

**Comment by timgraham** [comment]
Correct

**Comment by berkerpeksag** [comment]
Unfortunately, rebasing this is not enough:

* There are no tests for IPv4 and IPv6 and I'm not sure whether we should cover them since I haven't fully read the RFC
* The regex in https://github.com/django/django/commit/2e65d56156b622e2393dee1af66e9c799a51924f needs to be modified to conform the RFC (if I remember correctly, we should reject any domain names longer than 255 chars)
* We need more tests (e.g. TLDs longer than 3 chars)
* I'd probably update the default value of accept_idna to False. I don't see much IDNs to make it default behavior and it would be better to avoid mostly unnecessary encoding step by default.

**Comment by dbrgn** [comment]
Any updates on this?

By the way, I disagree with this:

> I'd probably update the default value of accept_idna to False.

An IDN is also a valid domain name.

**Comment by berkerpeksag** [comment]
Yes, it is, but I'm not sure it's common enough to make it a default behavior. [After the discussion on the django-developers list](https://groups.google.com/forum/#!topic/django-developers/ASBJ0ge2KYo), I'd even prefer to remove it in order to have a simpler implementation.

I will address my comments in https://github.com/django/django/pull/3477#issuecomment-137029354 and send a pull request.

Thanks for the ping!

**Comment by jpic** [comment]
Is there any follow up on this ?

**Comment by berkerpeksag** [comment]
Thanks for the ping. I thought I already have opened a PR for this :/ Will open a PR this week.

**Comment by berkerpeksag** [comment]
I've opened https://github.com/django/django/pull/7300 as a follow-up.

**Pull request closed without merging**
