### PR TITLE
[3.0.x] Updated translations from Transifex

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
@felixxm This should be included in 3.0.2, if possible.

**Comment by felixxm** [comment]
Sure, but in 3.0.3?

**Comment by claudep** [comment]
Sure :-)

**Comment by felixxm** [comment]
Thanks Claude :+1:

**Comment by claudep** [comment]
Thanks for merging, will you forward port to master, please?

**Comment by felixxm** [comment]
Done.

**Pull request merged**
