### PR TITLE
Fixed #24925 -- cast dates and times in Value

### PR DESCRIPTION
**Pull request by Ian-Foote**
Add `Value.as_mysql` method to `cast` datetimes, dates and times to their
corresponding MySQL types.

### CODE REVIEW

**Comment by akaariai** [comment]
The only problem here is that will there be some case where doing a cast for datetime, date or time value will break something. It shouldn't, but this being about MySQL it is hard to say if there could be some case that actually breaks.

**Comment by timgraham** [comment]
Does the commit reference the correct ticket (#24925 is closed, should it be reopened?) Also the new test doesn't pass on MySQL.

**Comment by Ian-Foote** [comment]
It was suggested after #24925 was closed that we might be able to do better than just documentation. This is a work in progress, which is why the new test is failing.

**Comment by timgraham** [comment]
All right. Please open a new ticket/pull request if you get something working.

**Pull request closed without merging**
