### PR TITLE
Fixed #32573 -- Query optimization in YearLookup breaks filtering by "__iso_year"

### PR DESCRIPTION
**Pull request by fdemmer**
https://code.djangoproject.com/ticket/32573

### CODE REVIEW

**Review by felixxm — COMMENTED** [review]
@fdemmer Thanks for this patch :+1:

I think we can preserve an optimization with different boundaries, e.g. calculated from [date.fromisocalendar()](https://docs.python.org/3/library/datetime.html#datetime.date.fromisocalendar) (available in Python 3.8+):
```python
>>> import datetime
>>> datetime.datetime.fromisocalendar(2015, 1, 1)
datetime.datetime(2014, 12, 29, 0, 0)
>>> datetime.datetime.fromisocalendar(2016, 1, 1) - datetime.timedelta(days=1)
datetime.datetime(2016, 1, 3, 0, 0)
```

What do you think?

**Comment by fdemmer** [comment]
I think the optimization was not the best idea in the first place (to be fair: it probalby _was_ back then, but the ORM has evolved a lot), so I would not try to rebuild it for this.

My expectation as a "user" of the ORM is, that it should make my life easier and handle things under the hood for me (like making joins and other amazing things), but when I explicitly use something like `ExtractIsoYear` it should absolutely not go ahead and generate a query with a different database operation.

IMHO, it would be bettter to suggest/document using a [functional index](https://www.postgresql.org/docs/7.3/indexes-functional.html) with EXTRACT. I haven't tried it, but that _should_ [already be possible via the ORM](https://docs.djangoproject.com/en/2.2/ref/models/indexes/).

**Comment by ljodal** [comment]
Hi, I don't have any strong opinions on whether this optimization should be kept or not, but wanted to chime in that in case we want to fix this with support for older versions of Python the same can be achieved using `datetime.strptime`:

```
In [32]: datetime.datetime.strptime('2020-1-1', '%G-%V-%u').date()
Out[32]: datetime.date(2019, 12, 30)
```

**Comment by felixxm** [comment]
> Hi, I don't have any strong opinions on whether this optimization should be kept or not, but wanted to chime in that in case we want to fix this with support for older versions of Python the same can be achieved using `datetime.strptime`:
> 
> ```
> In [32]: datetime.datetime.strptime('2020-1-1', '%G-%V-%u').date()
> Out[32]: datetime.date(2019, 12, 30)
> ```

Django 4.0 (the current `main` branch) supports only Python 3.8+.

**Comment by felixxm** [comment]
> I think the optimization was not the best idea in the first place (to be fair: it probalby _was_ back then, but the ORM has evolved a lot), so I would not try to rebuild it for this.
> 
> My expectation as a "user" of the ORM is, that it should make my life easier and handle things under the hood for me (like making joins and other amazing things), but when I explicitly use something like `ExtractIsoYear` it should absolutely not go ahead and generate a query with a different database operation.
> 
> IMHO, it would be bettter to suggest/document using a [functional index](https://www.postgresql.org/docs/7.3/indexes-functional.html) with EXTRACT. I haven't tried it, but that _should_ [already be possible via the ORM](https://docs.djangoproject.com/en/2.2/ref/models/indexes/).

This optimization has been in Django since 4c4209b14449554382b541d709749340f9b1a7ae :calendar:, support for functional indexes was recently added in Django 3.2 (still a release candidate). We can consider dropping it (with the deprecation period) but that's a separate issue, and dropping it only the `__iso_year` lookup would be even more confusing for users.

**Comment by charettes** [comment]
On top of what @felixxm already said it seems wasteful to me to ask users to create a functional index on the extract when the value can already be fetched by boundaries at least for lookups.

It feels like we should keep having `__year` and `__isoyear` lookups use the `BETWEEN` optimizations like they've done for years but ensure that filtering against explicit `Extract(Iso?)Year` doesn't. After all how these lookups are working is an implementation detail while I would consider it normal to expect that`.annotate(year=ExtractYear('date')).filter(year=2020)` uses `WHERE EXTRACT(YEAR FROM 'date') = 2020`. There is backward compatibility concerns to deal with here though so we should likely just focus on getting things working without changing things too much for now.

**Comment by fdemmer** [comment]
Thank you for all your feedback! I was under the impression functional indexes were already supported in 2.2 -- that obviously changes things.

I've opened https://github.com/django/django/pull/14170 with extended year boundary calculation to keep the optimization. This is now based on the `main` branch, but since 2.2 is still supported for another year I'd apprechiate a backport to 2.2.

It would also be excellent if someone could look into keeping explicit `ExtractYear` annotations in 3.2 or 4.x now that functional indexes are supported. I have no idea how to accomplish that with my current understanding of the innerts of the ORM :grimacing:

**Comment by felixxm** [comment]
> I've opened #14170 with extended year boundary calculation to keep the optimization. This is now based on the main branch, but since 2.2 is still supported for another year I'd apprechiate a backport to 2.2.

The issue has been present since the feature was introduced. Per our backporting policy this means it doesn't qualify for a backport anymore. See https://docs.djangoproject.com/en/stable/internals/release-process/ for more details.

Moreover, Django 2.2 is in extended support so it receives only security fixes.

**Pull request closed without merging**
