### PR TITLE
Refs #27795 -- Replaced force_bytes() usage in django.http

### PR DESCRIPTION
**Pull request by auvipy**
@jdufresne could you review

### CODE REVIEW

**Comment by timgraham** [comment]
Please ensure the tests are passing before asking for a review. This takes something thinking, you can't just do blind replacements.

**Comment by jdufresne** [comment]
Once ready, will probably want to adjust the comment at:

```
./django/http/response.py:224:        # Handle string types -- we can't rely on force_bytes here because:
```

To mention some operation other than `force_bytes`.

**Comment by timgraham** [comment]
I've pushed a working patch here. I think it would still be correct to reference `force_bytes()` in the comment, but I've proposed to remove it.

**Comment by auvipy** [comment]
great

**Pull request merged**
