### PR TITLE
Added a link in README.rst for people new to IRC.

### PR DESCRIPTION
**Pull request by kataria101**

### CODE REVIEW

**Comment by timgraham** [comment]
Maybe this could use some clarification but it isn't a typo. When configuring your iRC client, the address to use is irc.freenode.net.

**Comment by kataria101** [comment]
I came across this when I myself wanted to join for the IRC.
In order to join the channel it is required to have a nickname and an account(with username and pass) for recurrent usage.
I figured that the address given as irc.freenode.net does not run in the browser.
The link to register is https://freenode.net/

**Comment by atombrella** [comment]
@kataria101 You can also register using an IRC client, although it may be not as intuitive as filling out the form on https://freenode.net Feel free to try to incorporate something like this in the sentence:

It's required to register before you can join the channel and write messages. This can either be done using an IRC client, the instructions are available with the `/msg nickserv help` when you're logged on to a freenode server, or you may register at https://freenode.net

**Comment by kataria101** [comment]
@atombrella Thanks! That looks like a good suggestion.

**Comment by timgraham** [comment]
Maybe add this sentence: See https://en.wikipedia.org/wiki/Wikipedia:IRC/Tutorial if you're new to IRC.

**Pull request merged**
