### PR TITLE
Fixed #25385 -- Allowed importing views.generic.View from views.View.

### PR DESCRIPTION
**Pull request by auvipy**
docs and release note needed

### CODE REVIEW

**Comment by auvipy** [comment]
@timgraham release note for 1.10 and doc refs?

**Comment by auvipy** [comment]
unsure where to add docs actually

**Comment by timgraham** [comment]
Yes, please look at all the places where `django.views.generic.base.View` is currently documented and try to find a place where it makes sense to mention this.

**Comment by auvipy** [comment]
https://docs.djangoproject.com/en/dev/ref/class-based-views/ this says RedirectView and templateview is located in Base View, are they normal views? or generic views?

**Comment by timgraham** [comment]
Closing in favor of https://github.com/django/django/pull/5951.

**Pull request closed without merging**
