### PR TITLE
 Fixed #29324 -- Made SECRET_KEY validation lazy (on first access).

### PR DESCRIPTION
**Pull request by apollo13**
Requires #13239 to be merged first

ticket-29324

### CODE REVIEW

**Comment by apollo13** [comment]
@carltongibson May I ask you to write the release notes (If we need some at all?). In theory you can merge just this PR instead of #13239 and this one, or merge the other first and then rebase.

**Comment by carltongibson** [comment]
No problem @apollo13. I'll look at it this week. Thanks.

**Comment by carltongibson** [comment]
@apollo13: With this patch:

```
>>> from django.conf import settings
>>> settings.configure()
>>> settings.SECRET_KEY
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/carlton/Documents/Django-Stack/django/django/conf/__init__.py", line 85, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

```

**Comment by carltongibson** [comment]
Which is the desired behaviour, I think.

**Comment by carltongibson** [comment]
@kezabelle Don't know if you want to glance at this? 🙂

**Comment by apollo13** [comment]
> @apollo13: With this patch:
> 
> ```
> >>> from django.conf import settings
> >>> settings.configure()
> >>> settings.SECRET_KEY
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/carlton/Documents/Django-Stack/django/django/conf/__init__.py", line 85, in __getattr__
>     raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
> django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
> ```

This is good to see. That means that this patch makes the behaviour actually "more" correct. Because master currently lets you access `settings.SECRET_KEY` after `settings.configure()` even though it is an empty string.

**Comment by kezabelle** [comment]
late to the party, but I have had a glance at it. Made sense for all the scenarios I can think of.

**Comment by carltongibson** [comment]
Thanks @kezabelle

**Pull request merged**
