### PR TITLE
 Fixed #24526 -- Combined django.request/security loggers with the root logger.

### PR DESCRIPTION
**Pull request by timgraham**
https://code.djangoproject.com/ticket/24526

### CODE REVIEW

**Comment by timgraham** [comment]
This change may or may not be needed/useful. Discussion continues... https://groups.google.com/d/topic/django-developers/no2IhnRty68/discussion

**Comment by carljm** [comment]
It seems to me that this change is an improvement regardless of how exactly `disable_existing_loggers` behaves. It makes it easier for someone to build on top of Django's default logging config, and make their own use of the information logged by `django.request` and `django.security`.

**Comment by timgraham** [comment]
I remove the explicit definitions for `django.request` and `django.security` loggers and added a `mail_admins` handler to the `django` catch all logger. This seems like a simpler solution which will make it easier to add more loggers in the future, let me know if you see any drawbacks. If not, I'll complete the docs, etc.

**Comment by carljm** [comment]
Makes sense to me! Much simpler.

**Comment by claudep** [comment]
Just by quickly reading the patch, it appears this might send a ton of log messages to the admins. I'll need to dig a little to see if it's indeed the case, but not for tonight.

**Comment by timgraham** [comment]
Maybe there's some other problem you see, but the `mail_admins` handler still filters at `'level': 'ERROR'`.

**Comment by carljm** [comment]
@claudep I don't think so, because the `mail_admins` handler itself has `'level': 'ERROR'`, and Django does not currently log any messages above `DEBUG` level outside of `django.request` and `django.security`.

I think it's true that this change represents a possible future difference in behavior, in that it would mean that if we ever logged something at `ERROR` level in any other `django.*` logger, that would also get mailed to admins. But tbh that doesn't seem like a bad thing.

**Comment by claudep** [comment]
Understood. Then let's go ahead.

**Comment by timgraham** [comment]
Docs and test suite updated and ready for review.

**Comment by carljm** [comment]
LGTM

**Pull request merged**
