### PR TITLE
Fixed #24980 -- Fixed day determination in admin calendar widget

### PR DESCRIPTION
**Pull request by sasha0**

### CODE REVIEW

**Comment by timgraham** [comment]
Feasible to write a test?

**Comment by sasha0** [comment]
Done - updated existing test. Despite all tests pass locally in browser, they failed in CI.
Could you please check?

**Comment by timgraham** [comment]
That test fails for me in a browser and on the command line. Could it be dependent on the system's timezone?

**Comment by sasha0** [comment]
Yes. What timezone do you have locally? So I could test it too.

**Comment by timgraham** [comment]
UTC-5

**Comment by sasha0** [comment]
Done - updated test, made it consider all time zones of the world.

**Comment by sasha0** [comment]
Do we want to add also selenium test for this PR?

**Comment by timgraham** [comment]
A JavaScript test might be sufficient -- I haven't reviewed this issue yet. In general, prefer a JavaScript test as long as it covers the issue since selenium tests can be flaky.

**Comment by timgraham** [comment]
buildbot, test on selenium.

**Comment by timgraham** [comment]
@maxocub, as the author of the original patch (25e06bca57c068d4b9e9b4221b16a667ccb0d38e), could you +1 this? 

@sasha0, I found this is a regression in 1.8 so could you please add release notes for 1.9.2 and 1.8.9? Thanks.

**Comment by maxocub** [comment]
+1

**Comment by sasha0** [comment]
> @sasha0, I found this is a regression in 1.8 so could you please add release notes for 1.9.2 and 1.8.9? Thanks.

Sure, done.

**Comment by timgraham** [comment]
merged in 44930cc4667268c20493d7e97387db2a97d61a26, thanks!

**Pull request closed without merging**
