### PR TITLE
Imported django.http classes instead of django.http.

### PR DESCRIPTION
**Pull request by auvipy**
first pass @timgraham

### CODE REVIEW

**Comment by auvipy** [comment]
continuation line over indented for visual .....

**Comment by timgraham** [comment]
Please use the indentation in `contenttypes/views.py` from the other PR.

**Comment by auvipy** [comment]
OK.

**Comment by auvipy** [comment]
done

**Comment by timgraham** [comment]
Changes remain:
django/contrib/admindocs/middleware.py:from django import http
docs/topics/i18n/translation.txt:    from django import http
tests/messages_tests/base.py:from django import http
tests/messages_tests/test_middleware.py:from django import http
tests/redirects_tests/tests.py:from django import http

**Comment by auvipy** [comment]
thanks for pointing. will update accordingly

**Comment by auvipy** [comment]
hopefully this is done

**Pull request merged**
