### PR TITLE
Small simplifies template/library.py:filter, templatetags/cache.py: render, utils/log.py:emit

### PR DESCRIPTION
**Pull request by proggga**
Simplified try/catch block in utils/log:emit

Join two try/catch into one, remove code duplication

Make if conditions easier to read (they was too complicated) in template/library:filter

### CODE REVIEW

**Comment by proggga** [comment]
About code coverage, I removed big copypaste code, so present of coverage decreased, but actually nothing happend
image

**Comment by pope1ni** [comment]
Thanks, but I'm not sure I agree that these changes are more readable.

**Comment by proggga** [comment]
May be can revert some of them, Ive made different commits

**Comment by proggga** [comment]
And I removed code duplicate, that not bad, why rejected;(

**Pull request closed without merging**
