### PR TITLE
[2.2.x] Fixed #32856 -- Fixed compatibility with psycopg 2.9

### PR DESCRIPTION
**Pull request by dvarrazzo**
ticket-32856

Refs https://github.com/psycopg/psycopg2/issues/1293

### CODE REVIEW

**Review by carltongibson — COMMENTED** [review]
Hey @dvarrazzo — thanks for this. 

Erm... 😬

So normal policy is for fixes to go into the development branch, which is Django 4.0, due September. 

In theory we could backport to the supported release branches... — but ideally we'd avoid the break in psycopg2. (Can you explain the issue for me?) 

/cc @charettes 

It's a small change. We'd need a release note and test case.

**Comment by coderanger** [comment]
@carltongibson Django 2.2 still has a safety check to ensure Postgres is running in UTC. This check was removed in Django 3.1 when multi-TZ support for Postgres was added. That check is implemented by looking at `offset == 0`. Psycopg 2.9 changes the offset value from an integer to a timedelta object. So the check now fails as `timedelta(0) != 0`. Either all Django 2.2 Postgres users need to pin to Psycopg 2.8.6, or we something in Django, or Psycopg needs to revert the change.

**Comment by carltongibson** [comment]
@coderanger Thanks! 

> Either all Django 2.2 Postgres users need to pin to Psycopg 2.8.6, or we do something in Django, or Psycopg needs to revert the change.

Yes. 2.2 is in extended support, so normally "pin to Psycopg 2.8.6" would be the answer there. But let's see what Simon and Mariusz say (not @mentioning Mariusz because he's on holiday this week 😀)

**Comment by coderanger** [comment]
Not making a value judgement on any of those three, pinning seems fine but maybe a short blog post just to let people know :)

**Comment by carltongibson** [comment]
I hadn't noticed this was targeting `django:stable/2.2.x`.

**Comment by coderanger** [comment]
3.1 and above have no conflict with the Psycopg 2.9 change as they no longer use the offset value at all (they ignore it in favor of the Django-managed DB timezone).

**Comment by dvarrazzo** [comment]
@coderanger thank you very much for explaining everything :)

**Comment by dvarrazzo** [comment]
@carltongibson I apologise for the breakage: when making that change I kept Django in consideration to assess repercussions and I saw that the `tzinfo_factory` parameter is ignored.

https://github.com/django/django/blob/225d96533a8e05debd402a2bfe566487cc27d95f/django/db/backends/postgresql/base.py#L252-L253

However I only checked it on master and didn't expect older but still maintained versions were so different.

The change was needed on our side in order to fix https://github.com/psycopg/psycopg2/issues/1272 and drop a possible 30s error on  timestamps, now that Python 3.7 allows sub-minute resolution timezones. The constructor for `FixedOffsetTimezone` used to take the integer number of minutes so breaking this interface seems necessary for it, and adopting the same interface of `datetime.timezone()` seems the best thing to do moving on (`FixedOffsetTimezone` predates `datetime.timezone`).

**Comment by carltongibson** [comment]
Thanks for the follow-up @dvarrazzo. I don't think it's a big problem. Having to pin is a realistic assumption if one is going to hang out on old versions. Let me see what the others say.

**Comment by dvarrazzo** [comment]
If someone is pinning `Django < 2.3` in their requirement file, pinning `psycopg2 < 2.9` seems reasonable to do, yes.

**Comment by felixxm** [comment]
Closing per ticket, see also #14547.

**Comment by zyv** [comment]
Having literally everyone still using Django 2.2 LTS with Postgres to pin `psycopg` is not a very user-friendly solution.

I understand that this is the current interpretation of the LTS policy, but as on several previous occasions as trivial fixes were not included in the past, I'd like to reiterate that it's not necessarily a policy that makes an LTS more useful. The whole idea of an LTS is basically to give users some leeway with the upgrade schedule so that they can better reconcile it with their internal projects, and not shipping fixes making LTS still useable until the termination of support has the effect of nudging of the users to upgrade irrespectively of their internal schedules. We have lost almost a man-day of dealing with the fallout, and these resources would have been much better spent to contribute to Django...

Anyways, it's a pity that Django is not shipping optional packages like `Django[postgres]`, in which case one could have at least made possible to pin it globally for all those depending on the optional package.

**Comment by nikitagrygoriev** [comment]
> If someone is pinning `Django < 2.3` in their requirement file, pinning `psycopg2 < 2.9` seems reasonable to do, yes.

In case anyone stumbles upon this issue, psycopg<2.9 is not available for Python 3.10, so you have to use Python <3.9.x as well.

**Comment by sshishov** [comment]
I have a question... What is wrong with this PR? Instead of checking for the `int` it is checking if it is `falsy` where `0 (int)` and `timedelta(0)` are both falsy. And it is needed only for `2.2.x` version.
Why the maintainers are against to merge this FIX into `2.2.x` version?

**Comment by felixxm** [comment]
> Why the maintainers are against to merge this FIX into 2.2.x version?

Because Django 2.2 is in extended supports and doesn't receive new features or bugfixes (except security issues) anymore, see [Django’s release process](https://docs.djangoproject.com/en/stable/internals/release-process/) for more details.

**Comment by luzfcb** [comment]
Is psycopg2 2.8.6 compatible with PostgreSQL 14.x?:

For everyone who has the same question, maybe we will have an answer in https://github.com/psycopg/psycopg2/discussions/1441

**Comment by dvarrazzo** [comment]
@luzfcb 

> Is psycopg2 2.8.6 compatible with PostgreSQL 14.x?:

Yes it is.

**Pull request closed without merging**
