### PR TITLE
Refs #27468 -- Made user sessions use SHA-256 algorithm.

### PR DESCRIPTION
**Pull request by felixxm**
ticket-27468

### CODE REVIEW

**Comment by felixxm** [comment]
I think we should rotate legacy sessions on login, that's why I didn't change anything in `login()`.

**Comment by carltongibson** [comment]
Not sure about the CI failure there...

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Comment by felixxm** [comment]
Thanks y'all :star:

**Pull request merged**
