### PR TITLE
Refs #32673 -- Fixed lookups crash when comparing against lookups on Oracle.

### PR DESCRIPTION
**Pull request by felixxm**
ticket-32673

Based on #14302.

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Review by charettes — APPROVED** [review]
Glad to see we can reuse `conditional_expression_supported_in_where_clause` for this purpose.

**Review by carltongibson — APPROVED** [review]
OK, looks good. Thanks.

**Comment by carltongibson** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
Thanks both :rocket:

**Pull request merged**
