### PR TITLE
Compile sql parameters to lists instead of tuples

### PR DESCRIPTION
**Pull request by tuky**
Here's the corresponding ticket: https://code.djangoproject.com/ticket/30529#ticket. In some places I omitted the explicit `list` conversion. It might however be necessary to not break 3rd party compilers.

It occurs to me, that the use of tuples maybe was intentional, because they are immutable?!

### CODE REVIEW

**Comment by charettes** [comment]
FWIW I always felt like we should have made the public facing expression API's `as_sql` return `(:str, :tuple)` instead of `(:str, :list)` but now that this extension point as been around for a while we have no choices but to keep supporting both signatures.

Changing the signature of the internal compiler APIs `as_sql` to return `(:str, :tuple)` is likely to cause more harm than good though given for how long they've been using this signature.

My opinion is that if there was a regression in 2.2 with regards to a particular `as_sql` we should address it but we should leave the other methods untouched.

**Comment by tuky** [comment]
thx, for now i will put more efforts into this like fixing tests. it seems reasonable to me, to stay with tuples.

**Comment by felixxm** [comment]
I agree with Simon we should stay with tuples and support both signatures. This decision was made a long time ago :older_man: . Please describe a specific issue in a ticket description.

**Comment by adamchainz** [comment]
Thanks all for going over this. I'm fixing all expressions in Django-MySQL to use tuples for params in every case.

**Pull request closed without merging**
