### PR TITLE
Fixed #31027 -- Replaced .getAttribute()/.setAttribute() usage with DOM properties.

### PR DESCRIPTION
**Pull request by jdufresne**
https://code.djangoproject.com/ticket/31027

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Comment by jdufresne** [comment]
buildbot, test on selenium.

**Comment by felixxm** [comment]
@jdufresne Thanks :+1: I updated `collapse.min.js`.

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Pull request merged**
