### PR TITLE
Fixed #18468 -- Added support for SQL comments in tables and columns.

### PR DESCRIPTION
**Pull request by KimSoungRyoul**
why don't you support SQL COMMENT ?

help_text is useful for Developer  

**BUT** 

**DBA can not understand Django Models** 
They want to see db_comment with SQL not Python

This Issue causes a loss of communication costs between Developer to DBA

#### Summary
* ##### CREATE TABLE with comment
* ##### ALTER TABLE with comment
* ##### ADD FIeld with comment
* ##### ALTER Field with comment

### CODE REVIEW

**Comment by KimSoungRyoul** [comment]
close this pullRequest 

and i will reopen after modification

**Comment by KimSoungRyoul** [comment]
@felixxm 
By the way  i want to use this feature in version 2.2.x also 

if i pull request to 2.2.2 , is it able to merge?

**Comment by felixxm** [comment]
> if i pull request to 2.2.2 , is it able to merge?

No, we don't accept new features to the Django 2.2 or 3.0. This should be targeted to the Django 3.1.

**Comment by KimSoungRyoul** [comment]
@felixxm 

#### could you give me a feedback? 

i 'm planning to work on Postgresql  ,  Oracle  

but there is no more feedback to this feature

https://code.djangoproject.com/ticket/18468
https://groups.google.com/forum/?nomobile=true#!topic/django-developers/guVTzO3RhUs

I'm confused  at the thought doing something useless.

**Comment by KimSoungRyoul** [comment]
```Adding a new setting is always a bit controversial```
i agree your opinion

**Comment by KimSoungRyoul** [comment]
#### support postgresql db_comment
#### support oracle db_comment

**Comment by KimSoungRyoul** [comment]
@felixxm 
would you mind if you could feedback for this PullRequest?

**Comment by felixxm** [comment]
Closing due to inactivity.

**Pull request closed without merging**
