### PR TITLE
Fixed #29738 -- Changed serializer_factory so that unserializable values can be migrated

### PR DESCRIPTION
**Pull request by cansarigol**
I've changed my forked project branch as ticket_29738

### CODE REVIEW

**Comment by charettes** [comment]
One of the issue raised by Tim on the ticket is that relying on `__module__` can cause an undocumented path to be used for imports and is likely to break in the future.

For example, [`DateTimeTZRange` is documented as being importable from `psycopg2.extras`](http://initd.org/psycopg/docs/extras.html?highlight=datetimetzrange#psycopg2.extras.DateTimeTZRange) but is defined in `psycopg2._range` which should be considered an implementation detail. Using `psycopg2._range` instead of `psycopg2.extras` as an import path is more likely to break for the lifetime of a project given migration files are kept around for a while.

**Comment by cansarigol** [comment]
ok, I understand. What do you think about renaming the built-in modules? I researched and couldn't find sort of list that contains all built-in functions.

**Comment by cansarigol** [comment]
By the way, sorry about these commits. I couldn't handle the skipUnless about my case. I think that my test approach is wrong. Can you give any suggestion?

**Comment by timgraham** [comment]
Looking for the import in "extras" isn't a general solution. That happens to fix this case for psycopg2, but it isn't generalizable to other packages. I'm not sure how to solve that issue offhand.

The tests should remain in ` tests/migrations` rather than in `postgres_tests`. If the import issue can be solved, we can create a test in `tests/migrations` that simulates what `psycopg2` does with imports.

**Comment by cansarigol** [comment]
> Looking for the import in "extras" isn't a general solution. That happens to fix this case for psycopg2, but it isn't generalizable to other packages. I'm not sure how to solve that issue offhand.
> 
> The tests should remain in `tests/migrations` rather than in `postgres_tests`. If the import issue can be solved, we can create a test in `tests/migrations` that simulates what `psycopg2` does with imports.

ok, I'm trying to solve this. It is instructive for me.

**Comment by cansarigol** [comment]
as the last try :) I tried to find a convenient module in the same package.

**Pull request closed without merging**
