### PR TITLE
Complete test coverage for django/utils/lorem_ipsum.py

### PR DESCRIPTION
**Pull request by idanmel**
Fixed import sort

### CODE REVIEW

**Comment by idanmel** [comment]
Not sure how this doesn't pass.
Earlier only the isort check didn't pass.

And all the tests do pass on my end.

**Comment by orf** [comment]
That does seem strange, I would try rebasing the branch on master and pushing to trigger a new build.

**Comment by idanmel** [comment]
Thanks orf, it passes now :+1:

**Comment by orf** [comment]
Hmm @idanmel, I think you've made a mistake rebasing. It seems you applied the new commits on top of the changes you made, rather than the changes you made on top of the new commits. Git rebasing can be a bit of a b***, 

I'd do the following:

```
git checkout master && git pull upstream master
git branch my-new-branch
git cherry-pick 5051bdb5835e39ece3c1488e0e8000f6161e59e3
```

Then make a new MR with the `my-new-brach`. Or, ask in the #django irc channel for some help (I'm sure there is a cleaner way to do this!)

**Pull request closed without merging**
