### PR TITLE
Removed unused Query.clone() memo kwarg.

### PR DESCRIPTION
**Pull request by timgraham**
Unused since 23ca3a01940c63942885df4709712cebf4df79ec.

### CODE REVIEW

**Comment by timgraham** [comment]
`Query.__deepcopy__()` was part of the original [queryset refactor](https://github.com/django/django/commit/9c52d56f6f8a9cdafb231adf9f4110473099c9b5#diff-0edd853580d56db07e4020728d59e193R97). I'm not sure if no failing tests with it removed means that it's okay to remove it or if test coverage is lacking. It appears that it's only called in one test from 3508a86ddf:
```
======================================================================
FAIL: test_deepcopy_and_circular_references (many_to_one.tests.ManyToOneTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/tests/many_to_one/tests.py", line 420, in test_deepcopy_and_circular_references
    self.assertEqual(repr(deepcopy(self.r)), "<Reporter: John Smith>")
  File "/home/tim/.virtualenvs/django352/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/tim/.virtualenvs/django352/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/tim/.virtualenvs/django352/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/tim/.virtualenvs/django352/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/tim/.virtualenvs/django352/lib/python3.5/copy.py", line 166, in deepcopy
    y = copier(memo)
  File "/home/tim/code/django/django/db/models/query.py", line 191, in __deepcopy__
    obj.__dict__[k] = copy.deepcopy(v, memo)
  File "/home/tim/.virtualenvs/django352/lib/python3.5/copy.py", line 166, in deepcopy
    y = copier(memo)
  File "/home/tim/code/django/django/db/models/sql/query.py", line 244, in __deepcopy__
    assert False
AssertionError
```
@holvianssi, @jarshwah, @charettes -- any suggestions?

**Comment by timgraham** [comment]
At the commit before the one you mentioned, I don't see any test failures with `__deepcopy__` removed so that's why I thought test coverage might be lacking. That implementation is:
```python
def __deepcopy__(self, memo):
    result= self.clone()
    memo[id(self)] = result
    return result
```
Any idea what the purpose of that is?

**Comment by holvianssi** [comment]
I believe the reason for `__deepcopy__ ` is to limit the amount of work when a queryset is deepcopied. Might be that Django used `__deepcopy__` after queryset refactor for cloning, but that's not the case any more. If we remove the `__deepcopy__` method from queryset, things will work, but the deecopy is slower.

The memo argument should be safe to remove from clone.

**Comment by timgraham** [comment]
Thanks Anssi, I'll keep the method and add a docstring about it.

**Pull request merged**
