### PR TITLE
Exclude the files created in __pycache__ directory

### PR DESCRIPTION
**Pull request by srinivasreddy**

### CODE REVIEW

**Comment by timgraham** [comment]
Is the regression test working correctly? I don't see any failures with the patch reverted.

**Comment by srinivasreddy** [comment]
According to this PEP-3147  https://www.python.org/dev/peps/pep-3147/  python will only create __pycache__ directory, if the package has been accessed. I don't  understand why  the build machine importing `filepathfield_test_dir`, which isn't used anywhere in the code.

**Comment by srinivasreddy** [comment]
Just saw the build console log, May be while importing test packages before running tests, it will create `__pycache__` folders recursively

**Comment by srinivasreddy** [comment]
I found the reason, the test cases aren't failing because  there is a regex pattern matching in the test case code. https://github.com/django/django/blob/master/tests/forms_tests/field_tests/test_filepathfield.py#L57-L61

**Comment by timgraham** [comment]
Upon further consideration, I think we can skip explicit test for this. Committing `__pycache__` and `.pyc` files doesn't seem worth it. At least for me, they are incompatible with my post-checkout git hooks:
```
find . -name "*.pyc" -delete
find . -type d -empty -delete
```

**Pull request closed without merging**
