### PR TITLE
Fixed #24858 -- Added custom _get_FIELD_display to ArrayField

### PR DESCRIPTION
**Pull request by artursmet**
Improved patch by @asser https://github.com/django/django/pull/6381

### CODE REVIEW

**Comment by artursmet** [comment]
I don't know how to squash my changed properly, because original patch (logic) was written by @asser and I just fixed the tests.

**Comment by asser** [comment]
Hey, thanks for picking this up! Let me know if I can help :-)

**Comment by asser** [comment]
Looking at it again, I guess part of the problem is that not all the new code is covered by the tests, so they would need to be extended I think (which is why I never got back to it).

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
Yes, as I said on the previous PR, this seems to duplicate a lot of code. It would be nice to try for a more elegant solution.

**Comment by timgraham** [comment]
Closing due to inactivity.

**Pull request closed without merging**
