### PR TITLE
Refs #29926 -- Added Python 3.8 to classifiers and tox.ini.

### PR DESCRIPTION
**Pull request by Djailla**

### CODE REVIEW

**Comment by felixxm** [comment]
@auvipy No, Python 3.8 is already mentioned in the documentation.

**Comment by Djailla** [comment]
So what should I do, is my PR ok ?

**Comment by felixxm** [comment]
@Djailla Yes it is fine. Thanks.

**Comment by Djailla** [comment]
@felixxm what should I do next ? Wait for other reviews ?

**Comment by felixxm** [comment]
@Djailla You don't need to do anything. I'm going to merge this when we confirm support for Python 3.8.

**Pull request merged**
