### PR TITLE
Fixed #25441 -- Added support for negative filesize to filesizeformat template filter.

### PR DESCRIPTION
**Pull request by suffrage**
I need to show the difference of sizes, it can be negative.

### CODE REVIEW

**Comment by timgraham** [comment]
Please open a Trac ticket to to track the issue. Regression tests are also required.

**Comment by suffrage** [comment]
sorry, how can i do it?

**Comment by timgraham** [comment]
https://docs.djangoproject.com/en/dev/internals/contributing/ describes the process.

**Comment by suffrage** [comment]
https://code.djangoproject.com/ticket/25441

**Comment by suffrage** [comment]
ok?

**Comment by timgraham** [comment]
Okay so far, but tests are still needed.

**Comment by timgraham** [comment]
Do you want to try to add tests or should we close this and see if someone else comes along and does so?

**Comment by timgraham** [comment]
Updated in https://github.com/django/django/pull/5475.

**Pull request closed without merging**
