### PR TITLE
Refs #30581 -- Allowed sql.Query to be used without model.

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by Gagaro** [comment]
Maybe the `allow_joins` thing was actually for oracle? I don't know enough about oracle to tell about it though.

**Comment by felixxm** [comment]
> Maybe the `allow_joins` thing was actually for oracle? I don't know enough about oracle to tell about it though.

No, it's sth different. It seems that generated SQL is not valid on Oracle, I will check it tomorrow.

**Comment by felixxm** [comment]
@Gagaro Oracle doesn't support boolean expressions in the `SELECT` clause, so we need to wrap it with `CASE WHEN` expression. I fixed tests.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by Gagaro** [comment]
> @Gagaro Oracle doesn't support boolean expressions in the `SELECT` clause, so we need to wrap it with `CASE WHEN` expression. I fixed tests.

Awesome, thanks for looking that up.

**Pull request merged**
