### PR TITLE
Fixed typo of check-in in contributing doc

### PR DESCRIPTION
**Pull request by kdotmanoj**
# Trac ticket number

ticket-N/A

# Branch description
Corrected the term "checkin" to "check-in" for consistency with standard usage.

# Checklist
- [ ] This PR targets the `main` branch. 
- [x] The commit message is written in past tense, mentions the ticket number, and ends with a period.
- [ ] I have checked the "Has patch" ticket flag in the Trac system.
- [ ] I have added or updated relevant tests.
- [ ] I have added or updated relevant docs, including release notes if applicable.
- [ ] I have attached screenshots in both light and dark modes for any UI changes.

### CODE REVIEW

**Comment by kdotmanoj** [comment]
@sarahboyce can you please review this pr :)

**Comment by smithdc1** [comment]
There are many uses of checkin in the docs. It's also what is used in trac. I think we should make the change everywhere if we were to do this. 

I'm not sure the current phrase is wrong. We're aiming for `en-us` here, and as far as I'm aware hypens are generally avoided. Aleast compared to  `en-gb`.

**Comment by sarahboyce** [comment]
We have a state in Trac of "Ready for checkin". This is consistent with this and is part of our contributing docs
If we want to update this, I think it should be updated in Trac first :+1:

**Comment by kdotmanoj** [comment]
Thank you both for reviewing and giving appropriate feedback!

**Pull request closed without merging**
