### PR TITLE
Refs #31676 -- Used term "merger" instead of "committer" in docs.

### PR DESCRIPTION
**Pull request by felixxm**
Follow up to caa2dd08c4722c8702588f5dfe1fa4c506aa66fc.

- [x] I still need to figure out how to update `triage_process.graffle` and regenerate `triage_process.pdf` on Linux (`OmniGraffle` should do the trick on MacOS :thinking:  \cc @carltongibson).

### CODE REVIEW

**Comment by carltongibson** [comment]
> OmniGraffle should do the trick…

On it. 👍

**Comment by carltongibson** [comment]
Screenshot 2022-03-22 at 08 49 24

The SVG edit isn't right... — will re-export from OG.

**Comment by felixxm** [comment]
> Screenshot 2022-03-22 at 08 49 24
> 
> The SVG edit isn't right... — will re-export from OG.

I expected this :+1: I added it mainly to show which texts should be changed.

**Review by carltongibson — APPROVED** [review]
OK, thanks. 

I updated the source OmniGraffle file, and re-exported the two images.

**Comment by felixxm** [comment]
> I updated the source OmniGraffle file, and re-exported the two images.

Looks good, thanks :gift:

**Pull request merged**
