### PR TITLE
Fixed 35222: updated tablespace tests

### PR DESCRIPTION
**Pull request by bcail**

### CODE REVIEW

**Comment by nessita** [comment]
Hey @bcail, any chance you could fix the lint issue to ease the review? Thank you!

**Comment by bcail** [comment]
@nessita Sure, I fixed the linters. I can look into the failing tests - not sure what's happening there, postgres tests pass locally.

**Comment by felixxm** [comment]
> @nessita Sure, I fixed the linters. I can look into the failing tests - not sure what's happening there, postgres tests pass locally.

`DEFAULT_TABLESPACE` and `DEFAULT_INDEX_TABLESPACE` are specified for PostgreSQL tests on Jenkins to cover both cases with and without these settings. That's why I tried to explain to you that there is no need to improve these tests.

**Comment by bcail** [comment]
Oh, ok. Thanks.

**Pull request closed without merging**
