### PR TITLE
Fixed #21332, #26538 -- Fixed inconsistent and duplicate form fields on inline formsets

### PR DESCRIPTION
**Pull request by dsanders11**
https://code.djangoproject.com/ticket/21332
https://code.djangoproject.com/ticket/26538

### CODE REVIEW

**Comment by dsanders11** [comment]
Did a force push to redo the commit with the proper import order (didn't realize capitalization trumped alphabetical).

**Comment by dsanders11** [comment]
@timgraham, would you like me to force push the commit again with a commit message which matches the changed title?

**Comment by timgraham** [comment]
Not necessary. I made a couple edits to the docstrings to simplify them by dropping the "Ensures that" prefix in favor of stating the expected behavior and merged in a5c8a6ce19eabd96bf3b8c7bb4fb487f53928f3b, thanks!

**Comment by dsanders11** [comment]
Sounds good, thanks.

**Pull request closed without merging**
