### PR TITLE
Fixed #28780 -- Added customization for INTERNAL_RESET_URL_TOKEN

### PR DESCRIPTION
**Pull request by timgivois**
https://code.djangoproject.com/ticket/28780

### CODE REVIEW

**Comment by timgraham** [comment]
Documentation for those attributes should also be added.

**Comment by timgivois** [comment]
Sure, caaaan do !

**Comment by Debetux** [comment]
@timgivois are you writing documentation & tests ? If this isn't an issue for you, I would like to contribute to this ticket. :) Thanks!

**Comment by timgivois** [comment]
Sure, go on!

**Comment by timgivois** [comment]
Sure, @Debetux go for it!

**Comment by Debetux** [comment]
I'm working on it! Thanks. :)

Lancelot

**Comment by bukowa** [comment]
@timgraham isnt that a better idea for backwards compatibility ? 
https://github.com/django/django/pull/9859/commits/704c8a5fc62ac96e7db96704d603ee5ed61c5f51

**Comment by timgraham** [comment]
Those constants aren't documented so I don't think it's important to keep them.

**Comment by auvipy** [comment]
what works remain to complete this PR?

**Comment by timgivois** [comment]
@auvipy Documentation and tests .

**Comment by carltongibson** [comment]
Hi @timgivois are you up for finishing this PR? (If not I can de-assign the ticket and I'm sure someone would pick it up to get it across the line...)

**Comment by timgivois** [comment]
@carltongibson, I think that we can create a ticket for documentation + tests for this one.

**Comment by timgraham** [comment]
Okay, I'll close this and deassign the ticket. (We use the existing ticket rather than creating a new one.)

**Pull request closed without merging**
