### PR TITLE
Added #26836 - Allow applications to register links in the admin interface

### PR DESCRIPTION
**Pull request by smark-1**
https://code.djangoproject.com/ticket/26836

### CODE REVIEW

**Comment by shangxiao** [comment]
Hi @smark-1 the ticket originally requested some discussion on the ML… has this happened yet?

**Comment by smark-1** [comment]
@shangxiao the ticket only said that it would be a good idea to do this before writing lots of code and it being rejected. I got this to work without needing so much code. I also don't know how to do the discussion on the ML.

**Comment by nessita** [comment]
> @shangxiao the ticket only said that it would be a good idea to do this before writing lots of code and it being rejected. I got this to work without needing so much code. I also don't know how to do the discussion on the ML.

The comment from Tim in the ticket has a link with details on how to start the discussion in the Django Developer forum:

https://code.djangoproject.com/wiki/DevelopersMailingList

**Comment by smark-1** [comment]
@nessita  I started a discussion on Django Developer forum about a week ago. I did not receive any responses. What is the next step?

**Comment by nessita** [comment]
> @nessita I started a discussion on Django Developer forum about a week ago. I did not receive any responses. What is the next step?

Do you have a link to the discussion?

Please note that Django is a community driven project, and people contribute their time whenever they can, so I would advice to wait a bit longer. August was a month with many people on vacations in the north hemisphere, so I'm sure you'll get responses soon.

**Comment by smark-1** [comment]
https://groups.google.com/g/django-developers/c/s2Sy8gXu5LM/m/dqrGOe4DFwAJ

**Comment by felixxm** [comment]
Closing per ticket.

**Pull request closed without merging**
