### PR TITLE
Added Django Forum to mailing lists page.

### PR DESCRIPTION
**Pull request by carltongibson**
This is the target of various links, and so making reference to the Forum helps to steer traffic that way.

### CODE REVIEW

**Comment by smithdc1** [comment]
What do you think about updating the readme as well. Currently it guides folk to IRC and then to Google groups. 

On a similar there, but a separate topic to the forum, there's also the discord server in play. Is that "official"? 🤔

**Comment by carltongibson** [comment]
We could do all of that too! 😅

My real target here is the `|django-developers|` replacement in the docs conf file. But that appears lots of times still, and I thought I'd go for the incremental (but do-able) step first.

**Review by felixxm — APPROVED** [review]
@carltongibson Thanks :+1: I updated `/docs/index.txt`.

**Comment by carltongibson** [comment]
@felixxm Good catch! (As ever! 🎁)

**Pull request merged**
