### PR TITLE
Fixed #33547 -- Fixed error when rendering invalid inlines with readonly fields in admin.

### PR DESCRIPTION
**Pull request by felixxm**
Regression in de95c826673be9ea519acc86fd898631d1a11356.

Thanks David Glenck for the report.

ticket-33547

### CODE REVIEW

**Comment by felixxm** [comment]
@pascalfree Does it work for you?

**Review by hramezani — APPROVED** [review]
LGTM :+1:

**Review by carltongibson — APPROVED** [review]
Good, thanks!

**Comment by felixxm** [comment]
Thanks for checking :+1:

**Pull request merged**
