### PR TITLE
Fixed #27714 -- Fixed small visual artifact when clicking inline edit button in admin.

### PR DESCRIPTION
**Pull request by desecho**
https://code.djangoproject.com/ticket/27714

### CODE REVIEW

**Comment by timgraham** [comment]
It seems like the same issue would apply to the can add/delete buttons that follow? Using the `{% spaceless %}` tag might be a better approach.

**Comment by desecho** [comment]
I made the changes.

**Comment by timgraham** [comment]
Please add {% spaceless %} without changing indentation of the other lines. That's just creating noise in the commit history.

**Comment by desecho** [comment]
Done. By the way I tried to use it as shown in the example of the spaceless function itself.

**Pull request merged**
