### PR TITLE
Refs #25655 -- Made HAS_GEOS depend on a minimum version.

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
buildbot, test on precise.

**Comment by claudep** [comment]
buildbot, test on precise.

**Comment by timgraham** [comment]
LGTM

**Comment by claudep** [comment]
This is not sufficient, as tests depend on the "gis_enabled" db feature which is on even when GEOS version is too low.

**Comment by timgraham** [comment]
Do you think we should abandon this effort then? It looks to me like restoring https://github.com/django/django/pull/5527/files#diff-181a3ea304dfaf57f1e1d680b32d2b76L51 might fix the test errors that I looked at. Maybe this patch is enough if we discontinue the GIS builds in the matrix and keep SQLite/MySQL/PostgreSQL (those seemed to pass with your patch, besides some errors due to git checkout issues).

**Comment by timgraham** [comment]
buildbot, test on precise.

**Comment by timgraham** [comment]
This worked as outlined above. Let me know or put in a ticket if you want to try to restore the GIS builds on precise. Merged in b52b9cf6f2e88468b13ca64b806abc9a3dd437bd, thanks!

**Comment by claudep** [comment]
Fine, thanks.

**Pull request closed without merging**
