### PR TITLE
Removed unneeded handling of metadata tables in SpatialiteSchemaEditor.

### PR DESCRIPTION
**Pull request by sir-sigurd**
Changes in metadata tables are already handled by DiscardGeometryColumn()
and RecoverGeometryColumn().

### CODE REVIEW

**Comment by sir-sigurd** [comment]
@claudep, could you look on this?

**Comment by claudep** [comment]
It's totally possible that improvements in latest Spatialite release made those commands unneeded. I generally trust the test suite, so if the tested Spatialite version is the oldest still supported, I'm OK with those changes.

**Comment by timgraham** [comment]
Did you check [the ticket](https://code.djangoproject.com/ticket/23153) where this code was added?

**Comment by sir-sigurd** [comment]
Checked it more thoroughly and found out that `DiscardGeometryColumn()` removes column only from `geometry_columns`, but not from other `geometry_columns_*`.

**Pull request closed without merging**
