### PR TITLE
Used enterClassContext() where appropriate.

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Review by nessita — APPROVED** [review]
Changes looks great, thank you!

Question: are you also planning on moving to `enterContext` where appropriate?

**Comment by felixxm** [comment]
Thanks for reviews :+1: 

> Question: are you also planning on moving to `enterContext` where appropriate?

Probably, during my next "I have 20 minutes to the end of day" slot.

**Comment by carltongibson** [comment]
@felixxm I think I need a ☕ but... docs for `enterClassContext` say _New in Python 3.11_…

https://docs.python.org/3.12/library/unittest.html#unittest.TestCase.enterClassContext

So I'm not sure why isn't not complaining in 3.10. 🤔

**Comment by felixxm** [comment]
> So I'm not sure why it's not complaining in 3.10. 🤔

Because we're faster than Python, ed4f83782d9f3404ad600f6131ef78244ff1e162 :wink:

**Comment by carltongibson** [comment]
Super. Thanks! 🙏

**Comment by ngnpope** [comment]
You're welcome! 😜

**Pull request merged**
