### PR TITLE
[WIP] #24993 Test custom model fields 1.7.x

### PR DESCRIPTION
**Pull request by jedie**
Add unittests for "Custom Model field" described here:

​https://docs.djangoproject.com/en/1.7/howto/custom-model-fields/#the-subfieldbase-metaclass

Discussion: https://groups.google.com/forum/#!topic/django-developers/nYhZYyLcV1g
Ticket: https://code.djangoproject.com/ticket/24993

### CODE REVIEW

**Comment by timgraham** [comment]
Did you see `field_subclassing/fields.py`? As `SubfieldBase` is deprecated in Django 1.8, I don't think there's much value in adding new tests at this point.

**Comment by jedie** [comment]
I would also made same tests against v1.8.x and master:

https://github.com/jedie/django/compare/stable/1.8.x...test_custom_model_fields_1.8.x
https://github.com/jedie/django/compare/master...test_custom_model_fields_master

Only the SubfieldBase is deprecated, but the general customer model field API is there.

**Comment by timgraham** [comment]
`SubfieldBase` is replaced by `from_db_value()` which is tested in `tests/from_db_value`. Is your complaint that there isn't a single example that implements every method in the custom model field docs? I think all these methods are tested, but maybe not all in one place.

**Comment by jedie** [comment]
> SubfieldBase is replaced by from_db_value() which is tested in tests/from_db_value. 

Ah, ok. Then there is no more tests needed.

**Comment by jedie** [comment]
I looks around but didn't find a unittest for from_db_value() and .values() (see: https://code.djangoproject.com/ticket/9619 )... So i made this: https://github.com/django/django/pull/4875

**Pull request closed without merging**
