### PR TITLE
Fixed #35329 -- Fixed migrations crash when adding partial unique constraints with nulls_distinct.

### PR DESCRIPTION
**Pull request by felixxm**
Bug in 595a2abb58e04caa4d55fb2589bb80fb2a8fdfa1.

Thanks Lucas Lemke Saunitti for the report.

ticket-35329

### CODE REVIEW

**Comment by nessita** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
> buildbot, test on oracle.

`nulls_distinct` is supported only on PostgreSQL 15+, there is no need to run tests on Oracle.

**Comment by nessita** [comment]
> > buildbot, test on oracle.
> 
> `nulls_distinct` is supported only on PostgreSQL 15+, there is no need to run tests on Oracle.

I know but since the changes are made to the `base/schema.py`, I wanted to triple check all tests pass OK.

**Comment by felixxm** [comment]
> > > buildbot, test on oracle.
> > 
> > 
> > `nulls_distinct` is supported only on PostgreSQL 15+, there is no need to run tests on Oracle.
> 
> I know but since the changes are made to the `base/schema.py`, I wanted to triple check all tests pass OK.

None of tests with `nulls_distince` will run on Oracle :shrug:

**Comment by nessita** [comment]
> > > > buildbot, test on oracle.
> > > 
> > > 
> > > `nulls_distinct` is supported only on PostgreSQL 15+, there is no need to run tests on Oracle.
> > 
> > 
> > I know but since the changes are made to the `base/schema.py`, I wanted to triple check all tests pass OK.
> 
> None of tests with `nulls_distince` will run on Oracle 🤷

I understand that, but the changed code will be used in systems using Oracle.

**Review by nessita — APPROVED** [review]
LGTM, thanks!

**Review by charettes — APPROVED** [review]

**Comment by felixxm** [comment]
Thanks for reviews :+1:

**Comment by lsaunitti** [comment]
Thank you guys!

**Pull request merged**
