### PR TITLE
Simplified test_cursor_var() by using str instead of Database.STRING.

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
@timgraham It seems that `_output_type_handler()` should work in the same way with `str` data type (see [cx_Oracle example](https://github.com/oracle/python-cx_Oracle/blob/0924201461f3b406dd09ec943df33593138eecda/test/NumberVar.py#L24-L28)). IMO we should check if this has any impact on performance :thinking: .

**Comment by felixxm** [comment]
I checked `cx_Oracle` source code and it seems that it treats `str` in the same way as `cx_Oracle.STRING` for output variables e.g.
- https://github.com/oracle/python-cx_Oracle/blob/master/src/cxoTransform.c#L438-L441

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by timgraham** [comment]
But you want to keep other types like `Database.NUMBER` and `Database.Binary`? I don't know what the right thing to do is... just as long as you can explain the rationale.

**Comment by felixxm** [comment]
@timgraham To be honest, I'm not sure :thinking: . I think that wrapping variables on Oracle (i.e. `VariableWrapper`, `OracleParam`, `FormatStylePlaceholderCursor`, converters) should be investigated :male_detective: and hopefully simplified, e.g. by using Python data types, removing unnecessary conversions etc.

IMO we can leave `cx_Oracle.STRING` in `FormatStylePlaceholderCursor` for consistency, at least for now. I will try to prepare more complex set of changes and send separate PRs. I added ticket for that [#30170](https://code.djangoproject.com/ticket/30170).

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Pull request merged**
