### PR TITLE
Fixed typos in docs/faq/contributing.txt.

### PR DESCRIPTION
**Pull request by tangorishi**
fixed a bit of words, improved documentation

### CODE REVIEW

**Comment by shangxiao** [comment]
Nice spot 😁, the second one seems ok too 👍

**Comment by felixxm** [comment]
@tangorishi Thanks :+1: Welcome aboard :boat:

**Comment by tangorishi** [comment]
> Nice spot 😁, the second one seems ok too 👍

more than happy to contribute in any way possible!!

**Comment by tangorishi** [comment]
> @tangorishi Thanks 👍 Welcome aboard ⛵

Thanks @felixxm

**Comment by tangorishi** [comment]
@shangxiao I hope this message finds you well. I wanted to follow up on the pull request I submitted, I appreciate your feedback and I'm eager to see my changes merged into the project.

**Pull request merged**
