### PR TITLE
Fixed #24979 -- Removed usage of inspect.getargspec().

### PR DESCRIPTION
**Pull request by timgraham**
https://groups.google.com/d/topic/django-developers/NZskysjasx8/discussion

### CODE REVIEW

**Comment by carljm** [comment]
This approach looks OK to me; it abstracts out the simple common case, and leaves some custom version-dependent code in the one special case (allow migrate).

**Comment by aaugustin** [comment]
For clarity, instead of:

    def some_func():
        if six.PY2:
            # stuff for Python 2
            return result

        # stuff for Python 3
        return result

I'd rather do:

    if six.PY3:
        def some_func():
            # stuff for Python 3
            return result
    
    else:  # Python 2
        def some_func():
            # stuff for Python 2
            return result

**Comment by timgraham** [comment]
I chose the approach I did so that we can simply delete the Python 2 branches when the time comes and not have to pollute git blame with whitespace changes, but I'm happy to use your approach if you don't buy that reasoning.

**Comment by ev-br** [comment]
I was looking at working around inspect.getargspec() in scipy, and the search engine led me to this PR. --- Thank you!

I dared borrowing this nearly verbatim in https://github.com/scipy/scipy/pull/5248.  Just wanted to make sure it's OK with you. If there's a tiniest speck of discontent on your side, please accept my apologies and I'll remove that scipy PR.

**Comment by timgraham** [comment]
No problem. Django's code is BSD licensed, so just follow that and you should be fine.

**Pull request merged**
