### PR TITLE
Fixed #26293 -- Prevented CommonMiddleware from logging warnings during APPEND_SLASH.

### PR DESCRIPTION
**Pull request by the-kid89**
Removed a tab from lines 61 - 68 so code will run even if PREPEND_WWW is
set to False.

### CODE REVIEW

**Comment by timgraham** [comment]
Tests aren't passing (check `$ ./tests/runtests.py middleware`) and a new regression test to demonstrate that the issue described in the ticket is fixed is also required.

**Comment by the-kid89** [comment]
This is a bad patch by me.

**Comment by timgraham** [comment]
Please send a new PR if you get something working, thanks!

**Comment by the-kid89** [comment]
Will do.

**Pull request closed without merging**
