### PR TITLE
Fixed #29686 -- Made UserAdmin.user_change_password() pass object to has_change_permission().

### PR DESCRIPTION
**Pull request by atodorov**
https://code.djangoproject.com/ticket/29686

### CODE REVIEW

**Comment by atodorov** [comment]
The failing Jenkins job says `Killed`, not sure why, either OOM or some timeout.

**Comment by timgraham** [comment]
Thanks for the contribution. A [Trac ticket](https://code.djangoproject.com/) and a test are required.

**Comment by jeffyancey** [comment]
@timgraham do you think there is a valid case for this? Are you still interested in working on this @atodorov? I can create the ticket and modify the tests to get this PR ready.

**Comment by atodorov** [comment]
@jeffyancey added a new test, should be good to go.

**Comment by jeffyancey** [comment]
The change and test both look good to me, but you still need to make a Trac ticket as directed by @timgraham

**Comment by atodorov** [comment]
https://code.djangoproject.com/ticket/29686

**Pull request merged**
