### PR TITLE
Fixed #32645 -- Fixed QuerySet.update() crash when ordered by joined fields on MySQL/MariaDB.

### PR DESCRIPTION
**Pull request by felixxm**
Thanks Matt Westcott for the report.

Regression in 779e615e362108862f1681f965ee9e4f1d0ae6d2.

ticket-32645

### CODE REVIEW

**Comment by felixxm** [comment]
@gasman Can you confirm that it works for you?

**Comment by gasman** [comment]
@felixxm Yup, just tested - all looks good and works well here.

**Review by charettes — APPROVED** [review]

**Review by carltongibson — APPROVED** [review]
Yep, thanks @felixxm 👍

**Comment by felixxm** [comment]
Thanks y'all :confetti_ball:

**Pull request merged**
