### PR TITLE
Refs #26772 -- Added tests for FileField reopening closed files.

### PR DESCRIPTION
**Pull request by timgraham**
https://code.djangoproject.com/ticket/26772

### CODE REVIEW

**Comment by charettes** [comment]
Hmm that's odd, do you get the same failures if you `obj.refresh_from_db()` before accessing `obj.normal`?

**Comment by timgraham** [comment]
The new errors are due to 1b407050dd53e56686fdd3e168f8cac4f9be8306. Investigating to continue tomorrow (for me, at least).

**Comment by timgraham** [comment]
Simon, I went with the simpler test you described on #6792 since the other one doesn't pass on 1.9 (and still doesn't). Is it okay? I didn't follow all your comments there.

**Comment by charettes** [comment]
Yes, the simplified patch makes more sense. The other one was relying on mode passing to `_get_file()` which was reverted anyway.

**Pull request merged**
