### PR TITLE
Fixed typo in tests/forms_tests/field_tests/test_choicefield.py.

### PR DESCRIPTION
**Pull request by jdufresne**

### CODE REVIEW

**Comment by timgraham** [comment]
I'd like @claudep to confirm that this test isn't a candidate for removal in the spirit of https://github.com/django/django/pull/7986 (the clean up is ongoing).

**Comment by claudep** [comment]
That's clearly the sort of test I'd like to remove. On Python 3, we are assuming that strings are strings, not bytestrings. So unless we are dealing with interfaces where bytes input is legitimate (there are such cases, of course), we should not accept or test bytestrings handling.

**Comment by jdufresne** [comment]
Makes sense. Shall I close this PR?

**Comment by claudep** [comment]
Close it or make it remove the test?

**Comment by jdufresne** [comment]
OK, I'll close this. I'm not sure what assumptions are safe to know what parts of the form API always expect a string or can accept more than a string.

**Pull request closed without merging**
