### PR TITLE
Fixed #36017 Urlizer email fixed

### PR DESCRIPTION
**Pull request by gmaOCR**
#36017
ticket-36017
Branch 5.1.x

Add
```
         try:
            validate_email(value)
        except ValidationError:
            return False
```
to django.utils.html Urlizer.is_email_simple() to improve accuracy in validation

#### Checklist
- [v ] This PR targets the `5.1.x branch. 
- [v ] The commit message is written in past tense, mentions the ticket number, and ends with a period.
- [v ] I have checked the "Has patch" ticket flag in the Trac system.
- [N/A] I have added or updated relevant tests.
Existing validate the function
- [N/A ] I have added or updated relevant docs, including release notes if applicable.
- [N/A ] I have attached screenshots in both light and dark modes for any UI changes.

My firt PR on this repo.

### CODE REVIEW

**Comment by medmunds** [comment]
@gmaOCR thanks for this. The fix looks great.

It would help to add test cases that fail without your fix and then pass with it. A good place for that would be in test_urlize_unchanged_inputs() (tests/utils_tests/test_html.py). You could add the examples from the ticket (or your own) to the [group of not-quite-email-addresses](https://github.com/django/django/blob/f05edb2b43c347d4929efd52c8e2b4e08839f542/tests/utils_tests/test_html.py#L405-L409) in the list of cases.

**Comment by timgraham** [comment]
Additionally, all PRs should target the main branch. This doesn't qualify for a backport to 5.1.x, and even if it did. The fix first goes to main and the committer would backport from there.

**Comment by medmunds** [comment]
Also, the fixes for ticket-36014 and ticket-36017 can be merged in any order (despite my comment in the latter ticket).

**Comment by gmaOCR** [comment]
Ok i'm on the test. For the branch I had a doubt because for me 5.1 is actually the last stable version

**Comment by timgraham** [comment]
You can change the base branch on GitHub as you tried and then cherry-pick your commit onto a new branch locally and force push to this PR. If you can't figure it out, you may open a new PR. (This fix won't be backported to 5.1. You can read https://docs.djangoproject.com/en/dev/internals/release-process/#supported-versions for details.)

**Comment by gmaOCR** [comment]
(
                # RFC 6068 requires a mailto URI to percent-encode a number of
                # characters that can appear in <addr-spec>.
                "yes;this=is&a%valid!email@example.com",
                '<a href="mailto:yes%3Bthis%3Dis%26a%25valid%21email@example.com"'
                ">yes;this=is&a%valid!email@example.com</a>",
            ),
            (
                # Urlizer shouldn't urlize the "?org" part of this. But since
                # it does, RFC 6068 requires percent encoding the "?".
                "test@example.com?org",
                '<a href="mailto:test@example.com%3Forg">test@example.com?org</a>',
            ),
            
            Test are broken if validate is include in is_email_simple(). Imo, the logic of validation for RFC 6068 should be splitted with the validation for mail syntax. I try to find a solution

**Comment by medmunds** [comment]
@gmaOCR I added both of those tests in #18941. (And opened ticket-36017 as a result, see [comment](https://github.com/django/django/pull/18941#discussion_r1887355767).)

You should remove the second test: the comment is correct that "Urlizer shouldn't urlize the '?org' part." That's the bug you're fixing here. 

Instead, add its test case `"test@example.com?org"` to test_urlize_unchanged_inputs() later in the file. (With your fix, that invalid email address is no longer urlized.)

And I made a mistake in the first test: `"yes;this=is&a%valid!email@example.com"` is actually *not* a valid email: the semicolon isn't permitted in an email address unless it's within double quotes. (And Urlizer doesn't try to urlize email addresses with quotes, for a bunch of good reasons.) 

I'd suggest changing the semicolon to a plus sign, which *is* allowed (and encodes to `%2B`):

```patch
             (
                 # RFC 6068 requires a mailto URI to percent-encode a number of
                 # characters that can appear in <addr-spec>.
-                "yes;this=is&a%valid!email@example.com",
+                "yes+this=is&a%valid!email@example.com",
-                '<a href="mailto:yes%3Bthis%3Dis%26a%25valid%21email@example.com"'
+                '<a href="mailto:yes%2Bthis%3Dis%26a%25valid%21email@example.com"'
-                ">yes;this=is&a%valid!email@example.com</a>",
+                ">yes+this=is&a%valid!email@example.com</a>",
             ),
```

**Pull request closed without merging**
