### PR TITLE
Fixed #24788 -- Allowed Forms to specify a prefix at the class level.

### PR DESCRIPTION
**Pull request by RatanShreshtha**

### CODE REVIEW

**Comment by timgraham** [comment]
Can you revert the file mode changes?

**Comment by RatanShreshtha** [comment]
ok what should I keep file mode ?

**Comment by timgraham** [comment]
Look at the "Files changed 5,109 " tab of this PR> I see lots of 100644 → 100755 changes that shouldn't be there.

**Comment by RatanShreshtha** [comment]
There are too many files, is there a easy way to do that.

**Comment by timgraham** [comment]
`chmod`?

**Comment by RatanShreshtha** [comment]
I am unable to do that you can reject my pull request.

**Comment by timgraham** [comment]
Oh, this is from the contributing tutorial. I guess you didn't see the request not to submit a pull request added in 57292725093eb470851b35174c10573bbf717117.

**Comment by RatanShreshtha** [comment]
From now on I will be much more careful, and I will try to contribute for django.

**Pull request closed without merging**
