### PR TITLE
Fixed #28857 -- Fixed Cast function on PostgreSQL for complex expressions.

### PR DESCRIPTION
**Pull request by SShayashi**
https://code.djangoproject.com/ticket/28857

### CODE REVIEW

**Comment by timgraham** [comment]
The pull request should target the master branch and a regression test is also required.

**Comment by SShayashi** [comment]
> The pull request should target the master branch and a regression test is also required.

I added test, but I am wondering which branch should I push?

Master branch does not have `django/db/models/functions/base.py`. In addition, the master branch succeeded test even though I added the test before running. Obviously, I checked out the test properly in version 2.0.x and 1.11.x. What branch should I create pull request to?

**Comment by timgraham** [comment]
On master, `Cast` is moved to `functions/comparison.py`. If the test passes on master without any changes, you could [bisect](https://docs.djangoproject.com/en/dev/internals/contributing/triaging-tickets/#bisecting-a-regression) to find the commit that fixed it and we can figure out how to proceed from there.

**Comment by SShayashi** [comment]
According to a survey, the test was skipped on master because of a following reason:
`'Database doesn\\'t support feature(s): has_jsonb_datatype'`

If I detached `@skipUnlessDBFeature('has_jsonb_datatype')` annotation on master branch, the test worked exactly same as the other branches.  However, I thought the annotation was needed referring to stable/2.0.x and 1.11.x.

In conclusion, I'm sorry not to be sure points:

- why master is not using the annotation 

- whether to use the annotation, or not.

**Comment by timgraham** [comment]
`has_jsonb_datatype` was removed in 1d8cfa36089f2d1295abad03a99fc3c259bde6b5 because all supported versions of PostgreSQL now support jsonb.

You should try for a test in `tests/db_functions/test_cast.py`. `postgres_tests` is for testing things in `contrib.postgres`. You might try for a test that simply verifies the parentheses in the query, even if they are unnecessary.  Try grepping the tests for `connection.queries` and see if that gives some inspiration.

**Comment by SShayashi** [comment]
Thanks for a quick response. I added test and fix target branch.

**Pull request merged**
