### PR TITLE
Fixed #24381 -- Fixed pickling of QuerySets that filter on reverse FKs.

### PR DESCRIPTION
**Pull request by timgraham**
I am not suggesting this is the correct solution, but hopefully it will point someone in the correct direction.

### CODE REVIEW

**Comment by timgraham** [comment]
Maybe a better solutions is to add a `__reduce__()` method and delete the cached property from the pickled dict?

**Comment by charettes** [comment]
I think the `__reduce__()` approach would make sense.

**Comment by akaariai** [comment]
Lets just get rid of the opts and to_opts cached properties. It seems opts is used in just a couple of places, and to_opts isn't used at all. In addition, the properties are confusingly defined:
  self.model == self.to
  self.related_model != self.model
  self.opts = self.related_model._meta *!= self.model._meta*
  self.to_opts = self.to._meta

It is nearly impossible to see what happens in code using field.rel.opts, as there is no pointer at all that field.rel.opts != field.rel.model._meta.

I'll open an pull request showing the needed changes. If we want to have rel.opts for 1.8, then I think we could introduce an accelerated deprecation for it - rel.opts will be removed from 1.9, and is a regular property in 1.8.

**Comment by akaariai** [comment]
Opened #4194

**Comment by timgraham** [comment]
That looks good to me. I don't think a deprecation is needed.

**Pull request closed without merging**
