### PR TITLE
Fixed #9739 - Made Admin prefill DateTimeField from URL

### PR DESCRIPTION
**Pull request by RidleyLarsen**
Added the ability to prepopulate SplitDateTimeWidgets from a URL.
Added a test for ModelAdmin.get_changeform_initial_data. Added
documentation for prepopulating ManyToManyFields and DateTimeFields.

### CODE REVIEW

**Comment by RidleyLarsen** [comment]
I'm not so sure I like the "special case" approach this patch takes. Could an alternative patch modify the `decompress` method of `SplitDateTimeWidget`?

I implemented a subclassed Split Date/Time Widget for my own project with this method that achieves a similar effect. Currently, if you attempt to access an admin form with something like `?pub_date=2015-04-03,12:00:00`, django throws an error because it expects the decompress value to be a `datetime` object.

```python
def decompress(self, value):
        if value:
            if type(value).__name__ == "unicode":
                return value.split(',')
            else:
                value = to_current_timezone(value)
            return [value.date(), value.time().replace(microsecond=0)]
        return [None, None]
```

**Comment by timgraham** [comment]
Yes, it seems like the current patch isn't ideal since it assumes `DateTimeField` uses a `SplitDateTimeWidget`.

If you want to give your alternate approach a try, a better version of the third line would be `if isinstance(value, six.text_type)`

**Comment by RidleyLarsen** [comment]
OK, I've attached another commit. Thanks for the advice!

**Comment by timgraham** [comment]
I'd rather a test that didn't use the admin so if we dropped the admin, we don't lose the test for this.

**Comment by timgraham** [comment]
Closing due to lack of follow up. Please send a new PR if you can update it. Thanks!

**Pull request closed without merging**
