### PR TITLE
Fixed required SpatiaLite version in docs.

### PR DESCRIPTION
**Pull request by sir-sigurd**

### CODE REVIEW

**Comment by timgraham** [comment]
Can you say when it changed so we know how far to backport the correction?

**Comment by sir-sigurd** [comment]
See bc0aba7786978ec312809eae5ecb3d751608b5b7. It looks like it should be backported to 1.8.
I just noticed that 2.3 is also mentioned here https://github.com/django/django/blob/master/docs/ref/contrib/gis/install/spatialite.txt#L126.

**Comment by timgraham** [comment]
Merged in 1a10ae45b102bd6dab15ef0bd95cda91635916ad, thanks.

Created https://code.djangoproject.com/ticket/25633#ticket for the outdated KyngChaos installation instructions. I'll mail the geodjango mailing to try to get feedback on that unless it's something you're knowledgeable about?

**Comment by sir-sigurd** [comment]
Nope, I have no idea what (who?) this KyngChaos is.

**Pull request closed without merging**
