### PR TITLE
Fixed #27888 -- Added button to clear all admin filters

### PR DESCRIPTION
**Pull request by alaminopu**
Fixed #27888 -- Added button to clear all admin filters

### CODE REVIEW

**Comment by timgraham** [comment]
A mentioned on the ticket, the functionality is already provided when search is enabled. To the right right of the search box, something like "N results (X total)" is displayed. If you click "X total", the query string is removed and all results are displayed. Your proposal looks like it's adding a second button nearby to do the same thing?

**Comment by alaminopu** [comment]
Yes. I think it's a very simple approach and it solves the UX problem.

**Comment by timgraham** [comment]
In my mind, the purpose of the ticket was to allow clearing the list filters if `ModelAdmin.search_fields` isn't enabled.

**Comment by alaminopu** [comment]
@timgraham Updated the pull request. Placed the `clear` button on the right corner of the table.

**Comment by collinanderson** [comment]
The button hidden behind the filter box for me. My browser width is around 1100px wide.

**Comment by alaminopu** [comment]
@collinanderson Thanks for the report.  I have fixed the styling issue and updated the pull request.

**Comment by alaminopu** [comment]
@srinivasreddy Is it possible to merge?  r?

**Comment by timgraham** [comment]
The button appears even if no filters or search terms are selected. I'm not sure if that's ideal. I think we'd also want some tests for the button appearing appropriately.

**Comment by timgraham** [comment]
Closing due to inactivity.

**Pull request closed without merging**
