### PR TITLE
Unified NullBooleanField's and BooleanField's check constraints on Oracle.

### PR DESCRIPTION
**Pull request by felixxm**
See https://github.com/django/django/pull/9016#issuecomment-326822713.

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by timgraham** [comment]
Okay, I suggest "Removed useless condition from Oracle's NullBooleanField's check constraint." (maybe an extended description from your comment would also be useful). Separately, I don't think we have any failing tests for the existence of constraints if you want try to add some but it's not required to merge this.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by timgraham** [comment]
I'm not sure if it's better than the test your wrote but I envisioned a test in `backends/tests/oracle` that perhaps uses a raw SQL query to violate the constraint. The additional test coverage should be in a separate commit from the removal since no behavior is changing.

**Comment by felixxm** [comment]
@timgraham I sent the second proposition in #9025.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Pull request merged**
