### PR TITLE
Refs #31040, Refs #31224 -- Prevented cycles in exceptions chain.

### PR DESCRIPTION
**Pull request by felixxm**
Exception handling was raising an exception that was creating a cycle in the exception chain (by re-raising an exception that was already being handled).

Thanks Chris Jerdonek for detailed analysis.

See also https://bugs.python.org/issue40696.

### CODE REVIEW

**Comment by cjerdonek** [comment]
Great! Are you able to confirm that the test that was hanging with Python3.9.0a6 passes with this change?

**Comment by felixxm** [comment]
Yes it works with this patch.

**Comment by cjerdonek** [comment]
Looking at the patch: In `process_exception_by_middleware()`, what do `middleware_method`'s do with the exception? Is it common or possible that they would re-raise the same exception, and would that also wind up causing the same situation? In the change to `process_exception_by_middleware()`, it appears that only the case where it gets past all middlewares is being addressed.

**Comment by felixxm** [comment]
[process_exception()](https://docs.djangoproject.com/en/3.1/topics/http/middleware/#process-exception) should return either `None` or an `HttpResponse` object, so it's possible but it's not supported.

**Comment by felixxm** [comment]
@carltongibson Thanks for checking :+1:

**Pull request merged**
