### PR TITLE
Refs #28196 -- Removed mentions of bytestrings for EmailMessage

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by timgraham** [comment]
`EmailMultiAlternatives` has the same comment that I guess should be removed.  Just to double check, the message didn't get altered incorrectly in https://github.com/django/django/commit/d1bab24e0144d14513a1411503c95ececb425188#diff-e1d718400701d0b0adfafbdcf8163aa3 did it? Has the message been incorrect since its introduction in https://github.com/django/django/commit/953badbea5a04159adbfa970f5805c0232b6a401#diff-0aaf5087d6ec9f67d610ac1052a6430fR204?

**Comment by claudep** [comment]
Good catch! I don't think this was incorrect, but what made sense when strings were often a mix of bytestrings and unicode strings is no longer accurate with Python 3 IMO (master-only, of course).

**Comment by timgraham** [comment]
Okay, maybe you can include that explanation in the commit message or in the ticket. I'm not sure what "The SafeMIMEText class will handle any necessary encoding conversions" meant. Possibly some `force_text()` calls removed in 301de774c21d055e9e5a7073e5bffdb52bc71079?

**Comment by claudep** [comment]
Tentative basic explanation in the commit message.

**Pull request closed without merging**
