### PR TITLE
Fixed #34015 -- Allowed filtering by transforms on relation fields.

### PR DESCRIPTION
**Pull request by felixxm**
ticket-34015

### CODE REVIEW

**Review by charettes — COMMENTED** [review]
Should we also add tested coverage for nested relational fields transforms/lookups?

https://github.com/django/django/blob/cfe3008123ed7c9e3f3a4d51d4a22f9d96634e33/django/db/models/sql/query.py#L1453-L1458

**Review by David-Wobrock — APPROVED** [review]

**Comment by felixxm** [comment]
> Should we also add tested coverage for nested relational fields transforms/lookups?

Good catch :dart: I added an extra tests.

**Review by charettes — APPROVED** [review]
Awesome, thank you for adding the extra tests 🎉

**Comment by felixxm** [comment]
Thanks for checking :tada:

**Pull request merged**
