### PR TITLE
Refs #27558 -- Isolated a MySQL indexes test.

### PR DESCRIPTION
**Pull request by timgraham**
MySQL schema changes must be done in TransactionTestCase. (correct?)

### CODE REVIEW

**Comment by adamchainz** [comment]
Correct

**Comment by charettes** [comment]
yeah it's required because MySQL doesn't support transactional DDL. Creating the index silently commits the transaction wrapped around the test method by `TestCase`.

**Comment by charettes** [comment]
This makes me wonder if we could warn or error out if `schema_editor.execute()` is called when `connection.in_atomic_block` and `connection.features.can_rollback_ddl`.

**Comment by adamchainz** [comment]
That's a good idea, although technically it might execute a non-DDL statement

**Comment by charettes** [comment]
@adamchainz right but one could use `connection.cursor().execute()` to circumvent that.

**Pull request merged**
