### PR TITLE
Fixed #28498 -- Closed the cursor before closing the connection on Oracle.

### PR DESCRIPTION
**Pull request by felixxm**
https://code.djangoproject.com/ticket/28498

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by timgraham** [comment]
Maybe some comments in `creation.py` would be helpful for posterity?
Maybe the commit message/release note is better as something like "Fixed test database creation with cx_Oracle 6."

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
Yes, and it also works.

**Comment by felixxm** [comment]
I just wanted to keep this fix as small as possible.

**Pull request merged**
