### PR TITLE
Refs #25415 -- Stopped running checks on models with missing features.

### PR DESCRIPTION
**Pull request by charettes**

### CODE REVIEW

**Comment by timgraham** [comment]
I'm not sure if this is the best approach. I understand the usefulness for Django's tests but for normal usage, it seems that fields may want to raise errors if they're unsupported. Have you thought about it from that angle?

**Comment by charettes** [comment]
I assumed models with missing database features should simply be ignored as they are not meant to be used. What's the use a model definition without a table backing it?

If fields were throwing errors when they are unsupported where should that happen? It cannot be during their initialization phase as declaring `required_db_features` would be useless and if it's done at the `check` level then then would need to be silenced any way.

**Comment by timgraham** [comment]
I don't know, I was looking at something like https://github.com/django/django/blob/3c447b108ac70757001171f7a4791f493880bf5b/django/contrib/gis/db/models/fields.py#L426-L427 but I didn't too much. I guess this probably mostly only affects Django's test suite anyway.

Is it worth adding a test?

Maybe something a name like `has_connections_features` would be more descriptive but if you like the current name I'm okay with it.

**Comment by adamchainz** [comment]
Django-MySQL has fields that check for database features, though they aren't in `required_db_features` because it can't contribute features to the database backend, see e.g. https://github.com/adamchainz/django-mysql/blob/master/django_mysql/models/fields/dynamic.py#L38 . I added the checks to make sure people don't try to use them on the wrong database (MySQL vs MariaDB) or version.

**Comment by adamchainz** [comment]
Back in #6294 I took this and made it apply to only the two models that failed checks in Django's test suite.

**Comment by charettes** [comment]
Thanks @adamchainz, I suppose we can close this in this case.

**Pull request closed without merging**
