### PR TITLE
Fixed #25285 -- Prevented django-admin from raising "settings not configured" on an unknown command.

### PR DESCRIPTION
**Pull request by mlorant**
The project could not exist yet, so it can raise the wrong exception.

See https://code.djangoproject.com/ticket/25285

### CODE REVIEW

**Comment by timgraham** [comment]
Is it possible to add a regression test?

Please see our [patch review checklist](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/submitting-patches/#patch-review-checklist) for some helpful tips.

**Comment by mlorant** [comment]
After some thoughts, I need advice on this one... Currently, when a command is not found, [an access to `settings.INSTALLED_APPS` is done](https://github.com/mlorant/django/blob/d0e36ef040a15d5a2fe5ced30eecd89d7be0f57d/django/core/management/__init__.py#L183) to check if a project is correctly configured. It can be useful to highlight configuration errors, but the command startproject, no settings is needed for example. So if you make a typo, you raises an exception as if a project already exists...

I don't really know what the framework should do in this case. The easiest workaround I had in mindwas to return "unknown command" every time, even when it is because settings are not given in parameters... (We can't determine if the command really exists somewhere or if it is a real error from the user anyway). It does not affect Django commands (`check`, `shell`...) which requires settings, since the check is removed only in `fetch_commands`.

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
Closing in favor of https://github.com/django/django/pull/5158. Thanks for the start.

**Pull request closed without merging**
