### PR TITLE
Update change_form.html

### PR DESCRIPTION
**Pull request by a-roomana**
replace ' by " in url of forms.css

### CODE REVIEW

**Comment by timgraham** [comment]
This works fine as is. Did you encounter an error?

**Comment by a-roomana** [comment]
Yes it works, but I do not think it's standard.

`href="{% static "admin/css/forms.css" %}"`  bad
`href="{% static 'admin/css/forms.css' %}"` good

**Comment by timgraham** [comment]
Both single quotes and double quotes are used in Django's usage of `{% static ... %}`. If we make a change, we should be consistent throughout rather than changing one instance, but I don't think it's worth it.

**Comment by a-roomana** [comment]
I thought that this was the case everywhere. Apparently I thought wrong!
Good luck!

**Pull request closed without merging**
