### PR TITLE
Disabled caching in GitHub actions for Windows tests.

### PR DESCRIPTION
**Pull request by felixxm**
See https://github.com/actions/setup-python/issues/328.

### CODE REVIEW

**Review by carltongibson — APPROVED** [review]
Looks good (at least as a tmp measure whilst we find someone who knows what that error code means 🙂)

**Comment by carltongibson** [comment]
For ref: 

> Error: The process 'C:\hostedtoolcache\windows\Python\3.10.1\x64\Scripts\pip.exe' failed with exit code 3221225477

That's a good error code. 😄

**Comment by felixxm** [comment]
> Looks good (at least as a tmp measure whilst we find someone who knows what that error code means slightly_smiling_face)

Thanks for checking :+1: Yes, it's a temporary solution.

**Review by adamchainz — APPROVED** [review]
👍 yes I also did this over on Whitenoise: https://github.com/evansd/whitenoise/pull/350

**Comment by felixxm** [comment]
Thanks :+1:

**Pull request merged**
