### PR TITLE
Add distinct on Sum annotate

### PR DESCRIPTION
**Pull request by engelolivier**

### CODE REVIEW

**Comment by engelolivier** [comment]
https://code.djangoproject.com/ticket/19011
https://code.djangoproject.com/ticket/10060

**Comment by charettes** [comment]
Hello there! While the tickets you linked to can be sometimes worked around by using `DISTINCT` this doesn't fix them. Please [file a new feature request](https://code.djangoproject.com/newticket) to add distinct support to `Sum` to track this PR instead.

**Comment by AdamDonna** [comment]
@engelolivier Did you make a new ticket to track this issue? It would be a shame to not get your change out since there's not ticket for it yet

**Comment by timgraham** [comment]
Closing due to inactivity.

**Pull request closed without merging**
