### PR TITLE
[3.2.x] Updated translations from Transifex.

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
If possible, I'd like to re-fetch translations tomorrow if translators are still working today.

**Comment by carltongibson** [comment]
OK, super. General plan is for @felixxm to roll the security releases in the morning, and then I aim to push 3.2 around lunch time. (CET) Does that give you enough space? (Let me know — I can hold off until 3pm say.)

**Comment by claudep** [comment]
Sounds like a good plan :-)

**Comment by carltongibson** [comment]
Super, comme toujours tu es mon héros! 😊

**Comment by claudep** [comment]
Welcome in the French translation team!!

**Comment by carltongibson** [comment]
😀 maybe next year.

**Comment by felixxm** [comment]
I can re-fetch and merge translations before security releases. I don't see big issue in pending translations, we can re-fetch them again before 3.2.1 release.

**Comment by claudep** [comment]
I didn't see much activity today, let's go with this patch.

**Comment by felixxm** [comment]
@claudep Thanks :star:

**Pull request merged**
