### PR TITLE
Fixed #26558 -- Added username to admin view context

### PR DESCRIPTION
**Pull request by etos**
https://code.djangoproject.com/ticket/26558

### CODE REVIEW

**Comment by etos** [comment]
**Further observations not in original ticket:**
**test** 'test_post_save_message_no_forbidden_links_visible' will fail if 'django.contrib.messages.context_processors.messages' context_processors is not included
**test** 'test_login_page_notice_for_non_staff_users' will fail if 'django.contrib.auth.context_processors.auth' context_processors is not included

Am happy to look at these if the goal would be for Admin to remain functionally independent of template context_processors

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
Sure, [#24117](https://code.djangoproject.com/ticket/24117) is the ticket to make context processors unneeded in the admin.

**Comment by timgraham** [comment]
merged in 1206eea11e506c4e740ba2f0c1feaa01452d804b, thanks!

**Pull request closed without merging**
