### PR TITLE
Fixed #28197 -- Fixed introspection of index field ordering on PostgreSQL.

### PR DESCRIPTION
**Pull request by Mactory**
https://code.djangoproject.com/ticket/28197

### CODE REVIEW

**Comment by claudep** [comment]
Did you try with ordering the subquery, the query might be a little bit simpler?

**Comment by Mactory** [comment]
I did try that, but I think the row_number() is applied after the ordering, so this didn't solve the problem. I did not check that thoroughly though. It could also be a solution to wrap the subquery in another subquery and then sort it. This would probably eliminate one sort but make the query it more complex, so I decided against it.

**Comment by claudep** [comment]
If you tried and it failed, then let's forget it. By reading PostgreSQL docs, I initially thought that simply ordering the subquery without any `row_number` stuff (for example `ORDER BY indexname`) would be enough.

**Comment by Mactory** [comment]
That was my first thought as well, but there is no field that can be used for the ordering, that is why I used `row_number` as fallback. The ordering is given by the `unnest()` function which simply unnests the array as rows in the order they appear but does not provide a value for ordering. From postgres 9.4 on  [WITH ORDINALITY](http://www.postgresql.org/docs/9.4/interactive/functions-srf.html) was added that provides this functionality, but I didn't want to rely on postgres 9.4 yet. Maybe I should add a comment with this info for possible future usage?

**Comment by claudep** [comment]
Ah yes, that would be nice!

**Pull request merged**
