### PR TITLE
Fixes #23643 - Show exception chain in debug template for Py3k

### PR DESCRIPTION
**Pull request by tricoder42**
https://code.djangoproject.com/ticket/23643#no4

### CODE REVIEW

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
merged in 8414fcf16b9cfa8d989db913f0961fc4ce18c71b, thanks!

**Comment by prestontimmons** [comment]
This is a great feature.

Was it oversight that the traceback in the copy/paste box wasn't updated? It's kinda obscure, and I'm not sure it's used much, but it still shows the simple traceback.

**Comment by tricoder42** [comment]
That's definitely oversight... I'll fix it tomorrow.

**Pull request closed without merging**
