### PR TITLE
Fixed #30980 -- admin.E130(duplicate __name__ attributes of actions) …

### PR DESCRIPTION
**Pull request by keshav2212**
…should specify which were duplicated.

### CODE REVIEW

**Comment by keshav2212** [comment]
I am new to django contribtuion and I have tried to fix this issue, I have write some code to fix it . Can you review on it ?

**Comment by hramezani** [comment]
I am not sure about the solution. but at least your patch should pass the current tests.
Also, you should add some tests to prove that your proposed solution will fix the problem.

Then you should enable the [has patch](https://docs.djangoproject.com/en/dev/internals/contributing/triaging-tickets/#has-patch) flag of the ticket. reviewers then will review your patch.

**Comment by keshav2212** [comment]
ok, I work on it. Thank You! @hramezani

**Comment by keshav2212** [comment]
Hello @Parth1811 , I have solved that small changes. But here, it is not showing me any kind of merge conflicts.

**Comment by AdamDonna** [comment]
@keshav2212 I took some ideas from your PR and updated the tests, flake8, isort and ran it against master if you want to take a look to incorporate it into your PR. I'm keen to get this one solved https://github.com/django/django/pull/12281

**Comment by keshav2212** [comment]
@AdamDonna Hey, I have seen your changes,That looks good, I was not able to write its test case. Thanks for the help.

**Comment by keshav2212** [comment]
And @AdamDonna, Please give the necessary credit even I had to do that with my first PR when someone helped me.

**Comment by felixxm** [comment]
Updated in #12281.

**Pull request closed without merging**
