### PR TITLE
Fixed debug view crash during the autumn DST change.

### PR DESCRIPTION
**Pull request by aaugustin**
This PR supersedes #5529. /cc @apollo13

### CODE REVIEW

**Comment by aaugustin** [comment]
Apparently people had already noticed this last year: https://code.djangoproject.com/ticket/23714

**Comment by carljm** [comment]
@aaugustin This appears to be a partial re-implementation of #3576 (with test). Can you comment on whether other parts of #3576 should be included as well? Specifically I'm thinking of the documentation update and the updates to the `O`, `T`, and `I` format specifiers. Also, maybe @tricoder42 should be credited for his initial work on the problem?

I also thought the trick to only catch `AmbiguousTimeError` if pytz is installed was kind of nice, but maybe that's too clever...

**Comment by aaugustin** [comment]
@carljm I was precisely looking at this with @apollo13.

In fact I completed the patch for #3576 and committed it a few months ago. That PR dealt with when `USE_TZ = True`.

This new PR deals with essentially the same problem when `USE_TZ = True`.

**Comment by aaugustin** [comment]
Merged in 1014ba026e879e56e0f265a8d9f54e6f39843348.

**Pull request closed without merging**
