### PR TITLE
Fixed #22972 -- HashedFilesMixin.patterns should limit URL matches to their respective filetypes

### PR DESCRIPTION
**Pull request by aehlke**
Please see https://code.djangoproject.com/ticket/22972 for context.

### CODE REVIEW

**Comment by claudep** [comment]
Isn't a `test.js` file missing in the patch?

**Comment by aehlke** [comment]
> Isn't a test.js file missing in the patch?

Entirely possible. I can't find contributor's documentation about "test.js" though, can you please elaborate? This doesn't touch anything front-end so I'm not sure what this might mean.

**Comment by claudep** [comment]
The patch mentions some test.js file with some content like `sourceMappingURL=` or `test.js.map`. Was that file present in the Django test files when you wrote the patch, or was that a file you had locally and forgot to include in the patch?

**Comment by aehlke** [comment]
Ah I see, I had forgotten some details of this patch. I'll be sure to investigate this, haven't had the time to follow up yet.

**Comment by pySilver** [comment]
in a mean time one can use something like this: https://gist.github.com/seawolff/d1cc3633a4515dea336d

**Pull request closed without merging**
