### PR TITLE
Fixed #23986 -- Collectstatic --clear fails if the static dir doesn't ex...

### PR DESCRIPTION
**Pull request by sztrovacsek**
...ist yet

### CODE REVIEW

**Comment by timgraham** [comment]
Could you add a test?

**Comment by sztrovacsek** [comment]
working on the test as we speak

**Comment by sztrovacsek** [comment]
I will squash the commits into one

**Comment by timgraham** [comment]
buildbot, test this please.

**Comment by timgraham** [comment]
merged in 87d78241a2fc85e5715fb51c554fe06e91deee58, thanks!

**Comment by timgraham** [comment]
If you have time to investigate, I noticed the new tests fail on Windows:
```
======================================================================
ERROR: test_dir_not_exists (staticfiles_tests.tests.TestCollectionClear)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\Tim\code\django\tests\staticfiles_tests\tests.py", line 305, in
 test_dir_not_exists
    shutil.rmtree(settings.STATIC_ROOT)
  File "C:\Python27\Lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\Lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Python27\Lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 123] The filename, directory name, or volume label syntax i
s incorrect: 'c:\\users\\tim\\appdata\\local\\temp\\django_37weam\\tmpq4tbev\\te
st\\?.txt'
```

**Comment by sztrovacsek** [comment]
I will take a look and try to fix it this evening (in approx 4 hours). (I'm at work now, can't do it.)

**Comment by sztrovacsek** [comment]
I did not have time to set up a windows environment yesterday. And I am travelling for 3 days in a row, so I will not have time in the next few days either. Sorry.

**Comment by timgraham** [comment]
Not a problem, fixed in 389baccac5fce72c67cfed7a6ebcf9273edf9282.

**Pull request closed without merging**
