### PR TITLE
Update duration.py

### PR DESCRIPTION
**Pull request by PzaThief**
_get_duration_components function using divmod for shorter code and better readability
change format function to f-string for improvement of performance and readability

### CODE REVIEW

**Comment by jacobtylerwalls** [comment]
Hi @PzaThief. We currently aren't accepting pull requests for the sole purpose of implementing f-strings. This is mentioned at the [contributing guide](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/). Regarding the `divmod` change: reasonable folks can disagree whether a multiple assignment statement is more readable.

We're happy to look at any future contributions, so do head over to the Django forum or browse the open issues if you'd like to get involved with Django development. Thanks.

**Comment by PzaThief** [comment]
> Hi @PzaThief. We currently aren't accepting pull requests for the sole purpose of implementing f-strings. This is mentioned at the [contributing guide](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/). Regarding the `divmod` change: reasonable folks can disagree whether a multiple assignment statement is more readable.
> 
> We're happy to look at any future contributions, so do head over to the Django forum or browse the open issues if you'd like to get involved with Django development. Thanks.

Okay. I've misunderstoodd the contribution guide.
Thanks for detailed review.

**Comment by ngnpope** [comment]
> We currently aren't accepting pull requests for the sole purpose of implementing f-strings.

@Jacob Our discussions on this matter did leave open the possibility of limited changes based on performance concerns. `.format()` is quite significantly slower than f-strings and in some cases we're using them in certain hot paths where I've seen such calls being the most costly. But for such a change I'd expect to see some before and after numbers for comparison. _(For example, I have another patch I'm still sitting on for `django.db.backend.utils.format_number()` that yields a potential 2x improvement of which the change to an f-string is one part of the improvement.)_

**Comment by jacobtylerwalls** [comment]
Yes, true, thanks for clarifying. I think without the hypothetical benchmarks you mention this does sort of present as refactoring for the sake of refactoring, which I think the guide discourages, but you are right that a benchmarked performance improvement on a non-trivial path would be considered.

**Pull request closed without merging**
