### PR TITLE
Fixed forms_tests.tests.test_renderers with Jinja 3.1.0+.

### PR DESCRIPTION
**Pull request by felixxm**
See https://github.com/pallets/jinja/pull/1621.

### CODE REVIEW

**Review by carltongibson — APPROVED** [review]
OK. 👍 Thanks!

**Comment by felixxm** [comment]
@carltongibson Thanks for checking :+1:

**Comment by davidism** [comment]
Just saw this reported elsewhere, I'll fix this in Jinja so the final filename gets normalized, and then release 3.1.1.

**Comment by davidism** [comment]
And sorry, but the fix is going to cause this fix in your tests to fail again.

**Comment by felixxm** [comment]
@davidism No problem, we will revert, it's just a test fix. Thanks for your efforts :1st_place_medal:

**Comment by felixxm** [comment]
See #15545.

**Pull request merged**
