### PR TITLE
Fixed leaky logger in NonDjangoTemplatesDebugViewTests.

### PR DESCRIPTION
**Pull request by pope1ni**
```
...................................................................................Forbidden (Permission denied): /raises403/
Not Found: /raises404/
................ss.................................................................................................................
```

### CODE REVIEW

**Comment by timgraham** [comment]
Are you able to reproduce that deterministically? I tried ` ./tests/runtests.py view_tests.tests.test_debug --parallel=1` a couple times but don't see any output.

**Comment by pope1ni** [comment]
Hmm... Can't reproduce as I did before, nor with your command. Weird.

I saw it when simply running `./runtests.py` from the `tests` directory without `--parallel`.

I added `LoggingCaptureMixin` to `NonDjangoTemplatesDebugViewTests` as it was used for `DebugViewTests` which calls the same `/raises403/` and `/raises404/` views.

If you don't want to merge this, feel free to close and I can re-open it if it recurs.

**Comment by timgraham** [comment]
I've seen non-deterministic leaking when running tests in parallel. As I recall, this mixin didn't solve the problem and we didn't bother continuing the investigation.

**Comment by pope1ni** [comment]
For what it's worth, this just occurred again this morning (with more logging leaks in other tests):

```
.............................................................................................................................................................Forbidden (Permission denied): /raises403/
Not Found: /raises404/
................ss...Not Found: /site_media/nonexistent_resource
...............Not Found: /site_media/nonexistent_resource
.......................................................................................................................................................................................................

```

And on the run before it I received the following:

```
======================================================================
FAIL: test_version (admin_scripts.tests.CommandTypes)
version is handled as a special case
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib64/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File ".../django/tests/admin_scripts/tests.py", line 1429, in test_version
    self.assertOutput(out, get_version())
  File ".../django/tests/admin_scripts/tests.py", line 202, in assertOutput
    self.assertIn(msg, stream, "'%s' does not match actual output text '%s'" % (msg, stream))
  File "/usr/lib64/python3.6/unittest/case.py", line 1088, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib64/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '2.1.dev20171208085957' not found in '2.1.dev20171208093330\n' : '2.1.dev20171208085957' does not match actual output text '2.1.dev20171208093330
'
```

This was a standard parallel run with 4 processes. The third run was fine.

**Comment by timgraham** [comment]
Yes, the first output is what I've often seen.

The second failure happens when you amend a git commit after starting a test run.

**Pull request closed without merging**
