### PR TITLE
Updated GIS install instructions to use placeholders for GIS library versions.

### PR DESCRIPTION
**Pull request by brylie**
GEOS 3.4.2 reportedly does not work fully as expected. Bump GEOS recommended version to 3.6.2.

https://www.reddit.com/r/django/comments/8pim8i/how_do_i_request_an_edit_in_the_geodjango/

### CODE REVIEW

**Comment by timgraham** [comment]
Could you also bump the versions of the other packages on this page?

**Comment by claudep** [comment]
Shouldn't this snippet written with a placeholder (like `<latest version>`) instead of hardcoding a version number?

> GEOS 3.4.2 reportedly does not work fully as expected

What's the issue?

**Comment by brylie** [comment]
> Shouldn't this snippet written with a placeholder (like <latest version>) instead of hardcoding a version number?

That would seem like a reasonable idea. How could the `latest-version` be inserted into the tutorial? E.g. we could keep a list of latest version for the libraries, and the documentation pre-build script would insert their values throughout the article(s) where relevant.

**Comment by claudep** [comment]
Something like `First, download a Django-supported GEOS archive from the GEOS website...` and then a litteral `<version>` string in the lines below? I don't think inserting a real version number is worth the trouble.

**Comment by brylie** [comment]
Well, I think it is done so people can copy/paste the commands. That makes it easier to get started.

Another idea would be to maintain a basic installation script, so users could just run the script instead of a series of commands.

**Comment by claudep** [comment]
In my opinion, building from source is not for the faint-hearted, but for relatively experienced devs, that's why I think they are able to make the version replacement themselves.

**Comment by timgraham** [comment]
I'd be in favor of placeholders also.

**Pull request merged**
