### PR TITLE
Refs #31300 -- Allowed testing GeneratedField without collation.

### PR DESCRIPTION
**Pull request by timgraham**
CockroachDB and Snowflake don't support it.

### CODE REVIEW

**Comment by felixxm** [comment]
> CockroachDB and Snowflake don't support it.

Is there a collation that can be use for generated fields on CockroachDB and Snowflake? Or is it generally not supported?

**Comment by timgraham** [comment]
I don't think it's supported. Trying to create `model_fields_generatedmodeloutputfieldvirtual` without this change gives:

- [CockroachDB](https://github.com/cockroachdb/cockroach/issues/111091):  expected STORED COMPUTED COLUMN expression to have type collatedvarchar{sv}, but 'lower(name)' has type string
- Snowflake: Data type of virtual column does not match the data type of its expression for column 'LOWER_NAME'. Expected data type 'VARCHAR(11) COLLATE 'en-ci'', found 'VARCHAR(10)'

**Comment by felixxm** [comment]
@timgraham Thanks :+1:

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Pull request merged**
