### PR TITLE
Fixed #29501 -- Allowed dbshell to pass options to the underlying tool.

### PR DESCRIPTION
**Pull request by introquest**
https://code.djangoproject.com/ticket/29501

### CODE REVIEW

**Comment by timgraham** [comment]
Will you add tests and documentation? If so, uncheck those boxes on the ticket after updating.

**Comment by felixxm** [comment]
Closing due to inactivity.

**Comment by PhilipGarnero** [comment]
What's the status on this ?

**Comment by felixxm** [comment]
It's closed due to inactivity. Tests and documentation are required.

**Pull request closed without merging**
