### PR TITLE
restore jquery initial to old style

### PR DESCRIPTION
**Pull request by 9nix00**
please see [ticket#26885](https://code.djangoproject.com/ticket/26885#ticket)

### CODE REVIEW

**Comment by 9nix00** [comment]
I will check the fail reason in my spare time, it may cost a month or later...  sorry.
I am using this PR in my machine. it works well for me.

**Comment by timgraham** [comment]
I don't see this style in Django 1.8?
https://github.com/django/django/blob/stable/1.8.x/django/contrib/admin/static/admin/js/jquery.init.js

**Comment by claudep** [comment]
Looking at `jquery.init.js` history, we never had this `yl` variable defined. You must misunderstand something...

**Comment by 9nix00** [comment]
@timgraham  Sorry, I make a mistake. I found the real jquery.init.js file comes from  django-autocomple-light package. this project rewrite jquery.init.js file.

**Pull request closed without merging**
