### PR TITLE
Fixed #26750 -- Added PointZField model field.

### PR DESCRIPTION
**Pull request by saintbyte**
Add support for postgis field like: location geography(PointZ,4326) or GeoRuby like: t.st_point :location, geographic: true, has_z: true

### CODE REVIEW

**Comment by charettes** [comment]
Hi @saintbyte,

Thanks for your contribution for [as documented](https://github.com/django/django/blob/master/CONTRIBUTING.rst) this feature request will require the creation a [Trac ticket](https://code.djangoproject.com/newticket) (with docs and tests).

Please take a minute to read our [contributing guide](https://docs.djangoproject.com/en/dev/internals/contributing/).

**Comment by saintbyte** [comment]
Ok ticket created https://code.djangoproject.com/ticket/26750#ticket. (its right?)

**Comment by charettes** [comment]
Thanks for the ticket. The patch is still missing tests and docs.

**Comment by saintbyte** [comment]
I working for it =)

**Comment by claudep** [comment]
Replaced by #6801

**Pull request closed without merging**
