### PR TITLE
Fixed #25704 -- Response time in WSGIRequestHandler.log_request

### PR DESCRIPTION
**Pull request by andreif**
ref https://code.djangoproject.com/ticket/25704

### CODE REVIEW

**Comment by charettes** [comment]
Let's wait for #5560 to be merged before adding this feature as they are conflicting. Did you open a ticket for this change?

**Comment by andreif** [comment]
@charettes working on it :)

**Comment by andreif** [comment]
Done: https://code.djangoproject.com/ticket/25704

**Comment by andreif** [comment]
I am waiting for #5560 to be merged, after which I will rebase and include time in the log params

**Comment by timgraham** [comment]
The dependency is merged so you can rebase this at your convenience.

**Comment by timgraham** [comment]
Please send a new PR if you have time to return to it. I suppose tests might be needed too. Thanks!

**Pull request closed without merging**
