### PR TITLE
Fixed #24607 -- Fixed handling of natural keys in models that use inheritance

### PR DESCRIPTION
**Pull request by denys-duchier**
this PR concerns my bug report https://code.djangoproject.com/ticket/24607

@timgraham I have rebased it on master and added tests, as you asked in my previous PR https://github.com/django/django/pull/4473

In the last commit, I have also explained (and fixed) why it must be the case that use_natural_primary_keys => use_natural_foreign_keys.

### CODE REVIEW

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
@mrmachine, as the original author of the natural-primary/foreign options, do you have any feedback on this?

**Comment by denys-duchier** [comment]
@timgraham @mrmachine, we have a large django project that is stuck at 1.6.  we cannot possibly upgrade until json serialization works properly. what can I do to make this PR advance towards merging?

**Comment by timgraham** [comment]
Is this is a regression from Django 1.6? If so, I didn't realize / see how.

**Comment by denys-duchier** [comment]
yes, it is a regression... but I imagine few people actually require the odd bits of serialization that we do.

I developed a way to snapshot a database so that any snapshot could be reloaded into any later version of the app (regardless of intervening migrations on any app).  we depend very much on that capability.  it is unfortunately broken on master without the fix I proposed.

**Comment by timgraham** [comment]
On 1.6, there's only the `--natural` option. My understanding is that this is equivalent to the `--natural-foreign` option in 1.7+. In the test case you added, `test_neither` and `test_foreign` both pass on master without the changes proposed in this PR, so there's only a problem (as far as I can tell) when you add the new `natural_primary_keys` option. Can't you simply omit `natural_primary_keys` to achieve the same serialized results as as `dumpdata --natural` in 1.6?

**Comment by timgraham** [comment]
Please reply if I missed something. In the meantime, I'll propose a documentation patch on the ticket.

**Pull request closed without merging**
