### PR TITLE
Fixed #32504 -- Updated admin's jQuery to 3.6.0.

### PR DESCRIPTION
**Pull request by felixxm**
ticket-32504

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Review by carltongibson — APPROVED** [review]
Good. Thanks @felixxm

**Comment by felixxm** [comment]
@carltongibson Thanks for checking :+1:

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Pull request merged**
