### PR TITLE
fixed #28946 - login.css padding fix

### PR DESCRIPTION
**Pull request by kakulukia**
https://code.djangoproject.com/ticket/28946

this simply looks better and matches the mobile resolution settings

### CODE REVIEW

**Comment by timgraham** [comment]
Thanks for the contribution. A [Trac ticket](https://code.djangoproject.com/) that explains the issue (screenshots would be helpful) is required. Try to rebase your branch so that the merge commits don't appear here.

**Comment by kakulukia** [comment]
Okay, here is the matching ticket: https://code.djangoproject.com/ticket/28946
rebasing now ..

**Comment by kakulukia** [comment]
okay, i suck at rebasing .. need to look at a good tutorial, because i never needed it so far.
Any hints @timgraham ?

Took a fresh copy of master and cherrypicked that one commit. :)
That should do the trick for now.

**Comment by timgraham** [comment]
I can't reproduce the missing padding as shown in the screenshots in the ticket. Do you see the same missing padding at https://www.djangoproject.com/admin/login/ ?

**Comment by kakulukia** [comment]
No, cannot see it there either, but it’s also a different button, which i haven’t seen in the admin for a while! Is that a recent version?

**Comment by timgraham** [comment]
djangoproject.com is running Django 1.11 -- for me, the button there looks similar to the one in your screenshot on the ticket.

**Comment by kakulukia** [comment]
The Button i see on my phone is rounded and kinda 3D. Let me cross check with my laptop later.

**Comment by kakulukia** [comment]
Okay, i checked on my browser now and it looks okay, BUT not due to the right padding. The Admin at djangoproject.com renders an additional footer div, which is not present on my Django installation.
See this screenshot
bildschirmfoto 2017-12-28 um 22 26 57

**Comment by timgraham** [comment]
I guess there may be something odd with your install, as I haven't seen the problematic behavior before. Maybe a third-party app is inserting some custom styles or something similar?

**Comment by kakulukia** [comment]
Okay, i found whats causing the problem. In my installation this footer block (https://github.com/django/django/blob/3c447b108ac70757001171f7a4791f493880bf5b/django/contrib/admin/templates/admin/base.html#L83) is used to insert some admin scripts and therefor overwrites the empty footer div.

So i reinserted the footer to check whats happening for mobile resolutions:
    
    @media (max-width: 767px)
    responsive.css:458
    #footer:empty {
      padding: 0;
    }

The footer gets hidden on mobile and the other padding kicks in. So there are two different ways of handling the footer and different paddings on desktop and mobile. This could be simplified with my fix together with the above mobile styling applied to all resolutions. 

But i will keep the footer to have it visually fixed again on my side for now.
If you want to simplify the Django stylings, tell me and i will create a new enhanced PR like explained above otherwise be my guest in closing the issue, because its just not that important. :)

Have a final look at the current state of the footer handling:
bildschirmfoto 2017-12-28 um 22 58 50
bildschirmfoto 2017-12-28 um 22 59 05

**Comment by timgraham** [comment]
@elky, any opinion about that?

**Pull request closed without merging**
