### PR TITLE
Fixed #29826 -- Made urlize handle HTML angle brackets.

### PR DESCRIPTION
**Pull request by duck-rh**
This also incidentally simplifies the handling of the trail.
http://code.djangoproject.com/ticket/29826

### CODE REVIEW

**Comment by carltongibson** [comment]
> The test passes without the code changes.

Grrr. It's was Tim's PR #10505 that made me look at this. Who'd have thought? 🙂

So it comes down to, what's the expected behaviour here: 

> `urlize('&lt;https://www.example.org/&gt;'),`

**Comment by duck-rh** [comment]
@carltongibson the original problem is to get Gmail's automatic addition of angle brackets around URLs be properly transformed to links in the context of the Mailman 3 Hyperkitty's web interface. Currently the closing angle bracket is dragged into the link making it unusable.

I find this quite mean from @timgraham to get PR #10505 quickly merged before any decision is taken here, thus rendering this work moot.

urlize() was not initially intended to not handle HTML, as the remnants of the code confirms, as well as the old documentation which did not have this warning. Of course as upstream you may decide handling HTML is too complicated and not the way to go. Nevertheless this is a useful feature and the code to handle it is already complex, so this is not a matter of adding your 3 lines custom filter in your project, so I would believe it more useful to be included in Django itself.

Maybe this function could be restricted to text content and a urlize_hmtl() function created to handle the common uses cases with HTML content.

**Comment by timgraham** [comment]
I merged the code simplification in https://github.com/django/django/pull/10507. Feel free to continue the discussion on the [django-developers mailing list](https://groups.google.com/forum/#!forum/django-developers) as described on the ticket.

**Comment by duck-rh** [comment]
@carltongibson that is not true. WRAPPING_PUNCTUATION is used to find the angle brackets, and unescaping before checking the match was part of the solution to the MM3 problem.

I'm glad the code simplification was useful. I do not have the time and energy to explain and justify again all the things, also considering I have no idea how to make the case clearer to you. I wanted to help the MM3 developers get a clean solution but I guess that's not gonna happen anytime soon.

**Pull request closed without merging**
