### PR TITLE
Refs #25894 -- Fixed evaluation of zero-length slices of QuerySet.values() on Oracle.

### PR DESCRIPTION
**Pull request by sir-sigurd**
https://code.djangoproject.com/ticket/25894

### CODE REVIEW

**Comment by charettes** [comment]
Buildbot, test on oracle

**Comment by timgraham** [comment]
buildbot, test on oracle.

**Comment by charettes** [comment]
Did I misspell something?

**Comment by timgraham** [comment]
missing period

**Comment by timgraham** [comment]
merged in ed1bcf05158acf4bf4e0189d477b6c762bd0133e, thanks!

**Pull request closed without merging**
