### PR TITLE
Fixes #33697 Cleanup duplication of HTTP header parsing in utils.http and multipart parser

### PR DESCRIPTION
**Pull request by mehrdadmoradii**
Refactoring the duplicate of HTTP header parsing function that exists at django.utils.http and django/utils/http.py and Unifying the function under django.utils.http.

### CODE REVIEW

**Review by felixxm — COMMENTED** [review]
@mehrdadmoradii Thanks for this patch :+1: I would start from unifying logic in both implementation, i.e. adding in a separate PR https://github.com/python/cpython/commit/1ef0c0349e8fdb5415e21231cb42edbf232b742a to the `_parse_header_params()` with a proper regression test.

Also, we should try to avoid internal hooks as `f()`, `_f()` which cause a lot of conversions on hot-paths and make code less readable. Can we enforce using the same type of input values instead?

**Comment by mehrdadmoradii** [comment]
@felixxm Thanks for the review. 

Just to make sure I understand, first, I need to start unifying the logic of utils.http._parse_header_params() and http.multipartparser._parse_header_params() into utils.http._parse_header_params() via a separate PR with a proper regression test to make sure I didn't break anything. Afterwards, start working on utils.http.parse_header_parameters(). Please correct me if I'm wrong.

Also, can we enforce "str" as an input type for the header on both multipart and otherwise - coerce the binary input or throw an exception?

**Comment by felixxm** [comment]
> Just to make sure I understand, first, I need to start unifying the logic of utils.http._parse_header_params() and http.multipartparser._parse_header_params() into utils.http._parse_header_params() via a separate PR with a proper regression test to make sure I didn't break anything. Afterwards, start working on utils.http.parse_header_parameters().

Yes, exactly :+1:  I'd start from adding in a separate PR https://github.com/python/cpython/commit/1ef0c0349e8fdb5415e21231cb42edbf232b742a to the `_parse_header_params()` with a proper regression test.

> Also, can we enforce "str" as an input type for the header on both multipart and otherwise - coerce the binary input or throw an exception?

Yes, we should unify the input type to `str` or `bytes`.

**Comment by felixxm** [comment]
@mehrdadmoradii In the second step we could switch to `parse_header_parameters()` in the `MultiPartParser.__init__()`, e.g.
```diff
diff --git a/django/http/multipartparser.py b/django/http/multipartparser.py
index 26fb2bc41f..b7a26b3d8f 100644
--- a/django/http/multipartparser.py
+++ b/django/http/multipartparser.py
@@ -19,6 +19,7 @@ from django.core.exceptions import (
 from django.core.files.uploadhandler import SkipFile, StopFutureHandlers, StopUpload
 from django.utils.datastructures import MultiValueDict
 from django.utils.encoding import force_str
+from django.utils.http import parse_header_parameters
 from django.utils.regex_helper import _lazy_re_compile
 
 __all__ = ("MultiPartParser", "MultiPartParserError", "InputStreamExhausted")
@@ -49,7 +50,7 @@ class MultiPartParser:
     and returns a tuple of ``(MultiValueDict(POST), MultiValueDict(FILES))``.
     """
 
-    boundary_re = _lazy_re_compile(rb"[ -~]{0,200}[!-~]")
+    boundary_re = _lazy_re_compile(r"[ -~]{0,200}[!-~]")
 
     def __init__(self, META, input_data, upload_handlers, encoding=None):
         """
@@ -72,7 +73,7 @@ class MultiPartParser:
 
         # Parse the header to get the boundary to split the parts.
         try:
-            ctypes, opts = parse_header(content_type.encode("ascii"))
+            ctypes, opts = parse_header_parameters(content_type)
         except UnicodeEncodeError:
             raise MultiPartParserError(
                 "Invalid non-ASCII Content-Type in multipart: %s"
```

**Comment by mehrdadmoradii** [comment]
@felixxm Got it 👌.

**Comment by felixxm** [comment]
> @felixxm Got it ok_hand.

I would submit a separate PR with this small cleanup, instead of pushing it into this PR.

**Comment by mehrdadmoradii** [comment]
@felixxm I'm on it.

**Comment by felixxm** [comment]
@mehrdadmoradii Do you have time to keep working on this?

**Comment by mehrdadmoradii** [comment]
@felixxm Absolutely, I'm just going to submit the next PR.

**Comment by felixxm** [comment]
Closing in favor of #15797.

**Pull request closed without merging**
