### PR TITLE
Fixed #33131 -- Improved error messages for clashing reverse accessor names.

### PR DESCRIPTION
**Pull request by bernd-wechner**
I just spent ages trying to work out what this migration error meant after I added a new app. This very minor addition to the feedback could have saved me a load of time getting my head around what was happening.

### CODE REVIEW

**Comment by kezabelle** [comment]
Hi Bernd, 
Please open a [ticket on Trac](https://code.djangoproject.com/newticket) if there isn't one already (apologies if there is, I haven't spotted it).

I absolutely agree that it would be useful to say what the clashing name was. 

It looks like (based on the test failures) the following unit tests will need to be updated to accommodate the change in message:
```
invalid_models_tests.test_relative_fields.AccessorClashTests.test_clash_between_accessors
invalid_models_tests.test_relative_fields.ComplexClashTests.test_clash_parent_link
invalid_models_tests.test_relative_fields.ComplexClashTests.test_complex_clash
invalid_models_tests.test_relative_fields.SelfReferentialM2MClashTests.test_clash_between_accessors
```

**Comment by bernd-wechner** [comment]
> Please open a [ticket on Trac](https://code.djangoproject.com/newticket)

Voila: https://code.djangoproject.com/ticket/33131#ticket

Will review the patch review checklist soon.

**Comment by felixxm** [comment]
@bernd-wechner Do you have time to keep working on this?

**Comment by bernd-wechner** [comment]
Soon. Life's busy. Priorities. But a good reminder.

**Comment by bernd-wechner** [comment]
Wow, took a quick look. one tiny line tweak and 13 workflow failures? Most of which produce a 404 error when I click on Details. And the only one that doesn't is a New Contributor message with no clear indication as to what is wrong. What am I to do? 

I would love to get this cleaned up and learn what's up. I'm more than happy to contribute positively to Django (as I use it a lot) but this experience is less than encouraging so far ... I'd like to establish a workflow that, well, works ...

**Comment by felixxm** [comment]
> I would love to get this cleaned up and learn what's up. I'm more than happy to contribute positively to Django (as I use it a lot) but this experience is less than encouraging so far ... I'd like to establish a workflow that, well, works ...

We don't keep the entire history on Jenkins, that's why you're getting 404. You can rebase from the main branch and push again for a fresh build. Failures are related with the changed message (see `invalid_models_tests`). Please update also `fields.E302`, related tests, and [docs](https://docs.djangoproject.com/en/3.2/ref/checks/#related-fields).

**Comment by bernd-wechner** [comment]
>  (see `invalid_models_tests`). Please update also `fields.E302`

Can you interpret that for an inexperienced reader (like yours truly)?

**Comment by felixxm** [comment]
> (see `invalid_models_tests`)

You can run `invalid_models_tests` [locally](https://docs.djangoproject.com/en/3.2/internals/contributing/writing-code/unit-tests/#running-only-some-of-the-tests) to check failures before submitting updates, e.g.
```
./runtests.py invalid_models_tests
```
> Please update also `fields.E302`

`fields.E302` is a similar check:

https://github.com/django/django/blob/d400b08a8baa697905daadd47a6ba12336e93336/django/db/models/fields/related.py#L239-L248

I suggested to update it as well.

**Comment by bernd-wechner** [comment]
Got me with a moment to spare tonight between a few things and my attention and a burning desire to understand Django contribs better and get it right so I got started with:

https://docs.djangoproject.com/en/3.2/internals/contributing/writing-code/unit-tests/

Alas up front I note the instructions could be a tad clearer  ;-).  Only because to work:

```
python -m pip install -r requirements/py3.txt
```

won't do .... alas. Loads of noxious red garble on the screen. So first tune my console to use a legible colour for the red (which I though I did a while back) and then reading them I find essentially I needed to:

```
pip install wheel
sudo apt install libmemcached-dev 
```

Then the requirements installed fine. The second line of course is system dependent and my cited example is apt based some Debia/Ubuntu stream. The first line though is missing from `requirements/py3.txt` and I reckon I should add it as part of the PR? It's actually a very common problem, and I run into it a lot that docs presume wheel is installed. And in a new venv it never is it seems and having it in the requirements seems often overloooked somehow.

That said am looking at the test failures now ;-)

**Comment by felixxm** [comment]
> The first line though is missing from `requirements/py3.txt` and I reckon I should add it as part of the PR? It's actually a very common problem, and I run into it a lot that docs presume wheel is installed. And in a new venv it never is it seems and having it in the requirements seems often overloooked somehow.

I've just created a new virtual env (Python 3.8, Ubuntu) and all worked fine without `wheel`:
```
$ python -m pip install -e ..
Obtaining file:///django
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting asgiref>=3.3.2
  Using cached asgiref-3.4.1-py3-none-any.whl (25 kB)
Collecting sqlparse>=0.2.2
  Using cached sqlparse-0.4.2-py3-none-any.whl (42 kB)
Collecting backports.zoneinfo
  Using cached backports.zoneinfo-0.2.1-cp38-cp38-manylinux1_x86_64.whl (74 kB)
Installing collected packages: sqlparse, backports.zoneinfo, asgiref, Django
  Running setup.py develop for Django
Successfully installed Django-4.1.dev20211001111137 asgiref-3.4.1 backports.zoneinfo-0.2.1 sqlparse-0.4.2

$ python -m pip install -r requirements/py3.txt
...
Successfully installed MarkupSafe-2.0.1 Pillow-8.3.2 PyYAML-5.4.1 aiohttp-3.7.4.post0 argon2-cffi-21.1.0 async-timeout-3.0.1 attrs-21.2.0 bcrypt-3.2.0 certifi-2021.5.30 cffi-1.14.6 chardet-4.0.0 charset-normalizer-2.0.6 docutils-0.17.1 geoip2-4.4.0 idna-3.2 jinja2-3.0.1 maxminddb-2.2.0 multidict-5.2.0 numpy-1.21.2 pycparser-2.20 pylibmc-1.6.1 pymemcache-3.5.0 python-memcached-1.59 pytz-2021.3 pywatchman-1.4.1 redis-3.5.3 requests-2.26.0 selenium-3.141.0 six-1.16.0 tblib-1.7.0 typing-extensions-3.10.0.2 tzdata-2021.2.post0 urllib3-1.26.7 yarl-1.6.3
```

**Comment by bernd-wechner** [comment]
Bizarre, cannot explain that. Could be the order. I think I overlooked: `python -m pip install -e ..` on first try, and that may be the difference. Trying to interpret test results now and test definitions.  Fails on 4 assertions.

**Comment by bernd-wechner** [comment]
Ouch, been looking at the code behind these failures and starting to see why no-one wants to go there ;-).

The reports are superbly cryptic and unhelpful. Take a look at this:

```
FAIL: test_complex_clash (invalid_models_tests.test_relative_fields.ComplexClashTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/media/Data/Workspace/Eclipse/Django/django/tests/invalid_models_tests/test_relative_fields.py", line 1414, in test_complex_clash
    self.assertEqual(Model.check(), [
  File "/usr/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.8/unittest/case.py", line 1118, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/usr/lib/python3.8/unittest/case.py", line 1100, in assertSequenceEqual
    self.fail(msg)
  File "/usr/lib/python3.8/unittest/case.py", line 753, in fail
    raise self.failureException(msg)
AssertionError: Lists differ: [<Err[801 chars]ssor ('Target.id') for 'invalid_models_tests.M[3805 chars]05'>] != [<Err[801 chars]ssor for 'invalid_models_tests.Model.foreign_1[3737 chars]05'>]
```

What the heck is `ssor`? Still not found where that creeps in.  

Getting closer though. Stepping through the code. We're lucky that tonight my wife is stressed preparing stuff for uni tomorrow, the kids are in bed, and I've had enought of my other projects for the moment ;-). Won't last so I better get cracking and try to work out how to fix the test expectations for these failures.  Fixed 2 of 4 already, but ...

**Comment by jacobtylerwalls** [comment]
The failure report is hard to read, true, but the `[801 chars]` means the output was truncated. If you look up the failing test `test_complex_clash` and ctrl-F for "ssor" you'll see it's part of the word "accessor".

Try setting inserting the line `self.maxDiff = None` into the test case right before the assertion to get a bigger diff from the test failure. This test case should probably have it.

**Comment by bernd-wechner** [comment]
Thanks for that. Appreciate it. I did establish a little workflow for this painful process, and did fix the tests. I then encountered a hell hole of push issues to the branch because I use gitkraken generally and it's spitting errors about lacking worklflow permission so went to the cli and it can't log in and had to generate a new personal access token, and on and on and on ... 

and then even though I rebased the branch onto the latest main, when I did push, blam the this PR says 107 files changed. I',m puling hair out. How hard do these guys want to make this? The commit changed one extra file, not 106 extra files.

**Comment by bernd-wechner** [comment]
I cannot fathom what github is doing, except to suppose:

https://github.com/bernd-wechner/django/commits/improve-reverse-accessor-clash-feedback

that what happens here is because the branch was from an old version of main (but hey I rebased it!) this push merged all the main branch changes onto the branch and that was the 106 little surprises. Which is NOT what we wanted. I wonder is this undoable or is it easier to trash the branch and create a new one cherry picking these two commits and them pushing them.

**Comment by bernd-wechner** [comment]
Wow, that was a mess, but the PR looks cleaner, just the two files in question now. Next would the doc.

All I can says is, git is both a blessing and a bane (I wonder if you can count the number of people who can explain and understand rebasing, fast forwarding and such in the world on your fingers or if you'd need your toes as well ;-). I reread that stuff ever few months because I can't remember.

**Comment by bernd-wechner** [comment]
Oh and `fields.E302`. On the morrow. Past midnight now ... At least I think I have a clean repo again. 

Methinks what happened is I rebased the local and not the remote (origin) and so the push at the remote was onto a formk of main 105 commits ago.

Alas gitkraken on this repo and and this repo only bails on pushes with:

Push Failed: improve-reverse-accessor-clash-feedback: Push failed on refs/heads/improve-reverse-accessor-clash-feedback: refusing to allow an OAuth App to create or update workflow `.github/workflows/linters.yml` without `workflow` scope

So I had have to use the CLI to push (which uses ssh access and and a personal access token)

**Comment by bernd-wechner** [comment]
Thanks for you support BTW, all good upskilling (albeit IMHO frustrating at some levels) in the PR game. Been PRing a fair bit this last year, but this repo poses some special problems it seems (with gitkraken).

**Comment by felixxm** [comment]
> All I can says is, git is both a blessing and a bane (I wonder if you can count the number of people who can explain and understand rebasing, fast forwarding and such in the world on your fingers or if you'd need your toes as well ;-). I reread that stuff ever few months because I can't remember.

Don't worry we can squash & rebase for you with final edits, we do this every day.

**Comment by bernd-wechner** [comment]
Well tests all passed bar one flake. Looking better. Likely I'll finish this off this week between things as it's very close and been a large learning curve.

**Comment by bernd-wechner** [comment]
Well, once in the swing, it's much quicker. Just patched 302 and pushed the branch. All tests pass locally, and we'll see what Jenkins says shortly.

**Comment by bernd-wechner** [comment]
Dang, lots of new failures ;-). Overlooked 302 related issues. Clearly no invoked by the `invalid_models_tests` run. I shall have to seek and destroy them too ;-). It would be helpful if Jenkins reported the test that broke in the list without without having to open each of 17 items.

**Comment by felixxm** [comment]
> It would be helpful if Jenkins reported the test that broke in the list without without having to open each of 17 items.

Here you go https://djangoci.com/job/pull-requests-bionic/13541/#showFailuresLink.

**Comment by felixxm** [comment]
Only one test is broken: `model_inheritance.test_abstract_inheritance.AbstractInheritanceTests.test_reverse_foreign_key`.

**Comment by bernd-wechner** [comment]
Wow you're quick Felixxm! Looks like all the one line. Fixed and pushed (which works in gitkraken now!) Fingers cross got all the 302s now.

**Comment by bernd-wechner** [comment]
Out of interest, for my learning here, where does Jenkins run? We run it at work on a build server. is it running at the github end as a service, or do you need an instance runnning somwhere else to report to github?

**Comment by felixxm** [comment]
> Out of interest, for my learning here, where does Jenkins run? We run it at work on a build server. is it running at the github end as a service, or do you need an instance runnning somwhere else to report to github?

Some details can be found on the [wiki page](https://code.djangoproject.com/wiki/Jenkins).

**Comment by bernd-wechner** [comment]
And yippee!! 21 successful checks. At last. Been a great leg up and learning exercise for Django contribs.

Out of interest is how is https://djangoci.com/ hosted. Am mildly curious about Django's org structure and funding. Hosted by a cloud provide like Amazon? Or an angel investor?

**Pull request merged**
