### PR TITLE
Fixed #23791 -- Corrected object type check for pk__in=qs

### PR DESCRIPTION
**Pull request by akaariai**
When the pk was a relation field, qs.filter(pk__in=qs) didn't work.

### CODE REVIEW

**Comment by akaariai** [comment]
I'll do a rebase and rewording of the commit message before merge.

**Comment by jarshwah** [comment]
LGTM

**Comment by timgraham** [comment]
cosmetic edits: http://dpaste.com/3X3E6JN

**Comment by timgraham** [comment]
merged in 9ed82154bd0bd01c6195942db84302e791ad366f, thanks!

**Pull request closed without merging**
