### PR TITLE
Refs #24121 -- Improved Value.__repr__().

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Comment by felixxm** [comment]
`Value.__repr__()` should return a string that will allows to create an object with the same value.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Review by charettes — APPROVED** [review]

**Comment by felixxm** [comment]
@charettes Thanks for checking :+1:

**Pull request merged**
