### PR TITLE
Refs #35059 -- Adjusted test to use asyncio.Event for waiting.

### PR DESCRIPTION
**Pull request by carltongibson**
Sleep call leads to a hard to trace error in CI. Using an Event is more deterministic, and should be less prone to environment variations.

Bug in 11393ab1316f973c5fbb534305750740d909b4e4.

# Trac ticket number

ticket-35059

# Branch description

Sleep call leads to a hard to trace error in CI. Using an Event is more deterministic, and should be less prone to environment variations.

# Checklist
- [x] This PR targets the `main` branch. 
- [x] The commit message is written in past tense, mentions the ticket number, and ends with a period.
- [x] I have checked the "Has patch" ticket flag in the Trac system.
- [x] I have added or updated relevant tests.
- [x] I have added or updated relevant docs, including release notes if applicable.
- [x] I have attached screenshots in both light and dark modes for any UI changes.

### CODE REVIEW

**Comment by carltongibson** [comment]
@nessita I don't know if this will do it or not, but maybe 🤞

**Review by nessita — APPROVED** [review]
Looks good, thanks!
I want to confirm if this consistently fixes `main` by waiting a few runs (a week maybe?) and when confirmed, I'll backport to 5.1.

**Comment by carltongibson** [comment]
Sounds good. Likely 5.0 could do with it too? 🤔

**Comment by nessita** [comment]
/remind me to backport this fix to 5.0 and 5.1 in one week

**Comment by nessita** [comment]
Backported to 5.1 in dd3d0483ab6953b769077f16828ff88d0c2bffc4 and to 5.0 in dd3d0483ab6953b769077f16828ff88d0c2bffc4

**Pull request merged**
