### PR TITLE
Update Grammer mistake

### PR DESCRIPTION
**Pull request by krishnathanki**
Just made a small grammer change in the Text file

### CODE REVIEW

**Comment by krishnathanki** [comment]
just a grammer change done

**Comment by felixxm** [comment]
@krishnathanki Please send all suggestions in a single PR.

**Comment by smithdc1** [comment]
I don't believe we should be changing the LICENSE. Surely a matter for the DSF board?

**Comment by felixxm** [comment]
> I don't believe we should be changing the LICENSE. Surely a matter for the DSF board?

Yes, that's true.

**Pull request closed without merging**
