### PR TITLE
Fixed #25304 -- Added option to allow management commands to check if migrations are applied.

### PR DESCRIPTION
**Pull request by MounirMesselmeni**
adding required_migrations_checks to BaseCommand to support unapplied migrationgs on other managements command, runserver, createsuperuser and changepassword activate this check

### CODE REVIEW

**Comment by timgraham** [comment]
Looks reasonable except tests aren't running and the new option should be documented in `docs/howto/custom-management-commands.txt` and the 1.10 release notes.

**Comment by MounirMesselmeni** [comment]
Tests fixed and docs updated.

**Comment by timgraham** [comment]
Looking good. Some minor edits: http://dpaste.com/1PAKNJA
I think a simple test in `tests/user_commands/tests.py` would be useful. Maybe mocking `the `BaseCommand.check_migrations()` and testing whether or not it's called based on the value of `requires_migrations_checks` would be enough.

**Comment by timgraham** [comment]
Hi, are you able to update this? We could offer it as "easy pickings" if not.

**Comment by MounirMesselmeni** [comment]
Hi Tim, you can check the update which include the test.

**Comment by timgraham** [comment]
merged in 50931dfa5310d5ae1c6e2852d05bf1e86700827f, thanks!

**Pull request closed without merging**
