### PR TITLE
Refs #27236 -- Made operation deprecation checks run only on unapplied migrations.

### PR DESCRIPTION
**Pull request by felixxm**
See [comment](https://code.djangoproject.com/ticket/27236#comment:27).

Thanks Collin Anderson for the report.

Regression in 41019e48bbf082c985e6ba3bad34d118b903bff1.

### CODE REVIEW

**Comment by felixxm** [comment]
`spawn` doesn't like it :thinking:

**Comment by David-Wobrock** [comment]
> `spawn` doesn't like it 🤔

It would seem that `{'default': False, 'other': False}` is the input of the `core.checks.migrations.check_migration_operations` when running tests in parallel 🤔 
Is that the default DB config when spawning workers for the tests? How could we change that/catch that nicely?

**Comment by collinanderson** [comment]
"run only on unapplied migrations" makes sense to me. Thanks!

**Comment by felixxm** [comment]
Rebased on #15852.

**Review by David-Wobrock — APPROVED** [review]
Good catch for the `check` command call 👍

**Review by David-Wobrock — APPROVED** [review]

**Review by carltongibson — APPROVED** [review]
OK, looks sane. 👍

**Comment by felixxm** [comment]
Closing in favor of #15861.

**Pull request closed without merging**
