### PR TITLE
Amend comment to remove reference to the no longer used NullHandler

### PR DESCRIPTION
**Pull request by nealtodd**
null handler removed in 987e4b91

### CODE REVIEW

**Comment by charettes** [comment]
Could also remove the mention in `docs/topics/logging.txt`?

**Comment by claudep** [comment]
Sorry Simon, I already pushed the patch. I will care for the docs...

**Comment by claudep** [comment]
@charettes What mentions are you referring to? Did you mean to update the "complex" config example?

**Comment by nealtodd** [comment]
Sorry, I hadn't grepped the docs for Nullhandler. I can remove from logging.txt too.

**Comment by charettes** [comment]
No worries Claude, I found two mentions of it using grep. The complex config example is one of them.

**Comment by nealtodd** [comment]
Logging docs updated in commit a3d5d2ad (based partly on the default logging in `utils/log.py`)

Not sure how you want to incorporate it as the original commit has already been merged.

**Comment by timgraham** [comment]
merged doc update in b3acdeee502e961065bfcdb7673d7cf91ab5b283, thanks!

**Pull request closed without merging**
