### PR TITLE
[WIP] Fixed #28053 -- Support db_index=Index()

### PR DESCRIPTION
**Pull request by mjtamlyn**
WIP PR for expanding `db_index` to allow explicitly setting an index. It moves the responsibility for the indexes on a field to the field. This is also a step towards allowing a field type to define a default index type (e.g. for JSON or HStore fields, and for GIS).

TODO:
- [ ] Allow (for PG at least) [ops classes](https://www.postgresql.org/docs/9.5/static/indexes-opclass.html) when creating an index, so the Like index can be explicitly added. This can probably be done with an expression after #8056 is complete. **At present the logic for creating the like index (named `_like`) is there, but it creates a plan btree index!**
- [ ] Handle MySQL ForeignKey special case
- [ ] Possibly also fix #8118 - relates to `TextField` not having indexes on MySQL (or Oracle?) when indexed.
- [x] Handle Postgres Like indexes naming properly - maybe allow passing a max_length to an index?
- [ ] Possibly also address [this ticket](https://code.djangoproject.com/ticket/24082) about `unique=True` and indexes on PG text fields
- [ ] Some other tests need `clone_model` adding to fix things
- [x] Handle legacy index names (see also #8329)
- [ ] Change to using `Index.set_name_from_model()` (i.e. short index names) in both cases, and update all the tests where names change.
- [ ] More tests for changing values of `db_index`, especially changing from one kind of index to another
- [ ] Docs (including documenting change to `SchemaEditor.add_field`)

Questions:
- Should we be more careful about setting `Index.fields()`? Do we need to verify that it only affects this field, or that no fields should be permitted on init when it's a `db_index`? How does this fit with indexes taking expressions?

Backwards incompatible changes:
- `SchemaEditor.add_field` now takes the `to_model` in the signature. This could possibly be handled more carefully, and the `to_model` is not *always* necessary, only when an index changes, so the code could be crafted to make `to_model` optional except where necessary for backwards compatibility reasons. I'm not sure it's worth it though.

### CODE REVIEW

**Comment by timgraham** [comment]
Closing due to inactivity.

**Comment by auvipy** [comment]
@cansarigol I saw you are handling a lot of orm stuff lately, would you mind checking this pr if it is possible for you to take this over and complete as per discussion on the ticket?

**Comment by cansarigol** [comment]
thanks, @auvipy , I'll be glad if I could help. Looking at as soon as possible.

**Comment by cansarigol** [comment]
I've been working to understand the issue and bringing my pr to this pr level. 
@auvipy I'm pursuit this WIP PR's to-do items, aren't I?

[My commit](https://github.com/django/django/commit/c07fecb0d9b25fec9ea3f57601a6e9338608e265)

**Comment by auvipy** [comment]
it seems you are

**Comment by cansarigol** [comment]
I thought that we might proceed without delete the `_field_indexes_sql` just change something. This is tough because of `_alter_field` func. I couldn't pass `test_alter_field_to_explicitly_named_index`. I'm working this test on. If I can achieve, we can proceed with less change code.

**Comment by cansarigol** [comment]
By the way, should I start a new pr for my commits

**Pull request closed without merging**
