### PR TITLE
Fixed #26052 Response content of HEAD requests will no longer be removed

### PR DESCRIPTION
**Pull request by ArcTanSusan**
This is my attempt to fix https://code.djangoproject.com/ticket/26052 during the djangocon europe sprints. :saxophone: 

Yay removing code.

### CODE REVIEW

**Comment by timgraham** [comment]
What are the ramifications of this removal? Probably some mention of the behavior change is need in the release notes?

**Comment by ArcTanSusan** [comment]
I changed the commit message to be clearer --  " Fixed #26052 Response content of HEAD requests will no longer be removed" according to advice from http://blog.dscpl.com.au/2009/10/wsgi-issues-with-http-head-requests.html.

**Comment by syphar** [comment]
if I'm not mistaken this changes far more than only the `HEAD` request, since the content also was removed for `204` requests (for example)

Django's Conditional GET handling is not a problem though, since `get_conditional_response` and `_not_modified` return empty responses. 

It _will_ have an effect on anyone else returning responses with status `304 Not Modified`

**Comment by timgraham** [comment]
I guess this also needs improvement per the ticket description? ("We should check whether mod_wsgi, gunicorn and uwsgi properly strip the body of HEAD requests before proceeding. We should also move that behavior into runserver -- that is, on the other side of the WSGI.")

**Comment by timgraham** [comment]
Updated as discussed on the ticket in https://github.com/django/django/pull/6505.

**Pull request closed without merging**
