### PR TITLE
Add a note about same-origin as a referrer policy.

### PR DESCRIPTION
**Pull request by coderanger**

### CODE REVIEW

**Comment by coderanger** [comment]
Any objections to this?

**Comment by kezabelle** [comment]
Thank goodness for MDN provides an example table to lookup the various policies and how they behave ;) Seems sensible enough to me, though I'd encourage someone with more awareness of CSRF & all the security jazz gets pinged to double-triple-check this is the right policy to recommend in such cases.

TBH I feel like the _whole admonition_ could do with a bit of a rewording, because it's essentially "you might think you want want to do this, but don't" but phrased in an encouraging way that initially suggests you _should_ do them...

**Comment by felixxm** [comment]
@coderanger Do you have time to keep working on this?

**Comment by felixxm** [comment]
Closing due to inactivity.

**Pull request closed without merging**
