### PR TITLE
Fixed #34592 -- Removed Safari/Chrome workaround for system fonts.

### PR DESCRIPTION
**Pull request by minusf**
https://code.djangoproject.com/ticket/34592

### CODE REVIEW

**Comment by felixxm** [comment]
@knyghty Can you take a look?

**Comment by felixxm** [comment]
@minusf Thanks :+1:

**Review by knyghty — APPROVED** [review]
Yes, looks good, browser support looks like it's there, thanks for keeping on top of this.

Maybe one day we won't even need the hack for Windows.

**Comment by felixxm** [comment]
@knyghty Thanks for checking :+1:

**Pull request merged**
