### PR TITLE
Fixed permissions for GitHub action with screenshots.

### PR DESCRIPTION
**Pull request by felixxm**
Follow up to 97b7970c6479ef414175f22a009240ed0df8ce46.

### CODE REVIEW

**Comment by ngnpope** [comment]
I'm not sure that explicitly passing the token required?

I found [this](https://github.com/actions/labeler#permissions) which seems to imply we should use `pull_request_target:` instead of `pull_request:`?

**Comment by felixxm** [comment]
This probably will not help if it's not merged.

**Comment by felixxm** [comment]
> I'm not sure that explicitly passing the token required?
> 
> I found [this](https://github.com/actions/labeler#permissions) which seems to imply we should use `pull_request_target:` instead of `pull_request:`?

It depends, action permissions are [tricky](https://github.com/django/django/commits/main/.github/workflows/new_contributor_pr.yml) and it works that way for [new_contributor_pr.yml](https://github.com/django/django/blob/main/.github/workflows/new_contributor_pr.yml). Therefore, we can do the same here, or try the new `pull_request_target` way.

**Comment by felixxm** [comment]
> ... or try the new `pull_request_target` way.

It doesn't work for me, I'm not sure if I want to experiment more :smile:

**Comment by ngnpope** [comment]
That's fair enough... Let us not battle further with the manifold mysteries of CI... 🧙🏻‍♂️

**Comment by ngnpope** [comment]
Ah, looking at `new_contributor_pr.yml` it looks as though we're already using `pull_request_target` there and the implication is that you need that _and_ also need to pass the token - according to [this comment](https://github.com/peter-evans/create-or-update-comment/issues/238#issuecomment-1672346754).

**Comment by felixxm** [comment]
Sure, let's try both :shrug:

**Review by sarahboyce — APPROVED** [review]
🤞

**Pull request merged**
