### PR TITLE
Feature/24364

### PR DESCRIPTION
**Pull request by aethemba**
This PR is intended for ticket #24364 and adds a small piece of documentation.

### CODE REVIEW

**Comment by timgraham** [comment]
I'd suggest to tweak this slightly:
```diff
diff --git a/docs/ref/contrib/staticfiles.txt b/docs/ref/contrib/staticfiles.txt
index b134ccb..140506c 100644
--- a/docs/ref/contrib/staticfiles.txt
+++ b/docs/ref/contrib/staticfiles.txt
@@ -285,6 +285,12 @@ hashed names for all processed files in a file called ``staticfiles.json``.
 This happens once when you run the :djadmin:`collectstatic` management
 command.
 
+Due to the requirement of running :djadmin:`collectstatic`, this storage
+typically shouldn't be used when running tests as ``collectstatic`` isn't run
+as part of the normal test setup. During testing, ensure that the
+:setting:`STATICFILES_STORAGE` setting is set to something else like
+``'django.contrib.staticfiles.storage.StaticFilesStorage'`` (the default).
+
 .. method:: storage.ManifestStaticFilesStorage.file_hash(name, content=None)
 
 The method that is used when creating the hashed name of a file.
@@ -298,15 +304,6 @@ hashing algorithm.
 .. _`url()`: http://www.w3.org/TR/CSS2/syndata.html#uri
 .. _`Cascading Style Sheets`: http://www.w3.org/Style/CSS/
 
-.. warning::
-
-    Using ``ManifestStaticFilesStorage`` requires you to run the :djadmin:`collectstatic` 
-    management command to create the hashed names mapping in the file ``staticfiles.json``. 
-
-    Therefore, ``ManifestStaticFilesStorage`` should not be used when running tests. During testing,
-    make sure that the :setting:`STATICFILES_STORAGE` setting does not refer to
-    ``ManifestStaticFilesStorage``.
-
 CachedStaticFilesStorage
 ------------------------
 ```
Also, see our [patch review checklist](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/submitting-patches/#patch-review-checklist) for the proper commit message format to use. Thanks!

**Comment by aethemba** [comment]
Cool, thanks, I'll update the PR

**Comment by aethemba** [comment]
@timgraham , thanks, I've updated the PR. I'm happy to make more adjustments if things are not in order.

**Comment by timgraham** [comment]
merged in b4d8b16e5109170614ba505e36f60c2ad64dafc2, thanks! (for future reference, please send your PR against master -- we'll backport as necessary from there)

**Pull request closed without merging**
