### PR TITLE
Fixed #26954 -- Prevented ModelAdmin.has_module_permission()=False from blocking access to the app index page.

### PR DESCRIPTION
**Pull request by timgraham**
https://code.djangoproject.com/ticket/26954
I added an additional test to https://github.com/django/django/pull/6999.

### CODE REVIEW

**Comment by timgraham** [comment]
@kezabelle, in case you didn't get my message via Trac, could you review this?

**Comment by kezabelle** [comment]
Hi Tim,
I did catch the Trac message, just hadn't got around to it yet, sorry.
So, if I'm reading the changes correctly, if a every ModelAdmin inside an app label were to return a falsy value, the app index page would return a 404? That invalidates the change in [21603](https://code.djangoproject.com/ticket/21063), but returning a 404 instead of a 403 is certainly preferable to the current situation where one might be raised too eagerly.
On that basis, yeah, LGTM.

**Comment by timgraham** [comment]
Correct, I've updated the description of the test added in that ticket to reflect the new behavior.

**Comment by TriAnMan** [comment]
Sorry, but is there any way to know when this path will be merged in the stable/1.10.x branch?
The 1.10.4 version was out 1-st December but has no this patch inside it. ):

**Comment by charettes** [comment]
@TriAnMan this patch will never be backported 1.10 per our policy. It will be part of the upcoming 1.11 LTS release.

**Comment by TriAnMan** [comment]
@charettes Thanks for clarification.
I've just found https://docs.djangoproject.com/en/dev/internals/release-process/#supported-versions
But I can't clearly figure out from this page that only security and data-loss kind of patches are able to be backported.

**Comment by DylanYoung** [comment]
"Critical bugs fixed on master must also be fixed on the bugfix branch" --> "Major functionality bugs in newly-introduced features."

ModelAdmin.has_module_permission is a newly introduced feature that is essentially broken (as per it's documentation and use-case) by this bug.  Perhaps I misunderstand your policy.

**Comment by timgraham** [comment]
`ModelAdmin.has_module_permission()` is 3 years old (added in Django 1.8). If this bug were fixed during the time in which 1.8 was receiving bug fixes, it may have been backported.

**Comment by DylanYoung** [comment]
@TriAnMan  A work around is to set ModelAdmin.get_model_permissions to return an empty dict, at least in 1.8. Do a grep for the method in Django1.10.contrib.admin to see if it's used anywhere else that may break something.

**Comment by DylanYoung** [comment]
@timgraham  I see now: December 1, 2015 was end of feature fixes. @TriAnMan Footnote 1 on this page: https://www.djangoproject.com/download/#supported-versions

**Pull request merged**
