### PR TITLE
Django is now stable

### PR DESCRIPTION
**Pull request by adamchainz**
I think it's time to promote Django to being listed as Production/Stable on PyPI.

### CODE REVIEW

**Comment by graingert** [comment]
Hold onto your hats, this is going to the top of HN.

**Comment by charettes** [comment]
Stable branches are considered [stable](https://github.com/django/django/blob/stable/1.10.x/setup.py#L56). We keep master as `Development Status :: 2 - Pre-Alpha`.

**Comment by adamchainz** [comment]
Ahhhhhhhhh sorry

**Comment by graingert** [comment]
I suppose, *technically*, Django is sort of in beta until it supports semver in 2.0.0

**Comment by graingert** [comment]
Ah didn't spot the other branches

**Comment by charettes** [comment]
FWIW updating the classifiers is also already documented as a step of [rolling a Django release](https://docs.djangoproject.com/en/dev/internals/howto-release-django/#actually-rolling-the-release).

**Comment by adamchainz** [comment]
Cool, thanks @charettes .

**Pull request closed without merging**
