### PR TITLE
Clear floats with clear rather than overflow.

### PR DESCRIPTION
**Pull request by jpic**
I've been dissecting Django admin's model choice widget changes recently ( https://github.com/jpic/test_input_relation it has a bit of history too because it was initially related to [#24784](https://code.djangoproject.com/ticket/24784) ) and found something a bit weird in the new CSS, which kind of breaks the ability to have a dynamic widget (ie. a javascript menu or autocompletion) in a clean manner (without fixing the flow with custom JS).

Shouldn't we use the .clear class defined in base.css to clear floats instead ?

Isn't .form-row is meant to contain .field-box which have float:left ?

In this case, shouldn't we need .form-row to contain an element that will clear
the floats ?

This would remove the need to hide overflow and enable rich dynamic widgets
(ie. js menus) without hacks.

Let me know what you think.

### CODE REVIEW

**Comment by timgraham** [comment]
Is there a regression in 1.8 such that this change deserves to be backported? The `overflow: hidden;` line you removed has been there since 2008. I am not much of a CSS expert, but I'll try to understand the change if you can explain it a bit more.

**Comment by jpic** [comment]
TBH I've been working around this kind of quirks for ages in autocomplete-light and will probably continue doing so but that doesn't mean we shouldn't try to improve things.

[Documentation about clearing floats](https://developer.mozilla.org/en-US/docs/Web/CSS/float#Clearing_floats) states:

> The simplest way to clear the floats in this example is to add the clear property to the new heading we want to be sure is aligned left
> [...]
> If clearing floats on an element below them is not an option, another approach is to limit the block formatting context of the floats' container.
> [...]
> We can set the overflow property on that P to hidden or auto to cause it to expand to contain them, but not allow them to drop out the bottom of it.

So if there's no clear requirement that we want to prevent a widget (ie. js menu) to drop out the bottom of it, then we should use clear instead of overflow according to MDN. That's why my widget's JS has to do to display right anyway, but it would be great if this was upstreamed, rather than worked around in every js widgets.

I'm not a CSS expert either so please correct me if I'm wrong.

**Comment by amessinger** [comment]
:+1: @jpic.

Clearing floated content is most commonly achieved by restoring the normal flow of elements.

This used to be done by applying the `clear: both` property after a set of floated elements.
Reference: http://www.sitepoint.com/clearing-floats-overview-different-clearfix-methods/#solution-1-the-old-school-way

Nowadays, it is considered best practice to restore the flow through the `:after` pseudo-class of the parent of the floated elements.
Reference: https://css-tricks.com/snippets/css/clear-fix/

My 2 cents ;)

**Comment by jpic** [comment]
As @amessinger explained to me off-line, it is indeed wrong to add the div.clear.

Instead, we should add a clearfix class which is pretty much a standard (every CSS framework provides one) and apply it on the `.form-row`.

Updating my patch

Thanks a lot for your reviews

**Comment by jpic** [comment]
As @amessinger told me, we could just use:

```
.clearfix:after {
    clear: both;
}
```

Which is technically correct, **but** it's not a bad idea to have a version that supports browser quirks, like all CSS framework have, ie.:

- twitter bootstrap provides one: https://github.com/twbs/bootstrap/blob/master/less/mixins/clearfix.less
- zurb foundation provides one: https://github.com/zurb/foundation/blob/1f7efae3658caefc6752c47187bcae14276043fa/doc/pages/utility-classes.html
- blueprint css framework too: https://github.com/joshuaclayton/blueprint-css/blob/9bf9513439d8fbc53814a398f3f9060f42dd4eda/blueprint/src/grid.css#L263

**Comment by timgraham** [comment]
See also comments on 2c3ce26beb254101f12fa69cc341ba9aeae62029.

**Comment by timgraham** [comment]
@mtrythall, wondering if you have any input on this change.

**Comment by jpic** [comment]
I have changed the way autocomplete renders to use the same.pattern than
the calendar widget (append to body and position absolutely) and of course
that works.

So I have been thinking that a perhaps better way to contribute would be to
document how the make rich js widgets that work in the admin that way which
already has been "the django way".

What do you think ?

**Comment by timgraham** [comment]
That's an interesting an idea. I'm not sure we have any documentation targeted at extending the admin in that way, but if you think there's enough content to start a section or a page, it sounds reasonable.

**Comment by jpic** [comment]
Got a bit of backlog but expect another PR soonish it is definitely
something we want to help making django admin themes more compatible

**Comment by timgraham** [comment]
Okay, I'll close this for now then.

**Pull request closed without merging**
