### PR TITLE
Fixed #28710 -- Fixed the Basque DATE_FORMAT string

### PR DESCRIPTION
**Pull request by claudep**
Thanks Eneko Illarramendi for the report and initial patch.

### CODE REVIEW

**Comment by timgraham** [comment]
Please add `with self.subTest(locale=locale):` after the for loop (except on stable/1.11.x where Python 2 support is needed).

**Comment by claudep** [comment]
Don't you mind combining the with conditions?
`with self.subTest(locale=locale), translation.override(locale):`

**Comment by timgraham** [comment]
I tried that locally but it didn't seem to work.

**Comment by claudep** [comment]
Weird, it works fine on my system (Python 3.5). What error do you get?

**Comment by timgraham** [comment]
I guess I had made a mistake earlier, seems to work now.

**Pull request closed without merging**
