### PR TITLE
Fixed #25434 -- Documented HttpRequest.site and created a section for middleware attributes.

### PR DESCRIPTION
**Pull request by timgraham**
https://code.djangoproject.com/ticket/25434

### CODE REVIEW

**Comment by timgraham** [comment]
buildbot, test on windows.

**Comment by kezabelle** [comment]
As this is very much implementation detailing which an unfamiliar user could happen upon, I think it would be nicer to restore the calls to action which were previously there which gave the reader an idea about where to go next (eg: `see :doc:'/topics/auth/index'`, `see the :doc:'session documentation </topics/http/sessions>'`, + for `contrib.sites`)
What do you think?

**Comment by timgraham** [comment]
The same links are present in the middleware documentation that's linked from the class names so I thought it was slightly redundant to repeat it, and I thought it was a bit unhelpful to link to the entire contrib document and have to figure out where to go from there.

**Comment by ngnpope** [comment]
@timgraham: Thanks for picking this one up - I've had very little time recently.

Sorry for the late reply. I think that there could be another "Attributes set by developer" section into which ``urlconf`` and ``current_app`` would be placed. These are attributes that require the developer to set them explicitly which merits a separate section. This does leave ``resolver_match`` as a bit of an odd ball though unless there are any other currently undocumented attributes that should be?

**Comment by timgraham** [comment]
Good idea. Done in https://github.com/django/django/pull/5490, but I don't understand what you mean about resolver_match being an oddball?

**Comment by ngnpope** [comment]
Sorry - I meant that it will be left on its own. It is something set by Django once the URL has been matched, not by middleware or an application.

**Pull request merged**
