### PR TITLE
Fixed #25579 -- Added ArrayField.get_prep_value().

### PR DESCRIPTION
**Pull request by freshquiz**
Related [ticket](https://code.djangoproject.com/ticket/25579).

### CODE REVIEW

**Comment by timgraham** [comment]
I think it would be better if we could finish https://github.com/django/django/pull/6131 first so we can reuse the test classes there.

**Comment by timgraham** [comment]
I've merged the other fix in 2495023a4cae28f494d0a6172abfac3a47a0b816. Could you try to rebase your branch and use classes introduced there? I left a comment on the ticket about an example query that could serve as a regression test. Thanks! p.s. You can squash commits and follow the commit message guidelines as described on the [patch review checklist](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/submitting-patches/#patch-review-checklist).

**Comment by freshquiz** [comment]
Yep, I shall do all that shortly.

I appreciate your guidance and patience, as I'm sure other Django dev newbies do too.

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
merged in e7e5d9b338cabaafc61b7a0c55ff395b533d8c9e, thanks!

**Pull request closed without merging**
