### PR TITLE
Added missing lang attributes to html element in docs.

### PR DESCRIPTION
**Pull request by JohananOppongAmoateng**
#### Trac ticket number
N / A

#### Branch description
Provide a concise overview of the issue or rationale behind the proposed changes.

#### Checklist
- [ ] This PR targets the `main` branch. 
- [ ] The commit message is written in past tense, mentions the ticket number, and ends with a period.
- [ ] I have checked the "Has patch" ticket flag in the Trac system.
- [ ] I have added or updated relevant tests.
- [ ] I have added or updated relevant docs, including release notes if applicable.
- [ ] I have attached screenshots in both light and dark modes for any UI changes.

### CODE REVIEW

**Comment by sarahboyce** [comment]
Thank you for this @JohananOppongAmoateng :star: 
I think there are two more places we might want to add this in:
```diff
--- a/docs/topics/http/views.txt
+++ b/docs/topics/http/views.txt
@@ -23,7 +23,7 @@ Here's a view that returns the current date and time, as an HTML document::
 
     def current_datetime(request):
         now = datetime.datetime.now()
-        html = "<html><body>It is now %s.</body></html>" % now
+        html = '<html lang="en"><body>It is now %s.</body></html>' % now
         return HttpResponse(html)
 
 Let's step through this code one line at a time:
@@ -225,7 +225,7 @@ Here's an example of an async view::
 
     async def current_datetime(request):
         now = datetime.datetime.now()
-        html = "<html><body>It is now %s.</body></html>" % now
+        html = '<html lang="en"><body>It is now %s.</body></html>' % now
         return HttpResponse(html)
 
 You can read more about Django's async support, and how to best use async
```
Can you confirm whether these should be left out and if not, add these in?

**Comment by JohananOppongAmoateng** [comment]
Let me add it

**Comment by sarahboyce** [comment]
I think this looks good - @thibaudcolas can you confirm you're happy?

**Review by thibaudcolas — APPROVED** [review]
Spot on! :)

**Comment by JohananOppongAmoateng** [comment]
Hello 👋 @thibaudcolas  asking out of curiosity is there changes that needs to be done or it okay.

**Pull request merged**
