### PR TITLE
Fixed #29038 -- Removed closing slash from HTML void tags.

### PR DESCRIPTION
**Pull request by jdufresne**
https://code.djangoproject.com/ticket/29038

### CODE REVIEW

**Comment by pope1ni** [comment]
I am +1 on this as frankly XHTML has been dead for a long time and I think that XHTML5 is wishful thinking.

This should be mentioned in the backwards incompatibility section of the release notes as this will break things for anyone using XHTML with Django (assuming there is anyone). The changes in templates are easily reversed by overriding them in a project, but the modifications to tags generated in Python code are not.

**Comment by jdufresne** [comment]
I'm happy to add to the backwards incompatible section. However, Django is already using HTML5 features that are incompatible with XHTML. For example boolean attributes for `checked` and `disabled`. Understanding that, do you think a backwards incompatibility note is still necessary?

**Comment by jdufresne** [comment]
Added a not backwards incompatible note. Let me know what you think of the wording. I can easily tweak it if necessary. Thanks.

**Comment by pope1ni** [comment]
> For example boolean attributes for checked and disabled.

Fair point. I grepped the documentation, here are the most relevant bits:

```
docs/ref/forms/api.txt-* The output uses HTML5 syntax, targeting ``<!DOCTYPE html>``. For example,
docs/ref/forms/api.txt:  it uses boolean attributes such as ``checked`` rather than the XHTML style
docs/ref/forms/api.txt-  of ``checked='checked'``.

docs/ref/forms/widgets.txt-The HTML generated by the built-in widgets uses HTML5 syntax, targeting
docs/ref/forms/widgets.txt-``<!DOCTYPE html>``. For example, it uses boolean attributes such as ``checked``
docs/ref/forms/widgets.txt:rather than the XHTML style of ``checked='checked'``.

docs/releases/1.11.txt-* The ``checked`` and ``selected`` attribute rendered by form widgets now uses
docs/releases/1.11.txt:  HTML5 boolean syntax rather than XHTML's ``checked='checked'`` and
docs/releases/1.11.txt-  ``selected='selected'``.

docs/releases/2.0.txt-* The ``DEFAULT_CONTENT_TYPE`` setting is deprecated. It doesn't interact well
docs/releases/2.0.txt-  well with third-party apps and is obsolete since HTML5 has mostly superseded
docs/releases/2.0.txt:  XHTML.
```

Based on previous release notes, it feels right to at least make a mention of the incompatibility - what you've added looks fine.

**Pull request merged**
