### PR TITLE
Fix help text when there are no password validators

### PR DESCRIPTION
**Pull request by acatton**
This avoids having an empty list which is invalid HTML 4.
<http://www.w3.org/TR/html4/struct/lists.html#h-10.2>

### CODE REVIEW

**Comment by timgraham** [comment]
Could you add a regression test?

**Comment by acatton** [comment]
@timgraham sure. Here you go.

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by timgraham** [comment]
merged in 53ccffdb8c8e47a4d4304df453d8c79a9be295ab, thanks!

**Pull request closed without merging**
