### PR TITLE
Fixed #11929 -- Make dump data output YAML in a sane order.

### PR DESCRIPTION
**Pull request by AeroNotix**
Thanks to sampablokuper for the report.

### CODE REVIEW

**Comment by kxxoling** [comment]
Is this rejected? I think this is really a good improvement!

**Comment by timgraham** [comment]
I guess the test failures weren't ever fixed. Feel free to update the patch if you're able.

**Comment by AeroNotix** [comment]
The tests that were suggested are a bit overly tied to the exact strings output, which seems a bit odd to me. The other test failures were for a similar reason.

**Comment by kxxoling** [comment]
I've just upgrade to 1.8.8 and didn't find anything in this patch.
I would like to try to fix this after fixing my current work.

**Pull request closed without merging**
