### PR TITLE
Refs #34534 -- Reduced constraint operations with Meta.constraints when optimizing migrations.

### PR DESCRIPTION
**Pull request by bcail**

### CODE REVIEW

**Comment by nessita** [comment]
Hi, thank you for your contribution! In order for this PR to be listed as "needing review" in the [Django Development Dashboard](https://code.djangoproject.com/query?status=!closed&needs_better_patch=0&needs_tests=0&needs_docs=0&has_patch=1&stage=Accepted&desc=1&order=changetime), please remember to set the proper Trac flags in the ticket as described in the [patch checklist](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/submitting-patches/#patch-review-checklist) when this is ready for review.

**Comment by bcail** [comment]
@nessita Thanks, I updated the flag.

**Comment by felixxm** [comment]
@bcail Thanks :+1: I pushed tiny edits in the #17840.

Could you work on your personal (not company) fork in the future? This would allow me to make minor edits before merging.

**Comment by felixxm** [comment]
Merged in 8b7ddd1b621e1396cf87c08faf11937732f09dcd.

**Pull request closed without merging**
