### PR TITLE
Updated GEOS/GDAL links in docs and comments.

### PR DESCRIPTION
**Pull request by Debakel**
The official GEOS web site is now ​https://libgeos.org

### CODE REVIEW

**Comment by felixxm** [comment]
@Debakel Thanks for this patch :+1: Can you also update other links to: https://www.osgeo.org/, https://trac.osgeo.org, https://lists.osgeo.org/ in docs and comments?

**Comment by Debakel** [comment]
@felixxm Sure. I checked all other links matching \*osgeo.org/\*. The remaining ones are still up to date.

**Comment by felixxm** [comment]
@Debakel Thanks :+1: I found one more:
- `django/contrib/gis/geos/libgeos.py`: `# https://geos.osgeo.org/doxygen/geos__c_8h_source.html` this should be probably `https://libgeos.org/doxygen/geos__c_8h_source.html`.

**Comment by Debakel** [comment]
@felixxm Thanks, I updated this one as well.

**Comment by felixxm** [comment]
@Debakel Thanks :+1: Welcome aboard :boat:

**Pull request merged**
