### PR TITLE
Changed the order to highlight the success of the action after starting the development server

### PR DESCRIPTION
**Pull request by avallbona**
Changed the order to highlight the success of the action after starting the development server

This work is part of effort done in the Sprints in DjangoCon Europe in Vigo with Daniele Procida @evildmp

Task picked from the task list in https://docs.google.com/spreadsheets/d/16UTGwtAoOwznc46cszbwAHU9xbukXnnpwG-faE94Rw8/edit?gid=0#gid=0

### CODE REVIEW

**Review by evildmp — APPROVED** [review]

**Review by nessita — COMMENTED** [review]
Thank you, I agree this is a valuable swap! :star2:

I would just suggest that the bold is removed to not introduce a translation change. Could you please revert that?

**Comment by avallbona** [comment]
> Thank you, I agree this is a valuable swap! 🌟
> 
> I would just suggest that the bold is removed to not introduce a translation change. Could you please revert that?

@nessita Done it. Thanks.

**Comment by nessita** [comment]
> > Thank you, I agree this is a valuable swap! 🌟
> > I would just suggest that the bold is removed to not introduce a translation change. Could you please revert that?
> 
> @nessita Done it. Thanks.

Thanks, though it seems that you restored the previously deleted paragraph so now we have the exact same paragraph in two places! Could you please remove the original one that was moved to earlier in the text?

**Comment by avallbona** [comment]
> > > Thank you, I agree this is a valuable swap! 🌟
> > > I would just suggest that the bold is removed to not introduce a translation change. Could you please revert that?
> > 
> > 
> > @nessita Done it. Thanks.
> 
> Thanks, though it seems that you restored the previously deleted paragraph so now we have the exact same paragraph in two places! Could you please remove the original one that was moved to earlier in the text?

Ups, sorry. Fixed in 4cd7d4d4550a46a192343b2c973393a534f4a005

**Review by nessita — APPROVED** [review]
Thank you!

**Pull request merged**
