### PR TITLE
#35109  showmigrations leafs only

### PR DESCRIPTION
**Pull request by breid1313**
It would be nice to be able to have `showmigrations` only display the most recent migration for a given app. Currently, the functionality is to list all migrations, which can be a long list for more mature apps. I have found at times that I am really only looking for the most recent migration so that I can unapply it or find the number of the last migration so I can squash through that point.

Proposed enhancement: add an argument to `showmigrations` that will only show the leaf nodes for the given app(s) if provided.

It would great to apply this to stable branches post-3.2.x, and furthermore to `main`. I'm not sure of the best way to handle that, but would appreciate guidance from the maintainers if we like the change.

### CODE REVIEW

**Comment by felixxm** [comment]
Django 3.2 is in extended support, it no longer receives new features.

**Comment by breid1313** [comment]
> Django 3.2 is in extended support, it no longer receives new features.

@felixxm thanks. Can I contribute this to a subsequent version? There is no functionality like this in the current version. I would like to introduce this into the earliest version possible and ideally pull forward into the more current releases.

**Comment by felixxm** [comment]
> > Django 3.2 is in extended support, it no longer receives new features.
> 
> @felixxm thanks. Can I contribute this to a subsequent version? There is no functionality like this in the current version. I would like to introduce this into the earliest version possible and ideally pull forward into the more current releases.

We don't backport new features, so this could be implemented in Django 5.1+ (but I'm not convinced that we want to add it to Django).

**Comment by breid1313** [comment]
> > > Django 3.2 is in extended support, it no longer receives new features.
> > 
> > 
> > @felixxm thanks. Can I contribute this to a subsequent version? There is no functionality like this in the current version. I would like to introduce this into the earliest version possible and ideally pull forward into the more current releases.
> 
> We don't backport new features, so this could be implemented in Django 5.1+ (but I'm not convinced that we want to add it to Django).

what's the hesitation on adding to django? my colleagues and I would definitely use this. we currently have a lot of migrations and the output from `showmigrations` is significantly less helpful as a result.

**Comment by felixxm** [comment]
> what's the hesitation on adding to django? my colleagues and I would definitely use this. we currently have a lot of migrations and the output from `showmigrations` is significantly less helpful as a result.

We cannot add every possible option just because someone will use it. That kind of options should rather be implemented  in user code. If you have thousands of migrations why you cannot use, e.g. `showmigrations --plan | tail` or something similar.

**Comment by breid1313** [comment]
> > what's the hesitation on adding to django? my colleagues and I would definitely use this. we currently have a lot of migrations and the output from `showmigrations` is significantly less helpful as a result.
> 
> We cannot add every possible option just because someone will use it. That kind of options should rather be implemented in user code. If you have thousands of migrations why you cannot use, e.g. `showmigrations --plan | tail` or something similar.

that could work, but what about the case where someone has dozens or hundreds of apps? you would then need to `show migrations | tail` each of those apps, right?. I think this provides a nice summary-level view of the state of each app in the database at a glance (when `app_label` is not used).

**Comment by felixxm** [comment]
Do you really have hundreds of apps with thousand of migrations each and you daily introspect the last migrations? If you really do this you can use you own subclass of `showmigrations`. I wouldn't say that it especially useful to check only the last migrations for each app.

**Comment by jduffymclaughlin** [comment]
> Do you really have hundreds of apps with thousand of migrations each and you daily introspect the last migrations? If you really do this you can use you own subclass of `showmigrations`. I wouldn't say that it especially useful to check only the last migrations for each app.

All it really takes is a fews apps at the end of the alphabet with a lot of migrations to flood the terminal enough that the apps before it don't show. I think the essence of this command is to answer the question 'are there unapplied migrations? and if so, which?' and in both Django shops I've worked in, the output stopped being useful to answer that.

**Comment by felixxm** [comment]
> All it really takes is a fews apps at the end of the alphabet with a lot of migrations to flood the terminal enough that the apps before it don't show. I think the essence of this command is to answer the question 'are there unapplied migrations? and if so, which?' and in both Django shops I've worked in, the output stopped being useful to answer that.

You can do this in [many ways](https://forum.djangoproject.com/t/proposal-add-a-flag-to-showmigrations-that-lists-only-unapplied-migrations/24674/5).

**Comment by breid1313** [comment]
I would be in favor of altering this to output the last 2-3 migrations (as suggested in the ticket), if we would be more amenable to that type of change. I dont think that using `showmigrations --plan | tail` or grepping for `[ ]` gives the same high-level view into recent history for each app that printing the last 2-3 migrations would.

**Pull request closed without merging**
