### PR TITLE
Reorganized backends tests.

### PR DESCRIPTION
**Pull request by felixxm**
I reorganized backends specific tests (see https://github.com/django/django/pull/8015#discussion_r100357573, and ticket [23027](https://code.djangoproject.com/ticket/23027)).

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
I rebased from master.

**Comment by felixxm** [comment]
I rebased from master.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
I rebased from master.

**Comment by felixxm** [comment]
I rebased from master.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
I rebased from master.

**Comment by timgraham** [comment]
I worked on this today. Some notable changes:
* I created a `db_utils` test app for testing `django.db.utils` (stuff that's not in `django.db.backends`).
* I moved most of `tests/backends/base/tests.py` (now renamed to `test_base.py`) back to `tests/backends/tests.py` and added a docstring to that file that those tests are unorganized. Those tests are tests all sorts of things unrelated to the base backend, so I think we should just leave them alone for now in order to get this merged.

I'm going to give this a break for now and probably look at it again later this week.

**Comment by felixxm** [comment]
@timgraham Thanks! 🚀

**Pull request merged**
