### PR TITLE
Fixed #34693 -- Add get_by_table_name to ContentTypeManager

### PR DESCRIPTION
**Pull request by rahnama7m**

### CODE REVIEW

**Comment by felixxm** [comment]
@rahnama7m Please stop creating duplicates. The original ticket was closed as "wontfix", so [follow the triaging guidelines with regards to wontfix tickets](https://docs.djangoproject.com/en/stable/internals/contributing/triaging-tickets/#closing-tickets).

Closing per ticket.

**Comment by rahnama7m** [comment]
Is it possible to tell me what is the problem with this feature? @felixxm

**Comment by felixxm** [comment]
https://code.djangoproject.com/ticket/34690#comment:2

**Comment by rahnama7m** [comment]
I think we need some method like `ContentTypeManager.get_by_natural_key` to support getting the `ContentType` object with the title of the table in the database. Suppose that I want to find a specific model with `_meta.db_table` of that model. Isn't it a good feature?

**Comment by felixxm** [comment]
You may need this hook, but most of Django user don't need it. You can start a discussion on the mailing list if you don't agree.

**Comment by charettes** [comment]
> Suppose that I want to find a specific model with _meta.db_table of that model. Isn't it a good feature?

You don't need to hit the database for that nor use contentypes

```python
from django.apps import apps

def get_model_by_db_table(db_table):
    for model in apps.get_models():
        if model._meta.db_table == db_table:
            return model
```

Thing is there is doesn't exist a 1:1 map between models and db_tables; there could be multiple models mapped to the same table. Think of proxy and unmanaged models for example.

**Comment by rahnama7m** [comment]
Thanks for your answer @felixxm  and your codes @charettes.
I tried to help the community, but your words are absolutely correct. I will try to participate again.

**Pull request closed without merging**
