### PR TITLE
Fixed #31354: Properly reconstruct host header in presence of X-Forwarded-* header.

### PR DESCRIPTION
**Pull request by sreehari1997**
## Follow up to #12844 

When I ran the tests locally, I got the following failures (CSRF); it would be great if someone could assist me.
```
FAIL: test_https_good_referer_matches_cookie_domain (csrf_tests.tests.CsrfViewMiddlewareTests)
A POST HTTPS request with a good referer should be accepted from a
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sreehari/opensource/django/django/django/test/utils.py", line 437, in inner
    return func(*args, **kwargs)
  File "/Users/sreehari/opensource/django/django/tests/csrf_tests/tests.py", line 1228, in test_https_good_referer_matches_cookie_domain
    self._test_https_good_referer_matches_cookie_domain()
  File "/Users/sreehari/opensource/django/django/tests/csrf_tests/tests.py", line 790, in _test_https_good_referer_matches_cookie_domain
    self.assertIsNone(response)
AssertionError: <HttpResponseForbidden status_code=403, "text/html"> is not None

======================================================================
FAIL: test_https_good_referer_matches_cookie_domain (csrf_tests.tests.CsrfViewMiddlewareUseSessionsTests)
A POST HTTPS request with a good referer should be accepted from a
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sreehari/opensource/django/django/django/test/utils.py", line 437, in inner
    return func(*args, **kwargs)
  File "/Users/sreehari/opensource/django/django/tests/csrf_tests/tests.py", line 1359, in test_https_good_referer_matches_cookie_domain
    self._test_https_good_referer_matches_cookie_domain()
  File "/Users/sreehari/opensource/django/django/tests/csrf_tests/tests.py", line 790, in _test_https_good_referer_matches_cookie_domain
    self.assertIsNone(response)
AssertionError: <HttpResponseForbidden status_code=403, "text/html"> is not None

----------------------------------------------------------------------
Ran 15252 tests in 537.241s

FAILED (failures=2, skipped=1193, expected failures=4)
```

### CODE REVIEW

**Comment by tjni** [comment]
I was curious about what these headers do, and looked up X-Forwarded-Host on MDN: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host.

I noticed that X-Forwarded-Host is not defined to have a comma-separated value, so I do not think this should support extracting the first from multiple values.

On the other hand, if [X-Forwarded-For](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For#syntax) or the [Fowarded](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded#syntax) headers are used, then a list would be allowed.

Are the proxy servers accidentally violating the de-facto definition of X-Forwarded-Host? From the definition given in the MDN documentation, it doesn't seem to make sense for more than one host to be provided in this header, since it should only be the Host header from the original request.

**Comment by joachimBurket** [comment]
I also found it weird because, as you said, it wasn't specified on MDN.

My Django app is running on an Openshift cluster, which is behind a Citrix ADC LoadBalancer. 
I configured the Citrix LoadBalancer to add the X-Forwarded-Host header, which it does (`website1.domain.com` in my example), but then it seems that Openshift's load balancer is also modifying the Header. 

I couldn't find a lot of other cases where multiple Hosts are filled in this header, but I found those links talking about it:
* https://github.com/zmartzone/lua-resty-openidc/issues/128
* https://github.com/prerender/prerender-node/issues/184

**Comment by joachimBurket** [comment]
I may have found something in the [Openshift documentation](https://docs.openshift.com/container-platform/4.8/networking/ingress-operator.html#nw-ingress-controller-configuration-parameters_configuring-ingress) (Under the `httpHeaders` parameter). 
The IngressController seems to be configured to Append value by default in the X-Forwarded Headers. I will try to set it to `IfNone` and see what happens

**Comment by tjni** [comment]
You're a wizard to find those examples. I'm no expert, but I'd conclude that support to handle multiple X-Forwarded-Host headers would be needed in the wild, even if it's not described in MDN. After all, these headers are non-standard.

For context, in [proxy_util.c](https://github.com/apache/httpd/blob/5338e45798e2be5296b57c5b31c0de763f2d8962/modules/proxy/proxy_util.c#L4039) of mod_proxy, the code reads:

    /* Add X-Forwarded-Host: so that upstream knows what the
     * original request hostname was.
     */
    if ((buf = apr_table_get(r->headers_in, "Host"))) {
        apr_table_mergen(r->headers_in, "X-Forwarded-Host", buf);
    }

where `apr_table_mergen` adds to any existing table entry the new value separated by a comma and a space.

**Comment by felixxm** [comment]
Closing due to inactivity.

**Pull request closed without merging**
