### PR TITLE
Fixed #27009 -- Made update_session_auth_hash() rotate the session key.

### PR DESCRIPTION
**Pull request by timgraham**
https://code.djangoproject.com/ticket/27009

### CODE REVIEW

**Comment by timgraham** [comment]
@evildmp, are the documentation changes clear to you?

**Comment by evildmp** [comment]
@timgraham Yes, perfect.

**Comment by timgraham** [comment]
@apollo13, @shaib -- is this what you had in mind?

**Comment by apollo13** [comment]
Looks good, did you manually test that with two browser windows and database based sessions?

**Comment by timgraham** [comment]
Yes :-)

**Comment by apollo13** [comment]
K, well I cannot see anything wrong with the patch -- as long as we cycle the key before updating the hash (which you do), we should be fine.

**Comment by shaib** [comment]
LGTM2.

**Pull request merged**
