### PR TITLE
Refs #25367 -- Simplified OrderBy and Lookup by using Case() instead of RawSQL() on Oracle.

### PR DESCRIPTION
**Pull request by felixxm**
Follow up to efa1908f662c19038a944129c81462485c4a9fe8.

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by charettes** [comment]
Thanks for the follow up @felixxm!

**Pull request merged**
