### PR TITLE
Fixed #29116 -- Fixed OpenLayersWidget deserialization ignoring the widget map's SRID.

### PR DESCRIPTION
**Pull request by claudep**
https://code.djangoproject.com/ticket/29116

### CODE REVIEW

**Comment by sir-sigurd** [comment]
I think it also could be fixed by explicitly setting 'crs' on GeoJSON in MapWidget.

**Comment by claudep** [comment]
Yes, that could be an alternative. The GeoJSON standard is discouraging the use of other crs than WGS84, but it might be acceptable as a mean of communication between client and server in Django forms.

**Comment by sir-sigurd** [comment]
BTW do we have to use GeoJSON in OpenLayersWidget, rather than WKT?

**Comment by carltongibson** [comment]
OK. Short of any other input I think we should probably take this.

**Comment by timgraham** [comment]
Claude, do you want to move forward with this or investigate the alternative? In either case, we'll need a release note for the next 2.0.x.

**Comment by claudep** [comment]
Sorry, I do not plan other alternatives for now, but I can understand if anyone wants to try another approach.

**Comment by timgraham** [comment]
Sergey, do you want to try the approach you suggested or move forward with this?

**Comment by sir-sigurd** [comment]
> Sergey, do you want to try the approach you suggested or move forward with this?

I'll try to open PR using my approach next week.

**Comment by timgraham** [comment]
Sergey, is it possible you could complete a patch for the April 2 bug fix release?

**Comment by sir-sigurd** [comment]
@timgraham, sorry for delay but I'm unable to provide it.

**Pull request merged**
