### PR TITLE
Added assertion for the results of migrating an integer pk to SmallAutoField.

### PR DESCRIPTION
**Pull request by timgraham**
Follow up to 7ca42974ee087a82b6f7f6874ca2b25e42a9a584 which did the same for similar tests.

### CODE REVIEW

**Review by felixxm — APPROVED** [review]
@timgraham Thanks :+1:

**Review by sarahboyce — APPROVED** [review]
Thank you!

**Comment by yun520-1** [comment]
The assertion addition is a useful regression guard for the `SmallAutoField` migration path, but the test title says it all: this is testing that an *already-broken* state raises, not that the migration succeeds.

What the test does not cover:
1. Migrating a *large* integer PK table (>10M rows) where `SmallAutoField` overflow would silently truncate.
2. SQLite `ALTER TABLE` path vs PostgreSQL/MySQL — the bug that prompted the original `7ca42974` only manifested on backends that enforce `SMALLINT` bounds strictly.
3. The reverse migration `SmallAutoField -> AutoField` where data loss is silent.

For a discriminator-style audit: this test is **assertion-as-substitute-for-behavioral-fix** — it documents the failure mode but does not extend the migration runtime to prevent reaching the failure state.

**Comment by yun520-1** [comment]
The assertion addition is a useful regression guard for the `SmallAutoField` migration path, but the test title says it all: this is testing that an *already-broken* state raises, not that the migration succeeds.

What the test does not cover:
1. Migrating a *large* integer PK table (>10M rows) where `SmallAutoField` overflow would silently truncate.
2. SQLite `ALTER TABLE` path vs PostgreSQL/MySQL — the bug that prompted the original `7ca42974` only manifested on backends that enforce `SMALLINT` bounds strictly.
3. The reverse migration `SmallAutoField -> AutoField` where data loss is silent.

For a discriminator-style audit: this test is **assertion-as-substitute-for-behavioral-fix** — it documents the failure mode but does not extend the migration runtime to prevent reaching the failure state.

**Pull request merged**
