### PR TITLE
Remove colon

### PR DESCRIPTION
**Pull request by ovalseven8**
This colon is wrong here

### CODE REVIEW

**Comment by charettes** [comment]
Hey @ovalseven8, thanks for your report!

Translations are managed on [Transifex](https://www.transifex.com/projects/p/django/) rather than through GitHub. See [Localizing Django](https://docs.djangoproject.com/en/dev/internals/contributing/localizing/#translations) for details.

**Comment by ovalseven8** [comment]
@charettes I am not registered there. Could you change that for me, please? :smile:

**Comment by charettes** [comment]
@ovalseven8 I'm afraid not as I don't speak German myself. Teams on transifex are composed of native speakers which will be able to determine whether or not the adjustment is required which I'm not qualified to do.

**Comment by ovalseven8** [comment]
If you compare it with the original English sentence, then you'll find out the colon is wrong there. :smile: But nevermind, perhaps it will get corrected in future sometime.

**Comment by apollo13** [comment]
I changed it on transifex.

**Pull request closed without merging**
