### PR TITLE
Fixed #34784 -- Adjusted SHORT_DATE_FORMAT in various French variants.

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
@charettes Does this also need an `fr_CA` variant? I read that the official way in Canada is  to use yyyy-mm-dd to avoid the dd/mm - mm/dd confusion. Is it right?

**Comment by charettes** [comment]
@claudep thanks for the ping!

When inputing a date in numerical form only the yyyy-mm-dd and yyyymmdd format is effectively used so I think a `fr_CA` variant is required

- https://vitrinelinguistique.oqlf.gouv.qc.ca/21640/la-typographie/nombres/ecriture-des-dates
- https://en.wikipedia.org/wiki/Date_and_time_notation_in_Canada#French

**Comment by claudep** [comment]
@charettes Do you want to suggest a fr_CA file?

**Comment by charettes** [comment]
Submitted the `fr_CA` variant to @claudep's repository based on the following sources

- https://www.btb.termiumplus.gc.ca/tpv2guides/guides/clefsfp/index-fra.html?lang=fra&lettr=indx_catlog_d&page=9lcOojjUrxt8.html
- https://vitrinelinguistique.oqlf.gouv.qc.ca/21241/la-typographie/nombres/ecriture-des-dates-et-des-heures-dans-certains-contextes-techniques
- https://en.wikipedia.org/wiki/Date_and_time_notation_in_Canada
- https://metacpan.org/dist/DateTime-Locale/view/lib/DateTime/Locale/fr_CA.pod

This made we wonder if we wanted to include the sources in format file itself.

**Comment by claudep** [comment]
> This made we wonder if we wanted to include the sources in format file itself.

Why not, albeit it'd also add some workload to keep the URLs updated through time. Or else add them to commit message. @felixxm, any opinion on this?

**Comment by felixxm** [comment]
> > This made we wonder if we wanted to include the sources in format file itself.
> 
> Why not, albeit it'd also add some workload to keep the URLs updated through time. Or else add them to commit message. @felixxm, any opinion on this?

Formats are rarely changed, so I'd add them to the commit message.

**Comment by felixxm** [comment]
Thanks both :+1:

**Pull request merged**
