### PR TITLE
Refs #35339 -- Fixed source expressions in GeoAggregate on Oracle.

### PR DESCRIPTION
**Pull request by felixxm**
Regression in 42b567ab4c5bfb1bbd3e629b1079271c5ae44ea0.

### CODE REVIEW

**Review by charettes — APPROVED** [review]
So much for a flawed rule of thumb 😅 Completely forgot about `GeoAggregate`.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
Check out [logs](https://djangoci.com/job/django-oracle/database=oragis19,label=oracle,python=python3.12/1323/).

**Comment by felixxm** [comment]
> So much for a flawed rule of thumb 😅 Completely forgot about `GeoAggregate`.

me too :see_no_evil:

**Review by nessita — APPROVED** [review]
Looks good, thank you for the quick fix!

**Pull request merged**
