### PR TITLE
Refs #33173 -- Doc'd Python 3.11 compatibility in Django 4.1.x.

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Review by adamchainz — APPROVED** [review]
🤘

**Review by hramezani — APPROVED** [review]

**Review by pauloxnet — APPROVED** [review]

**Comment by felixxm** [comment]
Thanks for checking :+1:

**Comment by noamcohen97** [comment]
When will 4.1.3 be released?

**Comment by shangxiao** [comment]
> When will 4.1.3 be released?

November 1, it says it in the diff 😁

**Pull request merged**
