### PR TITLE
Fix repeating 'Add' image

### PR DESCRIPTION
**Pull request by martin-marty**
Pseudo attributes added to selectors, prevents repeating *+* in button

### CODE REVIEW

**Comment by felixxm** [comment]
@martin-marty Thanks :+1: Can you provide a sample project? I'm not sure how you're getting multiple icons :thinking:

**Comment by martin-marty** [comment]
Hi @felixxm - I can try to get you one up this week when I'm not so busy with work, if you create a new project, setup admin with users, fire up the server and add a user, go back and the background repeat property is in effect (due to the pseudo selectors) and you get the + repeated. Let me know if you find a chance to reproduce this otherwise I'll create a sample..

**Comment by martin-marty** [comment]
Hi again @felixxm - upon further investigation, the culprit is https://darkreader.org/ - when this extension is enabled you get the following:
image

**Comment by felixxm** [comment]
@martin-marty Thanks for details :+1: It's not an issue in admin per se, but rather an issue in the `darkreader` wrapper. Also, we're working on switch button for dark mode (see #15843) in the admin so you won't need it anymore.

**Comment by evanhobbs1988** [comment]
Sounds fine to me

**Pull request closed without merging**
