### PR TITLE
Clarified a few things in the Intro tutorial

### PR DESCRIPTION
**Pull request by swright573**
I suggest these changes to the intro tutorial.

tutorial01.txt
The location of the root URLconf isn't magic but as a beginner, it can seem so. Added a note about how Django knows where it is and that familiarity with settings will be valuable throughout the tutorial.

tutorial02.txt
Modified the direction to change timezone to local to state Django's recommendation is to leave it as the default UTC but you can change it if you wish. Later reminded that if the time a Poll record was created seems wrong, it might be because timezone was left at the default.

tutorial04.txt
In the section Amend URLconf, Django raises an error when attempting to restart the app if the change is saved. Added a note that this is ok and will be rectified once the change in Amend Views is saved.

### CODE REVIEW

**Comment by swright573** [comment]
I have no idea why this check failed ... "pull-requests-windows/database=sqlite3,label=windows,python=Python39check". I didn't touch anything in that area of the file tutorial02.txt.

**Comment by smithdc1** [comment]
Hi @swright573 -- thanks for the interest here and working on this. 👍

My view is that most of these changes are one of personal style (for example adding _next_ to line 718). We generally avoid these kind of changes as any change causes additional work for the translators, and there are _alot_ of supported languages. See https://www.transifex.com/django/django/

If there is anything truly "wrong" or new helpful clarifications then I'd be supportive of those changes. The last call out on the error could be worth thinking about, for example. I've not reviewed in detail, but it seems like a nice addition at first glance. 

I think it would be helpful if you could focus this PR on the new additions and any true corrections. It will drastically increase the likelihood of your proposals being accepted. 

Don't worry about the failing aws test one of the fellows is looking at fixing this. 

Thanks again.

**Comment by swright573** [comment]
Hello smithdc1 ... Thanks for your feedback. Regarding the translations, I see your point.

I will leave the "error" addition in the PR to see how it goes.

I would like to argue a little bit with you about what is "personal style" versus additional clarity for someone new to Django. I'll hold off on removing/revising these until I get your feedback.

1. Re the timezone-related changes ... The current tutorial suggests timezone be changed to local yet [elsewhere](https://docs.djangoproject.com/en/3.2/topics/i18n/timezones/) in the Django documentation it suggests it is good practice to use UTC. Why suggest something to someone new to Django that is not considered good practice? Rather than my explanation about the option of local/UTC, what do you think about just removing all references to timezone and let it default to UTC? If someone notices the time is "different" they will have to figure it out themselves (and learn something in the process :-).

2. Re the location of the root URLconf ... This probably seems obvious to you as an experienced Django developer but to a beginner, it is not. A hint can give someone a sense of how Django works (e.g. settings.py is VERY IMPORTANT) which will enable them to figure things out for themselves and therefore progress more quickly.

I'm not "married" to any of my other suggestions and will remove them.

Susan

**Comment by smithdc1** [comment]
Hi Susan,

> experienced Django developer

That's very kind of you but I consider myself very much a beginner. 🙂

I think the changes you've presented here are nice additions. 

For now can I ask you to wrap the lines at 79 chars. There's also one line which seems to have additional white space in it. Then I think we should put this on a mergers review list.

**Comment by swright573** [comment]
I think it is ready to go. I don't see any unintended white space.

**Comment by smithdc1** [comment]
@swright573 did you mean to chop all of the timezone docs in the latest commit?

**Comment by swright573** [comment]
I did. I had suggested to you it was a bad idea to direct people to set timezone to local when Django docs elsewhere recommend leaving at the default UTC and therefore those directions should be dropped from the tutorial.  I understood from your response that you agreed. If not, I can add them back in. 

Susan

**Comment by smithdc1** [comment]
Hi Susan,

Appologies for taking some time to get back to this. 

I agree it seems odd to recomend folk to change it when elsewhere we say the sane defauly is UTC. However, I quite liked the pieces you added to point folk at the timezone docs. (_It's UTC, that's best practice, but if you want to change it, see here..._)

**Comment by swright573** [comment]
David ... I've added back the bits that you described as _It's UTC, that's best practice, but if you want to change it, see here..._. Let me know if there is anything else.

**Review by carltongibson — COMMENTED** [review]
Hi. Thanks for the suggestions here. 

I'm going to say, no — 

We try and follow the [Diátaxis framework](https://diataxis.fr) as much as we can, and these kind of **explanatory** asides are not appropriate for the **tutorial** context that we're in here. 

See specifically the [Offer only minimum, necessary, explanation](https://diataxis.fr/tutorials/#offer-only-minimum-necessary-explanation) section of the guide to tutorials there. 

Thanks again.

**Pull request closed without merging**
