### PR TITLE
Refs #35074 -- Simplified adding spatial indexes on MySQL and Oracle.

### PR DESCRIPTION
**Pull request by felixxm**
This uses `deferred_sql` and `_field_indexes_sql()` instead of custom hooks on MySQL and Oracle. It's a preparation for ticket-35074.

### CODE REVIEW

**Comment by felixxm** [comment]
Unfortunately, we cannot do the same for `SpatiaLite` due to the way how table remake works.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by nessita** [comment]
Thank you @felixxm for this work!

@smithdc1 @claudep Is this something that (any of) you could help me test?

/remind me to re-review this in 20 days

**Comment by claudep** [comment]
Sorry, I'm out of the game for anything related to Oracle (or any other proprietary software).

**Review by sarahboyce — APPROVED** [review]
This looks good thank you

**Pull request merged**
