### PR TITLE
Fixed nondeterministic ordering test failure in model_forms.

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by charettes** [comment]
What about using `Category.objects.order_by('slug')` at line 1942 instead?

**Comment by felixxm** [comment]
Good idea. Thanks.

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Comment by timgraham** [comment]
I'm not sure what original fix you proposed was, but my inclination would be to use `self.assertCountEqual` in places where order doesn't matter. Either approach is okay, I guess, but this seems to make the test a bit simpler, IMO.

**Comment by felixxm** [comment]
I used `sorted()` in the first version.

**Pull request merged**
