### PR TITLE
Fixed #25981 Updated ForeignKey.on_delete depreciation warning message

### PR DESCRIPTION
**Pull request by Cheglader**

### CODE REVIEW

**Comment by timgraham** [comment]
merged in a856555df2a1b4ddad8bf21243de0bcbcc12fb20, thanks!

**Comment by timgraham** [comment]
I'm not sure that anyone considered an implementation that wouldn't require fixing them.

**Comment by JsseL** [comment]
Well, I'm tempted to consider it, if I don't value the benefit of fixing them 😄, but as long as I don't understand the benefits, I can't determine the value.

So if I have an app with `0001_init_migration.py`, which doesn't have the `on_delete` specified. Then:

1. Upgrade Django to 2.X
2. add the `on_delete` definitions to my model fields and make another migration `0002_add_on_delete_defs.py`.

What do I benefit from fixing the `0001_init_migration.py`? Is it just that, if someone decides to run the application after running only the first migration (but still using the latest Django 2 compatible version of it)?

**Comment by timgraham** [comment]
Django will crash if it needs to be fixed. Next time, please use [TicketClosingReasons/UseSupportChannels](https://code.djangoproject.com/wiki/TicketClosingReasons/UseSupportChannels) for usage questions.

**Comment by JsseL** [comment]
🤦‍♂️ Sorry to bother. At least learned something about the channels. Thanks and sorry. 👍

**Pull request closed without merging**
