### PR TITLE
Fixed trac #33589 - Incomplete string escaping or encoding

### PR DESCRIPTION
**Pull request by shriekdj**
This replaces only the first occurrence of "//", "/r", "/n", "/t" and "'",
So We Should Use regex for replacing all occurrence.
- Used regex for easy updating.

### CODE REVIEW

**Comment by shriekdj** [comment]
hello django team,
this is my first contribution, If any correction please inform me

**Comment by jacobtylerwalls** [comment]
Hi @shriekdj all behavior changes need an [accepted ticket](https://code.djangoproject.com/newticket). Could you please fill one out with a short statement of the problem?

**Comment by shriekdj** [comment]
ok i will try to create an ticket for it also @jacobtylerwalls

**Comment by shriekdj** [comment]
ok updated. the details @jacobtylerwalls .

**Comment by felixxm** [comment]
@shriekdj Thanks for the patch :+1: There is no need to rebase it daily. We need a regression test to make it reviewable, see [comment](https://code.djangoproject.com/ticket/33589#comment:2).

**Comment by felixxm** [comment]
@shriekdj Do you have time to keep working on this?

**Comment by felixxm** [comment]
Closing due to inactivity.

**Pull request closed without merging**
