### PR TITLE
Fixed #29192 -- Corrected docs regarding overriding fields from abstract base classes.

### PR DESCRIPTION
**Pull request by ovalseven8**
The issue https://code.djangoproject.com/ticket/29192 says that it's actually possible to override fields of abstract base classes.

Someone on IRC even said it's possible to remove fields using `field = None`. Is that true/recommended?

The nice thing is that you can now make fields of User required that are not required by default. For example:
```
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    email = models.EmailField(_('email address'), blank=False)
```

### CODE REVIEW

**Comment by ovalseven8** [comment]
#9756 also is about this issue.

**Comment by rfleschenberg** [comment]
The new functionality is intentional accoding to @knbk, https://code.djangoproject.com/ticket/24305 and https://docs.djangoproject.com/en/2.0/releases/1.10/#models. So yes, I think we should explicitly document it :)

**Comment by rfleschenberg** [comment]
Note that this was introduced in 1.10, so the docs update should probably be backported accordingly.

**Comment by ovalseven8** [comment]
Okay, added @rfleschenberg's suggestion.

Please review @timgraham :)

**Pull request merged**
