### PR TITLE
Fixed #30231 -- Fixed FilteredSelectMultiple widget verbose_name usage

### PR DESCRIPTION
**Pull request by TeresaPartidaS**
https://code.djangoproject.com/ticket/30231

I added the JS changes for updateSelectFilter made by Florian Schuler and added a Selenium test to verify the verbose_name was being showed correctly.

### CODE REVIEW

**Review by carltongibson — COMMENTED** [review]
Hi @TeresaPartidaS. Thanks for this. 

Sorry for the slow take-up: you seem to have fallen through the gaps. I can only apologise. 
After all this time, are you still up for finishing this one off? Let me know. If not I can pick it up, and totally understand. 

This looks good. I have rebased on the latest `master` and adjusted the conflicts. 
(I saw you had issues merging changes previously: if you have a local branch, you could `reset` but, it may just be easier to delete that and check out the remote branch fresh again…)

I want to have a think about whether we can re-use one of the existing models/inlines to use for the tests here (as adding a new model slows down the test suite fractionally). We have stacked and tabular inlines already so I'm thinking we should be able to leverage one of them. 

Also, the added tests are only covering the tabular inline case. We need to cover stacked inlines too. (Specifically nothing fails reverting the changes in the `.selectfilterstacked` blocks.)

**Comment by smithdc1** [comment]
@carltongibson, **if** Teresa is not in the market for finishing this off, I'd happy to put my hand up to have a look.

That is, if you are happy with this proposal. If you think it would cost you more time, not less, then please tell me to leave this alone!

**Comment by carltongibson** [comment]
Hi @smithdc1 Great thanks. I don't think it needs much. Mainly the extra test case (and seeing if there's the opportunity for re-use) 👍

**Comment by carltongibson** [comment]
OK, let's finish off in #13436. Thanks for getting this one started @TeresaPartidaS. Sorry again for the delay in following up! 🙏

**Pull request closed without merging**
