### PR TITLE
Fix a few spelling errors

### PR DESCRIPTION
**Pull request by pp**
Related to [#25755](https://code.djangoproject.com/ticket/25755).

The section ["Commonly used terms"](https://docs.djangoproject.com/en/1.9/internals/contributing/writing-documentation/#commonly-used-terms) in the docs also recommends 'website'.

### CODE REVIEW

**Comment by timgraham** [comment]
I think the comma/period inside the quotes are [correct usage for US style](http://www.quickanddirtytips.com/education/grammar/quotation-marks-with-periods-and-commas).

Merged the "website" commit in c8d970a548cb5cbdad80dbb1b5b4e44ff08662b5.

**Comment by pp** [comment]
I agree, you're right. The dot in "*etc.*" is [correct](https://english.stackexchange.com/questions/23022/how-to-deal-with-abbreviations-like-etc-at-the-end-of-parentheses-which-are-c), however.

**Comment by timgraham** [comment]
Can you rebase your branch and maybe do a more extensive search for that. From a quick search, I found at least one other usage:
```
topics/conditional-view-processing.txt:used for all HTTP methods (``POST``, ``PUT``, ``DELETE``, etc).
```

**Comment by timgraham** [comment]
merged in b34ff66e5bae3760273255fa5b2525eb21a5eb63, thanks!

**Pull request closed without merging**
