### PR TITLE
Minor addition to tutorial part 1 docs

### PR DESCRIPTION
**Pull request by asaf-kali**
I think that adding the word "used" to that sentence conveys the idea behind apps better.

### CODE REVIEW

**Comment by smithdc1** [comment]
Thanks for the patch. 👍

**For me, I** read the current version and the proposed change as having the same meaning. 

I'm not sure how translations work but it could be a disproportionate amount of effort for folk to re-translate this sentence into many different languages for what **I see** as a small change.

**Comment by tim-mccurrach** [comment]
> **For me, I** read the current version and the proposed change as having the same meaning.

I think a very slight ambiguity over the phrase "can be" could lead to the current version could being interpreted in two different ways. To really spell out the two interpretations:
 - An app is written in such a way that it can be replicated across multiple projects without having to alter the app for each project it's contained within.
 - An app can be structured in such a way, that the files that make up an app are spread across several projects.
 
Anyone who has even completed a single project in Django would probably quickly realise that the latter interpretation makes no sense at all, and so there is definitely an argument that context/common sense implies the first interpretation only. Having said that, this is the first page of the beginners tutorial - and maybe we should be more careful with our language to avoid confusion. Clarity is usually a good thing.
 
 > I'm not sure how translations work but it could be a disproportionate amount of effort for folk to re-translate this sentence into many different languages for what I see as a small change.

I'm not sure how translation works either, but this does seem like a sensible point. I really don't know if the translation effort is worth the change. But I thought I'd leave this comment just to clarify the meaning.

**Comment by felixxm** [comment]
Thanks for this patch, however we try to avoid trivial wording changes unless it's a big problem as it creates extra work for documentation translators.

**Comment by asaf-kali** [comment]
Makes sense! Thanks for the time and review anyway.

**Pull request closed without merging**
