### PR TITLE
Fixed #25200 -- Updated admin screenshots in docs.

### PR DESCRIPTION
**Pull request by ryangallen**
The files have been updated for the new admin styling, with slight adjustments/renaming to better match the documentation they demonstrate.

### CODE REVIEW

**Comment by collinanderson** [comment]
Just a thought: it might be smart to not have a reference to django 1.9, so the images don't become too dated over time.

**Comment by timgraham** [comment]
I don't see much harm in the Django 1.9 mention, but feel free to redo it if you like, Ryan.

**Comment by ryangallen** [comment]
I kind of see the 1.9 mention as a celebratory milestone marker -- if it start's to seem dated, chances are the admin style is dated too. I'd like to keep it if that's alright.

**Comment by ryangallen** [comment]
Note: here are the documentation sections that these images are for:

* fieldsets.png: [ModelAdmin.fieldsets](https://docs.djangoproject.com/en/dev/ref/contrib/admin/#django.contrib.admin.ModelAdmin.fieldsets)
* list_filter.png: [ModelAdmin.list_filter](https://docs.djangoproject.com/en/dev/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_filter)
* raw_id_fields.png: [ModelAdmin.raw_id_fields](https://docs.djangoproject.com/en/dev/ref/contrib/admin/#django.contrib.admin.ModelAdmin.raw_id_fields)
* admin-actions.png: [Admin Actions](https://docs.djangoproject.com/en/dev/ref/contrib/admin/actions/#admin-actions)
* adding-actions-to-the-modeladmin.png: [Adding actions to the ModelAdmin](https://docs.djangoproject.com/en/dev/ref/contrib/admin/actions/#adding-actions-to-the-modeladmin)
* actions-as-modeladmin-methods.png: [Actions as ModelAdmin methods](https://docs.djangoproject.com/en/dev/ref/contrib/admin/actions/#actions-as-modeladmin-methods)

**Comment by collinanderson** [comment]
cool. makes sense.

**Comment by timgraham** [comment]
merged in 6e8ddbaa2563ad7b95f96fe757d08870d2312977 and fba8655e88e9ed576630d7f505389119ab36ef28, thanks!

**Pull request closed without merging**
