### PR TITLE
Refs #24007 -- Removed an apps.populate() call in model unpickling that can cause deadlocks.

### PR DESCRIPTION
**Pull request by timgraham**
discussion: https://groups.google.com/d/topic/django-developers/YvEzdQU4qUU/discussion

(ticket to be created -- I guess this should this be backported with a note about needing to fix any affected scripts?)

### CODE REVIEW

**Comment by timgraham** [comment]
@claudep, I guess you have a project where you ran into this. Could you verify there is no problems with using `django.setup()`?

Assuming we proceed with this patch, do you think there's value in keeping the `test_unpickling_when_appregistrynotready` test?

**Comment by claudep** [comment]
If you judge that the use case of ticket https://code.djangoproject.com/ticket/24007 is not valid, so be it. In that use case, calling `django.setup()` before unpickling is not doable, as the external tool is doing the unpickling of model data before calling my app's function.
We should then at least document in backwards incompatibilities that unpickling model data from non-django code is not possible any longer. I don't know yet how I would workaround this limitation.

**Comment by timgraham** [comment]
Claude, did you follow [Aymeric's reply](https://groups.google.com/d/msg/django-developers/YvEzdQU4qUU/IYhkconCBAAJ) on the mailing list? Maybe you want to chime in there.

**Comment by aaugustin** [comment]
I'd like to see someone try (possibly myself, but I can't say when) the solution I suggested on the mailing list for rq before moving forwards with this. If it doesn't work easily, we'll strand users.

**Comment by timgraham** [comment]
Copying the "worker script" from the "Performance notes" section at http://python-rq.org/docs/workers/ and replacing
```
# Preload libraries
import library_that_you_want_preloaded
```
with 
```
from django.conf import settings
settings.configure(DEBUG=True, INSTALLED_APPS=['polls'], SECRET_KEY = "blah")
import django
django.setup()
```
worked for me.

**Comment by aaugustin** [comment]
I believe that's what we should recommend, then.

@claudep -- does that sound acceptable to you?

**Comment by claudep** [comment]
Yes, that looks very interesting, at least for my use case. Thanks Tim for exploring! I don't know if other tools all have this sort of hooks, so I still think that if we commit this, that should appear in backwards incompatibilities.

**Comment by aaugustin** [comment]
Yes, considering that we had the "magic fix" available in three releases, its removal is a backwards incompatibility. 

I considered implementing a deprecation path but I'm not sure many people read their rq or celery logs!

**Comment by timgraham** [comment]
Do you prefer not to backport the fix, or make its release note more prominent in the minor release notes?

**Comment by claudep** [comment]
I wouldn't backport such a sensible fix in a stable release!

**Comment by aaugustin** [comment]
Like Claude, I wouldn't do it in a minor release.

**Comment by timgraham** [comment]
Okay, I wasn't sure how severe the possible deadlock issue was. I've adapted and expanded the release note for 1.10.

**Comment by jbazik** [comment]
Ah, I'm sorry to hear it won't go into 1.8LTS - that's where I'm planning to stay for a while.  It's a real blocker for me, and I'll either have to maintain a patch going forward or tinker with my django-multisite configuration to avoid unpickling.

**Comment by aaugustin** [comment]
@jbazik Even if you stay on Django 1.9, if you do what the release notes suggest, `django.setup()` will already have run when reaching that point, the `if apps.ready` condition won't match, and `apps.populate()` won't run. So that should solve the issue for you.

**Comment by jbazik** [comment]
@aaugustin That won't help, in my case.  My site deadlocks from the first call to django.setup().

**Comment by aaugustin** [comment]
Ah, right, Django unpickles a model instance during `django.setup()` in your setup.

You may have to run with a patched version of Django :-/

**Pull request merged**
