### PR TITLE
Fixed #32934 -- Made Admin sidebar height dynamic based on visible header.

### PR DESCRIPTION
**Pull request by gmjosack**
The current sticky nav bar on admin anchors past the page. If you have
a long list of apps you have to scroll the whole page and then the nav
to get to the bottom. This subtracts the height of the headers from
the viewport height to get a sticky sidebar that scrolls as you'd expect

### Example of current behavior
You can see there is a scrollbar despite the main content being small. You must scroll the entire page to access the bottom of the nav bar.
Before

### Example of behavior with this change
After

### CODE REVIEW

**Comment by felixxm** [comment]
@knyghty Do you want to take a look?

**Comment by knyghty** [comment]
Thanks for this, @gmjosack. This would good to fix but I think this won't work universally. For example, there is a breakpoint that makes the header larger but the nav bar is still visible - this will produce an unnecessary scrollbar still (though you can't see it in this screenshot):

Screenshot 2021-04-19 at 10 40 10

We could fix this with a media query. However it's also possible to embiggen the header in other ways:

Screenshot 2021-04-19 at 10 43 15

To fix this we'd probably need a small piece of JS, but it would probably be overkill.

I imagine just adding the media query would address this for 99%+ of users, I don't think there is a need to over-engineer it.

**Comment by gmjosack** [comment]
So I know you said JavaScript for this would be overkill but I realized the original proposed change had the unintended consequence that that the sidebar didn't fill the page and had a large gap on the bottom when you had a lot of content because the header scrolls off the page.

The JavaScript solution was tested with large/small sidebars, large/small content, scrolling, resizing, and header embiggening due to breakpoint.

This is a bit more complicated that I anticipated when opening this PR and I'm not much of a frontend dev so I'd appreciate any advice of whether this is a reasonable solution. I couldn't figure out any way to do this with just CSS.

**Comment by gmjosack** [comment]
Lemme know if there are any changes that need to be made to make this more amenable. I'd love to get some kind of fix for this as its a pretty common annoyance as I tend to access links at the bottom of the sidebar often in my project.

**Comment by knyghty** [comment]
@gmjosack, sorry for the delay. I've tried this out locally, it seems to work well. I'm no JS expert either but it looks ok to my eyes.

I had another mess around with it today to try to find some simpler solution but I couldn't find anything.

**Comment by gmjosack** [comment]
Is there anything else I'd need to do to get this merged? I know it's a small thing but it'd be nice to have scrolling work properly in admin :)

**Comment by jacobtylerwalls** [comment]
> Is there anything else I'd need to do to get this merged?

The best bet is to open a [ticket](https://code.djangoproject.com/newticket), which is how we track open work.

**Comment by carltongibson** [comment]
I'm _quite_ sceptical about this. 😬

The existing behaviour is as I'm expecting: I have a long app list and short main content (change list say); I can scroll the app list independently of the main content to reach the bottom apps. (I can also scroll the main page, yes — but I'm not seeing an issue there: the HTML document extends down, so I'm expecting to be able to scroll.) — tl;dr: it's not an issue, as far as I can see thus far. (Is this a particular browser issue?) 

Maybe I've totally missed the issue? (But I think I've got the case from the description.) 

Then a JS solution here seems like... erm... _"using a sledgehammer to crack a nut"_, if you'll pardon the phrase. For me, unless we can highlight the issue more clearly, we should be looking for a CSS fix, if one at all. (I can't be the only one to think that no?) 

If we were to think about JS here, surely we'd need tests? (But the prospect of exactly what we'd test here makes me loop back to _JS is the wrong approach_.)

Currently I'm 👎 on this, and would say `wontfix`.

**Comment by knyghty** [comment]
Looking again... I think this problem also happens for long content, it's just easier to notice when the content is shorter. You still need to scroll the content down a bit to see the last few items, because more of the navbar is visible when you're scrolled down vs when the header is visible.

So I think there is something to fix here, but I also don't think this is the right fix.

**Comment by carltongibson** [comment]
> I imagine just adding the media query would address this for 99%+ of users,... 

Can we investigate that quickly? (i.e. the CSS fix, perhaps adjusting or dropping it where wrong)

**Comment by carltongibson** [comment]
Hi @gmjosack — do you have the energy here to see if we can get a good (enough) solution with the pure CSS approach?

**Comment by gmjosack** [comment]
I don't still have the dev environment setup with all the test models and have too much on my plate with other projects. If this doesn't bother others we can just close this issue for now. I think it'd be nice polish but not something i have the time to follow up on right now.

**Comment by carltongibson** [comment]
Ok, thanks for the update. I'll unassign you on the ticket and someone else can pick it up.

**Comment by hrushikeshrv** [comment]
Can we reopen this issue? I don't think there will be a pure CSS solution, at least not one that will work with 100% of use cases. We could use a media query to set the height of the nav as previously suggested. That would at least fix it for 99% of users - better than none. I agree it's nothing more than a mild annoyance but it has been mildly annoying me for a while 😬

**Comment by hrushikeshrv** [comment]
> Thanks for this, @gmjosack. This would good to fix but I think this won't work universally. For example, there is a breakpoint that makes the header larger but the nav bar is still visible - this will produce an unnecessary scrollbar still (though you can't see it in this screenshot):
> 
> Screenshot 2021-04-19 at 10 40 10
> 
> We could fix this with a media query. However it's also possible to embiggen the header in other ways:
> 
> Screenshot 2021-04-19 at 10 43 15
> 
> To fix this we'd probably need a small piece of JS, but it would probably be overkill.
> 
> I imagine just adding the media query would address this for 99%+ of users, I don't think there is a need to over-engineer it.

@knyghty I have opened a pull request with this CSS approach.

**Pull request closed without merging**
