### PR TITLE
Updated humanize translation catalog es_AR

### PR DESCRIPTION
**Pull request by TheCraftsmen**
like in the ticket https://code.djangoproject.com/ticket/21415  but for the Argentina translation case.

### CODE REVIEW

**Comment by TheCraftsmen** [comment]
@claudep , I added django.mo.  And I changed the translation sentence of "a minute ago"

**Comment by timgraham** [comment]
Shouldn't the translations be fixed in [Transifex](https://docs.djangoproject.com/en/dev/internals/contributing/localizing/#translations), not through GitHub?

**Comment by TheCraftsmen** [comment]
@timgraham like in https://code.djangoproject.com/ticket/21415 this is an issue associated to the naturaltime method error. Why somebody need make a transifex file? This is a bug in the main project in earlier versions, don't happen. And this bug had 4 years or more. You can see this person (https://stackoverflow.com/questions/30923349/django-naturaltime-adds-strange-characters) asking for this problem in 2015, for example. I think that this need a solution.

**Comment by timgraham** [comment]
As far as I understand, the `msgstr`strings are pulled from Transifex. If you submit the fix this way, it will be lost the next time translations are fetched from Transifex. Did you read the documentation about the translation workflow?

**Comment by TheCraftsmen** [comment]
But for a person like me that don't have the access to the transifex, is the unique way make a fork and solve the problem changing the file.

**Comment by claudep** [comment]
Thanks for the pull request. I fixed that in 72026fff / 61fd2b494a.

**Comment by claudep** [comment]
Oh, and I indeed fixed the strings in Transifex first!

**Comment by TheCraftsmen** [comment]
thanks @claudep !!

**Pull request closed without merging**
