### PR TITLE
Avoid CSRF token discovery via BREACH attack by masking with a random value

### PR DESCRIPTION
**Pull request by adambrenecki**
Patch for [ticket 20869 in trac](https://code.djangoproject.com/ticket/20869), using the same approach as the Rails patch mentioned in the first comment there.

Avoids CSRF token discovery via BREACH by XORing the token in the body with a value generated anew each request (actually, each time `get_token` is called) & storing said value alongside it.

### CODE REVIEW

**Comment by auvipy** [comment]
@MarkusH I want to do the remaining tasks related to this pull to get merged. how can I do that?

**Comment by MarkusH** [comment]
@auvipy You should first claim the ticket and open a new pull request with your patch (Download https://github.com/django/django/pull/1477.patch and apply with `git am`). You should also follow our [patch review checklist](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/submitting-patches/) to get your pull request merged.

**Comment by adambrenecki** [comment]
@auvipy I've [de-assigned the ticket on Trac](https://code.djangoproject.com/ticket/20869#comment:29); it's all yours.

As an aside, there was some discussion on django-developers as to whether to use a Vigenère cipher or XOR and I think the consensus was XOR was preferred; as mentioned above I have a non-squashed branch from which you can get my old code that uses XOR

**Comment by auvipy** [comment]
OK :) @adambrenecki

**Comment by timgraham** [comment]
Closing due to inactivity.

**Pull request closed without merging**
