### PR TITLE
Note that action descriptions are %-formatted.

### PR DESCRIPTION
**Pull request by jbothma**

### CODE REVIEW

**Comment by felixxm** [comment]
Description strings are not %-formatted.

**Comment by jbothma** [comment]
I'm quite sure they are https://github.com/django/django/blob/main/django/contrib/admin/options.py#L1029

If I make a description `Assign to University %r` I get the following:

Screenshot_2022-08-05_14-42-35

For a realistic example, we generate actions based on category names. If a category name is something like `Assign to SIOC: % change Matric result improvement` we get the following exception:

Screenshot_2022-08-10_10-33-21

I was surprised by the need to escape these, so I figured a note in the docs might help. I couldn't see any documentation that this is actually an intended feature so personally I'd prefer if this didn't do interpolation on my descriptions.

We generate action functions dynamically and [assign the description via the short_description attribute](https://docs.djangoproject.com/en/4.0/ref/contrib/admin/actions/).

**Comment by felixxm** [comment]
I'm really surprised, we should document supported placeholders in [`Admin actions` docs](https://docs.djangoproject.com/en/4.0/ref/contrib/admin/actions/).

**Comment by felixxm** [comment]
@jbothma Do you have time to keep working on this?

**Comment by jbothma** [comment]
Hi! Happy to try! Can't make big promises.

Do you just want something like this?

```
    .. note::

        The description string will be %-formatted. Supported values are verbose_name
        and verbose_name_plural of the model.

        %-signs intended to be printed as-is should be escaped with another %-sign, i.e. as %%.
```

**Comment by felixxm** [comment]
> Hi! Happy to try! Can't make big promises.
> 
> Do you just want something like this?

Yes something similar, e.g.
```
.. admonition:: Description formatting

    Action descriptions may contain ``'%(verbose_name)s'`` and
    ``'%(verbose_name_plural)s'``, which are replaced, respectively, by the ... and ....
```

**Pull request closed without merging**
