### PR TITLE
Fixed #34515 -- Made LocaleMiddleware prefer language from paths when i18n patterns are used.

### PR DESCRIPTION
**Pull request by felixxm**
ticket-34515

See [discussion](https://forum.djangoproject.com/t/django-behavior-on-translatable-url-patterns-i18n-patterns-when-prefix-default-language-false-is-used/20564/1).

### CODE REVIEW

**Comment by felixxm** [comment]
I'm going to squash commits before merging.

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Review by sarahboyce — APPROVED** [review]
LGTM! Thank you for picking this up :star:

**Comment by aboutofpluto** [comment]
LGTM too, thanks a lot, I'll give a try as soon as I can!

**Comment by felixxm** [comment]
Thanks for reviews :+1:

**Pull request merged**
