### PR TITLE
Added MultiPartParser tests for parsing base64-encoded fields.

### PR DESCRIPTION
**Pull request by benebsiny**
Hi, since I ran the testing coverage for this project and found the [base64 encoding](https://github.com/benebsiny/django/blob/40a2c811e3ed7fdb26ab4443e39e113c2fcf2aa9/django/http/multipartparser.py#L227) wasn't tested in `multipartparser.py`.

Therefore, I added a testing to test the base64 for `multiparser.py`. 

If this PR is inapproriate, please let me know. Thank you!

### CODE REVIEW

**Comment by felixxm** [comment]
@benebsiny Thanks :+1: extra tests coverage is always welcome. Can we move new tests to the `file_uploads.tests.FileUploadTests` where base64 uploads for files are tested?

https://github.com/django/django/blob/4f6a51dfe6a4a8d5ed61c73b902e808109f142b0/tests/file_uploads/tests.py#L127-L182

**Comment by benebsiny** [comment]
Hi @felixxm, thank you for your feedback! I've looked into the `FileUploadTests.py`. This module tests code that related to file. However, my testing is to test the base64 that defined in `field` instead of `file`. Is it a good idea to move these testing to `FileUploadTests.py` ?

**Comment by benebsiny** [comment]
Hi @felixxm, I've made changes, have a look at it, thanks!

**Comment by felixxm** [comment]
@benebsiny Thanks :+1: Welcome aboard :boat:

**Pull request merged**
