### PR TITLE
Fixed #34995 -- Fixed position of related widget's add link on admin pages for smaller screens.

### PR DESCRIPTION
**Pull request by knyghty**
https://code.djangoproject.com/ticket/34995

A little tricky. Had to reposition the selector div so the add links are in the right place.

Will wait for the ticket to be accepted before working on it more.

# Before

Screenshot 2023-11-23 at 16 13 01

# After

Screenshot 2023-11-23 at 17 40 37

Screenshot 2023-11-23 at 17 40 45

Screenshot 2023-11-23 at 17 40 57

Screenshot 2023-11-23 at 17 41 32

### CODE REVIEW

**Comment by nessita** [comment]
Thank you @knyghty ! Functionality looks great, I tested small, medium and wide screens. I'm not sure I understand the need to add the extra `div` to the selector, could you please explain a bit more? is it possible/does it make sense to add a selenium test for it?

**Comment by knyghty** [comment]
@nessita There isn't an extra element involved. `quickElement` appends the `selector` div to the end of the parent. However, we need it to be at the beginning so that the add link is on the right, rather than the left, when using flex. So the extra line moves it to the beginning.

I pushed a comment explaining this as it's not very obvious. I'm not sure (and hope) a Selenium test is needed because the behaviour is covered with existing tests, I'm not sure exactly what test I would add that doesn't already exist.

**Comment by sarahboyce** [comment]
If you need a regression test, I think we can do this in the Javascript tests:
```
--- a/js_tests/admin/SelectFilter2.test.js
+++ b/js_tests/admin/SelectFilter2.test.js
@@ -5,9 +5,11 @@ QUnit.module('admin.SelectFilter2');

 QUnit.test('init', function(assert) {
     const $ = django.jQuery;
-    $('<form><select id="id"></select></form>').appendTo('#qunit-fixture');
+    $('<form id="test"><label for="id_id">Test</label><div class="helptext">This is helpful.</div><select id="id"></select></form>').appendTo('#qunit-fixture');
     $('<option value="0">A</option>').appendTo('#id');
     SelectFilter.init('id', 'things', 0);
+    assert.equal($('#test').children().first().prop("tagName"), "DIV");
+    assert.equal($('#test').children().first().attr("class"), "selector");
     assert.equal($('.selector-available h2').text().trim(), "Available things");
     assert.equal($('.selector-chosen h2').text().trim(), "Chosen things");
     assert.equal($('.selector-chosen select')[0].getAttribute('multiple'), '');
```

**Comment by nessita** [comment]
@knyghty I can't reproduce locally the Selenium failure, could you take a look if you have some time?

**Comment by knyghty** [comment]
@nessita Of the test failures in the CI, the only one I can reproduce is `admin_views.test_autocomplete_view.SeleniumTests.test_select` and then only in Firefox. So I am not really sure what more I can do.

**Comment by sarahboyce** [comment]
> @nessita Of the test failures in the CI, the only one I can reproduce is `admin_views.test_autocomplete_view.SeleniumTests.test_select` and then only in Firefox. So I am not really sure what more I can do.

`admin_views.test_autocomplete_view.SeleniumTests.test_select` is a natorious flakey test, if you can figure that one out amazing but I think it will likely pass on a rerun.
With the other failures it is suspicious that they fail on the first click of the page. It might be that with the extra html manipulation, the page is not yet "ready" to be clicked and we need to add in some waits. I am having a play and seeing if I can get them passing on my fork 👍

**Comment by sarahboyce** [comment]
https://github.com/sarahboyce/django/pull/6/commits/b9130404c3fa7ac314ebddf09a3122acabae66e6

Thrown the kitchen sink at it (aka tried a whole bunch of things and hoped for the best), this seems to work 🤷‍♀️ 
Going to re-run 2 more times as a "flakiness" check 👍

**Review by sarahboyce — APPROVED** [review]
https://www.selenium.dev/selenium/docs/api/py/webdriver/selenium.webdriver.common.action_chains.html
I agree the `ActionChains` with the `move_to_element` functionality resolves when elements are outside the window in small windows and makes these tests more rubust to the ui changes.
Great job!

**Comment by nessita** [comment]
As I said in [Discord](https://discord.com/channels/856567261900832808/1177242175852007464/1179845176596893756):

> Ok, all done, proper authors, CI fully green, isolated commit
@knyghty  I am definitely landing this in main, then I'll do a local backport and see how things behave
because we've been landing so many changes in the admin CSS, that I wanna be sure that this change "in isolation" in 5.0 is an improvement (I think so but want to triple check)

**Pull request merged**
