### PR TITLE
Fixed #25322 -- Lazily compiled core.validators regular expressions.

### PR DESCRIPTION
**Pull request by jonashaag**
Don't execute lots of slow `re.compile` calls at module-level in
`django.core.validators`. This saves a few hundert milliseconds when
importing the module for the first time, which is a significant speedup
to the `django-admin.py` command (and possibly other places as well).

The former `re.compile` calls are wrapped in SimpleLazyObjects so
they're executed lazily, i.e. not before they're needed for the first
time.  This could have also been solved by making the regexes
`cached_poperty`s of the `Validator` classes, but that would have broken
backwards compatibility as some of the regexes are assigned to
module-level names (`slug_re`, ...).

This speeds up running `django-admin.py` by about 500ms on my machine.

### CODE REVIEW

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by jonashaag** [comment]
Note that the failed `default` check of the first commit has nothing to do with the code changes I made but indicates a flapping test.

**Comment by timgraham** [comment]
This changes seems okay. Hopefully it doesn't break any non-tested scenarios.
On my machine:
```
$ time django-admin
before:
real	0m0.933s
user	0m0.869s
sys	0m0.052s
after:
real	0m0.876s
user	0m0.827s
sys	0m0.046s
```
Curious if you benchmarked differently?

**Comment by jonashaag** [comment]
From a different machine than I initially used for testing:

- `master`:
  - Python 2: `0.56 real         0.49 user         0.06 sys`
  - Python 3: `        0.56 real         0.52 user         0.03 sys`
- patched:
  - Python 2: `        0.26 real         0.20 user         0.05 sys`
  - Python 3: `        0.35 real         0.31 user         0.03 sys`

**Comment by timgraham** [comment]
merged in 2bb1027d6bcdad59624a9d08701e0d2e4a9c0ba7, thanks!

**Pull request closed without merging**
