### PR TITLE
[4.1.x] Updated translations from Transifex.

### PR DESCRIPTION
**Pull request by claudep**
This also fixes related i18n tests.

### CODE REVIEW

**Comment by felixxm** [comment]
@claudep Thanks :+1: Why we have 174 files less? Have you reverted files where only "Plural-Forms" was changed?

**Comment by felixxm** [comment]
> @claudep Thanks +1 Why we have 174 files less? Have you reverted files where only "Plural-Forms" was changed?

As far as I'm aware we should include them, see ticket-32910.

**Comment by felixxm** [comment]
OK, you've also reverted `Plural-forms` changes for `es*` languages :thinking:

**Comment by claudep** [comment]
Yes, those plural forms are crazy.

**Comment by felixxm** [comment]
> Yes, those plural forms are crazy.

My Spanish is not good enough to decide here :es: hablo un poco de espanol :smile:

**Comment by felixxm** [comment]
Merged in a3bab9332416f655c6ae0fa306c94f7f52e7398d.

**Pull request closed without merging**
