### PR TITLE
Add import os

### PR DESCRIPTION
**Pull request by huakkai**

### CODE REVIEW

**Comment by felixxm** [comment]
There is no need to import `os` in the `settings.py` template.

**Comment by huakkai** [comment]
Why? Every time you create a project, you need to add the import os manually @felixxm

**Comment by felixxm** [comment]
> Why? Every time you create a project, you need to add the import os manually @felixxm

That's not true, `settings.py-tpl` doesn't use `os`.

**Comment by huakkai** [comment]
> > Why? Every time you create a project, you need to add the import os manually @felixxm
> 
> That's not true, `settings.py-tpl` doesn't use `os`.

I see. Thank you！

**Pull request closed without merging**
