### PR TITLE
Fixed wrapping of long model names in the admin.

### PR DESCRIPTION
**Pull request by felixxm**
Before:

image
----
image
----
image
----

After:

image
----
image
----
image
----

### CODE REVIEW

**Review by ngnpope — APPROVED** [review]
Based on your screenshots this looks good 👍🏻

**Review by hramezani — APPROVED** [review]
LGTM :+1:

**Review by kezabelle — APPROVED** [review]
Yeah, looks right enough[^1] at a glance (though CSS being CSS, who knows what else might lurk)

[^1]: We did this same dance previously for long values in the debug pages (#15351, #15253) and Modeladmin's list_filter (#15251) .

**Review by pauloxnet — APPROVED** [review]

**Comment by collinanderson** [comment]
This change kinda messes up the admin change list page. Maybe limit the change to only the admin index page if possible. https://code.djangoproject.com/ticket/34102

**Comment by collinanderson** [comment]
Here's a possible fix: https://github.com/django/django/pull/16190

**Pull request merged**
