### PR TITLE
Made GitHub action add welcome message only after opening PR.

### PR DESCRIPTION
**Pull request by felixxm**
By default, `pull_request_target` workflow runs when an activity type is `opened`, `synchronize`, or `reopened`.

### CODE REVIEW

**Review by carltongibson — APPROVED** [review]
Yes, We don't need it multiple times.

**Comment by felixxm** [comment]
@orf I don't know why but it looks that "New contributor message" crashes when branch doesn't contain `.github/workflows/new_contributor_pr.yml` (see #14117). The message came after rebase :thinking:

**Review by orf — APPROVED** [review]

**Comment by orf** [comment]
> @orf I don't know why but it looks that "New contributor message" crashes when branch doesn't contain `.github/workflows/new_contributor_pr.yml` (see #14117). The message came after rebase 🤔

Can you define crashes? I can’t see any errors in the actions page. We should only run it when a PR is opened, that was an oversight, but with this any PRs opened from now on should include the message?

**Comment by felixxm** [comment]
It looks that we don't have logs from before the rebase :disappointed: It was just `Server Error` :shrug: . Let's wait for the next first-time contributor.

**Pull request merged**
