### PR TITLE
Fixed #29799 -- Allowed registration and unregistration of lookups per field instances.

### PR DESCRIPTION
**Pull request by cansarigol**
Ticket [#29799](https://code.djangoproject.com/ticket/29799)

As far as I could understand, I prepared a PR. Does this approach work, Could you review @charettes?

### CODE REVIEW

**Comment by cansarigol** [comment]
Hi @charettes, I can merge our codes + tests if you want. 
I doubt about unregister and override from instance processes in your solution. Can we handle these in classorinstancemethod?

**Comment by carltongibson** [comment]
> Maybe it's too much magic.

Just thinking about this from the end-user POV. (i.e. I _want_ this, how do I want it to look?) — having `field_instance.register_lookup` work is exactly what I want. 

First pass thought: I **should not** be able to _unregister_ a class level lookup from an instance. 

@cansarigol Do you have capacity to keep working on this? (It would be a great addition 🙂)

**Comment by cansarigol** [comment]
Hi @carltongibson, I would like to pursue this issue. I wasn't sure that the approach is correct so I didn't assign myself.  I will continue, thanks.

**Comment by felixxm** [comment]
Closing due to inactivity.

**Pull request closed without merging**
