### PR TITLE
Fixed #32127 -- Fixed admin change-form textarea layout for mid-sized displays.

### PR DESCRIPTION
**Pull request by thatnerdjosh**
https://code.djangoproject.com/ticket/32127

### CODE REVIEW

**Comment by thatnerdjosh** [comment]
@carltongibson For visibility, just in case you still wanted to backport this soon

**Comment by carltongibson** [comment]
Thanks @thatnerdjosh. I will take a look this week 👍

**Review by carltongibson — APPROVED** [review]
Hi @thatnerdjosh — Thanks for this. Looks like it does the job. 🥇

**Comment by thatnerdjosh** [comment]
@carltongibson no problem =)

**Pull request merged**
