### PR TITLE
Fixed #32417 -- Removed unneeded hasattr() check in LiveServerTestCase._tearDownClassInternal().

### PR DESCRIPTION
**Pull request by cjerdonek**
https://code.djangoproject.com/ticket/32417

### CODE REVIEW

**Comment by cjerdonek** [comment]
I will fix / update this PR after PR #14001 is merged.

**Comment by cjerdonek** [comment]
@apollo13 would you mind taking a look at this one, too, if you have some time? @felixxm CC'ed you on the ticket.

**Comment by felixxm** [comment]
@cjerdonek Thanks :+1: I moved test improvements to a separate commit.

**Comment by cjerdonek** [comment]
> @cjerdonek Thanks 👍 I moved test improvements to a separate commit.

Thanks a lot for doing that, @felixxm. Those clean-ups were indeed separate (had been thinking of suggesting that, in fact).

**Review by apollo13 — APPROVED** [review]

**Pull request merged**
