### PR TITLE
Moved LogEntry-related tests to their own test case

### PR DESCRIPTION
**Pull request by claudep**
Refs #21113.

### CODE REVIEW

**Comment by timgraham** [comment]
I'll provide a diff with a few cleanups shortly.

**Comment by timgraham** [comment]
http://dpaste.com/1CYVPQP

**Comment by claudep** [comment]
Are you sure about your diff content:
```
patch unexpectedly ends in middle of line
patch: **** malformed patch at line 135:
```

**Comment by timgraham** [comment]
Hm, dpaste.com seems to cause issues. Please try https://dpaste.de/mcnc/raw

**Comment by claudep** [comment]
Thanks, I was able to apply that version.

**Pull request closed without merging**
