### PR TITLE
Fixed #30324 -- Forced utf-8 encoding when loading debug templates.

### PR DESCRIPTION
**Pull request by pope1ni**
Refs #28007 and #29654.

Regression in ea542a9c7239b5b665797b7c809f1aceb0b412cf and 50b8493581fea3d7137dd8db33bac7008868d23a.

### CODE REVIEW

**Comment by pope1ni** [comment]
An alternative to #11168. See [comment](https://code.djangoproject.com/ticket/30324#comment:4) on ticket.

**Comment by carltongibson** [comment]
Hey @pope1ni. This looks right. 

`<preamble>`
(The `Path` docs are a little misleading I think here. They say "behaves as built-in `open()`", which says `encoding` defaults to `locale.getpreferredencoding()`, rather than `...(False)` which should make a difference, however...) 

Testing on a vanilla Windows setup I get `cp1252` for the preferred encoding, regardless of passing the `set_locale` parameter or not. 
`</preamble>`

I'm not quite sure about the `Mock` usage here. When running the tests (without the fix) I get the expected failures **but** I'm kind of expecting to see the actual `UnicodeDecodeError`. What do you think? (Happy to be talked out of that. 🙂)

**Comment by pope1ni** [comment]
So apparently [`pathlib.Path.open()`](https://docs.python.org/3/library/pathlib.html#pathlib.Path.open) uses the builtin [`open()`](https://docs.python.org/3/library/functions.html#open), but looking [here](https://github.com/python/cpython/blob/2259b5af3c711b40d2b81eacc1b5d75cda1ae3e2/Lib/pathlib.py#L1177-L1186) I can see that it actually uses [`io.open()`](https://docs.python.org/3/library/io.html#io.open) although this is meant to be an alias for the builtin. (`io.open()` imports `_io.open()` as can be seen [here](https://github.com/python/cpython/blob/2259b5af3c711b40d2b81eacc1b5d75cda1ae3e2/Lib/io.py#L54-L57), at which point we're off into C.)

According to the documentation, the default value of `encoding` used by the builtin `open()` is determined by `locale.getpreferredencoding(False)`. I wanted to mock this to return `'ascii'` or `'cp1252'` so that we could see the `UnicodeDecodeError` in the tests, but was unable to work out where to mock this because the lookup is performed off in non-Python code. (I don't even know whether it is possible.)

If we can make this work, that would be ideal. Mocking the `django.views.debug.Path.open()` as I have done is the best alternative I can think of to ensure that we don't regress passing `encoding='utf-8'`... Ideas most welcome. :male_detective:

**Comment by pope1ni** [comment]
So I found the Python implementation of the `_io` module, [`_pyio`](https://github.com/python/cpython/blob/2259b5af3c711b40d2b81eacc1b5d75cda1ae3e2/Lib/_pyio.py), in which `_pyio.open()` delegates the [handling of encoding](https://github.com/python/cpython/blob/2259b5af3c711b40d2b81eacc1b5d75cda1ae3e2/Lib/_pyio.py#L240) to `_pyio.TextIOWrapper`. It looks as though this [imports `locale` locally](https://github.com/python/cpython/blob/2259b5af3c711b40d2b81eacc1b5d75cda1ae3e2/Lib/_pyio.py#L1942-L1954) which makes mocking hard (impossible?) in the Python case, let alone in the C implementation... And we are assuming that the two implementations are equivalent...

**Comment by pope1ni** [comment]
After a little more digging, I had some success with the following (on Linux):
```python
        reporter = ExceptionReporter(None, None, None, None)
        with mock.patch('_bootlocale.getpreferredencoding', return_value='ascii'):
            # UnicodeDecodeError should not be raised by the following calls.
            reporter.get_traceback_html()
            reporter.get_traceback_text()  
```
To explain: The [`locale`](https://github.com/python/cpython/blob/2259b5af3c711b40d2b81eacc1b5d75cda1ae3e2/Lib/locale.py) module [implements `getpreferredencoding()`](https://github.com/python/cpython/blob/2259b5af3c711b40d2b81eacc1b5d75cda1ae3e2/Lib/locale.py#L616-L662). This makes use of `_bootlocale.getpreferredencoding()` which I was able to mock successfully, but there are other ways of selecting the encoding such as [`CODESET`](https://github.com/python/cpython/blob/2259b5af3c711b40d2b81eacc1b5d75cda1ae3e2/Lib/locale.py#L627) and [`sys.flags.utf8_mode`](https://github.com/python/cpython/blob/2259b5af3c711b40d2b81eacc1b5d75cda1ae3e2/Lib/locale.py#L620).

I thought that this may not be robust, but then looking in [`_bootlocale`](https://github.com/python/cpython/blob/2259b5af3c711b40d2b81eacc1b5d75cda1ae3e2/Lib/_bootlocale.py) we see [this docstring](https://github.com/python/cpython/blob/2259b5af3c711b40d2b81eacc1b5d75cda1ae3e2/Lib/_bootlocale.py#L1-L5) which indicates that `_io` imports from `_bootlocale` and not `locale` anyway. That means mocking here is probably reliable enough to bypass the other methods of overriding the encoding.

The question is whether we can stomach this level of abuse of the internals of Python. Regardless, if things changed we wouldn't know that the test was no longer failing, so it is probably still important to mock `django.views.debug.Path.open()` anyway.

**Comment by carltongibson** [comment]
Hey @pope1ni. Thank you for your super effort here. 👍 

> The question is whether we can stomach ...

Yeah. This may be above-and-beyond...

Let me have a look tomorrow at this: it **should** just reproduce on my Windows setup. If it does, we can then see if it does similar on the Windows CI build. If so, that might just be enough. (We'd have a regression that _would have failed_ had it been in place beforehand.) If not, then the simple fix may be enough. 

Super work. (Again).

**Comment by felixxm** [comment]
I rebased and added some final edits.

**Comment by pope1ni** [comment]
Ok. Was just about to suggest some changes myself...

**Comment by felixxm** [comment]
@pope1ni Feel-free if I missed sth.

**Comment by pope1ni** [comment]
Fixes to the commit message:
```
Fixed #30324 -- Forced utf-8 encoding when loading debug templates.
    
Refs #28007 and #29654.
    
Regression in 50b8493581fea3d7137dd8db33bac7008868d23a.
Related to ea542a9c7239b5b665797b7c809f1aceb0b412cf.
```
Strictly speaking the regression was in 50b8493581fea3d7137dd8db33bac7008868d23a, but ea542a9c7239b5b665797b7c809f1aceb0b412cf was contributory. Admittedly we had no unicode characters in there before...

I didn't like what I'd written for the release note and feel this is more better as only the 500 page was directly affected:
```
* Fixed a regression in Django 2.2 that caused a crash when loading the 
  template for the technical 500 debug page. (:ticket:`30324`).
```

**Comment by pope1ni** [comment]
@felixxm Have made those tweaks.

@carltongibson I think the error was encountered with cp949 according to the original ticket.

**Comment by felixxm** [comment]
@pope1ni Sorry for late comments :neutral_face:, but due the fact that only 500 is affected by this regression in Django 2.2 we should probably split fix into two commits, and backport only fix for 500 errors.

**Comment by carltongibson** [comment]
Hmmm. Is this not going to affect all the templates though? (OK it’s the just the 500 that’s come up immediately...)

**Comment by pope1ni** [comment]
So what do we want to do here?

I think we can create another pull request targeting `stable/2.2.x` only with the release note from this PR and just revert the ellipsis to three periods. This PR can then have the release note removed and be committed to `master`.

**Comment by felixxm** [comment]
@pope1ni I will split commits give me few minutes.

**Comment by felixxm** [comment]
Done :relaxed: .

@pope1ni Thanks again for your hard work :rocket:

**Comment by pope1ni** [comment]
You're welcome!

**Pull request merged**
