### PR TITLE
Refs #34095 -- Changed more properties to use rem units in admin CSS.

### PR DESCRIPTION
**Pull request by SwastikTripathi**

### CODE REVIEW

**Comment by felixxm** [comment]
@SwastikTripathi Thanks! Can you check and fix [other cases](https://github.com/django/django/pull/16180#issuecomment-1279769391)?

**Comment by SwastikTripathi** [comment]
> @SwastikTripathi Thanks! Can you check and fix [other cases](https://github.com/django/django/pull/16180#issuecomment-1279769391)?

For the forms would it be good to convert the width measurements as well?
And yeah i plan on making more commits for other cases in a few days

**Comment by SwastikTripathi** [comment]
> @SwastikTripathi Thanks! Can you check and fix [other cases](https://github.com/django/django/pull/16180#issuecomment-1279769391)?

changed some other cases as well...

**Review by felixxm — COMMENTED** [review]
@SwastikTripathi Thanks :+1: I added a few more changes.

**Comment by felixxm** [comment]
buildbot, test on selenium.

**Pull request merged**
