### PR TITLE
Fixed #33507 -- Added uuid data type for MariaDB

### PR DESCRIPTION
**Pull request by raydeal**
Added db native uuid on MariaDB 10.7+

### CODE REVIEW

**Comment by raydeal** [comment]
Can @felixxm or anyone help and tell what version of mysql didn't pass tests?

**Comment by felixxm** [comment]
> Can @felixxm or anyone help and tell what version of mysql didn't pass tests?

See https://code.djangoproject.com/wiki/CI.

**Comment by SebaMutuku** [comment]
Please fix the failing tests

**Comment by raydeal** [comment]
I will create new PR

**Pull request closed without merging**
