### PR TITLE
Fixed #27604 -- Used the cookie signer to sign message cookies.

### PR DESCRIPTION
**Pull request by craiga**
Fixed #27604 -- Cleans up signing of message cookies.

Replaced signature-generation code with a call to the configured cookie signer.

### CODE REVIEW

**Comment by apollo13** [comment]
I do not think this is backwards compatible, as cookie signer prepends `django.http.cookies` etc before the key…

**Comment by craiga** [comment]
Thanks @apollo13, I didn't think this needed to be backwards-compatible. I'll try to get a bit more of an understanding of the context this afternoon.

**Comment by apollo13** [comment]
@craiga I guess that's something we will have to find out. What are the implications if this is not compatible? messages getting dropped silently? server error?

**Comment by craiga** [comment]
I left [a comment about this on the ticket](https://code.djangoproject.com/ticket/27604#comment:6):

> What should happen to cookies signed with the existing hashing method?
> 
> I haven't tested this (yet), but it looks like messages stored with the old hashing method will be silently ignored.
> 
> We could:
> 1. accept that messages from Django < 2.3 (?) are ignored;
> 2. add the existing `_hash` implementation into `_decode` for these legacy messages; or
> 3. just close this ticket.
> 
> I'll go ahead and implement option 2 as it's the safest.
> 
> However, as I've never left messages in storage for more than one or two request-response cycles, option 1 strikes me as reasonable and much cleaner.

**Comment by craiga** [comment]
Windows + SQLite CI failure looks unrelated to change… ?

**Comment by claudep** [comment]
I got a step further in #12397 by using the sign/unsign `Signer` methods. I'll explain on the ticket why I didn't use `set_signed_cookie`.

**Pull request closed without merging**
