### PR TITLE
Refs #33173 -- Added Python 3.11 to classifiers and tox.ini.

### PR DESCRIPTION
**Pull request by felixxm**
ticket-33173

### CODE REVIEW

**Review by carltongibson — APPROVED** [review]
Nice, thanks 👍

**Comment by felixxm** [comment]
All green :green_heart: :tada:

**Comment by pauloxnet** [comment]
Django for workgroups ? 😄

**Comment by adamchainz** [comment]
Will this be backported to the 4.1 branch, and the release notes updated to say 3.11 is supported?

**Comment by felixxm** [comment]
> Will this be backported to the 4.1 branch, and the release notes updated to say 3.11 is supported?

Yes, I'll do this later today.

**Comment by felixxm** [comment]
See #16230.

**Pull request merged**
