### PR TITLE
Fixed #32961 -- Added BitXor() aggregate to django.contrib.postgres.

### PR DESCRIPTION
**Pull request by ngnpope**
ticket-32961

Currently PostgreSQL 14 is still in beta, so marking as a draft.

### CODE REVIEW

**Comment by felixxm** [comment]
@pope1ni Thanks for this patch :+1: Just a note that PostgreSQL 14 will not be released before the Django 4.0 feature freeze, so I'm not sure if it's worth working on related features now :shrug:

**Comment by pope1ni** [comment]
> @pope1ni Thanks for this patch  Just a note that PostgreSQL 14 will not be released before the Django 4.0 feature freeze, so I'm not sure if it's worth working on related features now

I know, hence my [comment](https://code.djangoproject.com/ticket/32961#comment:2). It seems a shame that we might miss out by a matter of a week or two, especially as they're rather trivial. If they've already released, say, 14 RC2 then perhaps it could still be considered (with the potential to revert prior to beta)? Either way, this and the one for the SP-GiST additions are ready for post-freeze.

Also... Don't worry - I scanned the release notes and these were the only two things that really seemed significant for Django. There are unlikely to be more. 😄

**Comment by felixxm** [comment]
@ngnpope Thanks :+1:

**Comment by felixxm** [comment]
Merged in bd47b9bc816bf213b6d0027ed9a9a44955bb7694.

**Pull request closed without merging**
