### PR TITLE
Fixed #25438 -- Fixed assorted Oracle GIS tests failures

### PR DESCRIPTION
**Pull request by jtiai**
Fixed all tests to pass on Oracle. There seems to be some issues with Texas geometry with Oracle and some times apparently SpatiaLite as well.

### CODE REVIEW

**Comment by jtiai** [comment]
buildbot, test on oracle

**Comment by aaugustin** [comment]
Thank you so much for taking care of this :-)

**Comment by timgraham** [comment]
buildbot, test on oracle.

**Comment by timgraham** [comment]
merged in 58379d7e958fdf024f896b86f7df3415ce876200, thanks!

**Pull request closed without merging**
