### PR TITLE
Avoided direct mocking of psycopg2.__version__ in test_correct_extraction_psycopg2_version().

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Review by claudep — APPROVED** [review]
:+1:

**Review by hramezani — APPROVED** [review]
LGTM :+1:

**Review by carltongibson — APPROVED** [review]
OK, I guess... (/me 🤯 with the imports but...)

**Comment by felixxm** [comment]
Thanks for reviews :star2:

**Pull request merged**
