### PR TITLE
[WIP] Add view_decorators list to View

### PR DESCRIPTION
**Pull request by funkybob**
Add an option to the View class to apply decorators to the view function returned by as_view.

[needs docs + tests]

### CODE REVIEW

**Comment by timgraham** [comment]
I didn't check if this API was ever proposed, but I guess 186eb21d allows the use case with some different syntax?

**Comment by funkybob** [comment]
I find using method_decorator clumsy for the general case [of decorating all requests] as:

- it requires importing method_decorator
- it requires writing a `dispatch` just to decorate

In comparison, this will decorate the view function itself [avoiding all the hacks to look inside or carry attributes out], supports multiples trivially, is inheritable/extendable...

I'm ok with it being dismissed... just wanted to get this written down and proposed so I could point people at it for comment.

**Comment by timgraham** [comment]
I would raise it on the mailing list for further discussion.

**Comment by auvipy** [comment]
view decorators would be a good thing

**Comment by timgraham** [comment]
Curtis, could you raise it on the mailing list?

**Comment by timgraham** [comment]
Closing due to inactivity. [django-developers discussion](https://groups.google.com/d/topic/django-developers/kk-zb3cbPtg/discussion)

**Pull request closed without merging**
