### PR TITLE
Fixes #25397 --- Documented shadowing of template variables

### PR DESCRIPTION
**Pull request by jbzdak**
Documented context possible shadowing of context
processor variables by default implementation of get_context_data.

Also converted :: literal blocks to .. code-block:: python
(as in contributor documentation).

### CODE REVIEW

**Comment by jbzdak** [comment]
I'm not entrirely satisfied, it turns out that behaviour of ``get_context_data`` is partially documented in couple different places, I added information to the places I think most people will look first, but still I'd rather keep everything in one place.

**Comment by timgraham** [comment]
Actually literal blocks are preferred in my mind because they do get highlighted as long as there aren't any syntax errors, while code-block will force syntax highlighting even if there are syntax errors. Probably we should revise that suggestion in the contributing docs. In any case, it's better not mix cleanups like that with another ticket.

**Comment by jbzdak** [comment]
Ok, I'll revert that. 

However I found this in the contributing documentation: https://docs.djangoproject.com/en/dev/internals/contributing/writing-documentation/#improving-the-documentation: "Add .. code-block:: <lang> to literal blocks so that they get highlighted." Maybe I misunderstood it?

**Comment by timgraham** [comment]
As I tried to explain, that statement isn't really correct. I'll submit a PR to revise it.

**Comment by jbzdak** [comment]
Now I understand, I'll revert ``.. code-block::`` changes tommorow.

**Comment by aniruddhaadak80** [comment]
Template variable shadowing is a very common trap where local scope incorrectly overrides a global context object. Documenting this makes template debugging way faster for newcomers. Nice addition.

**Pull request closed without merging**
