### PR TITLE
Improve performance of floatformat template filter by using lru_cache

### PR DESCRIPTION
**Pull request by orf**
I noticed this block of code was quite expensive and could be cached quite easily.

Before:
```python
In [1]: from django.template.defaultfilters import floatformat
In [2]: f = 1 / 3
In [3]: %timeit floatformat(f)
19.4 µs ± 2.2 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

After:
```python
In [3]: %timeit floatformat(f)
11.7 µs ± 167 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

Not major, but it adds up if this method is called repeatedly.

### CODE REVIEW

**Comment by sir-sigurd** [comment]
That's not fair benchmark, you should try:
```
%timeit floatformat(random.random())
```

**Comment by orf** [comment]
How come? And wouldn't the overhead of `random.random()` affect the results though? I mean, it's roughly the same speed with `random.random()`:
```
In [7]: %timeit floatformat(random.random())
20.3 µs ± 516 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

But the optimization is to use a cache, in case it's being called repetitively with the same inputs on a page.

**Comment by sir-sigurd** [comment]
> And wouldn't the overhead of random.random() affect the results though?

```
In [19]: %timeit random.random()
94.8 ns ± 1.1 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [20]: %timeit floatformat(1/3)
29.6 µs ± 996 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [22]: (94.8*10**-9) / (29.6*10**-6)
Out[22]: 0.0032027027027027024
```
So overhead could be neglected.

> in case it's being called repetitively with the same inputs on a page.

How common is this case?

**Comment by felixxm** [comment]
Agreed. I don't think it's a common use case.

**Comment by timgraham** [comment]
I'd also agree and say that if this is a bottleneck for a particular project and they know their inputs are such that this will always help and not hinder, they should use a custom template tag.

**Comment by orf** [comment]
Fair enough, I understand. However there is a small code improvement to
remove the multiple calls to append/the while loop that might be worth
including, I will do that as a separate PR if anyone is interested.

**Pull request closed without merging**
