### PR TITLE
Refs #29167 -- Added HashedFilesMixin test for URL with closing parenthesis.

### PR DESCRIPTION
**Pull request by adamzap**
https://code.djangoproject.com/ticket/29167

1. Is this the correct place to test the behavior?
2. Could the commit message be better?

### CODE REVIEW

**Comment by felixxm** [comment]
@adamzap Thanks :+1: 

> 1. Is this the correct place to test the behavior?

Yes.

>   2. Could the commit message be better?

I left suggestion.

**Comment by adamzap** [comment]
@felixxm I updated the commit message. Thanks!

**Comment by adamzap** [comment]
I tested this all the way back to Django v2.0.2, which is the release the bug reporter was probably using, and Python 3.8. I wasn't able to reproduce the bug. In the process, I realized that Django has been skipping the processing of `data:` URLs since 46c12d1293aa90209f3c640f214c4b5a3d6cb9e6. That was well before the version specified on the ticket.

Other than adding named groups, I don't think the regex in question has changed at all since it was initially added in 1d32bdd3c9586ff10d0799264105850fa7e3f512. The ticket is correct in that the regex doesn't match to the final closing parenthesis, but it doesn't need to because `data:` URLs are skipped.

I'm unsure how the bug reporter was able to get unexpected behavior. I doubt that this PR is even needed since there's already an assert for `data:` URLs in the tests, and I wonder if the ticket is even valid.

**Comment by felixxm** [comment]
@adamzap Thanks :+1: Let me double-check it tomorrow.

**Comment by felixxm** [comment]
Closing per ticket.

**Pull request closed without merging**
