### PR TITLE
Fixed #28357 -- Modified JavaScript for prepopulated fields

### PR DESCRIPTION
**Pull request by Zotyamester**
Fixes #28357: The `prepopulated_fields` will work for the extra forms specified, in the admin.StackedInline, but in case of any additional forms that are added via "Add another <Model>" will not run the JS that pre populates the field. admin.TabularInline seems to work fine and is unaffected by this.

### CODE REVIEW

**Comment by felixxm** [comment]
@Zotyamester Thanks for this patch :+1: A regression test is required.

**Comment by Zotyamester** [comment]
Is it okay now? Or should I add more tests?

**Comment by Zotyamester** [comment]
Forgot to commit those. 😅
But here they are now.

**Comment by felixxm** [comment]
Updated in #15091.

**Pull request closed without merging**
