### PR TITLE
Fixed #30680 -- Removed obsolete system check for SECURE_BROWSER_XSS_FILTER setting.

### PR DESCRIPTION
**Pull request by uadnan**
Removes security.W007 check as mentioned here https://code.djangoproject.com/ticket/30680

### CODE REVIEW

**Comment by felixxm** [comment]
@adamchainz I don't think that we need to mention this in the release notes, but agreed we can add sth to a setting description, maybe:
```
Modern browsers don't honor ``X-XSS-Protection`` HTTP header anymore. Although
the setting offers little practical benefit, however you may still want to set
the header if you support older browsers.
```

**Comment by uadnan** [comment]
I agree with @felixxm. Thanks @felixxm for changes

**Comment by MarkusH** [comment]
Should we add a information message to the checks framework that goes off when the settings variable is defined, to inform people that it changed / can be removed?

**Comment by felixxm** [comment]
@MarkusH I don't think so, we removed security checks in the past without such steps (e.g. c27104a9c74bc9d9e552d41f53468b103749e110). Everyone should decide on their own we just do not recommend this anymore as a part of increasing security.

**Comment by adamchainz** [comment]
Agree with @felixxm - if a site has it defined already it's not harming them and may be required by their own security policies. Probably we'll need the setting for another 5 years still...

**Comment by felixxm** [comment]
@uadnan Thanks!

**Pull request merged**
