### PR TITLE
Simplified GIS test by removing unneeded Oracle branch.

### PR DESCRIPTION
**Pull request by sir-sigurd**

### CODE REVIEW

**Comment by sir-sigurd** [comment]
buildbot, test on oracle.

**Comment by sir-sigurd** [comment]
buildbot, test on oracle.

**Comment by timgraham** [comment]
I did a quick check and this prevents a crash on Oracle 11.2 which is still supported by Django. Maybe the skipping logic could use the Oracle version instead?

**Comment by sir-sigurd** [comment]
Could you give details of that crash? If it occurs because the SRID is not supported by Oracle 11.2, I'll change it to the supported one.

**Comment by timgraham** [comment]
Yes, ORA-13199: SRID does not exist.

**Comment by sir-sigurd** [comment]
I was planning to use SRID 3857, but it appeared in 11.2.0.2. Is that OK or this test should work on all versions ≥ 11.2?

**Comment by timgraham** [comment]
The virtual machine I have is 11.2.0.2.0, but I still get a crash with `wgs_pnt = fromstr(sa_4326, srid=3857)` (maybe more places need to be changed). Please don't spend much time on it. At this point, I don't mind if Oracle 11 users report/fix issues as needed since we don't have any formal testing for it.
```
======================================================================
ERROR: test_lookup_insert_transform (gis_tests.geoapp.tests.GeoModelTest)
Testing automatic transform for lookups and inserts.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/tim/code/django/django/db/backends/oracle/base.py", line 477, in execute
    return self.cursor.execute(query, self._param_generator(params))
cx_Oracle.DatabaseError: ORA-29902: error in executing ODCIIndexStart() routine
ORA-13199: SRID does not exist.
ORA-06512: at "MDSYS.MD", line 1723
ORA-06512: at "MDSYS.MDERR", line 17
ORA-06512: at "MDSYS.SDO_CS", line 5264
ORA-06512: at "MDSYS.SDO_CS", line 3034


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tim/code/django/django/test/testcases.py", line 1119, in skip_wrapper
    return test_func(*args, **kwargs)
  File "/home/tim/code/django/tests/gis_tests/geoapp/tests.py", line 113, in test_lookup_insert_transform
    tx = Country.objects.get(mpoly__contains=nad_pnt)
  File "/home/tim/code/django/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tim/code/django/django/db/models/query.py", line 372, in get
    num = len(clone)
  File "/home/tim/code/django/django/db/models/query.py", line 231, in __len__
    self._fetch_all()
  File "/home/tim/code/django/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/tim/code/django/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/home/tim/code/django/django/db/models/sql/compiler.py", line 829, in execute_sql
    cursor.execute(sql, params)
  File "/home/tim/code/django/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/tim/code/django/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/tim/code/django/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/tim/code/django/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/tim/code/django/django/db/backends/oracle/base.py", line 477, in execute
    return self.cursor.execute(query, self._param_generator(params))
django.db.utils.DatabaseError: ORA-29902: error in executing ODCIIndexStart() routine
ORA-13199: SRID does not exist.
ORA-06512: at "MDSYS.MD", line 1723
ORA-06512: at "MDSYS.MDERR", line 17
ORA-06512: at "MDSYS.SDO_CS", line 5264
ORA-06512: at "MDSYS.SDO_CS", line 3034
```

**Comment by sir-sigurd** [comment]
You placed `3857` in the wrong place. I updated PR to use SRID 3857. If it will fail on your VM, then I will make skipping logic use the Oracle version.

**Pull request merged**
