### PR TITLE
Fix #26975: clarify use of paths with loaddata and how to namespace fixture files

### PR DESCRIPTION
**Pull request by ancientHacker**
- Explain the different effects of relative and absolute paths on loaddata.
- Suggest that fixture files be namespaced, which makes the documentation for fixtures consistent with that for templates and static files.

### CODE REVIEW

**Comment by timgraham** [comment]
This seems to be headed down the path of duplicating https://docs.djangoproject.com/en/1.9/ref/django-admin/#what-s-a-fixture. I always thought it was awkward to put that extensive discussion of fixtures on the django-admin page. Maybe we could move it here instead?

**Comment by ancientHacker** [comment]
Tim, thanks for the feedback, and thanks for pointing me to that material on the admin page!  I have searched the docs many times for info about fixtures and that page has never come up high enough on the search rankings for me to see it, so I suspect that consolidating that material away from the rest of the admin stuff will make also it much easier to find.

I am happy to take a shot at what you suggest, but I would like your opinion on approach first.  The material on the ref/admin page seems to me to be way more detailed and, well, "ref-like" than the material usually found on howto pages.  I notice that there is no ref page on fixtures (and have always wondered why).  Do you think it would sense for me to make a ref/fixtures page, collect all the reference material on fixtures on that page, and reference it from both the howto/fixures and ref/admin pages?

**Comment by timgraham** [comment]
Sure, we could see what a new page looks like. Putting it in topics/ rather than ref/ seems like a better fit.

**Comment by timgraham** [comment]
Please send a new PR if you return to this.

**Pull request closed without merging**
