### PR TITLE
Fixed #27931 -- Clarified meaning of django catch-all logger.

### PR DESCRIPTION
**Pull request by vkaracic**
Two different commits with two different approaches, I prefer the second one.
https://code.djangoproject.com/ticket/27931

### CODE REVIEW

**Comment by timgraham** [comment]
I think the place to clarify is earlier on the page: "django is the catch-all logger. No messages are posted directly to this logger." Later on, text like "The ``django`` catch-all logger" could link to that section.

I don't think the example you added is particularly helpful. That isn't really the important case -- it receives messages from all child logger (e.g. django.request) that don't have loggers setup.

**Comment by timgraham** [comment]
@vkaracic, do you want to try to revise this?

**Comment by vkaracic** [comment]
Oh yes, sorry! I'll work on it in the beginning of the next week. If that's OK?

**Comment by timgraham** [comment]
I guess since you deassigned yourself from the ticket that means you won't be continuing this.

**Pull request closed without merging**
