### PR TITLE
Conversion of many tests to SimpleTestCase.

### PR DESCRIPTION
**Pull request by charettes**
This builds on top of #4522.

I plan to squash all commits if required, it was just easier working this way.

### CODE REVIEW

**Comment by charettes** [comment]
Note that I used [this poorly written stashed patch](https://gist.github.com/charettes/37d3be452deb3232851a) to detect possible candidates and I might have missed some.

While this doesn't makes a big speed-up difference on in memory SQLite and PostgreSQL I assume it should make one on databases that don't have fast transaction support.

**Comment by charettes** [comment]
Buildbot test on Oracle.

**Comment by timgraham** [comment]
buildbot, test on oracle.

**Comment by timgraham** [comment]
Unfortunately, no measurable speedup on Oracle in my testing.

**Comment by charettes** [comment]
Do you think it's still worth merging in this case? I guess we still make sure no queries are executed during those tests.

**Comment by timgraham** [comment]
I would still merge it after squashing all the "Used SimpleTestCase....".

**Comment by charettes** [comment]
Squashed all commits, will merge if tests still pass.

**Pull request merged**
