### PR TITLE
Refs 34343 -- Removed outdated comment about inline template from CSRF view file.

### PR DESCRIPTION
**Pull request by adamchainz**
Outdated since the template was moved in ticket-34343 / #16562.

### CODE REVIEW

**Comment by adamchainz** [comment]
@ngnpope

**Review by ngnpope — APPROVED** [review]
Thanks! Missed that.

**Review by nessita — APPROVED** [review]
LGTM

**Comment by felixxm** [comment]
`#` is missing in the commit message `Refs #34343 -- ...`

**Pull request merged**
