### PR TITLE
Various fixes to `django.contrib.gis.geoip2`.

### PR DESCRIPTION
**Pull request by ngnpope**
@orf Here's an initial follow up to https://github.com/django/django/pull/14215#issuecomment-813108040.

I noticed that we don't seem to run any coverage on Jenkins for much of the gis stuff. When I did so locally I found that there were a few bits of dead code and that there is a lot of code smell and oversights in this wrapper layer. We also leak exceptions from the underlying library, e.g.`geoip2.errors.AddressNotFoundError`. I've clean some things up, but there are other oddities such as `_reader` vs `_country_or_city` - I think we should prefer the information from the city database over the country database if it is available.

A part of me wonders whether we should just deprecate `django.contrib.gis.geoip2` and advise use of `geoip2` directly. It has a nice API and certain features are inhibited by this wrapper, e.g. locales. (Even if we decide to do that, we can still tidy up in the interim.)

Closes django/django-docker-box#14

### CODE REVIEW

**Comment by felixxm** [comment]
@ngnpope Thanks :+1: I moved some of those cleanups to a separate PR #15146, please rebase.

**Comment by ngnpope** [comment]
> @ngnpope Thanks 👍 I moved some of those cleanups to a separate PR #15146, please rebase.

Thanks. 🏅

Will have a look at this next week.

**Comment by felixxm** [comment]
@ngnpope Do you have time to keep working on this?

**Comment by ngnpope** [comment]
I did continue with this, but now it needs a post-black rebase and a couple of test tweaks. It is slowly progressing, I promise! 😅

**Comment by felixxm** [comment]
Closing due to inactivity.

@ngnpope  Feel-free to send a new patch when you have time, thanks.

**Pull request closed without merging**
