### PR TITLE
Disabled auto-created table of contents entries on Sphinx 5.2+.

### PR DESCRIPTION
**Pull request by felixxm**
Auto-created table of contents entries for all domain objects (e.g. functions, classes, attributes, etc.) were added in Sphinx 5.2, see https://github.com/sphinx-doc/sphinx/issues/6316.

An option to control new table of contents entries was added in Sphinx 5.2.3, see https://github.com/sphinx-doc/sphinx/pull/10886.

----
`toc_object_entries = True` (default):

image
----
`toc_object_entries = False`:

image

### CODE REVIEW

**Comment by smithdc1** [comment]
Worth bumping the required version?

https://github.com/django/django/blob/main/docs/requirements.txt

**Comment by felixxm** [comment]
> Worth bumping the required version?

For now, I'm not sure what else the Sphinx 5+ can surprise us, and we cannot bump without checking docs for Django 3.2, 4.0,  and 4.1 (see #15746).

**Review by claudep — APPROVED** [review]
Looks like the right thing to do, obviously!

**Review by pauloxnet — APPROVED** [review]

**Comment by felixxm** [comment]
Thanks :+1:

**Pull request merged**
