### PR TITLE
Fixed #31596 -- Changed ForeignKey.validate() to use the base manager.

### PR DESCRIPTION
**Pull request by jdufresne**
https://code.djangoproject.com/ticket/31596

### CODE REVIEW

**Comment by charettes** [comment]
Not sure we should allow this, `ForeignKey.formfield` passes along `_default_manager` and not `_base_manager`.

https://github.com/django/django/blob/59c19c372352441c2a0082703351032b38cd87a6/django/db/models/fields/related.py#L987

Wouldn't this allow users to submit disallowed values?

e.g.

```python
class Note(models.Model):
    deleted_at = models.DateTimeField(null=True)
    objects = Manager().filter(deleted_at=null)

class Something(models.Model):
    note = models.ForeignKey(Note)
```

A `ModelForm` generated for `Something` would only display non-deleted `Note` as choices but allow any value to be submitted.

I think what we need is a larger solution that allows specifying a manager in `ForeignKey` and I know there are tickets for that.

**Comment by jdufresne** [comment]
> A ModelForm generated for Something would only display non-deleted Note as choices but allow any value to be submitted.

No, this isn't the case. The value submitted would be validated by the queryset passed to `ModelChoiceField`. In the default case, that is the default manager, in the overridden case, it is the overridden queryset. I can try to get this represented in a test case if you'd like.

**Comment by jdufresne** [comment]
> I think what we need is a larger solution that allows specifying a manager in ForeignKey and I know there are tickets for that.

I'm unclear how this would solve my use case.

I like that ForeignKey uses the base manager. This allows normal code (non-form code) to save the relationship to the archived instance.

I also like that the default behavior of the model forms is to use the `_default_manager` to calculate choices. I think it makes a lot of sense in the default scenario. In the example, I don't think the archived relationships should show by default.

However, my use case is the non-default scenario. When I purposely override the queryset/choices in the model form, I expect those choices to be valid. Right now, the form validation considers them valid, but the model validation does not. This fixes that scenario.

**Comment by jdufresne** [comment]
I added the test `test_validate_foreign_key_uses_default_manager` in a fixup commit. This shows that the default model  form (no overridden queryset) still validates based on the default manager.

**Comment by charettes** [comment]
Thanks for the clarifications and the extra test John.

I did a bit of searching and I can't find the discussion I was referring to WRT to allowing a manager to be specified for a particular foreign key but it revolved around work done for https://github.com/django/django/pull/6175.

In all cases since both `ForeignKey` and `OneToOneField` forward and reverse descriptors use `_base_manager` (while forward and reverse `ManyToMany` use `_default_manager`) I guess this is more coherent. It will still be a bit more lax for users who were solely relying on the model level validation so it might be worth a note in the release notes.

I guess `ManyToManyField` doesn't have this problem because it does not implement any form of model level validation while `ForeignKey` does.

**Comment by jdufresne** [comment]
> so it might be worth a note in the release notes.

Good call, can do.

---

This process had me thinking, what use case is `ForeignKey.validate()` solving that is not already handled by `ModelChoiceField` validation? When a model is used, it seems to me the exact same validation is done twice:

1. `ModelChoiceField`: does the value exist in the given queryset (defaults to `_default_queryset`)?
2. `ForeignKey.validate()`: does the value exist in the `_default_queryset`?

Is is common to call model validation without using a form? I don't do so in my projects, but perhaps other projects do.  Maybe it would make sense to deprecate and drop `ForeignKey.validate()`, any thoughts on this?

**Comment by jdufresne** [comment]
>> so it might be worth a note in the release notes.

> Good call, can do.

Done in the latest fixup commit.

**Comment by carltongibson** [comment]
Oops. I pushed the wrong thing here. follow up in #13109

**Comment by ivanbrizuela** [comment]
> Is is common to call model validation without using a form?

I do call `full_clean()` on model instances without using forms, prompting validation.

With regard to this change, I added a comment on the original ticket:
https://code.djangoproject.com/ticket/31596#comment:10

This change introduced in `3.2` breaks working code that expects the _default_manager to be used when validating `ForeignKeys` defined with a proxy model class.

And I think that this reduces the value of proxy models, without any obvious improvement.

**Pull request closed without merging**
