### PR TITLE
Refs #373 -- Fixed CompositePKChecksTests.test_composite_pk_cannot_include_generated_field() test on databases with no GeneratedField support.

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Review by charettes — APPROVED** [review]

**Comment by charettes** [comment]
Curious to see what the crash looks like given the database model is never actually created.

Was it instead failing with `fields.E220`?

https://github.com/django/django/blob/3d819e23240ab6f903eb60d76237628981fd52b5/django/db/models/fields/generated.py#L131-L137

**Comment by felixxm** [comment]
> Curious to see what the crash looks like given the database model is never actually created.
> 
> Was it instead failing with `fields.E220`?
> 
> https://github.com/django/django/blob/3d819e23240ab6f903eb60d76237628981fd52b5/django/db/models/fields/generated.py#L131-L137

Removed `crash` in the commit message  :wink: All depends on what is supported by the database, it could contain `fields.E221`, `fields.E222`, or `fields.E220`.

**Review by csirmazbendeguz — APPROVED** [review]
Thanks!

**Review by sarahboyce — APPROVED** [review]
Thank you!

**Pull request merged**
