### PR TITLE
Fixed #25191 -- Better error output for assertXMLEqual

### PR DESCRIPTION
**Pull request by caioariede**
https://code.djangoproject.com/ticket/25191

### CODE REVIEW

**Comment by timgraham** [comment]
Could you please try to add a test similar to 1c7c782d6e7cdce09a982f05d468d538698c3004?

**Comment by timgraham** [comment]
buildbot, add to whitelist.

**Comment by caioariede** [comment]
Test added

**Comment by timgraham** [comment]
Merged in 62d4074005f68328b240ab5f4fdfe348896717da, thanks!

**Pull request closed without merging**
