### PR TITLE
Fixed #28316 -- Fixed ModelChoiceField with to_field_name pointing to non-primary key.

### PR DESCRIPTION
**Pull request by karolyi**
https://code.djangoproject.com/ticket/28316

### CODE REVIEW

**Comment by karolyi** [comment]
Will provide test soon ... just want to see if the full testsuite goes through.

**Comment by karolyi** [comment]
Referencing djangoproject ticket: https://code.djangoproject.com/ticket/28316

**Comment by timgraham** [comment]
@karolyi, will you continue this?

**Comment by karolyi** [comment]
I will (got really busy lately). I'd keep the tests as they were in my version, because they provide a better understanding on why having the patch is important.

**Comment by timgraham** [comment]
I like to avoid comparisons of rendered HTML -- they are verbose and difficult to debug. That's why I prefer to use the same approach as in 81963b37a92ef583b9f725f1a78dd2ca97c1ab95.

**Comment by karolyi** [comment]
Ah yes, I will skip the HTML comparison, but I saw you rewrote the tests to test the input-output of the `ModelChoiceField` whereas I would still test with a form to sort of 'explain' why we have that functionality added to it.

**Comment by timgraham** [comment]
I guess I'll have to see the diff of your proposal to understand. What I've written works as a regression test so it seems sufficient to me.

**Comment by karolyi** [comment]
closing this, will open a new PR after having my fork updated (don't want to contaminate this PR with the updates of my fork)

**Pull request closed without merging**
