### PR TITLE
Changed the screenshots Github workflow to run in the PR's branch by using pull_request as event trigger.

### PR DESCRIPTION
**Pull request by knyghty**
In debugging #17518 we discovered screenshots added in a PR weren't being run because `pull_request_target` runs against the target branch (main), not the PR. This means any new screenshots added in the PR don't show up, and worse, the screenshots show the results from the main branch, not the PR branch. So we fix this by changing to `pull_request`. However,  this does break the comments.

It might be possible to get the comments working in some way, but it doesn't seem trivial.

### CODE REVIEW

**Comment by knyghty** [comment]
@sarahboyce do you have any thoughts?

**Review by sarahboyce — APPROVED** [review]
I think this is the right decision 

The permissions makes the GitHub comment not possible when running against the fork's branch and although this is theoretically possible, the amount of code to achieve this is horrible 👍

**Review by nessita — APPROVED** [review]
I have confirmed and suffered from this as well, merging.

**Comment by felixxm** [comment]
`pull-requests: write` is probably no longer necessary.

**Comment by nessita** [comment]
> `pull-requests: write` is probably no longer necessary.

Good point, it seems like the whole `permissions` section could be removed? @knyghty thoughts?

**Comment by knyghty** [comment]
I think that's right but it's easy enough to test

**Comment by knyghty** [comment]
I opened https://github.com/django/django/pull/17603 to test.

**Pull request merged**
