### PR TITLE
Added autoreload_stopping Signal to complement autoreload_started

### PR DESCRIPTION
**Pull request by lbt**
During development apps may need to clean up before the sys.exit()

First code patch so AUTHORS ammended as requested. CLA sent.

### CODE REVIEW

**Comment by lbt** [comment]
OK - although it's a feature it was so trivial to implement and seemed, at face value, so aligned with the existing design, that it seemed sensible to just submit a PR to discuss if needed - and now it appears that it is needed :)

Some points:
* This is very much a "developer-only" change so the use cases here are related to situations which may not even make it into a production system
* There is an existing "started" Signal() so this seemed a reasonable complement to it and is not introducing Signals where they had not been used before

My use case is actually this pseudo-snippet in apps.py:
```
   if os.environ.get("RUN_MAIN") == "true":
            self._mqtt_thread = self.start_db_mqtt()
            autoreload_stopping.connect(self.stop_db_mqtt)
```

Without this clean stop the mqtt thread does not die and I lose autoreload functionality

**Comment by felixxm** [comment]
> There is an existing "started" Signal() so this seemed a reasonable complement to it and is not introducing Signals where they had not been used before

There is a big difference as `started` is used by Django itself.

**Comment by lbt** [comment]
Hmmm @felixxm 
So you're saying "when we needed this internally it was OK to use Signals but when a user would like to do something very similar it's not OK"?

Are you not actually making the point that it is a reasonable, existant and approved solution to the kind of "at a distance" problems that autoloading introduces ;) 

I do understand that Signals are questionable in many situations (and I have used them and later refactored to remove them) but here I think we're talking about asking the Django autoloader to politely say "I'm about to kill you" and giving the developer a chance to clean up rather than just doing a hard exit.

The autoloader code is complex and I read up a little on the history and difficulties associated with it so I a understand a reluctance to mess with it. Sometimes those complexities do extend into the developers world and this seems like a reasonable and fairly clean way to allow some pre-termination cleanup.

PS Is it appropriate that this discussion is happening here? I'm just unsure if I should be doing a feature request or something else as @carltongibson mentioned?

**Comment by carltongibson** [comment]
@lbt The best place is the Django Internals channel of the Forum. 

As I say, it's quite unlikely that there will be agreement to add a signal here. You will need to explain very clearly (and for folks who don't have your project running in front of them) why this can't be don't another way. 

The general take is, something like, that it's OK to use signals when there's no other option. But you've not demonstrated that (at all) — so explaining that clearly would be the first step to bringing folks along with you. 

Sorry if that seems a burden, but we try to work by consensus, and it's usually the case that things that haven't gone for many years without being needed, turn out not to be. 

I hope that makes sense.

**Comment by lbt** [comment]
It absolutely makes sense ... I am trying to make reasoned arguments and to respond to objections but it helps if I'm making them in the right place and to the right people. I'll go to the Forum.

I will say first that if broadcasting to any code that might want to hear "I'm about to randomly sys.exit()" isn't a reasonable use of the Signal() paradigm then I'm not sure what is!

And yes I realise that this is happening because I'm doing something odd with threads and MQTT/django and I will end up in Channels and workers sooner rather than later - but I need to iterate my way there and this would help.

**Comment by lbt** [comment]
Just for reference: Ticket @ https://code.djangoproject.com/ticket/34432

Conversation moved to:
https://forum.djangoproject.com/t/id-like-to-add-an-autoreload-stopping-signal-to-the-autloloader/19741

**Pull request closed without merging**
