### PR TITLE
Used more specific unittest assertions in tests.

### PR DESCRIPTION
**Pull request by pope1ni**
Improvements to choice of assertion methods highlighted by [flake8-assertive](https://pypi.org/project/flake8-assertive/).

### CODE REVIEW

**Comment by pope1ni** [comment]
buildbot, test on oracle.

**Comment by pope1ni** [comment]
So I expected `null_ok` in cursor `.description` rows to be one of `True`, `False`, or `None`.

It looks as though MariaDB/MySQL return `0` or `1` for this field, however. I'm just checking what happens for Oracle. I don't know whether we'd prefer to standardize this to real booleans or whether we want to keep allowing truthy/falsy values.

**Comment by pope1ni** [comment]
buildbot, test on oracle.

**Comment by pope1ni** [comment]
@carltongibson @felixxm This one is ready for review. (Test failure is unrelated.)

**Comment by felixxm** [comment]
@pope1ni Thanks!

**Comment by pope1ni** [comment]
@felixxm Aww... I guess I'm not allow to get my commit count up that way... :stuck_out_tongue_closed_eyes:

**Pull request merged**
