### PR TITLE
Fixed #24581 -- Added an exception when ManyToManyField._get_m2m_attr() fails to match

### PR DESCRIPTION
**Pull request by patrys**
This fixes https://code.djangoproject.com/ticket/24581

### CODE REVIEW

**Comment by timgraham** [comment]
Re: testing, if it's difficult to trigger indirectly, how about calling the private method with an invalid `attr`?

Please follow the commit message guidelines from the [patch review checklist](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/submitting-patches/#patch-review-checklist). Thanks!

**Comment by patrys** [comment]
@timgraham: unfortunately it only fails when called on an invalid relationship, it works properly when you ask for an invalid attribute of a valid relationship.

**Comment by patrys** [comment]
@timgraham I've added a test case that explicitly creates a broken relation.

**Comment by timgraham** [comment]
In case you didn't notice, some tests are failing.

**Comment by patrys** [comment]
I did! I apologize for the delay but work has prevented me from picking this during the week.

**Comment by timgraham** [comment]
Closing due to inactivity.

**Pull request closed without merging**
