### PR TITLE
Marked protected error message for translation

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
I think that string might be user visible, so translation would be nice. I can open a ticket if you think it deserves it.

**Comment by charettes** [comment]
Are you sure it's user visible? The [admin discards the message](https://github.com/django/django/blob/e4df8e6dc021fa472fa77f9b835db74810184748/django/contrib/admin/utils.py#L182) and since it subclasses `IntergrityError` it usually results in a 500 if not handled.

I think we'd need to figure out in which cases it's presented to a user before marking the string for translation.

**Comment by claudep** [comment]
Oh, I see now, in the project I encountered this, the protected error message was forwarded to a user message in a view. It might not be the best idea, but does it hurt to have it translated for such corner cases?

**Comment by charettes** [comment]
Well the message seems to be oriented towards developers and not users. For example it uses the model class and field name (not their verbose one) and the technical term such as `model` and `foreign key`.

**Comment by claudep** [comment]
You are probably right, thank you for your time.

**Pull request closed without merging**
