### PR TITLE
Refs #26167 -- Changed default value of DatabaseFeatures.supports_expression_indexes to True.

### PR DESCRIPTION
**Pull request by hannseman**
cc @timgraham

### CODE REVIEW

**Comment by felixxm** [comment]
I agree with Tim, let's change defaults to `True` and document both feature flags.

**Comment by timgraham** [comment]
If `collate_as_index_expression` applies to a minority of databases, I'd leave the default as `False`.

**Comment by hannseman** [comment]
> If collate_as_index_expression applies to a minority of databases, I'd leave the default as False.
 
Makes sense. I'll fix it.

**Review by felixxm — APPROVED** [review]
@hannseman Thanks :+1:

**Comment by hannseman** [comment]
@timgraham thanks for the report, @felixxm thanks for the review! 👍

**Pull request merged**
