### PR TITLE
Refs #26167 -- Added Expression.ordered attribute.

### PR DESCRIPTION
**Pull request by felixxm**
See [discussion](https://github.com/django/django/pull/11929#discussion_r458587537).

### CODE REVIEW

**Comment by felixxm** [comment]
buildbot, test on oracle.

**Review by hannseman — COMMENTED** [review]
Sweet!

Last time I looked at this I also found these usages of `isinstance(.., OrderBy)`:

https://github.com/django/django/blob/e74b3d724e5ddfef96d1d66bd1c58e7aae26fc85/django/contrib/admin/checks.py#L566
https://github.com/django/django/blob/b203ec70fd7ffc4027380940157d1cf9c9e588ad/django/contrib/admin/views/main.py#L319
https://github.com/django/django/blob/b203ec70fd7ffc4027380940157d1cf9c9e588ad/django/contrib/admin/views/main.py#L416

**Comment by felixxm** [comment]
@hannseman Thanks :+1: I forgot to check `contrib` apps.

**Review by hannseman — APPROVED** [review]
Thanks!

**Comment by felixxm** [comment]
@charettes Do you want to take a look?

**Comment by charettes** [comment]
After looking at https://github.com/django/django/pull/11929#pullrequestreview-542260861 in more details it's not clear to me if this is even required. If we really want to get #11929 through before the feature freeze would we be opposed to remove this property is a _cleaner_ approach is implemented before the release?

I really think we should introduce `django.contrib.postgres.indexes.OpClass` at least and find a way to generate expressions that are simple compileable from `IndexExpressions`'s perspective.

**Comment by felixxm** [comment]
Agreed, let's close it for now. Thanks both :+1:

**Pull request closed without merging**
