### PR TITLE
Added missing arabic characters in admin's urlify.js.

### PR DESCRIPTION
**Pull request by Bashar**
Added more arabic characters from the base arabic letters, i skipped letters like پ and چ as they are not native arabic characters but Farsi/Urdu ones but uses arabic script but not arabic letters

### CODE REVIEW

**Comment by RamezIssac** [comment]
Include ء, ئ ?
Also I'm not sure about ﻻ and its variations if it is it naturally broken to ل & ا or not. if not, i think better to include them too.
Is there a ticket for this pull ?

Regards;

**Comment by Bashar** [comment]
@RamezIssac 
> Include ء, ئ ?
good idea

> Also I'm not sure about ﻻ and its variations if it is it naturally broken to ل & ا or not. if not, i think better to include them too.
These are not single letters better to keep them for merging rather than considering them as single letter which i see a bug on some android/samsung keyboards

> Is there a ticket for this pull ?
Ticket where? haven't opened any :) is that a usual process for such PRs?

**Comment by timgraham** [comment]
A ticket probably isn't needed as long as both of you can agree on the changes.

**Comment by Bashar** [comment]
@timgraham since two letters need to be added, shall i edit this PR (if possible?) or close it and submit newer one? :) Thanks

**Comment by RamezIssac** [comment]
I think you'll find https://docs.djangoproject.com/en/1.8/internals/contributing/writing-code/working-with-git/ helpful.

**Comment by timgraham** [comment]
Reminder about this. If you have trouble editing the PR, just add a comment and I'll edit the commit when merging. Thanks!

**Comment by timgraham** [comment]
Closing due to inactivity. Please send a pull request against master if you can update it. Thanks!

**Pull request closed without merging**
