### PR TITLE
[WIP] Fixed #28053 -- Support db_index=Index()

### PR DESCRIPTION
**Pull request by cansarigol**
Ticket: [#28053](https://code.djangoproject.com/ticket/28053)
this PR is the continuation of @mjtamlyn's [PR](https://github.com/django/django/pull/8322). First commit mostly from there. an effort to understand the subject.

### CODE REVIEW

**Comment by cansarigol** [comment]
I tried to add a control for  `instance of Index` in [https://github.com/django/django/pull/11264/commits/37c3a3378bd08c209750d5574edb3a950c78bd8a](this commit)

> Questions:
> Should we be more careful about setting Index.fields()? Do we need to verify that it only affects this field, or that no fields should be permitted on init when it's a db_index? How does this fit with indexes taking expressions?

**Comment by auvipy** [comment]
good progress!

**Comment by cansarigol** [comment]
> Looks great so far. please rebase when you push again.

thanks, I did.

**Comment by felixxm** [comment]
buildbot

**Comment by auvipy** [comment]
IMHO you should focus most of your time on this one :) I can foresee you as a prospective django core team member in near future.

**Comment by auvipy** [comment]
I think the postgresql failures are due to merge conflict?

**Comment by cansarigol** [comment]
thanks @auvipy I will focus on this. this topic is very detailed and instructive for me. Thanks for your foresee again.

**Comment by cansarigol** [comment]
I couldn't reproduce this error. tried to run all tests with tox and django-box but couldn't see any error like it. help would be nice.

**Comment by auvipy** [comment]
might be a network issue?

**Comment by cansarigol** [comment]
I don't think so, my changes cause this problem but I couldn't detect it. I suspect runtests_jenkins.sh, I'm not sure it could be because don't know the contents.

**Comment by auvipy** [comment]
are you planning to handle this anytime soon?

**Comment by cansarigol** [comment]
Hi nowadays, I can't find any time to pursue this.

**Comment by felixxm** [comment]
Closing due to inactivity.

**Pull request closed without merging**
