### PR TITLE
Forms: specify which file contains example code.

### PR DESCRIPTION
**Pull request by eest**
From my beginner perspective it is not obvious where form code should be placed. Some googling suggests it belongs in forms.py. This PR attempts to make that clear.

### CODE REVIEW

**Comment by timgraham** [comment]
merged in f9c212d09ad59cd5b5d9be06e92be87d44c75d95, thanks.

**Comment by eest** [comment]
@timgraham: any reason f9c212d adds the line "from .forms import NameForm" instead of the "from myapp.forms import NameForm" that i used in my commit?

**Comment by timgraham** [comment]
Explicit relative imports are generally preferred these days. Feel free to update other areas of the docs in this regard you like. I updated the tutorial a couple weeks ago.

**Comment by eest** [comment]
@timgraham: thank you for the info :).

**Pull request closed without merging**
