### PR TITLE
Fixed #32649 -- Fixed ModelAdmin.search_fields crash when searching against phrases with unbalanced quotes.

### PR DESCRIPTION
**Pull request by felixxm**
Thanks Dlis for the report.

Regression in 26a413507abb38f7eee4cf62f2ee9727fdc7bf8d.

ticket-32649

### CODE REVIEW

**Comment by felixxm** [comment]
@dlis Can you confirm that it works for you?

**Review by carltongibson — APPROVED** [review]
OK, makes sense. Thanks! 

Do you think the single quote case is worth adding? :

```
diff --git a/tests/admin_views/tests.py b/tests/admin_views/tests.py
index e197a3a690..4ec1c90349 100644
--- a/tests/admin_views/tests.py
+++ b/tests/admin_views/tests.py
@@ -3648,6 +3648,7 @@ class AdminSearchTest(TestCase):
             ("John Doe John", 0),
             ('"John Do"', 1),
             ("'John Do'", 1),
+            ("'John O\'Hara'", 0),
             ("'John O\\'Hara'", 1),
             ('"John O\"Hara"', 0),
             ('"John O\\"Hara"', 1),
```

**Comment by felixxm** [comment]
@carltongibson Thanks for checking :+1: 

> Do you think the single quote case is worth adding? :

Yes, added.

**Comment by dlis** [comment]
> @dlis Can you confirm that it works for you?

I replaced "django" with "git+https://github.com/django/django@refs/pull/14262/merge#egg=django", disabled our temporary fix, whereupon the bug disappeared. Thanks!

**Comment by felixxm** [comment]
@dlis Thanks for checking :+1:

**Pull request merged**
