### PR TITLE
Fixed #32456 -- Added dbshell support for specifying a password file on PostgreSQL.

### PR DESCRIPTION
**Pull request by hramezani**
https://code.djangoproject.com/ticket/32456

### CODE REVIEW

**Review by recepsirin — APPROVED** [review]

**Comment by felixxm** [comment]
@recepsirin Please stop approving all PRs without checking anything, it's not helpful and adds unnecessary notifications for people watching this repository.

**Review by felixxm — COMMENTED** [review]
@hramezani Thanks :+1:

I would also remove `password` from a [`.pg_service.conf` example](https://docs.djangoproject.com/en/dev/ref/databases/#postgresql-connection-settings) and add and example of the password file.

**Comment by felixxm** [comment]
I've noticed a separate issue blocking this change, see [coment](https://code.djangoproject.com/ticket/32292#comment:14).

**Comment by felixxm** [comment]
I pushed docs changes.

**Comment by hramezani** [comment]
> I pushed docs changes.



> I pushed docs changes.

@felixxm 
Sorry for being late :man_facepalming:  I am busy these days.
Thanks for your help and support like always :+1:

**Pull request merged**
