### PR TITLE
Fixed #28885 -- Allowed footer of "Congratulations!" page to expand according to the height of content.

### PR DESCRIPTION
**Pull request by h-chauhan**
https://code.djangoproject.com/ticket/28885

### CODE REVIEW

**Comment by carltongibson** [comment]
This looks good to me. 

From current `master`:

without-patch

With patch applied: 

with-path

(Both these showing the "Tutorial: A Polling App" option with the Russian localisation.) 

Other layout, including resizing behaviour, is (essentially) unchanged.

**Comment by carltongibson** [comment]
I'm going to mark this as ready to commit. Assuming @h-chauhan submitted the CLA, we should be able to adjust the commit message when merging.

**Comment by h-chauhan** [comment]
I am new here, so sorry about the long commit message. Yes, I have submitted the CLA.

**Comment by carltongibson** [comment]
@h-chauhan No need to apologise! 🙂 Thank you for your input!

**Comment by timgraham** [comment]
It could go either way but I'd expect the gray text to be aligned under the green text rather than flowing below the icon. \cc @FlipperPA

**Comment by carltongibson** [comment]
> ... gray text to be aligned under the green text rather than flowing below the icon

That would be possible: 

```
<div class="option two">
  <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
    <path d="M0 0h24v24H0V0z" fill="none"></path>
    <path d="M9.4 16.6L4.8 12l4.6-4.6L8 6l-6 6 6 6 1.4-1.4zm5.2 0l4.6-4.6-4.6-4.6L16 6l6 6-6 6-1.4-1.4z"></path>
  </svg>
  <h4>Руководство: Приложение для голосования</h4>
 <p>Начало работы с Django</p>
</div>
```

If the `svg` was made a background image and then left padding on the `div` to move the `h4` and `p` in from that...

It's a bit more work. @h-chauhan What do you think?

**Comment by h-chauhan** [comment]
Yeah, I got your point. Okay, I'll do that.

**Comment by h-chauhan** [comment]
I have updated the commit. Now the gray text is aligned with the green text.
screenshot from 2018-01-12 10-28-08

**Comment by timgraham** [comment]
Adding non-semantic `<div>`s doesn't look so nice, but if nobody wants to try to find a solution without them, we can go with this, I guess.

**Comment by FlipperPA** [comment]
We got started on a fix for this, but my colleague with UI skills got pulled on a high priority project which has him busy. We will revisit once he gets some cycles. Thanks for the fix in the meantime! @chadwhitman

**Pull request merged**
